### ISSUE TITLE
Typo "Detschlands"

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1001]
## Where to find the issue

https://github.com/corona-warn-app/cwa-website/blob/10c9b616aa0119fee8be69d5f3b1620bbb468292/src/data/faq_de.json#L416

## Describe the issue

Typo "Detschlands"

This one instance in Line 416 was missed by PR https://github.com/corona-warn-app/cwa-website/pull/999.

## Suggested change

Change "Detschlands" => "Deutschlands"

**Comment by dsarkar** [comment]
@MikeMcC399 thanks.
