### ISSUE TITLE
BReg FAQ: Phone number for technical hotline national / international

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1003]
## Where to find the issue

Corona-Warn-App FAQ website hosted by the Bundesregierung:
- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392 (German)<br>Stand: ~~Mittwoch, 24. März 2021~~
~~Mittwoch, 21. April 2021~~
~~Montag, 3. Mai 2021~~
Mittwoch, 12. Mai 2021
- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636 (English)<br>Stand: ~~Wednesday, 24. März 2021~~
~~Wednesday, 21. April 2021~~
Monday, 3. May 2021

## Describe the issue

The CWA app's FAQ website has not taken account of the changes to the Corona-Warn-App telephone hotlines.
The technical hotline is listed as **+49 800 754 000 1**.

The Corona-Warn-App technical hotline should be listed as:
- 0800 7540001 when called from Germany or 
- +49 30 498 75401 when called from outside Germany.

![BRegPhoneENDE](https://user-images.githubusercontent.com/66998419/111687956-363ef900-882b-11eb-87b8-6d8dccb0b4bc.jpg)

## Suggested change

The FAQ of the Bundesregierung on:

- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392 (German) and
- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636 (English).

should align to the information published on the app's technical FAQ website:

https://www.coronawarn.app/en/faq/#who_can_help
The technical hotline (telephone 0800 7540001) will help you with technical questions about the Corona-Warn-App, for instance if you have problems with risk identification. You can reach the technical hotline from Monday to Saturday from 7 a.m. to 10 p.m. (except on German public holidays), and it is free of charge for you within Germany.

The TAN hotline (telephone 0800 7540002) will help you to enter the TAN if you have a positive test result and if you have not received a TAN or document with a QR code. The TAN hotline is available 24 hours a day, seven days a week. The call is free of charge.

https://www.coronawarn.app/en/faq/#international_phone_numbers
From abroad you can reach us at the following international phone numbers:

Technical hotline: +49 30 498 75401 available Monday to Saturday from 7 a.m. to 10 p.m. German local time (except on national holidays)

TAN hotline: +49 30 498 75402 available 24 hours a day, seven days a week

Note: These numbers are not free of charge - the cost of the international call is based on the contract with your provider.

---
Internal Tracking ID: [EXPOSUREAPP-5906](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5906)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal Tracking ID: [EXPOSUREAPP-5906](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5906)

**Comment by MikeMcC399** [comment]
The Corona-Warn-App FAQ website hosted by the Bundesregierung:
- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392 (German)

has already been updated three times since this issue was logged (Mittwoch, 24. März 2021, Mittwoch, 21. April 2021 and today Montag, 3. Mai 2021)

yet no changes have been made to the telephone numbers.

The equivalent English-language page at
- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636 (English)

has been updated (Wednesday, 24. März 2021 and Wednesday, 21. April 2021), also with no changes to the phone number.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks, updated internal ticket with your comment.

**Comment by MikeMcC399** [comment]
Are the phone numbers om the website of the Bundesregierung going to be updated? If there was any plan to do this I would have expected it to have been done by now. With the relaying of restrictions people are going to be more internationally mobile than they have been in the last months and may want to call the hotline from outside Germany. If they try to use the number listed it will not work.

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP 
Do you expect this to be fixed? I just wonder why 3 months has gone by and the phone number is still wrong.

**Comment by MikeMcC399** [comment]
Closing due to non-response and the fact that this issue is not about the https://www.coronawarn.app website.

I have left https://github.com/corona-warn-app/cwa-hotline/issues/13 open in the [CWA Hotline](https://github.com/corona-warn-app/cwa-hotline) repository to which is it more related.

**Comment by dsarkar** [comment]
@MikeMcC399 Alright.

**Comment by MikeMcC399** [comment]
Correction was made for telephone numbers on https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392 (German), see https://github.com/corona-warn-app/cwa-hotline/issues/13#issuecomment-919235748.

**Comment by dsarkar** [comment]
@MikeMcC399 Thank you for checking.

**Comment by MikeMcC399** [comment]
@dsarkar 
> Thank you for checking.

I wasn't just checking, I actively requested RKI to follow up last week and they contacted the Bundespresseamt who made the changes to the German page. RKI reported back that foreign language pages will follow soon.

**Comment by dsarkar** [comment]
@MikeMcC399 Great! I will mention this in the internal ticket as well! Thanks a lot for your dedication.
