### ISSUE TITLE
Update `mutation` to reflect the latest improvements reg. the risk calculation

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1009]
## Where to find the issue
https://www.coronawarn.app/de/faq/#mutation
https://www.coronawarn.app/en/faq/#mutation

## Describe the issue
The entry still says: 
"[...] If the risk of infection changes based on new findings, we certainly will adjust the risk calculation of the app."

The risk calculation has been changed 

on the 23.02.2021, see this blog post: https://www.coronawarn.app/en/blog/2021-02-23-corona-warn-app-risk-calculation-optimization/

and

on the 19.03.2021, see this blog post: https://www.coronawarn.app/en/blog/2021-03-19-risk-calculation-improvement/

## Suggested change
Add a note that the risk calculation has been adjusted and link to the blog posts

## Additional information

Let me know whether a PR regarding this would be welcome (-:

**Comment by heinezen** [comment]
@Ein-Tim If you want to make a PR, we won't stop you :D

----
Corona-Warn-App Open Source Team
