### ISSUE TITLE
Add button to FAQs to automatically unfold all answers

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-website#101]
If someone wants to read all the FAQs, they currently have to click on every single question to see the answer. It would be good if there was a button to "expand all".

**Comment by pixlbreaker** [comment]
Hi, I would be interested in adding this enhancement.

**Comment by Rameshwar3297** [comment]
or we can expand the Question when cursor moves on the particular question..?

**Comment by pixlbreaker** [comment]
Either works for me, I can start with the reveal all first and see how that works.

**Comment by MariusE** [comment]
Hover is not usable on mobile/touch devices, so a button is mandatory for this class of devices. 

Following the mobile-first approach, the button would be the go-to solution and the hover could be an additional trigger for supported devices.

Also I would be careful with using a simple hover as trigger. This can have some negative side effects like "flickering" layout when scrolling, while pointer hovering over the content. So there should at least be a delay.

**Comment by tkowark** [comment]
Hi @pixlbreaker sorry for the delay in response. If you are still interested in implementing the feature, we're more than happy to accept your PR. Focus should be on the "Expand All" functionality. On hover updates would be an additional feature. Thanks a lot for offering your help on that!

**Comment by tkowark** [comment]
Answers are now unfolded by default. We will further add a small search bar to make them more consumable.
