### ISSUE TITLE
Blog information regarding Place duration

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1010]
## Where to find the issue

**Corona-Warn-App version 1.14 brings new features to the contact journal**
https://www.coronawarn.app/en/blog/2021-03-09-corona-warn-app-version-1-14/

and

**Corona-Warn-App Version 1.14 bringt neue Funktionen ins Kontakt-Tagebuch**
https://www.coronawarn.app/de/blog/2021-03-09-corona-warn-app-version-1-14/

including also the "Video-Walkthrough: So funktioniert die neue Funktion"  on  https://www.coronawarn.app/assets/video/cwa-1-14-walk-through.mp4

## Describe the issue

1. In the paragraph shown below there is an implicit assumption that a Person and a Place are linked, however the only "link" is the occurrence on the same day. There is no explicit link available to state what Place a Person was met at.
2. It is not possible to choose 20 minutes as the duration for a Place on CWA Android 1.14.3. Only 0, 15, 30 and 45 minutes are accepted by the user interface.

"Users can also add their own notes for locations as well as people. For example, they can record circumstances that may affect the risk of infection: "sat close to each other", "sang", "crowded". This additional information can help users remember the situation later. For reasons of plausibility, however, users should make sure that the time entered in connection with people matches the time entered in connection with the location. For example, it might be confusing if users enter less than 15 min for a person they met, but 20 minutes for the location where they met the person."

## Suggested change

1. I would leave out the section "For reasons of plausibility, however, users should make sure that the time entered in connection with people matches the time entered in connection with the location. For example, it might be confusing if users enter less than 15 min for a person they met, but 20 minutes for the location where they met the person." and rely on the common sense of the user.
2. If the entry of a Place duration in iOS is so different to the way it works on Android, then a separate video needs to be supplied for each operating system. On Android you can skim up and down using a picker widget to select a value for hours and for minutes of duration. Also, again, in the video the duration is set to 20 minutes which is not possible in the Android app.

---
Internal tracking ID: [EXPOSUREAPP-5070](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5070)

**Comment by Ein-Tim** [comment]
As always, a very good point @MikeMcC399 

The behavior on iOS is like this:

On iOS it's also not possible to enter 20 minutes into the app with the picker, but if you click on the field there will be a numerical keyboard shown:

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for the iOS screenshot!

In Android, if you tap on the minutes field, the 00 is highlighted. Tap on 2 to try to enter 20 and 00 is cleared. There is no 2 displayed. Tap on 0 to try to finish entering 20 and 00 is displayed. You cannot enter 20!

In fact it is quite difficult to use. If you now tap 1 to try to enter 15, 0 is displayed. Then tap 5 for the second digit of 15 and nothing changes. You need to clear the field with the delete key, then you can enter 1, which immediately brings up 15.

As I noted in https://github.com/corona-warn-app/cwa-app-ios/issues/2209 it's much easier to flip up and down instead of using the keyboard on Android to input a duration.

![image](https://user-images.githubusercontent.com/66998419/111814345-a6f11e80-88da-11eb-9625-23d19534838b.png)

**Comment by ndegendogo** [comment]
> users should make sure that the time entered in connection with people matches the time entered in connection with the location. For example, it might be confusing if users enter less than 15 min for a person they met, but 20 minutes for the location where they met the person.

Yes, of course. I can go to a park for 20 minutes, and meet there with a friend for 10 or 15 minutes - why not?

**Comment by MikeMcC399** [comment]
I took a look at Android 1.15.1 RC0 and 2.0.0 RC2 and it seems that Place duration input through the keyboard has been disabled. This is a good thing if the minute values are constrained to 00, 15, 30 and 45 because otherwise it was quite strange attempting to input other values and have the keyboard input ignored.

**Comment by MikeMcC399** [comment]
@ndegendogo 
> Yes, of course. I can go to a park for 20 minutes, and meet there with a friend for 10 or 15 minutes - why not?

That's another good reason why the blog text doesn't really make a lot of sense. Thank you for pointing this out!

**Comment by dsarkar** [comment]
@MikeMcC399  @ndegendogo  Thanks, forward the issue to ticket: Internal tracking ID: [EXPOSUREAPP-5070](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5070)

**Comment by MikeMcC399** [comment]
On the page [Corona-Warn-App Version 1.14 bringt neue Funktionen ins Kontakt-Tagebuch](https://www.coronawarn.app/de/blog/2021-03-09-corona-warn-app-version-1-14/) the [Video-Walkthrough: So funktioniert die neue Funktion](https://www.coronawarn.app/assets/video/cwa-1-14-walk-through.mp4) has been labelled "(iOS-Beispiel)" so it is clear that is does not necessarily apply to Android as well.

The other issue remains unanswered:
This is about the statement in the blog that it would be confusing for a user to be in a place for longer than the duration of a meeting with another named person. @ndegendogo already gave a non-confusing simple example about going to a park and meeting somebody in the park for some of that time. The blog curiously suggests this would not be a plausible data entry.

**Comment by MikeMcC399** [comment]
If there are no plans to update the blog entries, which incorrectly imply that the duration of meeting with a person cannot be shorter than the duration of being at a place, please close this issue.

**Corona-Warn-App version 1.14 brings new features to the contact journal**
https://www.coronawarn.app/en/blog/2021-03-09-corona-warn-app-version-1-14/

**Corona-Warn-App Version 1.14 bringt neue Funktionen ins Kontakt-Tagebuch**
https://www.coronawarn.app/de/blog/2021-03-09-corona-warn-app-version-1-14/

**Comment by MikeMcC399** [comment]
Now that version 2.0 has been announced, I am not expecting any changes to be made to the 1.14 blog, so therefore I am closing this issue.
