### ISSUE TITLE
Update FAQs to agree with new risk calculation parameters

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1014]
## Where to find the issue

- [x] **How does the app calculate the risk (version >=1.9)?**
https://www.coronawarn.app/en/faq/#encounter_19_calc

- [x] **Previously, my app would display one or more low risk encounters - since the update to version 1.9 of the Corona-Warn App, these have disappeared or rather the number decreased.**
https://www.coronawarn.app/en/faq/#encounter_count_19

- [ ] **An encounter has been reported, but the risk status stays green**
https://www.coronawarn.app/en/faq/#encounter_but_green

## Describe the issue

The Risk Assessment parameters have changed. See PR https://github.com/corona-warn-app/cwa-documentation/pull/561 and https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf

This means that significant changes need to be made to the FAQ text describing the risk calculations. 

## Suggested change

All FAQ entries in the section https://www.coronawarn.app/en/faq/#risk_assessment should be reviewed and changed accordingly so that they agree with the new risk calculations.

https://github.com/corona-warn-app/cwa-documentation/issues/453 regarding the main document describing Risk Assessment remains open, otherwise the FAQ could just refer to this document and would not need to provide much detail.

(I am not planning to submit a PR on this and I would feel more comfortable for the changes to be done by the Open Source Team in this case, since risk assessment is such a central theme for CWA.)

**Comment by heinezen** [comment]
I have added this to #971

**Comment by MikeMcC399** [comment]
Unfortunately also the reference document https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf is out of date. See issue https://github.com/corona-warn-app/cwa-documentation/issues/586.

It gets more complicated, as time goes on, to know which documents are still accurate if they are not being actively maintained. As already mentioned in the original submission - see also https://github.com/corona-warn-app/cwa-documentation/issues/453 regarding:

**How does the Corona-Warn-App identify an increased risk?** found on
https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md

and translated document title
**Wie ermittelt die Corona-Warn-App ein erhöhtes Risiko?**
https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/cwa-risk-assessment.de.md

**Comment by heinezen** [comment]
@MikeMcC399 It's really unfortunate, but not something I can do anything about right now. I can assure you we ask for updated docs every week. Other parts of development take priority.

The proposed FAQ entry now contains the currently used parameters (slightly different than in the docs). This will have to do until the official resources get updated.

**Comment by MikeMcC399** [comment]
@heinezen 
I understand about this and I realize that there is little you can do. I also appreciate that the pandemic is dynamic with time pressures and shifting priorities. I just wanted to make a note so we don't lose track of the documentation dependencies.

It is part of the job of the FAQs to fill the gap left by in-app and web documentation, regarding details which are either not detailed enough or not up to date. That's pretty normal. So don't worry!

**Comment by MikeMcC399** [comment]
Closing in favor of other open issues:
https://github.com/corona-warn-app/cwa-documentation/issues/453 and
https://github.com/corona-warn-app/cwa-documentation/issues/586.
