### ISSUE TITLE
RKI: Outdated app risk screenshots

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1026]
## Where to find the issue

**Infektionsketten digital unterbrechen mit der Corona-Warn-App""
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html

## Describe the issue

The RKI website says:
"Die Corona-Warn-App hat drei verschiedene Statusanzeigen: "unbekanntes Risiko" (grau), "niedriges Risiko" (grün) und "erhöhtes Risiko" (rot)."

and it shows a screenshot of unknown risk (Unbekanntes Risiko)

https://www.rki.de/SharedDocs/Bilder/InfAZ/neuartiges_Coronavirus/WarnApp/Statusanzeige_unbekanntes-Risiko_210.jpg

Unknown risk was removed from the app as a status three months ago.

There have been several other changes made to the risk screens in versions including the currently released version 1.15.1:

- app now shows how long since installation, not how long exposure checking was active
- the text "Aktualisierung alle 24 Stunden" has been removed
- encounters show absolute not relative dates

## References

- [Screenshots for current release](https://www.coronawarn.app/de/screenshots/)

- [Unknown Risk status no longer used](https://github.com/corona-warn-app/cwa-website/issues/802) https://github.com/corona-warn-app/cwa-website/issues/802

- PR "Refactor riskcard & states; Chapter1 (EXPOSUREAPP-4049, EXPOSUREAPP-3834)" https://github.com/corona-warn-app/cwa-app-android/pull/1751 merged into branch release/1.8.x.

- [Announcement of CWA 1.9](https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/) listing release date of CWA 1.9 as Dec 16, 2020.

- [Announcement of CWA 1.15](https://www.coronawarn.app/en/blog/2021-03-24-corona-warn-app-version-1-15/)

## Suggested change

RKI should update their website using screenshots from [Screenshots for current release](https://www.coronawarn.app/de/screenshots/) https://www.coronawarn.app/de/screenshots/ and update the text accordingly.

---
Internal Tracking ID: [EXPOSUREAPP-5989](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5989)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal Tracking ID: EXPOSUREAPP-5989

**Comment by MikeMcC399** [comment]
RKI has updated the German-language page:

**Infektionsketten digital unterbrechen mit der Corona-Warn-App""
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html

with information about the 2.1 release from yesterday, May 2, 2021 (see "Projektteam integriert Schnelltests in Corona-Warn-App Version 2.1" https://www.coronawarn.app/de/blog/2021-05-02-corona-warn-app-version-2-1/).

The screen-shots however have not been updated. They are more than 4 months old and do not correspond to the ones on https://www.coronawarn.app/de/screenshots/. So this issue (with Internal Tracking ID: EXPOSUREAPP-5989) is still open.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Forwarded your comment to  Internal Tracking ID: EXPOSUREAPP-5989.

**Comment by MikeMcC399** [comment]
@dsarkar 

The unknown risk screenshot has been removed from https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html. This was the original reason for the issue, so this issue can now be closed.

---
The screenshots on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html **Infektionsketten digital unterbrechen mit der Corona-Warn-App** are still lagging behind the current app version 2.9.0 in minor ways. If this could cause confusion then a separate issue should be opened.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for checking!
