### ISSUE TITLE
FAQ [Android] Google "Bluetooth disabled" notification not translated to German

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#1032]
EN
[Android] Google "Bluetooth disabled" notification not translated to German
 
The notification produced by the Google Exposure Notifications System (ENS) version 18210613000 when Bluetooth is disabled is partially in English although the device locale is set to Deutsch (Deutschland) i.e., German.
This issue has been fixed by Google with Google Play services version 21.09.15, shown in the Corona-Warn-App (CWA) as ENF 18210915000 or higher.
Follow these steps in order to update Google Play services and the ENS:
Open Android Settings > Apps > Scroll down to Google Play Services and tap on it > Scroll down to details in store and tap on it > tap on update. Then close the CWA (swipe up) and re-open it.
Note, that you might not be able to update Google Play Services immediately, since apps or updates will often be rolled out in stages, i.e. not all users will be able update it at the same time. Try later again.
 
 
 
DE
 
[Android] Google "Bluetooth deaktiviert" Benachrichtigung nicht ins Deutsche übersetzt
 
Die Benachrichtigung des Google Exposure Notifications System (ENS) Version 18210613000, wenn Bluetooth deaktiviert ist, ist teilweise in englischer Sprache, obwohl die Geräte-Sprache auf Deutsch (Deutschland) eingestellt ist.
Dieses Problem wurde von Google mit Google Play-Diensten Version 21.09.15 behoben, die in der Corona-Warn-App (CWA) als ENF 18210915000 oder höher angezeigt wird.
Führen Sie die folgenden Schritte aus, um Google Play-Dienste und das ENS zu aktualisieren:
Öffnen Sie Android-Einstellungen > Apps > Scrollen Sie nach unten zu Google Play Services und tippen Sie darauf, > Scrollen Sie nach unten zu Details im Store und tippen Sie darauf, > tippen Sie auf Update. Schließen Sie dann den CWA (wischen Sie nach oben) und öffnen Sie die CWA erneut.
Beachten Sie, dass Sie Google Play Services möglicherweise nicht sofort aktualisieren können, da Apps oder Updates oft stufenweise eingeführt werden, d. h. nicht alle Benutzer können sie gleichzeitig aktualisieren. Versuchen Sie es später erneut.

---
Internal Tracking ID: [EXPOSUREAPP-5955](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5955)

**Comment by MikeMcC399** [comment]
@dsarkar 
Do you think it is necessary to have an FAQ article for this issue? Has there been a lot of feedback from users with disabled Bluetooth?

**Comment by dsarkar** [comment]
@MikeMcC399 In the PlayStore we had some feedback. We might reference to this FAQ in the Stores. However, we are hesitating, since not everybody can update GPServices yet.

**Comment by MikeMcC399** [comment]
@dsarkar 

I think this article is probably obsolete because normally all devices will have automatically updated to Google Play services version 21.09.15 by now.

What does that information from the data donation system say? According to https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf page 76 the app collects this data if data donation is enabled:

0.3 - Client Metadata (CWA Version, OS Version,
**ENF Version (Android only)**, App Config Hash)

**Comment by dsarkar** [comment]
@MikeMcC399 True, thanks.
