### ISSUE TITLE
Always use System UI demo mode for Android screenshots

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-website#1053]
## Where to find the issue

https://www.coronawarn.app/en/screenshots → Android screenshots

## Describe the issue

Some of the Android screenshots are using System UI demo mode while some others aren't. You can tell by checking the clock, which is always set to the Android version when System UI demo mode is enabled, and by checking if notification icons are displayed.

![image](https://user-images.githubusercontent.com/16943720/113597862-9b248c80-963c-11eb-9907-49a060584f76.png)

## Suggested change

All screenshots should use System UI demo mode to look consistent and clean. Specifically, no notification icons from other apps or system services should be shown.

Note that iOS screenshots also display different times of day in the notification bar.
 In iOS "demo mode" the clock would always show "9:41".

---
Internal tracking ID: [EXPOSUREAPP-6194](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6194)

**Comment by Ein-Tim** [comment]
iOS seems to display the actual time the screenshots were taken. In iOS "demo mode" the clock would always show "9:41".

**Comment by dsarkar** [comment]
Internal tracking ID: [EXPOSUREAPP-6194](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6194)

**Comment by dsarkar** [comment]
Indeed, demo mode should be used. Some screenshots were taken manually and not in demo mode. We will replace them eventually.


---
Corona-Warn-App Open Source Team

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:

>  our automated screenshot all use the demo mode. The ones on the website with a "dirty" status bar have been taken manually. In the future, we should enable demo mode before taking screenshots manually: https://developer.android.com/studio/debug/dev-options#general
>
> So I think I can set this ticket to obsolete
