### ISSUE TITLE
FAQ -  Recommendation to use or not CWA in other countries

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#1059]
## Where to find the issue

- Recommendation needed whether or not to switch Active Region/App while traveling in Europe
- Recommendation to use or not CWA in other countries

## Describe the issue

See https://github.com/corona-warn-app/cwa-wishlist/issues/437

## Suggested change

**FAQ DE**

Man kann folgende Fälle unterscheiden: Reisen in Länder, 
1.	die am EU "Interoperability Gateway" angeschlossen sind. 
2.	die nicht am EU "Interoperability Gateway" angeschlossen sind, aber die GAEN-Schnittstelle für ihre Kontaktverfolgungs-App benutzen, z.B. Kanada.
3.	deren Kontaktverfolgungs-App nicht die GAEN-Schnittstelle benutzt, z.B. Frankreich.
4.	die keine Kontaktverfolgungs-App bereitstellen.

**Allgemeine Hinweise:**
- In allen oben genannten Fällen sollte die CWA weiter benutzt werden, da den Benutzer auch noch bis zu 14 Tage nach Ankunft Benachrichtigungen über potenzielle Risiko-Begegnungen erreichen können. Auch deutsche Test-Ergebnisse können so dem Benutzer der CWA noch im Nachhinein übermittelt werden. 
- Sollte im Ausland ein PCR-Test mit positivem Test-Ergebnis vorliegen, wird empfohlen dieses Ergebnis über das TAN-Verfahren in die CWA einzugeben. Dazu rufen Sie bitte die internationale TAN-Hotline unter +49 30 498 75402 an, welche 24 Stunden und sieben Tage die Woche erreichbar ist.

**Des Weiteren kann man unterscheiden:**

1. Reisen in Länder, die an der "Länderübergreifende Risiko-Ermittlung" teilnehmen. ~am EU "Interoperability Gateway" angeschlossen sind.~
  - Vollständige Liste der teilnehmenden Länder: https://www.coronawarn.app/de/faq/#interoperability_countries
  - In diesen Ländern sind die Kontaktverfolgungs-Apps kompatibel. Die CWA wird den Benutzer auch vor Risiko-Kontakten warnen, die die Kontaktverfolgungs-App eines dieser Länder benutzen. 
  - Prinzipiell besteht die Möglichkeit, beide Apps, die App des bereisten Landes und die CWA, zu installieren und auch zu öffnen. Aber beide Apps sind nicht gleichzeitig zu aktiv. Sollten Sie beide Apps benutzen wollten, empfiehlt es sich einmal am Tag die aktive App zu wechseln. Das kann entweder über die App selbst oder dem Betriebssystem („Aktive Region“) vorgenommen werden.

2. Reisen in Länder, die an nicht der "Länderübergreifende Risiko-Ermittlung" teilnehmen ~die nicht am EU "Interoperability Gateway" angeschlossen sind~, aber die GAEN-Schnittstelle für ihre Kontaktverfolgungs-App benutzen.
  - Prinzipiell besteht die Möglichkeit, beide Apps, die App des bereisten Landes und die CWA, zu installieren, aber es nicht gleichzeitig zu aktivieren. Sollten Sie beide Apps benutzen wollten, empfiehlt es sich einmal am Tag die aktive App zu wechseln. Das kann entweder über die App selbst oder dem Betriebssystem (Aktive Region) vorgenommen werden.

3. Reisen in Länder, deren Kontaktverfolgungs-App nicht die GAEN-Schnittstelle benutzen
  - Die CWA und die App des bereisten Landes sind nicht kompatibel, jedoch besteht die Möglichkeit, beide Apps, die App des bereisten Landes und die CWA, zu installieren und gleichzeitig zu benutzen. Es empfiehlt sich in diesem Fall, Benachrichtigungen beider Apps Aufmerksamkeit zu schenken.

4. Reisen in Länder, die keine Kontaktverfolgungs-App bereitstellen
  - Der Nutzen der CWA beschränkt sich hauptsächlich auf die in den allgemeinen Hinweisen gegebenen.

**Comment by MikeMcC399** [comment]
@dsarkar 
You didn't mention Switzerland specifically, which is a special case, because it is part of the Transnational Exposure Logging, but not connected to the European Federation Gateway Service (EFGS). Is this Switzerland  in category 1 or 2?

Switzerland isn't listed in https://www.coronawarn.app/de/faq/#interoperability_countries.

**Comment by dsarkar** [comment]
@MikeMcC399 

> Switzerland isn't listed in https://www.coronawarn.app/de/faq/#interoperability_countries.

Yes, I also realized this today. Needs to be fixed.

> You didn't mention Switzerland specifically, which is a special case, because it is part of the Transnational Exposure Logging, but not connected to the European Federation Gateway Service (EFGS). Is this Switzerland in category 1 or 2?

Good question. Will get the info.

**Comment by dsarkar** [comment]
@MikeMcC399 They are not in EFGS, but in practice the user will not notice any difference, so Cat I.

**Comment by MikeMcC399** [comment]
@dsarkar 

>>Switzerland isn't listed in https://www.coronawarn.app/de/faq/#interoperability_countries.
>
>Yes, I also realized this today. Needs to be fixed.

I will open an issue to track this.

**Comment by MikeMcC399** [comment]
See https://github.com/corona-warn-app/cwa-website/issues/1060 for issue regarding missing Switzerland reference.

**Comment by Ein-Tim** [comment]
Is there any update available here?

**Comment by MikeMcC399** [comment]
@dsarkar 

Are you intending to follow this up?

It seems that an explanation about using CWA in other countries is no longer needed as the pandemic situation is receding.

**Comment by MikeMcC399** [comment]
- This issue is now obsolete, in the sense that Germany is no longer joined to the European Federation Gateway Service (EFGS). See also https://github.com/corona-warn-app/cwa-website/issues/3416.

**Comment by brianebeling** [comment]
Thanks Mike, closing the issue as not planned anymore for the aforementioned reasons
