### ISSUE TITLE
FAQ: Switzerland not listed in #interoperability_countries

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1060]
## Where to find the issue

**In which countries can the Corona Warn App be used?**
https://www.coronawarn.app/en/faq/#interoperability_countries

**In welchen Ländern kann die Corona Warn App genutzt werden?**
https://www.coronawarn.app/de/faq/#interoperability_countries

## Describe the issue

1. Switzerland is not listed as a country in the FAQ [In which countries can the Corona Warn App be used?](https://www.coronawarn.app/en/faq/#interoperability_countries), although the transnational exposure logging was expanded with the release of version 1.15 of the app on March 24, 2021  to include the integration of Switzerland (see https://www.coronawarn.app/en/blog/2021-03-24-corona-warn-app-version-1-15/).
2. The description in the [FAQ](https://www.coronawarn.app/en/faq/#interoperability_countries) only covers the integration with the EU "Interoperability Gateway". It does not cover the additional separate integration with Switzerland.

## Suggested change

1. Add Switerland to the list.
2. Ensure alignment of the FAQ to the [Privacy notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) section 7. "How does the transnational warning system work?"<br><br>"In order to also enable warnings between users of the Swiss coronavirus app and the Corona-Warn-App, the RKI also operates another exchange server together with Switzerland (Federal Office of Public Health of the Swiss Confederation)."

---
Internal Tracking ID: [EXPOSUREAPP-6346](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6346) FAQ
Internal Tracking ID: [EXPOSUREAPP-6347](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6347) RKI

**Comment by MikeMcC399** [comment]
Switzerland is also missing from the list of countries on the RKI site https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html => "Antworten auf häufig gestellte Fragen zur Corona-Warn-App
Allgemeine Fragen (25.3.2021)" => "Mit welchen Warn-Apps aus europäischen Ländern die Corona-Warn-App Daten austauscht" Stand: 25.03.2021.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. 

Internal Tracking ID: [EXPOSUREAPP-6346](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6346) FAQ
Internal Tracking ID: [EXPOSUREAPP-6347](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6347) RKI

**Comment by dsarkar** [comment]
PR FAQ https://github.com/corona-warn-app/cwa-website/pull/1086

**Comment by dsarkar** [comment]
1. Done.
2. ToDo

**Comment by dsarkar** [comment]
![Uploading image.png…]()

**Comment by dsarkar** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/1409741/114700295-a6a14300-9d21-11eb-8f63-f1e7b4a21de4.png">

**Comment by MikeMcC399** [comment]
> Internal Tracking ID: [EXPOSUREAPP-6346](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6346) FAQ

Since #1086 and #1089 have been merged, the FAQ issues on https://www.coronawarn.app are now addressed.

> Internal Tracking ID: [EXPOSUREAPP-6347](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6347) RKI

The RKI issue is still open, since Switzerland is missing from the list below. There should be 17 countries listed, not 16.

![image](https://user-images.githubusercontent.com/66998419/114714479-71512100-9d32-11eb-850f-5010f88a9ea7.png)

**Comment by dsarkar** [comment]
![Uploading image.png…]()

;-)

**Comment by dsarkar** [comment]
@MikeMcC399 
Malta is not on their list yet.

**Comment by MikeMcC399** [comment]
@dsarkar 
Thank you for pointing out my mistake about Switzerland (die Schweiz)! Also I should be careful with counting, because in the RKI list Deutschland is in the text, not in the list, whereas in the app it is in the list.

![image](https://user-images.githubusercontent.com/66998419/114732090-88980a80-9d42-11eb-9a61-663337e562b8.png)

So, now that Schweiz / Switzerland is listed everywhere we can close this issue. Thanks for fixing the FAQs!

Thanks also for the information about Malta.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for all the help!
