### ISSUE TITLE
RKI: Privacy document refers to missing Swiss agreement

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1061]
## Where to find the issue

Privacy notice, 24 March 2021, version 1.15
https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf

Section 7 "How does the transnational warning system work?"

• "The operation and data exchange of the joint exchange server with Switzerland is
regulated in an individual agreement between the RKI and Switzerland, available at
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html."

## Describe the issue

There is no link visible to an individual agreement between the RKI and Switzerland on the page https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html. 

There is only the following information section shown:

---
**Überblick über neue und geplante Funktionalitäten**

Mit dem Update auf die Version 1.15 wurde die länderübergreifende Risiko-Ermittlung um die Schweiz erweitert. Damit können zukünftig auch Warnungen an Nutzerinnen und Nutzer der schweizerischen Contact Tracing-App („SwissCovid“) versendet werden bzw. diese können Nutzende aus den anderen Teilnehmerländern warnen.

In einem der nächsten Releases soll die Corona-Warn-App um die Möglichkeit einer Event-Registrierung per QR-Code erweitert werden. Auch mit dieser Funktionalität bleibt der dezentrale Ansatz der App gewahrt. Es werden keine persönlichen Daten erfasst.

Weitere Details zu den Updates können Sie jeweils nach Veröffentlichung auf dem Blog der Entwicklungsteams nachlesen: https://www.coronawarn.app/de/blog/

---

## Suggested change

The RKI site should publish the agreement on the page https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html  **or**
the privacy document should be changed.

---
Internal Tracking ID: [EXPOSUREAPP-6348](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6348)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal Tracking ID: [EXPOSUREAPP-6348](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6348)

**Comment by MikeMcC399** [comment]
@dsarkar 

I am now seeing the document
[Behördenvereinbarung zwischen RKI und BAG zur grenzüberschreitenden Interoperabilität von Corona-Apps](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Vertrag-DE-SWI.pdf) published to the RKI page [Infektionsketten digital unterbrechen mit der Corona-Warn-App](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html) so this issue can be closed.

The text on that page says:

"Vereinbarung zwischen Robert Koch-Institut, Bundesinstitut im Geschäftsbereich des Bundesministeriums für Gesundheit der Bundesrepublik Deutschland und dem Eidgenössischen Departement des Innern der Schweizerischen Eidgenossenschaft betreffend Corona-Apps (Austausch von Schlüsseln über einen auf schweizerischer Seite betriebenen Gateway Server zur grenzüberschreitenden Interoperabilität)"

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.
