### ISSUE TITLE
Datenschutz-Folgenabschätzung says deinstallation keeps "Begegnungsaufzeichnung" 

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1066]
## Where to find the issue

[Datenschutz-Folgenabschätzung](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf)
Bericht zur Datenschutz-Folgenabschätzung für die Corona-Warn-App der Bundesrepublik Deutschland
Öffentliche Version
Version 1.7, 02.03.2021

5.6.9 Deinstallation der CWA App, Seite 54 von 148.

## Describe the issue

The [Datenschutz-Folgenabschätzung](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf) says that the "Begegnungsaufzeichnung" will not be deleted if the app is uninstalled.

This contradicts information in the [App FAQ](https://www.coronawarn.app/de/faq/#delete_random_ids) for the Android operating system and in the [Google API documentation](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#methods). The contradiction is only apparent for the Android operating system, not for the iOS operating system.

---
[Data Protection Impact Assessment](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf)

**5.6.9 Deinstallation der CWA App**

"Deinstalliert der CWA-Nutzer die CWA App auf dem Smartphone, werden dadurch sämtliche
von der CWA App gespeicherten Daten vom Smartphone gelöscht.

"Durch diesen Schritt nicht gelöscht werden die Daten, die durch das jeweilige Betriebssystem gespeichert und verwaltet werden. Dies sind der Verschlüsselungsschlüssel in der KeyChain sowie die Daten in der Begegnungsaufzeichnung des ENF des Betriebssystems."

---
[CWA FAQs - Anwendung](https://www.coronawarn.app/de/faq/#application)

[Werden die gesammelten Zufalls-IDs beim Deinstallieren der App entfernt?](https://www.coronawarn.app/de/faq/#delete_random_ids)

"Auf Android-Geräten werden in der derzeitigen Implementierung beim Deinstallieren ['Datenbank und Schlüssel' vom Gerät gelöscht](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#methods). Sie sollten daher davon ausgehen, dass mit Deinstallation der App auch die Begegnungsaufzeichnungen verloren gehen."

---
[Google - Exposure Notifications API](https://developers.google.com/android/exposure-notifications/exposure-notifications-api)

[Methods](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#methods)

"stop()<br><br>Disables the broadcast and scan process. You can call this directly. It's also called when a user uninstalls the app. When it’s called as part of the uninstallation process, the database and keys are deleted from the device."

---

## Additional comments

Uninstalling the Corona-Warn-App on Android deletes the complete Exposure Log history displayed by Google. 

### Steps to reproduce

1. Install CWA
2. Settings > Google > COVID-19 Exposure Notifications > three-dot icon > Exposure checks<br>Note the history of exposure checks
3. Settings > Apps > Corona-Warn > Uninstall
4. Install CWA and run through onboarding
5. Repeat step 2. and note that the previous history of Exposure checks has been completely replaced by one new entry only

## Suggested change

The [Datenschutz-Folgenabschätzung](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf) should be changed to say that uninstalling the app on Android removes the recorded exposure data. The statements regarding iOS are not affected. This concerns Android only.

---
 Internal Tracking ID: [EXPOSUREAPP-6351](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6351)

**Comment by Ein-Tim** [comment]
iOS keeps the data after a deinstallation (see also https://www.coronawarn.app/en/faq/#delete_random_ids).

Nobody seems to really know for how long, I could do some tests reg. this, if you say that this is needed here.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
This is only about the contradiction for Android.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Correct, my fault, thought we were in the documentation repository. Sorry. 😅

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for your feedback! I have modified the original posting:

"The [Datenschutz-Folgenabschätzung](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf) should be changed to say that uninstalling the app on Android removes the recorded exposure data. The statements regarding iOS are not affected. This concerns Android only."

I also added steps to reproduce. Although there is no way for a regular user to view the actual RPIs stored, the exposure log is accessible and it shows that the exposure log history is deleted when the app is uninstalled. Given that the Google documentation explicitly says that keys are deleted when an app is uninstalled, it is reasonable to assume that this is true. It is also consistent with the experience of seeing the exposure log history deleted.

The published [Datenschutz-Folgenabschätzung](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf) is stored on GitHub on https://github.com/corona-warn-app/cwa-website/blob/master/src/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf so I think here is a good place to have posted an issue on the document's contents.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks for the clarification and for explaining.
The now written sentence in the "Suggested Change" part of your issue seems fine to me and reflects the current situation. 
I think this repo should be fine for this issue. 

And as always: Great that you noticed this!

**Comment by dsarkar** [comment]
Good morning @MikeMcC399 @Ein-Tim. Thanks! Internal Tracking ID: [EXPOSUREAPP-6351](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6351)

**Comment by MikeMcC399** [comment]
Good morning @dsarkar! Thank you for picking up the issue!
Wishing you (and @Ein-Tim) a good Sunday!

**Comment by dsarkar** [comment]
@MikeMcC399 Many thanks for all the contributions! Same to you and @Ein-Tim, enjoy Sunday!

**Comment by dsarkar** [comment]
in new doc, the relevant subsection is now 5.6.12

**Comment by MikeMcC399** [comment]
v 1.12 of the document (page 81) now says:

"Durch diesen Schritt nicht automatisch gelöscht werden die Daten, die durch das jeweilige
Betriebssystem gespeichert und verwaltet werden. Dies betrifft zum einen
Verschlüsselungsschlüssel in der KeyChain. Unter iOS bleiben zudem die Daten in der
Begegnungsaufzeichnung des ENF zunächst erhalten. **Unter Android werden mit der
Deinstallation der CWA-App die Positivschlüssel dann automatisch gelöscht, wenn keine
weitere Corona-App installiert ist, die Zugriff auf die Begegnungsaufzeichnung des ENF hat.**"

I don't think that is a complete description. Not only the "Positivschlüssel" are deleted, but also all the "protokollierten RPIs"of the "Begegnungsaufzeichnung".

**Comment by MikeMcC399** [comment]
I will open a new issue, otherwise it will get quite confusing.

**Comment by MikeMcC399** [comment]
#1281 opened.
Closing this issue, because V1.12 of the document has a different (related) problem which is not exactly covered by the description in this issue.
