### ISSUE TITLE
FAQ: Effect of clear data on random ID storage

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1067]
## Where to find the issue

**Are the exposure logs/random IDs removed from my phone when I uninstall the app?**
https://www.coronawarn.app/en/faq/#delete_random_ids

**Werden die gesammelten Zufalls-IDs beim Deinstallieren der App entfernt?**
https://www.coronawarn.app/de/faq/#delete_random_ids

## Describe the issue

The FAQs misleadingly say:
"We recommend that before you re-install the app, you try clearing the app data first as this will not delete the random IDs:"

"Wir empfehlen daher, vor der Neu-installation zunächst die Daten in der App zurückzusetzen, da hierbei die gesammelten Zufalls-IDs nicht gelöscht werden:"

The FAQs mean resetting the app, not clearing the app data using the operating system UI.

The side-effect of using Android's "Clear data" storage maintenance function on the App listed as "Corona-Warn" is not explicitly mentioned. "Clear data" acts like uninstalling the app as far as the Google Exposure Notifications System is concerned. Keys will be deleted.

## Background

In an old post https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-719786581 from on Oct 30, 2020 @thomasaugsten wrote:

> I doubled check and it looks Google is now registering the data deleting and turns off the exposure notification framework the leads to a key wiping. We will update our FAQ

From the context of the issue https://github.com/corona-warn-app/cwa-app-android/issues/642 it seems that the FAQ being referred to was https://www.coronawarn.app/en/faq/#delete_random_ids.

The intention of updating the FAQ stated by @thomasaugsten was never actioned.

The general issue of the side-effects of deleting the data from the CWA on Android has been brought up in https://github.com/corona-warn-app/cwa-app-android/issues/2795.

### EN
[Are the exposure logs/random IDs removed from my phone when I uninstall the app?](https://www.coronawarn.app/en/faq/#delete_random_ids)

Reword:

"On Android devices, the current implementation deletes the ['database and keys' from the device](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#methods) when uninstalling the app. Hence, you should expect that the collected random IDs are deleted when the app is uninstalled. **Random IDs are also deleted if the Android App storage maintenance "Clear data" function is used on the App "Corona-Warn".**"

...

"We recommend that before you re-install the app, you try **resetting the app** first as this will not delete the random IDs:"

### DE
[Werden die gesammelten Zufalls-IDs beim Deinstallieren der App entfernt?](https://www.coronawarn.app/de/faq/#delete_random_ids)

Reword:

"Auf Android-Geräten werden in der derzeitigen Implementierung beim Deinstallieren 'Datenbank und Schlüssel' vom Gerät gelöscht. Sie sollten daher davon ausgehen, dass mit Deinstallation der App auch die Begegnungsaufzeichnungen verloren gehen. **Die Begegnungsaufzeichnungen gehen ebenso verloren, sollte die Android App-Speicherplatzverwaltungsfunktion "Daten löschen" auf die App "Corona-Warn" angewandt werden.**

...

"Wir empfehlen daher, vor der Neu-installation zunächst **die App zurückzusetzen**, da hierbei die gesammelten Zufalls-IDs nicht gelöscht werden:"

---

I will put the above into a draft PR later today.

**Comment by MikeMcC399** [comment]
I have created the PR https://github.com/corona-warn-app/cwa-website/pull/1068 and it is ready for review.

**Comment by MikeMcC399** [comment]
@heinezen 
Could you please review PR #1068? I'm unsure if the FAQ should go into the detail of what happens if a user deletes app data using Android tools. Perhaps we should close this PR instead of merging it?

**Comment by heinezen** [comment]
@MikeMcC399 

I have taken a look and don't see anything that would be problematic.

However, it got me thinking whether this FAQ entry takes the right approach in general. The question is: Who is the audience for this entry?

1. Someone who wants solve a problem with the app and considers re-installing it?
2. Someone who has uninstalled the app and wants to be sure that all the app's data (including exposue logs) are deleted?

Maybe it would be better to address both of these audiences individually with two separate entries:

* What happens if I uninstall the app?
* How do I delete all data gathered by the app?

**Comment by MikeMcC399** [comment]
@heinezen 

Thanks for taking a look!

The current FAQ
**Are the exposure logs/random IDs removed from my phone when I uninstall the app?**
https://www.coronawarn.app/en/faq/#delete_random_ids

answers more the question: "What happens if I uninstall the app?"

whereas the other question: "How do I delete all data gathered by the app?" is not specifically addressed.

I don't see much discussion in the last months about these topics however, so before spending additional time on this subject area at this stage in the app's life-cycle, I suggest either merging PR #1068 or closing it. I am fine with either decision.
