### ISSUE TITLE
What technology or framework are you using?

### ISSUE THREAD

**Issue by saibotma** [corona-warn-app/cwa-website#108]
## What technology or framework are you using?
I've taken a look at the code but i couldn't find out whether the website is built using some framework like Hugo, Vue or just plain HTML and JavaScript?
I want to know this in order to learn the framework/technology to be able to contribute.

**Comment by MariusE** [comment]
It looks like they use Panini for generating static HTML
https://github.com/foundation/panini

Additionally they included the Foundation Framework:
https://get.foundation/
