### ISSUE TITLE
Language Switch doesn't work on download page

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1092]
## Where to find the issue
https://www.coronawarn.app/de/download/
https://www.coronawarn.app/en/download/

## Describe the issue
The language switcher in the top right corner doesn't work. It redirects to the main page.

## Suggested change
Make the language switcher work.

## Additional information
The language can already be changed now by modifying the URL.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Good catch! Again, I think @svengabr should be involved.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks. If you got already a PR in preparation, I can merge it. If not, let me know, I will do it.  Thanks for all the help!

**Comment by Ein-Tim** [comment]
@dsarkar I didn't prepare something, so for me it would be ok if you could fix this!

**Comment by MikeMcC399** [comment]
@dsarkar 
I don't know how to fix this issue. I guess you might need gulp and JavaScript skills. Sorry.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Can you check again, it seems to work now.
Thanks.

**Comment by svengabr** [comment]
Short update:

The download page will be removed from the main website and afterwards be available in a separate repository.

Most likely on Monday next week.
This bug would be obsolete.

**Comment by Ein-Tim** [comment]
@svengabr 

Thanks for the update. Could you let us know when the change is done?

**Comment by Ein-Tim** [comment]
The repo for the language page is: https://github.com/corona-warn-app/cwa-event-landingpage

**Comment by svengabr** [comment]
> The repo for the language page is: https://github.com/corona-warn-app/cwa-event-landingpage

I will remove the code from cwa-website today as it is available in the new repository now.
