### ISSUE TITLE
Website benutzt manchmal Höflichkeitsform ("Sie") und manchmal nicht ("du")

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1093]
## Where to find the issue
Überall auf https://www.coronawarn.app/de

Die [Startseite](https://www.coronawarn.app/de), die [Communitiyseite](https://www.coronawarn.app/de/community) & die [Downloadseite](https://www.coronawarn.app/?target=download) nutzen "du", der [Blog](https://www.coronawarn.app/de/blog) & die [FAQ](https://www.coronawarn.app/de/faq) hingegen nutzten "Sie".

## Describe the issue
Wie oben beschrieben nutzt die Website nicht einheitlich "du" oder "Sie" sondern beide Formen.

## Suggested change
Es sollte eine Entscheidung getroffen welche Form genutzt werden soll und die Seite dementsprechend aktualisiert werden.

## Additional information
This is an issue about the German language, so I wrote the issue here in German.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Good point!

For the community I think that "du" is fine.

The app itself uses the "Sie" form, so it makes sense to have the FAQs also in the "Sie" form.

**The inconsistency is in the new download link, targeted at end users. To be consistent with the reset of the app it should use the "Sie" form.**

https://www.coronawarn.app/de/ avoids the issue by not using "du" or "Sie". The text next to the download buttons says:
"App mit!
Jetzt zum Download verfügbar im Apple App Store und auf Google Play."

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> For the community I think that "du" is fine.

I definitely agree.

> The inconsistency is in the new download link, targeted at end users. To be consistent with the reset of the app it should use the "Sie" form.

Right, that also was my starting point for opening this issue. I'll provide a separate PR suggesting to change the text on the download page from the "Du" to the "Sie" form. 

> coronawarn.app/de avoids the issue by not using "du" or "Sie"

Further down it also uses the "du" form ("Bleib auf dem Laufenden!"). But I think that's okay.

I think this issue can be closed once the form on the download page is corrected.

**Comment by Ein-Tim** [comment]
Fixed in #1095
