### ISSUE TITLE
Download app button order doesn't match text for Apple and Google

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1094]
## Where to find the issue

**Download Corona-Warn-App**
https://www.coronawarn.app/en/download

**Download Corona-Warn-App**
https://www.coronawarn.app/de/download/

## Describe the issue

In the text 
"Available for download on Apple App Store and Google Play."

Apple is mentioned first, then Google, however the order of the buttons is the other way around.

Same for the German text:
"Zum Dowload verfügbar im Apple App Store und auf Google Play."

Secondarily, there is a typo in the word "Dowload".

Thirdly, I'm not sure whether "Download Corona-Warn-App" should be used as a title on the German page.

---
![Download the app](https://user-images.githubusercontent.com/66998419/114913567-a2f4e580-9e21-11eb-92f4-4af24033bf46.png)

---
![Lade die App](https://user-images.githubusercontent.com/66998419/114913785-e4859080-9e21-11eb-8ab9-1f3d0e31e477.png)

---
Compare also with the button order on https://www.coronawarn.app/en/

![Get The App](https://user-images.githubusercontent.com/66998419/114913943-0ed74e00-9e22-11eb-9cfe-e952489b2254.png)

## Suggested changes

1. Change the button order to Apple on the left and Google Play on the right.
2. Correct the typo "Dowload" in the German text => "Download" or change it to "Herunterladen".
3. Change the HTML title on the German page from "Download Corona-Warn-App" => "Corona-Warn-App herunterladen"

## Additional points

The Open Source Team (for instance @svengabr who is the original author) should give feedback on these items. If changes are agreed, they could possibly be incorporated into @Ein-Tim's PR https://github.com/corona-warn-app/cwa-website/pull/1091 regarding other items on the new download pages.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

If that's ok for you I would already now correct the typo "Dowload" (point 2) in #1091. I can't imagine that the Open Source Team doesn't want to correct this. (:

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> If that's ok for you I would already now correct the typo "Dowload" (point 2) in #1091. 

Of course, yes.

**Comment by Ein-Tim** [comment]
#1091 is merged now. 
@svengabr Will you change the other things (1. & 3.) here and change the "Du" to "Sie" form, see #1093.
If not, let me know, I already prepared the most changes locally.

**Comment by svengabr** [comment]
Hey, @MikeMcC399 thanks for your feedback. 

An explanation on the new download page can be found here: https://github.com/corona-warn-app/cwa-website/pull/1091#issuecomment-820953715
> 
> 
> Thanks for your contributions! For now, I am not sure how to continue with this. The download page was a work in progress and the "real" download page will be located at: https://e.coronawarn.app/
> 
> The purpose of that simple static site is that we need a slim page without any type of tracking. However, the current version that can be seen there is not the final one. It will be a copy of the download page discussed here.
> 
> I will make sure your changes will be applied to that little static site.
> I would suggest not doing any additional HTML changes here for now.
> 
> Have a great day!

You can do your suggested changes if you like to. I will make sure everything will get merged. Don't bother with the 100vh issue, this is already fixed on my machine.

Have a great day!

**Comment by MikeMcC399** [comment]
@Ein-Tim

Since @svengabr wrote "You can do your suggested changes if you like to." and #1091 is merged, another PR would be necessary. If you want to pick this up, that is fine with me. It would otherwise make it a little complicated to have too many people working on the same area of issues.

If you don't want to do this, please reply here, and I will look at addressing the open changes I proposed:

---
On **Download Corona-Warn-App** (EN)
https://www.coronawarn.app/en/download

1. Change the button order to Apple on the left and Google Play on the right.

---
On **Download Corona-Warn-App** (DE)
https://www.coronawarn.app/de/download/

1. Change the button order to Apple on the left and Google Play on the right.
2. Change the HTML title on the German page from "Download Corona-Warn-App" => "Corona-Warn-App herunterladen"

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I prepared most of the changes locally already. I can open a PR here soon, if that's fine for you.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> I prepared most of the changes locally already. I can open a PR here soon, if that's fine for you.

Please feel free to go ahead. I suggest you keep @svengabr informed.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I try to get the PR finished by 10:15 lately, but I want to test the changes locally, mainly the change of the order form the download buttons.

I will keep you in the loop here @svengabr & @MikeMcC399.

**Comment by Ein-Tim** [comment]
Opened #1095

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for making the changes! I didn't get the chance to review before @svengabr had merged #1095, however the changes look good. The issues described here have all been addressed, so I will close this now.
