### ISSUE TITLE
Deploy master triggered on push to fork's master branch

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1098]
## Where to find the issue

[deploy-master.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/deploy-master.yml)

## Describe the issue

If a user pushes a commit to the master branch of a fork of the [cwa-website](https://github.com/corona-warn-app/cwa-website) repository like to
`https://github.com/<GitHub-Username>/cwa-website/tree/master` and Actions are enabled in the fork, then [deploy-master.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/deploy-master.yml) attempts and fails to deploy the fork to the production web server.

## Steps to reproduce

1. Fork the repository https://github.com/corona-warn-app/cwa-website
2. In the forked repository `https://github.com/<GitHub-Username>/cwa-website/tree/master` select "Settings" > "Actions" and "Allow all actions" and Save
3. From a clone of the fork on a local system execute
-- `git checkout master`
-- `git push origin`
4. Open Actions in forked repository and note the error marked against "Deploy master"

![Deploy master](https://user-images.githubusercontent.com/66998419/115015514-121b1a00-9eb4-11eb-96aa-dc0af6b68ab9.jpg)

## Expected behavior

The [deploy-master.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/deploy-master.yml) should only result in a website deployment if there is a push to the [master branch](https://github.com/corona-warn-app/cwa-website/tree/master) of the [original cwa-website repository](https://github.com/corona-warn-app/cwa-website), not to a fork of this repository.

~~It is advantageous to enable actions in a cwa-website fork, because then the [build.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) will be run against any community pushes. This gives earlier feedback on any errors through `npm run-script build`, which would otherwise only be flagged when a PR is merged.~~ This comment does not apply, because [build.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) is currently triggered on a pull_request, not on a push.

## Workaround

Select "Disable actions" in "Settings" > "Actions" of a fork before executing `git push origin master` to a fork of the [cwa-website](https://github.com/corona-warn-app/cwa-website) repository.

## Suggested change

Modify [deploy-master.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/deploy-master.yml) 

I don't have experience in yaml. I did find https://github.community/t/stop-github-actions-running-on-a-fork/17965 though and it seems like 
`if: github.repository == ‘corona-warn-app/cwa-website’`
might help if it can be inserted in the right place.

---
Internal Tracking ID: [EXPOSUREAPP-7157](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7157)

**Comment by heinezen** [comment]
Fixed in https://github.com/corona-warn-app/cwa-website/pull/1229
