### ISSUE TITLE
FAQ: Typo in #check_in_qr_warning

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1120]
## Where to find the issue

**Questions and answers about the warning:**
https://www.coronawarn.app/en/faq/#check_in_qr_warning

Section
**Can this information be voluntarily communicated to the health authority? If so, what information is flowing?**

## Describe the issue

There is an extra character "N" at the beginning of the sentence:

"NAfter a red tile warning (high risk) you should quarantine and have a PCR test taken immediately."

## Suggested change

In https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq.json change the sentence to
"After a red tile warning (high risk) you should quarantine and have a PCR test taken immediately."
by removing the character "N".

Perhaps you have other planned updates for Event Check-In? If not, please let me know and I will create a PR for this typo.

**Comment by MikeMcC399** [comment]
I created PR #1122 to clean up this typo.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.
