### ISSUE TITLE
iOS screenshot in Android screenshot section

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1121]
## Where to find the issue
https://www.coronawarn.app/de/screenshots/
https://www.coronawarn.app/de/screenshots/
Android screenshots - section "Check In".

## Describe the issue
First picture is from iOS, not from Android.

## Suggested Change
Replace the iOS screenshot by one from Android.

**Comment by dsarkar** [comment]
Fixed.

**Comment by Ein-Tim** [comment]
Fixed in #1126
