### ISSUE TITLE
RKI: CWA English language page not updated since Jan 2021

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1127]
## Where to find the issue

**Interrupt chains of infection digitally with the Corona-Warn-App**
https://www.rki.de/EN/Content/infections/epidemiology/outbreaks/COVID-19/CWA/CWA.html

## Describe the issue

The information on the RKI page https://www.rki.de/EN/Content/infections/epidemiology/outbreaks/COVID-19/CWA/CWA.html is outdated.

The last app version to be described on this page is version 1.9 released on December 16, 2020.

The page has a date-stamp 18.01.2021.

## Suggested change

Either:
- update this page with current information corresponding to the CWA Version 2.0 released on April 21, 2021
- mark the page as obsolete and no longer being maintained with current information (and in which case add a link to the equivalent German language page for current information)

**Comment by MikeMcC399** [comment]
The page RKI English-language page:

**Interrupt chains of infection digitally with the Corona-Warn-App**
https://www.rki.de/EN/Content/infections/epidemiology/outbreaks/COVID-19/CWA/CWA.html

now shows a date 28.04.2021 and includes information regarding the version 2.0 previously released on April 21, 2021 (see https://www.coronawarn.app/en/blog/2021-04-21-corona-warn-app-version-2-0/ ).

Since the suggested change to "update this page with current information corresponding to the CWA Version 2.0 released on April 21, 2021" has been carried out, I will close this issue.

---
The page has not been updated with information for the release 2.1 from yesterday, May 2, 2021 (https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/). That should be monitored, independently of this issue.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.

**Comment by MikeMcC399** [comment]
**Interrupt chains of infection digitally with the Corona-Warn-App**
https://www.rki.de/EN/Content/infections/epidemiology/outbreaks/COVID-19/CWA/CWA.html

which still shows CWA version 2.0, will now need to be updated to CWA version 2.2.

https://www.coronawarn.app/en/blog/2021-05-12-corona-warn-app-version-2-2/

**Comment by MikeMcC399** [comment]
**Interrupt chains of infection digitally with the Corona-Warn-App**
https://www.rki.de/EN/Content/infections/epidemiology/outbreaks/COVID-19/CWA/CWA.html

has been updated to CWA version 2.2.

(Status date at bottom of page: 17.05.2021.)
