### ISSUE TITLE
[Overview] Enhance https://www.coronawarn.app/en/eventregistration

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#1138]
## Feature description

Enhance https://www.coronawarn.app/en/eventregistration/:

1. Feature/Buttons: "Download PDF file", "Download PNG file"
1. Feature/Button: "Show QR code fullscreen"
Might be interesting for shops using a tablet: Create code and immediately show it in fullscreen to visitors
1. Feature/textfield: Create a batch of QR codes into one single PDF file from a comma-separated value string (pasted into a text-field)
1. Feature/Button: "Show _Rolling_ QR code": Create automatically e.g. every hour a new QR code and show fullscreen (auto-refresh)

**Comment by heinezen** [comment]
I propose we make individual issues for each enhancement idea.

1. The community can discuss each feature individually
2. We can put more details and references about the feature in these issues. For example, for "Download PDF" we could link to the poster specification or the code currently being created in https://github.com/corona-warn-app/cwa-event-qr-code/pull/5
3. We can link them in the general overview https://github.com/corona-warn-app/cwa-wishlist/issues/479

When we then decide to implement the feature, we would already have a bunch of feedback. And if a community member wants to do it, they would have more information to start from.

**Comment by dsarkar** [comment]
@Ein-Tim Sure. Just collecting rough ideas for the moment. I understand there will be a lot of suggestions, so this can be used as a starting point for ideas. Of course, each idea should be discussed and developed in separate issues.

**Comment by dsarkar** [comment]
@heinezen @Ein-Tim Haha ... It was you, @heinezen ;-)

**Comment by Ein-Tim** [comment]
@dsarkar 

Our profile pictures are quite similar (;
Do you want to keep this issue open? 
I'll follow up with at least 3 issues reg. the generator today and I'd say we can use https://github.com/corona-warn-app/cwa-wishlist/issues/479 for the overview. 
But as you like (:
Enjoy the nice weather!

**Comment by dsarkar** [comment]
@Ein-Tim Sure, sounds good. I will close this issue.
