### ISSUE TITLE
Typo in eventregistration

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-website#1139]
## Where to find the issue
https://www.coronawarn.app/de/eventregistration/

## Describe the issue
Typo: Weder die von Ihnen generierten QR-Codes noch die darin enthaltene Informationen werden an die Server der Corona-Warn-App gesendet.

## Suggested change
Weder die von Ihnen generierten QR-Codes noch die darin enthaltenen Informationen werden an die Server der Corona-Warn-App gesendet.

**Comment by Ein-Tim** [comment]
This has been addressed in #1147.

**Comment by heinezen** [comment]
Sorry we merged our own fix by accident and not your PR. The result is the same: It's fixed now :)

----
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment]
> 
> 
> Sorry we merged our own fix by accident and not your PR. The result is the same: It's fixed now :)
> 
> Corona-Warn-App Open Source Team

OK. Thanks for the appology.
