### ISSUE TITLE
QR-Code should not change when "Download" is pressed

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1144]
## Where to find the issue
https://www.coronawarn.app/de/eventregistration/
https://www.coronawarn.app/en/eventregistration/

## Describe the issue
The QR-Code changes when the download button is pressed.
This could result in a situation where the person who created the QR-Code checks in to the QR-Code shown on the website after he/she downloaded the QR-Code and thus he/she checks in to another event than the people who check in with the QR-Code which was downloaded.
The event will have the same name and the user can't tell a difference, but it's another event. 
Thus, in case of an infection, the person who checked in to the QR-Code shown on the website won't be warned.

## Suggested change
Deactivate [`b7d04d8` (#1132)](https://github.com/corona-warn-app/cwa-website/pull/1132/commits/b7d04d820370a58e69eb9f060438646f0caf911f) for the "Download" button.

## Related issue 
- #1137

**Comment by rugk** [comment]
> Deactivate b7d04d8 (#1132) for the "Download" button.

As I'm not sure what that means:

IMHO the QR code should just not be regenerated when clicking _Download_ or _Generate_.

**Comment by Ein-Tim** [comment]
@rugk 

I think that this commit changed the behavior so that the QR-Code always changes if the content of the fields change (intended) but the QR-Code also changes when the Download/Generate button is pressed (unintended).
