### ISSUE TITLE
Show QR code in fullscreen

### ISSUE THREAD

**Issue by heinezen** [corona-warn-app/cwa-website#1150]
## Feature description

Add an option to show a generated QR code in fullscreen view.

## Problem and motivation

Might be interesting for shops using a tablet or another digital screen.

---
Internal Tracking ID: [EXPOSUREAPP-14227](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14227)

**Comment by fynngodau** [comment]
There is a similar wishlist item for a similar request for the mobile apps: https://github.com/corona-warn-app/cwa-wishlist/issues/458

**Comment by przybciu** [comment]
Can I work on this? I already have an idea
