### ISSUE TITLE
Batch creation of QR codes

### ISSUE THREAD

**Issue by heinezen** [corona-warn-app/cwa-website#1151]
## Feature description

Create multiple QR codes at once from user input. The user input could be a comma-separated value string pasted into a text field. The QR codes could be downloaded individually, as a zipped file or merged as a single PDF.

## Problem and motivation

Users who need to create QR codes for multiple rooms will have a much easier time generating them.

**Comment by MikeMcC399** [comment]
@heinezen 

There is a feature described in the repository https://github.com/corona-warn-app/cwa-event-qr-code and in the instructions on https://www.coronawarn.app/en/event-qr-code-guide/ which say:

"**How do I use the official Corona-Warn-App QR code tool?**

This step-by-step guide will help you to create QR codes one by one or several QR codes at once."

It was announced in the blog [Event registration: Project team releases additional features](https://www.coronawarn.app/en/blog/2021-04-23-qr-code-generator/)

Does this answer your enhancement request?

**Comment by dsarkar** [comment]
@MikeMcC399  As an alternative means, we have additionally prepared a PR to create multiple event QR codes via the web interface. Input of the data will be via loading a CVS file. I expect that we can merge that one soon.

**Comment by MikeMcC399** [comment]
@dsarkar 

I guess that the following PR is the one which you were referring to:

- https://github.com/corona-warn-app/cwa-website/pull/2105

I see on https://www.coronawarn.app/en/eventregistration/#multi that there is an option "Generate multiple QR codes" and on https://www.coronawarn.app/de/eventregistration/#multi "Mehrere QR-Codes erstellen".

So perhaps now this enhancement request can be closed?

**Comment by heinezen** [comment]
@MikeMcC399  Works for me! I consider it implemented :)
