### ISSUE TITLE
Align Start/Ende to android app, fix date pattern to TT.MM.JJJJ

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-website#1153]
## Where to find the issue
https://www.coronawarn.app/de/eventregistration/
Switch Ort/Event e.g. to Vereinsaktivität.

## Describe the issue

The German "Endzeit" means something different: See https://www.duden.de/rechtschreibung/Endzeit . Maybe "Enduhrzeit" could be used.
While comparing with the android app, I think "Beginn" and "Ende" would be better.

Furthermore, the pattern for the date should be TT.MM.JJJJ.

## Suggested change
While comparing with the android app, I think "Beginn" and "Ende" would be better.

Furthermore, the pattern for the date should be TT.MM.JJJJ.

**Comment by svengabr** [comment]
Should the English version remain unchanged then?

```
"starttime": "Start time",
"endtime": "End time",
```

**Comment by DerVogel2020** [comment]
> Should the English version remain unchanged then?
> 
> ```
> "starttime": "Start time",
> "endtime": "End time",
> ```

Good point. See #1159.

**Comment by svengabr** [comment]
The pull request was merged, thank you very much for cour contribution @DerVogel2020
