### ISSUE TITLE
Up/down buttons for length of issue don’t work

### ISSUE THREAD

**Issue by rugk** [corona-warn-app/cwa-website#1155]
## Where to find the issue

https://www.coronawarn.app/de/eventregistration/
https://www.coronawarn.app/en/eventregistration/

## Describe the issue

Go to https://www.coronawarn.app/en/eventregistration/
Click the up or down button in the “Typical length of stay (minutes)” field:

![grafik](https://user-images.githubusercontent.com/11966684/116011541-d73c8300-a625-11eb-95d1-a31abda89298.png)

Even if you enter a value like 0 or 15 I cannot press the buttons, respectively they do nothing.

Furthermore, I can enter a negative number even though the `min=0` value is set in HTML:
![grafik](https://user-images.githubusercontent.com/11966684/116011682-7792a780-a626-11eb-98c1-0a5d4f076640.png)

## Suggested change

Fix the issue.

Firefox 88

**Comment by heinezen** [comment]
This worked in Firefox 87 btw. Just upgraded and I have the same issue as you.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Can't reproduce in Safari on Mac OS.

**Comment by bastianjoel** [comment]
This is an issue with the webbrowser. The properties of the input Element are set correctly.

There is already an issue #1143 that suggests adding pickers to the form.

**Comment by rugk** [comment]
Another detail: Scrolling in the input field works, just not clicking the buttons… Strange… :thinking:

**Comment by heinezen** [comment]
I've encountered this on Ubuntu 20.10 and Windows 10.

I also found the same bug report on another (very weird) website: https://gitmemory.com/issue/twbs/bootstrap/33725/825602758 (warning: TLS is broken on this site). So this might be a Firefox problem.

@rugk Can you file a bug report for Firefox? Looks like we cannot do much here.


----
Corona-Warn-App Open Source Team

**Comment by rugk** [comment]
Just filed a WebCompat bug first: https://github.com/webcompat/web-bugs/issues/72092

Let’s see what they say…
