### ISSUE TITLE
Datenschutz-Folgenabschätzung does not cover Switzerland or Event registration

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1165]
## Where to find the issue

[Datenschutz-Folgenabschätzung](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf)
Bericht zur Datenschutz-Folgenabschätzung für die Corona-Warn-App der Bundesrepublik Deutschland
Öffentliche Version
Version 1.7, 02.03.2021

## Describe the issue

The [Datenschutz-Folgenabschätzung](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf) covers the CWA app version only up to version 1.13 of the app which was released on March 4, 2021 https://www.coronawarn.app/en/blog/2021-03-04-corona-warn-app-version-1-13/.

In the meantime there have been further releases which each add functionality to be considered in the document:

Release | Date | Functionality
--- | --- | ---
[1.14](https://www.coronawarn.app/en/blog/2021-03-09-corona-warn-app-version-1-14/) | March 9, 2021 | Contact Journal enhancements
[1.15](https://www.coronawarn.app/en/blog/2021-03-24-corona-warn-app-version-1-15/) | March 24, 2021 | Connection to Switzerland
[2.0](https://www.coronawarn.app/en/blog/2021-04-21-corona-warn-app-version-2-0/) | April 21, 2021 | Event registration

## Suggested change

The [Datenschutz-Folgenabschätzung](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf) should be updated to cover all new aspects introduced into the app from version 1.14 onwards, including the connection to Switzerland and Event registration.

---
Internal Tracking ID: [EXPOSUREAPP-6779](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6779)

**Comment by MikeMcC399** [comment]
Here are some additional minor comments on:
[Datenschutz-Folgenabschätzung](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf)
Bericht zur Datenschutz-Folgenabschätzung für die Corona-Warn-App der Bundesrepublik Deutschland
Öffentliche Version
Version 1.7, 02.03.2021

1. The date on the title page for version 1.7 (02.03.2021) does not agree with the date listed on page 3 in the Änderungshistorie, where it shows 1.7 with a date of 23.02.2021.
2. The abbreviation for the "European Federation Gateway Service" EFGS is incorrectly written as EFSG on pages 123 und 128.

Since these are only minor issues, I did not want to create a separate issue for them.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal Tracking ID: [EXPOSUREAPP-6779](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6779)

**Comment by MikeMcC399** [comment]
The published [Datenschutz-Folgenabschätzung](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf)
Bericht zur Datenschutz-Folgenabschätzung für die Corona-Warn-App der Bundesrepublik Deutschland
Öffentliche Version

has been updated to 
Version 1.12, 11.05.2021

and it covers all released app versions. The latest released version is 2.2.

This issue is therefore resolved and can be closed.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks!

**Comment by MikeMcC399** [comment]
The comments:

1. The date on the title page for version 1.7 (02.03.2021) does not agree with the date listed on page 3 in the Änderungshistorie, where it shows 1.7 with a date of 23.02.2021.
2. The abbreviation for the "European Federation Gateway Service" EFGS is incorrectly written as EFSG on pages 123 und 128.

were not addressed in V1.12 of the document however. I'm just making a note here, but again I will not follow this up further.

**Comment by dsarkar** [comment]
@MikeMcC399

**Comment by MikeMcC399** [comment]
@dsarkar 
Was the previous comment supposed to be a message to me?
