### ISSUE TITLE
Release date for rapid testing?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1171]
## Background

According to https://www.coronawarn.app/en/blog/2021-03-31-corona-warn-app-test-integration/

"The federal government's Corona-Warn-App is getting another important feature. In the future, the app will integrate rapid COVID-19 tests. Users can save the confirmation of their test in the app and add them to the contact diary. In addition, anyone who tests positive for COVID-19 through a rapid test will also be able to warn contacts via the Corona-Warn-App in the future."

and

"The rapid test-function is supposed to be available in the second half of April. SAP and Deutsche Telekom will provide further information on the details here soon."

## Your Question

Is the rapid test function going "to be available in the second half of April"? If not, then the blog should be updated.

**Comment by dsarkar** [comment]
@MikeMcC399 Ok, noted. Thanks.

**Comment by MikeMcC399** [comment]
**Federal Government integrates rapid COVID-19 tests into Corona-Warn-App**
https://www.coronawarn.app/en/blog/2021-03-31-corona-warn-app-test-integration/ has been superseded by 

**Project team integrates rapid COVID-19 tests into Corona-Warn-App version 2.1**
https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/ dated May 2, 2021

**Eight partners participate from the beginning**

Deutsche Telekom and SAP’s project team have integrated the [announced rapid COVID-19 tests](https://www.coronawarn.app/en/blog/2021-03-31-corona-warn-app-test-integration/) in the Corona-Warn-App’s latest version (2.1) launching today. Users can now break infection chains and warn their fellow citizens even faster. The update will be available to all users within the next 48 hours."

The issue about the release date is therefore resolved through the release today.

This issue can therefore be closed.
