### ISSUE TITLE
FAQ - Make it more clear which QR code type an entry refers to

### ISSUE THREAD

**Issue by heinezen** [corona-warn-app/cwa-website#1172]
## Where to find the issue

Everywhere in the FAQ where "QR code" is mentioned.

- https://www.coronawarn.app/en/faq/#who_can_help
- https://www.coronawarn.app/en/faq/#international_phone_numbers
- https://www.coronawarn.app/en/faq/#check_in_index
- https://www.coronawarn.app/en/faq/#check_in_implementation
- https://www.coronawarn.app/en/faq/#check_in_which_places_and_events
- https://www.coronawarn.app/en/faq/#check_in_misuse
- https://www.coronawarn.app/en/faq/#check_in_%20prevent_false_warnings
- https://www.coronawarn.app/en/faq/#check_in_privacy
- https://www.coronawarn.app/en/faq/#check_in_qr_code
- https://www.coronawarn.app/en/faq/#check_in_qr_warning
- https://www.coronawarn.app/en/faq/#qr_scan
- https://www.coronawarn.app/en/faq/#qr_test
- https://www.coronawarn.app/en/faq/#cause9002_recovery
- https://www.coronawarn.app/en/faq/#QRcodes
- https://www.coronawarn.app/en/faq/#new_device
- https://www.coronawarn.app/en/faq/#result_time
- https://www.coronawarn.app/en/faq/#test_multiple_devices
- https://www.coronawarn.app/en/faq/#sick_leave
- https://www.coronawarn.app/en/faq/#hearing_impaired

...and their german counterparts

## Describe the issue

With CWA 2.0 the app uses two types of QR codes

- Test Result QR code
- Event Registration QR code

Most entries still contain the wording "***the*** QR code" when they actually mean the test result QR code. This might confuse users who are searching for a solution for errors in the event registration and get the wrong instructions. One example where this could happen is https://www.coronawarn.app/en/faq/#qr_scan. We might run into more ambiguity issues later with sentences like "Scan the QR code you received at the doctor's office" which could refer to both the test result QR code and the event location QR code.

More QR code types may follow with other features, so the solution should be future proof.

## Suggested change

Clarify which QR code type is meant.

- Always name the correct QR type in the heading
- In the entry text, name the QR code type explicitely if it would be ambiguous otherwise
- Ideally the QR code type names should be short, e.g.
    - PCR-Test QR code
    - Event QR code
- Instruction "scan the QR code" could additionallly tell the user where to find the correct scanner (we can use enumerated lists like in the other entries)
- Add an FAQ entry that explains the differencce between the QR codes(?) (I guess we only need this if the entries are still confusing after the changes)

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 

The ambiguity between QR codes of test documents and QR codes to check in to an event or place already exists in the current 2.0 release.

The 2.1 release branch introduces another type of QR code for rapid testing. The app refers to the tests as "rapid antigen tests" or "rapid test", however when scanning it just says "QR Code Scan" independently of which type of QR test code is being scanned. The user does not need to select a different button depending on the type of QR test code being scanned. The app works out which type of QR test code has been scanned after reading the scanned data.

**Comment by heinezen** [comment]
@MikeMcC399 Oops, I actually meant 2.0. But we already have it on our radar for 2.1 as well :)
