### ISSUE TITLE
Capitalize German locations

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-website#1179]
## Where to find the issue
https://www.coronawarn.app/de/eventregistration/ in selection of Ort/Event: "öffentliche Gebäude", "anderer Ort", "private Feier" and "anderes Event"

## Describe the issue
First letters are not writen as majuscile.
Change "öffentliche Gebäude" to "Öffentliches Gebäude" as it is in both apps.

## Suggested change
Capitalize all named locations, see also https://github.com/corona-warn-app/cwa-wishlist/issues/491

**Comment by DerVogel2020** [comment]
Closed, because #1180 won't be merged for convention reasons.

**Comment by dsarkar** [comment]
@DerVogel2020 Thanks.


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Please reopen, it seems like the opinion has changed. They will capitalize it starting in version 2.3: https://github.com/corona-warn-app/cwa-app-android/pull/3177

**Comment by DerVogel2020** [comment]
IMHO, this (= #1270) can be merged before the text changes in both apps in CWA 2.3.
