### ISSUE TITLE
QR-Code Generation Typical length of stay is not strongly enforced

### ISSUE THREAD

**Issue by thomasaugsten** [corona-warn-app/cwa-website#1192]
## Where to find the issue
https://www.coronawarn.app/en/eventregistration/

## Describe the issue
Typical length of stay is not strongly enforced you can override manually the max value of 3600

## Suggested change
Check in NodeJs if the value over the limit and return an error

**Comment by thomasaugsten** [comment]
@bastianjoel  Do you have the time for this fix?

**Comment by bastianjoel** [comment]
@thomasaugsten Yes, but not until tomorrow. 

I could fix this together with the implementation of #1143.
