### ISSUE TITLE
Change "öffentliche Gebäude" to "öffentliches Gebäude"

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-website#1193]
## Where to find the issue

https://www.coronawarn.app/de/eventregistration/ in selection of Ort/Event: "öffentliche Gebäude"

## Describe the issue

Change "öffentliche Gebäude" to "öffentliches Gebäude" as it is in both apps.

**Comment by dsarkar** [comment]
@DerVogel2020 Thanks. Needs to be fixed.

---
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment]
Fixed in #1194 and merged to master.
