### ISSUE TITLE
`rapid_test` needs update

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1195]
## Where to find the issue
https://www.coronawarn.app/de/faq/#rapid_test
https://www.coronawarn.app/en/faq/#rapid_test

## Describe the issue
This entry is outdated with the release of version 2.1, which integrated quick tests into CWA.

## Suggested change
Move this entry up to the "Rapid antigen test" section and use it as an index, similar to https://www.coronawarn.app/en/faq/#check_in_index, as discussed with @dsarkar before.

**Comment by MikeMcC399** [comment]
You are right that this article should be updated.

Another suggestion would be to leave the article where it is and link it to the group link  https://www.coronawarn.app/en/faq/#rapid_antigen_test and to the blog announcement for 2.1 https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/

I'm not sure if an additional link list is necessary.

**Comment by Ein-Tim** [comment]
I am working on this and will do the following:

Move entry to resolved section and link to blog post & FAQ-section. I agree with @MikeMcC399 that we don't need another index.

Hope that's fine with you @dsarkar!

Enjoy this nice Saturday everyone!

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 OK, we can do this for now. Should this grow bigger, we still can create an index. Thanks.
