### ISSUE TITLE
CSP inline style on brave-browser

### ISSUE THREAD

**Issue by JProof** [corona-warn-app/cwa-website#120]
## Where to find the issue
Request via Browser
https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf
(from https://www.coronawarn.app/de/ )

## Describe the issue
Brave-Browser is configured more strict to respect the CSP Rules.

## Suggested change
Fix the Response Header CSP Rule to allow safe inline-styles
![FireShot Screen Capture #006 - 'Open-Source-Projekt für Corona-Warn-App' - www_coronawarn_app](https://user-images.githubusercontent.com/12245927/85267838-061e2180-b476-11ea-93ad-b3947a89f50b.png)
![FireShot Screen Capture #005 - 'cwa-datenschutz-folgenabschaetzung_pdf' - www_coronawarn_app](https://user-images.githubusercontent.com/12245927/85267843-06b6b800-b476-11ea-9824-9a4ada5665f5.png)

**Comment by JProof** [comment]
the inline-styles will be render in by the browser not by the website! sry ...

**Comment by tkowark** [comment]
Thanks for bringing up that issue. We even discussed this with folks at Google and their will supposedly be a fix available in one of the upcoming Chrome versions. In the meantime, either opening in another browser or disabling the internal preview (chrome://settings/content/pdfDocuments) might help
