### ISSUE TITLE
Add an overview for rapid test partners

### ISSUE THREAD

**Issue by kannicht** [corona-warn-app/cwa-website#1202]
## Feature description

As of version 2.1 Antigen-Rapid-Test results can be obtained by the CWA. Even though there are only few partners at the moment an overview on the website (and maybe in the app) of all current partners.

## Problem and motivation

The problem is that people don't know wether their local test center is included in the CWA. 

People don't want to check the press releases on a regular basis and prefer to have a comprehensive overview.

## Is this something you're interested in working on

Unfortunately my coding skills don't allow me to help on this feature.

---
Internal Tracking ID: [EXPOSUREAPP-7043](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7043)
Internal Tracking ID: [EXPOSUREAPP-7342](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7342)

**Comment by dsarkar** [comment]
@kannicht Thanks for the suggestion. Internal Tracking ID: [EXPOSUREAPP-7043](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7043)

---
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment]
May be it should be moved to wishlist. I think it's also a nice feature for both apps.

**Comment by MikeMcC399** [comment]
It would probably be better to leave this request here on the website and add a separate item on the wishlist to have the list of Rapid Antigen Test partners available in the app. That way the two types of requests (website and app) are decoupled from each other.

**Comment by dsarkar** [comment]
@MikeMcC399 agreed.

**Comment by DerVogel2020** [comment]
> It would probably be better to[...] add a separate item on the wishlist 

Done: https://github.com/corona-warn-app/cwa-wishlist/issues/498

**Comment by DerVogel2020** [comment]
This had been resolved in #1203 and #1205.

**Comment by MikeMcC399** [comment]
@DerVogel2020 
> This had been resolved in #1203 and #1205.

According to https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/ there are currently 8 partners offering integrated rapid COVID-19 tests and a further 125 requests for integration have been received.

If anything like the number of 125 is reached, then a separate place to list all these organizations would be helpful.

**Comment by Ein-Tim** [comment]
One more partner seems to be integrated now: https://landing.ticket.io/news/corona-warn-app-ticket-io-kooperieren-im-kampf-gegen-corona

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Cross-Checking.

**Comment by kannicht** [comment]
@dsarkar 

Can confirm that. Had a Test yesterday at testing site which uses their backend.

Even though I was unable to scan the QR-Code when I got the result from their webpage I had the possibility to add the result in the CWA.

**Comment by dsarkar** [comment]
@kannicht Thank you very much for the info!

**Comment by DerVogel2020** [comment]
> 
> 
> One more partner seems to be integrated now: https://landing.ticket.io/news/corona-warn-app-ticket-io-kooperieren-im-kampf-gegen-corona

If all testing sites using their backend will be listed, the list would be very long since there are very much partners, using the ticket.io-backend for integrating with CWA.
See https://www.google.com/search?q=ticket.io%20schnelltest .

**Comment by Ein-Tim** [comment]
And one more: https://www.presseportal.de/pm/156361/4932908 (https://www.covisa.de)

**Comment by Ein-Tim** [comment]
Is this what you have been asking for: https://map.schnelltestportal.de

**Comment by Ein-Tim** [comment]
Could this been closed because of www.schnelltestportal.de?

**Comment by MikeMcC399** [comment]
@dsarkar 
It does seem that the request has been fulfilled through https://map.schnelltestportal.de/ which is linked to by:

- https://www.coronawarn.app/en/faq/#where_can_i_get_tested "Where can I get tested?"
- https://www.coronawarn.app/de/faq/#where_can_i_get_tested "Wo kann ich mich testen lassen?"

**Comment by Ein-Tim** [comment]
@dsarkar I suggest to close this issue now.

**Comment by Ein-Tim** [comment]
@dsarkar Please close this issue.
