### ISSUE TITLE
Blog: Whitespace below footer in blogentries

### ISSUE THREAD

**Issue by JNSOFF** [corona-warn-app/cwa-website#1207]
## Where to find the issue
https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/
And all other blogentries

## Describe the issue
There is no whitespace under the footer on the other sites, so there shouldn't be whitespace under the footer in blogentries.

## Suggested change
Remove the `padding-bottom: 4rem;` from the `<section>` / Add a CSS-Class for the `<section>` in blogentries where is now `padding-bottom: 4rem;` attribute.

---
Internal Tracking ID: [EXPOSUREAPP-7153](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7153)

**Comment by dsarkar** [comment]
@JNSOFF Thanks. Internal Tracking ID: [EXPOSUREAPP-7153](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7153). Best wishes, DS

---
Corona-Warn-App Open Source Team
