### ISSUE TITLE
Missing Rapid Antigen Test screenshots for English / iOS

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1217]
## Where to find the issue

https://www.coronawarn.app/en/screenshots/#ios_screenshots

## Describe the issue

Rapid antigen test image 7 of 10
Rapid antigen test image 6 of 10
text is displayed instead of images

https://www.coronawarn.app/assets/img/screenshots/en/iOS/rat_7.png and
https://www.coronawarn.app/assets/img/screenshots/en/iOS/rat_6.png

![image](https://user-images.githubusercontent.com/66998419/117262874-fde29100-ae51-11eb-8bc8-ff44583d4fbe.png)

## To reproduce

1. Open https://www.coronawarn.app/en/screenshots/ in Google Chrome desktop
2. Click on iOS Screenshots
3. Scroll down to section "Rapid antigen test"
4. Note that alt text 
Rapid antigen test image 7 of 10
Rapid antigen test image 6 of 10
is displayed instead of images.

## Suggested change

Something seems to have gone wrong with deployment as when I test this with an npm local clone everything works. I will take a deeper look to see if I can find what is going wrong.

**Comment by MikeMcC399** [comment]
@dsarkar 
This issue seems to have been fixed by https://github.com/corona-warn-app/cwa-website/pull/1218, so I will close the issue..

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks!
