### ISSUE TITLE
Add background running information to FAQ

### ISSUE THREAD

**Issue by Clauswgh** [corona-warn-app/cwa-website#122]
## Where to find the issue
No information in FAQ about running app in background is needed

## Describe the issue
In the FAQ is no information about if the app must be started and run in background to work or the exchange of the keys is managed by operation system and the app do the analysis of "infected" keys only. (maybe the wrong wording "infected" sorry)

## Suggested change
Add information to FAQ or better display the information in the app directly

**Comment by OlMue** [comment]
Hi @Clauswgh 
thanks. Could you be a bit more specific about the question you would like to include? We assume that people install and open the app at least once. As soon as they have completed the basic setup when starting the app for the first time, the exchange of random IDs happens in the background. This is also stated within the app.

In the FAQs, we collect questions that many users have as well as troubleshooting tips if something isn't working like it should. Examples: 

- [Will exposure logging still work when I close the app?](https://www.coronawarn.app/en/faq/#close_app)
- [Apple: My risk status hasn't been updated for over a day. An internet connection was available, what's wrong?](https://www.coronawarn.app/en/faq/#no_risk_update_ios)

So which would be the question you would like to include?

**Comment by Clauswgh** [comment]
@OlMue OK, the question is answered in "Will exposure logging still work when I close the app?" - but the information is missing in the FAQ inside the APP: 
Path to FAQ inside the App: Startscreen scroll down to "Häufige Fragen" tab on it to visit "www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392"
There I can't find anything about closing the app :-(

**Comment by tkowark** [comment]
Thanks for the clarification. This then seems to be more along the lines of corona-warn-app/cwa-documentation#289. Hence, we'll close it here in the Website repository (where the FAQ already is available) and work towards consolidating FAQs better in the overall Apps + Websites ecosystem.
