### ISSUE TITLE
Typo: Check-In

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-website#1227]
## Where to find the issue
https://www.coronawarn.app/de/eventregistration/

## Describe the issue
While grepping for https://github.com/corona-warn-app/cwa-app-android/issues/3120 I found 2 typos: Check-In is used instead of Check-in.

## Suggested change
Change the text to Check-in.

**Comment by DerVogel2020** [comment]
Fixed in #1228 .

**Comment by dsarkar** [comment]
@DerVogel2020 Thanks.


---
Corona-Warn-App Open Source Team
