### ISSUE TITLE
FAQ - Need to turn on iOS background app refresh explained

### ISSUE THREAD

**Issue by ringobowie** [corona-warn-app/cwa-website#126]
In faq/#no_risk_update_ios the user is informed to turn on background app refresh. I miss an explanation why this is necessary.
Is the background task used for automatic risk calculation purposes only or are there any other reasons this setting is needed? As risk calculation can be triggered manually, one could mention this as an alternative maybe?

And, btw, there is another option to disable background app refresh in iOS. If you use Family Sharing and the Screentime feature to eg. control your kids device usage, you can disable background app refresh by setting "background app activities" in "screentime" -> "family, kids name..." -> "content & privacy restrictions" to "don't allow".

**Comment by ringobowie** [comment]
As to why I ask this, is my wife told me, she heard an interview  with a so called expert in radio today, who said it's crucial to activate background app refresh for the app to work in general. Also have a look at https://github.com/corona-warn-app/cwa-app-ios/issues/741 - this is another part of my confusion about this.

**Comment by MarlisFriedl** [comment]
Dear ringobowie,

thank you very much for your proposal. I'm very sorry to coming back to you only now.

In the meantime, the background app refresh was widely discussed and also improved. We updated #no_risk_update_ios and #no_risk_update accordingly, whenever there was an update to report.
To directly answer your question, see this  https://www.linkedin.com/pulse/corona-warn-app-software-update-f%25C3%25BCr-ios-harald-lindlar/ blog post, which is also linked in the FAQs.

Best regards,

MF

Corona-Warn-App Open Source Team
