### ISSUE TITLE
[Blog 2.2] Why is there v 1.14.1 shown for error reporting

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-website#1264]
## Your Question

* Website URL Path: https://www.coronawarn.app/de/blog/2021-05-12-corona-warn-app-version-2-2/ ![image](https://user-images.githubusercontent.com/73582096/118020854-e1b38800-b35a-11eb-9468-6cc78b203d3e.jpeg)
* Line / Paragraph: Nutzer*innen können einen Fehlerbericht in der Corona-Warn-App erstellen (only german Version)
* Question: The version is 14.4.1, there something probably went bad.

**Comment by MikeMcC399** [comment]
@jucktnich 
>Question: The version is 14.4.1, there something probably went bad.

The version shown is 1.14.1 (0) which is just an older version than 2.2. You can see how long this functionality has been in the app but not released.

I think this should be a bug report, and perhaps somebody with an iOS 2.2 app installed could replace this screenshot with one from version 2.2 through a PR. I can only provide a screenshot for Android and I wouldn't want to mix up the two operating systems in one blog.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I'll do that with. Hope that's fine with you @jucktnich.

**Comment by jucktnich** [comment]
Yeah fine by me XD. I even don't have an iPhone with notch and you an XS right. This brings consistency.

**Comment by Ein-Tim** [comment]
Please take a look at #1265
