### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1268]
## Current Implementation
The website www.coronawarn.app only has a light mode.

## Suggested Enhancement
Most websites today (e.g. GitHub, WhatsApp Web, etc.) also offer a dark mode. This can be either switched on by the user or the theme of the OS is used.

## Expected Benefits
Better UX when pressing a link from the Corona-Warn-App (which offers a dark mode) to e.g. a FAQ entry and the dark mode is active.

## Additional Information
Low priority - probably something for a community contributor.

---
Internal Tracking ID: [EXPOSUREAPP-12722](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12722)

**Comment by molarya1** [comment]
@dsarkar Anybody currently tackling this one? If not, would love to take charge here

**Comment by ahodzic2** [comment]
@molarya1 It looks like they may be handling this one internally.

**Comment by dsarkar** [comment]
Hi @molarya1 and @ahodzic2, thanks a lot for your offer, however, let me first check, if we could accept such enhancement. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by molarya1** [comment]
@ahodzic2 @dsarkar Got it, no worries! Will be on standby if needed!

**Comment by MikeMcC399** [comment]
@molarya1 

Did you do any preparatory work on this before offering to take on this issue? I would be interested to know if you looked at the feasibility and impact of introducing this functionality.

Some points which occurred to me:

- the coronawarn.app has no user profile to set preferences. How would the choice be determined?
- there has been a lot of effort lately to meet accessibility needs (see https://www.coronawarn.app/en/accessibility/) would adding a dark mode conflict with these changes?
- would any of the pages cause specific issues by introducing a dark mode?
- would there be an impact on the effort of maintaining the web if a specific light mode and dark mode were introduced?
- is there a list of browsers which this change should be tested against?

**Comment by Ein-Tim** [comment]
Just for the record:
This would definitely be a huge change which should not be done without testing all functionality of the page afterwards.
Regarding the accessibility: Adding a dark mode increases accessibility for people with weak eyesight, as dark colors are often more pleasant for their eyes.

**Comment by Ein-Tim** [comment]
@dsarkar Did you already get [feedback](https://github.com/corona-warn-app/cwa-website/issues/1268#issuecomment-1094324368)?

**Comment by larswmh** [comment]
Considering the remaining timespan of the project and the extensive effort needed to appropriately implement this enhancement, we decided against working on a dark mode any futher. 

Thanks for your understanding.
