### ISSUE TITLE
Privacy notice (EN) cross-reference error to 6 g

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1269]
## Where to find the issue

Privacy notice (EN) for CWA Version 2.2
https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf
5. What data is processed? 
e. Event data
4th paragraph starting "An entry will also be created ..."

https://github.com/corona-warn-app/cwa-documentation/issues/610 is related to this issue.

## Describe the issue

An unresolved reference is shown in the PDF https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf "**Error! Reference source not found..**"

"An entry will also be created in your contact journal by default. Sections 5 g. and **Error!
Reference source not found..** explain this in more detail."

## Suggested change

The Android text resolves the reference to "6.g.". Possibly this is a formatting issue and it should be "6 g." instead.

https://github.com/corona-warn-app/cwa-app-android/blob/595ab630dfad5ac1e29021c084c400054193a498/Corona-Warn-App/src/main/assets/privacy_en.html#L269-L273

"An entry will also be created in your contact journal by default. Sections 5 g. and 6.g. explain this in more detail. If you do not want to create an entry in your contact journal for an event or place, you can simply switch off this feature using the corresponding toggle switch."

The German PDF https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf does not show this issue and it includes the following text which lists "6 g.".

"Außerdem wird standardmäßig ein Eintrag in Ihrem Kontakt-Tagebuch angelegt. Die
Einzelheiten hierzu werden unter Punkt 5 g. und 6 g. erläutert."

---
Internal Tracking ID: [EXPOSUREAPP-7287](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7287)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal Tracking ID: [EXPOSUREAPP-7287](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7287)


---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-website/pull/1292

**Comment by MikeMcC399** [comment]
https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf no longer contains an error (was "Error! Reference source not found.."), thanks to PR #1292, so this issue can be closed.
