### ISSUE TITLE
FAQ: Bluetooth incompatibility does not mention introduction version

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1274]
## Where to find the issue

**[Google/Android] A card on my Start Screen is notifying me that my device is not or only partially compatible. What does this mean?**
https://www.coronawarn.app/en/faq/#incompatibility_warning

**[Google/Android] Auf meinem Hauptbildschirm werde ich gewarnt, dass mein Gerät nicht oder nicht vollständig kompatibel ist. Was bedeutet das?**
https://www.coronawarn.app/de/faq/#incompatibility_warning

## Describe the issue

The introduction of the functionality to check Bluetooth Low Energy compatibility has not been announced as tied to a particular release anywhere. This leaves users updating to CWA Android 2.2.x (the version where it was introduced) who are seeing an incompatibility message for the first time wondering if there is a bug in the app.

- The blog announcement https://www.coronawarn.app/en/blog/2021-05-12-corona-warn-app-version-2-2/ has no mention of the BLE compatibility check.
- The Android [release_info_strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/release/2.2.x/Corona-Warn-App/src/main/res/values/release_info_strings.xml) mentions only:
o "Record Troubleshooting Logs"
o "Create Rapid Test Profiles"
So also here in the App Information > New Features section of the app there is no mention of the new checks.

## Suggested change

Explain in the FAQ that this is a new check introduced with version 2.2 of the Android app. You could say that the Google Play Store checked previously for the presence of Bluetooth before allowing for installation, however the new check does a more detailed compatibility check compared to previous versions.

The suggestion was already made in https://github.com/corona-warn-app/cwa-website/pull/1211#pullrequestreview-652528871 by @Ein-Tim and the subject was raised again in https://github.com/corona-warn-app/cwa-app-android/issues/3170#issuecomment-841830041.

Maybe @fynngodau as the original author would like to pick this up as a PR? Or perhaps @Ein-Tim, who raised the flag previously? Please let me know if you need assistance.

**Comment by Ein-Tim** [comment]
I'm quite busy at the moment, so happy to leave this to @fynngodau if he has time. 🙂

**Comment by MikeMcC399** [comment]
I'd suggest the following simple addition, so I'll open a PR with this:

---
EN
Bluetooth compatibility checking and warnings were introduced with Android Corona-Warn-App version 2.2. 

---
DE
Bluetooth-Kompatibilitätsüberprüfungen und -Warnmeldungen wurden mit der Android Corona-Warn-App Version 2.2 eingeführt.

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/1275 opened.

**Comment by fynngodau** [comment]
Thanks @MikeMcC399

**Comment by MikeMcC399** [comment]
@fynngodau 
You raised the valid point that Bluetooth checks were done before V2.2.

I simplified the text in the FAQ to not mention those details, as the main point was to avoid users thinking there was a bug in the app. These would probably be users with older hardware which did not meet the BLE requirement, especially BLE peripheral mode.

I checked on a Pixel 3a emulator running API 29 (Android 10), which doesn't have Bluetooth.

CWA Android is only supported for distribution through the Google Play Store and if a user goes directly to https://play.google.com/store/apps/details?id=de.rki.coronawarnapp from a device with no Bluetooth, they will see the following:

![image](https://user-images.githubusercontent.com/66998419/118452609-9e5c6f00-b6f6-11eb-8f0b-bf2b545092a0.png)

Bypassing the Google Play Store, sideloading a version earlier than 2.2.1, such as 2.1.2 through an apk, then starting and attempting to activate exposure logging will bring up 

![image](https://user-images.githubusercontent.com/66998419/118453501-9650ff00-b6f7-11eb-896a-924fdf2c1dc6.png)

I think what is new for the user in 2.2.1 is that the app now catches and flags missing BLE peripheral mode.

I don't have any physical device without Bluetooth or a physical device without BLE peripheral mode, so I can't check that.

Anyway, as I responded in the PR, I think we can leave the updated FAQ as it is, unless you think that users will be confused.

**Comment by fynngodau** [comment]
@MikeMcC399 I meant something different: you could read that version 2.2 introduced "bluetooth warnings", as in "Bluetooth-based exposure notifications". So the phrasing could be improved a bit but it is also okay as is.

We will need to rework this for 2.3 to split it up into warnig for no advertising and no scanning (though I don't know or own any device where the latter is the case either, and you are right to mention that those devices should not be able to install the app at all – though OTAH, this could be changed to allow those devices, whichever they are, to at least use the other features)

**Comment by MikeMcC399** [comment]
@fynngodau
> I meant something different: you could read that version 2.2 introduced "bluetooth warnings", as in "Bluetooth-based exposure notifications". So the phrasing could be improved a bit but it is also okay as is.

I see what you mean now. I think the wording is OK in the context of the FAQ which is only about the compatibility warnings. 

> We will need to rework this for 2.3 to split it up into warnig for no advertising and no scanning (though I don't know or own any device where the latter is the case either, and you are right to mention that those devices should not be able to install the app at all – though OTAH, this could be changed to allow those devices, whichever they are, to at least use the other features)

I hadn't thought about allowing installation without Bluetooth. I'd like to check the wishlist and add an entry there if it is not already covered.

**Comment by MikeMcC399** [comment]
I've opened https://github.com/corona-warn-app/cwa-app-android/issues/3186 to remove the Google Play Store restriction on requiring BLE.
