### ISSUE TITLE
FAQ Section not updated on scrolling

### ISSUE THREAD

**Issue by tkowark** [corona-warn-app/cwa-website#128]
## Where to find the issue
On the left hand side, the FAQ page has a list of 5 sections to simplify navigation.
https://www.coronawarn.app/de/faq/

## Describe the issue

When you scroll through the list, it is not updated according to the section you are currently looking at.

## Suggested change
Set the highlighting according to the current focus

**Comment by mfickers** [comment]
I am working on this issue.
