### ISSUE TITLE
Cypress still in use?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1282]
## Your Question
* Website URL Path: https://github.com/corona-warn-app/cwa-website/blob/master/README.md#testing
* Question: Is cypress still being actively used by the Open Source Team for website testing of https://www.coronawarn.app/ ?

https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/hotline_spec.js fails in cypress because the hotline phone number was updated without updating the cypress test routine.

```
  Running:  hotline_spec.js                                                                 (3 of 3)


  Test Hotline phone number
    1) Verify App and TAN Hotline


  0 passing (5s)
  1 failing

  1) Test Hotline phone number
       Verify App and TAN Hotline:
     AssertionError: Timed out retrying: Expected to find content: '+49 800 7540001' within the element: <div.link-item.col-6.col-md-4> but never did.
      at Context.eval (http://localhost:8000/__cypress/tests?p=cypress\integration\hotline_spec.js:10:53)

```

**Comment by MikeMcC399** [comment]
I opened PR #1289 to fix the failing cypress test.

It seems that the cypress test has not been acted on for the last 5 months, since the problem was introduced in January this year by PR https://github.com/corona-warn-app/cwa-website/pull/757.

I also found that sometimes 

`npm run test`

times out and that a second attempt to run it is sometimes successful. Perhaps this is connected to the issue I reported in https://github.com/corona-warn-app/cwa-website/issues/1168?

```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  eventregistration.js (658 KiB)
```

**Comment by MikeMcC399** [comment]
Cypress tests are now passing again, since PR #1289 has been merged.

I will leave this issue open for the time being in case there are any comments about using cypress or not.

**Comment by MikeMcC399** [comment]
A new issue has come up https://github.com/corona-warn-app/cwa-website/issues/1322, so again, the question whether cypress tests are still in use or whether their failure should be ignored?

If cypress is no longer being used, then it should be taken out of the [README.md](https://github.com/corona-warn-app/cwa-website/blob/master/README.md).

**Comment by svengabr** [comment]
Cypress was updated lately with some new pull requests that were approved. @MikeMcC399 do you think we could close this issue?

**Comment by MikeMcC399** [comment]
@svengabr 
The cypress tests are now completing successfully, so this issue can be closed.

```
  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ √  applink_spec.js                          00:08        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  blog_spec.js                             00:08        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  hotline_spec.js                          00:01        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  pages/eventRegistration.js               00:33        6        6        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    √  All specs passed!                        00:50       12       12        -        -        -

```
