### ISSUE TITLE
Issue count badge in README shows question count only

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1285]
## Where to find the issue

https://github.com/corona-warn-app/cwa-website/blob/master/README.md

## Describe the issue

The README.md contains code
`| **General discussion, issues, bugs**   | <a href="https://github.com/corona-warn-app/cwa-website/issues/new/choose" title="General Discussion"><img src="https://img.shields.io/github/issues/corona-warn-app/cwa-website/question.svg?style=flat-square"></a> </a>   |`

which displays the badge
https://img.shields.io/github/issues/corona-warn-app/cwa-website/question.svg?style=flat-square

![questions issues](https://user-images.githubusercontent.com/66998419/118632993-46466b00-b7d1-11eb-9760-192dc7f5c118.jpg)

and counts only issues with the [question](https://github.com/corona-warn-app/cwa-website/labels/question) label.

## Suggested change

If there are no objections I will submit a PR to change the link to
https://img.shields.io/github/issues/corona-warn-app/cwa-website?style=flat-square

which displays a count of all issues, including ones with the [question](https://github.com/corona-warn-app/cwa-website/labels/question) label.

![Issues badge](https://user-images.githubusercontent.com/66998419/118633181-7beb5400-b7d1-11eb-85e8-64834bbf2d73.jpg)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Your suggestion makes sense! Go ahead, please!

**Comment by MikeMcC399** [comment]
PR #1285 created, awaiting approval 😄
