### ISSUE TITLE
FAQ - Add small entry explaining the staged rollout

### ISSUE THREAD

**Issue by heinezen** [corona-warn-app/cwa-website#1287]
## Describe the issue

New releases are distributed to users over a 48 hour staged rollout in both app stores. The distance between the official release date from the blog post and the actual time users get the new version has lead to confusion in the past

## Suggested change

New entry `release_time`:

- There is a staged rollout that lasts 48 hours
- (Explain that it can be skipped on iOS?)
- Reasons fir staged rollout: early error detection, preventing critical bugs from affecting users

**Comment by MikeMcC399** [comment]
@heinezen 
If your organization has any influence on Google, please feedback that it would be good for the Google Play Store to allow manual overriding of the staged rollout like iOS allows.

This would allow testers and those urgently waiting for a fix to get earlier access for Android releases of CWA.

**Comment by Ein-Tim** [comment]
Do we want to mention that you can skip it under iOS? 
Pros: Users can faster get updates (which maybe fix bugs for them).
Cons: Entry will be longer and more complicated.
