### ISSUE TITLE
Add faq entry to explain "Ihr Browser ist nicht kompatibel. Bitte öffnen Sie den Link in Chrome".

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-website#1301]
## Feature description

Explain the mentioned text at the website after clicking a link to import a RAT result into CWA.

## Problem and motivation
After clicking a link similar to following after receiving a RAT result:
![Screenshot_20210526-201909_Firefox](https://user-images.githubusercontent.com/65366950/119711536-f23a2700-be5f-11eb-966e-cf8fdead0ad4.jpg)
the firefox browser on android 8 just opens the link in the browser so the following website is shown:

![Screenshot_20210526-113701_Firefox](https://user-images.githubusercontent.com/65366950/119711654-10a02280-be60-11eb-8f8c-06734cf8878e.jpg)

There are two possible solutions for the user:

1. installing chrome
2. hold on the "Ergebnis in App eintragen"-Link and click on "Link in externer App öffnen". This opens the CWA and after click on "Einverstanden" to approve the agreement and information the RAT result is imported in the CWA.

## See also related

https://github.com/corona-warn-app/cwa-wishlist/issues/532
https://github.com/corona-warn-app/cwa-event-landingpage/issues/23

## Is this something you're interested in working on

Yes, I can prepare a corresponding PR for the english and german faq if it's desired (and https://github.com/corona-warn-app/cwa-event-landingpage/issues/23 won't be fixed, see also EXPOSUREAPP-7379 and EXPOSUREAPP-7359 )

**Comment by Ein-Tim** [comment]
This problematic is also mentioned in https://www.coronawarn.app/en/blog/2021-05-11-how-to-rapid-test-integration/ at the very bottom.

**Comment by DerVogel2020** [comment]
Thanks @Ein-Tim . Hard to find 😆
These explanations should be included in the  faq entry.

**Comment by Ein-Tim** [comment]
@DerVogel2020 Do you still think this issue is relevant?

**Comment by DerVogel2020** [comment]
No, all fine now.
