### ISSUE TITLE
Add FAQ entry reg. compatibility of Android 12 Beta

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1305]
## Where to find the issue
--

## Describe the issue
The Android 12 Beta (at least the first one) seems to be incompatible to CWA, see https://github.com/corona-warn-app/cwa-app-android/issues/3295.

## Suggested change
Add a FAQ entry, similar to the one we had when iOS 14 was in Beta.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for opening!

I'm not sure that it has been proven that there is an incompatibility between CWA 2.2.1 and Android 12 beta 1. We probably need to find out a bit more before making this statement.

On the other hand it may be a good idea to get a statement from the Open Source Team about how they want to handle CWA running under Android 12 betas. Maybe they say they would be happy to get feedback from leading edge users in GitHub, and could handle feedback on a best-effort basis, but say don't call the telephone hotline with issues? 

According to https://developer.android.com/about/versions/12 platform stability is planned for August 2021 and final release at an unspecified date after that.

**Comment by LeQuadratico** [comment]
I have no problems on my device with the Android 12 Beta 1, so the issue only applies to some devices (if any).

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> I'm not sure that it has been proven that there is an incompatibility between CWA 2.2.1 and Android 12 beta 1. We probably need to find out a bit more before making this statement.

I absolutely agree with you on that! If it turns out that https://github.com/corona-warn-app/cwa-app-android/issues/3295 is only a problem for this user, we should not create a FAQ entry.

> On the other hand it may be a good idea to get a statement from the Open Source Team about how they want to handle CWA running under Android 12 betas. Maybe they say they would be happy to get feedback from leading edge users in GitHub, and could handle feedback on a best-effort basis, but say don't call the telephone hotline with issues?

👍 Maybe they also consider to add a FAQ entry similar to https://www.coronawarn.app/en/faq/#beta_ios which talks about the situation of betas under iOS.

Finally I want to say sorry if my comments came over rude today in https://github.com/corona-warn-app/cwa-app-android/issues/3295, this was definitely not my intention.

Have a nice evening, everyone!

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for the pointer to the iOS beta entry. If the Open Source Team agrees that would be a good template for Android.

You do not need to apologize for the tone of your comments in the technical issue. I think it is difficult to contribute to Android technical issues successfully if you do not have a reference Android device to look at.

**Comment by heinezen** [comment]
> :+1:  Maybe they also consider to add a FAQ entry similar to https://www.coronawarn.app/en/faq/#beta_ios which talks about the situation of betas under iOS.

I think, the FAQ entry was added when iOS betas had significant problems with ENF/CWA handling, so this article is also not as relevant anymore.

My proposal would be to add a general disclaimer about beta versions that covers both iOS and Android.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen 

Yes this was added for the iOS 14 Betas and after the final release the entry was adapted. 

We could change the text and the anchor (with a redirect) and make it more general to apply to iOS & Android. 

If you want to, I can take this over.

**Comment by heinezen** [comment]
@Ein-Tim On it!

But can you tell me: Is there any warning/notification in the CWA or by the OS if you use a beta version?

**Comment by Ein-Tim** [comment]
@heinezen 

No, AFAIK not. At least not under iOS.

**Comment by MikeMcC399** [comment]
@heinezen 
> But can you tell me: Is there any warning/notification in the CWA or by the OS if you use a beta version?

There is no warning under Android 12 beta, no. If you think that would be helpful, you could open a wishlist item. 🙂

**Comment by heinezen** [comment]
@Ein-Tim @MikeMcC399 Thank you for checking. I think that's actually okay to have no message. I've reformulated the FAQ entry to sound more like a general information notice.

**Comment by heinezen** [comment]
```
{
    "title": "I am testing a beta version of iOS/Android. What do I have to consider?",
    "anchor": "os_beta",
    "active": true,
    "textblock": [
        "Beta versions of the respective operating systems are not officially supported because they are still in development and not intended for productive operation. You can still use the app like normal, but you should be aware that you might encounter errors that are not present when using a release version of your operating system.",
        "However, if you exerience errors, you can feel free to point them or other incompatibilities out by opening an issue on Github:",
        "<ul><li><a href='https://github.com/corona-warn-app/cwa-app-ios/issues' target='_blank' rel='noopener noreferrer'>iOS Issue Tracker</a></li><li><a href='https://github.com/corona-warn-app/cwa-app-android/issues' target='_blank' rel='noopener noreferrer'>Android Issue Tracker</a></li></ul>"
    ]
},


{
    "title": "Ich teste eine Betaversion von iOS/Android. Was muss ich beachten?",
    "anchor": "os_beta",
    "active": true,
    "textblock": [
        "Betaversionen der jeweiligen Betriebssysteme werden nicht offiziell unterstützt, da sich die noch in der Entwicklung befinden und nicht für den produktiven Einsatz vorgesehen sind. Sie können die App weiterhin normal benutzen, sollten aber daran denken, dass möglicherweise Fehler auftreten, die in der Releaseversion Ihres Betriebssystems nicht vorhanden sind.",
        "Falls bei Ihnen solche Fehler auftreten, können sie diese oder andere Inkompatibilitäten jedoch gerne melden, indem Sie ein Github Issue erstellen:",
        "<ul><li><a href='https://github.com/corona-warn-app/cwa-app-ios/issues' target='_blank' rel='noopener noreferrer'>iOS Issue Tracker</a></li><li><a href='https://github.com/corona-warn-app/cwa-app-android/issues' target='_blank' rel='noopener noreferrer'>Android Issue Tracker</a></li></ul>"
    ]
},
```

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Since there is no proven incompatibility of the CWA app with the Android 12 beta, please consider changing the title of this issue.

Suggestion: change "incompatibility" to "compatibility".

**Comment by MikeMcC399** [comment]
@heinezen 

You should be able to create a PR for this independently of the work which @dsarkar is doing.

Here are some suggestions for corrections:

---
"You can still use the app like normal, but you should be aware that you might encounter errors that are not present when using a release version of your operating system."

"like normal" => "normally"
"release" => "released"

 "However, if you exerience errors, you can feel free to point them or other incompatibilities out by opening an issue on Github:"

"exerience" => "experience"
"Github" => "GitHub"

---
Betaversionen der jeweiligen Betriebssysteme werden nicht offiziell unterstützt, da sich die noch in der Entwicklung befinden und nicht für den produktiven Einsatz vorgesehen sind. 

"da sich die" => "da sie sich"

"Falls bei Ihnen solche Fehler auftreten, können sie diese oder andere Inkompatibilitäten jedoch gerne melden, indem Sie ein Github Issue erstellen:",

"sie" => "Sie"
"Github" => "GitHub"
