### ISSUE TITLE
Screenshots page: Missing screenshots of RAT profile 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1308]
## Where to find the issue
DE: https://www.coronawarn.app/de/screenshots/
EN: https://www.coronawarn.app/en/screenshots/

## Describe the issue
There are no screenshots of the RAT profile added in version 2.2. 

## Suggested change
Add some screenshots of the RAT profile.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
This issue seems to be a duplicate of https://github.com/corona-warn-app/cwa-website/issues/1257.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

It is closely related, but I'm asking to add some screenshots which show how the Rapid Test Profile is added and how it looks when it's added.
You've noticed that the profile is missing on some screenshots.

Should we merge the two issues?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I didn't describe that in the problem section, but I did write about it in the suggested changes of https://github.com/corona-warn-app/cwa-website/issues/1257

"Possibly also:

Add a screenshot of an example of Rapid Test Profile data entry screen and
Add a screenshot of an example of a completed Rapid Test Profile showing a QR code"

So let's leave your issue open as well, and just have them linked.

**Comment by larswmh** [comment]
@Ein-Tim 

> Still a valid issue, which is now older than a year. If there won't be any screenshots of the RAT profile added, please let us know.

A "Rapid Test Profiles" section was added on May 4th, 2022. 

- iOS: [Rapid Test Profiles](https://www.coronawarn.app/en/screenshots/#ios_rat_profiles)
- Android: [Rapid Test Profiles](https://www.coronawarn.app/en/screenshots/#android_rat_profiles)

I would therefore consider this issue as solved. Can this issue be closed?

**Comment by Ein-Tim** [comment]
Agreed @larswmh.

Closing as implemented.
