### ISSUE TITLE
[WIP] FAQ - Vaccination certificate 

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#1311]
Disclaimer: This is a preliminary version. Content still has to be verified and approved.
---

Edited:
- 210529 1930 based on @fynngodau s comments https://github.com/corona-warn-app/cwa-website/issues/1311#issuecomment-850815722  
- 210523 2015 some more EN translations.

Q&A - Basic information/Introduction
---
- [ ] 10
  - DE
**Was ist der digitale Impfnachweis?**
Ab Version 2.3 der Corona-Warn-App (CWA) können Sie ihren digitalen Impfnachweis in der CWA hinzufügen und so per 2D-Barcode (QR-Code) ihren Corona-Impfstatus bei Bedarf sicher und digital nachweisen. Die CWA zeigt den vollständigen Impfschutz 14 Tage nach der letzten benötigten Impfung an.  Der digitale Impfnachweis ist eine zusätzliche Möglichkeit, um Impfungen zu dokumentieren. Sie können damit Informationen wie Impfzeitpunkt und Impfstoff personalisiert bequem auf ihren Smartphones digital speichern. Die Nutzung des digitalen Impfnachweises in der CWA ist freiwillig. Sie können Ihre Corona-Impfung auch auf eine andere Weise nachweisen. 
  - EN
**What is the digital certificate of vaccination?**
 Starting with version 2.3 of the Corona-Warn-App (CWA), you can add your digital vaccination certificate in the CWA and thus securely and digitally prove your Corona vaccination status via 2D barcode (QR code). The CWA indicates the complete vaccination protection 14 days after the last required vaccination.  The digital vaccination certificate is an additional way to document vaccinations. Thereby you are able to digitally store information such as vaccination time and vaccine in a personalised manner on their smartphones. The use of digital certificate of vaccination in the CWA is voluntary. You can also prove your Corona vaccination in a different way.
- [ ] 11
  - comment (see below): Will this FAQ be published before the feature is released? Otherwise, the tense needs to be changed. -> we will publish FAQ after release. Changed tense!
  - DE
**Warum gibt es einen digitale Impfnachweis?**
Zu Beginn des Jahres wurde durch den Europäischen Rat beschlossen, einen interoperablen und standardisierten Impfnachweis für medizinische Zwecke auf den Weg zu bringen. Deutschland setzt diese europäische Entscheidung nun schnell um, um allen Bürgern, die dies wünschen, einen digitalen Impfnachweis zur Verfügung stellen zu können. Mittlerweile hat die Europäische Kommission auch einen Verordnungsentwurf zur Regelung eines EU-weiten Anerkennungsrahmens für (digitale) Zertifikate für Impfungen, Tests und für Personen mit COVID-19-Heilstatus vorgelegt, um die Reisefreizügigkeit zu erleichtern. Das grüne Zertifikat der EU bildet den Rechtsrahmen für die Lösungen der Mitgliedsstaaten.
- [ ] 17
   - comment, see below: These two (Q17 and 9) questions have very similar answers and should be merged. It is also partially overlapping with the question "Wie funktioniert der digitale Impfnachweis?". -> agreed. Merge articles.
   - comment, see below:  I think the latter question should be the third question after "Was ist…?" and "Warum gibt es…?", and then more questions could provide further details. You should know how it works before being told how to receive it. -> agreed. moved to # 3.
  - DE
**Wer kann einen elektronischen Impfnachweis erhalten?
Wie erhalte ich ein Impfzertifikat?
Wie kann ich, wenn ich bereits vollständigen Impfschutz haben, den Status nachträglich in die Corona-Warn-App übertragen?**
Alle Personen, die in einen Anspruch auf eine Impfung haben, können sich ergänzend zum analogen Impfnachweis auch einen digitalen Impfnachweis ausstellen lassen. 
Sie können gegebenenfalls ein Corona-Impfzertifikat von der Arztpraxis oder dem Impfzentrum erhalten, wo die Impfung vorgenommen wurde. Fragen Sie vor Ort ganz einfach nach. Die Impfzentren und die Arztpraxen sind jedoch nicht dazu verpflichtet, Impfzertifikate auszustellen. Zukünftig wird die Ausstellung eines Impfzertifikats auch in Apotheken möglich sein.
Es werden verschiedene Möglichkeiten geprüft, um auch nachträglich digitale Impfnachweise für Corona-Impfungen zu erstellen. Grundsätzlich soll die nachträgliche Ausstellung dort erfolgen, wo man geimpft worden ist. Wenn in den Impfzentren entsprechende Kontaktdaten vorliegen, sollen die 2D-Barcodes (QR-Codes) möglichst automatisch per Post zugesandt werden. Außerdem könnten Ärztinnen und Ärzte sowie Apothekerinnen und Apotheker nachträglich Impfnachweise ausstellen. 
- [ ] 9
  - delete this one, merge with Q17, see comment there.
  - DE
~**Wie kann ich, wenn ich bereits vollständigen Impfschutz haben, den Status nachträglich in die Corona-Warn-App übertragen?** 
Es werden verschiedene Möglichkeiten geprüft, um auch nachträglich digitale Impfnachweise für Corona-Impfungen zu erstellen. Grundsätzlich soll die nachträgliche Ausstellung dort erfolgen, wo man geimpft worden ist. Wenn in den Impfzentren entsprechende Kontaktdaten vorliegen, sollen die 2D-Barcodes (QR-Codes) möglichst automatisch per Post zugesandt werden. Außerdem könnten Ärztinnen und Ärzte sowie Apothekerinnen und Apotheker nachträglich Impfnachweise ausstellen.~
- [ ] 12
  - comment, see below: Maybe we could find a resource which provides further information here? -> ToDo, probably the best place is to look at the webpage of the ministry of foreign affairs of the corresponding countries. Maybe suggest this?
  - DE
**Kann ein vollständiger Impfstatus in der App als Berechtigung zum Reisen dienen?** 
Ob Sie mit einem vollständigen Impfschutz beispielsweise reisen dürfen, hängt von den Bestimmungen des jeweiligen Landes ab.  
- [ ] 14 
  - DE
**Wie funktioniert der digitale Impfnachweis?**
Der digitale Impfnachweis wird in der Arztpraxis oder in einem Impfzentrum generiert. Nach Eingabe oder Übernahme der Daten wird ein 2D-Barcode erstellt (QR-Code), den die Nutzer direkt abscannen können oder auf einem Papierausdruck mitbekommen und später einscannen können.
Der digitale Impfnachweis wird dann von den Nutzern über eine App, die kostenfrei zum Download bereitgestellt wird, auf dem Smartphone gesteuert. Damit wird nach der Impfung in einem Impfzentrum oder beim niedergelassenen Arzt ein sog. Impfbescheinigungstoken (2D-Barcode/QR-Code) abgescannt.
Die App speichert die Impfbescheinigung lokal auf dem Smartphone.
- [ ] 22
  - DE
**Kann ich den QR-Code auch ohne Internetverbindung vorzeigen?**
Ja. Sobald der QR-Code in der Corona-Warn-App angezeigt wird, können Sie ihn jederzeit ohne eine bestehende Internetverbindung vorzeigen.
  - EN
**Can I show the QR code without an internet connection?**
Yes, indeed. As soon as the QR code is displayed in the Corona-Warn-App, you can show it at any time without an existing internet connection.
- [ ] 13
  - DE
**Bin ich verpflichtet, den digitale Impfnachweis in der Corona-Warn-App zu nutzen?**
**Wird es trotzdem noch den gelben analogen Impfausweis geben?**
**Kann ich meinen gelben Impfpass auch weiterhin benutzen?**
**Was ist mit Personen, die kein Smartphone besitzen?**
Der digitale Impfnachweis per Corona-Warn-App ist lediglich ein vollkommen freiwilliges und ergänzendes Angebot. Wenn Sie keinen digitalen Impfnachweis besitzen oder diesen verloren haben, ist der Impfnachweis über das bekannte „gelbe Heft“ (gelber Impfpass) weiterhin möglich und gültig. Ausserdem können Sie Corona-Impfungen auch mit dem ausgedruckten Corona-Impfzertifikat für die vollständige Impfung nachweisen.
  - EN
**Am I obliged to use the digital certificate of vaccination in the Corona-Warn-App?**
**Will there still be the yellow analog vaccination booklet?**
**Can I continue to use my yellow vaccination booklet?**
**What about people who don't own a smartphone?**
The digital proof of vaccination via the Corona-Warn-App is a completely voluntary and complementary offer. If you do not have a digital certificate of vaccination or have lost it, the proof of vaccination via the well-known "yellow booklet" (yellow vaccination passport) is still possible and valid. You can also prove Corona vaccinations with the printed Corona vaccination certificate for full vaccination.
- [ ] 15
  - DE
**Wie soll der Nachweis einer Impfung geprüft werden können?**
Das Impfzertifikat (QR-Code) wird z.B. über die CovPass App oder die Corona-Warn-App (CWA) digital oder alternativ als maschinenlesbarer Ausdruck genutzt. Das Impfzertifikat enthält nur Informationen zum Impfstatus, den Namen des Geimpften und das Geburtsdatum. Für Dienstleister, die den Impfstatus überprüfen möchten, wird es eine Prüf-App zur Prüfung des Impfzertifikats geben. Damit kann der Impfstatus ähnlich wie ein Barcode eines Flug- oder Bahntickets gescannt werden. Alternativ ist ein Nachweis mit dem analogen Impfpass möglich.
  - EN
**How is the proof of vaccination verified?**
The vaccination certificate (QR code) is used digitally via the CovPass-App or the Corona-Warn-App (CWA) or alternatively as a machine-readable print. The vaccination certificate contains only information about the vaccination status, the name of the vaccinated person, and the date of birth. For service providers who want to check the vaccination status, there will be a verification app to check the vaccination certificate. This allows the vaccination status to be scanned in a similar way to a barcode of a flight or train ticket. Alternatively, proof with the analogue vaccination document is possible.
- [ ] 18
  - DE
**Kann man auch im digitalen Impfnachweis speichern, dass man bereits infiziert war oder negativ getestet wurde?**
Ja, auch negative Tests oder eine durchgemachte Infektion lassen sich in der CovPass- App und Corona-Warn-App als Testzertifikat bzw. Genesenenzertifikat hinterlegen. Eine durchgemachte Infektion wird mittels eines PCR-Test-Ergebnisses dokumentiert. 
  - EN
**Can you also store in the digital vaccination certificate that you have already been infected or tested negative?**
Yes, negative tests or a recovery from the Corona virus can also be stored in the CovPass-App and Corona-Warn-App as a test certificate or recovery certificate. A recovery from a Corona infection is documented by means of a PCR test result.
- [ ] 19
  - DE
**Warum wurde kein EU-weites Projekt für ein Zertifikat ausgeschrieben?**
Eine gemeinsame EU-Ausschreibung hätte zu viel Zeit benötigt und wäre aufgrund der unterschiedlichen Impfinformationssysteme in den Mitgliedstaaten auch schwierig umzusetzen gewesen. Beim EU-Ansatz geht es um die Regelung eines Anerkennungsrahmens. Etwaige grenzüberschreitende Nutzungspiloten könnten seitens der EU-Kommission begleitet werden. Bei der Umsetzung des Digitalen Impfnachweises in Deutschland werden die EU-Vorgaben von vornherein berücksichtigt.

Q&A - Risk calculation/warnings
---
- [ ] 5
  - comment, see below: Maybe it would be good to add more explanation here: the features are independent of each other. The quality of your risk assessment does not change depending on whether or not you choose to store your vaccination certificate in the application, underlining the fact that this is completely voluntary. However, your personal status may influence how you interpret the warning. -> Thanks for this comment! Will include this.
  - DE
**Wirkt sich der Impfstatus auf die Berechnung des Risikos aus? Beispielsweise, wenn eine geimpfte Person sich infiziert haben sollte und dann andere Nutzer*innen warnt?** 
Nein, in der Risikoberechnung wird nicht berücksichtig, ob Sie gegen Corona geimpft oder genesen sind. Die Funktionen sind voneinander unabhängig. Die Qualität Ihrer Risikobewertung ändert sich nicht, je nachdem, ob Sie Sich dafür entscheiden, Ihren Impfausweis in der Anwendung zu speichern, was unterstreicht, dass dies völlig freiwillig ist. Ihr persönlicher Impfstatus kann jedoch Ihre Interpretation der Risiko-Warnung beeinflussen.
  - EN
**Does vaccination status affect the calculation of the risk? For example, if a vaccinated person has become infected and then warns other users?** 
No, do not take into account in the risk calculation whether you are vaccinated against or recovered from a corona infection. The functions are independent of each other. The quality of your risk assessment does not change depending on whether you choose to save your vaccination certificate in the application, which underlines that this is completely voluntary. However, your personal vaccination status may affect your interpretation of the risk warning.
- [ ] 6
  - comment, see below: It would be helpful to add the detail that you can always get tested if you want to be safe. What does "eigenes Monitoring" mean? 
  - DE
**Wie sollte man sich verhalten, wenn man teil- oder vollständig geimpft ist, aber eine rote Warnung in der Corona-Warn-App erhält?** 
Handlungsempfehlung: Wenn eine geimpfte Person als enge Kontakt-Person eingestuft wird, ist zunächst keine Quarantäne (aber eigenes Monitoring) nötig, solange keine Symptome auftreten. Sollten doch Symptomen auftreten, sollten Sie sich unmittelbar testen lassen und in sofort Quarantäne begeben. 

Q&A - several apps/change device/backup/several certificates
---

- [ ] 4
  -   "anchor": "vaccination_certificate_multiple_scan_possible", 
  - [x] PR  https://github.com/corona-warn-app/cwa-website/pull/1312
  - DE
**Kann ich mein Impfzertifikat auf mehreren Smartphones speichern, z.B. auf meinem privaten und dem Geschäftshandy? 
Wie kann ich die Impfbescheinigung beim Gerätewechsel übertragen?
Was mache ich, wenn ich mein Smartphone verloren habe?
Ist das Impfzertifikat in meinem Backup enthalten?
Kann ich das Zertifikat in der Corona-Warn-App und der CovPass-App gleichzeitig verwalten, oder muss ich mich für eine der beiden Apps entscheiden?** 
Es gibt keine Begrenzung, wie oft Sie den 2D-Barcode (QR-Code) Ihres Impfzertifikats scannen. Sie können die Impfzertifikate auf mehreren Geräten, auf einem neuen Gerät, auf einem zurückgesetzten Gerät, und sogar in mehreren Apps hinzufügen und verwalten. Daher ist auch keine Sicherung (Backup) erforderlich.
  - EN
**Can I save my vaccination certificate on multiple smartphones, e.g., on my private and business phone?  
How can I transfer the vaccination certificate when changing device?
What do I do if I lose my phone?
Will the vaccination certificate be included in my backup?
Can I manage the certificate in the Corona-Warn-App and the CovPass-App at the same time, or do I have to choose one of the two apps?**
There is no limit to how often you scan the 2D barcode (QR code) of your vaccination certificates. You can add and manage the vaccination certificates on multiple devices, on a new device, on a device you have reset, and even in several apps. Therefore, a backup is not required.
- [ ] 1
  - DE
**Kann ich die Impfzertifikate von Angehörigen, beispielsweise Kindern in der Corona-Warn-App speichern?** 
Mit der Corona-Warn-App Sie können nur Impfnachweise von einer Person scannen und der App hinzufügen. Es ist nicht möglich, den eigenen und zusätzlich beispielsweise den des Kindes oder des Partners/der Partnerin hinzuzufügen. 
Mit der CovPass-App können digitale Impfnachweise von Kindern oder Partnern zusammen auf einem Smartphone gespeichert werden.
  - EN 
**Can I save the vaccination certificates of relatives, such as children, in the Corona-Warn-App?**
With the Corona-Warn-App, you can only scan   and add vaccination certificates from one person. It is not possible to add your own and additionally, for example, that of your child or partner. 
With the CovPass-App, the digital vaccination certificates of children or partners can be stored together on a smartphone.

Q&A - DATENSCHUTZ/PRIVATSPHÄRE/Sicherheit
---

- [ ] 20
  - DE
**Welche Daten werden bei der Überprüfung des QR-Codes angezeigt?** 
Der QR-Code wird in der Corona-Warn-App angezeigt. Nach dem Scannen des QR-Codes mit der CovPassCheck-App sind nur die nötigsten Informationen zu sehen: Impfstatus, Name, Vorname und Geburtsdatum der geimpften Person. 
  - EN
**What data is displayed when checking the QR code?** 
The QR code is displayed in the Corona-Warn-App. After scanning the QR code with the CovPassCheck app, only the most necessary information can be seen: vaccination status, last name, first name and date of birth of the vaccinated person. 
- [ ] 8
  - DE
**Wo werden meine persönlichen Daten beim digitalen Impfnachweis gespeichert? Ist ein zentrales Impfregister geplant?**
Nein, es gibt kein zentrales Impfregister.  Bei Erstellung des Corona-Impfzertifikats werden Ihre Daten einmalig durch die Impfstelle erhoben und zur Signierung an das RKI übermittelt. Die Daten werden dort sofort wieder gelöscht. Wenn Sie das Corona-Impfzertifikat in der App hinzufügen, werden ihre persönlichen Daten nur lokal (dezentral) auf ihrem Smartphone gespeichert. Sie können selbst entscheiden, ob und wann Sie diese Daten auf Ihrem Gerät löschen. 
Alle digitalen Impfnachweise werden nur temporär im Impfprotokollierungssystem erstellt und anschließend gelöscht. Eine dauerhafte Speicherung ist nur dezentral auf den Smartphones der Nutzer vorgesehen. 
  - EN
**Where is my personal data of the digital certificate of vaccination stored? Is a central vaccination register planned?**
No, there is no central vaccination register.  When the Corona vaccination certificate is created, your data will be collected once by the vaccination site and transmitted to the RKI for signing. The data will be deleted there immediately. When you add the Corona vaccination certificate in the app, your personal information is only stored locally (decentralized) on your smartphone. You can decide for yourself if and when to delete this data on your device. 
All digital vaccination certificates are created only temporarily in the vaccination logging system and then deleted. Permanent storage is only realized decentral on the users' smartphones.
- [ ] 23
  - DE
**Werden meine Daten beim Löschen der Corona-Warn-App entfernt?** 
**Werden meine Daten beim Entfernen des Impfzertifikats aus der Corona-Warn-App entfernt?** 
Ja. All Ihre gesammelten Daten in der Corona-Warn-App werden beim Löschen der Anwendung rückstandslos entfernt. Dies gilt auch für das Entfernen des Impfzertifikats aus der Corona-Warn-App.
  - EN
**Will my data be removed when I delete the Corona-Warn-App? 
Will my data be removed from the Corona-Warn-App when I remove the vaccination certificate?** 
Yes. All your collected data in the Corona-Warn-App will be removed when you delete it. This also applies to the removal of the vaccination certificate from the Corona-Warn-App.
- [ ] 7
  - comment, see below: This question is not needed in my opinion. The answer boils down to "the pass needs to be checked carefully, also forgery is a crime", which is does not actually answer the question what makes the analog pass safe. It also does not answer the question about what makes the digital certificate safe (because this is already answered in the next question).  -> ok!
  - DE
~**Wie wird dabei sichergestellt, dass die Informationen aus dem gelben Impfheft, bzw. das digitale Impfzertifikat echt und nicht gefälscht sind?**
Bei der Prüfung der analogen Impfpässe ist besondere Vorsicht geboten ist. Das gilt sowohl dann, wenn der analoge Impfpass genutzt wird, um z. B. Geschäfte zu betreten. Und es gilt auch dann, wenn die Informationen von dem analogen in einen digitalen Impfpass übertragen werden. Die Fälschung von Impfpässen ist strafbewehrt. Das gilt für analoge wie für digitale Impfdokumente.~
- [ ] 16
  - comment, see below: You used two different dashes here. '–' is the correct one. -> corrected.
  - DE
**Wie soll ein Missbrauch verhindert werden?**
Der QR-Code für den digitalen Impfnachweis darf nur von autorisierten Personen in Impfzentren, Arztpraxen und Krankenhäusern ausgestellt werden. Bei der Überprüfung von digitalen Impfnachweisen ist – wie in der analogen Welt auch – ggf. ergänzend ein Lichtbildausweis vorzulegen. Der digitale Impfnachweis ist kryptographisch vor Veränderungen geschützt. 
  - EN
**How to prevent misuse?**
The QR code for digital certificate of vaccination may only be issued by authorized persons in vaccination centers, medical practices and hospitals. When reviewing digital vaccination certificates, a photo ID may be presented as appropriate, as in the analogue world. The digital proof of vaccination is cryptographically protected against changes.

Q&A - Technical details
---

**Comment by Ein-Tim** [comment]
Hey @dsarkar 

Thanks for creating this issue. What do you prefer, should we only give content feedback here or also feedback reg. spelling?

**Comment by Ein-Tim** [comment]
First point, before I give any feedback, we have soooo many things that are already in https://www.bundesgesundheitsministerium.de/coronavirus/faq-covid-19-impfung/faq-digitaler-impfnachweis.html. 
The only advantage of our FAQ would be an English version. 

Do we really need all this in the CWA's FAQ? Probably this was decided like this internally, or?
What does the community think (@MikeMcC399?)

**Comment by dsarkar** [comment]
@Ein-Tim Any feedback is most welcome!

**Comment by fynngodau** [comment]
> Deutschland wird diese europäische Entscheidung nun schnell umsetzen, um allen Bürgern, die dies wünschen, einen digitalen Impfnachweis zur Verfügung stellen zu können.

Will this FAQ be published before the feature is released? Otherwise, the tense needs to be changed.

>  Ob Sie mit einem vollständigen Impfschutz beispielsweise reisen dürfen, hängt von den Bestimmungen des jeweiligen Landes ab.

Maybe we could find a resource which provides further information here?


>  Wer kann einen elektronischen Impfnachweis erhalten? Wie erhalte ich ein Impfzertifikat?

>  Wie kann ich, wenn ich bereits vollständigen Impfschutz haben, den Status nachträglich in die Corona-Warn-App übertragen?

These two questions have very similar answers and should be merged. It is also partially overlapping with the question "Wie funktioniert der digitale Impfnachweis?".

I think the latter question should be the third question after "Was ist…?" and "Warum gibt es…?", and then more questions could provide further details. You should know how it works before being told how to receive it.

> Wirkt sich der Impfstatus auf die Berechnung des Risikos aus? Beispielsweise, wenn eine geimpfte Person sich infiziert haben sollte und dann andere Nutzer*innen warnt?
>  Nein, im Moment wird in der Risikoberechnung nicht berücksichtig, ob Sie gegen Corona geimpft oder genesen sind.

Maybe it would be good to add more explanation here: the features are independent of each other. The quality of your risk assessment does not change depending on whether or not you choose to store your vaccination certificate in the application, underlining the fact that this is completely voluntary. However, your personal status may influence *how you interpret* the warning.

>  Wie sollte man sich verhalten, wenn man teil- oder vollständig geimpft ist, aber eine rote Warnung in der Corona-Warn-App erhält?
> Handlungsempfehlung: Wenn eine geimpfte Person als enge Kontakt-Person eingestuft wird, ist zunächst keine Quarantäne (aber eigenes Monitoring) nötig, solange keine Symptome auftreten. Sollten doch Symptomen auftreten, sollten Sie sich unmittelbar testen lassen und in sofort Quarantäne begeben.

It would be helpful to add the detail that you can always get tested if you want to be safe. What does "eigenes Monitoring" mean?

Related: https://github.com/corona-warn-app/cwa-wishlist/issues/457 → also add this advice to the app

> - wie in der analogen Welt auch –

You used two different dashes here. '–' is the correct one.

>  Wie wird dabei sichergestellt, dass die Informationen aus dem gelben Impfheft, bzw. das digitale Impfzertifikat echt und nicht gefälscht sind?
>Bei der Prüfung der analogen Impfpässe ist besondere Vorsicht geboten ist. Das gilt sowohl dann, wenn der analoge Impfpass genutzt wird, um z. B. Geschäfte zu betreten. Und es gilt auch dann, wenn die Informationen von dem analogen in einen digitalen Impfpass übertragen werden. Die Fälschung von Impfpässen ist strafbewehrt. Das gilt für analoge wie für digitale Impfdokumente.

This question is not needed in my opinion. The answer boils down to "the pass needs to be checked carefully, also forgery is a crime", which is does not actually answer the question *what makes the analog pass safe*. It also does not answer the question about what makes the digital certificate safe (because this is already answered in the next question).

**Comment by dsarkar** [comment]
@fynngodau Many thanks for your feedback, very much appreciated! I adopted basically almost all of your suggestions. Thanks.

**Comment by DerVogel2020** [comment]
Sometimes you use Corona-Warn-App, sometimes only CWA. This should be consistent.
I also found some typos. Will you provide a PR? Then it's easier to mark them😆

**Comment by Ein-Tim** [comment]
@fynngodau 
Mentioned quite all my points, I only suggest to capitalise "ihr/e" & "sie", etc.

**Comment by fynngodau** [comment]
@dsarkar Thank you for considering my feedback! I have a few more items now:

* You are using the term "2D barcode" throughout the FAQ. This is a rather technical term that most users are probably not familiar with. It is also currently not used in the FAQ document. I'd suggest to use the more familiar term "QR code" directly.

* > No, do not take into account in the risk calculation whether you are vaccinated against or recovered from a corona infection.
 
   I think you mixed up the grammar here. You probably meant to say: "No, the app does not take into account in the risk calculation […]", or even better: "No, the risk calculation in the app does not take into account […]".

* >  How to prevent abuse?

   Similarly, here, you probably meant: "How is abuse being prevented?"

* >  Nein, in der Risikoberechnung wird nicht berücksichtig, ob Sie gegen Corona geimpft oder genesen sind. Die Funktionen sind voneinander unabhängig. Die Qualität Ihrer Risikobewertung ändert sich nicht, je nachdem, ob Sie Sich dafür entscheiden, Ihren Impfausweis in der Anwendung zu speichern, was unterstreicht, dass dies völlig freiwillig ist. Ihr persönlicher Impfstatus kann jedoch Ihre Interpretation der Risiko-Warnung beeinflussen.
  
  I didn't mean this suggestion literally, rather as an idea for what points it could mention. The reason is that what I suggested can still be read with the negative spin that both are intentionally equally bad. I thought about it further and came up with a refined suggestion: "[…] Die Funktionen sind unabhängig voneinander – wenn Sie sich entscheiden, Ihren Impfausweis nicht in der Anwendung zu speichern, wird dadurch die Genauigkeit Ihrer Risikobewertung nicht verschlechtert. […]"

* >  Will my data be removed from the Corona-Warn-App when I remove the vaccination certificate?

   This question is a bit pointless. Why would a user think that this is not the case?

* >  Ist das Impfzertifikat in meinem Backup enthalten?

   This question is not directly answered in the block that follows it. One option would be to remove it here and integrate it with the `backup` FAQ.
   Then, the [`backup`](https://www.coronawarn.app/en/faq/#backup) FAQ should be updated to reflect this information, and to also address the other features of the app (contact journal etc.). It should also explain that this is done to ensure that the sensitive data that the Corona-Warn-App stores doesn't leave the device.

**Comment by Ein-Tim** [comment]
Reg.: "vaccination_certificate_multiple_scan_possible" please see: https://github.com/corona-warn-app/cwa-website/pull/1312#pullrequestreview-671773415

**Comment by dsarkar** [comment]
@DerVogel2020 Thanks for having a look at this. I will provide PR later today. In an FAQ article we use Corona-Warn-App (CWA) the first time, and later within the same article CWA.

@Ein-Tim ok, thanks.

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/1313

**Comment by Ein-Tim** [comment]
I think a FAQ entry reg. the validity time would be good. 
See https://github.com/ehn-digital-green-development/hcert-spec/blob/main/hcert_spec.md#61-hcert-signature-validity-time

**Comment by heinezen** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/1313 has been merged with release 2.3
