### ISSUE TITLE
Only in Germany? Or other countries too?

### ISSUE THREAD

**Issue by conradkleinespel** [corona-warn-app/cwa-website#132]
## Your Question

* Website URL Path: https://www.coronawarn.app/en/
* Line / Paragraph: "The Corona-Warn-App is an app that helps trace infection chains of SARS-CoV-2 (which can cause COVID-19) in Germany."
* Question:

The app was available only in Germany for a while. Now, it seems like it is available in a lot of countries (Netherlands, Belgium, Luxembourg, France, Austria, Czech Republic, Poland, Denmark, Romania and Bulgaria): https://twitter.com/venriser/status/1275779483153432577

But the website seems to indicate that the app works only in Germany:
> The Corona-Warn-App is an app that helps trace infection chains of SARS-CoV-2 (which can cause COVID-19) in Germany.

Is that the case? Or does it actually work and warn users regardless of location?

**Comment by MichaelPFrey** [comment]
If a person travels to Germany for a longer time (e.g. vacation, seasonal work, studying) but not permanently, it makes sense to install the German app during that time. But when the persons moves back out of germany, the german app will have little use to that person, as it is highly unlikely that the person meets german app users in an other country that are able to acquire test results that they can use to get a TAN to submit their keys. And even if you local health authority might not be prepared to handle the notification of a foreign app.

If a person moves permanently, the person should change location in the app store. Changing the location in the app store how ever is not an option for a two week vacation or 1 semester study abroad (changing the location has other implications). So "staying in germany but not beeing able to change app store location" is the reason why the app should be available outside of Germany.

It will get better once infected key roaming is implemented, then countries with compatible apps will exchange infected keys. This will help in the board region of for e.g. germany and switzerland - then you can download the app for you place of residency and be notified if you had contact by person while a cross the border or with a person that crossed the border and contact your local health authority.
(Note that france is not using a compatible protocol - so key roaming/exchange will not be possible)

**Comment by conradkleinespel** [comment]
@MichaelPFrey Thanks for taking the time to answer in such detail ! :+1: :pray: 

I understand that for now, there are no plans to promote this app for people not living in or traveling to Germany. If that changes, I'll be happy to help with French translations. Having a trusted open source app such as the Corona Warn App globally available could go a long way towards driving adoption.

**Comment by conradkleinespel** [comment]
@MichaelPFrey Thanks for taking the time to answer in such detail ! :+1: :pray: 

I understand that for now, there are no plans to promote this app for people not living in or traveling to Germany. If that changes, I'll be happy to help with French translations. Having a trusted, privacy aware & open source app such as the Corona Warn App globally available could go a long way towards driving adoption.
