### ISSUE TITLE
`#rat_how_long_valid` only describes the implementation under Android

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1330]
## Where to find the issue
DE: https://www.coronawarn.app/de/faq/#rat_how_long_valid
EN: https://www.coronawarn.app/en/faq/#rat_how_long_valid

## Describe the issue
The FAQ entry talks about a countdown, however, there is no countdown under iOS. 
The implementation under iOS and Android differs here. See the screenshots on https://www.coronawarn.app/en/screenshots/:

| iOS | Android |
|---|---|
|<img src="https://www.coronawarn.app/assets/img/screenshots/en/ios/rat_7.png" width="300">|<img src="https://www.coronawarn.app/assets/img/screenshots/en/android/rat_7.png" width="300"> |

## Suggested change
Also mention the iOS implementation and change the title to something more general.

## Additional information

I could provide a PR for this, but I was not sure if the implantation will change with version 2.4, which integrates the DCC for test result proofs. If this will not change anything on the countdown, please let me know and I'll work on this.

**Comment by thomasaugsten** [comment]
There is no change planned.

**Comment by Ein-Tim** [comment]
PR #1334 opened and ready for review.
