### ISSUE TITLE
Align all `page-title`s & improve `page-description` s

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1331]
## Feature description

Format all `page-title`s in the same way & improve the `page-description`s, they are often very long and not really helpful. 

## Problem and motivation

Consistency between the pages, nicer overview when working with multiple tabs.

## Is this something you're interested in working on

Yes - PR is coming.

**Comment by Ein-Tim** [comment]
PR #1332 opened and ready for review. 
Please note that you have to either merge the PR **into** the `svengabr/screenshot-archive` branch or merge it into `master` **after** #1329.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. I will merge after the other R 2.3 PRs!
