### ISSUE TITLE
Example of EU Digital COVID vaccination certificate half upside down

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1349]
## Where to find the issue

https://www.coronawarn.app/en/faq/#vac_cert_invalid
https://www.coronawarn.app/de/faq/#vac_cert_invalid

link to image https://user-images.githubusercontent.com/6367738/121354638-59aba880-c92f-11eb-98bb-9dcbc42d6742.jpg

## Describe the issue

The top half of the image used in the FAQ is upside down and not easily readable by non-acrobats.

![121354638-59aba880-c92f-11eb-98bb-9dcbc42d6742](https://user-images.githubusercontent.com/66998419/121585358-c8255f00-ca32-11eb-85bd-712bd771e580.jpg)

## Suggested change

Provide an image such as the one attached where the text is all readable from one viewing position without having to print out the graphic or have the user stand on their head.

![EU Digital Covid Vaccination Certificate Demo](https://user-images.githubusercontent.com/66998419/121585483-f014c280-ca32-11eb-83b1-38ef4a74719b.jpg)

**Comment by MikeMcC399** [comment]
@dsarkar 

Is this what you intended?

![image](https://user-images.githubusercontent.com/66998419/121649196-9e9f1e80-ca98-11eb-8b30-10fe5d122806.png)

**Comment by MikeMcC399** [comment]
Maybe this was a refresh issue? Anyway it is working now. So ignore previous comment. 🙂

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks! File was missing.
