### ISSUE TITLE
Suggestion: Stop publishing weekly app status report

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1355]
The weekly app status report "KENNZAHLEN ZUR CORONA-WARN-APP" copied from the https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html site is not really useful for CWA end-users who are interested in pandemic trends in conjunction with the app. This is especially because many of the numbers in the report are cumulative from June 2020 last year, instead of being delta daily or weekly numbers.

The daily statistics published in the app itself:
- Confirmed new infections
- Warnings by App Users
- 7-Day Incidence
- 7-Day R Value

are far more interesting.

I suggest to stop copying the report to the blog https://www.coronawarn.app/en/blog/ every week e.g. https://www.coronawarn.app/en/blog/2021-06-03-facts-and-figures/.

Instead add a permanent link to https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html somewhere on https://www.coronawarn.app and leave the updating to RKI.

That would also save @HannaHei weekly work.

Apart from the criticism that the report is mostly based on cumulative figures, it gives no history about all the major enhancements and releases which have been done over the last year. It would be very interesting to have a concise history of all the improvements, version by version, month by month, in such a status report.

---
 Internal Tracking ID: [EXPOSUREAPP-10003](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10003)

**Comment by Ein-Tim** [comment]
This issue is wrongly labeled as `question`, I think the type is `enhancement`. Please relabel, thank you!

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal Tracking ID: [EXPOSUREAPP-10003](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10003)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Thank you for noticing the statement on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html where it says:

---
<h2>Kennzahlen-Dashboard zur Corona-Warn-App</h2>
<p>Seit mehr als einem Jahr veröffentlicht das Projektteam (Robert Koch-Institut, SAP, Deutsche Telekom) regelmäßig Kennzahlen zur Corona-Warn-App. Dies ist ein wichtiger Beitrag zur Transparenz, die zentraler Bestandteil aller Open-Source-Projekte ist. </p>
 <p>An die Stelle des wöchentlichen Übersichtsdokuments tritt nun ein öffentliches, interaktives Dashboard mit den wichtigsten Kennzahlen. Diese werden täglich aktualisiert. In der Startversion sind folgende Kennzahlen abrufbar: Downloads, Registrierung von Tests, Testergebnisse sowie Teilungsverhalten und Warnungen mit grünem und rotem Risiko. Die Daten können ebenfalls als csv-Datei heruntergeladen werden. <br />
Das Dashboard ist über den Blog der Corona-Warn-App unter <a class="RichTextExtLink ExternalLink" href="https://coronawarn.app/de/analysis/" target="_blank" rel="noopener noreferrer" title="Externer Link Corona-Warn-App (Öffnet neues Fenster)">https://www.coronawarn.app/de/analysis</a> verfügbar.</p>
 <p>Details zu den Quellen der dargestellten Daten sowie zur Nutzung des Dashboards finden Sie unter: <a  href="https://www.coronawarn.app/de/blog/2021-10-04-key-figures-dashboard/" target="_blank" rel="noopener noreferrer" title="Externer Link Kennzahlen-Dashboard zur Corona-Warn-App (4.10.2021) (Öffnet neues Fenster)">https://www.coronawarn.app/de/blog/2021-10-04-key-figures-dashboard/ </a></p>
<p><a class="RichTextIntLink GenericTable" href="DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html;jsessionid=71A323C514D63E0A4093B51CB86752A0.internet051?nn=13490888" title="Übersicht zu aktuellen und früherer Zahlen und Fakten zur Corona-Warn-App">Archiv: Übersicht zu Kennzahlen zur Corona-Warn-App</a></p>

---

There should be an entry in the CWA blog https://www.coronawarn.app/en/blog/ to mirror this statement.

In https://www.coronawarn.app/en/blog/2021-10-01-facts-and-figures/ it still says:

"In this post, you can find **regularly updated** facts and figures about the Corona-Warn-App, as well as the number of transmitted and shared test results."

and the announcement for the analysis page on https://www.coronawarn.app/en/blog/2021-10-04-key-figures-dashboard/ says nothing about the discontinuation of the weekly report.

**Comment by MikeMcC399** [comment]
Also the FAQ article https://www.coronawarn.app/en/faq/#numbers_RKI which says:

<p>The Robert Koch Institute provides current numbers and statistics <a href='https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html' target='_blank' rel='noopener noreferrer'>on their website</a> (in German).</p>

needs to be updated if the page referred to (<a href='https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html' target='_blank' rel='noopener noreferrer'>on their website</a>) which resolves to https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html is no longer being updated.

The RKI page https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html could also refer to https://www.coronawarn.app/de/analysis/. At the moment there is no comment on that page. The last entry is from Oct 1, 2021.

**Comment by MikeMcC399** [comment]
Closing this issue as the original "Suggestion: Stop publishing weekly app status report" is being followed de facto, even though there has been no blog announcement to this effect.

https://www.coronawarn.app/en/faq/#numbers_RKI has been updated.
