### ISSUE TITLE
FAQ: Typos, grammar and understandability of vac_cert_invalid

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1364]
## Where to find the issue

https://www.coronawarn.app/en/faq/#vac_cert_invalid and
https://www.coronawarn.app/de/faq/#vac_cert_invalid

## Describe the issue

The articles (English and German) have been revised several times and they include typos, grammatical errors and are not very understandable.

Mentioning June 14 twice in the first sentence doesn't read well.

EN

"... there are certificates with QR codes are issued ..." (grammar is incorrect)
"digitial" (typo)

DE

"eine Bescheinigungen" (doesn't agree singular/plural)

## Suggested change

- Fix typos and grammatical errors.
- Make the text more oriented to the user who has just tried to scan in a vaccination certificate: why didn't it work? what should they do now? what can they expect to happen?

I can submit a PR for this, but I don't want to clash with @thomasaugsten who has lately submitted fast-track PRs without peer review, so I need to know if a PR from me would be useful or not.

**Comment by thomasaugsten** [comment]
PR are very welcome for anything

**Comment by MikeMcC399** [comment]
PR #1365 added to correct typos and grammar issues in 
https://www.coronawarn.app/en/faq/#vac_cert_invalid and
https://www.coronawarn.app/de/faq/#vac_cert_invalid.

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/1447 addresses some readability issues in the first sentence of the FAQ article.

https://www.coronawarn.app/en/faq/#vac_cert_invalid now starts with:
"The app can only successfully scan 'EU Digital COVIID Vaccination Certificates' and these are being issued by vaccination centers since 14 June 2021."

https://www.coronawarn.app/de/faq/#vac_cert_invalid now starts with:
"Die App kann nur erfolgreich ein 'EU digitales COVID-Impfzertifikat' scannen. Diese Bescheinigungen werden seit dem 14.06.2021 in den Impfzentren ausgegeben."

This is now improved enough to close this issue.

**Comment by dsarkar** [comment]
@MikeMcC399 Thank you very much!
