### ISSUE TITLE
Missing link to Twitter

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1375]
## Where to find the issue

https://www.coronawarn.app/

## Describe the issue

https://www.coronawarn.app/ does not link to the Twitter channel https://twitter.com/coronawarnapp.

![image](https://user-images.githubusercontent.com/66998419/122081598-86fcc880-cdff-11eb-8c5c-6432f741d9ec.png)

Related to https://github.com/corona-warn-app/cwa-wishlist/issues/364 "Use your Twitter-Account".

## Suggested change

Add link to https://twitter.com/coronawarnapp on footer of https://www.coronawarn.app/.

https://publish.twitter.com/ offers some automation possibilities.

I would like to leave this change to the Open Source team, so I wasn't planning to submit a PR on it.

---
Internal Tracking ID: [EXPOSUREAPP-8089](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8089)

**Comment by liza-kl** [comment]
Hi, is this issue still unassigned? If yes, in which section should this link be? Learn more maybe?

**Comment by Ein-Tim** [comment]
@liza-kl 

@MikeMcC399 suggested to place the link in the footer of the website.

**Comment by MikeMcC399** [comment]
@liza-kl 
> is this issue still unassigned? 

Yes it is unassigned (in the web view here, you can see: "Assignees / No one assigned"). Most of the issues in this repo are unassigned until they are being actively worked on.

> If yes, in which section should this link be? Learn more maybe?

"Learn more" contains links to read-only areas, so I don't think that Twitter fits in there.

Most sites which link to social media just add the icons (e.g. Facebook, YouTube, Twitter & Instagram) to their footer, either in an unnamed section or the contact section. There isn't a section named contact in the CWA footer though.

---
Footer from https://www.coronawarn.app/en/

![image](https://user-images.githubusercontent.com/66998419/123204679-e2425100-d4b8-11eb-83ca-3e2f78bd1a51.png)

**Comment by liza-kl** [comment]
Thanks for the quick answer :) If it would be possible, could you assign me to the issue? I'll probably take care of it on the weekend :)

**Comment by dsarkar** [comment]
@liza-kl Hi thanks for offering to contribute. I will come back to you, let me check internally about adding a Link to twitter. Thanks. Best, DS 


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
FYI: Related PR: #1441

**Comment by Ein-Tim** [comment]
There we go: https://www.coronawarn.app/en/blog/2021-06-29-cwa-twitter-account/

**Comment by dsarkar** [comment]
@liza-kl @MikeMcC399 @Ein-Tim 

Yes, indeed, we agree that a link to twitter in the footer should be implemented. Happy to hear your suggestions. 

I assume a link via icon and/or l text @coronawarnapp will do. Maybe just below the GitHub icon, what do you think?

**Comment by dsarkar** [comment]
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/1409741/124166980-c552e280-daa3-11eb-9ef6-e2b58a17af82.png">

**Comment by MikeMcC399** [comment]
@dsarkar 
I'm no Twitter expert, but using the tool https://publish.twitter.com/ on @coronawarnapp gives one choice for embedded code as:

`<a href="https://twitter.com/coronawarnapp?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @coronawarnapp</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`

which would show on the page as:

![image](https://user-images.githubusercontent.com/66998419/124171059-5af07100-daa8-11eb-829b-ba952c4aa9f1.png)

Given that @Ein-Tim has told us that the Twitter channel is used more in sending out information from RKI to users, rather than responding individually to users, the link would fit better under "Learn more", rather than "Get Involved".

**Comment by MikeMcC399** [comment]
Probably you'll need to reference https://about.twitter.com/en/who-we-are/brand-toolkit to get brand guidelines and logos to embed. I'll see if I can try something out.

**Comment by MikeMcC399** [comment]
PR #1452 created.

**Comment by Ein-Tim** [comment]
FYI: The Twitter Account started to respond to tweets from the community.
