### ISSUE TITLE
Define the term purpose (Zweck) in the scientific blog 

### ISSUE THREAD

**Issue by DanAmt** [corona-warn-app/cwa-website#1378]
## Where to find the issue
https://www.coronawarn.app/de/science/2021-06-15-science-blog-1/

## Describe the issue

The second paragraph differentiates terminology in German :  functionality (Funktionalität), effectivness( Wirksamkeit)  and usefulness (Nutzen), which is good. 
However the third para then makes extensive use of "purpose" of the app, which in this scientific context is undefined. 

## Suggested change
1. Define "purpose" ("Zweck") scientifically in second para. Something like "intended purpose" (beabsichtigter Nutzen) possibly. 
2. Ensure proper definition for terminology used throughout. 

---
Internal Tracking ID: [EXPOSUREAPP-8018](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8018)

**Comment by Ein-Tim** [comment]
Will be done in #1406

**Comment by Ein-Tim** [comment]
Now live: 

![Bildschirmfoto 2021-06-21 um 16 11 16](https://user-images.githubusercontent.com/67682506/122776418-61fad080-d2ab-11eb-839d-e7655ed12664.png)

Please confirm that this is ok for you and close this issue @DanAmt.

**Comment by DanAmt** [comment]
Looking good to me

**Comment by Ein-Tim** [comment]
@DanAmt You should be able to close your own issues. If not, @dsarkar is surely willing to help out here 🙂

**Comment by dsarkar** [comment]
@DanAmt @Ein-Tim Thanks everybody for contributing here! Enjoy the evening. Closing this issue!
