### ISSUE TITLE
Capitalization of "Du", "Dein", "Dich", "Dir" in coronawarn.app/de

### ISSUE THREAD

**Issue by jostschmithals** [corona-warn-app/cwa-website#14]
I've noticed that in the German version most occurrences of "Du" are capitalized, but in some places I found lower case notation ("du") too.

The notation should certainly be harmonised. But the question arises: In which direction?

Duden ([https://www.duden.de/sprachwissen/sprachratgeber/Gross-oder-Kleinschreibung-von-duDu-und-ihrIhr](https://www.duden.de/sprachwissen/sprachratgeber/Gross-oder-Kleinschreibung-von-duDu-und-ihrIhr)) says that nowadays the lower case notation is correct (only in letters, SMS and emails upper case is still tolerated).

From my point of view the upper case version looks pretty old-fashioned in this context. Therefore I'd recommend to write all occurrences of "Du", "Dein", "Dich", "Dir" etc. consequently in **lower** case - according to Duden's rules.

I can send a related PR, but first I'd like to ask if it would be okay to make the adjustment in this direction(?)

**Comment by SebastianWolf-SAP** [comment]
Thanks for that report, d2a3f035936926a4d17426e20470badf765ba7a9 should capitalize the remaining "du"s on the website.

As we explicitly address the reader via the website, we chose to use capital letters in line with the option mentioned in the Duden as a slightly more formal (without using 'Sie') variant. Therefore, we would rather stick to "Du", "Dein", "Dir", "Dich" etc.

Of course, pull requests are always appreciated, but it was good that you asked. We probably would not have accepted the lower case variants.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
