### ISSUE TITLE
Corona-Warn-App Website Spanish translation

### ISSUE THREAD

**Issue by adrianapintod** [corona-warn-app/cwa-website#140]
## Feature description

Translate the Corona-Warn-App website into Spanish language as currently there is no Spanish language support.

## Problem and motivation

Spanish community will be able to leverage the application enabling the app to reach a bigger audience in Germany.

## Is this something you're interested in working on

Yes. I'm already working on this translation. I would like to later send the PR with the issue resolution.

**Comment by tkowark** [comment]
Dear @adrianapintod , thank you very much for the proposal. Before you start translating the entire website (including the FAQ?), please give me one or two days to clarify with the team how to proceed here. 

Things that we'll have to clarify:
* We a have to roughly check whether all answers and descriptions are still accurate 
* We have to maintain then newly added FAQ in 3 languages
* We need to establish some idea of how to scale that beyond just two languages

As said, I hope that we'll have an answer in the next days.

**Comment by tkowark** [comment]
Thanks again for your proposal. As the team cannot maintain especially FAQs in multiple languages and provide proper checks for the texts on the website, we will only continue with german and english as the languages for the website.
