### ISSUE TITLE
FAQ: Dealing with multiple & non-personal vaccination certificates

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1409]
## Where to find the issue

https://www.coronawarn.app/en/faq/#vac_cert
https://www.coronawarn.app/de/faq/#vac_cert

## Describe the issue

The FAQ writes as though there is only one vaccination certificate.

The document "Handlungshilfe zur nachträglichen Erstellung der COVID-19-Impfzertifikate durch Apotheker
Geschäftsbereich Pharmazie
11. Juni 2021
ABDA – Bundesvereinigung Deutscher Apothekerverbände e. V."
explicitly says:

"3.2 Erstellung des digitalen COVID-19-Impfzertifikats

Für die vollständige digitale Impfdokumentation ist für die Verabreichung jeder einzelnen Impfstoffdosis ein digitales Impfzertifikat als QR-Code auszustellen. Der Apotheker muss nicht über den Abschluss des Impfprogramms entscheiden, da im Zertifikat die Information zum Datum der Impfung hinterlegt ist. Somit können die COVID-19-Impfzertifikate zeitlich unabhängig generiert werden. Es ist nicht erforderlich mit einer Ausstellung bis 14 Tage nach der letzten Impfung zu warten."

The CWA FAQ does not deal with multiple vaccination certificates and always refers to them as though every person only ever has one certificate.

## Suggested change

Review and revise the FAQs in the https://www.coronawarn.app/en/faq/#vac_cert section to clearly describe how CWA works with multiple vaccination certificates - one for each vaccination dose received.

Since the release of CWA 2.5 it is also possible for the app to store certificates from different people, therefore the FAQ should not assume in the descriptions that a certificate belongs to the phone owner. That means that references such as "my certificate" need to be written in a neutral way, e.g. "a certificate" instead.

**Comment by MikeMcC399** [comment]
The German language blog for 2.3 https://www.coronawarn.app/de/blog/2021-06-10-cwa-version-2-3/ says:

"Nutzer*innen können den QR-Code bereits nach der ersten Impfung scannen und so den Impfstatus in die App übertragen, müssen das aber nicht tun. Sie können auch abwarten, bis sie alle benötigten Impfungen erhalten haben und den Status erst dann in die Corona-Warn-App übertragen."

Please clarify if the certificate for both vaccinations have to be scanned in or if only the final (usually second) vaccination certificate has to be scanned in.

**Comment by MikeMcC399** [comment]
Is there any official answer to this question?

> Please clarify if the certificate for both vaccinations have to be scanned in or if only the final (usually second) vaccination certificate has to be scanned in.

**Comment by MikeMcC399** [comment]
To answer my own question in https://github.com/corona-warn-app/cwa-website/issues/1409#issuecomment-866049540

> Please clarify if the certificate for both vaccinations have to be scanned in or if only the final (usually second) vaccination certificate has to be scanned in.

https://www.bundesgesundheitsministerium.de/coronavirus/faq-covid-19-impfung/faq-digitaler-impfnachweis.html says:

"Müssen sich Personen, die das Zertifikat "Impfung 2 von 2" digital erhalten haben, das erste Zertifikat nachträglich besorgen?

Personen, die bereits vollständig geimpft sind, benötigen lediglich das Zertifikat „Impfung 2 von 2“ um ihren Impfschutz nachweisen zu können."

**Comment by MikeMcC399** [comment]
@dsarkar / @heinezen 

When I wrote this issue, CWA could only manage vaccination certificates for one person. Even so, it was still possible to add both the first and second vaccination certificate of a two-series vaccination program.

With the release of CWA 2.5, and the ability to manage vaccination certificates for more than one person, the FAQ language needs to be adapted to cover the fact that CWA can manage more than one certificate.

If the Open Source Team is not planning to make this change then I would submit a PR to change the mentioning of single vaccination certificates so that the text covers multiple vaccination certificates.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for your comments. More than happy if you would provide a PR to update the corresponding article!

**Comment by MikeMcC399** [comment]
The first PR in this series is https://github.com/corona-warn-app/cwa-website/pull/1506 referring to 
https://www.coronawarn.app/en/faq/#vac_cert_invalid and
https://www.coronawarn.app/de/faq/#vac_cert_invalid

I plan to submit one PR for each article to make feedback, revision and merging simpler.

**Comment by MikeMcC399** [comment]
PRs #1507, #1508 & #1509 have been submitted and merged.

From the introduction of vaccination certificates in version 2.3 it was always possible to add multiple certificates for one person (typically for a two dose vaccination series). From version 2.5 it became possible to add certificates for multiple persons as well.

The issue that some FAQ articles referred to vaccination certificates in the singular, and assumed that vaccination certificates were only from the smartphone owner, has now been resolved. Closing this issue now.
