### ISSUE TITLE
[REMINDER] #1418 - Remove „current version“ once 2.3 is not the current one anymore

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1419]
Title says everything here. 
#1418 added the sentence:
"Neither the **current** version 2.3 nor the future version 2.4 of the Corona-Warn-App support recovery certificates. Further information on this topic will follow at a later date."
(Same in German)
This has to be updated once version 2.3 is not the current version anymore.

**Comment by Ein-Tim** [comment]
Version 2.4 has been released, I can provide a PR for this tomorrow afternoon. Alternatively @dsarkar, could you take this over?

**Comment by Ein-Tim** [comment]
Found some time and did it myself in #1427. 😁

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.
