### ISSUE TITLE
Version 2.4 announcement blog post & screenshot section - picture issues

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1426]
## Where to find the issue
DE: https://www.coronawarn.app/de/blog/2021-06-24-cwa-version-2-4/
EN: https://www.coronawarn.app/en/blog/2021-06-24-cwa-version-2-4/

## Describe the issue & Suggested change
For [DE](https://www.coronawarn.app/de/blog/2021-06-24-cwa-version-2-4/): 
- The screenshot https://www.coronawarn.app/assets/img/blog/2021-06-24%20CWA%202.4%20Testzertifikat/testzertifikat_geburtstag.png is broken. It should be replaced.

For [EN](https://www.coronawarn.app/en/blog/2021-06-24-cwa-version-2-4/): 
- One picture is [missing](https://user-images.githubusercontent.com/67682506/123329994-bc12c480-d53d-11eb-9852-529b123ee6f1.png). It should be added.
- The screenshot https://www.coronawarn.app/assets/img/blog/2021-06-24%20CWA%202.4%20Testzertifikat/request-certificate-birthday.png is broken. It should be replaced.

---
Internal Tracking ID: [EXPOSUREAPP-8004](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8004) DoB issue
Internal Tracking ID: [EXPOSUREAPP-8118](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8118) blog, pic missing

**Comment by MikeMcC399** [comment]
@Ein-Tim 

---
The strange birthday images are also in the screenshot section

- https://www.coronawarn.app/assets/screenshots/2-4/en/ios/iPhone%2011%20Pro-submissionflow_screenshot_test_certificate_entered_birthday.png
- https://www.coronawarn.app/assets/screenshots/2-4/de/ios/iPhone%2011%20Pro-submissionflow_screenshot_test_certificate_entered_birthday.png

---
For the missing picture in https://www.coronawarn.app/en/blog/2021-06-24-cwa-version-2-4/ the HTML is missing a filename

`<img src="/assets/img/blog/2021-06-24 CWA 2.4 Testzertifikat/.png" title="Teststelle unterstützt Testzertifikate nicht" style="align: center">`

The equivalent code in https://www.coronawarn.app/de/blog/2021-06-24-cwa-version-2-4/ shows:

`<img src="/assets/img/blog/2021-06-24 CWA 2.4 Testzertifikat/teststelle-nicht-unterstützt.png" title="Teststelle unterstützt Testzertifikate nicht" style="align: center">
`

**Comment by vaubaehn** [comment]
Another picuture issue:
The disease or agent targeted is named: Schneider, Andrea - but should be Sars-Cov-2, I guess...

DE: 
https://www.coronawarn.app/assets/img/blog/2021-06-24%20CWA%202.4%20Testzertifikat/zertifikat-qr-code.png
EN:
https://www.coronawarn.app/assets/img/blog/2021-06-24%20CWA%202.4%20Testzertifikat/certificate-qr-code.png


<img src="https://www.coronawarn.app/assets/img/blog/2021-06-24%20CWA%202.4%20Testzertifikat/zertifikat-qr-code.png" width="200"> <img src="https://www.coronawarn.app/assets/img/blog/2021-06-24%20CWA%202.4%20Testzertifikat/certificate-qr-code.png" width="200">

😉

**Comment by Ein-Tim** [comment]
Maybe thats a new disease @vaubaehn? 😉

Thanks for spotting, I'll update the title of this issue so that it reflects that it's also about issues with the screenshots page and not only with the blog.

**Comment by MikeMcC399** [comment]
https://www.coronawarn.app/assets/screenshots/2-4/en/android/CertificatesFragment_pending.png 

shows "Error during certificate retrieval" 🙁 

<img alt="" width="200" src="https://www.coronawarn.app/assets/screenshots/2-4/en/android/CertificatesFragment_pending.png">

The same problem in the German language screenshot

https://www.coronawarn.app/assets/screenshots/2-4/de/android/CertificatesFragment_pending.png

**Comment by MikeMcC399** [comment]
There is also a 6 week old issue with the screenshots in 2.2, 2.3 and now 2.4 https://github.com/corona-warn-app/cwa-website/issues/1257.

The 2.4 Android screenshot https://www.coronawarn.app/assets/screenshots/2-4/en/android/rat_2.png hardly matches the 2.4.2-RC0 app layout at all.

**Comment by Ein-Tim** [comment]
These issues persist even after the update of the screenshots with the release of version 2.5.

**Comment by Ein-Tim** [comment]
I consider this as obsolete and will open a new issue reg. the screenshot page soon.
