### ISSUE TITLE
Version 2.4 announcement blog post - Technical refinement

### ISSUE THREAD

**Issue by vaubaehn** [corona-warn-app/cwa-website#1433]
## Where to find the issue
https://www.coronawarn.app/en/blog/2021-06-24-cwa-version-2-4/

> **Please note:** To create the test certificate, the data is encrypted end-to-end and transmitted from the lab or the rapid test site to the Corona-Warn-App. For this purpose, the encrypted data is transmitted to the Robert Koch-Institut (RKI) in order to digitally sign it and thus confirm the certificate’s validity. The RKI cannot decrypt the data, which will be deleted after the certificate has been delivered.

https://www.coronawarn.app/de/blog/2021-06-24-cwa-version-2-4/
> **Wichtig:** Zur Erstellung des Testzertifikats werden die Daten Ende-zu-Ende verschlüsselt und vom Labor, beziehungsweise der Schnellteststelle an die Corona-Warn-App übermittelt. Dafür werden die verschlüsselten Daten an das Robert Koch-Institut (RKI) übermittelt, um sie digital zu signieren und so die Gültigkeit des Zertifikats zu bestätigen. Die Daten können vom RKI nicht entschlüsselt werden und werden nach Zustellung des Zertifikats gelöscht.

## Describe the issue
The "RKI" does not receive an encrypted DCC document from the test lab for signing, but only a hash of the data. For this, the above text is misleading.
Please see here the discussion with thomasaugsten (not pinging intentionally, as I did already a lot in the past days... He deserves a rest.): https://github.com/corona-warn-app/cwa-documentation/issues/647

## Suggested change
EN:
**Please note:** To create the test certificate, the data is encrypted end-to-end and transmitted from the lab or the rapid test site to the Corona-Warn-App. The Robert Koch-Institut (RKI) receives a fingerprint (hash) of the data in order to digitally sign it and thus confirm the validity of the certificate. The fingerprint does not contain any personal or test-related data and is deleted there after the certificate has been transmitted.

DE:
**Wichtig:** Zur Erstellung des Testzertifikats werden die Daten Ende-zu-Ende verschlüsselt und vom Labor, beziehungsweise der Schnellteststelle an die Corona-Warn-App übermittelt. Das Robert-Koch-Institut (RKI) erhält einen Fingerabdruck (Hash) von den Daten, um ihn digital zu signieren und so die Gültigkeit des Zertifikats zu bestätigen. Der Fingerabdruck enthält keinerlei persönliche oder testbezogene Daten und er wird dort nach der Zustellung des Zertifikats gelöscht.

**Comment by heinezen** [comment]
Does the RKI receive the encrypted data and then computes the hash or does it just receive the hash?

**Comment by 1muen** [comment]
@heinezen Its written here: https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-der-Partnersysteme#backend-integration

It just retrieves the hash.

**Comment by heinezen** [comment]
@1muen I think you were looking at the wrong page because your link shows the pre-DCC rapid-test integration.

But through your link I found the correct page: https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/Anbindung-an-CWA-mit-Verwendung-von-DCCs

See **step 7.**: The backend recives both the Encrypted DCC and the hash

**Comment by Ein-Tim** [comment]
I doubt that there will be any update for this blog post at this time, so I suggest to close this issue.

**Comment by Ein-Tim** [comment]
@vaubaehn Please consider to close this issue.

**Comment by vaubaehn** [comment]
@Ein-Tim 
Oh captain, my captain, shall thee be closed as thee grew old!
