### ISSUE TITLE
Selection for 2.3 screenshots does not work

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1439]
## Where to find the issue

https://www.coronawarn.app/en/screenshots/

## Describe the issue

When selecting 2.3 in the Versions drop-down on https://www.coronawarn.app/en/screenshots/ a 404 error is displayed. The screenshots for 2.3 are not displayed.

View code shows the following:

````
                  <div class="d-flex justify-content-sm-end position-relative mb-3 mb-sm-0">
                      <select name="archived-screenshots" class="form-select form-select-sm w-auto position-sm-absolute">
                              <option value="">Versions</option>
                                  <option value="/en/screenshots-archive/2-2.html">2.2</option>
                                  <option value="/en/screenshots-archive/2-3">2.3</option>
                                  <option value="/en/screenshots">2.4</option>
                      </select>
                  </div>
````

Follow on from open issue https://github.com/corona-warn-app/cwa-website/issues/1402.

## Workaround

To view 2.3 screenshots open the page explicitly by hand
- https://www.coronawarn.app/en/screenshots-archive/2-3.html (EN)
- https://www.coronawarn.app/de/screenshots-archive/2-3.html (DE)

## Additional information

This problem is not reproducible locally using `npm start`.
Perhaps the Open Source Team has a test server which mirrors the configuration on https://www.coronawarn.app/ to investigate and fix the problem?

**Comment by MikeMcC399** [comment]
PR #1440 successfully resolves this issue.

Issue #1402 regarding 404 errors when switching languages is still open.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for PR
