### ISSUE TITLE
How to report an issue for map.schnelltestportal.de

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-website#1451]
## Your Question

* Website URL
* Line / Paragraph:
* Question: Good evening.
Is there a way to report an error at  https://map.schnelltestportal.de/ ?
I cannot find them on github and the Impressum only links to info@t-systems.com

The issue is, that the website for my favourite test center changed and maps.schnelltestportal.de links to the old website. It seems, that the operator of the testing site changed, too.

---
Internal Tracking ID: [EXPOSUREAPP-8219](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8219)

**Comment by Ein-Tim** [comment]
Related to: https://github.com/corona-warn-app/cwa-documentation/issues/646

**Comment by dsarkar** [comment]
@DerVogel2020  @Ein-Tim Thanks. We check internally how to proceed with this issue.

---
Internal Tracking ID: [EXPOSUREAPP-8219](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8219)
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Maybe the e-mail address registrierung.labore.pandemietest@t-systems.com from https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki helps?

**Comment by DerVogel2020** [comment]
I think I will send an email to t-systems since the results are no longer shared with the CWA backend. 
The testing site should be removed from the website.

**Comment by DerVogel2020** [comment]
> @DerVogel2020  @Ein-Tim Thanks. We check internally how to proceed with this issue.

@dsarkar 
Any news on this? I wrote an email to t-systems, but didn't get an answer yet.

**Comment by Ein-Tim** [comment]
I've also found some issues on the page and I'd like to report them...

**Comment by DerVogel2020** [comment]
@dsarkar 
Any news on this? My email to t-systems is still unanswered and the issue (wrong website to testing site) still occurs.

**Comment by dsarkar** [comment]
@DerVogel2020 
- For the moment write to registrierung.labore.pandemietest@t-systems.com until another channel might be established. 
- Optionally, issues reported here regarding map.schnelltestportal.de, will be forwarded by us internally. 

---
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment]
I sent them the email again.

**Comment by saerdnaer** [comment]
Whats about bugs or feature requests for the web app itself (or the corresponding API)? Is there a own repo for that, or should be one of the exiting ones be reused?

**Comment by dsarkar** [comment]
@saerdnaer There is no repo for that site. We will forward to TSI bug you report here.

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
FYI: https://github.com/corona-warn-app/cwa-map-public-frontend

**Comment by DerVogel2020** [comment]
I closed this issue because there is a github repository where issues can be created.
