### ISSUE TITLE
Increase size of GitHub logo in footer

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1453]
## Where to find the issue
In the footer of the website.

## Describe the issue
The GitHub logo seems a bit tiny in comparison to the Twitter logo.

## Suggested change
Increase the GitHub logo to match the size of the Twitter logo.

## Would you like to work in this?

Yes, if @MikeMcC399 doesn't want to do this.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
The GitHub icon is used in several different places, so if you make changes to the footer you need to ensure that you don't introduce unwanted side effects in other places.

Please feel free to try doing this if you feel comfortable with it. It may be more work than you think though.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

If you go the GitHub logo source https://github.com/logos and download the logos, you can use GitHub-Mark-Light-32px.png only for the footer. This logo is 32px in size, exactly the same as the Twitter logo.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thank you! I will give it a try later on!

**Comment by Ein-Tim** [comment]
PR #1455 opened, addressing this.

**Comment by DerVogel2020** [comment]
Should this also be implemented in the event landing page? (and also the PR for the Twitter link)
Then the footers would be again the same.

**Comment by Ein-Tim** [comment]
@DerVogel2020 See https://github.com/corona-warn-app/cwa-event-landingpage/pull/30
