### ISSUE TITLE
FAQ: Article missing for 2.5 app error HC_PREFIX_INVALID

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1462]
## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 2.5.1-RC1 (pre-release version)

Also affects iOS.

## Describe the bug

When a scan error occurs scanning an EU digital COVID certificate, the error message HC_PREFIX_INVALID includes an option "FAQ FOR CERTIFICATES" which links to an FAQ article https://www.coronawarn.app/en/faq/#hc_prefix_invalid.

The articles

- https://www.coronawarn.app/en/faq/#hc_prefix_invalid and
- https://www.coronawarn.app/de/faq/#hc_prefix_invalid

do not exist.

## Steps to reproduce the issue

1. Tap "Certificates" in the bottom menu bar
2. Tap "ADD CERTIFICATE"
3. Scan any QR code which is not a valid EU digital COVID certificate such as the following QR code which contains the text "DE12345678"

![QR Code DE12345678](https://user-images.githubusercontent.com/66998419/105467552-25905d80-5c96-11eb-8408-b4835ee6d61f.png)

![image](https://user-images.githubusercontent.com/66998419/124722041-f1d68680-df09-11eb-8d65-01beeffd468e.png)

## Expected behavior

Tapping on "FAQ FOR CERTIFICATES" should display a relevant FAQ article.

## Possible Fix

Write and publish articles which display under the following URLs:

- https://www.coronawarn.app/en/faq/#hc_prefix_invalid and
- https://www.coronawarn.app/de/faq/#hc_prefix_invalid

---

This is a follow-on from https://github.com/corona-warn-app/cwa-documentation/issues/653.

Internal Tracking ID: [EXPOSUREAPP-8216](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8216) iOS
Internal Tracking ID: [EXPOSUREAPP-8226](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8226) Android

**Comment by MikeMcC399** [comment]
@dsarkar 
CWA 2.5.1 was released today (https://www.coronawarn.app/en/blog/2021-07-12-cwa-version-2-5/) and the FAQ article for the app error is still missing.

**Comment by Ein-Tim** [comment]
PR #1494 added the entry.

**Comment by MikeMcC399** [comment]
PR #1495 submitted.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Merged!

**Comment by MikeMcC399** [comment]
Verified fixed with steps to reproduce from https://github.com/corona-warn-app/cwa-website/issues/1462#issue-938618963.
