### ISSUE TITLE
Delete some unused branches

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1464]
## Enhancement description

Delete some unused or already merged branches, like https://github.com/corona-warn-app/cwa-website/tree/dsarkar-release-2-4, https://github.com/corona-warn-app/cwa-website/tree/dsarkar-faq-2-4 and other ones that are shown on https://github.com/corona-warn-app/cwa-website/branches/active. 

## Problem and motivation

Makes it easier to keep an overview over the branches that are still used and that are currently being worked on.

---
EDIT Corona-Warn-App Open Source Team
https://github.com/corona-warn-app/cwa-website/branches/all?page=1

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. WIP

**Comment by dsarkar** [comment]
@svengabr  @heinezen Suggestion: A branch is deleted in general by the one who created it.

**Comment by Ein-Tim** [comment]
The situation here as improved, I'd only ask to delete the following branches, then I would consider this as fixed.

- https://github.com/corona-warn-app/cwa-website/tree/hschepp1965-patch-1
- https://github.com/corona-warn-app/cwa-website/tree/science-blog-02
- https://github.com/corona-warn-app/cwa-website/tree/dsarkar-faq-update-vac_cert_privileges_travel (?)
- https://github.com/corona-warn-app/cwa-website/tree/svengabr/screenshot-archive-link-fix
- https://github.com/corona-warn-app/cwa-website/tree/science-blog-graphs
- https://github.com/corona-warn-app/cwa-website/tree/science-blog-use-png-instead-of-interactive-graphs
- https://github.com/corona-warn-app/cwa-website/tree/science-blog-fix
- https://github.com/corona-warn-app/cwa-website/tree/not-supported-devices

**Comment by Ein-Tim** [comment]
The situation has improved very well here, still, there are some branches which haven't been touched for over 6 months now. 

I still consider this as fixed and will close this issue now.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Although you have closed this issue, I think it would make sense to clean up the stale PRs and branches. Of course, you cannot do this, as the community doesn't have privileges to make changes.

There is even a special link which highlights these branches https://github.com/corona-warn-app/cwa-website/branches/stale which are mainly from @heinezen and which are associated with stale PRs.

https://github.com/corona-warn-app/cwa-website/tree/not-supported-devices is from @svengabr. There is no PR for this one.

Perhaps @heinezen, @svengabr and @dsarkar could take a look to see what could be cleaned up?

**Comment by Ein-Tim** [comment]
@dsarkar 

Could you delete https://github.com/corona-warn-app/cwa-website/tree/admin/Android-screenshots-for-version-2.10.0 & https://github.com/corona-warn-app/cwa-website/tree/revert-multiqr, please?

**Comment by dsarkar** [comment]
revert-multiqr was created by @svengabr, I'd prefer that he deletes this branch (I will let him know). I will delete the other one.
