### ISSUE TITLE
Provide glossary in English

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1476]
## Feature description

The glossary feature, which was added with #1457, should also be added in English version (www.coronawarn.app/en) of the website.

## Problem and motivation
English speaking people are also interested in the definition of terms (;

## Is this something you're interested in working on

Should be done by the Open-Source-Team.

**Comment by Ein-Tim** [comment]
Update on this:

@GisoSchroederSAP wrote in https://github.com/corona-warn-app/cwa-website/pull/1528#issuecomment-885951886:
> Therefore, there is currently no plan (and no capacity) to go for an English version of the glossary - thanks for your understanding in that matter.

So this would probable have to be done from the community. I'll take a look at this once I've enough time.

**Comment by GisoSchroederSAP** [comment]
If you think, the English translation is beneficial to the community, well, I appreciate your input and support.
Thanks!

**Comment by heinezen** [comment]
@Ein-Tim I'll start the translation today and create a branch + draft PR. If I'm not getting finished today, the community is invited to push to my branch.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen Thank you @heinezen! I'll probably have time to make changes on Thursday. 👍
