### ISSUE TITLE
FAQ: Review and revise Vaccination Certificate section

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1479]
## Where to find the issue

https://www.coronawarn.app/en/faq/#vac_cert
https://www.coronawarn.app/de/faq/#vac_cert

## Describe the issue

The FAQ section [Vaccination Cert.](https://www.coronawarn.app/en/faq/#vac_cert) would benefit from review and revision since some statements are out of date as certain things which were still in planning at the time of writing have now been implemented.

There are also several articles which are missing the fact that pharmacies are able to issue digital certificates to catch up on events which happened before digital certificates were introduced and that can now be documented with digital certificates.

## Suggested change

It may be better to tackle this point after the release of CWA 2.5, since for instance, it will be possible to add certificates for multiple persons with 2.5 and that will mean changes in this section very soon anyway.

## Related issue

https://github.com/corona-warn-app/cwa-website/issues/1409  regarding multiple vaccination certificates.

**Comment by Ein-Tim** [comment]
Fully support for this request!

One point I'd like to add: Please consider removing or merging some FAQ entries with reference to the other FAQs at https://digitaler-impfnachweis-app.de/faq/#allgemeine-fragen and https://www.bundesgesundheitsministerium.de/coronavirus/faq-covid-19-impfung/faq-digitaler-impfnachweis.html. 

Thank you!

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for the links! The CWA FAQ should definitely be cross-checked with the other information sources, however currently the other sources are only in the German language, so having the CWA FAQ English version will be a useful resource for readers without German-language skills.

The links could also be added to the FAQs as an additional source of information. In the CWA FAQ section they could be added with the remark (German-language only).

**Comment by MikeMcC399** [comment]
#1409 has now been dealt with. The FAQs now describe the app ability to store multiple vaccination certificates, also for multiple people.

**Comment by MikeMcC399** [comment]
Additional merged PRs which are related to this revision are:

https://github.com/corona-warn-app/cwa-website/pull/1511
https://github.com/corona-warn-app/cwa-website/pull/1514
https://github.com/corona-warn-app/cwa-website/pull/1518
https://github.com/corona-warn-app/cwa-website/pull/1520

This concludes the general effort to update the section
https://www.coronawarn.app/en/faq/#vac_cert
https://www.coronawarn.app/de/faq/#vac_cert

I did not add links to 
- https://digitaler-impfnachweis-app.de/faq/#allgemeine-fragen or
- https://www.bundesgesundheitsministerium.de/coronavirus/faq-covid-19-impfung/faq-digitaler-impfnachweis.html

since in some cases the information on those sites was not up-to-date. As mentioned previously, it is also problematic because those pages don't supply English language text and that could make the CWA FAQs seem unbalanced.
