### ISSUE TITLE
`further_details` (statistics FAQ entry) does not mention vaccination, local statistics & hospitalization statistics

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1497]
## Where to find the issue
EN: https://www.coronawarn.app/en/faq/#further_details
DE: https://www.coronawarn.app/de/faq/#further_details

## Describe the issue
The FAQ entry does not mention the vaccination statistics, which were added in version 2.5. Neither it explains the local statistics which were added in version 2.6. Also it does not mention the hospitalization statistics. 

## Suggested change
Add informations reg. the vaccination statistics & local statistics to the FAQ entry.

---
Internal Tracking ID: [EXPOSUREAPP-8383](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8383)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-8383](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8383)

**Comment by MikeMcC399** [comment]
Also
EN: https://www.coronawarn.app/en/faq/#further_details "In-App statistics starting with release 1.11"
DE: https://www.coronawarn.app/de/faq/#further_details "In-App Statistiken ab Release 1.11"
are in the "News" section, even though version 1.11 was released on Jan 28, 2021 (see https://www.coronawarn.app/en/blog/2021-01-28-corona-warn-app-version-1-11/ ) and this release isn't newsworthy any more.

**Comment by Ein-Tim** [comment]
The issue will get worse with the release of version 2.6, which includes local statistics.

**Comment by MikeMcC399** [comment]
There are two other open issues which reference
EN: https://www.coronawarn.app/en/faq/#further_details "In-App statistics starting with release 1.11"
DE: https://www.coronawarn.app/de/faq/#further_details "In-App Statistiken ab Release 1.11"

these are:
https://github.com/corona-warn-app/cwa-website/issues/904 and
https://github.com/corona-warn-app/cwa-website/issues/971.

**Comment by MikeMcC399** [comment]
EN: https://www.coronawarn.app/en/faq/#further_details "In-App statistics starting with release 1.11"
DE: https://www.coronawarn.app/de/faq/#further_details "In-App Statistiken ab Release 1.11"

needs to be completely reworked:

- move from section "News" perhaps to new section "Statistics"?
- remove reference in title to release 1.11
- remove detailed information for facts covered in blog post and refer instead to blog post https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/ and https://www.coronawarn.app/de/blog/2021-08-05-statistictiles/
- add details for statistics not covered by blog post, i.e. vaccination and local statistics
