### ISSUE TITLE
Cypress test: pages/eventRegistration.js fails

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1503]
## Where to find the issue

https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/pages/eventRegistration.js

## Describe the issue

 ```
 npm ci
 npm run test:prepare
 npm run test
 ```
shows the test for pages/eventRegistration.js failing. 

 ![image](https://user-images.githubusercontent.com/66998419/125816571-c76f9bb5-a96f-4d04-9386-e8dc5c464692.png)

```
  Test Event Registration Page
    1) "before each" hook for "Basic page assertions"


  0 passing (660ms)
  1 failing

  1) Test Event Registration Page
       "before each" hook for "Basic page assertions":
     CypressError: `cy.visit()` failed trying to load:

http://localhost:8000/undefined/eventregistration

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

```

Change was introduced by PR https://github.com/corona-warn-app/cwa-website/pull/1499.

**Comment by MikeMcC399** [comment]
@svengabr / @chrisenitan 
Please verify if the test also fails for you on the master branch of the repository.


If anybody else is able to test and report back on the results, that would also be helpful.

**Comment by MikeMcC399** [comment]
There is new text in the README.md file which says:

----
- Set the default language to test against: create a `cypress.env.json` file with the following values
- Values can be "en" or "de". Defaults to "en"
```
{
  "testEnvLang": "en"
}
```

---

The previous tests were carried out by default on both the English (en) and German (de) pages.
Could the eventregistration test also be aligned to test both languages by default?

The instructions don't say that the comments only apply to the eventregistration test.
Where is the file `cypress.env.json` supposed to be created?
If it is necessary for the correct working of the eventregistration test, it would be better to include the file `cypress.env.json` in the repository.

**Comment by MikeMcC399** [comment]
I will close this issue and re-write as an enhancement request to eventregistration since the test does run if cypress.env.json is created as described.

**Comment by chrisenitan** [comment]
> I will close this issue and re-write as an enhancement request to eventregistration since the test does run if cypress.env.json is created as described.

Sure! Please tag me, I should avoid creating new dependencies so I'd say we drop the use of `cypress.env.json` and use `cypress.json` instead since they both serve the same purpose. 

- Ideally the `cypress.env.json` file would be in the projects root dir
- Will also standardise the language test for both available options and update the READ.me to reflect the changes.

**Comment by MikeMcC399** [comment]
@chrisenitan 

It looks like https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/pages/eventRegistration.js is a work-in-progress which does not test the German language page correctly, even though the [README.md](https://github.com/corona-warn-app/cwa-website/blob/master/README.md) suggests otherwise.

Please let us have your comments in the follow-on issue https://github.com/corona-warn-app/cwa-website/issues/1513.
