### ISSUE TITLE
Cypress eventRegistration.js test fails with 'de' set

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1513]
This issue follows on from issue https://github.com/corona-warn-app/cwa-website/issues/1503 and PR https://github.com/corona-warn-app/cwa-website/pull/1499.

@chrisenitan provided the source and
@svengabr merged PR https://github.com/corona-warn-app/cwa-website/pull/1499
so they should be good contacts to respond to the attached.

## Describe the bug

https://github.com/corona-warn-app/cwa-website/blob/master/README.md says:

- Set the default language to test against: create a `cypress.env.json` file with the following values
- Values can be "en" or "de". Defaults to "en"
```
{
  "testEnvLang": "en"
}
```

If "testEnvLang" is set to "de" all three tests of [eventRegistration.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/pages/eventRegistration.js) fail.

## Steps to reproduce the issue

1. `npm ci`to ensure cypress is up-to-date
2. create file `cypress.env.json` in root folder of repository clone
3. set content of `cypress.env.json` to { "testEnvLang": "de" }
4. `npm run test:open`
5. Ìn cypress UI click `eventRegistration.js`
The Cypress error messages are as follows:

### Basic page assertions

`Timed out retrying after 4000ms: Expected to find content: 'The app now allows a check-in for events and locations. People who host events or have a business can now create a QR code. By scanning the QR code, guests can check in upon arrival to register their presence. If desired, the app will also create a corresponding diary entry. If a checked-in person later tests positive for the coronavirus, other people who were checked in at the same time can be warned.' within the element: <section.section.component.qrgenerator> but never did.
`
### Registration criteria validations

`Timed out retrying after 4000ms: Expected to find content: 'The location type is required' within the element: <div#qr-error-locationtyperequired.invalid-feedback> but never did.`

### Test Registration Functionality

`Timed out retrying after 4000ms: Expected to find content: 'The location type is required' within the element: <div#qr-error-locationtyperequired.invalid-feedback> but never did.`

## Expected behavior

If the contents of `cypress.env.json` is
`{ "testEnvLang": "de" }`
then the tests should pass.

## Possible Fix

[eventRegistration.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/pages/eventRegistration.js) is missing code to test against the German language form.

Possible short-term fix:
Hard code "testEnvLang": "en" into `eventRegistration.js` so only the English language page is tested.

Longer term fix:
Add code to `eventRegistration.js`to:
- branch and test differently for the German page.
- automatically switch between languages (as is done in [blog_spec.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/blog_spec.js)) so that both languages are tested and a separate environment file is not needed.

## Additional context

Also the statement `Defaults to "en"` seems questionable. There is no default programmed into [eventRegistration.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/pages/eventRegistration.js).

---

Internal Tracking ID: [EXPOSUREAPP-8242](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8242)

**Comment by chrisenitan** [comment]
From #1503: The test is work in progress for `de` 

- We may benefit from using string handlers for the test and allowing the optional selection of language by who is running the test or use pipeline variables in CI to define this or group tests by localisation...

But all the above might create more complexity however
- So the proposed solution is to duplicate the tests and abstract localised strings to `json` files for easy management. 
- I also removed the `cypress.env.json` file from `gitignore` and updated the README.md file

PR is #1515

**Comment by svengabr** [comment]
Should be resolved with https://github.com/corona-warn-app/cwa-website/pull/1515

**Comment by MikeMcC399** [comment]
PR #1515 fixes the issue.

## Verification

1. `npm ci` to ensure cypress is up-to-date
2. `npm run test:open`
3. In cypress UI click `eventRegistration.js`
4. 6 tests are successful, 0 tests fail
