### ISSUE TITLE
Discussion about PR contribution best practices

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1533]
Some new best practices were introduced into https://github.com/corona-warn-app/cwa-website/blob/master/CONTRIBUTING.md#pull-request-checklist recently (see below).

I'd like to start this thread as an open discussion to help collaboration and implementing the best practices.

---
## Pull Request Checklist

* Use a [git GUI interface](https://git-scm.com/downloads/guis/) if you are new to `git`. It will help you getting familiar with the basic submission workflow.

* Branch from the `master` branch and also target `master` with your Pull Request.

* Commits should be as small as possible while ensuring that each commit is correct independently (i.e., each commit should compile and pass tests).
  * If you notice a small error in your latest commit, you should [amend](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) fixes instead of creating a new commit.
  * If you make several related fixup commits in a row, you should [squash](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) them into a single commit.
  * Use [restore](https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things) operations if you want to revert a change in a commit.

* Create _Draft_ pull requests only if you need clarification or an explicit review before you can continue your work item.

* If your patch is not getting reviewed or you need a specific person to review it, you can @-reply a reviewer asking for a review in the pull request or a comment, or you can ask for a review by contacting us via [email](mailto:corona-warn-app.opensource@sap.com).

* Post review:
  * Integrate the requested changes into your submission.
  * Set respective comments in your GitHub review to resolved.
  * [Rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) your PR to the latest upstream `master` branch.
  * Create a general PR comment to notify the reviewers that your amendments are ready for another round of review.

**Comment by MikeMcC399** [comment]
I noticed that the [GitHub Desktop](https://docs.github.com/en/desktop) has new functionality for

[Squashing commits](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits) and

[Amending a commit](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/amending-a-commit)

I will try to use this in future. (Previously I used the git CLI because I felt more in control, but I think the GUI is easier to use for squashing and amending.)

**Comment by MikeMcC399** [comment]
@heinezen 
Is there any agreement in the Open Source Team that the squash / amend best practices will be used for PRs initiated by the team? Looking at the current history it does not seem to be the case.

**Comment by MikeMcC399** [comment]
Is there any recommendation about using the suggestion function when commenting on other people's PRs?

![image](https://user-images.githubusercontent.com/66998419/127190333-a281f706-fe44-450a-81ee-016406bef9dc.png)

Each suggestion leads to a separate commit. If there are multiple suggestions to a PR which are then individually accepted then that leads to multiple commits, which would need to be squashed to leave a clean history.

**Comment by heinezen** [comment]
> Is there any agreement in the Open Source Team that the squash / amend best practices will be used for PRs initiated by the team? Looking at the current history it does not seem to be the case.

They should be followed by everyone, including the OS team, so you can remind us about the best practices if you think they are not followed. Sometimes squashing is not possible, e.g. when committing via the web interface, but that does not happen that often and is generally OK.

> Each suggestion leads to a separate commit. If there are multiple suggestions to a PR which are then individually accepted then that leads to multiple commits, which would need to be squashed to leave a clean history.

I don't like to use it for that reason: It doesn't generate good commit messages and leads to a number of very tiny commits. So I either make the changes locally myself or squash them locally and force push like in https://github.com/corona-warn-app/cwa-website/pull/1534. However, I still find the suggestion feature useful if I'm mostly in the web interface and cannot do local changes.

**Comment by MikeMcC399** [comment]
After merging the master branch into a open PR, pulling it locally then adding a commit, GitHub Desktop wouldn't let me squash. I had to rebase on master then I could squash and force push to origin.
Still learning here 🙂 !

**Comment by MikeMcC399** [comment]
https://github.com/corona-warn-app/cwa-website/pull/1600 from @larswmh did not follow these best practices.

@larswmh Are you a member of the Open Source Team or are you a community member?

It seems that it will be difficult to keep the history of the https://github.com/corona-warn-app/cwa-website repository to be as readable as the history of the Android app on https://github.com/corona-warn-app/cwa-app-android for instance. The fact that most of the work on the website repo is being done on two files faq.json and faq_de.json by multiple people in parallel means that there is a lot of merging into master necessary to keep open PRs up-to-date with the other work going on.

**Comment by larswmh** [comment]
@MikeMcC399 sorry for not following best practices, I'm still learning and will give my best to follow them from now on. I'm not a member of the Open Source Team, I get my information from other people who then assign tasks to me.

**Comment by MikeMcC399** [comment]
Closing, since this discussion is no longer active.
