### ISSUE TITLE
Glossary placement and naming

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1540]
## Where to find the issue

https://www.coronawarn.app/de/faq/ Glossar

Assuming that PR https://github.com/corona-warn-app/cwa-website/pull/1534 is merged, then also
https://www.coronawarn.app/en/faq/ Glossary

## Describe the issue

The Glossary takes a prominent place at the top of all FAQ articles.

The name and the placement implies that it is a glossary covering all aspects of CWA, however the currently published German-language terms only deal with EU Digital COVID Certificates (DCC) and nothing more. The terms in the English-language PR https://github.com/corona-warn-app/cwa-website/pull/1534 are currently a subset of the terms appearing the the German-language Glossar.

The fact that the Glossary appears at the top of the FAQ hides the fact that there is an FAQ search field available on the page. The user must then search for the search field by scrolling down to it.

## Suggested change

- Move the Glossar / Glossary to a less prominent place on the web site. For instance make it a section of the FAQs or separate it from the FAQs.
- Change the name to Zertifikatsglossar / Certificate Glossary
- Link to the [app Glossary](https://github.com/corona-warn-app/cwa-documentation/blob/master/glossary.md) in the [documentation](https://github.com/corona-warn-app/cwa-documenation) repository.

---
Internal Tracking ID: [EXPOSUREAPP-8934](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8934)

**Comment by larswmh** [comment]
I'm planning to work on this. I think that putting the glossary below the entire FAQ would solve the problem, but I would still leave some kind of hyperlink on top so people can quickly get to it if that's what they are specifically looking for.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for proposal. @larswmh implemented a solution for now to mitigate the "worst". Thanks.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Since the glossary was moved to the bottom (PR #1617), the main part of this issue has been fixed. Would you maybe want to open a new one regarding the naming? If you want to leave this issue open that's also fine for me.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
The naming of the "Glossar" is an open issue, so I would leave this issue open.

Provide Glossary in English is still unaddressed https://github.com/corona-warn-app/cwa-website/issues/1476.

https://github.com/corona-warn-app/cwa-website/issues/1566 is solved, so I will make a note there.

**Comment by MikeMcC399** [comment]
It seems that I accidently closed this issue, however because the situation has changed:
- the Glossary has moved to the bottom of the FAQ page: PR https://github.com/corona-warn-app/cwa-website/pull/1620
- the English language Glossary has been published: PR https://github.com/corona-warn-app/cwa-website/pull/1534

I opened a new issue https://github.com/corona-warn-app/cwa-website/issues/1625 as a follow-on to this issue.
