### ISSUE TITLE
Create a short FAQ entry for the "Your test result cannot be loaded. The response has no content" error under iOS

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1541]
## Where to find the issue
n/a

## Describe the issue
In some cases, the iOS app shows the error "Your test result cannot be loaded. The response has no content" to the user. There is no more information in this error message and only an "OK" button to dismiss the pop-up. More information can be found in: https://github.com/corona-warn-app/cwa-app-ios/issues/3254

## Suggested change
Add a short FAQ entry:

title: "[Apple/iOS] Why do I see the error message 'Your test result cannot be loaded. The response has no content'"
content: "This error message is sometimes shown if your test result is not yet available. This message does not mean the you won't receive your test result through the Corona-Warn-App."

If https://github.com/corona-warn-app/cwa-app-ios/issues/3254 is rejected or just not implemented, we could also add a link to this FAQ entry to the error message.

## Additional information

I can provide a PR for this, if this is welcome.

**Comment by molarya1** [comment]
Hey guys,

**Comment by molarya1** [comment]
Hey guys,

Any update on this item? Looking to get involved with the project and would love to start here

**Comment by Ein-Tim** [comment]
This issue has been fixed. No need to create a FAQ entry.
