### ISSUE TITLE
https://www.coronawarn.app/de/faq/#cert_eu_travel missing

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1546]
Version 2.6 [includes](https://github.com/corona-warn-app/cwa-app-ios/blob/474daba76f9bbd0493726b7ad2654d4486574a36/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.links.strings#L35) a link to https://www.coronawarn.app/de/faq/#cert_eu_travel, will this FAQ entry be published soon?

_Originally posted by @Ein-Tim in https://github.com/corona-warn-app/cwa-website/issues/1523#issuecomment-887763016_

**Comment by MikeMcC399** [comment]
@dsarkar 

There are articles named

https://www.coronawarn.app/en/faq/#eu_cert_travel
https://www.coronawarn.app/de/faq/#eu_cert_travel

which is not the same as

https://www.coronawarn.app/en/faq/#cert_eu_travel and
https://www.coronawarn.app/de/faq/#cert_eu_travel

as used in the Android 2.6 code.

It looks like a mistake was made in https://github.com/corona-warn-app/cwa-website/pull/1523 (https://github.com/corona-warn-app/cwa-website/pull/1523/commits/d1d6888a2e87282ad2a8bb3030806ff4ee7e8967) where the commit is labelled

`rename anchor eu_cert_travel`.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Many thanks for spotting this one !!!!

**Comment by MikeMcC399** [comment]
@dsarkar 
I checked in the Android app that clicking on the FAQ link in the screen "Certificate is Valid" now leads to the correct FAQ entry https://www.coronawarn.app/en/faq/#cert_eu_travel.
