### ISSUE TITLE
Android Screenshots: "Check certificates for validity before a trip" wrong OS

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1549]
## Where to find the issue

https://www.coronawarn.app/en/screenshots/#android_check_validity_certificate "Check certificates for validity before a trip"
https://www.coronawarn.app/de/screenshots/#android_check_validity_certificate "Zertifikate vor einer Reise auf Gültigkeit prüfen"

First reported for CWA version: 2.8
Reviewed as not yet fixed for CWA version: 2.23 screenshots

## Describe the issue

The Android screenshots for "Check certificates for validity before a trip" are unlike the screens actually presented on Android.

They are screenshots from iOS.

### Steps to reproduce

1. View https://www.coronawarn.app/en/screenshots/#android_check_validity_certificate
2. View https://www.coronawarn.app/de/screenshots/#android_check_validity_certificate
3. Note that the English and German language screenshots for Android are from iOS. This is for instance recognizable because "Check Validity" is shown in mixed case. On a real Android device the button label appears in upper case as "CHECK VALIDITY".

## Suggested change

Replace the screen shots by ones from Android.

---
Internal Tracking ID: [EXPOSUREAPP-8503](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8503)

**Comment by MikeMcC399** [comment]
The Android section is using iOS screenshots.

https://github.com/corona-warn-app/cwa-website/blob/b9237487273a8f0d84df47007d3e0a9212706d02/src/data/screenshots.json#L171-L178

There don't appear to be appropriate screen shots available in https://github.com/corona-warn-app/cwa-website/tree/master/src/assets/screenshots/2-6/en/android.

**Comment by MikeMcC399** [comment]
A correct screenshot taken from CWA Android 2.6 is

![VaccinationDetailsFragment_2 6 1](https://user-images.githubusercontent.com/66998419/129439402-9a17fdf2-223b-4b6b-9949-af32b412ba8b.png)

Compare to the posted screenshot (which is from iOS, not from Android):

![iPhone 11 Pro-screenshot_first_vaccination_certificate_details_part1](https://user-images.githubusercontent.com/66998419/129439635-297f3143-685d-4e3e-8d5f-6c904ab89061.png)

**Comment by dsarkar** [comment]
@MikeMcC399 Internal Tracking ID: EXPOSUREAPP-8503

**Comment by Marcono1234** [comment]
Would it be possible to adjust the GitHub workflow to detect such things? That is, `"android-screnshots"` ([sic]) may only refer to screenshots under `/android` and `"ios-screnshots"` may only refer to screenshots under `/ios`.

Similarly it might make sense to verify that the German screenshot JSONs only refer to `/de` and the English ones only to `/en` (though it appears there is no issue with this at the moment).

**Comment by Ein-Tim** [comment]
@Marcono1234 Sometimes we replace broke/outdated/wrong screenshots from one os with a screenshot from another os, so this workflow should give a warning but not block the merge or similar.

**Comment by Ein-Tim** [comment]
Btw do you want to address the typo "screnshots"?

**Comment by Marcono1234** [comment]
> Btw do you want to address the typo "screnshots"?

Created #1661 for this.

**Comment by Marcono1234** [comment]
> @Marcono1234 Sometimes we replace broke/outdated/wrong screenshots from one os with a screenshot from another os, so this workflow should give a warning but not block the merge or similar.

Maybe this could be implemented as combination of [annotations](https://github.community/t/annotations-how-to-create-them/18387/2) and a generated comment on a pull request (annotations on their own are easy to miss, they don't appear on the pull request). Though this might be somewhat tricky to implement.

**Comment by MikeMcC399** [comment]
To return to the original problem: the Android screenshots are missing.

I looked at the Android app, and theses screenshots are not being generated automatically, so the Android app needs to be enhanced to generate them.

I would expect to find a module `ValidationStartFragmentTest.kt` to produce screenshots from `ValidationStartFragment.kt`. I would also expect to find screenshots which start with the filename `Validation`.

Is there any dev feedback to 

> Internal Tracking ID: [EXPOSUREAPP-8503](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8503)

so far?

**Comment by dsarkar** [comment]
@MikeMcC399 Has not been assigned to any dev currently.

**Comment by Ein-Tim** [comment]
Still a valid issue, however, there are multiple places where iOS screenshots are used in the Android section and the way around.

I wonder how screenshots are provided for each release, see https://github.com/corona-warn-app/cwa-website/issues/1760#issuecomment-1100198898.

**Comment by MikeMcC399** [comment]
The screenshots [Check Certificates for Validity Before a Trip](https://www.coronawarn.app/en/screenshots/#android_check_validity_certificate) for Android 2.23 are completely wrong.

There is no "Check validity" button under the QR code, instead the button is located under the tile which shows "Currently used certificate".

The other screenshots bear almost no resemblance to the current UI. If no better screenshots are available then I suggest to remove this section completely, also for the upcoming 2.24 release.

**Comment by MikeMcC399** [comment]
The screenshots [Check Certificates for Validity Before a Trip](https://www.coronawarn.app/en/screenshots/#android_check_validity_certificate) for Android 2.24 published yesterday are also completely wrong.

There is no "Check validity" button under the QR code, instead the button "Check Validity for Travel" is located under the tile which shows "Currently used certificate".

It looks like PR #2985 was intended to correct this, however it now contains conflicts which would need to be resolved.
