### ISSUE TITLE
Nutzungsbedingungen Schreibfehler

### ISSUE THREAD

**Issue by damianbarbig** [corona-warn-app/cwa-website#155]
Hallo CWA Programmirer,

Bei den Nutzungsbedingungen fehlt eine Klammer zu  -> ) <- 

Abschnitt 2 
"...die ungefähre Nähe zur infizierten Person, basierend auf der gemessenen Dämpfung des Bluetooth-Signals (_signal attenuation_) sowie ggf. Übertragungsrisiken (_transmission risk_ **)**..."

Die **FETT** gedruckte (bzw. letzte) Klammer die hier aufgeführt ist fehlt.

Liebe Grüße 

damianbarbig

---
Internal Tracking ID: EXPOSUREAPP-2028

**Comment by mojoaxel** [comment]
This is an Android issue please move to [corona-warn-app/cwa-app-android](/corona-warn-app/cwa-app-android):
https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/assets/terms_de.html#L210

**Comment by tkowark** [comment]
The EULA is also linked as a PDF on the website and contains the same error there.
The iOS App closed the bracket but not after risk, but after transmission (https://github.com/corona-warn-app/cwa-app-ios/blob/a957768a8e17d4f7288e17641d32ac21d4b1d220/src/xcode/ENA/ENA/Resources/Localization/de.lproj/usage.html#L272)

I'll forward this to all both app repos and leave it here for the PDF version.

**Comment by mtb77** [comment]
should be fixed in 1.4.0, but PR still missing @janetback

**Comment by mtb77** [comment]
PR existing, will be part of 1.4.0 RC
