### ISSUE TITLE
Issues with the screenshots page

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1550]
- [ ] Please finally remove the contact journal onboarding screens under iOS (align it to the Android section).
- [x] "Check-In - Scan QR-Code" section: 
	- [x] Title is not translated into German (should be "Check-in - QR-Code scannen"
- [x] "Check-in - QR-Code erstellen" / "Check In - Create Event section:
	- [x] Titles should be aligned (German to English or vice versa)
	- [x] Picture 3 is still broken
- [x] "Aktuelle Zahlen" / "Statistics" section:
	- [x] First picture shows a screenshot of the "Länderübergreifende Risiko-Ermittlung" -> should be replaced
- [x] "Test registrieren & andere warnen" section:
	- [x] Picture 2 is stil broken
- [x] "Testergebnis abrufen" / "Test result home"
	- [x] English title should be aligned to the German one
- [x] "Zertifikate" / "Certificates" section:
	- [x] All pictures have the same name ("Test certificate Image")
- [x] "Testzertifikat" / "Test certificate" section: 
	- [x] All pictures have the same name ("Test certificate Image")
	- [x] Second picture is broken
- [x] "Impfzertifikat" / "Vaccination Certificate" section:
	- [x] All pictures have the same name ("Vaccination certificate Image 11 of 11")
- [x] "Genesenenzertifikat" section:
	- [x] All pictures have the same name ("Genesenenzertifikat")
	
from https://github.com/corona-warn-app/cwa-website/pull/1522#pullrequestreview-712689255

**Comment by MikeMcC399** [comment]
Also https://github.com/corona-warn-app/cwa-website/issues/1549.

**Comment by Ein-Tim** [comment]
Everything mentioned here has been fixed through #1552. 

The contact journal onboarding is tracked in #1307. 

Closing as fixed.
