### ISSUE TITLE
Some blog post screenshots might leak sensitive information

### ISSUE THREAD

**Issue by Marcono1234** [corona-warn-app/cwa-website#1565]
## Where to find the issue
- [`blog/2021-05-11-How-to-Schnelltest-Partner/dm-5.jpg`](https://github.com/corona-warn-app/cwa-website/blob/master/blog/2021-05-11-How-to-Schnelltest-Partner/dm-5.jpg)
QR code stores JWT token containing birthday and unique test ID.
- [`blog/2021-05-12-cwa-2-2/profil-anlegen(3).jpg`](https://github.com/corona-warn-app/cwa-website/blob/master/blog/2021-05-12-cwa-2-2/profil-anlegen(3).jpg)
Contains pretty specific personal information which does not look like mock data.

Maybe more?

## Describe the issue
The screenshots might, by accident, contain sensitive data which should not be public.

## Suggested change
Replace the screenshots, if necessary.

**Comment by MikeMcC399** [comment]
@Marcono1234 

> * [`blog/2021-05-12-cwa-2-2/profil-anlegen(3).jpg`](https://github.com/corona-warn-app/cwa-website/blob/master/blog/2021-05-12-cwa-2-2/profil-anlegen(3).jpg)
>   Contains pretty specific personal information which does not look like mock data.

![image](https://user-images.githubusercontent.com/66998419/127738213-72ae5c1d-c40f-4d5f-ab47-d8dc13778f7c.png)

According to https://www.postdirekt.de/plzserver/ there are several Blumenstr. in Berlin, however none of them have the PLZ 439243.

In fact PLZ 439243 does not exist in real life.
https://www.postdirekt.de/plzserver/index.html > Weitere > Erweiteterte Suche
`0 Suchtreffer für "439243"`

So I would say this is mock data.

**Comment by Marcono1234** [comment]
Thanks for taking a look at this! Maybe this is not problematic then, sorry for the fuss.
Feel free to close this issue.

**Comment by MikeMcC399** [comment]
@Marcono1234 
Thanks for keeping an eye out for problems. Mistakes do sometimes happen.

You should be able to close the issue yourself. 

See if you have a button "Close Issue" at the bottom available to you if you are viewing via web browser, or just "CLOSE" if you are using the GitHub app.
