### ISSUE TITLE
Umlaut problems in science tables

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1573]
## Where to find the issue

https://www.coronawarn.app/de/science/2021-08-02-science-blog-3/

## Describe the issue

In several tables the graphics contain Umlauts which are displayed incorrectly.

[tab_02](https://github.com/corona-warn-app/cwa-website/blob/master/science/2021-08-02-science-blog-3/tab_02.png)

![Screenshot 2021-08-02 193549](https://user-images.githubusercontent.com/66998419/127901609-038e84fd-9c6a-401b-b392-a9e6ed8a40de.png)

[tab_05](https://github.com/corona-warn-app/cwa-website/blob/master/science/2021-08-02-science-blog-3/tab_05.png)
[tab_06](https://github.com/corona-warn-app/cwa-website/blob/master/science/2021-08-02-science-blog-3/tab_06.png)
[tab_14](https://github.com/corona-warn-app/cwa-website/blob/master/science/2021-08-02-science-blog-3/tab_14.png)
[tab_16](https://github.com/corona-warn-app/cwa-website/blob/master/science/2021-08-02-science-blog-3/tab_16.png)

## Suggested change

Re-generate and re-publish the .png files which have incorrect characters.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. We will get the raw data from RKI and then edit it in line with the other the tables, which will also resolve this issue.

Internal Tracking ID: [EXPOSUREAPP-8784](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8784)

**Comment by MikeMcC399** [comment]
This issue is resolved by PR #1745 which updated https://www.coronawarn.app/de/science/2021-08-02-science-blog-3/ today, September 20, 2021.
