### ISSUE TITLE
FAQ for hard of hearing needs review regarding TANs and RATs

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1589]
## Where to find the issue

- https://www.coronawarn.app/en/faq/#hearing_impaired "I'm deaf or hard of hearing, so making phone calls is a problem for me. What do I have to keep in mind when I'm using the app?"

- https://www.coronawarn.app/de/faq/#hearing_impaired "Ich bin gehörlos oder schwerhörig. Telefonieren ist problematisch für mich. Worauf muss ich bei der Nutzung der App achten?"

## Describe the issue

The article says:

"In general, you're not required to make phone calls in connection with the Corona-Warn-App. In case of a positive test result, you will get the result via a PCR-Test QR code, which you can scan into the app. If the testing facility doesn't support QR codes or if you don't want to use them, you receive a TAN. Only if you have received neither a QR code nor a TAN, would you have to call the TAN hotline, which you might not be able to do without outside help.

If you can't make phone calls because you're hard of hearing, you should mention this during the test, because this will affect the whole communication process. You will then receive the TAN, if necessary, in writing."

Based on the comment https://github.com/corona-warn-app/cwa-documentation/issues/509#issuecomment-764622025 " I got feedback: The only way teleTANs are issued is via the hotline in verbal form." from @dsarkar the above text does not make sense, because TANs are not issued by laboratories.

## Suggested change

- Review the article for correctness and modify accordingly.
- Ensure that the article covers the case of Rapid Antigen Tests as well as PCR tests.

This needs input from the Open Source Team as I am unsure about the correctness of the details.

---
Internal Tracking ID: [EXPOSUREAPP-14496](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14496)

**Comment by MikeMcC399** [comment]
Due to introduction of TANs which can be issued by health authorities for "warn-on-behalf-of" this is another reason to review the article for correctness.

See https://www.coronawarn.app/en/blog/2021-09-08-cwa-version-2-9/.

**Comment by MikeMcC399** [comment]
- Also related to https://github.com/corona-warn-app/cwa-documentation/issues/697.

**Comment by Ein-Tim** [comment]
Is there any update on this issue available? There was no feedback from the @Open-Source-Team yet.

**Comment by MikeMcC399** [comment]
- This issue will need review depending on the issue https://github.com/corona-warn-app/cwa-hotline/issues/31

**Comment by MikeMcC399** [comment]
When CWA 3.0 is released, these articles should be reviewed:

- https://www.coronawarn.app/en/faq/#hearing_impaired "I'm deaf or hard of hearing, so making phone calls is a problem for me. What do I have to keep in mind when I'm using the app?"

- https://www.coronawarn.app/de/faq/#hearing_impaired "Ich bin gehörlos oder schwerhörig. Telefonieren ist problematisch für mich. Worauf muss ich bei der Nutzung der App achten?"

**Comment by MikeMcC399** [comment]
- This issue is resolved by PR https://github.com/corona-warn-app/cwa-website/pull/3321
