### ISSUE TITLE
Reminder: CWA 2.7 missing FAQ #hc_signature_invalid

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1594]
## Where to find the issue

https://www.coronawarn.app/en/faq/ and
https://www.coronawarn.app/de/faq/ 

## Describe the issue

The as yet unreleased CWA 2.7 links to the as yet non-existing FAQ articles
https://www.coronawarn.app/en/faq/#hc_signature_invalid and
https://www.coronawarn.app/de/faq/#hc_signature_invalid

String name in Android `dcc_signature_validation_dialog_faq_link`

This is not an issue until the app version 2.7 is released, but based on the experience with previous releases there may be a planning gap.

### Steps to reproduce

1. On CWA Android 2.7 RC tap on Certificates
2. Scan unsigned vaccination certificate [Demo QR Code](https://github.com/Digitaler-Impfnachweis/certification-apis/blob/master/examples/01_example.png)
3. Note error message: "Signature invalid HC_DSC_NO_MATCH"
4. Tap on "FAQ FOR SIGNATURE VALIDATION"
5. Note that browser tries to open https://www.coronawarn.app/en/faq/#hc_signature_invalid which does not exist, so the FAQ list is shown with only titles, no content.

## Suggested change

1. Create draft content for #hc_signature_invalid in English and German
2. Publish FAQ content in time for CWA 2.7 release

---
Internal Tracking ID: [EXPOSUREAPP-8748](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8748)

**Comment by dsarkar** [comment]
**DE**

Warum erhalte ich die Fehlermeldung, dass mein Zertifikat ungültig ist?

Die Signatur des Zertifikats ist ungültig.
Damit ist das ganze Zertifikat als digitales Dokument ungültig. Es kann daher nicht als Nachweis verwendet und auch nicht in die App importiert werden. Tritt diese Fehlermeldung bei einem bereits importierten Zertifikat auf, wird es nun als "ungültig" markiert.
Prüfen Sie bitte, ob die Gültigkeit Ihres Zertifikats abgelaufen ist:
- In der Regel ist ein in Deutschland ausgestelltes Impfzertifikat ein Jahr ab Ausstellungdatum gültig.
- Ein Genesenen-Zertifikat darf lt. Festlegung der EU dagegen nicht länger als 180 Tage ab dem Datum des letzten positiven PCR-Tests gültig sein.

Ist Ihr Zertifikat technisch noch gültig, wurde es offenbar von einer nicht autorisierten Stelle oder fehlerhaft ausgestellt. In diesem Fall bitten wir Sie,  sich an die technische Hotline zu wenden und uns mitzuteilen, wann und von welcher Stelle dieses Zertifikat ausgestellt wurde. Dann lassen Sie sich bitte ein neues Zertifikat mit gültiger Signatur von einer autorisierten Stelle ausstellen.

**EN**

ToDO

**Comment by larswmh** [comment]
@dsarkar ich werde den FAQ Eintrag in einem zukünfigten Pull Request hinzufügen

**Comment by MikeMcC399** [comment]
This issue is resolved by PR #1615.
