### ISSUE TITLE
Text is cut off in some science blog tables

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1598]
## Where to find the issue
https://www.coronawarn.app/de/science/2021-08-02-science-blog-3/

## Describe the issue
The text in some of the tables is cut off and thus important information to understand the table is missing.

Tables which are affected: 
- https://github.com/corona-warn-app/cwa-website/blob/master/science/2021-08-02-science-blog-3/tab_06.png
- https://github.com/corona-warn-app/cwa-website/blob/master/science/2021-08-02-science-blog-3/tab_14.png
- https://github.com/corona-warn-app/cwa-website/blob/master/science/2021-08-02-science-blog-3/tab_16.png

## Suggested change
Correct the tables.

## Additional information
I searched for issues covering this, but did not find any. Please let me know if this is already covered in another issue. (:

---
Internal Tracking ID: [EXPOSUREAPP-8784](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8784)

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Your issue is related to https://github.com/corona-warn-app/cwa-website/issues/1573.

@dsarkar wrote that the tables are planned to be regenerated.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks Mike, I actually saw #1573 but thought that this is a new issue. 

I'll leave this open until the tables are regenerated.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Yes, it is a different issue, but the resolution is probably the same as #1573.  It is good for you to leave it open, as you suggest, until a fix is provided and can be checked.

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Thanks. Tracked in the same internal ticket.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
PR #1745 has reworked https://www.coronawarn.app/de/science/2021-08-02-science-blog-3/

Of the three tables you mentioned, 

- https://github.com/corona-warn-app/cwa-website/blob/master/science/2021-08-02-science-blog-3/tab_14.png

has been updated and is readable.

The other two tables:

- https://github.com/corona-warn-app/cwa-website/blob/master/science/2021-08-02-science-blog-3/tab_06.png
- https://github.com/corona-warn-app/cwa-website/blob/master/science/2021-08-02-science-blog-3/tab_16.png

Do not exist as separate files any more.

As far as I can see, looking at the page https://www.coronawarn.app/de/science/2021-08-02-science-blog-3/, all the tables are now readable. To view some tables, you need to click on the arrow symbol.

Maybe you'd like to check yourself?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks for checking! 

I just took a look at it myself and yes, this seems to have been fixed.

Closing as fixed.
