### ISSUE TITLE
Create FAQ to remove a certificate

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1606]
## Feature description

Add an FAQ article to describe how to remove a digital certificate from the app under Android and iOS.

## Problem and motivation

Users are having difficulty finding the option to remove a digital certificate from the app. See https://github.com/corona-warn-app/cwa-app-android/issues/3895.

A wishlist item has been submitted to improve the app usability https://github.com/corona-warn-app/cwa-wishlist/issues/608, however even if accepted it will still take time to implement and release an improvement.

## Is this something you're interested in working on

In https://github.com/corona-warn-app/cwa-website/pull/1600#issuecomment-895757291 @larswmh indicated that he would write such an article. I would leave the lead to him.

**Comment by larswmh** [comment]
Created a pull request with the requested FAQ article, thanks for the suggestion! https://github.com/corona-warn-app/cwa-website/pull/1607

**Comment by MikeMcC399** [comment]
@larswmh 
Should the article in PR https://github.com/corona-warn-app/cwa-website/pull/1607 only be about removing a vaccination certificate or should be it more general and cover all types of certificate (test and recovery)?

**Comment by larswmh** [comment]
@MikeMcC399 I'll make it more generalized in the next commit, thanks!

**Comment by MikeMcC399** [comment]
Resolved through PR https://github.com/corona-warn-app/cwa-website/pull/1607

New articles are:
- https://www.coronawarn.app/en/faq/#eu_dcc_remove "How do I remove a certificate from the Corona-Warn-App?"
- https://www.coronawarn.app/de/faq/#eu_dcc_remove "Wie kann ich ein Zertifikat aus der Corona-Warn-App entfernen?"
