### ISSUE TITLE
Add a new content section for inplementing test centers

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#1608]
## Feature description

Add a new content section for inplementing test centers

## Problem and motivation

Higher visibility, direct interested parties to the corresponding GitHub repository

## Navigation

![image](https://user-images.githubusercontent.com/1409741/128870692-654f4652-d3b8-4a0b-b945-78222711481a.png)

## Content

[RAT-partner-on-CWA-webpage.pdf](https://github.com/corona-warn-app/cwa-website/files/6961797/RAT-partner-on-CWA-webpage.pdf)

## Todo

- English translation

---
Internal Tracking ID: [EXPOSUREAPP-7583](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7583)

**Comment by Ein-Tim** [comment]
Please don't remove the whole Community section as shown in the PDF, rather create a new page for quick test partners (and mention it on the community page).

**Comment by dsarkar** [comment]
@Ein-Tim Yes, we will note remove the community page. this will be a new page. We still have to determine if at all there should be a separate menu entry in the header.

**Comment by MikeMcC399** [comment]
@dsarkar 
I would suggest adding a link "Partners" in the footer in the column "Get involved".

Partners could cover:
- Event app partners
- PCR test partners
- Rapid test partners

![image](https://user-images.githubusercontent.com/66998419/128875497-0a0f80a1-b676-45a9-8c3e-57cfb04d6762.png)

Consider also creating a separate website (like https://partners.coronawarn.app/) for the special needs of partners. (Probably you won't do this, but you should think about it.)

**Comment by MikeMcC399** [comment]
@dsarkar 
I believe that this issue has been resolved by PR #1612 which you merged on Aug 12, 2021.

**Comment by dsarkar** [comment]
@MikeMcC399 Yep, you are right.
