### ISSUE TITLE
"Wo kann ich mich testen lassen?" should link to FAQ article

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#1611]
## Where to find the issue

Main page: link "Wo kann ich mich testen lassen?"
All other pages: link "Wo kann ich mich testen lassen?"

## Describe the issue

- "Wo kann ich mich testen lassen?" links to https://map.schnelltestportal.de
- https://map.schnelltestportal.de lists mainly RAT centres, but not PCR test centres 
- The FAQ article provides more options to find a test center

## Suggested change

- "Wo kann ich mich testen lassen?" should link to the FAQ article https://www.coronawarn.app/de/faq/#where_can_i_get_tested
- similar in EN

---
Internal Tracking ID: [EXPOSUREAPP-8937](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8937)

**Comment by Ein-Tim** [comment]
I can provide a PR for this if you want to @dsarkar.

**Comment by dsarkar** [comment]
@Ein-Tim Very happy if you do so! Thanks!

At the same time, I suggest also to modify the FAQ article https://www.coronawarn.app/de/faq/#where_can_i_get_tested:

Use for the images the following, looks nicer:
`<div class='right-float'><img src='../../assets/img/faq/image-file-name' alt='image' width='300'></div>`
and/or
`<div class='left-float'><img src='../../assets/img/faq/image-file-name' alt='image' width='300'></div>`
