### ISSUE TITLE
Glossary naming and placement of links

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1625]
## Where to find the issue

https://www.coronawarn.app/en/faq/
https://www.coronawarn.app/en/faq/#glossary Glossary

https://www.coronawarn.app/de/faq/
https://www.coronawarn.app/de/faq/#glossary Glossar

## Describe the issues

This is a follow-on to https://github.com/corona-warn-app/cwa-website/issues/1540

1. The name "Glossary / Glossar" implies that it is a glossary covering all aspects of CWA, however the currently published terms only deal with EU Digital COVID Certificates (DCC) and nothing more.
2. At the top of the German language FAQ page https://www.coronawarn.app/de/faq/ the FAQ contains a link https://www.coronawarn.app/de/faq/#glossary to the Glossar at the bottom of the page. Positioning the link at the top of the page implies that the Glossary covers all topics in the FAQ.
3. At the top of the English language FAQ page https://www.coronawarn.app/en/faq/ there is no link to the Glossary https://www.coronawarn.app/en/faq/#glossary. This is inconsistent compared with the German page https://www.coronawarn.app/de/faq/ which does contain a link.

## Suggested changes

1. Change the name of the Glossary on the FAQ page to "Certificate Glossary" / "Zertifikatsglossar" if there is no intention of expanding the scope of the Glossary to cover other topics apart from certificates.
2. If the name is changed, consider moving the link in the German language https://www.coronawarn.app/de/faq/ to the Glossary from the top of the FAQ page to the https://www.coronawarn.app/de/faq/#eu_dcc section, possibly with a new FAQ article.
3. Add a link in the English language https://www.coronawarn.app/en/faq/ to the English language Glossary https://www.coronawarn.app/en/faq/#glossary either at the top of the page, or similar to what is decided for suggestion 2. above.

---
#1540 was linked to Internal Tracking ID: [EXPOSUREAPP-8934](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8934)

**Comment by larswmh** [comment]
Although the glossary might not contain a lot of entries at the moment, it is planned to include as many terms that need further explaination as possible. The open source community is invited to suggest new glossary entries. Therefore I wouldn't rename it or change its position. 

The link to the glossary on the english page will follow later today.

**Comment by MikeMcC399** [comment]
@larswmh 
> ... it is planned to include as many terms that need further explaination as possible. The open source community is invited to suggest new glossary entries. Therefore I wouldn't rename it or change its position.

If that is the plan, then I withdraw my suggestion to rename the glossary.

> The link to the glossary on the english page will follow later today.

Thank you!

**Comment by MikeMcC399** [comment]
Closing:

1, The Glossary is planned to cover more topics
2. The link https://www.coronawarn.app/en/faq/#glossary has been added to https://www.coronawarn.app/en/faq/ via #1629.
