### ISSUE TITLE
FAQ: How to manage multiple rapid antigen tests with certificates

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1626]
## Where to find the issue

https://www.coronawarn.app/en/faq/#rat_multiple_rat "Can I save/manage multiple rapid antigen tests?"
https://www.coronawarn.app/de/faq/#rat_multiple_rat "Kann ich mehrere Schnelltests speichern/verwalten?"

## Describe the issue

- This issue follows on from a question https://github.com/corona-warn-app/cwa-documentation/issues/685.

The answer to the question "Can I save/manage multiple rapid antigen tests?" does not consider the introduction of EU Digital COVID test certificates in [CWA 2.4](https://www.coronawarn.app/en/blog/2021-06-24-cwa-version-2-4) and especially the ability to manage multiple certificates introduced in [CWA 2.5](https://www.coronawarn.app/en/blog/2021-07-12-cwa-version-2-5/).

## Suggested change

Either the FAQ article 

https://www.coronawarn.app/en/faq/#rat_multiple_rat "Can I save/manage multiple rapid antigen tests?"
https://www.coronawarn.app/de/faq/#rat_multiple_rat "Kann ich mehrere Schnelltests speichern/verwalten?"

needs to be expanded to cover how to handle rapid antigen tests for multiple people when the aim is to present EU Digital COVID test certificates for those people in CWA on one mobile device.

OR

A new FAQ should be written explaining the steps above and linked into the original article #rat_multiple_rat.

## Additional comments

@Ein-Tim 
- If you want to pick this up, as you suggested in https://github.com/corona-warn-app/cwa-documentation/issues/685#issuecomment-899018933 then please go ahead!

**Comment by Ein-Tim** [comment]
I will take care of this!

**Comment by Ein-Tim** [comment]
My proposal:
![Bildschirmfoto 2021-08-16 um 22 25 49](https://user-images.githubusercontent.com/67682506/129625232-a67c1968-f80b-4e29-afab-e0a8a2e3428d.png)

Feedback is welcome!

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I'm not sure that the trick of registering multiple rapid antigen tests, one after another, is a safe way to use the app or a good recommendation, even if it would work like this.

Registering a test is about getting a positive result to share, but only for the user of the device, or to get a negative result which may be recorded as a certificate.

There is a danger that a positive test result from a family member who is not the user of the device may end up warning the wrong people. 

It may be better to try to cover this case with an enhancement request first, so that there is a way to register additional RATs in the app at the same time without the danger that a positive result could be used incorrectly when sending out a warning.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim This is in fact an important discussion. The feature enhancement to be able to register and manage several tests at the same time had been declined by the stakeholders some time ago. This does not mean that the topic cannot be brought up again in near future. 

However, in the meantime, the workaround described by @Ein-Tim can help e.g. families to store test certificates of their children. On the other side there are valid concerns as you mention @MikeMcC399. We will clarify internally how to proceed with this. Probably a solution is to explicitly mention in the FAQ, besides the workaround, in a clear statement that responsible use must be made, when registering tests which do not correspond to the main user of the device. 

IN this context, another feature enhancement would be a tick box in the app "This is my test" when registering a test. If not checked, sharing a positive result would not be offered.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, true. Do you see any short-time solution for this issue then? What should we recommend to the user who needs DCCs now and their only way to get them is the Corona-Warn-App. I wouldn't want to leave the user alone here.

@dsarkar Thanks for jumping in here and giving some feedback. I'll wait for the clarification then 👍

> IN this context, another feature enhancement would be a tick box in the app "This is my test" when registering a test. If not checked, sharing a positive result would not be offered.

Should I open a new wishlist issue to track this feature request? 

> The feature enhancement to be able to register and manage several tests at the same time had been declined by the stakeholders some time ago. This does not mean that the topic cannot be brought up again in near future.

Yes, I think this should definitely be reevaluated, see also https://github.com/corona-warn-app/cwa-wishlist/issues/109#issuecomment-896380231.

**Comment by dsarkar** [comment]
> Should I open a new wishlist issue to track this feature request?

@Ein-Tim Yes, please. Thank you!

**Comment by MikeMcC399** [comment]
@dsarkar 
It is good to hear that the issue will discussed internally. I probably don't have the right level of process know-how for the RAT test flow to contribute much more, especially about the possibility to deliver negative test results and test certificates outside of the CWA app for a group of people such as parents with younger children.

If a user can receive test certificates outside of the app, then can just be scanned in.
 
Maybe it does need a separate family testing function built in to CWA, which ensures that no false warnings are distributed in case of any positive results.

If the suggestion from @Ein-Tim is published then probably some additional instructions need to be added to help prevent positive results for the wrong person, i.e. not the smartphone user, to be shared.

**Comment by Ein-Tim** [comment]
There was no progress on this issue since some months & I step back from my proposal above, as the situation has changed again with the introduction of the recycle bin.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- It looks like this will be covered in CWA 2.20 https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.21.0-rc.1 under the name of "family tests".

- https://github.com/corona-warn-app/cwa-wishlist/issues/623 is now showing a 2.21 label as well.

**Comment by MikeMcC399** [comment]
- This issue will be covered by https://github.com/corona-warn-app/cwa-website/pull/2704 to be published with the release of CWA 2.21.

**Comment by MikeMcC399** [comment]
The following FAQs have been updated with the release of CWA 2.21 and therefore this issue is now resolved:

- https://www.coronawarn.app/en/faq/results/#rat_multiple_rat "Can I save/manage multiple rapid antigen tests?"
- https://www.coronawarn.app/de/faq/results/#rat_multiple_rat "Kann ich mehrere Schnelltests speichern/verwalten?"
