### ISSUE TITLE
Old screenshot versions claim they are "current release"

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1637]
### Screenshots CWA 2.6
https://www.coronawarn.app/en/screenshots-archive/2-6.html
https://www.coronawarn.app/de/screenshots-archive/2-6.html

### Screenshots CWA 2.5
https://www.coronawarn.app/en/screenshots-archive/2-5.html
https://www.coronawarn.app/de/screenshots-archive/2-5.html

## Describe the issue

The screenshot text for CWA 2.5 and 2.6 both claim that they are the current version. The current version is in fact 2.7.

## Suggested change

Remove the statement in 
- https://www.coronawarn.app/en/screenshots-archive/2-6.html
- https://www.coronawarn.app/de/screenshots-archive/2-6.html
- https://www.coronawarn.app/en/screenshots-archive/2-5.html
- https://www.coronawarn.app/de/screenshots-archive/2-5.html

referring to "current version" / "aktuelle Release" when the statement is no longer true.

Also preferably write text for 2.7 and future versions so that it does not need to be changed when a newer version is released.

**Comment by Ein-Tim** [comment]
@dsarkar Since I did not find a branch from you in https://github.com/corona-warn-app/cwa-website/branches/active I decided to quickly fix this by myself. I hope you didn't start to work on this already.

PR #1638 open and ready for review.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for pointing out the issue. @Ein-Tim Thanks for fix.
