### ISSUE TITLE
Create FAQ eu_dcc_export 

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#1645]
## Describe the issue
EU DCC Export function will be implemented and there will be a links in the CWA to the FAQ.

The functionality covers:
- PDF can be generated for all types of DCCs with different templates (vaccination, test, recovery)
- PDF can be generated only for DCCs issued in Germany
- for DCCs issued by another country, an error message is presented to the user
- Original EU template used for printing
- PDF can be shared using the standard OS sharing functionality

Issue:
- The FAQ entry will be linked to if printing fails because the certificate was not issued in Germany. This should be covered in the FAQ entry, see https://github.com/corona-warn-app/cwa-website/issues/1645#issuecomment-902558208 
- Links to FAQ:
  - EN https://www.coronawarn.app/en/faq/#eu_dcc_export
  - DE https://www.coronawarn.app/de/faq/#eu_dcc_export 
  - see https://github.com/corona-warn-app/cwa-app-ios/pull/3388 
     - "HealthCertificate_Print_FAQ_Link" = "https://www.coronawarn.app/en/faq/#eu_dcc_export";
     - "HealthCertificate_PrintPdf_ErrorAlert_Message" = "Die Druckversion des Zertifikats kann nicht angezeigt werden, da das Zertifikat nicht in Deutschland ausgestellt wurde.";

<img width="305" alt="image" src="https://user-images.githubusercontent.com/1409741/130219743-2dc96111-8a10-4d73-ad10-326db6e496b2.png">

## Suggested change

Create FAQ articles

Link to FAQ:

- EN https://www.coronawarn.app/en/faq/#eu_dcc_export
- DE https://www.coronawarn.app/de/faq/#eu_dcc_export 

---
Internal Tracking ID: [EXPOSUREAPP-9112](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9112)

Related:
Internal Tracking ID: [EXPOSUREAPP-8384](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8384)
Internal Tracking ID: [EXPOSUREAPP-8900](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8900)

**Comment by Ein-Tim** [comment]
The FAQ entry will be linked to if printing fails because the certificate was not issued in Germany. This should be covered in the FAQ entry.

**Comment by dsarkar** [comment]
@Ein-Tim Yes, indeed. Thanks for raising that point.

**Comment by dsarkar** [comment]
Wie erstelle ich einen Ausdruck meines Digitalen COVID Zertifikates der EU?
Zweck 
Ab der Version 2.10 der Corona-Warn-App können Sie eingescannte Digitale COVID Zertifikate der EU in PDF-Dokumente exportieren. Diese Funktion dient vorrangig der Erstellung von Sicherheitskopien der Zertifikate für Ihre persönlichen Zwecke.
Selbstverständlich werden für das Layout der Zertifikate die Original-EU-Vorlagen benutzt. 
Sicherheitshinweise
Der Export und die Speicherung der Zertifikate sind freiwillig. Das Erstellen der PDF-Datei findet ausschließlich lokal auf Ihrem Smartphone statt. Nur Sie selbst haben Zugriff auf dieses Dokument.
Beachten Sie aber, dass das erzeugte Dokument sensible persönliche Informationen enthält. Gehen Sie daher bitte sorgsam mit der PDF-Datei um. Zeigen Sie das Dokument nur solchen Personen vor, denen Sie vertrauen und die zur Prüfung auch berechtigt sind.
Wir raten dringend davon ab, das PDF-Dokument zu veröffentlichen über potentiell unsichere Kanäle (z.B. per E-Mail oder über andere Apps) zu teilen.
Limitierung
Mit der neuen Funktion können nur PDF-Dokumente von Zertifikaten erzeugt werden, die auch in Deutschland ausgestellt wurden. Ansonsten erscheint eine ausführliche Meldung: “Druckversion anzeigen nicht möglich - Die Druckversion des Zertifikats kann nicht angezeigt werden, da das Zertifikat nicht in Deutschland ausgestellt wurde."
Anwendung
Nach dem erfolgreichen Export des Zertifikates in das PDF-Dokument können Sie entscheiden, ob Sie es auf Ihrem Smartphone speichern, in andere Apps importieren oder drucken möchten. Dazu nutzen Sie bitte die Standard-Funktionen des Betriebssystems. 
Schritt-für-Schritt-Anleitung:
-	Um einen Ausdruck Ihres Digitalen COVID Zertifikates der EU zu erstellen, gehen Sie bitte folgendermaßen vor:
-	Klicken Sie auf den „Zertifikate“-Reiter in der Corona-Warn-App
-	Wählen Sie eine Person aus, indem Sie in der Zertifikate-Übersicht auf ein entsprechendes Zertifikat klicken
-	Scrollen Sie nach unten und wählen Sie ein Zertifikat dieser Person aus 
-	In dieser Detailansicht klicken Sie oben rechts auf das Drei-Punkte-Menü (Android) beziehungsweise unten auf „Mehr“ (iOS)
-	Klicken Sie auf „Druckversion anzeigen“
-	Klicken Sie auf Weiter
-	Klicken Sie oben rechts auf das Symbol für “Drucken” oder für “Teilen”
-	In der folgenden Ansicht können Sie das erstellte PDF-Dokument mit den Standardfunktionen des Betriebssystems drucken, in andere Apps importieren oder auch teilen
