### ISSUE TITLE
`check_in_qr_warning` does not cover which warning is issued if one was checked in to an event up to 30 mins after a later positive tested person

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1651]
## Where to find the issue
- https://www.coronawarn.app/en/faq/#check_in_qr_warning
- https://www.coronawarn.app/de/faq/#check_in_qr_warning

## Describe the issue
In the app there is this information: 
![IMG_240891DC9EF2-1](https://user-images.githubusercontent.com/67682506/130323398-c6217520-0109-4248-bd79-0057e7b30a96.jpeg)

However, this is not mentioned in the above mentioned FAQ entry, it only says:
"As a result, all other participants who were checked in **at the same time** will receive an immediate warning without having to burden the health authorities." 
or
"The calculation of the risk depends on whether and for how long a user's attendance **overlaps** with the attendance of a person who later tested positive about COVID-19." 

## Suggested change
Add the information which risk status (low or high risk) is shown in case a user gets warned because he/she was checked in up to 30 min after a later positive tested person.

**Comment by Ein-Tim** [comment]
The FAQ entry https://www.coronawarn.app/en/faq/#check_in_qr_warning has been deleted and no redirect for it was implemented. I will provide a PR adding a redirect from https://www.coronawarn.app/en/faq/#check_in_qr_warning to https://www.coronawarn.app/en/faq/results/#check_in.

**Comment by Ein-Tim** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/2749 provided. This issue is obsolete and can be closed.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The text you mentioned "As a result, all other participants who were checked in at the same time will receive an immediate warning without having to burden the health authorities." is part of https://www.coronawarn.app/en/faq/results/#check_in_qr_warning_procedure

"The calculation of the risk depends on whether and for how long a user's attendance overlaps with the attendance of a person who later tested positive about COVID-19." is part of
https://www.coronawarn.app/en/faq/results/#check_in_qr_warning_how

**Comment by Ein-Tim** [comment]
Thank you @MikeMcC399! 

I'm thinking about submitting a PR for this.

**Comment by Ein-Tim** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/2759 provided.
