### ISSUE TITLE
Screenshots page: Changing version defaults back to iOS screenshots

### ISSUE THREAD

**Issue by Marcono1234** [corona-warn-app/cwa-website#1652]
## Where to find the issue
https://www.coronawarn.app/de/screenshots/#

## Describe the issue
Switching to the "Android Screenshots" tab, then selecting a different app version, e.g. 2.5, from the versions dropdown defaults back to showing iOS screenshots.
This is slightly inconvenient and confusing.

Tested browsers:
- Firefox 91.0.1 (64-Bit)
- Microsoft Edge Version 92.0.902.78 (Official build) (64-bit)

## Suggested change
When selecting a different version from the versions dropdown the selected device type (iOS or Android) should be remembered.

**Comment by dsarkar** [comment]
@Marcono1234 OK, I see, and agree. We will see if there is a "easy solution".

**Comment by dsarkar** [comment]
@Marcono1234 This was recently fixed. Thanks for contributing here.
