### ISSUE TITLE
Screenshots page: Android uses anchor `ios_rat`

### ISSUE THREAD

**Issue by Marcono1234** [corona-warn-app/cwa-website#1653]
## Where to find the issue
https://github.com/corona-warn-app/cwa-website/blob/ff40e69e20050ef9f0110c987aa0442b34e1d85d/src/data/screenshots-archive-2-3.json#L112

## Describe the issue
A section for Android screenshots uses an anchor called `ios_rat`.

:warning: This might affect more than just the version 2.3 page.

## Suggested change
- Fix the incorrect anchor.
- If possible: Add a GitHub workflow (or enhance the current workflow) verifying that all Android anchors start with `android_` and all iOS anchors start with `ios_`.

**Comment by dsarkar** [comment]
@Marcono1234 Thanks. Do you want to offer a fix PR?

**Comment by Marcono1234** [comment]
@dsarkar, created #1656

**Comment by dsarkar** [comment]
@Marcono1234 Your Pr was merged. Thanks.

**Comment by dsarkar** [comment]
fixed
