### ISSUE TITLE
Screenshots page: Multiple screenshots have alt text "Image/Bild"

### ISSUE THREAD

**Issue by Marcono1234** [corona-warn-app/cwa-website#1655]
## Where to find the issue
https://github.com/corona-warn-app/cwa-website/blob/d8ab82dd48c6142786b62f3debe3d4109e63990b/src/data/screenshots.json#L136

## Describe the issue
Multiple screenshots just have the generic `alt` text "Image/Bild". This might not be very good for accessibility.

:warning: This affects more than the linked `screenshots.json`.

## Suggested change
Not quite sure what the best way to solve this would be. This might not be that problematic because the whole page is dedicated to screenshots and therefore most likely not visited by someone with reduced vision (?).

So some possible solutions might be:
- Use a proper `alt` text
- Simply omit the pointless "Image/Bild" `alt` text since it adds little value
- Omit the pointless "Image/Bild" and for screenshots without `alt` use "Screenshot" as default; this could possibly be specified [here](https://github.com/corona-warn-app/cwa-website/blob/0b5f325b232ccd883a69e0f6ed54cb5377f7e63d/src/partials/page-screenshots.html#L75-L76)?

---

Also for what it's worth, the numeration of some of the screenshots is incorrect, e.g. (all have "1 von 3"):
https://github.com/corona-warn-app/cwa-website/blob/d8ab82dd48c6142786b62f3debe3d4109e63990b/src/data/screenshots-archive-2-6_de.json#L341-L343

Ideally this text ("n von N" / "n of N") would be automatically generated (maybe [here](https://github.com/corona-warn-app/cwa-website/blob/0b5f325b232ccd883a69e0f6ed54cb5377f7e63d/src/partials/page-screenshots.html#L75-L76)?) since this is often incorrect or outdated.

And some of the English screenshots use the German `alt` texts, e.g.:
https://github.com/corona-warn-app/cwa-website/blob/ff40e69e20050ef9f0110c987aa0442b34e1d85d/src/data/screenshots.json#L369

**Comment by larswmh** [comment]
Fixed with PR #1663
