### ISSUE TITLE
Discussion: Screenshots page: Do we maintain all versions or only the ones from the current version?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1660]
Hi everyone, concerning the latest issues and discussion regarding the screenshots page, I thought a little hint from the Open-Source team on whether we want to maintain the screenshots of all versions since the screenshots archive was started or do we only maintain the currently latests versions screenshots?

Definition of maintain:
- Fix issues with the alt texts
- Fix screenshots
- Delete unused screenshots
- etc.

**Comment by svengabr** [comment]
We are currently not supporting content changes on old screenshot releases. They are simply archived and not to be touched again. We try our best to always fix all issues in the current version, which is later to be archived.
