### ISSUE TITLE
Make bookmarking glossary entries easier

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1673]
## Where to find the issue

https://www.coronawarn.app/en/faq/#glossary "Glossary"
https://www.coronawarn.app/de/faq/#glossary "Glossar"

## Describe the issue

This is an enhancement request.

PR https://github.com/corona-warn-app/cwa-website/pull/1672 "Glossary anchors introduced bookmarks for glossary entries e.g. the URL https://www.coronawarn.app/en/faq/#glossary_business_rules links to the Glossary entry labelled "Business Rules".

![image](https://user-images.githubusercontent.com/66998419/131108308-936be202-b705-481f-a1c8-95b7b6d0d5f1.png)

A casual website user who would like to bookmark this entry has no easy means to find out the name of the anchor used. 

## Suggested change

Add a method for each Glossary entry to allow a user to find out the link to a Glossary entry and use it to bookmark or refer to it from elsewhere.

FAQ entries each have a "Link to this answer" line which can be used to bookmark or copy the link.

For example https://www.coronawarn.app/en/faq/#vac_cert_internet

![image](https://user-images.githubusercontent.com/66998419/131107946-72850e34-d560-44d6-9aa5-7727d1273f16.png)

Perhaps this could also be applied to glossary entries?

---
Internal Tracking ID: [EXPOSUREAPP-9226](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9226)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reporting this issue, no need to open another issue.

**Comment by MikeMcC399** [comment]
#1678 depending on this issue being solved.
