### ISSUE TITLE
Glossary => cross-references

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1678]
## Where to find the issue

- https://www.coronawarn.app/en/faq/#glossary "Glossary"
- https://www.coronawarn.app/de/faq/#glossary "Glossar"

## Describe the issue

Multiple glossary entries use "=>" to refer to another glossary entry. For instance, - https://www.coronawarn.app/en/faq/#glossary_recovery_certificate says

"**Recovery Certificate**

The certificate of recovery is a => digital certificate issued for a person who has demonstrably recovered from COVID-19 and proved immunity by a PCR test."

where `=> digital certificate` is a cross-reference to https://www.coronawarn.app/en/faq/#glossary_digital_certificate

## Suggested change

Replace all such occurrences of `=> cross-reference target` with an HTML link.

## Additional comment

I would want the generic link issue https://github.com/corona-warn-app/cwa-website/issues/1673#issuecomment-907318956 clarified first before proceeding on this issue. Edit: https://github.com/corona-warn-app/cwa-website/issues/1673 is now resolved.

**Comment by dsarkar** [comment]
@MikeMcC399 fixed in #1685

**Comment by MikeMcC399** [comment]
@dsarkar 
> fixed in #1685

Mostly good. Thank you @larswmh!

https://www.coronawarn.app/de/faq/#glossary_vaccination_certificate has links added, but the `=>` string has not been removed.

**Comment by svengabr** [comment]
I think this might have been resolved by now, could you check again if you still have issues @MikeMcC399?

**Comment by MikeMcC399** [comment]
@svengabr 
> I think this might have been resolved by now, could you check again if you still have issues

Thanks for the reminder! PR https://github.com/corona-warn-app/cwa-website/pull/1686 resolved the remaining issue.
