### ISSUE TITLE
FAQ: Error 2001 missing link to firewall settings

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1680]
## Where to find the issue

- https://www.coronawarn.app/en/faq/#cause2001 "[Google/Android]: CAUSE: 2001, trying to establish a secure connection to the server"
- https://www.coronawarn.app/de/faq/#cause2001 "[Google/Android]: URSACHE: 2001, trying to establish a secure connection to the server"

## Describe the issue

The FAQ article [#cause2001](https://www.coronawarn.app/en/faq/#cause2001) does not mention that firewall settings may also contribute to the error message "CAUSE: 2001" appearing.

## Suggested change

Add a troubleshooting step to [#cause2001](https://www.coronawarn.app/en/faq/#cause2001) in addition to checking for certificates enabled which refers to firewall settings and links to the corresponding firewall article [#access-list](https://www.coronawarn.app/en/faq/#access-list) for both languages.

- https://www.coronawarn.app/en/faq/#cause2001 "[Google/Android]: CAUSE: 2001, trying to establish a secure connection to the server" to be linked to https://www.coronawarn.app/en/faq/#access-list "[Google/Android]: Firewall/Router configuration: CAUSE: 4000, error during web request, HTTP status 901".
- https://www.coronawarn.app/de/faq/#cause2001 "[Google/Android]: URSACHE: 2001, trying to establish a secure connection to the server" to be linked to https://www.coronawarn.app/de/faq/#access-list "[Google/Android]: Firewall/Router Konfiguration: URSACHE: 4000, error during web request, HTTP status 901"

## Background information

In https://github.com/corona-warn-app/cwa-app-android/issues/968#issuecomment-907159657 and previous posts in that thread user @Goliath0 reported that certificates were active and there was still a problem with error message 2001. On the advice of @vaubaehn the user wrote that they allowed access to `svc80.main.px.t-online.de` (sic) and @Goliath0 confirmed in https://github.com/corona-warn-app/cwa-app-android/issues/968#issuecomment-907164158 that this solved the issue.

Edit: Note that the app does not use `svc80.main.px.t-online.de` 
https://github.com/corona-warn-app/cwa-app-android/blob/main/prod_environments.json defines
` "DOWNLOAD_CDN_URL": "https://svc90.main.px.t-online.de",`
so we assume the user intended to write `https://svc90.main.px.t-online.de`.

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/1681 opened to resolve this issue arising from https://github.com/corona-warn-app/cwa-app-android/issues/968#issuecomment-907159657.

**Comment by vaubaehn** [comment]
> On the advice of @vaubaehn the user allowed access to svc80.main.px.t-online.de

I think there was a typo in the user's response, because as far as I know, svc**9**0.main.px.t-online.de is still hardcoded in the app, and svc80.main.px.t-online.de results in 'access denied'. But this should not be an issue for this PR here.

**Comment by Goliath0** [comment]
I'm not sure. svc90 is also free in the blocklist. I whitelisted svc80. Maybe this was not needed. A typo? The reason must be, that an update of the blocklist occured and have one of this URL which I gave free. Thanks all. My blocklists are AdAway official hosts,  Pete Lowe blocklist hosts, StevenBlack Unified hosts (the later is two days old and must be the issue.)

**Comment by MikeMcC399** [comment]
@vaubaehn 

>I think there was a typo in the user's response, because as far as I know, svc90.main.px.t-online.de is still hardcoded in the app, and svc80.main.px.t-online.de results in 'access denied'. But this should not be an issue for this PR here.

Thanks for pointing out the typo! The PR does not specifically mention this node name, only `*.t-online.de` through the reference to https://www.coronawarn.app/en/faq/#access-list. I edited the original entry above to highlight the typo so nobody is misled, trying to use the wrong node name.

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/1681 is merged, which resolves this issue.
