### ISSUE TITLE
Add FAQ entry or extend `cert_eu_travel` explaining why certificates listed as valid in CWA v 2.7 are shown as "Certificate Cannot Be Validated" in CWA v 2.8

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1682]
## Where to find the issue
- https://www.coronawarn.app/de/faq/#cert_eu_travel
- https://www.coronawarn.app/en/faq/#cert_eu_travel

## Describe the issue
See https://github.com/corona-warn-app/cwa-documentation/issues/678#issuecomment-907697651

## Suggested change
See https://github.com/corona-warn-app/cwa-documentation/issues/678#issuecomment-907706289 & https://github.com/corona-warn-app/cwa-documentation/issues/678#issuecomment-907777399

---
Internal Tracking ID: [EXPOSUREAPP-9279](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9279)

**Comment by Ein-Tim** [comment]
Proposed text by @vaubaehn:

**Update**
With version 2.8 the behaviour of the certificate validity check has changed. Entry rules for travellers have been set up by all EU member countries, but until today only a few countries provided technically translated entry rules which Corona-Warn-App can make use of. Before version 2.8, when there were no rules available to be downloaded for a certain country, after a check Corona-Warn-App displayed "Certificate Valid" and explained in the following text, that for this country no rules were provided/could have been checked. "Certificate Valid" referred to "Technical Validity" in this case [insert FAQ LINK here]. However, we understood that this result may be misinterpreted, for example when an incomplete vaccination was checked, the wrong conclusion could have been drawn, that this certificate warrants entry without restrictions. We clarified this since version 2.8: In case a member country did not provide technically translated entry rules for Corona-Warn-App, the headline now states "Certificate Cannot Be Validated", whereas the following texts stayed the same. This does not mean that your certificate is not valid or that you are not allowed to enter the country you checked your certificate against. In this case, please verify your status with information that you find in reopen.europa.eu. Further information on this change can be found in the second paragraph of this blogpost: [Corona-Warn-App version 2.8 displays names in certificates in standardized characters](https://www.coronawarn.app/en/blog/2021-08-25-cwa-version-2-8/)

**Why does the CovPass app show a different result when I check entry rules for a country that did not provide technically translated entry rules yet?**
The validity check for entry rules was first introduced in Corona-Warn-App with version 2.6.1. When this validity check was developed for CovPass, Corona-Warn-App's result screen served as a template for CovPass' current implementation. We are in contact with developers of CovPass to align the results of both apps.

**Comment by vaubaehn** [comment]
I'm not so happy that this is that long, but I'm afraid that otherwise most users won't understand what's going on when it's not explained in-depth.
Another thing that I'm a bit unhappy about is the term 'technically translated entry rules'. I was only Introducing it, because from user reports in the stores I understood, that entry rules published by countries in media are 'set equal' to the rules that CWA can check. I felt it is necessary to distinguish here so that users can understand why CWA can't check everything even though a country had published entry rules on their website.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I would hold back on mentioning contact with the CovPass App developers unless they have acknowledged a willingness to change, otherwise it may be setting false expectations.

**Comment by Ein-Tim** [comment]
I suggest to create a new FAQ entry: "Why does the Corona-Warn-App on version 2.8 show that my certificate couldn't be validated although the previous version showed my certificate as valid?"

**Comment by vaubaehn** [comment]
> I would hold back on mentioning contact with the CovPass App developers unless they have acknowledged a willingness to change, otherwise it may be setting false expectations.

Maybe then instead
> We are in contact with developers of CovPass to align the results of both apps.

better:
We are working on a common solution for both apps.
?
Because @mtwalli expressed already his agreement in this way
> Yes, we need to explain to them why there is inconsistency between the two Apps. I agree, we need to communicate that to CovPass team

which is first step on 'working on it'.
What do you think,

**Comment by Ein-Tim** [comment]
![Bildschirmfoto 2021-08-29 um 14 55 51](https://user-images.githubusercontent.com/67682506/131251064-9d967bcb-e715-46c9-9d10-f88409bce24f.png)

**Comment by vaubaehn** [comment]
> I suggest to create a new FAQ entry: "Why does the Corona-Warn-App on version 2.8 show that my certificate couldn't be validated although the previous version showed my certificate as valid?"

One practical reason to have it all in the one and old eu travel entry could be, that all business rules screens in CWA link to that entry. Without change in the code, the link in the screen for 'Certificate Cannot Be Validated' would not link to the explanation in the FAQ and could be missed, when not reading other FAQ entries.

Another option would be to create a new entry, and additionally place a link to that in the eu travel entry.

**Comment by Ein-Tim** [comment]
@vaubaehn 

I'd rather add a link to the old FAQ entry. Also, I'd place the new entry directly below the old one.

**Comment by vaubaehn** [comment]
@Ein-Tim 
> What do you think? I'll start to translate this now and provide a PR when the translation is finished.

For me this is very nice! ❤️ Thanks a lot!

**Comment by vaubaehn** [comment]
@dsarkar @heinezen 
Pinggggg...

**Comment by Ein-Tim** [comment]
PR: #1683

**Comment by vaubaehn** [comment]
Hi @dsarkar , do you consider to refer/instruct the app store support teams to point to the new FAQ entry in their responses to users?
At least in Google Play Store there are still users asking about the changed UI for countries without rules, but the answers didn't change yet.

**Comment by dsarkar** [comment]
@vaubaehn Sure, I let them know. Many thanks for pointing it out!
