### ISSUE TITLE
Create FAQ entry: "In Vertrung warnen"

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#1695]
**DE**

Als Organisator einer Veranstaltung können Sie ab der Version 2.9 nach Aufforderung durch das Gesundheitsamt Ihre Gäste in Vertretung für eine positiv getestete Person warnen, die an einer Veranstaltung teilgenommen hat, aber nicht über die Corona-Warn-App (CWA) eingecheckt war. 
Wird eine nicht eingecheckte Person später positiv getestet, können die Gäste gewarnt werden, wenn sie sich zur gleichen Zeit oder bis zu 30 Minuten nach der positiv getesteten Person im gleichen Raum aufgehalten haben.
Um als Organisator einer Veranstaltung andere Gäste über die CWA zu warnen, gehen Sie bitte folgendermaßen vor:

1.	Erhalten Sie im Nachhinein Kenntnis von der Gegenwart einer positiv getesteten Person auf Ihrer Veranstaltung, und hat das Gesundheitsamt Sie als Organisator einer Veranstaltung noch nicht kontaktiert, setzen Sie sich mit dem Gesundheitsamt in Verbindung. Das Gesundheitsamt kann Ihnen gegebenenfalls eine TAN ausstellen.
2. Klicken Sie auf der Startseite der CWA auf „QR-Code erstellen“.  
3. Klicken Sie auf der „Meine QR-Codes“-Seite oben rechts auf das Drei-Punkte-Menü und dann auf den Menüpunkt „In Vertretung warnen“. 
4. Klicken Sie auf dem Infoscreen auf „Weiter“. 
5. Wählen Sie eine Veranstaltung, für welches Sie in Vertretung einer infizierten Person andere warnen möchten. Oder stellen Sie eine gelöschte Veranstaltung wieder her, indem sie den QR-Code der Veranstaltung erneut einscannen. Klicken Sie auf „Weiter“. 
6. Geben Sie die Aufenthaltsdauer der positiv getesteten Person an, für die gewarnt werden soll. Diese Information erhalten Sie vom Gesundheitsamt. Klicken Sie auf „Weiter“.
7. Geben Sie die 10-stellige TAN ein, die Ihnen mitgeteilt wurde. Klicken Sie auf „Warnung abschicken“.

![image](https://user-images.githubusercontent.com/1409741/131668174-e06ff711-fb6d-4c44-a478-0644625a103a.png)

---
Internal Tracking ID: [EXPOSUREAPP-9181](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9181)

**Comment by MikeMcC399** [comment]
"In Vertrung warnen" => "In Vertretung warnen" in title of this issue.

Otherwise excellent functionality 👍🏻 and the text looks fine too 👍🏻!
