### ISSUE TITLE
QR-Code generation does not work ("Event" only)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1703]
## Where to find the issue
- https://www.coronawarn.app/en/eventregistration/
- https://www.coronawarn.app/de/eventregistration/

## Describe the issue
Attempting to generate a QR code of the type "Event" fails, if "Create" is clicked nothing happens.

## Screenrecording 

https://user-images.githubusercontent.com/67682506/132072579-d4c774fa-95f7-4568-9eb1-be9155c65ead.mp4

## Error in the console: 

```
[Error] AssertionError: Assertion failed
	(anonyme Funktion) (eventregistration.js:1:40694)
	(anonyme Funktion) (eventregistration.js:1:41075)
	(anonyme Funktion) (eventregistration.js:1:41287)
	(anonyme Funktion) (eventregistration.js:1:200993)
	(anonyme Funktion) (eventregistration.js:1:338446)
	(anonyme Funktion) (eventregistration.js:1:204498)
	(anonyme Funktion) (eventregistration.js:1:335349)
	(anonyme Funktion) (eventregistration.js:1:335162)
	(anonyme Funktion) (eventregistration.js:1:354264)
	(anonyme Funktion) (eventregistration.js:1:354828)
```

**Comment by Ein-Tim** [comment]
@dsarkar 

Is somebody working on a fix for this? I think it's very suboptimal that the QR code creation does not work on Safari.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for reporting, we will check.

**Comment by dsarkar** [comment]
@Ein-Tim Ok, Type "Events" is affected, not "Place". We are looking at it. Probably introduced with the multi QR functionality.

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/1706#pullrequestreview-747013803
reverts to commits.

**Comment by Ein-Tim** [comment]
@dsarkar 

Thanks. Since this will just revert the whole feature, this will also fix this issue.
I assume that when you add the feature back you will also make sure that the issue mentioned here does not appear again. 

Thanks for the fast response and taking care of it!

**Comment by dsarkar** [comment]
@Ein-Tim As mentioned by @svengabr, two commits are reverted. #1575 introduced this issue for Mac only apparently. The multi QR code generator is unrelated to this issue but was taken offline in order to fix the button issue and refine the texts.

Also, many thanks for mirroring issue from twitter here on GH.

**Comment by Ein-Tim** [comment]
Thanks @dsarkar & @svengabr!
