### ISSUE TITLE
Is it intended that below the button "CSV Datei laden" the button "Datei auswählen" is shown, which does exactly the same as "CSV Datei laden"?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1705]
## Your Question

When building the website locally and navigating to the QR-Code generator page (`eventregistration`) the page is shown like this:

<img width="1438" alt="Bildschirmfoto 2021-09-05 um 15 50 52" src="https://user-images.githubusercontent.com/67682506/132129680-9aa594e8-bdc1-432f-a399-55f2549eeb87.png">

Only the button "Ihre CSV Datei hochladen" (currently "CSV Datei laden") is shown. 

On the prod. website https://www.coronawarn.app/de/eventregistration/, however, the page is shown like this:

<img width="1438" alt="Bildschirmfoto 2021-09-05 um 15 50 59" src="https://user-images.githubusercontent.com/67682506/132129744-05a52e10-b2a7-42d3-b307-05f210cf07a4.png">

There is an additional button "Datei auswählen" which does exactly the same as the "CSV Datei laden" button above. Is this intended? It seems unnecessary to me.

## Additional information
I tested if this is browser specific, but it seems like it isn't. The button is shown under Edge (Chromium) as well as under Safari.

**Comment by dsarkar** [comment]
@Ein-Tim No, this button should not be there. We revert this PR for the moment. https://github.com/corona-warn-app/cwa-website/pull/1706#pullrequestreview-747013803

**Comment by dsarkar** [comment]
@Ein-Tim Fix is provided by @svengabr in https://github.com/corona-warn-app/cwa-website/pull/1709

**Comment by Ein-Tim** [comment]
@dsarkar Agreed.
