### ISSUE TITLE
Expired certificate in Check Validity screenshots

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1708]
### Sections

**"Check certificates for validity before a trip"**

- https://www.coronawarn.app/en/screenshots/#ios_check_validity_certificate
- https://www.coronawarn.app/en/screenshots/#android_check_validity_certificate

**"Zertifikate vor einer Reise auf Gültigkeit prüfen"**

- https://www.coronawarn.app/de/screenshots/#ios_check_validity_certificate
- https://www.coronawarn.app/de/screenshots/#android_check_validity_certificate

### Image files

- https://www.coronawarn.app/assets/screenshots/2-9/en/ios/iPhone%2011%20Pro-screenshot_first_vaccination_certificate_details_part1.png
- https://www.coronawarn.app/assets/screenshots/2-9/de/ios/iPhone%2011%20Pro-screenshot_first_vaccination_certificate_details_part1.png

![iPhone 11 Pro-screenshot_first_vaccination_certificate_details_part1](https://user-images.githubusercontent.com/66998419/132237088-b0f966d6-d795-447b-b100-7677c2ba04d3.png)

## Describe the issue

The section **"Check certificates for validity before a trip"** starts with a screenshot of an expired certificate. It makes no sense to check the validity of an expired certificate against the Business Rules of a EU country. If the certificate has expired then it is invalid and the other screenshots in the series cannot sensibly follow on from the first screenshot with an expired certificate.

![image](https://user-images.githubusercontent.com/66998419/132237611-a579a4ce-ff01-4a4e-b69a-6c3cc6bfcd3c.png)

This issue is also related to the missing Android screenshots described in https://github.com/corona-warn-app/cwa-website/issues/1549 where iOS screenshots are being used in the Android section.

The same screenshot for CWA 2.7 was not showing expired. See https://www.coronawarn.app/assets/screenshots/2-7/en/ios/iPhone%2011%20Pro-screenshot_first_vaccination_certificate_details_part1.png.

## Steps to reproduce

1. In CWA Android 2.6.1 scan the vaccination certificate from https://www.coronawarn.app/assets/screenshots/2-8/en/ios/iPhone%2011%20Pro-screenshot_vaccination_certificate_overview_part1.png 
2. Update CWA to current version (2.8.0 or higher)
3. View the certificate details where the Technical Expiration Date is shown as 28.05.21 11:10 AM i.e. a date in the past.

## Suggested change

The screenshots should be replaced by ones (EN and DE) showing a non-expired certificate.

**Comment by Ein-Tim** [comment]
@MikeMcC399

> If the certificate has expired then it is invalid and the other screenshots in the series cannot sensibly follow on from the first screenshot with an expired certificate.

Actually, it's possible to check for validity if the certificate has expired or is invalid, but, as you mention, it doesn't make much sense to do this.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Actually, it's possible to check for validity if the certificate has expired or is invalid, but, as you mention, it doesn't make much sense to do this.

That is true. If you scan the expired vaccination certificate from https://www.coronawarn.app/assets/screenshots/2-8/en/ios/iPhone%2011%20Pro-screenshot_vaccination_certificate_overview_part1.png with CWA 2.6.1, then use the "CHECK VALIDITY" function choosing Country: Germany, then the result is the following.

![Screenshot_20210906-190319_Corona-Warn](https://user-images.githubusercontent.com/66998419/132247596-52140fb3-e92c-4c0f-bfb6-14217d17abcb.jpg)

It is not a normal use case to check validity on an expired certificate and that is part of the reason I call this not sensible.

---
I've opened also https://github.com/corona-warn-app/cwa-app-android/issues/4018 for implausible screenshot expiration dates in Android. 

The same also applies to iOS, so it might be worth opening a separate iOS issue about this. The dummy data for screenshots is not shared between iOS and Android, so I didn't report this in the cwa-documentation repository. The resolution needs to be handled separately. As you know, I don't have an iOS device, so I don't want to submit any iOS issue report.

**Comment by MikeMcC399** [comment]
The issue that the left-hand screenshot in [Check Certificates for Validity Before a Trip](https://www.coronawarn.app/en/screenshots/#ios_check_validity_certificate) was showing an expired certificate is fixed for screenshots from CWA 2.10. The certificate is no longer expired and it has a blue background.

See for instance https://www.coronawarn.app/en/screenshots/#ios_check_validity_certificate containing screenshot https://www.coronawarn.app/assets/screenshots/2-10/en/ios/iPhone%2011%20Pro-screenshot_vaccination_certificate_valid_details_part3.png.

![image](https://user-images.githubusercontent.com/66998419/134776549-4d04be53-3f48-4718-b1f3-dbd8ac020a3c.png)

- The screenshots for earlier versions 2.9 and 2.8 are not corrected. They are archived in the state they were published.

- The screenshots for versions 2.7 and 2.6 did not show the problem.

- Versions 2.5 and earlier did not show the section [Check Certificates for Validity Before a Trip](https://www.coronawarn.app/en/screenshots/#ios_check_validity_certificate).

- The issue that [Check Certificates for Validity Before a Trip - Android](https://www.coronawarn.app/en/screenshots/#android_check_validity_certificate) are using iOS screenshots in place of Android ones, tracked in https://github.com/corona-warn-app/cwa-website/issues/1549, is still open at this time.
