### ISSUE TITLE
Screenshots: Valid certificates in 'Invalid certificates' section (Android)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1710]
## Where to find the issue

Screenshots https://www.coronawarn.app/en/screenshots/
Android Section **Invalid certificates** / **Ungültige Zertifikate** of the published app version 2.8 and of the PR https://github.com/corona-warn-app/cwa-website/pull/1707 for the planned version 2.9 release.

## Describe the issues

For the Android **Invalid certificates** / **Ungültige Zertifikate** 

- https://www.coronawarn.app/en/screenshots/#android_invalid_certificate
- https://www.coronawarn.app/de/screenshots/#android_invalid_certificate

1. The screenshots shown in the Android section are iOS screenshots, not Android screenshots.
2. The two right-hand screenshots are valid, not invalid. This is a regression from the screenshots published for version 2.7 which were correctly invalid certificates.

![Invalid certificates](https://user-images.githubusercontent.com/66998419/132305001-8207ddf3-7207-45ec-9e15-e640364d2562.png)

## Suggested change

- Capture and publish Android screenshots in the Android section
- If not possible to get Android screenshots, then use the same screenshots in the Android section as used in the iOS section:
    - `en/ios/iPhone%2011%20Pro-screenshot_recovery_certificate_expired_details_part1.png`
    - `en/ios/iPhone%2011%20Pro-screenshot_recovery_certificate_expired_details_part2.png`
    - `de/ios/iPhone%2011%20Pro-screenshot_recovery_certificate_expired_details_part1.png`
    - `de/ios/iPhone%2011%20Pro-screenshot_recovery_certificate_expired_details_part2.png`

---
Internal Tracking ID: [EXPOSUREAPP-8884](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8884)

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/1711 opened to address the issue in for CWA 2.8.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks a lot!

**Comment by MikeMcC399** [comment]
Issue in PR https://github.com/corona-warn-app/cwa-website/pull/1707 is resolved by commit https://github.com/corona-warn-app/cwa-website/pull/1707/commits/610ebd230e5a9c7cc8d8f6f183c0af2257ea6ad5 in that PR.

**Comment by MikeMcC399** [comment]
Since both the 2.8 and future 2.9 screenshots are now corrected, this issue can be closed.
