### ISSUE TITLE
Update FAQs - Sofortige Impfstatusanzeige für Genesene

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#1713]
**UPDATE** the following articles:

https://www.coronawarn.app/de/faq/#eu_dcc_validity
https://www.coronawarn.app/de/faq/#rec_cert
https://www.coronawarn.app/de/faq/#vac_cert_what
https://www.coronawarn.app/de/faq/#vac_cert_privileges_travel 
 
Content to be added at appropriate position:

"Sofortige Impfstatusanzeige für Genesene: Für Genesene wird ab der Version 2.9 direkt nach der ersten Impfung der vollständigeImpfschutz in der Corona-Warn-App angezeigt. Die zweiwöchige Wartezeitentfällt bei allen Impfstoffen außer bei Johnson & Johnson." 

---
Internal Tracking ID: [EXPOSUREAPP-9182](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9182)

**Comment by MikeMcC399** [comment]
@dsarkar 
There were some spaces missing in the original text. It should look like this:

"Sofortige Impfstatusanzeige für Genesene: Für Genesene wird ab der Version 2.9 direkt nach der ersten Impfung der vollständige Impfschutz in der Corona-Warn-App angezeigt. Die zweiwöchige Wartezeit entfällt bei allen Impfstoffen außer bei Johnson & Johnson."
