### ISSUE TITLE
Screenshots for previous 2.8 version no longer accessible

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1722]
## Where to find the issue

- https://www.coronawarn.app/en/screenshots-archive/2-8.html
- https://www.coronawarn.app/de/screenshots-archive/2-8.html

## Describe the issue

When selecting screenshot version 2.8, only the text about the version is shown, not the screenshots themselves

### Steps to reproduce

1. Open https://www.coronawarn.app/en/screenshots/
2. Select 2.8 in Versions drop-down menu
3. Note that no images are shown

**Comment by dsarkar** [comment]
@MikeMcC399  thanks for reporting

**Comment by dsarkar** [comment]
@MikeMcC399 FYI https://github.com/corona-warn-app/cwa-website/pull/1723

**Comment by MikeMcC399** [comment]
Closing. Fixed with PR #1723.
