### ISSUE TITLE
Missing json file settings for Visual Studio Code editor

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1724]
## Where to find the issue

https://github.com/corona-warn-app/cwa-website/blob/master/.vscode/settings.json

## Describe the issue

The [Visual Studio Code project settings file](https://github.com/corona-warn-app/cwa-website/blob/master/.vscode/settings.json) does not provide any default settings for `json` files.

[CHANGE_WEBSITE_CONTENT.md](https://github.com/corona-warn-app/cwa-website/blob/master/docs/CHANGE_WEBSITE_CONTENT.md) says:

* JSON files use 4 space-character soft-tab indentation
* Use a proper JSON formatter after making your changes (e.g. the format document option of VSCode) from time to time 

and it leaves it to contributors to set up the corresponding settings.

## Suggested change

Modify the [Visual Studio Code project settings file](https://github.com/corona-warn-app/cwa-website/blob/master/.vscode/settings.json) to include settings which implement the 4 space-character soft-tab indentation.

Insert the following into [.vscode/settings.json](https://github.com/corona-warn-app/cwa-website/blob/master/.vscode/settings.json)

```
"[json]": {
  "editor.detectIndentation": false,
  "editor.tabSize": 4,
  "editor.insertSpaces": true
}
```

which will modify the Workspace Settings for editing json files in the [corona-warn-app/cwa-website](https://github.com/corona-warn-app/cwa-website) repository with a Visual Studio Code editor.

Possibly
`"editor.trimAutoWhitespace": true`
should also be added, although this has not been specified as a convention for json files in the repository.

Similarly
`"files.insertFinalNewline": true`
could also be defined. Again this has not been specified as a repository convention so far.

## Visual Studio Code - Reference information

 [User and Workspace Settings](https://code.visualstudio.com/docs/getstarted/settings)

[Keybindings](https://code.visualstudio.com/docs/getstarted/keybindings) for different operating systems, for example: Windows `Shift+Alt+F` = Format document.

**Comment by MikeMcC399** [comment]
I will wait for comment on this suggestion and then submit a corresponding PR if there is interest and agreement.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I would definitely appreciate this setting, as I use VS Code as my main editor (: 
Thanks for taking care!

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for your positive feedback!

This is what I would propose for https://github.com/corona-warn-app/cwa-website/blob/master/.vscode/settings.json if the Open Source Team would like this added.

```
{
  "[html]": {
    "editor.formatOnSave": false
  },
  "[json]": {
    "editor.detectIndentation": false,
    "editor.tabSize": 4,
    "editor.insertSpaces": true,
    "editor.trimAutoWhitespace": true,
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true
  }
}
```

**Comment by MikeMcC399** [comment]
I have created PR #1726 to implement this suggestion.

**Comment by MikeMcC399** [comment]
#1726 is merged, so this issue can now be closed.
