### ISSUE TITLE
`personal_data` FAQ entry is outdated

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1729]
## Where to find the issue

DE: https://www.coronawarn.app/de/faq/#personal_data

EN: https://www.coronawarn.app/en/faq/#personal_data

says:

DE:
"Wie in der Datenschutz-Grundverordnung (DSGVO) vorgeschrieben, ist die Datenminimierung das oberste Gebot für die Umsetzung der App. Die nutzenden Personen **können** und müssen in Verbindung mit der App ausschließlich die folgenden Angaben machen: [...]"

EN:
"As mandated by the General Data Protection Regulation (GDPR), data minimization is a paramount principle in the implementation of the app. The only inputs that users **can** and have to provide to the app are: [...]"

## Describe the issue

The "can" ("können") is not true anymore, the user can create a rapid test profile, enter their dob for accessing PCR COVID test certificates, etc. 

## Suggested change
Remove "can" ("können"). I'll provide a PR for this.

---
Internal Tracking ID: [EXPOSUREAPP-12410](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12410)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The app has become much more complicated and extensive since his article was written.

It might be better to remove the very basic examples of data input and instead refer to the official documents:
- https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf
- https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, agreed! However, I'd like to get feedback from the Open-Source Team on this before creating a PR.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

This issue has not been addressed and the FAQ contents are quite out of date and misleading.

![image](https://user-images.githubusercontent.com/66998419/141505414-08de02b6-35ae-426a-9a3a-e5c918d0e30f.png)

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, I agree. However, I still would like to wait for feedback from the Open-Source-Team on what their preferred solution for this is.

**Comment by ahodzic2** [comment]
Hello,

Any update with this item since November? Looking to get involved and this looks like it might be a good entry point :)

**Comment by Ein-Tim** [comment]
@ahodzic2 

This issue remains unfixed, however, the Open-Source-Team (e.g. @dsarkar or @larswmh) did not respond to this issue as I wished. If they respond and clarify how their plan to proceed is, you can certainly provide a PR!

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 @ahodzic2 
Snowed under ... 
I think @MikeMcC399's suggestion https://github.com/corona-warn-app/cwa-website/issues/1729#issuecomment-917408467 is the way to go. @ahodzic2 if you would like to provide a corresponding PR, please, go ahead, will be appreciated very much. Thanks.

**Comment by MikeMcC399** [comment]
@ahodzic2 
> Looking to get involved and this looks like it might be a good entry point :)

Please respond about whether you will provide a PR for this. It's no problem if you don't. We just need to know.

**Comment by ahodzic2** [comment]
@MikeMcC399 @dsarkar Yes, I can provide a PR! I'll get to work on that.

**Comment by ahodzic2** [comment]
@dsarkar @MikeMcC399 @Ein-Tim 
I have updated this particular FAQ section to include the brief note about data minimization and then a link to the privacy policy. The English site leads to the English pdf and the German site leads to the German PDF. Any objections with the wording? Please let me know if the German needs to be updated as well. My German is a bit rusty :)

![image](https://user-images.githubusercontent.com/72961430/159614736-c4ee6569-b920-4ac3-ad05-68ae46b6bcbb.png)

![image](https://user-images.githubusercontent.com/72961430/159617215-beb73bb7-709c-4ee6-81be-c51b46191b6e.png)

**Comment by MikeMcC399** [comment]
@ahodzic2 
This looks fine to me. 👍🏻

**Comment by dsarkar** [comment]
@ahodzic2 Thanks for your suggestion. We clarified, the wording is fine. Please, we would appreciate a PR **after** going live with the new FAQ website (today).

**Comment by ahodzic2** [comment]
Pull request #2566 has been created for these changes. @dsarkar

**Comment by Ein-Tim** [comment]
Closing this issue as fixed with PR #2587. 

Thanks to @ahodzic2 for providing the PR!
