### ISSUE TITLE
Capitalization of screenshot titles in English

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1740]
## Where to find the issue

https://www.coronawarn.app/en/screenshots/
with source code
https://github.com/corona-warn-app/cwa-website/blob/master/src/data/screenshots.json

## Describe the issue

Screenshot section titles in English are not consistently capitalized.

Whereas some section titles like:

- "Risk Cards"
 
correctly use title case, others, including the following, do not use title case:
- "Test registration & Key sharing"
- "Warn for others"
- "Rapid antigen test"
- "Check certificates for validity before a trip"
- "Invalid certificates"
- "Check In - Scan QR code"
- "Check In - Create QR code"
- "Test result home"

## Suggested change

There are different conventions about how to capitalize headings in English. https://en.wikipedia.org/wiki/Title_case describes _title case_.

Using AP style (see https://capitalizemytitle.com/style/AP/).

- "Test registration & Key sharing" => "Test Registration & Key Sharing"
- "Warn for others" => "Warn for Others"
- "Rapid antigen test" => "Rapid Antigen Test"
- "Check certificates for validity before a trip" => “Check Certificates for Validity Before a Trip”
- "Invalid certificates" => "Invalid Certificates"
- "Check In - Scan QR code" => "Check In - Scan QR Code"
- "Check In - Create QR code" => "Check In - Create QR Code"
- "Test result home" => "Test Result Home"

I suggest to change the section headings in PR https://github.com/corona-warn-app/cwa-website/pull/1737 for release 2.10 from @larswmh first, then retro fit to previous versions.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> I suggest to change the section headings in PR #1737 for release 2.10 from @larswmh first, then retro fit to previous versions.

Agreed, but I suggest not to retro fit this change to previous versions, to not break the convention in https://github.com/corona-warn-app/cwa-website/issues/1660#issuecomment-909960309. 
Or do you think an exception should be made here?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> ... I suggest not to retro fit this change to previous versions, to not break the convention in [#1660 (comment)](https://github.com/corona-warn-app/cwa-website/issues/1660#issuecomment-909960309).
Or do you think an exception should be made here?

I would interpret the statement to mean that screenshots for previous versions will not be changed. I'm happy to submit a PR to change the text headings for previous versions including 2.9, if we get agreement for the 2.10 submission.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Mh, we would need a definition of "content changes", but as I asked in the OP of https://github.com/corona-warn-app/cwa-website/issues/1660 explicitly also for the alt texts, I think the texts are also covered by this statement.

However, if you would provide a PR for this, I'm fine with that, for sure (:

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim I think this proposal is ok, however, let's wait for more opinions.

**Comment by GisoSchroederSAP** [comment]
Thanks for pointing out the inconsistencies. Agreed to change in the AP style way. Regarding a definition of "content change" - this can be easily done: If we change the content in terms of "meaning", ist's a content change. If we just re-arrange, it's a "layout change". I would not make this a philosophical discussion here.
So, please focus on the current/most recent content - there is no need to maintain the old stuff.
Again, thanks for have an eye on the "perception" of our content.

**Comment by MikeMcC399** [comment]
Submitted PR #1742 for current screenshot headings (CWA 2.9).

**Comment by dsarkar** [comment]
PR #1742 has been merged. Thanks to everybody!
