### ISSUE TITLE
Untranslated labels in some Science Blog 2 tables

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1751]
## Where to find the issue

https://www.coronawarn.app/en/science/2021-07-08-science-blog-2/

## Describe the issue

In the English language version of the Science Blog 2
https://www.coronawarn.app/en/science/2021-07-08-science-blog-2/
"Who are the people using the Corona-Warn-App?"

there are some remaining table labels which are in German although the rest of the article is in English.

- "Fig. 14: EDUS - relationship between educational level and contact in the professional context."<br>"An n - m Tagen pro Woche"

- "Fig. 15: EDUS - relationship between known contacts and infections."<br>"Testergebnis"

## Suggested change

Translate the German labels into English.

**Comment by dsarkar** [comment]
PR #1754 merged.

**Comment by MikeMcC399** [comment]
Resolved by PR #1754.
