### ISSUE TITLE
Screenshots: Android Check-In screenshots out-of-date

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1760]
## Where to find the issue

- https://www.coronawarn.app/en/screenshots/#android_screenshots
    - https://www.coronawarn.app/en/screenshots/#android_check_in
- https://www.coronawarn.app/de/screenshots/#android_screenshots
    - https://www.coronawarn.app/de/screenshots/#android_check_in

## Describe the issue

Note: This issue was logged for CWA Android 2.11 and the issue is not fixed for 2.23.

The Android screenshots in the [Check In](https://www.coronawarn.app/en/screenshots/#android_check_in) section for the 2.11 release are not taken from the 2.11 version.

The category tabs in the screenshots show only:
- Start Screen
- Check In
- Journal

The tab
- Certificates

which was introduced in the [CWA 2.4 release](https://www.coronawarn.app/en/blog/2021-06-24-cwa-version-2-4/), is not shown. See blog post [Digital vaccination certificate now in the Corona-Warn-App's certificates section](https://www.coronawarn.app/en/blog/2021-06-30-cwa-impfnachweis-zertifikatsbereich/) from June 30, 2021.

## Suggested change

1. Capture up-to-date screenshots for Android CWA 2.11 for the section [Check In - EN](https://www.coronawarn.app/en/screenshots/#android_check_in) and [Check In - DE](https://www.coronawarn.app/de/screenshots/#android_check_in). 
2. Publish them to the website.

---
Internal Tracking ID: [EXPOSUREAPP-13554](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13554)

**Comment by MikeMcC399** [comment]
The Check In screenshots for 2.16 are outdated.

**Comment by Ein-Tim** [comment]
There are multiple places in the screenshots page where the screenshots displayed are out of date. I just checked, the Check-In screenshots are still out of date.

I wonder what the process is: Are all screenshots retaken on the latest version or are only screenshots of views taken which changed?
