### ISSUE TITLE
FAQ is missing on information that the app data is not included in a back-up

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1766]
## Where to find the issue
https://www.coronawarn.app/de/faq/
https://www.coronawarn.app/en/faq/

## Describe the issue
There is no FAQ entry informing the user that they neither their DCCs nor their contact journal entries are included in a backup.

## Suggested change
Either adjust https://www.coronawarn.app/en/faq/#backup or create a new FAQ entry.

## Additional information
I can provide a PR for this, I'd modify https://www.coronawarn.app/en/faq/#backup so that the title is "Is the data of the Corona-Warn-App included in a backup?" and answer this question with no.
Then I'd write what the workarounds are (export DCCs before switching the device and export contact journal).

**Comment by MikeMcC399** [comment]
@Ein-Tim 

On Android the operating system backup of data from CWA is disabled:
`android:allowBackup="false"`
see https://github.com/corona-warn-app/cwa-app-android/blob/9d6525b7f7f849bb52f11a31916707ab60a33759/Corona-Warn-App/src/main/AndroidManifest.xml#L30
so you are right when you say there is no backup done.

There is already an open issue from @dsarkar regarding backup. See https://github.com/corona-warn-app/cwa-website/issues/1319, so you might consider adding your comments to the existing issue.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks for confirming that under Android also no data from CWA is backed up. 

Also thanks for reminding me of #1319, I will add my comments there and close this issue, as it seems to be very closely related to #1319.

Have a nice Saturday!
