### ISSUE TITLE
Analyse shows only "Loading..."

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1775]
## Where to find the issue

https://www.coronawarn.app/en/analyse/

## Describe the issue

No graphs are displayed, only the text "Loading ..."

![image](https://user-images.githubusercontent.com/66998419/135259020-e49a56c3-2f5f-4268-a6dc-40c4348e18b8.png)

**Comment by Ein-Tim** [comment]
Confirum this issue, happened locally yesterday evening too.

**Comment by MikeMcC399** [comment]
Strangely it is working for me if I run the website locally (`npm start`).

It is not working for me on the production site https://www.coronawarn.app/en/analyse/

I tried from a desktop with Chrome and Mozilla, also from a mobile device with Chrome, same issue - only "Loading...", no results shown.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Could you close your browser and navigate to the local instance again? It worked for me the first time and then, the second time it didn't work anymore.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim  We are on it.

**Comment by Ein-Tim** [comment]
Analysis page has been reverted: https://github.com/corona-warn-app/cwa-website/pull/1774

**Comment by MikeMcC399** [comment]
https://www.coronawarn.app/en/analyse/ is still available. The revert did not cause a delete to deploy to the production server. 

https://www.coronawarn.app/en/analyse/ no longer shows "Loading..." though. It is just a incomplete web page now with no graphs and a lot of text.

I will leave this open for the time-being even though the original problem no longer occurs.

**Comment by MikeMcC399** [comment]
https://www.coronawarn.app/en/analyse/ no longer shows an incomplete page.

It may however be superfluous, which is covered by a new issue https://github.com/corona-warn-app/cwa-website/issues/1792.

Closing this issue, since this point is resolved.

Also the new page https://www.coronawarn.app/en/analysis/ and https://www.coronawarn.app/de/analysis/ are working too.
