### ISSUE TITLE
Name for analysis page is verb not noun

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1776]
## Where to find the issue

https://www.coronawarn.app/

## Describe the issue

All other headings on the website https://www.coronawarn.app/ are English language nouns.

The heading "Analyse" could be an English language verb or it could be a German language noun.

![image](https://user-images.githubusercontent.com/66998419/135259802-e5da080b-1deb-4d68-a4c8-4e2262f0ee48.png)

## Suggested change

Change the heading from "Analyse" to "Analysis" to make it an English language noun, like the other headings.

(If it was supposed to be an English verb, then "Analyze" would conform to the rest of the website which uses US English, not UK English spelling.)

## References
https://dictionary.cambridge.org/dictionary/english/analyse
https://dictionary.cambridge.org/dictionary/english/analysis

---
Internal Tracking ID: [EXPOSUREAPP-9698](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9698)

**Comment by dsarkar** [comment]
@FabioFuschi-SNK FYI

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/1777 removes "Analyse" from the menu on https://www.coronawarn.app/en/, however if anybody already bookmarked

https://www.coronawarn.app/en/analyse/ or
https://www.coronawarn.app/de/analyse/

the menu bar still shows "Analyse", as before. 

Also, under

https://www.coronawarn.app/en/analysis and
https://www.coronawarn.app/de/analysis/

the heading of the page is still "Analyse".  I'm not sure that that heading is needed, directly above the text "Corona-Warn-App (CWA): Kennzahlen". If it is needed there, then consider whether it should be changed to "Analysis" there as well.

**Comment by Ein-Tim** [comment]
FYI: https://github.com/corona-warn-app/cwa-website/pull/1774 has removed the analysis page from the website again.

**Comment by MikeMcC399** [comment]
Assuming that the analysis page will be published again, leaving this issue open.

**Comment by MikeMcC399** [comment]
@dsarkar / @FabioFuschi-SNK / @mtb77 

PR https://github.com/corona-warn-app/cwa-website/pull/1793 has added the navigation name "Analyse" back.

Originally it was "Analyse", then it was changed to "Analysis", now it is "Analyse" again,

Is that what you want it to be?

This issue pointed out the inconsistency of using a verb in that place when everything else in the menu is a noun.

**Comment by mtb77** [comment]
Commented it in #1793

**Comment by MikeMcC399** [comment]
@mtb77 
> Commented it in #1793

Thanks! I will leave this issue open until the naming is resolved.

**Comment by dsarkar** [comment]
@MikeMcC399 @mtb77 @FabioFuschi-SNK FYI PR https://github.com/corona-warn-app/cwa-website/pull/1800

**Comment by MikeMcC399** [comment]
The name has been changed to "Analysis" in PR #1800 which resolves this issue, so now closing.

Thanks very much to @dsarkar ! 👍🏻

**Comment by Ein-Tim** [comment]
I disagree with the decision to name the page "Analysis" in German.

Analysis in German has a different meaning, see https://www.duden.de/rechtschreibung/Analysis.

It makes no sense to use a word which is out of context just for consistency, IHMO. 

I opened #2331 to change "Analysis" to "Analyse".

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> I disagree with the decision to name the page "Analysis" in German.

I understand your point about the discrepancy between the menu item "Analysis" and the page topic text "Analyse" on https://www.coronawarn.app/de/analysis/. I already noted in https://github.com/corona-warn-app/cwa-website/issues/1776#issuecomment-930283228 that I didn't think the page header was needed and I think in fact it would be much better if it were removed, which would need some reformatting of the page.

Since this is really a new (although related) topic could you please open a new issue for this point?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I will see how my PR #2331 is handled and then open an issue if necessary.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
- I had a new idea, so I opened issue https://github.com/corona-warn-app/cwa-website/issues/2352.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

And I like the idea very much, this is the way I'd go!
