### ISSUE TITLE
Broken links in production due to Analyse merge

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1778]
## Where to find the issue

https://www.coronawarn.app

## Describe the issue

There are multiple **404 errors** on the website https://www.coronawarn.app accessing the website's own internal resources.

For example:

Keep background updates switched on and check them regularly
https://www.coronawarn.app/faq/#background_updates

Frequently Asked Questions about the Corona-Warn-App.
https://www.coronawarn.app/faq/

Read the Blog
https://www.coronawarn.app/blog/2021-09-24-facts-and-figures

Although the website shows a 404 error, a browser registers a 403 error (forbidden).  In any case the corresponding links are broken.

## Suggested change

Either revert PR https://github.com/corona-warn-app/cwa-website/pull/1772 or find a way to check all links on the production site to find out if they are broken or not (and then fix them if necessary).

**Comment by Ein-Tim** [comment]
Could anyone please give a reason why the analysis page PR caused so many unrelated changes, especially to links? 

Where is the improvement over the implementation as it was before?

**Comment by MikeMcC399** [comment]
Also on 

https://www.coronawarn.app/en/blog/
Show news archive
https://www.coronawarn.app/archive

broken (404 error)

**Comment by Ein-Tim** [comment]
The analysis page has been reverted: https://github.com/corona-warn-app/cwa-website/pull/1774

Can you check again @MikeMcC399?

**Comment by MikeMcC399** [comment]
Closed due to PR #1774.
