### ISSUE TITLE
Dead external links to 10C formula in FAQs

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1780]
## Where to find the issue

- https://www.coronawarn.app/en/faq/#qr_scan
- https://www.coronawarn.app/de/faq/#qr_scan

## Describe the issue

https://www.kbv.de/media/sp/Ansichtsexemplar_Muster10C.pdf is a dead link included in the FAQ articles:

    - https://www.coronawarn.app/en/faq/#qr_scan
    - https://www.coronawarn.app/de/faq/#qr_scan

## Suggested change

Find current 10C document and either link it or copy it.

**Comment by MikeMcC399** [comment]
I found resources on https://update.kbv.de/ita-update/Blankoformulare/10C_OEGD/ however I could not find any exact replacement for the missing https://www.kbv.de/media/sp/Ansichtsexemplar_Muster10C.pdf file.

The form changes regularly in accordance with changes in the law about testing, especially concerning the checkboxes, so it's probably not a good idea to get a static copy of the form because that may easily become out of date.

Perhaps the Open Source Team could ask KBV officially for help?

**Comment by GisoSchroederSAP** [comment]
We'll do, Mike. Thanks for pointing out the missing resource.

**Comment by GisoSchroederSAP** [comment]
I just talked to the KBV headquarter. We'll receive the latest samples for form 10C and OEGD shortly to present those on our FAQ. 
IT department reorganised the data pool and removed those (and other links).
Currently, there are no plans to update/change these forms.  But if so, we can call again to retrieve these updates manually.

**Comment by dsarkar** [comment]
@MikeMcC399 FYI PR https://github.com/corona-warn-app/cwa-website/pull/1799
