### ISSUE TITLE
Add link checking to https://www.coronawarn.app

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1781]
## Feature description

For website https://www.coronawarn.app add link checking to site tools.

This follows on from the question https://github.com/corona-warn-app/cwa-website/issues/889.

Consider integrating link checking into the checks done in workflows:

- https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml and
- https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/deploy-master.yml

Also, consider regularly monitoring https://www.coronawarn.app in order to catch changing and dead external links.

## Problem and motivation

1. There is no check done when changes are made to the website https://www.coronawarn.app which might ensure that existing (internal) links are not broken. For example see issue https://github.com/corona-warn-app/cwa-website/issues/1778.
2. If external links change, there is no check done to ensure that the links on the website https://www.coronawarn.app/en/ continue to work. For instance there are currently at least two dead external links (see  https://github.com/corona-warn-app/cwa-website/issues/1779 and https://github.com/corona-warn-app/cwa-website/issues/1780) on the website.

## Is this something you're interested in working on

Unfortunately I don't have the experience to implement this.

---
Internal Tracking ID: [EXPOSUREAPP-9734](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9734)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. We will look into this. Internal Tracking ID: [EXPOSUREAPP-9734](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9734)

**Comment by MikeMcC399** [comment]
https://www.deadlinkchecker.com gives some false positives for e-mail obfuscation and links with umlauts in them, but it does also find some dead links on https://www.coronawarn.app/en/ which in some cases have been there for quite a while.

For instance https://www.coronawarn.app/de/blog/2021-05-12-corona-warn-app-version-2-2/, which is four months old, includes a link 

`<a href="+493049875401">+49 30 498 75401</a>` which resolves to the bad URL

`https://www.coronawarn.app/de/blog/2021-05-12-corona-warn-app-version-2-2/+493049875401`

that is probably intended to be 

`<a href="tel:+493049875401">+49 30 498 75401</a>`

as used in the English language version of the page on https://www.coronawarn.app/en/blog/2021-05-12-corona-warn-app-version-2-2/

 `"tel:"` is simply missing in the German language source https://github.com/corona-warn-app/cwa-website/blob/master/blog/2021-05-12-cwa-2-2/index_de.md in line 41.

**Comment by dsarkar** [comment]
@MikeMcC399  FYI https://github.com/corona-warn-app/cwa-website/pull/1786

**Comment by MikeMcC399** [comment]
Thanks to @dsarkar and @mtb77 for implementing the link check in cypress! 🚀 

The test does not yet run error free and this should be covered in separate issues.

Closing this request now, since the request has been implemented and it is now just a case of fixing some bad links and ensuring that the script errors really only occur when there is an actual error. This is just a small and manageable number of error lines at this time.
