### ISSUE TITLE
Question on the data shown on the analysis page

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1795]
## Your Question
* Website URL Path: https://www.coronawarn.app/de/analysis/
* Line / Paragraph: "Warnungen"
* Question: Where does the data for the "Warnungen" come from? The data donation?
Because https://www.coronawarn.app/assets/documents/2021-09-30-cwa-daten-fakten.pdf says: 
"Es gibt keine Daten dazu, wie viele Menschen mit Hilfe der Corona- Warn-App über eine mögliche Risiko-Begegnung informiert wurden, da die App auf einem dezentralen Ansatz basiert.

Alle Daten der Nutzerinnen und Nutzer werden verschlüsselt und ausschließlich auf dem eigenen Smartphone gespeichert. Weder das Robert Koch-Institut als Herausgeber noch Dritte haben Zugriff auf diese Daten."

This is obviously not true, since on https://www.coronawarn.app/de/analysis/ one can even see how many low risk and how many increased risk warnings were "issued".

**Comment by Ein-Tim** [comment]
After switching to "Gesamter Zeitraum" and looking at the "Warnungen" graph again, I'm pretty sure that the data comes from the PPA (it starts in March when the data donation was first included into the apps).
It would still be good to get an official answer on this and I think this would be worth a short notice on the page, maybe under the "i" of the "Warnungen" card?

**Comment by HelTob** [comment]
Hello Tim, this is Tobias from the CWA Team. 
Yes, you're totally right, the data comes from the Privacy Preserving Analytics (PPA). 
In the near future we will add some information about the sources of the data in the graphs. 

Thanks for your contribution, keep it up!

Best regards,
Tobias

**Comment by Ein-Tim** [comment]
Hey @HelTob 👋

Thanks for your answer and thank you for the information that the sources can be seen on the page soon! 

I'm looking forward for a great cooperation with you! Thank you for working at the Corona-Warn-App / RKI! 

Have a nice evening!

---

Closing as answered.
