### ISSUE TITLE
`vac_cert_voluntary` needs update (Berlin requires digital certificate)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1805]
## Where to find the issue
- https://www.coronawarn.app/de/faq/#vac_cert_voluntary
- https://www.coronawarn.app/en/faq/#vac_cert_voluntary

## Describe the issue
The FAQ entry https://www.coronawarn.app/en/faq/#vac_cert_voluntary states that the yellow vaccination booklet can be used and equivalent to the EU digital vaccination certificate. However Berlin is now requiring a digital proof of vaccination and not the yellow vaccination booklet. See https://www.berlin.de/corona/massnahmen/verordnung/ §8a Absatz 2 Ziffer 4.

## Suggested change
Add a note or similar reg. the "special" case Berlin.

---
Internal Tracking ID: [EXPOSUREAPP-9779](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9779)

**Comment by dsarkar** [comment]
![image](https://user-images.githubusercontent.com/1409741/135838880-efd36ae0-791f-404a-a6e9-9f3d7cabeab1.png)

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399  Thanks. Suggestion to update https://www.coronawarn.app/de/faq/#vac_cert_voluntary

(bold => new text/changes)

Bin ich verpflichtet, den digitale Impfnachweis in der Corona-Warn-App zu nutzen? Wird es trotzdem noch den gelben analogen Impfausweis geben? Kann ich meinen gelben Impfausweis auch weiterhin benutzen? Was ist mit Personen, die kein Smartphone besitzen?


**Im Allgemeinen ist** der digitale Impfnachweis (**beziehungsweise digitale Test- oder Genesenennachweis**) per Corona-Warn-App lediglich ein vollkommen freiwilliges und ergänzendes Angebot. Wenn Sie keinen digitalen Impfnachweis besitzen oder diesen verloren haben, ist der Impfnachweis über das bekannte „gelbe Heft“ (gelber Impfausweis) **in der Regel** weiterhin möglich und gültig. Außerdem können Sie Corona-Impfungen auch mit dem ausgedruckten Corona-Impfzertifikat für die vollständige Impfung nachweisen.

**Wichtig: Prüfen Sie bitte die lokalen Verordnungen der Bundesländer. Berlin beispielsweise verlangt, dass der Nachweis der Impfung gegen oder Genesung von SARS-CoV2 digital verifizierbar sein muss (Siehe https://www.berlin.de/corona/massnahmen/verordnung/ §8a Absatz 2 Ziffer 4.). Das heißt, dass Sie gegebenenfalls ein entsprechendes digitales Zertifikat der EU entweder in der Corona-Warn-App, der CovPass-App oder als Papierausdruck zur Überprüfung vorzulegen zu haben.**

**Comment by MikeMcC399** [comment]
@dsarkar 
"vorzulegen zu haben." => "vorzulegen haben." ?
Also, `&nbsp;` after § symbol.


Maybe also mention: ?
Digitale Zertifikate können nachträglich durch Apotheken ausgestellt werden.
