### ISSUE TITLE
App unter iOS 14.0 (18A5319i) komplett ohne Funktion

### ISSUE THREAD

**Issue by kgruenler** [corona-warn-app/cwa-website#182]
Auf meinem iPhone XS Max habe ich die Public Beta von iOS14 installiert, seitdem ist die App komplett funktionslos. Ich habe die App Version 1.0.7 installiert.
In den Einstellungen unter Datenschutz / Health / COVID-19-Kontaktprotokoll steht jetzt auch "Aus" und "In deiner Region nicht verfügbar".
Bis zum Zeitpunkt des Wechsels der iOS-Version funktionierte die App (bis auf die bekannten Fehler "13-14 Tage" usw.) einwandfrei.
Vielleicht kann mit Apple geklärt werden, dass die COVID-19-Thematik auch in der Beta für Eure App wichtig ist.

**Comment by tkowark** [comment]
Please have a look at the FAQ: https://www.coronawarn.app/de/faq/#ios_14_beta
This issue will go away once the Exposure Notification Framework is shipped/activated with iOS 14 release or one of the upcoming BETAs
