### ISSUE TITLE
Include `check_links.js` check into GitHub workflow (build and test)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1825]
## Feature description
I suggest to integrate the `check_links.js` check, which currently has to be run manually on a local instance of the website, into the build and test GitHub Action which runs for every commit in a PR:

## Problem and motivation
This feature would save work and broken links can be found more easily.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
That sounds like a good idea!

The script does need to mature a little before it becomes part of an automated process and there are some other issues right now, like https://github.com/corona-warn-app/cwa-website/issues/1824.

It there are link issues, the log file is not very helpful in finding the exact cause. You still need to run test manually to find out which link is failing.

Here is a partial log for the branch [dsarkar-release-2-11](https://github.com/corona-warn-app/cwa-website/tree/dsarkar-release-2-11)

```
  Check for broken links
    √ "/de" - Check for broken links (43763ms)
    √ "/en" - Check for broken links (25423ms)
    √ "/de/eventregistration/" - Check for broken links (3298ms)
    √ "/en/eventregistration/" - Check for broken links (2172ms)
    √ "/de/community/" - Check for broken links (3121ms)
    √ "/en/community/" - Check for broken links (2486ms)
    √ "/de/science/" - Check for broken links (3684ms)
    √ "/en/science/" - Check for broken links (3638ms)
    √ "/de/analysis/" - Check for broken links (7757ms)
    √ "/en/analysis/" - Check for broken links (7325ms)
    √ "/de/blog/" - Check for broken links (6874ms)
    √ "/en/blog/" - Check for broken links (5813ms)
    √ "/de/blog/archiv/" - Check for broken links (16579ms)
    √ "/en/blog/archive/" - Check for broken links (15686ms)
    √ "/de/screenshots/" - Check for broken links (16262ms)
    √ "/en/screenshots/" - Check for broken links (14805ms)
    √ "/de/faq/" - Check for broken links (150845ms)
    1) "/en/faq/" - Check for broken links
    √ "/de/rat-partner/" - Check for broken links (6273ms)
    √ "/en/rat-partner/" - Check for broken links (3317ms)
    √ "/de/privacy/" - Check for broken links (11289ms)
    √ "/en/privacy/" - Check for broken links (12154ms)
    √ "/de/terms-of-use/" - Check for broken links (2523ms)
    √ "/en/terms-of-use/" - Check for broken links (2613ms)
    √ "/de/event-qr-code-guide/" - Check for broken links (2076ms)
    √ "/en/event-qr-code-guide/" - Check for broken links (1945ms)


  25 passing (8m)
  1 failing

  1) Check for broken links
       "/en/faq/" - Check for broken links:
     Error: nntFailed soft assertions... check log above ↑nn
  Error: Failed soft assertions... check log above ↑
      at Context.eval (http://localhost:8000/__cypress/tests?p=cypress\support\index.js:37857:13)

```

**Comment by Ein-Tim** [comment]
@dsarkar 

Mh, okay. You're right, 10 min is quite long. 

Maybe there's a way to make it run faster, somehow? E.g. running the tests for each page via different, independent workflows which all run simultaneously? 

I still that this should be implemented, of course not if it takes 10 min, but this would be a huge improvement as failing checks here on GitHub are better visible and each and every commit is checked. There would practically be no way that a broken link slips through and makes it to the live page.

**Comment by MikeMcC399** [comment]
I found recently that the website https://ec.europa.eu/ was online but rejecting connections. That meant that the `check_links.js` Cypress script failed, since the link is used in the FAQs. There was nothing wrong in the FAQs and the website problem went away on its own 10 minutes later.

So, it would be problematic to stop deployment of the CWA website because a third-party website which CWA has no control over is failing.

If link checking could be integrated into deployment so it does not delay or stop deployment if there is a minor error, then that would be different. Maybe there would need to be some threshold to accept, for instance, 5 bad links, but anything more would be an indication of something more serious being wrong.

Anyway it is a major step forward to have link checking available, even if it needs to be used manually at this time.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I agree with you! I also thought that failing links should not be shown as an error but only as a warning, so that the author of the commit / RP can decide themself how to proceed and whether to check why the check is failing and why not.

AFAIK checks can either be required to succeed to be able to merge the PR or be optional to pass.

**Comment by MikeMcC399** [comment]
There was an issue in September 2020 with running the Cypress tests as part of the build. (This was before link-checking was introduced.) PR https://github.com/corona-warn-app/cwa-website/pull/385 removed the tests from the Cypress workflow.

**Comment by Ein-Tim** [comment]
Closing in favour of https://github.com/corona-warn-app/cwa-website/issues/2892.
