### ISSUE TITLE
Missing link to icon file for web top level

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1833]
## Where to find the issue

https://www.coronawarn.app/index.html

## Describe the issue

Running https://www.deadlinkchecker.com on https://www.coronawarn.app produces the error 

Error |	URL	| Anchor Text |	Linked From
--- | --- | --- | ---
403 Forbidden | https://www.coronawarn.app/assets/img/icons/ | link/href | https://www.coronawarn.app

## Analysis

https://www.coronawarn.app/index.html
includes the following HTML code

```
<link
  rel="icon"
  type="image/png"
  sizes="32x32"
  href="/assets/img/icons/"
/>
```

which is generated from [src\layouts\redirect.html](https://github.com/corona-warn-app/cwa-website/blob/master/src/layouts/redirect.html)

The name of the icon file is missing.

## Suggested change

Change LN14 of src\layouts\redirect.html 
https://github.com/corona-warn-app/cwa-website/blob/557237207948549bf46188229f9f8042c0a48ed2/src/layouts/redirect.html#L14
from
`href="{{root}}{{global.favicon.url}}"`
to
`href="{{root}}{{global.favicon.url}}{{global.favicon.name}}-32x32.png"`

This generates 

`href="/assets/img/icons/favicon-32x32.png"`

which points to the existing icon https://www.coronawarn.app/assets/img/icons/favicon-32x32.png

### Reference

https://html.spec.whatwg.org/multipage/links.html#rel-icon

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. We will have a look at this issue.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks a lot, your PR was merged.
