### ISSUE TITLE
`eu_dcc_validity` FAQ entry is missing information on where to renew certificates

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1835]
## Where to find the issue
- https://www.coronawarn.app/en/faq/#eu_dcc_validity
- https://www.coronawarn.app/de/faq/#eu_dcc_validity

## Describe the issue
The FAQ entry is missing information what to do after the certificate got invalid. Should the certificate be renewed? If yes, where? And how if there was no booster vaccination, according to the FAQ entry the vaccination protection only lasts one year? 

Also, there is [this](https://twitter.com/bmg_bund/status/1445720652107980801?s=21) video shared by the BMG on Twitter (and retweeted by [@coronawarnapp](https://twitter.com/coronawarnapp?s=21)), which says this:

![image](https://user-images.githubusercontent.com/67682506/136339496-1a00fc68-cb31-4ecc-9dad-06088d1f1fb7.jpeg)

Does this mean that nobody should have to renew their vaccination certificates?

## Suggested change
Clarify what exactly the current recommendations are and update the FAQ entry accordingly.

---
Internal Tracking ID: [EXPOSUREAPP-12829](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12829)

**Comment by Ein-Tim** [comment]
@dsarkar Any update here? Although there is an certificate update feature in the app now, it is not used to extend EU DCCs reg. their technical validity.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The information on https://www.zusammengegencorona.de/faqs/impfen/impfnachweis/#id-1fec6f86-736f-5cee-b286-81bd122558fa was updated last week and it says:

"**Das digitale Impfzertifikat hat ein Ablaufdatum. Bedeutet das, dass mein Impfschutz ebenfalls erlischt?**

Nein. Das digitale Impfzertifikat hat aus technischen Gründen ein Ablaufdatum. Dieses richtet sich nicht nach dem Zeitpunkt der Impfung, sondern nach dem Zeitpunkt der Zertifikat-Ausstellung. Ihr Impfschutz erlischt also nicht mit dem Ablaufdatum des Zertifikats. Die ersten Impfzertifikate laufen Ende des zweiten Quartals 2022 aus. Bis dahin wird es eine einheitliche europäische Lösung geben, so dass auch nach Ablauf der Impfzertifikate eine Nutzung des digitalen Impfnachweises möglich sein wird.

Wichtig zu wissen: Die Anerkennungsdauer für das digitale Impfzertifikat der EU für Reisezwecke wurde auf max. 180 Tage festgelegt. Für die Einreise nach Deutschland – und in andere Mitgliedsstaaten der EU - sind daher digitale COVID-Impfzertifikate der EU nach Abschluss der ersten Impfserie (Grundimmunisierung) 180 Tage und bei einer Booster-Impfung unbegrenzt gültig. Für andere Zwecke innerhalb von Deutschland (2G und 3G) gilt die Befristung nicht. Die Gültigkeit des Genesenenzertifikats wurde für Deutschland auf 90 Tage begrenzt. Diese Frist gilt auch für die Einreise nach Deutschland.

Stand: 07.04.2022"

So no change in the fact that we are still waiting for the statement from the authorities promised by the end of calendar Q2/2022 i.e. end of June 2022.

**Comment by Ein-Tim** [comment]
@MikeMcC399

Thank you! Then the question rather is: Should the article state **not** to get certificates reissued? What would you say? And what does the Open-Source-Team say? 

cc @thomasaugsten

---

Completely unrelated side note, the information on the page is wrong, it is not 180 days but 270 days, see https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837. I will write them an E-Mail to fix this.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> Should the article state not to get certificates reissued?

No

> What would you say? 

- For "How to extend the technical validity of a certificate?" - wait for the EU process to be announced (end of Q2/2022)
- For "How to extend the effective validity of a certificate?" - rely on the booster rules to inform users about additional vaccinations e.g. https://github.com/corona-warn-app/cwa-wishlist/issues/820 and https://github.com/corona-warn-app/cwa-documentation/issues/754

I do not think that there should be any change to https://www.coronawarn.app/en/faq/results/#eu_dcc_validity at this time.

**Comment by Ein-Tim** [comment]
- FYI: https://github.com/corona-warn-app/cwa-app-ccl/pull/75

**Comment by MikeMcC399** [comment]
@Ein-Tim 

According to https://github.com/corona-warn-app/cwa-website/blob/f8a688704bbc5049bc067317efabb7a4491ed481/src/data/screenshots.json#L14 reissuance is planned for the 2.23 release.

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/2858 adds FAQ articles concerning renewal of certificates when the technical validity is expiring.

[#eu_dcc_validity](https://www.coronawarn.app/en/faq/#eu_dcc_validity) is however not being changed by the above PR.

The statement https://www.zusammengegencorona.de/faqs/impfen/impfnachweis/#id-1fec6f86-736f-5cee-b286-81bd122558fa mentioned in https://github.com/corona-warn-app/cwa-website/issues/1835#issuecomment-1097830798 does not yet contain any concrete information about certificate renewal.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for raising this issue. [#eu_dcc_validity](https://www.coronawarn.app/en/faq/#eu_dcc_validity) should be adapted!

**Comment by svengabr** [comment]
I have added the generic link list to the newly added related articles to the `release/2.23` branch:

![eu_dcc](https://user-images.githubusercontent.com/4686874/171167551-be156c66-43d9-423e-a7dc-88ba5e3a636f.png)

**Comment by Ein-Tim** [comment]
@svengabr This looks good to me! Thanks.

**Comment by Ein-Tim** [comment]
Additional information has been added. Closing.
