### ISSUE TITLE
check_links.js does not find bad hyperlinks to bookmarks

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1836]
## Where to find the issue

[cypress/integration/check_links.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/check_links.js)

## Describe the issue

[check_links.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/check_links.js) does not find bad links to bookmarks.

### Steps to reproduce

1. Introduce a bookmark hyperlink error into one of the .json source files
For instance, in [faq.json](https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq.json) change the first occurrence of `#international_phone_numbers` to `#international_phone_number` (remove last letter)
2. run `npm run test:open`
3. select check_links.js to run in cypress console
4. Note that the error is not found. Instead the test shows a success

`Link: http://localhost:8000/en/faq/#international_phone_number: expected 200 to equal 200`

The bad link
`<a href='#international_phone_number' target='_blank' rel='noopener noreferrer'>click here to see the phone numbers</a>` shows as success.

In the next paragraph the link is correct
`<a href='#international_phone_numbers' target='_blank' rel='noopener noreferrer'>click here to see the phone numbers</a>`

Both the bad link and the good link show as success.

![wrong success check links](https://user-images.githubusercontent.com/66998419/136363648-fa36a229-311f-4b1a-b784-e06f74820fc9.jpg)

## Suggested change

Since there is a lot of use of hyperlinks to bookmarks (aka anchors) in faq.json and faq_de.json, implement a link check for these hyperlinks either in check_links.js or in a separate cypress JavaScript script.

This is an enhancement request.

---
Internal Tracking ID: [EXPOSUREAPP-9752](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9752)

**Comment by MikeMcC399** [comment]
I thought it might be possible to use `npm run-script checklinks`  from the [cwa-documentation repository](https://github.com/corona-warn-app/cwa-documentation)  that makes use of [markdown-link-check](https://www.npmjs.com/package/markdown-link-check) on *.md files which are used in the [blog](https://github.com/corona-warn-app/cwa-website/tree/master/blog) and [science](https://github.com/corona-warn-app/cwa-website/tree/master/science) sources.

It seems though that [markdown-link-check](https://www.npmjs.com/package/markdown-link-check) will not find hyperlinks to non-existent bookmarks either, such as in `[my link](#bad_bookmark)`. It just marks them as passed. 🙁

**Comment by dsarkar** [comment]
@MikeMcC399 Sure, open an issue and we try to look into that ASAP. Thanks!
