### ISSUE TITLE
Request to add PPA (Privacy Preserving Analytics) to Glossary

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1843]
## Enhancement request to Glossary

Please add the term PPA (Privacy Preserving Analytics) to the [Glossary](https://www.coronawarn.app/en/faq/#glossary) and link to the entry [Data Donation](https://www.coronawarn.app/en/faq/#glossary_data_donation).

## Reason for request

The term is used in the Analysis text for https://www.coronawarn.app/en/analysis/ > Warnungen > i symbol where it says:

"Datenquellen
Privacy-Preserving-Analytics (PPA)"

however this term is not explained there.

**Comment by MikeMcC399** [comment]
@dsarkar / @larswmh 

https://www.coronawarn.app/en/faq/#glossary_ppa and
https://www.coronawarn.app/de/faq/#glossary_ppa

have been created which simply link to

https://www.coronawarn.app/en/faq/#glossary_data_donation and
https://www.coronawarn.app/de/faq/#glossary_data_donation respectively

I thought you might want to explain what PPA is.

There is an explanation on https://www.coronawarn.app/de/science/2021-10-15-science-blog-4/#3-privacy-preserving-analytics which could be the basis for some similar text in the Glossary:

"PPA steht für Privacy Preserving Analytics. Mit diesem Verfahren ist es möglich, dass Nutzende der CWA die in ihrer App auf ihrem Smartphone anfallenden Daten einer auswertenden Instanz zur Verfügung stellen, ohne dabei ihre Identität preiszugeben."

Please consider if the new 

https://www.coronawarn.app/en/faq/#glossary_ppa and
https://www.coronawarn.app/de/faq/#glossary_ppa

could be enhanced with a bit more information like the above.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. https://github.com/corona-warn-app/cwa-website/pull/1912

**Comment by MikeMcC399** [comment]
This issue is now resolved. Thanks to @larswmh and @dsarkar for responding!
