### ISSUE TITLE
Error result from Uni Wuppertal survey linked from blog

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1877]
## Where to find the issue

- https://www.coronawarn.app/en/blog/2021-02-23-corona-warn-app-survey/ "Corona-Warn-App Survey"
- https://www.coronawarn.app/de/blog/2021-02-23-corona-warn-app-survey/ "Umfrage zur Corona-Warn-App"

## Describe the issue

The link https://umfrage.uni-wuppertal.de/index.php/765823?lang=de embedded in the blog leads to an error message:

---
Fehler

Es tut uns leid, aber diese Umfrage ist abgelaufen und nicht mehr verfügbar.

Bitte kontaktieren Sie Tim Katzwinkel für weitere Informationen.
katzwinkel@uni-wuppertal.de

---

![image](https://user-images.githubusercontent.com/66998419/137365273-84f96405-d8e1-4d51-8cb9-e0e38e78a38a.png)

## Suggested change

There are several options:

1. Do nothing and assume that the web page will continue to stay online giving out the present information.
2. Remove the link to the survey https://umfrage.uni-wuppertal.de/index.php/765823?lang=de in the source files found in https://github.com/corona-warn-app/cwa-website/tree/master/blog/2021-02-23-umfrage-uni-wuppertal and state that the survey has been discontinued
3. Contact the survey author katzwinkel@uni-wuppertal.de from the Bergische Universität Wuppertal to find out if the survey produced results.
4. If there are useful results, then consider publishing them to the [Science Blog](https://www.coronawarn.app/en/science/)

---
Internal Tracking ID: [EXPOSUREAPP-11551](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11551)

**Comment by LucaSchwan** [comment]
Hello,
I've written an E-mail to to survery author asking him wether there are any results to the survey that can be linked. Can I update the Blog post when I get an answer?

**Comment by MikeMcC399** [comment]
@LucaSchwan 
> Can I update the Blog post when I get an answer?

It would be great if you could first share an answer if you do get a reply. After that we might discuss exactly what to do after that and get agreement.

**Comment by LucaSchwan** [comment]
I have just gotten an answer. The Survey has been conducted for SAP and they should have all the results. So as far as I know there isn't any official pulication.

**Comment by MikeMcC399** [comment]
@LucaSchwan 

The question now, for SAP (and RKI), is if they want to publish the results or at least make some statement, after having enlisted the cooperation of users. This is all quite old now though.

**Comment by larswmh** [comment]
Thanks for your report @MikeMcC399. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11551](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11551)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@larswmh Do you have any update on this, which you could share with us?

**Comment by MikeMcC399** [comment]
Option 2. from the suggestions was used to resolve this issue:

- Remove the link to the survey https://umfrage.uni-wuppertal.de/index.php/765823?lang=de in the source files found in https://github.com/corona-warn-app/cwa-website/tree/master/blog/2021-02-23-umfrage-uni-wuppertal and state that the survey has been discontinued
