### ISSUE TITLE
Falsche Hotline-Telefonnummern bzw. Nummern falsch angegeben

### ISSUE THREAD

**Issue by bjhaberer** [corona-warn-app/cwa-website#189]
## Where to find the issue

Z.B. im Footer bzw. Footer-Menü, aber auch in den Telefon-Apps
## Describe the issue

0800er-Nummern sind aus dem Ausland nicht erreichbar. Da nutzt es nichts, diese zu "internationalisieren", indem man die 0 wegnimmt und ein+49 davorsetzt. Das funktioniert möglicherweise von einem Handy im Inland aus, aber nciht aus dem Ausland.
Die falsche Angabe ist sehr ärgerlich. Nicht nur, wenn man darauf verwiesen wird, doch die App-Hotline anzurufen, um den Fehler zu melden, sondern auch, wenn man sich eine TAN im Sinne der effizienten Nutzung der App besorgen möchte.  

## Suggested change

Der Fehler wäre beseitigt, wenn die "+49" durch eine "0" ersetzt werden würde. Klarer Hinweis auf eine nationale Telefonnummer statt einer pseudo-internationalisierten Nummer.
Funktional sinnvoll wäre allerdings eine zusätzliche Nummer, die vom Ausland zu erreichen ist, bzw. ein Hinweis, wie man sonst eine TAN erhalten oder die App-Hotline erreichen kann.

**Comment by SebastianWolf-SAP** [comment]
Wir haben uns auf eine konsistente Verwendung der internationalen Schreibweise geeinigt. Diese funktioniert auch im Inland und macht zudem deutlich, dass es sich um eine deutsche Telefonnummer handelt. 

Sie haben allerdings recht - die Schreibweisen der Telefonnummern waren streckenweise falsch und entsprachen nicht der Norm. Wir haben das mit 53e61d7a1f0ca7843022ffbfbd9b07fddcb6fdf9 korrigiert.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by bjhaberer** [comment]
> Wir haben uns auf eine konsistente Verwendung der internationalen Schreibweise geeinigt. Diese funktioniert auch im Inland und macht zudem deutlich, dass es sich um eine deutsche Telefonnummer handelt.
> 
> Sie haben allerdings recht - die Schreibweisen der Telefonnummern waren streckenweise falsch und entsprachen nicht der Norm. Wir haben das mit [53e61d7](https://github.com/corona-warn-app/cwa-website/commit/53e61d7a1f0ca7843022ffbfbd9b07fddcb6fdf9) korrigiert.
> 
> Mit freundlichen Grüßen/Best regards,
> SW
> Corona Warn-App Open Source Team

Ich habe den Kommentar nicht verstanden. 
Sie wollen die internationale Schreibweise beibehalten für eine Nummer, die aus dem Ausland nicht zu erreichen ist?

Was ist der Sinn hiervon? Was ist die Funktion einer Telefonnummer, die den Anschein erweckt, man könne sie vom Ausland anrufen und die dannn meldet "Die Nummer, die Sie gewählt haben ist regional begrenzt und aus Ihrem Vorwahlbereich nicht erreichbar"?

Weil Sie sich mit der eigentlichen  Zielgruppe einer internationalen Schreibweise - nämlich die, die vom Ausland aus anrufen - einen Scherz erlauben wollen?

Die internationale Schreibweise ist falsch. Sie ist pseudo.international, weil die Nummer nicht aus dem Ausland Ierreicht werden kann. 

Die Nummern waren nicht streckenweise falsch, sie sind es immer noch im Sinne des Zweckes, warum man eine internationale Schreibweise verwendet, nämlich für den internationelen Gebrauch.

Damit führen Sie die Benutzer in die Irre, bzw. veràrgern, verunsichern und stehlen die Zeit von genau denjenigen, für die die Schreibweise gedacht ist:: 
Für einen Anruf aus dem Ausland

Das hat nichts mit dem Einfügen von Leerzeichen nach DIN zu tun.

Und das Voranstellen einer Làndervorwahl sagt nicht aus, dass es sich um eine Nummer dieses Landes handelt, die nur innerhalb dieses Landes erreichbar ist, sondern dass die Nummer dieses Landes mit dieser Vorwahl aus dem Auswahl erreichbar ist. 

Wenn man ausdrücken, möchte, dass die Nummer nur aus dem Land selbst erreichbar ist, dann verwendet eben KEINE Ländervorwahl.  

Mit freundlichen Grüßen 

Bernward Haberer

**Comment by mohe2015** [comment]
Ich finde die internationale Schreibweise an sich nicht schlimm, da dann erkennbar ist, dass es sich um eine deutsche Nummer handelt. Jedoch sollte der Hinweis, dass diese Nummer nur aus Deutschland erreichbar ist, hinzugefügt werden, die in dem anderen PR auch vorgeschlagen.

**Comment by bjhaberer** [comment]
> Ich finde die internationale Schreibweise an sich nicht schlimm, da dann erkennbar ist, dass es sich um eine deutsche Nummer handelt. Jedoch sollte der Hinweis, dass diese Nummer nur aus Deutschland erreichbar ist, hinzugefügt werden, wie in dem anderen PR auch vorgeschlagen.

Ich glaube nicht, dass man jemanden in Deutschland und auch im Ausland erklären muss, dass eine Telefonnummer ohne Ländervorwahl auf einer deutschen Website eine deutsche Telefonnummer ist.

Der Sinn einer Ländervorwahl und einer Telfonnummer mit Ländervorwahl ist und bleibt: 
Diese Telefonnummer ist genau so aus dem Ausland erreichbar. 

Mit "erkennbar, dass es sich um eine deutsche Nummer handelt, jedoch ..." pervertieren Sie den Sinn einer Ländervorwahl. Der ist nämlicdh rein praktisch und nicht informationsromantisch.

**Comment by SebastianWolf-SAP** [comment]
Ein kleines Problem mit dem Zusatz '(Deutschland)' oder '(Germany)' neben dem Titel - was im mittlerweile geschlossenen PR #191 vorgeschlagen wurde - ist, dass der Text dann leicht zu lang wird. Das ist besonders dann interessant, wenn die Seite auf Mobilgeräten angezeigt wird. Hierbei kommt es zu Darstellungsfehlern. Deswegen haben wir die Überschriften so kurz wie möglich gehalten.

Davon abgesehen: Wir erlauben uns hier keinen Scherz und wir "pervertieren" auch nicht den Sinn einer Ländervorwahl. Ich möchte an der Stelle auch um eine sachliche Diskussionskultur bitten. 

Wir nutzen eine gültige Notation, die in jedem Kontext funktioniert und sich zudem immer mehr auch im rein innerdeutschen Kontext durchsetzt. Die App selbst funktioniert selbst auch nur vollständig im innerdeutschen Kontext - dennoch haben wir nicht an jeder Stelle einen Hinweis darauf eingebaut. Bisher sind wir davon ausgegangen, dass sich dies aus dem Kontext und den bestehenden Erklärungen ergibt. Kontaktmöglichkeiten für Menschen, die sich nicht in Deutschland aufhalten, haben wir zudem genug - etwas GitHub oder unsere E-Mail-Adresse.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by bjhaberer** [comment]
Sie nutzen eine Notation, die eben nicht in jedem Kontext funktioniert. Nämlich genau nicht in dem Kontext, für den sie gedacht ist. Dies ist nun eine Perversion - eine Umdrehung - des ursprünglichen Sinnes der Ländervorwahl. Sie geben ihr ihren eigenen Sinn. Dies ist eine durchaus sachliche, argumentativ untermauerte Feststellung. Und als betroffener Nutzer aus dem Ausland fühle ich mich verschaukelt, weil mir etwas vorgegaukelt wird, was nicht stimmt, und ich dadurch nur Zeit verliere. Das ist Worst Practice für Website-Informationsgestaltung.

Auf der Website sind keine alternativen Kontaktmöglichkeiten zur Hotline für den "normalen Besucher" angegeben.

Github: ist laut Website für die Mitarbeit gedacht, und nicht für die das Melden von Benutzerproblemen stattt Hotline. Der Aufwand und Einarbeitung ist nicht angemessen dafür. Das wissen Sie. 

E-Mail-Adresse: Welche meinen Sie?
Als einziger Kontakt auf der Website ist (war?) die Hotline-Telefonnummer angegeben. Ich habe vor einigen Wochen nur die Mailadresse im Impressum gefunden (wo m.E. die wenigsten normalen Benutzer reinschauen). An diese Adresse habe ich geschrieben. Ich wurde darauf hingewiesen, dass SAP nichts mit dem Inhalt der Website zu tun habe, und ich doch die Hotline anrufen solle. Zusätzlich wurde mir dann doch noch eine Mailadresse des RKI angegeben, die als Antwort gemeldet hat, dass Mails an diese Adresse nicht gelesen werden. nach weiterem Austausch wurde mir geantwortet, dass obwohl die Mail nichts mit SAP zu tun habe, sie an die zuständige Gruppe der Telekom weitergeleitet wurde. Das ist lange her.  

Mit freundlichen Grüßen

Bernward Haberer

**Comment by SebastianWolf-SAP** [comment]
Das Robert-Koch-Institut als Herausgeberin der App hält für allgemeine Fragen die Adresse CoronaWarnApp@rki.de bereit. Die E-Mails werden schon gelesen und - sofern Ihre Frage nicht durch FAQs und bestehende Erklärungen abgedeckt ist - auch beantwortet.

Für Fragen zum Open Source/Community-Prozess haben wir unter https://www.coronawarn.app/de/community/ sowie hier auf GitHub die E-Mail-Adresse corona-warn-app.opensource@sap.com veröffentlicht. Je nach ihrem Anliegen können Sie sich an die eine oder andere Adresse wenden.

Weiterhin können Sie hier auf GitHub Fehler und Verbesserungsvorschläge melden.

Deswegen der Vorschlag: Bevor wir uns jetzt hier über die Frage der internationalen Notation für Telefonnummern weiter streiten, würde ich Sie bitten, sich mit Ihrem konkreten Problem an die entsprechende Stelle zu wenden. 

Da Sie sich allerdings noch im Ausland befinden, muss ich Ihnen leider mitteilen, dass der Nutzen der App für Sie wahrscheinlich begrenzt ist. Aktuell ist sie nur sinnvoll innerhalb Deutschlands einsetzbar.

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by bjhaberer** [comment]
Sie nutzen eine Notation, die eben nicht in jedem Kontext funktioniert. Nämlich genau nicht in dem Kontext, für den sie gedacht ist. Dies ist nun eine Perversion - eine Umdrehung - des ursprünglichen Sinnes der Ländervorwahl. Sie geben ihr ihren eigenen Sinn. Dies ist eine durchaus sachliche, argumentativ untermauerte Feststellung. Und als betroffener Nutzer aus dem Ausland fühle ich mich verschaukelt, weil mir etwas vorgegaukelt wird, was nicht stimmt, und ich dadurch nur Zeit verliere. Das ist Worst Practice für Website-Inhalt.

Github: ist laut Website für die Mitarbeit gedacht, und nicht für die das Melden von Benutzerproblemen stattt Hotline. Der Aufwand und Einarbeitung ist nicht angemessen dafür. Das wissen Sie.

E-Mail-Adresse: Welche meinen Sie?
Als einziger Kontakt auf der Website ist (war?) die Hotline-Telefonnummer angegeben. Ich habe vor einigen Wochen nur die Mailadresse im Impressum gefunden (wo m.E. die wenigsten normalen Benutzer reinschauen). An diese Adresse habe ich geschrieben. Ich wurde darauf hingewiesen, dass SAP nichts mit dem Inhalt der Website zu tun habe, und ich doch die Hotline anrufen solle. Zusätzlich wurde mir dann doch noch eine Mailadresse des RKI angegeben, die als Antwort gemeldet hat, dass Mails an diese Adresse nicht gelesen werden. nach weiterem Austausch wurde mir geantwortet, dass obwohl die Mail nichts mit SAP zu tun habe, sie an die zuständige Gruppe der Telekom weitergeleitet wurde.  

Mit freundlichen Grüßen

Bernward Haberer

**Comment by bjhaberer** [comment]
Wir sprechen hier vom Problem, dem Problem auf der Website. Das Problem ist nicht die Notation, sondern dass die Notation falsch, nämlich blind ohne Sinn, angewandt wird und so zu einem Fehler bzgl. Inhalt und Benutzerführung führt. 

> Ein kleines Problem mit dem Zusatz '(Deutschland)' oder '(Germany)' neben dem Titel ...
Das Problem besteht nicht im Zusatz, sondern darin, dass der Zusatz nicht notwendig ist.

> Wir erlauben uns hier keinen Scherz
Ich wollte damit zus£tzlich verdeutlichen, dass Sie die Benutzer mit einer falschen Telefonnummer in die Irre führen. Wenn man dies trotz besseren Wissens aufrecht erhält, muss man schon einen guten Grund haben. Gut, dass es zumindest kein Scherz ist.

> wir "pervertieren" auch nicht den Sinn einer Ländervorwahl. 
Pervertieren=Ins Gegentetil verkehren, fälschen. Mit der Ländervorwahl wird eine bestehende, funktionierende Telefonnummer für einen Anruf aus dem Ausland erreichbar. Die Ländervorwahl dient nicht dazu anzuzeigen, dass die Nummer nicht funktioniert, weil sie einem anderen Land zugeordnet ist. Dies iist Ihre Umdeutung und verkehrt den Sinn der Ländervorwahl ins Gegenteil.
  
> Wir nutzen eine gültige Notation, die in jedem Kontext funktioniert und sich zudem immer mehr auch im rein innerdeutschen Kontext durchsetzt. 
Diese Notation funktioniert nicht in jedem Kontext, nämlich genau nicht im Kontext der 0800er-Nummern. Alle anderen Nummern können mit dieser Konvention für das Anfügen der Ländervorwahl Rufnummern umgewandelt werden, die vom Ausland aus erreichbar sind. Diese nicht. Es is schön, dass sich die Notation auch im innerdeutschen Kontext durchgesetzt hat, um ausländischen Kommunikationspartnern das Nachschauen der korrekten Vorwahl und Anpassung zu erleichtern. Denn das ist der einzige Sinn einer solchen Notation.  Es ist schön, dass die Auslands-Nummer auch (und auch mit altem analogen oder ISDN-Anschluss?) innerhalb Deutschlands funktioniert. Innerhalb von Deutschland brauchen Sie aber die Ländervorwahl nicht. Und die Nummer funktioniert aus dem Ausland eben nicht. Die Nummer ist pseudo-internationalisiert und funktioniert in Deutschland selbst nur weil das Netz mittlerweile in der Lage ist, seine eigene Auslandsvorwahl aufzulösen, was füher im Festnetz gar nicht ging. Das heißt aber nicht, dass die Verwendung im innerdeutschen Kontet irgendeinen Sinn ergäbe. Ich speichere das im Handy so ein, damit ich auch vom Ausland meinen Kontakt wie gewohnt anwählen zu können, ohne korrigieren zu müssen.  

> Die App selbst funktioniert selbst auch nur vollständig im innerdeutschen Kontext
Das ist falsch nach der Ankündigung von allen Stellen zum Start der App inklusive Regierung, Verbraucherschutz, Medien.
Die App funktioniert im Ausland zwischen allen, die die gleiche App verwenden (explizit erwähnt, auch das Beispiel deutscher Urlauber trifft deutschen Urlauber, oder ich werde im Urlaub im Ausland krank), und im Inland zwischen allen ohne Unterscheid zwischen Zugehörigkeit zu einem anderen Sozialsystem.
Sonst wäre da kommunikationsmäßig von Ihrer Seite kräftig etwas schief gelaufen.
Oder wieso funktioniert sie nur im innerdeutschen Kontext?
Ich kann nicht ständig die FAQs neu durchackern. Da gab es schon genug interesaante Änderungen im Rahmen der PlayStore-Panne.

Was macht denn den innerdeutschen Kontext bzgl. Funktion aus? Wenn ich eine positive Testbscheinigung einreiche, werden theoretisch alle 30000 "deutschen Pendler-Kollegen" benachrichtigt. Und alle meine Kontakte in Deutschland, wo ich regelmäßig bin. Feine Sache zur Verfolgung der Infektionsketten. Dafür brauche ich nur eine TAN. Kein Problem, die bekomme bei der TAN-Hotline, die ist laut App und Website sogar aus dem Ausland erreichbar: +49 7.... Ups. Oder doch nicht.  Dazu später noch eine Frage.

> dennoch haben wir nicht an jeder Stelle einen Hinweis darauf eingebaut.
Sie sollen auch keinen Hinweis hinzufügen, sondern einen falschen Hinweis entfernen. Die Nummern gibt es so nicht. Sie ist nicht aus dem Ausland erreichbar, und der einzige Sinn einer Ländervorwahl ist, die darauf folgende Nummer vom Ausland aus erreichbar zu machen.

> Bisher sind wir davon ausgegangen, dass sich dies aus dem Kontext und den bestehenden Erklärungen ergibt. 
Dass sie einen Formalismus auf eine Telefonnummer falsch angewandt haben und daher den Benutzer bewusst in die Irre führen?

> Kontaktmöglichkeiten für Menschen, die sich nicht in Deutschland aufhalten, haben wir zudem genug - etwas GitHub oder unsere E-Mail-Adresse.
Können Sie mir bitte sagen, wo ich die auf der Website (darum geht es hier) oder in der App finde?

> Das Robert-Koch-Institut als Herausgeberin der App hält für allgemeine Fragen die Adresse [CoronaWarnApp@rki.de](mailto:CoronaWarnApp@rki.de) bereit. Die E-Mails werden schon gelesen und - sofern Ihre Frage nicht durch FAQs und bestehende Erklärungen abgedeckt ist - auch beantwortet.

Ich habe z.B. keine Antwort auf die implizite Frage erhalten, welche Nummer aus dem Ausland gewählt werden kann um zum Beispiel eine TAN zu erhalten. Die Linie bzgl. der PlayStore-Panne mit sich ändernden Informationen durch Hotline (Artikel SR) und sich ändernden FAQs ("stand ja in den FAQs") bis hin zu den nachräglichen Kommentaren im PlayStore halte ich nicht für aufrichtig und könnte das auch gerne ausführen. Gehört aber nicht hierhin. Ich habe nur das Gefühl, die Diskussion hier atmet den gleichen Geist. 

> Für Fragen zum Open Source/Community-Prozess haben wir unter https://www.coronawarn.app/de/community/ sowie hier auf GitHub die E-Mail-Adresse [corona-warn-app.opensource@sap.com](mailto:corona-warn-app.opensource@sap.com) veröffentlicht. Je nach ihrem Anliegen können Sie sich an die eine oder andere Adresse wenden.

* An wen muss ich mich melden, wenn ich melden will, dass die Auslandsnummern für TAN- und App-Hotline, die auf der Website angegeben  ist, aus dem Ausland nicht erreichbar ist? 
* An wen muss ich mich wenden, um eine Telefonnummer zu erhalten, die vom Ausland aus zu erreichen ist? 
* An wen muss ich wenden, dass diese Nummer dann auch in die App und auf die Website kommt?

Bis dahin, oder falls es keine Nummer geben wird: 
* An welche E-Mail-Adresse muss ich schreiben, wenn ich (z.B. ein im Ausland erkrankter Deutscher, der sich vor seinem Urlaub angesteckt hat) eine TAN benötige?
* An wen muss ich mich wenden, dass diese E-Mailadresse in die App und auf die Website kommt (vielleich sogar ein paar Informationen dazu?)
 * An welche E-Mailadresse muss ich mich wenden, wenn ich als Deutscher im Ausland Fragen zur App habe?

> Weiterhin können Sie hier auf GitHub Fehler und Verbesserungsvorschläge melden.
Die Verwendung der Auslandsvorwahll ist ein Fehler, wenn die Nummer nicht aus dem Ausland erreichbar ist.

> Deswegen der Vorschlag: Bevor wir uns jetzt hier über die Frage der internationalen Notation für Telefonnummern weiter streiten, würde ich Sie bitten, sich mit Ihrem konkreten Problem an die entsprechende Stelle zu wenden.

Da gibt es nichts zu streiten, und ich kann Ihre Haltung auf vernünftige Weise nicht nachvollziehen. Eine internationale Notation ist nur sinnvoll, wenn die Nummer auch international erreichbar ist. Sprechen Sie mit Ihren Kollegen von der Telekom darüber. Es gibt keinen anderen Grund für diese Notation. (Nur aus Neugier: Haben Sie schon oft aus dem Ausland telefoniert?)

Mein konkretes Problem ist, 
* dass die Nummern nicht aus dem Ausland erreichbar sind, wie durch die Notation eindeutig angekündigt. 
* (Rein formal: Benutzer werden in die Irre geführt. Das macht man nicht. Aus veschiedenen Gründen) 
* Es gibt genug Gründe, dass diese Nummern - bzw. da das ja gar nicht geht: alternative, nicht kostenfreie alternative Nummern - aus dem Ausland erreichbar sind.
* Diese Nummern müssen kommuniziert werden, auf Website und auf App
* Falls keine alternativen Nummern genannt werden können (aber soweit ich weiß, ist jede 0800-Nummer auch an eine kostenpflichtige reguläre Nummer gekoppelt, dazu gibt es sogar eigene Websites), müsste klar und deutlich eine alternative Form der Kommunikation (E-Mail-Adresse) eingerichtet werden, und in App und auf Website kommuniziert werden.

Wie auch schon weiter oben: An wen muss ich mich für die einzelnen Punkte wenden?  
 
> Da Sie sich allerdings noch im Ausland befinden, muss ich Ihnen leider mitteilen, dass der Nutzen der App für Sie wahrscheinlich begrenzt ist. Aktuell ist sie nur sinnvoll innerhalb Deutschlands einsetzbar.

Wieso ist die Nutzung begrenzt? Wieso ist sie nur sinnvoll in Deutschland einsetzbar? Technische Gründe gibt es laut Ankündigungen nicht, und auch funktionale kann ich nicht erkennen. Ich bekomme eine interne ID/Schlüssel, lade einen offiziellen positiven Test hoch oder werde informiert, wenn jemand anderes aus meiner Umgebung das gemacht hat. Wo ist der Haken? Es hieß ausdrücklich, dass Handys mit der gleichen App auch im Ausland miteinander kommunizieren und die App entsprechend funktioniert. Es gibt eine Menge ins Ausland pendelnder Deutscher und nach Deutschland pendelnder Nachbarn. Da ist der Einsatz sehr sinnvoll, wie auch für den Nachbarn, zu dem der Deutsche einkaufen fährt  Den Fall hat man einfach nur vergessen, wie auch die ganzen Ausländer mit nicht-deutschem PlayStore - ich habe Zahlen von 10 Mio gelesen, selbst wenn das stark übertrieben sein mag. (Hätte man das nicht vorher kommuniziert, wernn man letztere nicht vergessen hätte?. Nur ein einziger hat vom ersten oder zweiten Tag an mitgedacht, das beschrieben und sogar die App mit entspechendem Warnhinweis zum Download bereitgestellt) . Nicht schlimm.  Passiert. Ist auch nicht die Hauptzielgruppe. Aber es kommt darauf an, wie man damit umgeht. Und fühle mich auch durch die Diskussion hier bestätigt. 
Aber ich lasse mich gerne eines besseren belehren. 

Ich wäre froh, wenn Sie mir meine Fragen z.B. bzgl. eingeschränkter Funktionalität  beantworten bzw. mir sagen könnten, an welche Mailadresse ich mich mit welchem Anliegen wenden muss. Das ist mir nicht ersichtlich. Wobei ich persönlich der Meinung bin, dass hier ein Gesamtansatz zur Lösung notwendig ist, und nicht eine Verteilung der Fragen auf einzelne Tickets, die den Gesamtzusammenhang ignorieren.   

Mit freundlichen Grüßen

Benward Haberer

**Comment by SebastianWolf-SAP** [comment]
Vielen Dank für die Konkretisierung Ihrer Fragen, auf die wir natürlich gerne eingehen.

- Ergebnisse ausländischer Testlabore werden aktuell nicht akzeptiert. Sie erhalten nur eine teleTAN, wenn Sie innerhalb Deutschlands von einem Labor getestet wurden, welches das QR-Code-Verfahren nicht unterstützt oder Sie diesen QR-Code nicht mehr haben
- Da Sie bei Tests aus dem Ausland keine TAN erhalten werden, ergibt eine Erreichbarkeit der Hotlines aus dem Ausland wenig Sinn. Weiterhin müssen wir auch auf eine Abgrenzung mit den nationalen Apps der entsprechenden Länder achten. Die Interoperabilität mit anderen Apps ist aktuell in Planung, hier wird es demnächst weitere Informationen geben. Grenzgängern empfehlen wir, eventuelle Fragen entweder schriftlich an die genannten Stellen zu richten oder innerhalb Deutschlands anzurufen
- Die E-Mail-Adressen sind vom Robert-Koch-Institut als Herausgeber sowie von uns als Entwickler/Auftragnehmer an den genannten verschiedenen Stellen und auch nochmal hier im Issue publiziert worden. 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
