### ISSUE TITLE
Bad wording in Science Blog 4

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1893]
## Where to find the issue
https://www.coronawarn.app/de/science/2021-10-15-science-blog-4/#32-erhobene-daten (3.2.6)

## Describe the issue
In paragraph 3.2.6 in the section "Schlüsselteilung mit Metadaten der Endgeräte" there is one bullet point "Schlüsselteilung nach Abbruch des Schlüsselteilungsprozesses?".
This sounds like, to me, one did not want to share their keys but the app still shared them. 

## Suggested change
Sadly, I don't have a suggestion for a better wording right now. But maybe someone else has?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
You are referring to https://www.coronawarn.app/de/science/2021-10-15-science-blog-4/#326-schlüsselteilung

![image](https://user-images.githubusercontent.com/66998419/141500145-dd534e97-bc5f-4ef0-bbfb-d2a77f63ae55.png)

and it sounds like you think that:

"Schlüsselteilung nach Abbruch des Schlüsselteilungsprozesses?"

is a bad translation of:

`submitted_after_cancel`

Is that correct?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, exactly! "Schlüsselteilung nach Abbruch des Schlüsselteilungsbprozesses" is to englisch "Key sharing after termination of key sharing process."

This makes no sense, as it sounds like one didn't want to share their keys but the app shared it anyways.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I think that "submitted_after_cancel" means exactly what you say, which is strange, but I don't think that it is a translation error.

**Comment by MikeMcC399** [comment]
@Ein-Tim
 
The English page has now been published and on https://www.coronawarn.app/en/science/2021-10-15-science-blog-4/#326-key-submission it lists the equivalent line:

  - Key submitted after cancelling the key submission process? (`submitted_after_cancel`)

corresponding to:

  - Schlüsselteilung nach Abbruch des Schlüsselteilungsprozesses? (`submitted_after_cancel`)

Do you still see an issue here?

**Comment by Ein-Tim** [comment]
Yeah, also in English, it sounds like the key sharing process was canceled and the user didn't want to submit any keys but keys were still submitted. Or what do you say, as a native English speaker?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I believe that the English and German wording are correct and I do not think that there is any bug here.

At the most, you could say that this is a question about when and why this situation can occur. I do not have an explanation about why a key would be submitted after the key submission process has been cancelled.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Exactly this is the question I asked myself and which should be clarified IHMO. I think that what's meant is that if the user wanted to add the start of symptoms to the DKs but then canceled this process. Then the DKs are uploaded but the process itself has been canceled.

**Comment by Ein-Tim** [comment]
I consider this issue as obsolete, I have no idea how we could rephrase this so closing.
