### ISSUE TITLE
Always output source maps

### ISSUE THREAD

**Issue by jonaskuske** [corona-warn-app/cwa-website#19]
## Describe the issue

Currently, source maps are only written in development (using `gulp-if` and `!PRODUCTION` as condition). This makes it harder to inspect the code of the live site in the browser's DevTools and as far as I see doesn't really have any advantages, the code is open source anyway.

## Suggested change

Shipping source maps makes it easier to inspect and debug code on the live site and also is nice for beginners who might want to take a look at the website's code to discover how something was implemented. :)
So I suggest removing the guarding calls to `$.if()` that currently wrap `$.sourcemaps.write()` as well as the condition for the `devtool` webpack config.

I'd be happy to submit a PR if you agree. :)

---
Internal Tracking ID: [EXPOSUREAPP-12958](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12958)

**Comment by alvin-raminger-snk** [comment]
I agree that sourcemaps make it easier to inspect the code - which is why they are included for development. It is kind of common to not include those maps on the productive line.
This matter can hardly be concidered a bug. Yet I agree that this one would be an enhancement/improvement.

**Comment by svengabr** [comment]
While it's possible to have source maps now using `npm run dev`, source maps are still not included in the production build right now. I can change this next week to include source maps for production.

**Comment by dsarkar** [comment]
@jonaskuske Thanks for your suggestion. Now implemented. Best wishes, DS

---
Corona-Warn-App Open Source Team
