### ISSUE TITLE
FAQs don't redisplay in right place after browser resizing

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1922]
## Where to find the issue

https://www.coronawarn.app/en/faq/

## Describe the issue

When reading an FAQ article then resizing the browser the article is not always still displayed and re-entering the same link does not change the display.

### Steps to reproduce

1. Open Google Chrome on Desktop maximized i.e. it fills the screen.
2. Enter "https://www.coronawarn.app/en/faq/#eu_dcc_which" into address field to display this FAQ entry
3. Note that the article with the title "Which EU certificates are supported?" is displayed
4. Shrink the browser to the minimum width possible
5. Note that the article is no longer shown
6. Go to the address field and re-enter "https://www.coronawarn.app/en/faq/#eu_dcc_which"
7. Note that nothing changes: the requested article is still not shown

## Expected behavior 

If an FAQ article has been selected by using its anchor e.g. https://www.coronawarn.app/en/faq/#eu_dcc_which then after resizing the browser the article should still be displayed.

If the above is not possible then at least re-entering the URL should re-display the selected article.

**Comment by brifemu** [comment]
We have tested it on Firefox and Safari, and it works correctly. Researching, we have discovered that it is a Google Chrome bug.

**Comment by brifemu** [comment]
@MikeMcC399 
FYI: #2053

**Comment by MikeMcC399** [comment]
@brifemu 

I confirm that it now works perfectly with Google Chrome Version 95.0.4638.69 (Official Build) (64-bit)!

Thank you very much for fixing this issue! 🚀
