### ISSUE TITLE
Knock-on for planned change of main FAQ location in 2.13

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1929]
In the planned CWA 2.13 release the FAQ link in the app is changed from:

**EN**
https://www.bundesregierung.de/corona-warn-app-faq-englisch to
https://www.coronawarn.app/en/faq/

**DE**
https://www.bundesregierung.de/corona-warn-app-faq to
https://www.coronawarn.app/de/faq/

(See for instance Android PR https://github.com/corona-warn-app/cwa-app-android/pull/4179).

Should the references in https://www.coronawarn.app/en/faq and https://www.coronawarn.app/de/faq be changed with the 2.13 release or after it? That would seem to make sense.

### Locations which refer to Bundesregierung's FAQ

https://www.coronawarn.app/en/faq/#who_can_help
=> https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch

https://www.coronawarn.app/en/faq/#non_dev_related
=> https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch
=> https://www.bundesregierung.de/breg-en/service/contact

(... and equivalent /de pages as well.)

**Comment by MikeMcC399** [comment]
link to #1940

**Comment by MikeMcC399** [comment]
According to the text in https://github.com/corona-warn-app/cwa-website/pull/1945 the 2.13 release is planned for Wednesday, Nov 3, 2021.

Did you come to any decision about references on https://www.coronawarn.app to the FAQs on https://www.bundesregierung.de? Do the references need to be updated?

**Comment by Ein-Tim** [comment]
@MikeMcC399 Do you still want to leave this issue open? Or can it be closed?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Do you still want to leave this issue open? Or can it be closed?

The question was never answered. I reviewed the links in the CWA FAQs:

- https://www.coronawarn.app/en/faq/
    - https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch
    - https://www.bundesregierung.de/breg-en/service/contact
- https://www.coronawarn.app/de/faq/
    - https://www.bundesregierung.de/breg-de/themen/corona-warn-app
    - https://www.bundesregierung.de/breg-de/service/kontakt

and they point to either a general page or a contact page. 

Some of the linked information on these pages like the hotline phone numbers is out of date. The pages also link to the Bundesregierungs CWA FAQ pages which the CWA app no longer references:

- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636
- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-kontakt-1760044
- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392
- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-kontakt-1759708

It's a decision of the Open Source Team if they still want to stay linked to these pages. 

So the answer to your question is: yes, the issue should stay open.

What was your reason for asking if the issue can be closed?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thank you for your answer!

> What was your reason for asking if the issue can be closed?

I asked because in your OP you write:
> Should the references in https://www.coronawarn.app/en/faq and https://www.coronawarn.app/de/faq be changed at the same time as the 2.13 release? That would seem to make sense.

As version 2.13 has been released & what you suggested did not happen, I thought that this issue can be closed by now (as it is a question issue and not a enhancement request or bug report) because the question you asked was answered "by itself".

I also didn't get feedback on my issue #1944 and closed it with the 2.13 release therefore. 

But if you would like to hear feedback on this issue, feel free to leave it open (-:

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I have updated the question to make it not obsolete with the release announcement.
The Android roll-out is still on-going and I have not yet received the 2.13 release yet.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks!

Yes, as you know, rollout was paused. Some minutes ago, this version has been released on GitHub: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.13.2

**Comment by MikeMcC399** [comment]
### Locations which refer to Bundesregierung's FAQ

I have reviewed these links:

---
https://www.coronawarn.app/en/faq/#who_can_help

![Who can help EN](https://user-images.githubusercontent.com/66998419/142463459-3c3ce7c6-3c38-4496-ae3d-827602bd18e7.jpg)

=> https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch

![federal government EN](https://user-images.githubusercontent.com/66998419/142463510-38379234-992a-45b1-932a-c40863d384d6.jpg)

---
https://www.coronawarn.app/en/faq/#non_dev_related

![non dev related EN](https://user-images.githubusercontent.com/66998419/142463546-1115d46a-e25d-423d-a1f2-871c384a1d72.jpg)

links to 

=> https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch (as above).

and to
=> https://www.bundesregierung.de/breg-en/service/contact
which is a general purpose contact page unrelated to the CWA app.

---

The information on
https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch (EN) covers updates to the CWA app up to Version 2.2, so it is quite out of date.

The information on
https://www.bundesregierung.de/breg-de/themen/corona-warn-app (DE) includes information about Version 2.13 
https://www.bundesregierung.de/breg-de/themen/buerokratieabbau/corona-warn-app-version-2-13-1974488.

## Summary

The [German language link](https://www.bundesregierung.de/breg-de/themen/corona-warn-app) could be useful since it is being fed with up-to-date information. The [English language link](https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch) on the other hand is out-of-date and less useful. It is probably not harmful though.

So I withdraw the question and suggest to make no changes from the FAQs to the pages of the Federal Government (Bundesregierung).
