### ISSUE TITLE
Image issues in FAQ #warn_for_others

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1939]
## Where to find the issue

- https://www.coronawarn.app/en/faq/#warn_for_others "How can I warn for others?"
- https://www.coronawarn.app/de/faq/#warn_for_others "Wie kann ich in Vertretung warnen?"

## Describe the issue

- The screenshot [warn_for_others2.png](https://www.coronawarn.app/assets/img/faq/warn_for_others2.png) does not fit the sequence of "warn for others". It shows "No QR codes created yet". An event organizer can only warn for others if a QR code has already been created, and the screenshot [warn_for_others2.png](https://www.coronawarn.app/assets/img/faq/warn_for_others2.png) does not match [warn_for_others3.png](https://www.coronawarn.app/assets/img/faq/warn_for_others3.png) which lists the event "Konzert".

- There are 6 iOS images link to the FAQ article [How can I warn for others?](https://www.coronawarn.app/en/faq/#warn_for_others) and the same for the German-language equivalent  [Wie kann ich in Vertretung warnen?](https://www.coronawarn.app/de/faq/#warn_for_others). The images taken from https://github.com/corona-warn-app/cwa-website/tree/master/src/assets/img/faq are very large - for the English images 1212 KB. This impacts the amount of data which is transferred every time a user opens the [FAQ page](https://www.coronawarn.app/en/faq/).

Filename | Size
--- | ---
[warn_for_others1.png](https://www.coronawarn.app/assets/img/faq/warn_for_others1.png) | 249 KB
[warn_for_others2.png](https://www.coronawarn.app/assets/img/faq/warn_for_others2.png) | 562 KB
[warn_for_others3.png](https://www.coronawarn.app/assets/img/faq/warn_for_others3.png) | 114 KB
[warn_for_others4.png](https://www.coronawarn.app/assets/img/faq/warn_for_others4.png) | 94 KB
[warn_for_others5.png](https://www.coronawarn.app/assets/img/faq/warn_for_others5.png) | 110 KB
[warn_for_others6.png](https://www.coronawarn.app/assets/img/faq/warn_for_others6.png) |  83 KB

- Only screenshots for iOS are shown, not for Android. It is not mentioned that the screenshots are only for iOS in the description.

- With the release of CWA 2.12 the tabs have changed, making the screenshot [warn_for_others1.png](https://www.coronawarn.app/assets/img/faq/warn_for_others1.png) out of date.

- The article refers to "CWA home page". This should be changed to align with other articles which use the text "the Status tab ('Start Screen' before version 2.12)".

## Suggested change

Alternatives:

1. Remove the images from the FAQ and link to the screenshots:
    - https://www.coronawarn.app/en/screenshots/#ios_warn_for_others and
    - https://www.coronawarn.app/en/screenshots/#android_warn_for_others

2. Update the images

---
For option 2 (updating the images):
    
- Replace the image with the out-of-date tabs ([warn_for_others1.png](https://www.coronawarn.app/assets/img/faq/warn_for_others1.png)) using a screenshot from CWA 2.12 and
- Reduce the size of the images appropriate for display in a web browser and
- Mention that the images are for iOS only and link to https://www.coronawarn.app/en/screenshots/#android_warn_for_others for Android images

---

My preference is for option 1: "Remove the images from the FAQ and link to the screenshots" since it is the one with the least work, it immediately solves the size problem and it ensures that the FAQ article will stay up-to-date with screenshots by linking to the current version of the appropriate screenshot page.

**Comment by larswmh** [comment]
This issue is resolved by PR #1941

**Comment by MikeMcC399** [comment]
@larswmh 

Thank you for fixing this issue!

All the points mentioned have been addressed.
