### ISSUE TITLE
🚨 BUG: "running-app.svg" image is broken

### ISSUE THREAD

**Issue by mojoaxel** [corona-warn-app/cwa-website#195]
## Where to find the issue
https://www.coronawarn.app/de/

## Describe the issue

The "running-app" image is broken:
![image](https://user-images.githubusercontent.com/600565/87575565-63ea0600-c6d0-11ea-8936-d5b0293915be.png)

## Suggested change
replace the image with a new one.

**Comment by mojoaxel** [comment]
this has been fixes with f9f188d0cd7e34b56e698e1188c55700dec33268

@tkowark I'm sorry for causing such big problems! I have no idea what went wrong with #194 ! I've testes the new svg in multible resolutions.

**Comment by tkowark** [comment]
yeah, me neither. Image is fixed now. Stranger than the image error are the huge delays until the action workflows are executed ...

**Comment by mojoaxel** [comment]
@tkowark It looks to me that a old version of the image was merged. As you can see in #194 the image should look complexly different. Maybe some old version of the branch has been merged.

**Comment by tkowark** [comment]
Yep, looks like it. I'll merge #194, and then we should be fine again 😀

Thanks again for all your great work on the website!

**Comment by tkowark** [comment]
PR is merged and now deployed - Image looks great :)
