### ISSUE TITLE
Plotly "Download plot as png" fails on science blogs

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1983]
## Where to find the issue

All science blogs on https://www.coronawarn.app/en/science/ and https://www.coronawarn.app/en/science/ using Plotly graphs.

## Describe the issue

The Plotly control "Download plot as png" fails.

### Steps to reproduce

1. Open https://www.coronawarn.app/en/science/2021-07-08-science-blog-2/#31-survey-participation in desktop web browser
2. Hover mouse over graph of Fig. 2, then
3. click on camera control icon
4. Note that the tool-tip shows "Download plot as png"
5. Click on camera control icon
6. Note that two messages appear:
Taking snapshot - this may take a few seconds, then
Sorry, there was a problem downloading your snapshot!

![Snapshot Plotly fail](https://user-images.githubusercontent.com/66998419/139387994-285fab4e-a021-4d31-8452-5328a6d59e7e.jpg)

## Expected

If a control icon to take a snapshot is shown, it should work and download a plot.

**Comment by brifemu** [comment]
I tested #1987 on Windows using nginx, and it works. I will create a VM running Ubuntu to test it.

**Comment by MikeMcC399** [comment]
@brifemu 
What about the comment on https://github.com/corona-warn-app/cwa-website/pull/1987#discussion_r739129249 from @svengabr:

> The CSP on live is set with headers from the webserver/cdn

Are you able to make that change and test it? I think that means nginx on AWS S3.

Also considering what @dsarkar wrote in https://github.com/corona-warn-app/cwa-website/issues/1792#issuecomment-946706638

> I assume from reading https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/deploy-master.yml that the website is hosted using AWS S3, so shouldn't you have access to the site data manually using AWS tools, like console?
>> ... We from the community team do not have access.

**Comment by brifemu** [comment]
@MikeMcC399 

That change is applied already

**Comment by brifemu** [comment]
@MikeMcC399 

The fix had been already merged. I replaced the blob download for a blob conversion to canvas, and later in an image, so we don't need to edit the CSP.

It had been tested on Windows 10 using the latest stable versions of Edge and Chrome, and on Mac using the latest stables versions of Safari and Chrome.

**Comment by MikeMcC399** [comment]
@brifemu

It's great that you found a solution!

1. On Google Chrome, if you have "Ask where to save each file before downloading" disabled (which I think is the default setting), then for a short time the error message "Sorry, there was a problem downloading your snapshot!" is shown, then it disappears and the image is correctly downloaded to the default download directory of the browser. This is a bit strange and I don't know if there is anything which can be done about this point.

2. Could you please check about the locale? In science blog 1 and 2 index.md (English source) there are figures with locale set to `de`. It should be `en` in the English language files. (This is a regression from https://github.com/corona-warn-app/cwa-website/issues/1982 which is closed now.)

**Comment by brifemu** [comment]
@MikeMcC399 

I'm gonna check it, thanks for your feedback!

**Comment by dsarkar** [comment]
@MikeMcC399 FYI PR #2039

**Comment by MikeMcC399** [comment]
@dsarkar 
Thanks to @matriceria for fixing this issue with #2039!

I checked in English and German. Both are fine!
