### ISSUE TITLE
App Code Image broken on Mobile 

### ISSUE THREAD

**Issue by tkowark** [corona-warn-app/cwa-website#199]
## Where to find the issue
https://www.coronawarn.app/de/ -> Scroll to "Mach mit beim Open Source Project"

## Describe the issue
On iPhones (at least iPhone 11 and iPhone 8) and Desktop Safari, the code in the image is weirdly formatted.

## Suggested change
Fix SVG rendering in Safari or find the magic formatting attribute or option in the SVG that causes the problems.

![IMG_1197](https://user-images.githubusercontent.com/164467/87760195-afef9480-c80f-11ea-81af-4481cd857549.PNG)

**Comment by mojoaxel** [comment]
I'll try to solve this.

**Comment by mojoaxel** [comment]
The problem is caused by the [xml:space="preserve"](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:space) attribute that is not wenn supported.
