### ISSUE TITLE
Timeout running Cypress test

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1993]
## Where to find the issue

https://github.com/corona-warn-app/cwa-website

## Describe the issue

Executing `npm test` will sometimes time out.

```text
Error: Timed out waiting for: http://localhost:8000
at ...\cwa-website\node_modules\wait-on\lib\wait-on.js:132:31````
```

According to https://github.com/bahmutov/start-server-and-test#readme

### "Timeout

This utility will wait for maximum of 5 minutes while checking for the server to respond (default). Setting an environment variable `WAIT_ON_TIMEOUT=600000` (milliseconds) sets the timeout for example to 10 minutes."

### Steps to reproduce

In terminal of clone of [cwa-website](https://github.com/corona-warn-app/cwa-website)
1. Execute `npm test`
2. Note that sometimes the following error message appears:
```text
Error: Timed out waiting for: http://localhost:8000
at ...\cwa-website\node_modules\wait-on\lib\wait-on.js:132:31
```
This seems to happen more often on the first run of `npm test` and on the second attempt it succeeds. This is sure to be dependent of the performance abilities of the host system (CPU, memory, etc.). 

## Current solution

Currently the script `npm test`
invokes `npm start` which causes:

```gulp
// Build the site, run the server, and watch for file changes
gulp.task('default', gulp.series('build', server, watch)); 
```
to run. The default timeout starts at the beginning of the build session, not at the beginning of the server start function call in gulp. As [cwa-website](https://github.com/corona-warn-app/cwa-website) has grown in size and complexity, the time to build the web has increased, so that the likelihood of timing out has now also increased.

## Workarounds

There are two immediate workarounds:
- increasing the timeout through an environment variable `WAIT_ON_TIMEOUT`
- separating build and Cypress start in two different terminal windows

See below for further details:

### Increase timeout through parameter

Create or edit `.bash_profile` in the user's home directory to increase the timeout from the default 5 minutes to 10 minutes.

Add
```
export WAIT_ON_TIMEOUT
WAIT_ON_TIMEOUT=600000
```
This sets an environment variable which will be used by [start-server-and-test](https://www.npmjs.com/package/start-server-and-test) and its use will show up in the log.

### Split build and test start

This is equivalent to `npm test`.

Execute:
`npm start`
in a terminal window and wait for a browser window with http://localhost:8000/en/ to open.

In a separate terminal window execute:
`npx cypress run -b chrome`

## Suggested change

Restructure the scripts so that the default timeout for [start-server-and-test](https://www.npmjs.com/package/start-server-and-test) starts running **after** the build has completed.

For instance:
- add a new task in `gulp.js` which only runs `server` and `watch`, not `build`
- modify the scripts in `package.json` so that the test scripts run the `build` task before running [start-server-and-test](https://www.npmjs.com/package/start-server-and-test) and this in turn only starts the server without building the server contents

**Comment by MikeMcC399** [comment]
I tried this out, however I don't really have the experience in `npm `and `gulp` to be sure to implement the suggested change cleanly, so I'd be happy for somebody else with the right skills to implement it (assuming that the suggestion is accepted).

I already used the workaround successfully in my own environment. That is a quick (temporary) solution.

**Comment by MikeMcC399** [comment]
There is another workaround to the timeout, which I will add to the main issue:

This is equivalent to `npm test`.

Execute:
`npm start`
in a terminal window and wait for a browser window with http://localhost:8000 to open

In a separate terminal window execute:
`npx cypress run -b chrome`

**Comment by MikeMcC399** [comment]
I changed my mind and I plan to submit a PR for this myself soon. Stand by!

**Comment by MikeMcC399** [comment]
I have submitted https://github.com/corona-warn-app/cwa-website/pull/1997 now which separates out the build process from the web server start and Cypress test. This avoids a timeout because the clock doesn't start counting down until the build process has completed.

I have tested it on Windows and I will test it also on Ubuntu next.

I would like to wait for PR https://github.com/corona-warn-app/cwa-website/pull/1996 from @brifemu to be merged first, so that there is a clean base of Cypress tests which all work before changing anything in the higher level build / test scripts.

**Comment by MikeMcC399** [comment]
PR #1997 is now tested and ready for review.

**Comment by MikeMcC399** [comment]
Unfortunately PR #1997 did not work on all Windows systems, although it was fine on Ubuntu, Mac and Windows 10 Home.

I am working on a replacement PR which is (hopefully!) platform independent.

**Comment by MikeMcC399** [comment]
PR #1997 did not work on all Windows environment because it needed the npm key `shell-script` to point to the bash shell executable.

The new PR #2067 is less stringent, however to successfully run the complete Cypress suite of tests defined in https://github.com/corona-warn-app/cwa-website/tree/master/cypress/integration it is still necessary to follow the instructions in https://github.com/corona-warn-app/cwa-website#cypress-under-microsoft-windows concerning setting the npm key `shell-script`, i.e. execute `npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"`.

This is because the https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/blog_spec.js script relies on executing `npm run test:prepare` first which will only run correctly in a bash shell. This is not a change from previously.

**Comment by MikeMcC399** [comment]
PR #2067 is now merged, which resolves this issue.

Note that anybody testing locally will need to run `npm ci` or `npm install` to update their Node package installation.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the PR and all the feedback!
