### ISSUE TITLE
Blog statement on cancelled and replaced weekly report needed

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#1994]
This follows on from the issue https://github.com/corona-warn-app/cwa-website/issues/1903.

## Where to find the issue

- https://www.coronawarn.app/en/blog/ and
- https://www.coronawarn.app/de/blog/

## Describe the issue

The blog statements regarding the weekly reports are out of date.

According to RKI ["Infektionsketten digital unterbrechen mit der Corona-Warn-App"](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html) the weekly report is retired and replaced by the ([Analysis](https://www.coronawarn.app/de/analysis/)) dashboard.

["Kennzahlen-Dashboard zur Corona-Warn-App"](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html?nn=13490888#doc14201188bodyText17)

![Kennzahlen-Dashboard zur Corona-Warn-App](https://user-images.githubusercontent.com/66998419/137714787-b44f1ab1-139b-4961-8dde-3b75d05d9244.jpg)

However the last blog statements from CWA do not reflect this change.

1. https://www.coronawarn.app/en/blog/2021-10-04-key-figures-dashboard/
"From now on, important key figures are also available in a public dashboard as an interactive overview."
"also available" implies that the previous reports will continue

2. https://www.coronawarn.app/en/blog/2021-10-01-facts-and-figures/
"In this post, you can find regularly updated facts and figures about the Corona-Warn-App, ..."
"regular updates" implies that there will be more in the future.

## Suggested change

Publish a CWA blog article to reflect the RKI statement:

"An die Stelle des wöchentlichen Übersichtsdokuments tritt nun ein öffentliches, interaktives Dashboard mit den wichtigsten Kennzahlen. Diese werden täglich aktualisiert."

(FAQ https://www.coronawarn.app/en/faq/#numbers_RKI has already been updated - see PR https://github.com/corona-warn-app/cwa-website/pull/1963.)

---
Internal Tracking ID: [EXPOSUREAPP-10259](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10259)

**Comment by dsarkar** [comment]
@MikeMcC399  Thanks. Internal Tracking ID: [EXPOSUREAPP-10259](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10259)

**Comment by MikeMcC399** [comment]
This should be solved when PR #2038 is published.

**Comment by MikeMcC399** [comment]
PR #2038 was withdrawn.

---

1. https://www.coronawarn.app/en/blog/2021-10-04-key-figures-dashboard/
"From now on, important key figures are also available in a public dashboard as an interactive overview."
"also available" implies that the previous reports will continue

Corrected by PR https://github.com/corona-warn-app/cwa-website/pull/2061

---

2. https://www.coronawarn.app/en/blog/2021-10-01-facts-and-figures/
"In this post, you can find regularly updated facts and figures about the Corona-Warn-App, ..."
"regular updates" implies that there will be more in the future.

Corrected by PR https://github.com/corona-warn-app/cwa-website/pull/2059
