### ISSUE TITLE
Blog: 2.13 article refers to trash instead of Recycle Bin (EN)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2007]
## Where to find the issue

https://www.coronawarn.app/en/blog/2021-11-03-cwa-version-2-13/ "Oops, certificate deleted? - Corona-Warn-App version 2.13 gets it back!"

from @HannaHei 

## Describe the issue 

The blog refers to both "recycle bin" and "trash" in the article.

The latest Android version of 2.13.x has renamed "trash" to "Recycle Bin", so the blog article should also only use the term "Recycle Bin" for Android.

Please check also for iOS.
See also https://www.coronawarn.app/en/faq/#cert_recycle_bin.

## Suggested change

Change references in https://github.com/corona-warn-app/cwa-website/blob/master/blog/2021-11-03-cwa-2-13/index.md from "trash" to "Recycle Bin".

## Related issue

https://github.com/corona-warn-app/cwa-website/issues/2006 "Screenshots: Trash now named Recycle Bin (EN)".

**Comment by Ein-Tim** [comment]
Reg. iOS, see: https://github.com/corona-warn-app/cwa-website/issues/2006#issuecomment-959299913

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for your comment that also in iOS the correct term is "Recycle Bin" not "trash".

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks. Issue is forwarded internally.

**Comment by MikeMcC399** [comment]
@dsarkar 
Thank you! It is good to see the @larswmh is getting the screenshots (as reference material) corrected in PR https://github.com/corona-warn-app/cwa-website/pull/2010.

**Comment by larswmh** [comment]
@MikeMcC399 FYI I just opened a PR to fix it

**Comment by MikeMcC399** [comment]
PR #2011 has fixed this issue and there is no longer a reference to "trash" in https://www.coronawarn.app/en/blog/2021-11-03-cwa-version-2-13/.

Thanks to @larswmh for this fix!
