### ISSUE TITLE
FAQ entry needed clarifying that it‘s normal that the Booster certificate is only set as the standard one after 14 days

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2012]
## Where to find the issue

n/a

## Describe the issue
Users are wondering why their booster certificates are not selected as the standard one directly after they added them to the app but only after 14 days.

Until now, I thought this was an issue, but seems like it isn't as [Corona-Warn-App notifies users about a booster vaccination](https://www.coronawarn.app/en/blog/2021-11-04-cwa-booster-notification/) says:

"The QR code of the booster vaccination is automatically displayed first in the certificate overview 14 days after the vaccination."

## Suggested change
Add a small FAQ entry reg. this. 

Example:

Title: 
"Wie kann ich das Zertifikat meiner Auffrischungsimpfung als aktives Zertifikat auswählen?"

Content:
"Das Zertifikat Ihrer Auffrischungsimpfung wird automatisch 2 Wochen nach der Impfung als aktives Zertifikat ausgewählt. Sie müssen nichts weiter tun und können bis dahin Ihren Impfstatus weiterhin mit dem aktuell aktivem Zertifikat nachweisen."

**Comment by Ein-Tim** [comment]
Example for confused user: https://twitter.com/day_bicycle/status/1456265876496257028?s=21

**Comment by dsarkar** [comment]
@Ein-Tim The  Regarding these users, is this a booster (2/2) on top of a 1/1-J&J or a 3/3-booster on top of a 2/2-vaccination?

**Comment by Ein-Tim** [comment]
@dsarkar 

I asked the user.
I guess the reason why you're asking is because if one received a "2/2" on top of a "1/1" the "2/2" should be selected as active instantly, but only get valid after 14 days, right?

**Comment by floscher** [comment]
@Ein-Tim With #4343 the "1/1" boosters (after recovery), the "2/2" Johnson&Johnson boosters and the "3/3" boosters will immediately become active in the CWA.

I can confirm that a "3/3" BioNTech booster is considered valid by CovPassCheck immediately after the vaccination.

**Comment by Ein-Tim** [comment]
@floscher 

Not sure about this. The OP of https://github.com/corona-warn-app/cwa-app-android/pull/4343 says that a J&J vaccination after a recovery will still get only active after 14 days.
Also, this does not cover the case when somebody who received J&J was boostered with Biontech and got a 2/2 certificate. 
In this case the "1/1" certificate stays as the active one: https://github.com/corona-warn-app/cwa-app-android/issues/4334

So I still think this should be covered in a FAQ entry.

**Comment by floscher** [comment]
@Ein-Tim Ah yes, didn't catch the J&J edge cases. Sure, this topic warrants an FAQ entry, because either way some people will get confused when the app either activates the certificate immediately or waits 14 days with activation when they expected it to do the other one of the two cases.

**Comment by Ein-Tim** [comment]
@floscher Yes exactly!

@dsarkar Could you maybe give us an update here? Is a FAQ entry planned?

**Comment by dsarkar** [comment]
Dear @floscher @Ein-Tim. So far we have this text. What do you think?

Dieser Fall kann eintreten, wenn eine Grundimmunisierung mit dem Impfstoff von Johnson & Johnson erfolgte. Da für eine Grundimmunisierung mit dem Janssen-Impfstoff nur eine Impfung nötig ist, muss im Impfzertifikat für die Auffrischungsimpfung unter "Nummer der Impfung" der Eintrag "2 von 2" vorgenommen werden. 

Bei der Grundimmuniserung mit anderen Impfstoffen als J&J, wie z.B. BioNTech, Moderna, oder AstraZeneca, wird die zweite Dosis ebenfalls unter "Nummer der Impfung" der Eintrag "2 von 2" vorgenommen. Solchen Impfungen setzen für gewöhnlich eine Wartezeit von 14 Tagen bis zum vollständigen Impfschutz nach der 2. Dosis der Grundimmunisierung voraus.

 Das hat zur Folge, dass Prüf-Apps, wie die CovPassCheck-App daher in diesem speziellen Fall nicht unterscheiden können, ob es sich um eine Auffrischimpfung für eine Jannsen-Grundimmunisierung oder um die zweite Dosis der Grundimmunisierung handelt. Daher wird das Impfzertifikat für die Auffrischungsimpfung für 14 Tage als ungültig angezeigt, wenn vorher eine Impfung mit dem Janssen-Impfstoff durchgeführt wurde und in dem Zertifikat der Auffrischimpfung 2 von 2 notiert wurde. 

Andererseits wird bei einer vorangegangenen Grundimmunisierung durch zwei Dosen die Auffrischungsimpfung als die 3. von 3 Impfungen deklariert. Durch den Eintrag "3 von 3" erkennt die App die Auffrischungsimpfung korrekt als solche an und es entfällt die Anzeige der 14 Tage Wartezeit bis zum vollen Impfschutz. 

Als Nachweis können Sie für diese 14 Tage weiterhin Ihr Impfzertifikat für die Grundimmunisierung vorzeigen. Dieses behält seine Gültigkeit, sofern die technische oder fachliche Gültigkeit nicht abgelaufen ist.

**Comment by Ein-Tim** [comment]
@dsarkar 

This sounds really good to me! 

One case which should be added: 
Second booster after recover (yes, some people really do already get this!)

Thanks for your efforts!

**Comment by larswmh** [comment]
In the PR that is linked above my comment, I've added an FAQ entry containing @dsarkar's suggested text and @Ein-Tim's suggested case that should be added.

**Comment by Ein-Tim** [comment]
@larswmh 

Thank you very much! I will take some time later and review the PR (-:

**Comment by Ein-Tim** [comment]
This issue is solved with https://www.coronawarn.app/en/faq/#vac_booster_jj & https://www.coronawarn.app/de/faq/#vac_booster_jj.

Closing as fixed.
