### ISSUE TITLE
Links to rki vaccination page in Booster blog

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2013]
## Where to find the issue

- https://www.coronawarn.app/en/blog/2021-11-04-cwa-booster-notification/ "Corona-Warn-App notifies users about a booster vaccination"
    - linking to https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/Impfempfehlung-Zusfassung.html "STIKO-Empfehlung zur COVID-19-Impfung"

- https://www.coronawarn.app/de/blog/2021-11-04-cwa-booster-notification/ "Corona-Warn-App informiert zu Booster-Impfungen"
    - linking to https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/COVID-19.html "COVID-19 und Impfen"

## Describe the issue

The English and German blog pages for booster vaccinations link to different RKI pages. 
    - The [English booster blog](https://www.coronawarn.app/en/blog/2021-11-04-cwa-booster-notification/) links to [STIKO-Empfehlung zur COVID-19-Impfung](https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/Impfempfehlung-Zusfassung.html)
    - The [German booster blog](https://www.coronawarn.app/de/blog/2021-11-04-cwa-booster-notification/) links to [COVID-19 und Impfen](https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/COVID-19.html)

## Suggested change

1. Decide which of the RKI pages should be linked to and use the same link on both the English and the German versions of the blog.

**Comment by MikeMcC399** [comment]
The second point concerning the jsessionid is addressed in PR #2057.

@HannaHei should probably look at whether the English and German blog pages should link to different RKI pages. This part of the issue is still open.

**Comment by MikeMcC399** [comment]
The page [COVID-19 und Impfen](https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/COVID-19.html) used in the  [German booster blog](https://www.coronawarn.app/de/blog/2021-11-04-cwa-booster-notification/) does link to [STIKO-Empfehlung zur COVID-19-Impfung](https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/Impfempfehlung-Zusfassung.html), however this makes it more complicated for a user to find the related information.

## Suggested change

In [German booster blog](https://www.coronawarn.app/de/blog/2021-11-04-cwa-booster-notification/):  https://www.coronawarn.app/de/blog/2021-11-04-cwa-booster-notification/

change the link from

[COVID-19 und Impfen](https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/COVID-19.html)

to 

[STIKO-Empfehlung zur COVID-19-Impfung](https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/Impfempfehlung-Zusfassung.html)

This would then be the same as the English blog post.

**Comment by MikeMcC399** [comment]
There haven't been any comments about this issue so far. 

Changing the link in the German blog so it points to the same link as in the English blog would make it easier for German readers to find the relevant information.

If this is not wanted, then please let me know, otherwise I will go ahead with PR submission,

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Will check this.

**Comment by MikeMcC399** [comment]
@dsarkar 
> Will check this.

Thanks for picking this up. I will wait in that case. 

I was triggered again on this subject by @svengabr's new issue https://github.com/corona-warn-app/cwa-website/issues/2162.

**Comment by MikeMcC399** [comment]
@dsarkar 
You wrote at the beginning of December 2021 that you would check the suggestion, however I didn't see any further feedback.

I believe the suggested change makes sense, so I have submitted the PR #2306 to implement this small change in the link.

**Comment by MikeMcC399** [comment]
- This issue is resolved through PR #2306.
