### ISSUE TITLE
Analysis page shows outdated data

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2024]
## Where to find the issue
- https://www.coronawarn.app/de/analysis/

## Describe the issue
The following figures on https://www.coronawarn.app/de/analysis/ are out of date:
- Downloads (last data from 04.11.2021)
- Registriere Tests (last data from 02.11.2021)
- Teilungsverhalten (last data from 02.11.2021)

## Suggested change
Update the data.

**Comment by MikeMcC399** [comment]
@dsarkar 

The data feed for:

- Registrierte Tests and
- Teilungsverhalten

is still blocked.

![image](https://user-images.githubusercontent.com/66998419/140755632-cabd02c2-3cd6-454b-986e-ac5515385edb.png)

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Yes, TSI is looking at it right now.

One can see the issue in https://obs.eu-de.otc.t-systems.com/obs-public-dashboard/json/v1/nested_cwa_public_dashboard_data.json. 
Date in this file is shown on the dashboard.

Screenshots from left to right show 2.11., 3.11., 7.11. (marked are the  "Downloadzahlen", which are updated)

From  3.11. on, there are missing numbers (null) in the json file.
Up to date:
- Downloads 
- Empfangene Warnungen
Not up to date:
- Registrierte Tests
- Teilungsverhalten

![image](https://user-images.githubusercontent.com/1409741/140787993-0f619008-5191-4e1f-a08a-00040b3313e9.png)

**Comment by MikeMcC399** [comment]
@dsarkar 

Thanks for the link to https://obs.eu-de.otc.t-systems.com/obs-public-dashboard/json/v1/nested_cwa_public_dashboard_data.json!

You can also see the pattern of missing data in https://obs.eu-de.otc.t-systems.com/obs-public-dashboard/csv/cwa_all_data.zip (use the "Alle Daten exportieren Button on https://www.coronawarn.app/de/analysis/).

The .json file is a bit easier to read but maybe that's just a personal preference.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
The data is now appearing up to date again.

**Comment by Ein-Tim** [comment]
I can confirm that this issue has been fixed. 
As of now, 09.11.2021, 20:45h, all data on the analysis page is available, up to yesterday (this is intended).

Here is a screenshot from the page:
![Bildschirmfoto 2021-11-09 um 20 47 55](https://user-images.githubusercontent.com/67682506/140994284-9c8bf377-006c-404a-b8bb-040607888a8f.png)

---

Thanks to @MikeMcC399 for informing me that this issue has been fixed!

---

Closing as fixed.
