### ISSUE TITLE
`ios_cards` & `android_cards` screenshots are out of date

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2026]
## Where to find the issue
- https://www.coronawarn.app/en/screenshots/#android_cards
- https://www.coronawarn.app/de/screenshots/#android_cards
- https://www.coronawarn.app/en/screenshots/#ios_cards
- https://www.coronawarn.app/de/screenshots/#ios_cards

## Describe the issue
The screenshots showing the high risk detail card are out of date. Compare the screenshot
https://www.coronawarn.app/assets/screenshots/2-13/de/ios/iPhone%2013-details_screen_risk_level_high_risk_one_day_active_tracing_5days_0001.png to one taken from the app:
<img src="https://user-images.githubusercontent.com/67682506/140608610-194e4f89-6b65-4359-b617-11cd1b73d647.png" width="300">

As you can see, the sentence "Weitere Informationen zu Ihren Risiko-Begegnungen finden Sie in Ihrem Kontakt-Tagebuch." is missing.

## Suggested change
Update the screenshots.

## Related Issue
- #1881

**Comment by Crystalskulls** [comment]
@Ein-Tim the related Issue is already closed and the screenshots are up to date, so i think this Issue can be closed.

**Comment by Ein-Tim** [comment]
@Crystalskulls 

Thanks, you're right! 

There's a mix of iOS & Android screenshots in the section, but this is another issue.
