### ISSUE TITLE
Problem with site menu on analysis page

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2028]
## Where to find the issue
- https://www.coronawarn.app/de/analysis/

## Describe the issue
If one opens the page menu on the [analysis page](https://www.coronawarn.app/de/analysis/), the headers of the figures are still shown:

https://user-images.githubusercontent.com/67682506/140613037-da8ebf47-aba9-4ab5-87d3-6494f06d60ac.MOV

## Suggested change
Fix the bug (Maybe the background of the menu has an incorrect color assigned to it?).

**Comment by dsarkar** [comment]
@Ein-Tim  FYI PR https://github.com/corona-warn-app/cwa-website/pull/2036

**Comment by Ein-Tim** [comment]
Works flawless now!

Thanks @matriceria & @dsarkar!

Closing as fixed.
