### ISSUE TITLE
Analysis background buttons do not resize

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2029]
## Where to find the issue

https://www.coronawarn.app/de/analysis/

## Describe the issue

Button background of Analysis data display modes does not resize when window resizes. Background may cause overlap or truncation of data display labels.

### Steps to reproduce

In Google Chrome on desktop.
Zoom is 100%
1. Open browser in full screen size.
2. Open https://www.coronawarn.app/de/analysis/
3. Reduce to minimum width
4. Note that background of "Täglich" overlaps with "Wöchentlich" label
5. Refresh (F5)
6. Note that "Täglich" is now correct
7. Expand browser window to maximum width
8. Note that Täglich is now displayed truncated as "Täglic". 

Browser reduced to minimum width:

![Analysis minimum width](https://user-images.githubusercontent.com/66998419/140614967-8e9203ad-f77d-4811-b7aa-7d8d659e6097.jpg)

Browser expanded to maximum width:

![Analysis maximum width](https://user-images.githubusercontent.com/66998419/140614971-08d6343d-b673-4350-8741-e6378ad90a9a.jpg)

**Comment by dsarkar** [comment]
@MikeMcC399 FYI PR https://github.com/corona-warn-app/cwa-website/pull/2037

**Comment by MikeMcC399** [comment]
Solved with PR #2037! Thank you @matriceria / @dsarkar !
