### ISSUE TITLE
Which versions to describe in FAQs?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2032]
This is a follow-on to the stale issue https://github.com/corona-warn-app/cwa-website/issues/971 "FAQ - Remove outdated information from FAQ and review existing entries 🔧" where the question was raised about which versions of CWA are supported and which need to be described in the current FAQs.

The FAQ descriptions have in some cases become quite complicated and difficult to read if they need to cover all past versions where many incremental changes have taken place over time.

**Perhaps there could be a decision to restrict the number of previous versions covered by the FAQs e.g. only the latest version and the previous version?**

This may also affect the screenshot versions shown.

There has already been one forced update (see https://github.com/corona-warn-app/cwa-app-android/issues/4270). All Android users of 2.11 were forced to update to 2.12. According to https://github.com/corona-warn-app/cwa-app-android/issues/4263#issuecomment-956033746 forced updates is an on-going topic. 

If there is a general forced update in the future which sets a de facto minimum version in use for Android and iOS, then that would also be a good reason to adjust the FAQs accordingly.

Can there be a decision about which versions to continue to describe in the FAQs? The question is addressed to the Open Source Team.

---
[EXPOSUREAPP-14338](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14338)

**Comment by Ein-Tim** [comment]
There has been no response to this issue in over 4 months. Please take care of it @open-source-team.

**Comment by MikeMcC399** [comment]
CWA Android version 3.0 is being prepared as the next version for release, so I would like to raise this topic again about which versions the FAQs need to support and described.

I would suggest deciding about an official End-of-Life (EOL) for CWA 1.x which would mean that the FAQs would no longer need to consider this version.

Some FAQs could be simplified if 1.x no longer needs to be described.

Is there any planning also for the EOL of the complete CWA app? I guess there are political, legal, contractual and epidemiological issues to consider for this aspect.

**Comment by brianebeling** [comment]
Thanks for your feedback, I will raise the topic internally in an upcoming meeting and hopefully come back with a definite answer.

---
[EXPOSUREAPP-14338](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14338)

**Comment by brianebeling** [comment]
Considering there has been a force update (at least on Android and that I'm aware of) it would make much sense to restrict the FAQ. It'd be really helpful if we could compile some examples of rough FAQ entries due to the versioning. Especially extremes would be very interesting.

**Comment by Ein-Tim** [comment]
@brianebeling 

Which version was the update forced to?

**Comment by MikeMcC399** [comment]
The enforced minimum app versions are currently:

Android | iOS
--- | ---
1.0.4 | 1.5.3

- I asked for clarification in https://github.com/corona-warn-app/cwa-server/issues/1962 since I expected to see CWA Android 1.5.1 as the minimum version in `app_config` delivered to the app.

- If Android and iOS align on 1.5 as the minimum version, then I suggest to clean up any information in the FAQ which is only relevant for versions 1.0 to 1.4 as a first step in reducing the FAQ complexity. That would probably better be tracked in a separate issue to avoid overloading this one.

- For the moment, wait and see!

**Comment by MikeMcC399** [comment]
So now we have confirmation about the minimum CWA app versions:

Android | iOS
--- | ---
1.0.4 | 1.5.3

I will take a look at this and submit a separate issue.

**Comment by brianebeling** [comment]
Hey @MikeMcC399 

I got feedback from the developers regarding this issue, confirming your findings of the minimum app versions.

Generally speaking 1.X doesn't need to be described in detail, if information is missing. Barely anyone - if anyone - is using such old versions. Definitely not below 1.0.4 (android) and 1.5.3 (iOS). Going forward we'd suggest focusing on 2.X. If there is an obvious mistake with the older versions or an urgent topic we should take care of that, otherwise improving current topics and the general quality of the FAQ has precedence. 

Thanks for raising the topic again, hopefully that answers your question. Let me know if you have additional questions!

**Comment by MikeMcC399** [comment]
@brianebeling 

Thank you for getting the developers' feedback. Your answer is fine.

Would you like to consider merging PR #3238? This just removes information which is no longer needed because it refers to problems which can no longer occur using the supported versions.

I think in any case that this issue can be closed since the question is answered.

**Comment by MikeMcC399** [comment]
Thanks again to  @brianebeling! Closing this issue.

- The issue https://github.com/corona-warn-app/cwa-website/issues/3238 is open
