### ISSUE TITLE
Misleading FAQ statement regarding personal data collection with luca

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2070]
## Where to find the issue

- https://www.coronawarn.app/en/faq/#check_in_luca "The most important questions about joint use of luca-QR-Codes"
    - "12. Is the data of the users of the Corona-Warn-App still secure?"

![Luca 12 EN](https://user-images.githubusercontent.com/66998419/141499045-cb40b45c-6ce7-44c0-af8f-eaf667a951e2.jpg)

- https://www.coronawarn.app/de/faq/#check_in_luca "Die wichtigsten Fragen zur Mitnutzung der luca-QR-Codes"
    - "12. Sind die Daten der Nutzenden der Corona-Warn-App weiterhin sicher?"

![Luca 12 DE](https://user-images.githubusercontent.com/66998419/141499088-8203f8eb-7cd6-422a-ac2c-11872a5ac756.jpg)

## Describe the issue

The statement in the FAQ [The most important questions about joint use of luca-QR-Codes](https://www.coronawarn.app/en/faq/#check_in_luca) in "12. Is the data of the users of the Corona-Warn-App still secure?" which says:

"For the CWA, it still applies that it does not collect any personal data."

is not true unless it is qualified. The app **may** collect and hold personally identifiable information, such as from EU digital COVID certificates.

## Suggested change

Perhaps change the statement to say that scanning a luca-QR-Code does not cause any **addtional** personal data to be collected?

Also, it might be helpful to have the [Privacy notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) extended to explicitly mention the integration of third-party event codes.

## Reference

The [Privacy notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) "5. What data is processed?" mentions cases of where personal data is collected and stored.

**Comment by browkin** [comment]
@MikeMcC399 Thanks!
The PR : https://github.com/corona-warn-app/cwa-website/pull/2200

**Comment by MikeMcC399** [comment]
@browkin 
Thanks for PR #2200! When that is merged we can close this issue.

**Comment by MikeMcC399** [comment]
- PR #2200 

is now merged, so closing this issue.

---
I'm not sure why PR #2200 is not showing up automatically in the issue history, as usually when an issue is mentioned in a PR then GitHub will automatically link it and show the status. Putting it in a list (as above) serves the same purpose though.
