### ISSUE TITLE
Misleading description of number of "Empfangene Warnungen"

### ISSUE THREAD

**Issue by OlympianRevolution** [corona-warn-app/cwa-website#2084]
## Where to find the issue
https://www.coronawarn.app/en/analysis/
Plot Empfangene Warnungen

## Describe the issue
Neither the plot subtitle nor the info text mention that this is a lower bound. It is a lower bound since the number of warnings given is only known for participants of PPA.(about half of users)

## Suggested change
I would change the title from:
"Empfangene Warnungen"
To:
"Mindestanzahl empfangener Warnungen"
AND
Change the text "Gesamt (Anzahl bis gestern" to "Gesamt (Mindestsumme aus Daten der freiwilligen Datenspende)" or similar

AND OR

Change the info text from:
"Empfangene Warnungen
Anzahl roter und grüner Risikowarnungen sowie deren Summe in der Corona-Warn-App."
To:
"Mindestanzahl Empfangener Warnungen
Anzahl roter und grüner Risikowarnungen bei Teilnehmern der PPA sowie deren Summe in der Corona-Warn-App." or similar

**Comment by MikeMcC399** [comment]
@OlympianRevolution

Thanks for your suggestion!

I agree that it should be clearer for "Empfangene Warnungen" what this really means.

I suggest changing the title displayed on the graph to
"Empfangene Warnungen (nur Datenspende)"

and in the ℹ️ Info text explain that these warnings are only collected from users who have enabled in the app to share data (German: Datenspende), currently approximately half of users. 

Casual readers may not understand the significance of the text:

**Datenquellen**
Privacy-Preserving-Analytics (PPA)

---
The science blog https://www.coronawarn.app/de/science/2021-10-15-science-blog-4/#2-das-wichtigste-in-k%C3%BCrze-zahlen-daten-fakten says:

- Täglich spenden etwa 12 Mio. Nutzende ihre Daten (insgesamt gibt es 9.638.099.766 Datensätze).
- Der Anteil der Datenspendenden liegt bei etwa 49%.

which is completely in agreement with your statement about the data coming from about half of users. This puts the data into perspective.

**Comment by Ein-Tim** [comment]
#2169 will fix this.

**Comment by MikeMcC399** [comment]
@OlympianRevolution 

The texts you referred to have now been changed:

- https://www.coronawarn.app/en/analysis/ "Warnings received by data donors"
- https://www.coronawarn.app/de/analysis/ "Von Datenspendenden empfangene Warnungen"

"**Warnings received by data donors** (EN)

Count of red and green risk warnings as well as the sum of both risk warnings received by data donors in the Corona-Warn-App."

"**Von Datenspendenden empfangene Warnungen** (DE)

Anzahl der von Datenspendenden in der Corona-Warn-App empfangenen roten und grünen Risiko-Warnungen sowie deren Summe."

---

The author of the changes didn't follow your suggestions to label the data as lower bound, but I think that the labels and descriptions are now clear.

If you are happy with the changes, perhaps you would like to close this issue now?

**Comment by OlympianRevolution** [comment]
Sure, if it was decided it is clear enough.
