### ISSUE TITLE
FAQ: Warum wird der QR-Code von der Corona-Warn-App nicht gescannt? Warum reagiert der QR-Code-Scanner nicht?

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#2087]
**DE**

**Warum wird der QR-Code von der Corona-Warn-App nicht gescannt?
Warum reagiert der QR-Code-Scanner nicht?**

Auf einigen Geräten erkennt die Kamera den QR-Code nicht sofort und es passiert zunächst gar nichts, d.h. es wird weder der QR-Code eingelesen noch eine Fehlermeldung angezeigt. Dieses Verhalten betrifft vorrangig einige Android-Geräte, kann jedoch auch auf iOS-Geräten auftreten.

Folgende Tipps helfen oft dabei, den QR-Code zu scannen:
- Auf dem QR-Code erkennen Sie 3 größere Quadrate in den Ecken: Diese müssen vollständig von der Kamera erfasst werden.
- Halten Sie die Kamera etwas weiter vom QR-Code weg, bis er in etwa die Größe einer Briefmarke hat.
- Sorgen Sie für ausreichende Kontraste und Lichtverhältnisse.
- Drehen Sie den QR-Code um 90 Grad und versuchen Sie es erneut.

Alternativ können Sie auch folgendes versuchen:
Erstellen Sie ein Foto von Ihrem QR-Code und importieren Sie diese Datei in die Corona-Warn-App, indem Sie in dem QR-Code-Scanner „Datei öffnen“ wählen.

**Comment by DerVogel2020** [comment]
Muss sowas wirklich in die FAQ? 
Wie man einen QR Code scannt betrifft schließlich alles QR Code Scanner und alle QR Codes.

**Comment by Ein-Tim** [comment]
@DerVogel2020 

Ich vermute mal der Artikel wird wegen https://github.com/corona-warn-app/cwa-app-android/issues/3514 hinzugefügt.
