### ISSUE TITLE
FAQ: #check_in_luca_error

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#2088]
New FAQ:
- **DE** https://www.coronawarn.app/de/faq/#check_in_luca_error 
- **EN** https://www.coronawarn.app/en/faq/#check_in_luca_error

To be covered:

- private luca QR codes
- outdated luca QR codes, generated before 25 May
- luca QR codes generated after 25 May, but not CWA compatible
- "Faulty" luca QR codes, see https://github.com/corona-warn-app/cwa-website/pull/2069

Related:
https://github.com/corona-warn-app/cwa-wishlist/issues/680
https://github.com/corona-warn-app/cwa-website/pull/2069
https://github.com/corona-warn-app/cwa-documentation/issues/741

---
Internal Tracking ID: [EXPOSUREAPP-10564](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10564)
Internal Tracking ID: [EXPOSUREAPP-10617](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10617)

**Comment by MikeMcC399** [comment]
@dsarkar 

- Is this issue now obsolete given https://github.com/corona-warn-app/cwa-website/issues/2751?
