### ISSUE TITLE
Rollout state for Android 2.13.3?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2090]
Is CWA Android 2.13.3 completely rolled out and available for all users from the [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp)?

https://www.coronawarn.app/en/blog/2021-11-15-cwa-recalled-vaccination-certificates/ did not mention any 48 hour rollout and for me it was immediately available on https://play.google.com/store/apps/details?id=de.rki.coronawarnapp.

![image](https://user-images.githubusercontent.com/66998419/142039363-650d6b02-0872-4865-a3c6-eeb3b1177a14.png)

**Comment by dsarkar** [comment]
@MikeMcC399 roll out startet 15. Nov 1322 with 10% and finished 16 Nov 1754 with 100%

**Comment by MikeMcC399** [comment]
@dsarkar 

Thank you very much for the information! The user for issue #4327 "Wrong federal state for some cities on 7 days incidence cards, affects "Thuringia" / "Thüringen" only" confirmed now that they received the new version and could confirm also closure of that issue.

Since this question is now answered, I will close it.
