### ISSUE TITLE
FAQ: scan_tips

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#2093]
Anchor: #scan_tips
Section: #most_asked

**DE**

Warum wird der QR-Code von der CWA nicht gescannt?
Warum reagiert der QR-Code-Scanner nicht?

Auf einigen Geräten erkennt die Kamera den QR-Code nicht sofort und es passiert zunächst gar nichts, d.h. es wird weder der QR-Code eingelesen, noch eine Fehlermeldung angezeigt. Dieses Verhalten betrifft vorrangig einige Android-Geräte, kann jedoch auch auf iOS-Geräten auftreten.

Folgende Tipps helfen oft dabei, den QR-Code zu scannen:

- Auf dem QR-Code erkennen Sie 3 größere Quadrate in der Ecke: Diese müssen vollständig von der Kamera erfasst werden.
- Halten Sie die Kamera etwas weiter vom QR-Code weg, bis er in etwa die Größe einer Briefmarke hat.
- Sorgen Sie für ausreichende Kontraste und Lichtverhältnisse.
- Drehen Sie den QR-Codes um 90 Grad und versuchen Sie es erneut.

Alternativ können Sie auch folgendes versuchen: Erstellen Sie ein Foto oder einen Screenshot von Ihrem QR-Code und importieren Sie diese Datei, in dem Sie im QR-Code-Scanner „Datei öffnen“ wählen.

**EN**

Why does the CWA not scan a QR code? 
Why does the QR code scanner not respond?

On some devices, the camera does not recognize the QR code immediately and nothing happens at first, i.e. neither the QR code is scanned nor an error message is displayed. This behavior primarily affects some Android devices, but can also occur on iOS devices.

The following tips often help to scan the QR code: 
- On the QR code, you will see 3 larger squares in the corner: these must be fully captured by the camera.
- Hold the camera a little further away from the QR code until it is about the size of a postage stamp.
- Make sure there is sufficient contrast and lighting conditions.
- Rotate the QR code 90 degrees and try again.
 
Alternatively, you can try the following: Create a photo/screenshot of your QR code and import this file by selecting "Open File" in the QR code scanner.

**Comment by Ein-Tim** [comment]
@dsarkar 

Will you close #2087? Or is this a separate issue?
