### ISSUE TITLE
Remove duplicate content from robots.txt

### ISSUE THREAD

**Issue by uniquoo** [corona-warn-app/cwa-website#21]
## Where to find the issue
cwa-website/src/root-assets/robots.txt

## Describe the issue
It is not necessary to declare the /sitemap.htm again if the root directory is already within the allowed path.

## Suggested change

@@ -1,4 +1,3 @@
 User-agent: *
 Allow: /
-Allow: /sitemap.htm
 Sitemap: https://coronawarn.app/sitemap.xml

**Comment by SebastianWolf-SAP** [comment]
Issue fixed with #24
