### ISSUE TITLE
Update the Blog Post „Explanation of the statistic tiles in the Corona-Warn-App“ to include the newest statistic card

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2102]
## Your Question
* Website URL Path: https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/
* Question: The blog post "[Explanation of the statistic tiles in the Corona-Warn-App](https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/)" is referenced from the statistics info screen in the app with the sentence 
"For more details about the content of the individual key figures, read our [blog](https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/)."
I, as a user, would expect to get information about all key figures in the blog, and not only 4 of them. 
Thus, I ask me the question whether the blog post should be extended, to also cover statistic cards which were added after the blog was published. 

---
Internal Tracking ID: [EXPOSUREAPP-13577](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13577)

**Comment by MikeMcC399** [comment]
Also the FAQ:

- EN: https://www.coronawarn.app/en/faq/#further_details "In-App statistics starting with release 1.11"
- DE: https://www.coronawarn.app/de/faq/#further_details "In-App Statistiken ab Release 1.11"

is quite out of date, as already discussed in your issue https://github.com/corona-warn-app/cwa-website/issues/1497.

**Comment by Ein-Tim** [comment]
@dsarkar Please, could you take care of this issue?

**Comment by Ein-Tim** [comment]
@dsarkar / @larswmh will someone from the team eventually come back to this issue? Or is it forever forgotten? :D

**Comment by Ein-Tim** [comment]
@larswmh Please, could you come back to this item?

**Comment by larswmh** [comment]
@Ein-Tim @MikeMcC399 

We think that editing content of a blog contradicts the basic idea of a blog. Many blogs would have to be revised, since they deal with past events in the present tense with words like "now", etc. Due to the release date of the blog article that is always displayed, the reader should be aware that the information might be outdated. For the FAQ however, this is not the case. We agree that this would need an update and have forwarded it internally.

**Comment by Ein-Tim** [comment]
@larswmh I only asked for this blog, as it is linked to from the app. If you don't plan to update the blog, you should consider changing the app link.

**Comment by larswmh** [comment]
@Ein-Tim 

We have now created an internal ticket for this issue, as there is action required in our opinion as well. Thanks for bringing this up.

---
Internal Tracking ID: [EXPOSUREAPP-13577](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13577)

**Comment by MikeMcC399** [comment]
@larswmh 

Based on your feedback:

>We think that editing content of a blog contradicts the basic idea of a blog. Many blogs would have to be revised, since they deal with past events in the present tense with words like "now", etc. Due to the release date of the blog article that is always displayed, the reader should be aware that the information might be outdated. For the FAQ however, this is not the case. We agree that this would need an update and have forwarded it internally.

and

> We have now created an internal ticket for this issue, as there is action required in our opinion as well. 

- Is it the FAQ article [#further_details](https://www.coronawarn.app/en/faq/#further_details) which you will update? In that case perhaps this issue is better tracked through https://github.com/corona-warn-app/cwa-website/issues/1497?

- If the blog article will not be changed then this issue (https://github.com/corona-warn-app/cwa-website/issues/2102) should be closed.

**Comment by MikeMcC399** [comment]
I don't know if there is an easy answer to this issue.

- Blogs are one-time news articles that don't get updated (apart from maybe removing dead links or correcting small mistakes).
- FAQs are short articles providing some additional explanation for topics which are not covered by in-app descriptions.

The detailed statistics explanations don't fit into either of these categories.

It really needs a new website category "Documentation", which would be posted in German and English. Adding extra information into the app instead would be nice for users, but it would mean that everything needs to be translated into each of the app languages (German => English, Turkish, Bulgarian, Polish, Romanian & Ukrainian).

It's probably too late in the game to make such an enhancement, so I guess we have to live with the explanations in
- https://www.coronawarn.app/en/faq/#further_details plus
- https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/ combined.

**Comment by GisoSchroederSAP** [comment]
For quite a while we have been thinking about what key values and statistics [w|c]ould be helpful in tackling the pandemic and would be valuable for the users of the app.
After the release of the first statistic tiles with basic metrics in CWA, there were a number of suggestions for additional indicators; in particular, support of local incidence numbers was requested.
For all those statistics, not only we had to find reliable data sources, but the data also had to be prepared, validated and aggregated before it could be presented in the CWA. Finally, the pandemic radar was added to provide users with even more comprehensive information. 
In the meantime, interest in numbers, data and facts has clearly waned. In addition, there are at least three groups of people: Those who are interested in just such figures, those who generally think these figures are suspicious, and a considerable share of the population who don't care at all about these statistics.

With respect to the current situation, where measures are being withdrawn and where there are no longer any controls or consequences, these statistics also no longer have any function as a guide.

Therefore, we decided not to document any more statistics tiles but to focus now on providing a description of the new functions.

If this is acceptable, please close this issue as well. If there are specific questions to the one or the other KPI in our statistics, please let us know and we will provide a specific answer.
