### ISSUE TITLE
Data feed to Analysis page interrupted

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2109]
## Where to find the issue

- https://www.coronawarn.app/en/analysis/ "Corona-Warn-App (CWA): Key performance indicators"
- https://www.coronawarn.app/de/analysis/ "Corona-Warn-App (CWA): Kennzahlen"

## Describe the issue

1. The timestamp on https://www.coronawarn.app/en/analysis/ is from yesterday:
"_Last data update: November 21, 2021, 9:21 AM GMT+1. The data of the CWA dashboard is updated on a daily basis at 10:30 AM._"
Although the text says it is updated daily at 10.30 AM, this has not happened.

2. The last update for "Downloads" is from Thursday, November 18, 2021. The data for Nov 19 and Nov 20 is missing.

![image](https://user-images.githubusercontent.com/66998419/142854875-24e13b28-dfb5-4f59-9870-09dedab4f55f.png)

## Suggested change

Research the data provisioning on the T-Systems server:
https://obs.eu-de.otc.t-systems.com/obs-public-dashboard/json/v1/nested_cwa_public_dashboard_data.json

**Comment by dsarkar** [comment]
@MikeMcC399 Seems updated now.
![image](https://user-images.githubusercontent.com/1409741/142899853-fbf82132-cc61-46dd-9d48-0f9cb640abfd.png)

**Comment by MikeMcC399** [comment]
@dsarkar 

Yes, thank you. It all looks good now. 👍🏻 

"Last data update: November 22, 2021, 11:51 AM GMT+1. The data of the CWA dashboard is updated on a daily basis at 10:30 AM."

**Comment by MikeMcC399** [comment]
@dsarkar 

The analysis page has not updated at the displayed planned time today, so I am re-opening.

https://www.coronawarn.app/en/analysis/ displays:

"Last data update: November 22, 2021, 11:51 AM GMT+1. The data of the CWA dashboard is updated on a daily basis at 10:30 AM."

Today is Nov 23, 2021, and the time is 12:48 PM so I would expect the page to have already updated and carry an update timestamp of November 23, 2021.

**Comment by MikeMcC399** [comment]
The page has updated. The date / time now is November 23, 2021, 5:16 PM:

"Last data update: November 23, 2021, 11:21 AM GMT+1. The data of the CWA dashboard is updated on a daily basis at 10:30 AM"

I will leave this issue open until it is clear what is happening.

https://github.com/corona-warn-app/cwa-website/issues/2091 is also related to this.

**Comment by MikeMcC399** [comment]
Issue https://github.com/corona-warn-app/cwa-website/issues/2091 is now resolved.

This issue can be closed if the following pages reliably update daily:

- https://www.coronawarn.app/en/analysis/ "Corona-Warn-App (CWA): Key performance indicators"
- https://www.coronawarn.app/de/analysis/ "Corona-Warn-App (CWA): Kennzahlen"

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the feedback.

**Comment by MikeMcC399** [comment]
The page https://www.coronawarn.app/en/analysis/ has updated today with the text:
"_Last update of the data: November 25, 2021, 9:21 AM GMT+1._"

All values have been updated with data from yesterday, Nov 24, 2021.

So, now closing as this is now working correctly as expected.
