### ISSUE TITLE
Scrolling behavior is broken under Safari on iOS on FAQ page

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2114]
## Where to find the issue
DE: https://www.coronawarn.app/de/faq/
EN: https://www.coronawarn.app/en/faq/

## Describe the issue
The scrolling behavior of the FAQ page is really broken on the mobile Safari browser: 

https://user-images.githubusercontent.com/67682506/142935138-0fb8b47b-9a7e-426f-8e63-90080f7eed31.mp4

https://user-images.githubusercontent.com/67682506/142935185-66fae5c2-d6cc-40c4-bd85-2501291385a3.mp4

## Suggested change
Fix the issue ASAP.

## Additional information
I was not able to reproduce this under Android using the Chrome browser. I did not check under iOS with another browser. IHMO this is a high priority issue.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks, we will have a look at this.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for reporting. PR https://github.com/corona-warn-app/cwa-website/pull/2116

**Comment by Ein-Tim** [comment]
Thanks @dsarkar & @matriceria!

Confirm fixed! 

Closing.
