### ISSUE TITLE
FAQ entry needed informing about the current risk calculation parameters

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2120]
## Feature description

There should be a FAQ entry which informs about the current risk calculation parameters (e.g. green warning if the contact lasted longer than 5, but shorter than 9 minutes and was not in close proximity).

## Problem and motivation
Users often ask about the current parameters and want to know them. There is no way to guide them, currently (besides from https://www.coronawarn.app/en/faq/#encounter_19_calc which also talks about other thinks).

## Is this something you're interested in working on

Too busy currently, sorry (:

**Comment by ahodzic2** [comment]
Hi @Ein-Tim - Do you know if this is still needed? If so, and if someone can provide some guidance on the calculations or some sort of resource, I would be happy to add an faq section for this.

**Comment by MikeMcC399** [comment]
@ahodzic2 / @Ein-Tim 

I suggest to copy the last sentence from https://www.coronawarn.app/en/faq/results/#encounter_but_green

"For more details about risk assessment see the [Mobile Applications section in the Solution Architecture document](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#mobile-applications)."

into

https://www.coronawarn.app/en/faq/results/#encounter_19_calc

---
... and from
https://www.coronawarn.app/de/faq/results/#encounter_but_green

"Weitere Details zur Risiko-Ermittlung (auf Englisch) finden Sie im [Abschnitt 'Mobile Applications' des Dokuments 'Solution Architecture'](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#mobile-applications)."

into

https://www.coronawarn.app/de/faq/results/#encounter_19_calc

---
It's not necessary to add a new section. There are already two sections
- https://www.coronawarn.app/en/faq/results/#app_features_risk_assessment
- https://www.coronawarn.app/en/faq/results/#technical_correlations_risk_assessment

which bundle the articles on this topic together

**Comment by Ein-Tim** [comment]
I agree with @MikeMcC399, but would also suggest to remove unnecessary information from https://www.coronawarn.app/en/faq/results/#encounter_19_calc.

IMO the entry is currently too packed with technical information which the user didn't want to see.

I would change the entry so that it comes out like this:

"With the introduction of Corona-Warn-App version 1.9, a new version of the Exposure Notification Framework (ENF) from Apple/Google is used. For more information, take a look at: [Corona-Warn-App Version 1.9 to use version 2 of the Exposure Notification Framework](https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9)

The version 2.0 considers 30-minute time windows.

Each of these windows must meet certain criteria to be considered:

- The signal attenuation must have been below 79dB for at least 5 minutes within the 30-minute window

- The transmission risk level must be at least III (3). It is determined when sharing the diagnosis codes [**I think codes is wrong, it should be KEYS**] per day according to defined criteria such as symptom status and/or symptom onset

If these criteria are **not** met, an encounter is **not counted** within the app. It is a 'non-risk encounter'. These encounters will still show up in the operating system's contact log, but do not count towards the overall risk score in the app, see [What do the exposure check logs show?](https://www.coronawarn.app/en/faq/results/#keys_matches).

If the conditions are met, the contact times are weighted depending on the signal attenuation:

- Times with an attenuation <63dB are weighted at 80%.
- Times with an attenuation >= 63dB and <73dB are weighted at 100%.
- Times with an attenuation >= 73dB and <79dB are weighted at 10%.

Based on the transmission risk level (III to VIII), a factor between 0.6 and 1.6 is determined. The weighted exposure time from the previous step is multiplied by this factor, which then results in the normalized exposure time. Finally, all normalized times of a day are added up. Ultimately, this means that several short low risk encounters can result in a red status in total. The sum of all normalized exposure times is now used to decide the final risk score:

- Sum of contact time <5 minutes: No risk exposure(s) (green).
- Sum of contact time >=5 minutes and <9 minutes: Low risk exposure(s) (green).
- Sum of contact time >=9 minutes: High risk exposure(s) (red).

For more details about risk assessment see the [Mobile Applications section in the Solution Architecture document](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md)."

If this change is accepted, I would go ahead and provide a PR for this myself.

**Comment by ahodzic2** [comment]
@Ein-Tim and @MikeMcC399 those are both great ideas IMO.

@dsarkar - Can you provide feedback on the suggestions and if agreed upon, I can gladly get to work on revising the mentioned sections and working on a PR.

**Comment by svengabr** [comment]
Nice inputs from everyone in this conversation, @Ein-Tim you can go ahead and provide a PR for your proposal if you like.

**Comment by Ein-Tim** [comment]
@svengabr 

I'll provide a PR in the due course of this week. Thank you!

**Comment by ahodzic2** [comment]
@Ein-Tim Let me know if you've got your hands full. Would be happy to knock this one out on your behalf. 

@svengabr agreed, great input from all 😊

**Comment by Ein-Tim** [comment]
@ahodzic2 Would you like to join our Slack Channel (see https://github.com/corona-warn-app/cwa-documentation/issues/379). Then we can coordinate via DM!

**Comment by ahodzic2** [comment]
@Ein-Tim Absolutrly! I've been looking for a better way to coordinate with others around this repo so thank you for sharing that.

I have joined under the same display name as my GitHub. When you get a chance, let me know if I can be of assistance on this item. I've got time after work these days and am trying to get more involved with open source projects so I would be more than happy to take something off your hands 😊

**Comment by MikeMcC399** [comment]
@Ein-Tim

Missing `#mobile-applications` anchor in English version.

---

https://www.coronawarn.app/en/faq/results/#encounter_19_calc is linked to https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md and not to https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#mobile-applications. The anchor `#mobile-applications` is missing, so the reader is left at the top of the document instead of being taken to the right section.

https://www.coronawarn.app/de/faq/results/#encounter_19_calc on the other hand is linked to the correct topic https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#mobile-applications. 

---

It's a minor point but you might want to add the  `#mobile-applications` anchor to the hyperlink in https://www.coronawarn.app/en/faq/results/#encounter_19_calc to make it the same as in the German version. The full URL would be https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#mobile-applications.

**Comment by ahodzic2** [comment]
@MikeMcC399 @Ein-Tim Since I worked on the English version, I'd be happy to make that change. However, since the original pull request and issue were marked as done/closed I assume I should create a new issue? Making sure so have the process down.

**Comment by MikeMcC399** [comment]
@ahodzic2 
I'd suggest you coordinate with @Ein-Tim (who I'm sure will reply here!) and one of you could just submit a new PR to make the change. It's not necessary from my point of view to create a new issue, since the details are already discussed in this (closed) issue.

Since @svengabr closed this issue automatically then @Ein-Tim can't re-open it, so perhaps @svengabr could just re-open this issue? That's only a secondary point however. There is nothing preventing a PR from being submitted without having an open issue to refer to.

**Comment by ahodzic2** [comment]
> @ahodzic2 
> 
> I'd suggest you coordinate with @Ein-Tim (who I'm sure will reply here!) and one of you could just submit a new PR to make the change. It's not necessary from my point of view to create a new issue, since the details are already discussed in this (closed) issue.
> 
> 
> 
> Since @svengabr closed this issue automatically then @Ein-Tim can't re-open it, so perhaps @svengabr could just re-open this issue? That's only a secondary point however. There is nothing preventing a PR from being submitted without having an open issue to refer to.

@MikeMcC399 Thanks for the rundown!

@Ein-Tim - Let me know if you are ok with me opening up a PR for this minor fix/update.

**Comment by Ein-Tim** [comment]
> Let me know if you are ok with me opening up a PR for this minor fix/update.

For sure!

**Comment by ahodzic2** [comment]
@Ein-Tim Perfect! I'll have that today.
