### ISSUE TITLE
Website is returning 502: Bad Gateway

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2130]
## Where to find the issue
https://www.coronawarn.app/

## Describe the issue
The website is showing 502: Bad Gateway.

## Suggested change
Fix this issue ASAP.

**Comment by Ein-Tim** [comment]
Deployments are also failing: https://github.com/corona-warn-app/cwa-website/actions/runs/1507535800

**Comment by Ein-Tim** [comment]
@dsarkar Are you aware of this issue.
Cc @thomasaugsten, @larswmh, @brifemu & @svengabr

**Comment by larswmh** [comment]
Hi @Ein-Tim, thanks for your report.  We are aware of the issue and are currently working on it. 

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@larswmh Are you aware that the whole server infrastructure is down? See https://github.com/corona-warn-app/cwa-server/issues/1614

**Comment by Ein-Tim** [comment]
I can now access coronawarn.app again, I will still leave this issue open for some time, just to be sure.

**Comment by Ein-Tim** [comment]
So, as I am still able to access www.coronawarn.app without any problems, I can confirm that this issue is really fixed by now.

Closing as fixed.

**Comment by dsarkar** [comment]
Good morning @Ein-Tim Thanks again for reporting! Enjoy Saturday!

**Comment by Ein-Tim** [comment]
@dsarkar 

Thanks to the whole team for the quick fix! Enjoy the weekend!
