### ISSUE TITLE
Event registration bad link (DE)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2138]
## Where to find the issue

https://www.coronawarn.app/de/eventregistration/

## Describe the issue

Cypress `check_links` test finds the following broken link:

```
==================== Broken links ====================

[RESPONSE 404] http://localhost:8000/de/eventregistration/.%20/event-qr-code-guide/ on '/de/eventregistration/'
```

## Steps to reproduce

`npm run test:open`
select
`check_links.js`
to run this test.
Note 1 failed test and view file 
`cwa-website/cypress/logs/broken_links_result.txt`

## Suggested change

In https://github.com/corona-warn-app/cwa-website/blob/df3fce6c432174376cf3221aa83a357bde5601bd/src/data/eventregistration_de.json#L50

change
`<a href='. /event-qr-code-guide/'>hier überprüfen.</a>`
to
`<a href='../event-qr-code-guide/'>hier überprüfen.</a>`

**Comment by dsarkar** [comment]
fixed by https://github.com/corona-warn-app/cwa-website/pull/2140

**Comment by MikeMcC399** [comment]
Thanks to @matriceria for PR #2140.

Cypress check_links.js now runs successfully again!
