### ISSUE TITLE
GitHub new default Nodejs 16 may break build workflow

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2142]
## Where to find the issue

[build.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) workflow.

## Describe the issue

This is a follow-on to issue https://github.com/corona-warn-app/cwa-website/issues/2098 which described the impact of GitHub updating the configuration of [ubuntu-latest](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md) to use Nodejs 16 instead of 14 by default starting the week beginning Nov 29, 2021 i.e. this week.

Issue #2098 and PR https://github.com/corona-warn-app/cwa-website/pull/2106 only addressed the impact to [deploy-master.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/deploy-master.yml). The same impact however also applies to the [build.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) workflow.

The default change to Nodejs 16 has not yet been implemented on the [cwa-website](https://github.com/corona-warn-app/cwa-website). According to the announcement [ubuntu-latest](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md) it says "Image deployment is starting on November 29 and will take 3-4 days."

## Suggested change

Update also [build.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) to select Nodejs 14 explicitly.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks!

**Comment by MikeMcC399** [comment]
PR #2143 submitted.

**Comment by MikeMcC399** [comment]
@dsarkar 

The assumption that the new default Nodejs would break the [.github/workflows/build.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) workflow was not correct.

The specification of
`container: cypress/browsers:node14.7.0-chrome84`
in the workflow, prevents the problem, however node 14.7.0 is not the LTS (Long Term Support Version), so I will open a new issue to discuss if this point needs to be addressed.

I will leave the PR #2143 open in draft state for the moment.

**Comment by dsarkar** [comment]
@MikeMcC399 Anyway many thanks for all the effort in analysing this issue!

**Comment by MikeMcC399** [comment]
@dsarkar 
> Anyway many thanks for all the effort in analysing this issue!

No problem. It's quite interesting to understand it. I did the GitHub trainings a while ago and now I realize where I have some knowledge gaps!

The issue on cwa-website is not urgent, since there are no failures, but I hope to provide an update later today.

**Comment by MikeMcC399** [comment]
Follow-on issue is #2146.
