### ISSUE TITLE
How does the data from the analysis page fit together with the data from the apps statistic tile "Warning by App Users"?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2147]
## Your Question
* Website URL Path: https://www.coronawarn.app/en/analysis/
* Line / Paragraph: "Sharing behaviour"
* Question: In the box "Sharing behaviour" it says that on 01.12.21, 4,160 infections were "shared" through QR-Codes & 937 through teleTANs. Both numbers together is 5.097. So these are the "Warnings by App Users", or not? In the app however, it says "Warning by App Users" "Yesterday (01.12.): 12.162" and in the information text of the statistic it says "Number of app users who have been diagnosed with coronavirus via PCR test and have warned others through the app." so this is even the number without RATs. 
How do these numbers fit together? What am I overlooking?

**Comment by Ein-Tim** [comment]
Maybe this has something to do with what's written in the informational text of the graph?

"**Reference date**
The reference date is the day of test registration (QR code) or of the call to the verification hotline (teleTAN)."

Does this mean that e.g if the test was registered on 30.11.2021 and the result cam back positive on 01.12.2021, the app will show this at 30.11.2021 and not on 01.12.2021 were the infection was "shared" through the app?

**Comment by DanAmt** [comment]
We also see in the Total Shared statistic "PCR not shared" is included. Only when you go to QR or TAN is the number broken down in "shared" or "not shared". The can be interpreted as misleading and should be clarified as well as the obvious difference above.

**Comment by HelTob** [comment]
Hi Tim,

you're right, it has something to do with the reference date but it's a little bit tricky: 

Every single value stands for a different reference date. The shared QR codes refer to the scan date, the shared teleTANs refer to the call date and the count of users who shared their positive test result refer to the share date. 
In addition, the data comes from two different data views: one is a real-time monitoring of HTTP requests to the verification server (count of users), the other is DB backend (QR codes and teleTANs).
Moreover the scripts that retrieve the data do this at two different times during the day. 
For these reasons, the two values may differ.

Best regards
Tobias

**Comment by DanAmt** [comment]
@HelTob From what I see the difference is more than 50%. How can this be explained ?

**Comment by Ein-Tim** [comment]
@HelTob 

Phew, that's tricky & confusing and opens space for a lot of questions (e.g. the one from @DanAmt). Wouldn't it make sense to align the two values? 
Thanks for your response, really appreciate it!

**Comment by HelTob** [comment]
Hello all,

I understand your interest and desire to talk about the topic. Everything I know about the reasons for the difference between the values, I have shared with you. If I can find out more, I will inform you.

Best regards
Tobias

**Comment by Ein-Tim** [comment]
@HelTob 

Okay, thank you very much! Since my initial question was sufficiently answered, I'll close this issue.

@DanAmt Please create a new issue for the remaining open questions. Thanks!
