### ISSUE TITLE
7-day moving average and daily display in Analysis 

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2149]
## Where to find the issue

- https://www.coronawarn.app/en/analysis/ "Corona-Warn-App (CWA): Key performance indicators"
- https://www.coronawarn.app/de/analysis/ "Corona-Warn-App (CWA): Kennzahlen"

## Describe the issue

Using mouse hover to display data in the [Corona-Warn-App (CWA): Key performance indicators](https://www.coronawarn.app/en/analysis/) with "7-day moving average" selected, the averages are displayed with exactly the same notation as the daily counts.

![7-day moving sections](https://user-images.githubusercontent.com/66998419/144579724-1ddc0f34-4f07-45d7-96f6-45ff55561459.png)

## Steps to reproduce

1. Open https://www.coronawarn.app/en/analysis/ in a web browser
2. Select "7-day moving average"
3. Hover the mouse over the graph and view the displayed data

## Suggested change

Make it clear in the hover data display of Analysis which data is a 7-day moving average and which data is a daily count.

**Comment by dsarkar** [comment]
@MikeMcC399 Alright, we will have a look at this.

**Comment by brifemu** [comment]
@MikeMcC399 
FYI: https://github.com/corona-warn-app/cwa-website/pull/2212

**Comment by MikeMcC399** [comment]
Thanks to @brifemu for fixing this issue with PR
- #2212!
