### ISSUE TITLE
7-day moving average decimal places in Analysis 

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2150]
## Where to find the issue

- https://www.coronawarn.app/en/analysis/ "Corona-Warn-App (CWA): Key performance indicators"
- https://www.coronawarn.app/de/analysis/ "Corona-Warn-App (CWA): Kennzahlen"

## Describe the issue

Using mouse hover to display data in the [Corona-Warn-App (CWA): Key performance indicators](https://www.coronawarn.app/en/analysis/) with "7-day moving average" selected, the averages are displayed with three decimal places of precision unless the original number was exactly divisible by 7 in which case no decimal places are displayed.

1. The mixture of displaying sometimes three decimal places of precision and sometimes no decimal places of precision is confusing. For example, in Downloads on Wednesday, December 1, 2021 the Android average is displayed as 54,091.286 (with three decimals places), whereas the iOS average is displayed as 55,507 (with no decimal places shown, because they would be 000 if they were to be displayed).
2. Displaying a total of 8 or 9 digital of precision for an average value clutters the results without adding to the information value. For example, in Downloads on Wednesday, December 1, 2021, the Total average is displayed as 109,598.286.

![7-day moving decimals](https://user-images.githubusercontent.com/66998419/144581531-8033d7bc-70db-4ef9-ac7d-bfa614b07813.png)

## Steps to reproduce

1. Open https://www.coronawarn.app/en/analysis/ in a web browser
2. Select "7-day moving average"
3. Hover the mouse over the graph and view the displayed data

## Suggested change

All the important numbers on the graphs are in the thousands or millions, so it is not helpful to display decimal values in average figures.

Display only rounded whole numbers for 7-day moving averages. For example, the Total 7-day moving average Downloads for Wednesday, December 1, 2021, would be displayed as 109,598 instead of as 109,598.286.

**Comment by dsarkar** [comment]
@MikeMcC399 Alright, we will have a look at this.

**Comment by dsarkar** [comment]
@MikeMcC399 FYI PR https://github.com/corona-warn-app/cwa-website/pull/2207

**Comment by MikeMcC399** [comment]
Thanks to @browkin for PR #2207 which resolves this issue!
