### ISSUE TITLE
Analysis export data files with wrong fields

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2151]
## Where to find the issue

https://www.coronawarn.app/en/analysis/ "Corona-Warn-App (CWA): Key performance indicators" using files published to:

1. https://obs.eu-de.otc.t-systems.com/obs-public-dashboard/csv/cwa_all_data.zip
2. https://obs.eu-de.otc.t-systems.com/obs-public-dashboard/csv/cwa_downloads_data.zip
3. https://obs.eu-de.otc.t-systems.com/obs-public-dashboard/csv/test_results_data.zip
4. https://obs.eu-de.otc.t-systems.com/obs-public-dashboard/csv/cwa_sharing_data.zip
5. https://obs.eu-de.otc.t-systems.com/obs-public-dashboard/csv/cwa_ppa_warnings_data.zip

This issue concerns files with the embedded filename date 2021-12-02 i.e. CWA_dashboard_data_2021-12-02.csv. The files are replaced daily, so it is unknown if the error is temporary or persistent.

## Describe the issue

The csv files associated with "Export data" graphs on the [Corona-Warn-App (CWA): Key performance indicators](https://www.coronawarn.app/en/analysis/) page contain incorrect data fields.

1. All files contain the field `infections_published_daily` which is not displayed anywhere on the Analysis page.
2. The Downloads file `cwa_downloads_data.zip` contains no downloads fields and contains instead ppa fields.
3. The PPA file `cwa_ppa_warnings_data.zip` is missing the fields `update_timestamp` and `effective_date`. It contains also fields from downloads and test sharing.

## Steps to reproduce

1. Open https://www.coronawarn.app/en/analysis/ in a web browser
2. Click "Export all Data"
3. For each graph: click the "Export" link, then "Export data" to download a zip file. 
4. Extract the contents of each downloaded zip file
5. Examine the first line of each `CWA_dashboard_data_YYYY-MM-DD.csv` file which contains the field names
6. Compare with the names according to the document `CWA_dashboard_data-en.pdf`

## Suggested change

Concerning the csv files in the zip files:

1. Remove the field `infections_published_daily` from all csv files.
2. Correct the Downloads file `cwa_downloads_data.zip` so it contains only downloads data and no other fields.
3. Correct the PPA file `cwa_ppa_warnings_data.zip` to include the fields `update_timestamp` and `effective_date`. Remove the fields from downloads and test sharing.

**Comment by MikeMcC399** [comment]
The zip files for today 2021-12-03 have the same issue.

**Comment by MikeMcC399** [comment]
Hallo Tobias @HelTob!

This might be an issue for you.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reporting and suggestions. We contacted TSI/Data analytics group.

**Comment by HelTob** [comment]
Hi there,

we will add a description for the field `infections_published_daily` in the attached data definition document in near future.
Thank you for your commitment.

Best regards
Tobias

**Comment by MikeMcC399** [comment]
@HelTob 
Thanks for the feedback about your planned documentation update. It is good to hear that you plan to add a field definition.

I don't think we need to track this point separately here, so I will now close this issue.

Thanks again to @dsarkar and to you!
