### ISSUE TITLE
Website migration steps for Nodejs 16

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2155]
I migrated a copy of the cwa-website to Nodejs 16 and I successfully tested it. I can provide more details if desired.

The currently used Nodejs version 14 is supported for another 16 months until end of Apr 2023, however there might be other reasons to migrate, apart from this end-of-life date.

## Steps to migrate

1. Update working environment `nvm install lts/gallium` and then `nvm use lts/gallium` (Node v16)
2. Modify build workflow to use Node v16
3. Modify deploy-master workflow to use Node v16

## Workaround for Panini

Building the web causes the error:

```
Error: Panini: rendering error occured.
RangeError: Maximum call stack size exceeded
```

Removing the 5.5 MB interactive graph ("Fig. 6: EDUS participants by 3-digit postcode and district.") from each language version of the Science 2 blog prevents this error occurring.

Edit: Removed the following steps which have now been completed through PR https://github.com/corona-warn-app/cwa-website/pull/2178.

1. Install node-sass@6 through npm (previously using version 4)
2. Install gulp-sass@5 through npm (previously using version 4)
3. Modify gulpfile.js to use gulp-sass@5

---
Internal Tracking ID: [EXPOSUREAPP-10928](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10928)

**Comment by MikeMcC399** [comment]
@dsarkar 

Related topics:

- How long does this website need to be maintained? Probably nobody can answer this question at this time, so it may be better to assume a longer time-frame rather than a shorter one.
- Does it makes sense to start addressing some dependent topics soon without actually migrating to Node v16? That would provide a more solid baseline, if and when the time comes to migrate the Node version.
    - Migration to gulp-saas@5 & node-sass@6
    - Review of need and impact of 5.5 MB graphic source in Science 2 blog

**Comment by svengabr** [comment]
We are aware of the Node16 and will begin to evaluate it soon. We have an open Jira issue already where we started to collect feedback a while back (EXPOSUREAPP-10928).

Thanks to the community there are already some draft pull requests and suggestions on how to move forward with this.

**Comment by MikeMcC399** [comment]
@svengabr 
Let me know if you want to see a PR which migrates to Node16. I've already had it working on a test system.

The only showstopper at the moment is the graph in https://www.coronawarn.app/en/science/2021-07-08-science-blog-2/#51-distribution-by-district which chokes Panini, and makes it fail, due to the sheer amount of data. Is it worth logging this as a separate issue to reduce the amount of data or make it a static graph instead?

**Comment by MikeMcC399** [comment]
If there is going to be an update to Node16, it might also be a good time to update Cypress to 9.x (currently using 7.7.0) and do the testing together. For the update to Cypress there is nothing to change except `package,json` / `package-lock.json` i.e. just execute `npm install cypress@9 --save-dev`.

https://github.com/corona-warn-app/cwa-website/blob/ff12fb53c338e3e69c05a2dbe4e50dd44724be5b/package.json#L73

PR https://github.com/corona-warn-app/cwa-website/pull/2067 already prepared for a Cypress update. I haven't requested it previously because I didn't see any particular advantage to updating.

**Comment by MikeMcC399** [comment]
@svengabr 

I looked at this again after merging
- https://github.com/corona-warn-app/cwa-website/pull/2178

If the large (5.5 MB) interactive graph ("Fig. 6: EDUS participants by 3-digit postcode and district.") is removed from each language version of the Science 2 blog, then the web site can be built without error under Node16 and it runs, at least on the local system.

There are quite a few deprecation warnings when running `npm install` from scratch. Almost none of these can be resolved by upgrading npm packages. Either there are no newer packages available, or installing the latest version doesn't resolve the issue with the dependencies. Despite all the warnings, I couldn't see any problems in the build.

**Comment by MikeMcC399** [comment]
The specific point about the Panini problem with https://www.coronawarn.app/en/science/2021-07-08-science-blog-2/#51-distribution-by-district is now separately described in #2272.

**Comment by MikeMcC399** [comment]
The Panini issue is now resolved.

**Comment by MikeMcC399** [comment]
@svengabr 

I have submitted PR https://github.com/corona-warn-app/cwa-website/pull/2282 which migrates the repository to Nodejs 16.13.1. You may like to consider if you want to use this at this time.

**Comment by MikeMcC399** [comment]
- PR #2282 is updated to use Nodejs 16.13.2 and waiting for Open Source Team

**Comment by dsarkar** [comment]
@MikeMcC399 We will wait for the next science blog article first, just in case.

**Comment by MikeMcC399** [comment]
@dsarkar

> We will wait for the next science blog article first, just in case.

It would be good to make the change when there are not too many other urgent changes being done, just in case there are unexpected side-effects.

I will put the PR into draft state in the meantime. When the science blog article is available as a PR I will check out that there are no conflicts.

**Comment by svengabr** [comment]
The pull request was finally merged today. 
**Thank you very much for your contribution @MikeMcC399 !** 

I did also close the internal Jira Issue `EXPOSUREAPP-10928`. If you have any issues with the new version, please open a new issue.

**Comment by MikeMcC399** [comment]
@svengabr 

I'm happy that this was able to be merged! I agree that any resulting questions / problems are better covered in new issue(s).

Thanks also from me for your trust! (I know you tested as well of course.)

- I also submitted a related PR for the documentation repository. https://github.com/corona-warn-app/cwa-documentation/pull/844. Perhaps somebody could take a look at this one as well. The documentation PR is not so critical because `node` / `npm` are only used for CI checking. There is no website build which could be affected like here. The idea is just to keep the repositories on the same level, so that contributors do not have to switch versions to stay compatible.
