### ISSUE TITLE
Wording change in german faq "Auffrischungsimpfung"

### ISSUE THREAD

**Issue by svengabr** [corona-warn-app/cwa-website#2162]
Please change the wording `Auffrischungsimpfung` to `Auffrischimpfung` in the whole german faq section.

**Comment by MikeMcC399** [comment]
@svengabr 

It seems that both terms:

- `Auffrischungsimpfung` and 
- `Auffrischimpfung` 

are in widespread use. I guess the plan is to align with the use by RKI, for instance on https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/Impfempfehlung-Zusfassung.html.

---

`Auffrischungsimpfung` is used by Bundesministerium für Gesundheit (BMG):

https://www.zusammengegencorona.de/auffrischungsimpfungen-gegen-covid-19-was-ist-jetzt-wichtig/

![image](https://user-images.githubusercontent.com/66998419/145019450-4ae7d1b0-f695-4833-8f9e-e4a798f4bc66.png)

https://www.zusammengegencorona.de/impressum/
Herausgeber der Website:
Bundesministerium für Gesundheit (BMG)
Referat L7 "Presse, Internet, Soziale Netzwerke"

---

Are you going to submit a PR yourself to make this change?

**Comment by MikeMcC399** [comment]
I found "Auffrischimpfungen" in the legal text of

Bundesministerium für Gesundheit
Verordnung
zum Anspruch auf Schutzimpfung
gegen das Coronavirus SARS-CoV-2
(Coronavirus-Impfverordnung – CoronaImpfV)
Vom 30. August 2021

found [here](https://www.bundesanzeiger.de/pub/publication/UOQwlJwXXb8WCuAjJ0P/content/UOQwlJwXXb8WCuAjJ0P/BAnz%20AT%2031.08.2021%20V1.pdf?inline) from https://www.bundesgesundheitsministerium.de/service/gesetze-und-verordnungen.html.

So it seems to make sense to use the same term as in the legal documents (as already requested by this issue), even if there are some pages from the Ministry which are not legal documents and that use the other term. 🙂

**Comment by svengabr** [comment]
@MikeMcC399  sorry that I didn't put any more context in!

I got the order from RKI to change `Auffrischungsimpfung` to `Auffrischimpfung` in the FAQ section

@browkin will take care of this.

**Comment by MikeMcC399** [comment]
@svengabr 
No problem! All is well! Thanks for the response and clarification.
