### ISSUE TITLE
Invalid Percentage for contact time weights in FAQ

### ISSUE THREAD

**Issue by Morphyum** [corona-warn-app/cwa-website#2168]
## Where to find the issue

On the page
https://www.coronawarn.app/en/faq/#risk_assessment
in the category:
**How does the app calculate the risk (version >=1.9)?**

## Describe the issue

> If the conditions are met, the contact times are weighted depending on the signal attenuation:
> 
> Times with an attenuation <63dB are weighted at 80%.
> Times with an attenuation >= 63dB and <73dB are weighted at 100%.
> Times with an attenuation >= 73dB and <79dB are weighted at 10%.

I assume contact at very close range aka very high dB is not weighted with 10%?

## Suggested change

Change the percentage to the correct value.

**Comment by MikeMcC399** [comment]
@Morphyum 
You're referring to https://www.coronawarn.app/en/faq/#encounter_19_calc

In fact high attenuation means the opposite of very close range.

You might find the issue https://github.com/corona-warn-app/cwa-website/issues/712 helpful to understand what each attenuation range means.

**Comment by MikeMcC399** [comment]
@Morphyum 

The figure of 10% in
"Times with an attenuation >= 73dB and <79dB are weighted at 10%." 
from https://www.coronawarn.app/en/faq/#encounter_19_calc
agrees with the [Solution Architecture Documentation](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md).

In the [Risk Calculation section of the Solution Architecture](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-calculation) the [Figure 16: Risk calculation](https://github.com/corona-warn-app/cwa-documentation/blob/master/images/solution_architecture/risk_calculation.svg) labels 73dB as Medium threshold and 79dB as Far threshold and shows a 0.1 weighting factor (= 10%) for the Far threshold.

![image](https://user-images.githubusercontent.com/66998419/145376978-d4b2ea94-6820-42d2-aae4-dadf43cc2e65.png)

According to the reference documentation there is no error in the website information. They both agree.

If your issue has been answered you can close this topic.

**Comment by dsarkar** [comment]
@Morphyum Thanks for participating here. Many thanks to @MikeMcC399 for resolving @Morphyum's doubts.

---
Corona-Warn-App Open Source Team
