### ISSUE TITLE
Update sass npm packages (gulp-sass and node-sass)?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2170]
I suggest to update gulp-sass and node-sass because:

1. It allows to solve the GitHub Dependabot alert requiring an upgrade of tar to version 4.4.18 or later. tar is currently held back at tar@2.2.2 due to gulp-sass@4.1.1 > node-sass@4.14.1 > node-gyp@3.8.0 > tar@2.2.2
2. It prepares the way to update to Node.js 16 at some later date (see https://github.com/corona-warn-app/cwa-website/issues/2155)

gulp-sass would go from 4.1.1 to 5.0.0
node-sass would go from 4.14.1 to 6.0.1
tar would go from 2.2.2 to 6.1.11

If there is interest from the Open Source Team I can submit a PR for this change. I already tested that it works.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. We will have a look also at this one.

**Comment by MikeMcC399** [comment]
@dsarkar 
To make this more concrete I have submitted a draft tested PR https://github.com/corona-warn-app/cwa-website/pull/2178.

**Comment by svengabr** [comment]
We will have a look at your pull request soon.

Thank you very much @MikeMcC399 !

**Comment by MikeMcC399** [comment]
@svengabr 

> We will have a look at your pull request soon.

I am happy to hear that. As soon as you are actively considering it, please let me know and I will rebase PR #2178, retest it and take it out of draft status.

**Comment by MikeMcC399** [comment]
@svengabr / @dsarkar 

Thank you very much for merging. It is good to see that `tar`  has now disappeared from the Dependabot alerts due to the version update.

I'm also happy that the workflows continue to work without errors! 🙂

**Comment by dsarkar** [comment]
@MikeMcC399 Thank you very much for the suggestion and analysis!
