### ISSUE TITLE
Analysis page: Issue with title

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#2171]
**Where:**
Second graph on:
[0] https://www.coronawarn.app/de/analysis/
[1] https://www.coronawarn.app/en/analysis/

**Issue**
Short moment one sees new title, then the old one.

**Comment by MikeMcC399** [comment]
@dsarkar 
Good morning!
Could you explain a bit more about this issue as I don't understand it? I couldn't see any problem when I opened either of the pages.

Is it perhaps happening only with a particular browser?

**Comment by HelTob** [comment]
@MikeMcC399 

Good morning,

the title of the quadrant "Registrierte Tests" (DE) or "Registered test" (EN) has been changed to "Übermittelte und registrierte Testergebnisse" (DE) or "Transmitted and registered test results" (EN) but the old title is still shown.

If you hit F5 on the analysis page (DE and EN) the new title is shown for a short moment but then changes on an instant to the old one.

Tested with Mozilla Firefox 91.3.0 and Microsoft Edge 96.0.1054.43.

Best regards
Tobias

**Comment by MikeMcC399** [comment]
@HelTob 
Now I see it. Thank you for taking the trouble to explain.

**Comment by dsarkar** [comment]
![image](https://user-images.githubusercontent.com/1409741/145384064-ef344593-af69-48e0-a01c-ca379bb1b56b.png)

![image](https://user-images.githubusercontent.com/1409741/145384083-db4f5fab-6c60-4717-9abb-30cafdb01f6e.png)

**Comment by brifemu** [comment]
FYI: https://github.com/corona-warn-app/cwa-website/pull/2172

**Comment by dsarkar** [comment]
@brifemu Thanks.
