### ISSUE TITLE
R 2.16 FAQ #admission_policy

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#2179]
New FAQ R 2.16 FAQ #admission_policy

Links:
- DE https://www.coronawarn.app/de/faq/#admission_policy
- EN https://www.coronawarn.app/en/faq/#admission_policy

**DE**
TBD - article should cover:

- "Zertifikat" im folgenden Text bezieht sich auf das digital COVID Zertifikat der EU.

**Was zeigt der blaue Punkt an?**
**ANZEIGE**
- Der blaue Punkt oben rechts zeigt an, welche Regeln die vorhandenen Zertifikate erfüllen:
- Derzeit kann die CWA vier verschiedene Möglichkeiten unterscheiden, nämlich 3G, 3G+, 2G und 2G+:
  - 3G: Es ist nur folgendes Zertifikate vorhanden: RAT-Test-Zertifikat. 
     im Prinzip einen von Impf-, Genesenen-, RAT-Test- oder PCR-Test-Zertifikat
  - 3G+: Es ist mindestens eines der folgenden Zertifikate vorhanden: Impf-, Genesenen- oder PCR-Test-Zertifikat
  - 2G: Es ist mindestens eines der folgenden Zertifikate vorhanden: Impf- oder Genesenen-Zertifikat. 
  - 2G+: Es ist mindestens eines der folgenden Zertifikate vorhanden: Entweder ein Impf- oder Genesenen-Zertifikat, und des Weiteren ist zusätzlich ein PCR-Test- oder RAT-Test-Zertifikat vorhanden.

**Welche Events kann ich besuchen?**

- Wenn die 2G+-Regeln erfüllt sind, ermöglichen Ihre Zertifikate den Zutritt für 2G+, 2G, 3G und 3G+-Events. Wenn es sich bei dem Test um einen PCR-Test handelt, dann sind auch die 3G+-Regeln erfüllt.
- Wenn die 2G-Regeln erfüllt sind,  ermöglichen Ihre Zertifikate den Zutritt für 2G, 3G und 3G+-Events. D. h. Geimpfte und Genesene müssen keinen negativen Corona-Test vorzeigen.
- Wenn die 3G+-Regeln erfüllt sind, ermöglichen Ihre Zertifikate den Zutritt für 3G+- und 3G-Events.
- Wenn die 3G-Regeln erfüllt sind, ermöglichen Ihre Zertifikate den Zutritt für 3G-Events.

**Mögliches Problem bei 2G+** 

Wenn Ihre Zertifikate nicht mit exakt gleichem Namen und Geburtsdatum ausgestellt wurden, dann kann die Corona-Warn-App diese Zertifikate nicht zueinander zuordnen. Wenn Ihr Testzertifikat nicht mit exakt demselben Namen wie Ihr  Impf- oder Genesenenzertifikat ausgestellt wurde, kann die Corona-Warn-App nicht erkennen, dass Ihre Zertifikate zusammengehören. In diesem Fall zeigt die App "nur" ein 3G statt "2G+" an. 
Stellen Sie daher immer schon beim Ausstellen eines Zertifikats sicher, dass Ihr Name korrekt und vollständig eingetragen wird. Wenden Sie sich an den Aussteller des Zertifikates, sollten Fehler beim Eintrag des Namens oder Geburtsdatums entstanden sein.

**2G+B**
Kann noch nicht von der CWA erkannt werden.

**EN**
TBD

---
Internal Tracking ID: [EXPOSUREAPP-10854](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10854)

**Comment by Ein-Tim** [comment]
The FAQ entry is published. Can this issue be closed?

**Comment by MikeMcC399** [comment]
- There is one open PR on the content. See https://github.com/corona-warn-app/cwa-website/pull/2357.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Do you think this issue should be left open until the PR is merged?

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks for all the improvements!
