### ISSUE TITLE
R 2.15 FAQs:  #quarantine_measures and #voluntary_self_quarantine

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#2184]
**FAQ 1 DE #quarantine_measures** 

Fragen zu Quarantäne-Maßnahmen 

Sollten Sie positiv getestet werden, muss Ihr zuständiges Gesundheitsamt informiert werden. Dies geschieht über Ihren Hausarzt bzw. das Testzentrum, bei dem Sie Ihren Test durchgeführt haben. Wurde Ihr Test nicht in Deutschland durchgeführt, sind Sie verpflichtet, Ihr zuständiges Gesundheitsamt oder Ihren Hausarzt selbst zu informieren, wenn das Testergebnis positiv sein sollte. Die zuständige Behörde, in der Regel Ihr Gesundheitsamt, wird dann eine Isolation anordnen. 

Die Quarantäne, bzw. Isolation im Falle eines positiven Testergebnisses, ist ein wichtiges Element in der Bekämpfung der Pandemie und soll die Verbreitung des Virus verhindern. Sie dient Ihrem Schutz und dem Schutz Aller vor Ansteckung mit dem neuartigen Coronavirus.

Es wird dann von der zuständigen Behörde genau festgelegt, wie lange Sie in Isolation/Quarantäne kommen. Die Maßnahme endet aber nicht automatisch, sondern erst, wenn sie durch die zuständige Behörde wieder aufgehoben wurde. Sie zählen zu denjenigen, die ansteckungsverdächtig sind, ohne notwendigerweise selbst krank oder krankheitsverdächtig zu sein. 

Es ist sehr wichtig, dass sie die Quarantäne/Isolation und die Hygieneregeln genau einhalten – auch wenn Sie keine Beschwerden haben sollten. Beachten Sie die Schutzmaßnahmen, d. h. befolgen Sie Husten- und Nies-Regeln, eine gute Händehygiene und halten Sie Abstand zu anderen Personen.

Derzeit werden folgende Quarantäneoptionen empfohlen:
-	10 Tage Quarantäne ab der letzten Risikobegegnung ohne abschließenden Test
-	5 Tage mit PCR-Test bei Probenahme frühestens am 5. Tag.
Die Entlassung aus der Quarantäne erfolgt erst nach Erhalt des negativen Testergebnisses. Bei Personen, die regelmäßig im Rahmen einer seriellen Teststrategie getestet werden (z.B. Schülerinnen und Schüler), kann der negative Nachweis auch mittels Antigen-Schnelltests erwogen werden. Die Testung mittels Antigen-Schnelltest sollte als Fremdtestung durch oder unter Aufsicht vor Ort von geschulten Personen (überwachter Antigen-Test zur Eigenanwendung) erfolgen.
-	7 Tage mit Antigen-Schnelltest bei Probenahme frühestens am 7. Tag. 
Die Entlassung aus der Quarantäne erfolgt erst nach Erhalt des negativen Testergebnisses. Die Testung sollte als Fremdtestung durch oder unter Aufsicht vor Ort von geschulten Personen (überwachter Antigen-Test zur Eigenanwendung) erfolgen.

Weitere detaillierte Informationen finden Sie unter den RKI-Empfehlungen zum Kontaktpersonenmanagement: [Kontaktpersonen-Nachverfolgung (KP-N) bei SARS-CoV-2-Infektionen](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Kontaktperson/Management.html)

Weitere hilfreiche Informationen zur häuslichen Quarantäne finden Sie hier: [Warum wird die freiwillige Selbstquarantäne empfohlen?](https://www.coronawarn.app/de/faq/#voluntary_self_quarantine)

Testmöglichkeiten finden [Wo kann ich mich testen lassen?](https://www.coronawarn.app/de/faq/#where_can_i_get_tested)

Weitere Informationen zum Testablauf: [Rote Karte? So geht es zum Corona Test](https://www.coronawarn.app/de/faq/#red_card_how_to_test)

Weitere Informationen zu Quarantäne-Maßnahmen finden Sie hier: https://www.coronawarn.app/de/faq/#quarantine_measures 

**FAQ 1 EN #quarantine_measures** 
TBD

**FAQ 2 DE #voluntary_self_quarantine**

Warum wird die freiwillige Selbstquarantäne empfohlen?

**Eigenverantwortung:** 
Sollte die Corona-Warn-App Ihnen eine Begegnung mit erhöhtem Risiko in einer roten Kachel anzeigen, begeben Sie sich, wenn möglich, in eine freiwillige Selbstquarantäne, bis Sie ein negatives Testergebnis vorweisen können. Auch wenn diese Maßnahme nicht von einer zuständigen Behörde, in der Regel von Ihrem Gesundheitsamt, angeordnet wurde, wird Ihnen empfohlen, zu Hause zu bleiben und Begegnungen mit anderen Personen Ihres Haushalts zu minimieren und außerhalb Ihres Haushalts zu vermeiden. Dies gilt auch, wenn Sie geimpft oder genesen sind und keine Symptome zeigen. Die Quarantäne ist ein wichtiges Element in der Bekämpfung der Pandemie und soll die Verbreitung des Virus (falls Sie sich angesteckt haben) verhindern. Sie dient Ihrem Schutz und dem Schutz Aller vor Ansteckung mit dem neuartigen Coronavirus.

**Die Gesundheitsämter sind ausgelastet:** 
Derzeit bewegen sich die COVID-19-Infektionzahlen auf sehr hohem Niveau und eine hohe Zahl von positiven Testergebnissen wird über die CWA übermittelt.  Bitte haben Sie daher Verständnis, dass das Gesundheitsamt nicht alle Kontaktpersonen betreuen kann. Halten Sie dem Gesundheitsamt den Rücken frei für Aufgaben, die es nicht abgeben kann. Kontaktieren Sie Ihr Gesundheitsamt nur, wenn Sie unbedingt Unterstützung brauchen, z.B. weil Ihr Arbeitgeber oder Ihre Ausbildungsstätte eine Bescheinigung verlangt.

**Handlungsempfehlungen:**
-	Lassen Sie sich testen. Bei einer Warnung über ein erhöhtes Risiko („rote Kachel“) haben Sie Anspruch auf einen kostenlosen Test. Das muss nicht notwendigerweise ein PCR-Test sein.
-	Empfohlen sind mindestens 7 Tage, besser 10 Tage, für die Zeitdauer der Selbstquarantäne ab dem Tag der letzten Risikobegegnung. Das Datum der letzten Begegnung mit erhöhtem Risiko finden Sie in der roten Kachel.
-	Verzichten Sie nach Möglichkeit auf Besuche und Aktivitäten, bei denen Sie mit anderen Menschen zusammenkommen. Lassen Sie sich Lebensmittel liefern oder bitten Sie jemanden, die Einkäufe zu erledigen; meiden Sie öffentliche Verkehrsmittel und verzichten Sie auf Flug- und Zugreisen.
-	Vermeiden Sie insbesondere Kontakte zu vulnerablen Personen und Gruppen, beispielsweise zu Älteren und Vorerkrankten.
-	Minimieren Sie auch Kontakte im eigenen Haushalt.
-	Wenn Ihr Arbeitgeber Ihnen die Möglichkeit gibt, arbeiten Sie von zu Hause aus.
-	Achten Sie mindestens für 14 Tage (ab Risikobegegnung) auf Krankheitssymptome und wenden Sie sich an Ihre Hausarztpraxis, falls Sie sich krank fühlen oder Symptome auftreten sollten.
-	Halten Sie die Hygieneregeln ein.

Weitere hilfreiche Informationen zur häuslichen Quarantäne finden Sie hier: [Häusliche Quarantäne (vom Gesundheitsamt angeordnet): Flyer für Kontaktpersonen](www.rki.de/covid-19-quarantaene)
Weitere Informationen zu Quarantäne-Maßnahmen finden Sie hier: https://www.coronawarn.app/de/faq/#quarantine_measures 
Testmöglichkeiten finden [Wo kann ich mich testen lassen?](https://www.coronawarn.app/de/faq/#where_can_i_get_tested)
Weitere Informationen zum Testablauf: [Rote Karte? So geht es zum Corona Test](https://www.coronawarn.app/de/faq/#red_card_how_to_test)

**FAQ 2 EN #voluntary_self_quarantine**
TBD

---
Internal Tracking ID: [EXPOSUREAPP-10857](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10857)
Internal Tracking ID: [EXPOSUREAPP-10856](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10856)

**Comment by MikeMcC399** [comment]
Since #2188 has been merged, this issue can probably now be closed.

**Comment by dsarkar** [comment]
@MikeMcC399 True... Good morning!
