### ISSUE TITLE
R 2.15 Update FAQ #vac_cert_red_warning

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#2192]
Update FAQ
https://www.coronawarn.app/de/faq/#vac_cert_red_warning

Wie sollte man sich verhalten, wenn man teil- oder vollständig geimpft ist, aber eine rote Warnung in der Corona-Warn-App erhält?

OLD

Wenn eine vollständig geimpfte Person eine Begegnung mit erhöhtem Risiko (rote Kachel) angezeigt bekommt, ist zunächst keine Quarantäne nötig, solange keine Symptome auftreten. Falls im weiteren Verlauf Symptome auftreten, sollten Sie sich unmittelbar testen lassen und in sofortige Quarantäne begeben. Wenn Sie sich testen lassen wollen, konsultieren Sie bitte Ihren Arzt bzw. Ihre Ärztin für die weiteren Schritte. Bei nicht abgeschlossener Grundimmunisierung sowie in den ersten 14 Tagen nach der letzten Dosis ist der Impfschutz deutlich geringer, so dass hier dieselben Empfehlungen wie bei Ungeimpften gelten.

NEW

Wenn eine vollständig geimpfte Person eine Begegnung mit erhöhtem Risiko (rote Kachel) angezeigt bekommt, ist zunächst keine Quarantäne nötig, solange keine Symptome auftreten. Lassen Sie sich testen, auch wenn Sie keine Symptome haben. Bei einer Warnung über ein erhöhtes Risiko (Rote Kachel) haben Sie Anspruch auf einen kostenlosen Test. Dies muss nicht notwendigerweise ein PCR-Test sein. 

Falls im weiteren Verlauf Symptome auftreten, sollten Sie sich unmittelbar testen lassen sofern dies nicht geschehen ist und in sofortige Quarantäne begeben. Konsultieren Sie bitte Ihren Arzt bzw. Ihre Ärztin für die weiteren Schritte. 

Bei nicht abgeschlossener Grundimmunisierung sowie in den ersten 14 Tagen nach der letzten Dosis ist der Impfschutz deutlich geringer, so dass hier dieselben Empfehlungen wie bei Ungeimpften gelten.

**Comment by MikeMcC399** [comment]
@dsarkar 
I am confused because this text is not in alignment with the text for #voluntary_self_quarantine in the open PR https://github.com/corona-warn-app/cwa-website/pull/2188

**Comment by thorbenkuro** [comment]
Thank you for the feedback @MikeMcC399 ! We will adjust this text to align with the #voluntary_self_quarantine faq text.

**Comment by Ein-Tim** [comment]
Also, please think about also mention what recovered people are recommended to do in this FAQ entry.

**Comment by dsarkar** [comment]
@Ein-Tim  @MikeMcC399 Thanks for the hints. PR was updated.
