### ISSUE TITLE
"Was tun bei einer roten Kachel?" Blog posting

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2198]
## Where to find the issue

https://www.coronawarn.app/de/blog/2021-12-15-cwa-red-tile-guidance/ "Was tun bei einer roten Kachel?"
https://www.coronawarn.app/en/blog/2021-12-15-cwa-red-tile-guidance/ "Was tun bei einer roten Kachel?"

## Describe the issues

1. Covid-19 is written inconsistently as "Covid-19" and "COVID-19"

2. The link in "Mehr zu den Empfehlungen finden Sie auf der [Website des Robert Koch-Instituts](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Kontaktperson/Management.html;jsessionid=FA6467ABE90F33E7D9982350BA10FBAB.internet051?nn=13490888#doc13516162bodyText16)." includes a `jsessionid`.

3. The visible part of the links to

    - https://www.coronawarn.app/de/faq/#voluntary_self_quarantine
    - https://www.coronawarn.app/de/faq/#quarantine_measures

are literal and absolute.

4. In the following:

    - https://www.coronawarn.app/de/faq/#where_can_i_get_tested
    - https://www.coronawarn.app/de/faq/#red_card_how_to_test
    - https://www.coronawarn.app/de/science/2021-10-15-science-blog-4/#3-privacy-preserving-analytics

the visible part of the links are literal and both the visible part and the target are absolute references.

5. In "Antworten auf häufig gestellte Fragen rund um das Verhalten bei einer roten Kachel finden Sie auch in den [FAQs auf der Website der CWA](https://www.coronawarn.app/de/faq/#red_card_how_to_test)." the target is absolute not relative.

6. The English text is a complete copy of the German text which makes maintenance of the text twice the effort if all corrections have to be repeated.

## Suggested change

1. Capitalize "COVID-19" everywhere in accordance with other posts, the FAQs and RKI's spelling on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/nCoV.html

2. Remove `jsessionid` from the RKI link

3. Change absolute links to relative links

4. Integrate relative links into text instead of quoting absolute links

5. For the English posting use only the summary German text and add a link to the full German text to avoid having to maintain two copies of the same text

**Comment by MikeMcC399** [comment]
The actual text reads very well, so the above comments are more about the technical aspects of the posting.

Let me know if the Open Source Team wants to correct these points and if you need assistance. The PR https://github.com/corona-warn-app/cwa-website/pull/2195 was only open for 4 minutes before it was merged, so that was not long enough to read and comment on it before it was published.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the report. Happy with your suggestions. Do you want to provide a PR?

**Comment by MikeMcC399** [comment]
@dsarkar 
> Thanks for the report. Happy with your suggestions. Do you want to provide a PR?

Thanks for your confirmation. I will provide a PR for the German text. 

Regarding the posting in the English blog content: Do you know if there is a time-line for replacing the German text by translated English text? If this will happen soon, then I would hold back on making corrections there, otherwise I would suggest changes to the English blog as well.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for offering a PR, very much appreciated. I suggest to keep the English blog as it is. I expect the translated version within a couple of days.

**Comment by MikeMcC399** [comment]
On more point:

"Allein vom 1. bis einschließlich 7.&nbsp;Dezember haben geschätzt **mehr als 1,1 Millionen Nutzer\*innen der Corona-Warn-App (CWA) eine rote Kachel erhalten** ([Stand 14.12.2021](https://www.coronawarn.app/de/science/))*."

The estimation needs some more explanation and source of data (https://www.coronawarn.app/de/analysis/). There are 588,072 red warnings collected from PPA, so x 2 = estimated 1,176,144 in that time period.

![von-datenspendenden-empfangene-warnungen-2021-12-01-2021-12-07](https://user-images.githubusercontent.com/66998419/146374708-90b0f2ce-e6a6-40fa-a358-e2595989b054.png)

**Comment by dsarkar** [comment]
@MikeMcC399 I will come back to you

**Comment by MikeMcC399** [comment]
PR #2202 is now submitted to modify https://www.coronawarn.app/de/blog/2021-12-15-cwa-red-tile-guidance/ "Was tun bei einer roten Kachel?" DE version only.

**Comment by svengabr** [comment]
> The estimation needs some more explanation and source of data (https://www.coronawarn.app/de/analysis/). There are 588,072 red warnings collected from PPA, so x 2 = estimated 1,176,144 in that time period.

Thanks, @MikeMcC399 for your PR. The changes did not add any contextual explanations of the analysis part. Do you want me to close this issue and open a new one to keep track of this additional task?

**Comment by MikeMcC399** [comment]
@svengabr 

> > The estimation needs some more explanation and source of data (https://www.coronawarn.app/de/analysis/). There are 588,072 red warnings collected from PPA, so x 2 = estimated 1,176,144 in that time period.
> 
> Thanks, @MikeMcC399 for your PR. The changes did not add any contextual explanations of the analysis part. Do you want me to close this issue and open a new one to keep track of this additional task?

I did not want to make changes in that area without agreement, so yes, it would be great if you could close this issue and open a new one regarding the explanation of the estimate.

Thank you!

**Comment by svengabr** [comment]
I have created this new issue: https://github.com/corona-warn-app/cwa-website/issues/2203
