### ISSUE TITLE
Website needs simpler language

### ISSUE THREAD

**Issue by beckchris** [corona-warn-app/cwa-website#22]
We want many millions of people in Germany to install the app, right? To achieve this the landing page needs a much easier-to-understand language.

One example:
When looking at the german version of the website, one of the first senteces that the user reads is: "Das Exposure Notification Framework (von Apple und Google) auf einem mobilen Gerät sendet einen Rolling Proximity Identifier und sucht gleichzeitig regelmäßig mithilfe der Technologie Bluetooth Low Energy nach IDs anderer Smartphones und speichert die IDs lokal."

How many percent of people in Germany are able to understand this?

Don't forget that the challenge is not to develop this app, but rather to bring it onto the smartphones of about 50 million people in germany. So the marketing team should be larger than the development team.

Is there any strategy for that already in place?

**Comment by MalteJ** [comment]
Hi Chris,

the idea for coronawarn.app is to get in contact with developers, tech freaks and people interested in the progress of the open source project. The target group of coronawarn.app is definitively not the broad population of Germany.
A separate PR campaign will be set up with the target to get a huge adoption.
I think the language is OK for the group we are targeting with coronawarn.app.

Malte

**Comment by beckchris** [comment]
Hi Malte, okay I understand. Thanks for clarification.
Christian

**Comment by gregorwolf** [comment]
Hi @MalteJ, Hi @beckchris,

before I found this issue I've already sat down and created this simpler version of the german text for section 01.:

> Apple und Google stellen für iOS und Android das Exposure Notification Framework bereit. Dieses sendet eine sich alle 10 bis 20 Minuten ändernde ID (Rolling Proximity Identifier). Gleichzeitig sucht es regelmäßig mithilfe von Bluetooth Low Energy nach IDs anderer Smartphones. Die empfangenen IDs werden lokal abgespeichert. Die IDs werden kryptografisch von temporären Schlüsseln abgeleitet, die sich alle 24 Stunden ändern.

If you like it I'm also happy to create a pull request.

I hope that also the marketing campaign will be created in an open way so it can be improved before hitting the broader public.

Best regards
Gregor
