### ISSUE TITLE
Add more explanation to analysis data in cwa-red-tile-guidance blog article

### ISSUE THREAD

**Issue by svengabr** [corona-warn-app/cwa-website#2203]
## Where to find the issue

https://www.coronawarn.app/de/blog/2021-12-15-cwa-red-tile-guidance/ "Was tun bei einer roten Kachel?"
https://www.coronawarn.app/en/blog/2021-12-15-cwa-red-tile-guidance/ "Was tun bei einer roten Kachel?"

## Describe the issues

> "Allein vom 1. bis einschließlich 7.&nbsp;Dezember haben geschätzt **mehr als 1,1 Millionen Nutzer\*innen der Corona-Warn-App (CWA) eine rote Kachel erhalten** ([Stand 14.12.2021](https://www.coronawarn.app/de/science/))*."

![von-datenspendenden-empfangene-warnungen-2021-12-01-2021-12-07](https://user-images.githubusercontent.com/66998419/146374708-90b0f2ce-e6a6-40fa-a358-e2595989b054.png)

## Suggested change
The estimation needs some more explanation and source of data (https://www.coronawarn.app/de/analysis/). There are 588,072 red warnings collected from PPA, so x 2 = estimated 1,176,144 in that time period.

**Comment by svengabr** [comment]
@dsarkar did already start working on it internally. We are currently waiting for updated texts.

**Comment by MikeMcC399** [comment]
@svengabr 

Are you still planning to update the blog article?
https://www.coronawarn.app/en/blog/2021-12-15-cwa-red-tile-guidance/ "What should you do if you see a red tile?"

In general, blog articles aren't maintained. They are just like newspaper articles which are a snapshot in time.

**Comment by MikeMcC399** [comment]
@svengabr 

Isn't this issue now obsolete now that it is over 6 months old?

**Comment by larswmh** [comment]
Closing as suggested
