### ISSUE TITLE
Dashboard CSV data provide counts with decimal fractions

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2204]
## Where to find the issue

https://www.coronawarn.app/en/analysis/ "Corona-Warn-App (CWA): Key performance indicators"

## Describe the issue

All data values in exported data from the [Corona-Warn-App (CWA): Key performance indicators](https://www.coronawarn.app/en/analysis/) page where the fields corresponds to a count of something, and which therefore can only be a whole number, are transmitted with a single decimal place. For example `tests_total_cumulated` is exported as `71762776.0` instead of the integer value `71762776`.

## Steps to reproduce

1. Open https://www.coronawarn.app/en/analysis/ in web browser
2. Click on "Export all data"
3. Extract `CWA_dashboard_data_yyyy-mm-dd.csv` from `cwa_all_data.zip`
4. Open `CWA_dashboard_data_yyyy-mm-dd.csv` with text editor
5. Note the first line (containing the field names) starting with `update_timestamp,effective_date,infections_published_daily,tests_total_cumulated,`
6. Scroll down to the end of the file and note the start of the last full line e.g. `"2021-12-16T09:21:49,398",2021-12-15,51301,71762776.0`

In the above example
- `infections_published_daily` is correctly an integer `51301`
- `tests_total_cumulated` is incorrectly transmitted as a real number `71762776.0` with a decimal place. It should be `71762776` without `.0` at the end

## Suggested change

Remove the decimal place from all of the fields which are counts. That is to say the data belonging to the following fields with names:
- *daily
- *cumulated
- *sum

should be transmitted with no decimal fraction.

Only average values with field names:
- *avg

should be permitted to have decimal fractions in the exported CSV files.

**Comment by dsarkar** [comment]
@MikeMcC399 Good morning! Same here, I will forward this!. Thanks.

**Comment by MikeMcC399** [comment]
Good morning @dsarkar ! Thank you.

**Comment by MikeMcC399** [comment]
This issue has not yet been addressed. Values which are counts, and therefore can only be whole numbers, are still transmitted with a meaningless decimal fraction.
`2022-03-10T09:21:52,031",2022-03-09,215854,160816431.0`

`160816431.0` should be `160816431`

**Comment by HelTob** [comment]
Thank you very much for the suggestion. I have forwarded the issue and an adjustment will be made in the near future.

Best regards,
Tobias

**Comment by MikeMcC399** [comment]
Hi Tobias @HelTob 

Have there have been any concrete changes prepared? (I know that "near future" is a flexible term, however the last statement was about 7 weeks ago.)

**Comment by HelTob** [comment]
Hi Mike,

I am still in exchange with the responsible people and I have not forgotten about the issue. 

As far as I know, it is complicated to remove the decimals because of the different conversion processes. 

I'll stay tuned and let you know if there are any further developments.

Best regards
Tobias
