### ISSUE TITLE
Analysis CSV data field names

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2205]
## Where to find the issue

https://www.coronawarn.app/en/analysis/ "Corona-Warn-App (CWA): Key performance indicators"

## Describe the issue

1. The field name `*invalide` is not an English language word, unlike the other suffixes.
2. In the documentation the prefix `tests_rat_positve` is misspelled

## Steps to reproduce

1. Open https://www.coronawarn.app/en/analysis/ in web browser
2. Click on "Export all data"
3. Extract `CWA_dashboard_data-en.pdf` from `cwa_all_data.zip`

## Suggested change

1. It may be too disruptive to change the field names from `*invalide` to `*invalid` which would be a proper English word, but please consider.
2. Correct the spelling `tests_rat_positve` to `tests_rat_positive` in the English and German documentation. There is no error in the CSV data, only in the documentation.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks, I will forward this.
