### ISSUE TITLE
No timestamp on 2.15 blog

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2216]
## Where to find the issue

- https://www.coronawarn.app/en/blog/2021-12-20-cwa-2-15/ "Corona-Warn-App simplifies certificate checks when booking tickets"
- https://www.coronawarn.app/de/blog/2021-12-20-cwa-2-15/ "Corona-Warn-App vereinfacht die Zertifikatsprüfungen bei der Ticketbuchung"

## Describe the issue

The blog announcement for CWA 2.15 includes the text:

"Version 2.15 - like previous versions - will be delivered in a staged rollout and is made available for users in waves. While users can manually trigger an update in Apple’s App Store, this option is not available in the Google Play Store. There, the delivery of the Corona-Warn-App’s new version can take up to 48 hours."

Since there is no timestamp on the blog, only a date (December 20, 2021), there is no start-time defined to count 48 hours until the Android app should be available for all users.

## Suggested change

- Add a release time to the header of the blog, as has been done for all previous release announcements e.g. https://www.coronawarn.app/en/blog/2021-11-22-cwa-2-14/ shows "Hanna Heine, 10 am, on November 22, 2021" or
- add a release time to the paragraph quoted above

**Comment by dsarkar** [comment]
@MikeMcC399 I will check with HH.

**Comment by dsarkar** [comment]
@MikeMcC399 Release roll out started about 0800 AM, do you want to provide a PR? Otherwise I will do it. Thanks.

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/2224
