### ISSUE TITLE
"Limitierung Personenzahl bei Zertifikats-Scan" not mentioned in blog

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2217]
## Where to find the issue

- https://www.coronawarn.app/en/blog/2021-12-20-cwa-2-15/ "Corona-Warn-App simplifies certificate checks when booking tickets"
- https://www.coronawarn.app/de/blog/2021-12-20-cwa-2-15/ "Corona-Warn-App vereinfacht die Zertifikatsprüfungen bei der Ticketbuchung"

## Describe the issue

The Twitter announcement of CWA 2.15 https://twitter.com/coronawarnapp/status/1472840234006155269

![image](https://user-images.githubusercontent.com/66998419/146750188-46f2b6d0-d89a-4766-8a0e-c675759d6efd.png)

includes the item:

- "Limitierung Personenzahl bei Zertifikats-Scan"

This is not mentioned in the blog announcement for CWA 2.15 on  https://www.coronawarn.app/de/blog/2021-12-20-cwa-2-15/ "Corona-Warn-App vereinfacht die Zertifikatsprüfungen bei der Ticketbuchung".

## Suggested change

Add information regarding "Limitierung Personenzahl bei Zertifikats-Scan" to CWA 2.15 English and German announcement blogs.

---
Internal Tracking ID: [EXPOSUREAPP-11889](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11889)

**Comment by MikeMcC399** [comment]
@dsarkar 
There hasn't been any response here so far and the functionality is not documented in the blog or the FAQs.

Perhaps it would be better now to just create a new FAQ article?

**Comment by dsarkar** [comment]
@MikeMcC399 Sure.

**Comment by MikeMcC399** [comment]
@dsarkar 
I understood that you agreed there should be an FAQ about limiting the number of certificates which can be scanned, however nothing has been written so far.

Will you follow up?

**Comment by Ein-Tim** [comment]
I doubt that the blog will be updated reg. this now, 4 months after the version has been released. I suggest to close this issue.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> I doubt that the blog will be updated reg. this now, 4 months after the version has been released. I suggest to close this issue.

I agree. The issue was only left open because @dsarkar indicated there would be a new FAQ. Judging by lack of reported issues on this subject it seems that an FAQ is not necessary.

Closing because the request is now outdated.
