### ISSUE TITLE
Privacy notice cross-reference error EN

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2225]
## Where to find the issue

https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf
cwa-privacy-notice-en.pdf 15 December 2021 2.15 page 18
6. Why is your data processed?
k. Verifications of certificates for ticket bookings

"You can then select this and send it to the verification partner together with the booking information made available by the provider (See Section Error! Reference source not found..)."

## Describe the issue

Error! Reference source not found

## Suggested change

Correct missing cross reference in document.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reporting, I will forward this issue.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10950](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10950)

**Comment by MikeMcC399** [comment]
This issue carries a label "Fix 2.15", however the document was not fixed whilst 2.15 was the current version and it has not been changed since the publication of the 2.16 app version.

See https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf
cwa-privacy-notice-en.pdf 15 December 2021 2.15 page 18

![image](https://user-images.githubusercontent.com/66998419/150185387-916ee5d9-f564-42d7-9aae-7fc1ed4b4e4f.png)

**Comment by MikeMcC399** [comment]
@dsarkar 
The privacy notice was not updated with the release of 2.17, it still contains the error and this issue still contains the label Fix 2.15.

See https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf
cwa-privacy-notice-en.pdf 15 December 2021 2.15 page 18 and previous comment  https://github.com/corona-warn-app/cwa-website/issues/2225#issuecomment-1016711242.

**Comment by MikeMcC399** [comment]
@dsarkar 
- It seems that there is no plan to fix this issue in the 2.15 version of the EN privacy notice, although it will be fixed in the 2.19 version in the open PR https://github.com/corona-warn-app/cwa-website/pull/2512.

**Comment by MikeMcC399** [comment]
Closing.

- PR https://github.com/corona-warn-app/cwa-website/pull/2480 in branch [release/2.19](https://github.com/corona-warn-app/cwa-website/tree/release/2.19) fixes the issue for the 2.19 version of the EN privacy notice. "You can then select this and send it to the verification partner together with the booking information made available by the provider (See Section 5 k.)."
- the 2.15 version of the EN privacy notice (15 December 2021 page 18) retains the error "See Section Error! Reference source not found.."
