### ISSUE TITLE
Inconsistent full name of RKI in EN blogs

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2226]
## Where to find the issue

https://www.coronawarn.app/en/blog/

## Describe the issue

In the English language blogs the RKI is referred to as both:

- Robert Koch-Institut
- Robert Koch Institute

## Suggested change

Change all "Robert Koch-Institut" instances in English language blogs to "Robert Koch Institute".

This would be consistent with the English language imprint https://www.coronawarn.app/en/imprint/ and with the use on the English language FAQs.

**Comment by MikeMcC399** [comment]
If there is agreement, I can submit a PR to make this global change.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks, we will check tomorrow. Enjoy the evening!

**Comment by dsarkar** [comment]
@MikeMcC399 OK, let's go for it. Also here https://www.rki.de/EN/Home/homepage_node.html  "Robert Koch Institute" is used.

**Comment by MikeMcC399** [comment]
@dsarkar 
> OK, let's go for it. 

Fine. I will submit a PR for this. Thanks for checking first!

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/2237 is submitted to resolve this issue.
