### ISSUE TITLE
Confusing statements in the 2.15 announcement blog post

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2227]
## Where to find the issue
DE: https://www.coronawarn.app/de/blog/2021-12-20-cwa-2-15/
EN: https://www.coronawarn.app/en/blog/2021-12-20-cwa-2-15/

## Describe the issue
The blog post says:

"After the user has selected a certificate and once again given their consent, the certificate is checked. **For this purpose, it is temporarily transmitted in encrypted form to the validation service.** The validation service then compares the organizer's rules with the certificate and then informs the booking system whether the certificate complies with the rules or not."

And then, in the next paragraph it says:

"Please notice: the certificates **remain on the user's own smartphone and are not stored in the validation system** at any time."

This is very confusing and seems to be a contradiction. Yes, one time the text is about "the validation service" and one time about "the validation system". Normal users don't understand the difference. Not even I do. 😅 

## Suggested change
Make it clearer whether the certificate (and what data of the certificate) is send to the server in the process.

Ping @HannaHei

**Comment by MikeMcC399** [comment]
@Ein-Tim

Thank you for raising this important topic!

- https://github.com/corona-warn-app/cwa-website/pull/2232 changed this text.

https://www.coronawarn.app/en/blog/2021-12-20-cwa-2-15/
"**The certificates are not transmitted to the booking system and are not stored in the validation service.**"

https://www.coronawarn.app/de/blog/2021-12-20-cwa-2-15/
"**Die Zertifikate werden nicht an das Buchungssystem übertragen und nicht im Validierungsservice gespeichert.**"

Perhaps you could check if you think this is now solved?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks for the reminder. Yes, it's clearer now, for the remanning issues I'll open a new issue.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks for following up!
