### ISSUE TITLE
Links in "What should you do if you see a red tile?" (EN)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2229]
## Where to find the issue

https://www.coronawarn.app/en/blog/2021-12-15-cwa-red-tile-guidance/ "What should you do if you see a red tile?"

## Describe the issues

This is a carry-over from the closed issue #2198. The German text in the English language blog https://www.coronawarn.app/en/blog/2021-12-15-cwa-red-tile-guidance/ has been replaced with English text. It seems that this is based on the original, uncorrected German text and some of the original issues reported still exist:

1. Covid-19 is written inconsistently as "Covid-19" and "COVID-19"

2. The link in "For more information on the recommendations, visit the [Robert Koch-Institut's website](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Kontaktperson/Management.html;jsessionid=FA6467ABE90F33E7D9982350BA10FBAB.internet051?nn=13490888#doc13516162bodyText16)." includes a `jsessionid`.

3. Some links are displayed literally and with absolute addresses.

## Suggested change

In general, make the same changes to the English version as already made to the German version.

1. Capitalize "COVID-19" everywhere in accordance with other posts, the FAQs and RKI's spelling on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/nCoV.html

2. Remove `jsessionid` from the RKI link

3. Change absolute links to relative links

4. Integrate relative links into text instead of quoting absolute links

**Comment by MikeMcC399** [comment]
PR #2230 submitted to resolve this issue.

**Comment by dsarkar** [comment]
Good morning @MikeMcC399 Thanks.

**Comment by MikeMcC399** [comment]
Good morning @dsarkar. You're welcome!
