### ISSUE TITLE
Link to UK Government site in blog

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2236]
## Where to find the issue

https://www.coronawarn.app/en/blog/2021-12-15-cwa-red-tile-guidance/ "What should you do if you see a red tile?"

## Describe the issue

https://www.coronawarn.app/en/blog/2021-12-15-cwa-red-tile-guidance/ "What should you do if you see a red tile?" says:

"Nevertheless, you should **adhere to the usual hygiene rules**: "When you encounter other people, wear a medical mask, keep distance from other people, sneeze or cough into your elbow or a handkerchief, wash your hands regularly with soap, and let fresh air in several times a day (see [here](https://www.gov.uk/government/news/public-reminded-to-let-in-fresh-air-when-meeting-others-indoors-to-reduce-the-spread-of-covid-19) for further information)."

which includes a link to the UK Government website https://www.gov.uk/government/news/public-reminded-to-let-in-fresh-air-when-meeting-others-indoors-to-reduce-the-spread-of-covid-19.

This link contains not only technical information about ventilation, it also includes legal information about regulations in the United Kingdom which do not apply in Germany and are therefore confusing to read for somebody located in Germany.

## Suggested change

Instead of using a link to the UK Government https://www.gov.uk/government/news/public-reminded-to-let-in-fresh-air-when-meeting-others-indoors-to-reduce-the-spread-of-covid-19

link to the English language page
[Coronavirus infection - this is how the coronavirus spreads](https://www.zusammengegencorona.de/en/ansteckung-mit-corona-so-wird-das-coronavirus-uebertragen/) produced by the German "Bundesministerium für Gesundheit (BMG)" which includes the following paragraph:

"**The DHM formula protects from coronavirus infection**

The likelihood of getting infected with the coronavirus via one of the foregoing modes of transmission can be reduced by observing the DHM formula. By adhering to the minimum distance of 1.5 metres, following hygiene rules and masking up, you can protect yourself and those close to you. Another major protective measure is the A in the broader DHM + A formula: Here you can find out how thoroughly airing helps lower the risk of infection through aerosols. You can also help to stem the spread of the virus by using the Corona Warn-App (DHM+A) This is because the app helps you to identify if you have been in contact with an infected person and if this encounter involves a risk of infection."

---

The English and German information are organized differently on the pages of https://www.zusammengegencorona.de from the "Bundesministerium für Gesundheit (BMG)".

A good reference for the equivalent area of concern in the German language would be
https://www.zusammengegencorona.de/informieren/sich-und-andere-schuetzen/

**Comment by MikeMcC399** [comment]
This is a suggestion for change.

If there is agreement to replace the UK Government link by a link to the German Government Federal Ministry of Health site, please let me know and I can submit a PR.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the suggestion. We would welcome corresponding PR!

**Comment by MikeMcC399** [comment]
@dsarkar 
Thank you for your agreement! You can find the PR #2238 proposing this change.
