### ISSUE TITLE
browser-sync does not refresh browser

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2239]
## Where to find the issue

cwa-website

## Describe the issue

This is a testing issue only. It does not affect the production website.

When making source changes to cwa-website, `browser-sync` announces "Reloading Browsers", however it does not refresh the browser contents as it should.

## Steps to reproduce

Execute 

```
npm start
```

Terminal shows
```
[Browsersync] Serving files from: ./public
Finished 'server' after xx ms
Starting 'watch'...
Finished 'watch' after xx ms
Finished 'start-server' after xxx ms
Finished 'default' after xx s
```

Web browser displays http://localhost:8000/en/

Open `src/data/index.json` in an editor.
Make a change, such as changing the title in line 5 and save the change.

```
Starting 'resetPages'...
Finished 'resetPages' after xx ms
Finished 'pages' after x.x s
[Browsersync] Reloading Browsers...
```

Note that browser contents have not changed.
Press `F5` (refresh) in browser
Now the changes which were made are displayed.

## Expectation

When browser-sync displays "Reloading Browsers..." then the contents of the browser should be refreshed.

This is documented in [README - Start server](https://github.com/corona-warn-app/cwa-website/blob/master/README.md#start-server) as:

"The web server uses public as its base directory. It also watches for file changes and refreshes the browser contents if necessary."

It is also a documented function of [Browsersync](https://browsersync.io/).

Synchronized scrolling between multiple browsers also does not work for cwa-website as documented in the Browsersync documentation.

## Workaround

To refresh the page after making a change to the source, press `F5` (refresh) in the browser window.

If there is no solution to this issue, then this hint should be added to the [README - Start server](https://github.com/corona-warn-app/cwa-website/blob/master/README.md#start-server) section.

**Comment by MikeMcC399** [comment]
I am trying to find out the reason for this not working, but I don't know if I will get to the bottom of it.

It works with a simple test page, so there is something about the complexity of the cwa-website which is causing a problem.

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/1784 "Analysis page" with commit https://github.com/corona-warn-app/cwa-website/commit/7e7d2217f04eba716e0981b9508552c5a8187ae0 merged on Oct 1, 2021 introduced a regression concerning the automatic reload of the browser window by `Browsersync` when web site source files were changed.

After this PR, `Browsersync` only worked correctly with the new Analysis page, the other pages no longer reloaded after changes were made.

The analysis page uses the "Content-Security-Policy"
`<meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' 'unsafe-eval' *.coronawarn.app; img-src 'self' *.coronawarn.app data:; connect-src 'self' https://obs.eu-de.otc.t-systems.com/" />` which includes `'unsafe-inline' 'unsafe-eval'`.

Other pages such as /en/index.html had `'unsafe-inline' 'unsafe-eval'` removed. They then used
`<meta http-equiv="Content-Security-Policy" content="default-src 'self' *.coronawarn.app; img-src 'self' *.coronawarn.app data:" />` which did not allow `Browsersync` reload to work.

Adding back `'unsafe-inline' 'unsafe-eval'` restores the functionality of `Browsersync` reload to the other pages.

## Next steps

Would the Open Source Team like me to submit a PR to revert the general removal of `'unsafe-inline' 'unsafe-eval'` from the `Content-Security-Policy` of the pages affected in order to restore `Browsersync` reload functionality to the website?

**Comment by dsarkar** [comment]
Hi @MikeMcC399 ! Thank you very much for the analysis! We will have a look at this!

**Comment by MikeMcC399** [comment]
Hi @dsarkar 
I hope you had a good (short) Christmas break 🎄 🎁 ☃️ and it's good to see you back!
I will submit a PR anyway because I already tried the changes when I was trying to figure out what had gone wrong. This is a new area for me so if there is any different advice I would be happy to take that on board.

I also discovered another issue with rebuilding the blogs during `Browsersync` reload and I will submit that as an issue / PR pair  separately.

**Comment by MikeMcC399** [comment]
PR #2247 now submitted for consideration.

**Comment by MikeMcC399** [comment]
PR #2247 is now merged, so closing this issue.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the wishes! Hope you had/are having also some nice happy Christmas time!


Thanks for the PR!
