### ISSUE TITLE
EU Digital COVID Certificate press release changes validity and booster coding

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2240]
The press release [EU Digital COVID Certificate: Commission adopts binding acceptance period of nine months for vaccination certificates](https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837) from Dec 21, 2021 may affect two aspects documented in the FAQs:

- binding acceptance period of 270 days for travel
- new coding for booster vaccinations

## Booster changes

"In addition, today the Commission has also adapted the rules for the encoding of vaccination certificates. This is necessary to ensure that vaccination certificates showing completion of the primary series can always be distinguished from vaccination certificates issued following a booster dose.

Boosters will be recorded as follows:

- 3/3 for a booster dose following a primary 2-dose vaccination series.
- 2/1 for a booster dose following a single-dose vaccination or a one dose of a 2-dose vaccine administered to a recovered person"

---
Note that this is an EU announcement. The official German government position needs to be monitored and considered also.

---
EU Regulations are:

- [(EU) 2021/2288](https://eur-lex.europa.eu/legal-content/EN-DE/TXT/?uri=CELEX:32021R2288) (Dec 21, 2021) "It shall apply from 1 February 2022. / Sie gilt ab dem 1. Februar 2022."

- [(EU) 2021/2301 ](https://eur-lex.europa.eu/legal-content/EN-DE/TXT/?uri=CELEX:32021D2301) (Dec 21, 2021)

**Comment by MikeMcC399** [comment]
The new coding for booster vaccinations is described in an FAQ update through PR https://github.com/corona-warn-app/cwa-website/pull/2264.

**Comment by MikeMcC399** [comment]
The legal documents referred to in the press release [EU Digital COVID Certificate: Commission adopts binding acceptance period of nine months for vaccination certificates](https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837) from Dec 21, 2021  are still in draft status:

- [Commission Delegated Regulation on the validity of vaccination certificates issued under the EU Digital COVID Certificate framework](https://ec.europa.eu/info/files/commission-delegated-regulation-validity-vaccination-certificates-issued-under-eu-digital-covid-certificate-framework_en)

- [Commission Decision amending Implementing Decision (EU) 2021/1073 laying down technical specifications and rules for the implementation of the trust framework for the EU Digital COVID Certificate](https://ec.europa.eu/info/files/commission-decision-amending-implementing-decision-eu-2021-1073-laying-down-technical-specifications-and-rules-implementation-trust-framework-eu-digital-covid-certificate_en)

Status: Jan 10, 2022

**Comment by MikeMcC399** [comment]
The legal documents referred to in the press release [EU Digital COVID Certificate: Commission adopts binding acceptance period of nine months for vaccination certificates](https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837) from Dec 21, 2021  are now published "in force":

- [Commission Delegated Regulation (EU) 2021/2288 of 21 December 2021 amending the Annex to Regulation (EU) 2021/953 of the European Parliament and of the Council as regards the acceptance period of vaccination certificates issued in the EU Digital COVID Certificate format indicating the completion of the primary vaccination series (Text with EEA relevance)](https://eur-lex.europa.eu/legal-content/EN/TXT/?qid=1643281793602&uri=CELEX%3A32021R2288) (Dec 21, 2021) "It shall apply from 1 February 2022."

- [Commission Implementing Decision (EU) 2021/2301 of 21 December 2021 amending Implementing Decision (EU) 2021/1073 laying down technical specifications and rules for the implementation of the trust framework for the EU Digital COVID Certificate established by Regulation (EU) 2021/953 of the European Parliament and of the Council (Text with EEA relevance)](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32021D2301) (Dec 21, 2021)

Status: Jan 27, 2022

**Comment by MikeMcC399** [comment]
- PR #2377 relates to this issue.

**Comment by MikeMcC399** [comment]
@larswmh 

- What is the plan for PR #2377?

[(EU) 2021/2288 ](https://eur-lex.europa.eu/legal-content/EN-DE/TXT/?uri=CELEX:32021R2288) comes into effect tomorrow, 1 February 2022.

**Comment by Ein-Tim** [comment]
https://www.coronawarn.app/en/faq/#vac_booster_jj needs changing too.

**Comment by Ein-Tim** [comment]
@larswmh & @dsarkar 

When will the FAQs be updated? Currently the FAQs are still on the stand from before 01.02.2022.

**Comment by MikeMcC399** [comment]
- PR #2377 is closed.
- PR #2408 follows on.

**Comment by MikeMcC399** [comment]
- The FAQ article https://www.coronawarn.app/en/faq/#eu_dcc_validity "How long is my certificate valid?​" is updated to say:

"**UPDATE February 1, 2022**

The EU Commission has adopted the EU COVID digital certificate rules, which establish a mandatory 270-day (approximately 9-month) recognition period for vaccination certificates for travel within the EU. As this new rule should apply to Member States from February 1, 2022, therefore, when traveling within the EU, note that your destination country may already apply this rule."

This part of the issue is resolved.

**Comment by MikeMcC399** [comment]
In the FAQ article https://www.coronawarn.app/en/faq/#vac_booster_basics "What is a booster vaccination and how does it appear in the CWA?" it still says:

"The '1 of 1' label for a booster vaccination indicates that it is the first and only vaccination after a COVID-19 disease recovery. Vaccinations with Johnson & Johnson are an exception."

To be able to clearly follow the remaining discrepancies regarding description of boosters and the FAQ I suggest to close this issue and start a new one.
