### ISSUE TITLE
QR-Code Generator: Align input validation with app validation

### ISSUE THREAD

**Issue by LukaHarambasic** [corona-warn-app/cwa-website#2243]
## Where to find the issue

Generate QR Code on https://www.coronawarn.app/de/eventregistration/ with date in the past (can't remember the date/time).

## Describe the issue

When creating Event QR Codes, you can select a date in the past. I think this doesn't make sense in the use case of Event QR Codes. Also, it isn't possible to select dates in the past in the app. Besides that, the QR Code generated by this isn't valid. 

_Affected QR Code_

![E5A2BF7F-4D81-4EF1-B096-6FE054904A1E](https://user-images.githubusercontent.com/22857823/147255396-60d3d966-22e1-43cb-9ef5-49ca362325c1.JPG)

_Result in CWA_

![IMG_497FD0C2D624-1](https://user-images.githubusercontent.com/22857823/147255416-ff861548-3774-4e3c-bf5d-2aa18dd27b65.jpeg)

## Suggested change

Add the same input validation for the QR-Code Generator as it is applied in the app. It shouldn't be possible to generate QR-Codes which are already invalid at the time of generation.

**Comment by Ein-Tim** [comment]
Thanks for opening @LukaHarambasic (nice to see you here)!

I'll ping @bastianjoel here, as he initially developed the QR code generator for the website, maybe he has an idea what's the best way to fix this.

**Comment by dsarkar** [comment]
@LukaHarambasic Indeed, nice to hear from you! We will have a look at this ASAP.

**Comment by dsarkar** [comment]
@LukaHarambasic FYI PR https://github.com/corona-warn-app/cwa-website/pull/2260

**Comment by LukaHarambasic** [comment]
Happy to spot bugs :)

Thanks <3

**Comment by Ein-Tim** [comment]
@LukaHarambasic #2260 has been merged. Can you confirm the fix?

**Comment by dsarkar** [comment]
@LukaHarambasic Happy new year! Has been fixed, closing this issue. Best, DS
