### ISSUE TITLE
Long rebuild time for watched blog change

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2248]
## Where to find the issue

- Input on [cwa-website - blog](https://github.com/corona-warn-app/cwa-website/tree/master/blog)
- Output on http://localhost:8000/en/blog/

## Describe the issue

If there is any change made to a blog source and the gulp `start-server` task is running to display the web contents to http://localhost and to watch for changes, then multiple rebuilds take place and the build takes a long time to complete.

## Steps to reproduce

On a local clone of https://github.com/corona-warn-app/cwa-website execute:
```
npm ci
npm run test:prepare
npm start
```
After the browser starts, navigate to http://localhost:8000/en/blog/.

In an editor, open `blog\2099-01-01-visual-testing\index.md`, make a change in the text and save the change.

The terminal window now fills with `Starting 'pages'...`

Wait for `[Browsersync] Reloading Browsers...` to be shown in the terminal window.

Note that approximately 1000 lines have been output to the terminal window and the elapsed time is about six times longer than the original build and display sequence.

Press F5 in the browser window to display the text changes which were made. (This step is necessary until issue https://github.com/corona-warn-app/cwa-website/issues/2239 is resolved.)

## Analysis

The gulp task `start-server` in [gulpfile.js](https://github.com/corona-warn-app/cwa-website/blob/master/gulpfile.js) starts the server and then watches for changes.

When a change is made to one of the blog source files being watched in `blog/**/*` the `buildBlogFiles` function is triggered. This (re-)creates subdirectories and `index.html` (intermediate html) files in `src/pages/{de,en}/blog/`. Then the `pages` function is triggered which picks up everything and compiles into `public` using Panini.

The watch function watches also `src/pages/**/*.html`. This is problematic because of the number of changes to `src/pages/**/*.html` caused by running the `buildBlogFiles` function. Each change causes the `pages` and `reload` function to run, leading to a multitude of unnecessary calls. 

`pages` is already called through the `blog/**/*` watch. `reload` is triggered later through the watch on `src/data/**/*.{js,json,yml}` because `buildBlogFiles` places `blogentries.json` into `src/data` which triggers `resetPages`, `pages` and `reload` in sequence.

## Suggested change

The section in [gulpfile.js](https://github.com/corona-warn-app/cwa-website/blob/master/gulpfile.js) which watches for changes in `src/pages/**/*.html` should be excluded from watching files produced by the `buildBlogFiles` function.

The pages to be excluded from watching are
`src/pages/{de,en}/blog/*-*-*-*/`
and
`src/pages/{de,en}/blog/*-*-*-*/index.html`.

The same issue also applies to the Science blog, however because there are only 4 science blog articles currently, completion of the Science blog rebuild is not delayed so much that it causes a practical problem.

**Comment by MikeMcC399** [comment]
PR ##2249 submitted to resolve this issue.

**Comment by MikeMcC399** [comment]
Thanks to @browkin for testing!
PR #2249 is merged and I verified that it works after the merge by separately changing `src\data\blog.json` and `src\data\science.json`, then observing that the web is rebuilt quickly and with only a small number of steps.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reporting and providing PR!
