### ISSUE TITLE
Wrong use of narrow no-break space (U+202f) in FAQ (DE)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2251]
## Where to find the issue

- `src\data\faq_de.json` displaying on
- https://www.coronawarn.app/de/faq/#val_service_no_valid_dcc "Warum erhalte ich die Meldung, dass kein geeignetes Zertifikat vorhanden ist?" 

## Describe the issue

The `src\data\faq_de.json` FAQ source file contains multiple instances where the Unicode character [U+202f](https://en.wikipedia.org/wiki/Whitespace_character#NNBSP) is used in incorrect places.

It is particularly noticeable in https://www.coronawarn.app/de/faq/#val_service_no_valid_dcc "Warum erhalte ich die Meldung, dass kein geeignetes Zertifikat vorhanden ist?" where it looks like "Sienur" is one word.

![val_service_no_valid_dcc](https://user-images.githubusercontent.com/66998419/147475772-96057037-7c41-4d90-b188-f3b7f0945d73.png)

## Suggested change

Review each use of narrow no-break space (`U+202f`) in `src\data\faq_de.json` and correct if necessary.

**Comment by MikeMcC399** [comment]
PR #2252 submitted to resolve this issue.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reporting.
