### ISSUE TITLE
Comments and suggestions for #val_service_basics (EN)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2253]
## Where to find the issue

https://www.coronawarn.app/en/faq/#val_service_basics "Questions and answers about certificate verification during ticketing"

## Describe the issue

1. The list "In the pandemic, they therefore need reliable access management for business premises, factory halls, aircraft, trams, hotels and restaurants or events." is not exhaustive. What about local and long-distance travel, like buses, trains and ferries for instance?

2. The abbreviation "BMG" is not explained.

3. The grammar is gender specific.

4. The app is called "Corona Warning app" in one place.

5. "communicate encrypted" sounds strange

6. The term "test" is used where "check" is meant. The term "test" should be reserved for a medical virus test, and should not be used for an IT validation check.

7. The term "ISO 27001" is used without explanation.

8. The link https://ec.europa.eu/health/sites/health/files/ehealth/docs/covid-certificate_traveller-onlinebooking_en.pdf is provided in plain text and there is no rel='noopener noreferrer' in the hyperlink.

9. The link https://github.com/eu-digital-green-certificates/dgca-validation-service is provided in plain text and there is no rel='noopener noreferrer' in the hyperlink.

10. There is no further explanation of GDPR.

11. The approval process for new validation service providers through BMG is mentioned without providing any further details.

## Suggested change

1. Add "for example" to the list "In the pandemic, they therefore need reliable access management for business premises, factory halls, aircraft, trams, hotels and restaurants or events."

2. Add "Federal Ministry of Health (Bundesministerium für Gesundheit, BMG)" to explain the abbreviation "BMG"

3. Use gender general pronouns e.g. "If the buyer requires a valid certificate for the event visit, he can carry out the certificate check immediately upon purchase." instead of "he" use "they".

4. Use the standard app name which is used elsewhere in the FAQs "Corona-Warn-App".

5. Write "use encrypted communication".

6. Replace "test" by "check".

7. Link "ISO 27001" for instance to https://en.wikipedia.org/wiki/ISO/IEC_27001.

8. Integrate the link https://ec.europa.eu/health/sites/health/files/ehealth/docs/covid-certificate_traveller-onlinebooking_en.pdf into the text.

9. Integrate the link https://github.com/eu-digital-green-certificates/dgca-validation-service into the text.

10. Link GDPR to https://en.wikipedia.org/wiki/General_Data_Protection_Regulation.

11. Provide contact details and documentation for potential providers of a validation service.

---
Internal Tracking ID: [EXPOSUREAPP-11114](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11114)

**Comment by MikeMcC399** [comment]
The above comments are for the English language version, some of the comments also apply to the German version as well:

https://www.coronawarn.app/de/faq/#val_service_basics "Fragen und Antworten zur Zertifikatsprüfung bei Ticketbuchungen".

I will submit two PRs (one for each language version) with concrete change suggestions tomorrow.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the suggestions.

**Comment by MikeMcC399** [comment]
I have submitted
- PR #2255 for the English version
- PR #2256 for the German version

There are more changes suggested in the English version than in the German version, since the English version is (presumably) a translated text.

In both versions I corrected the security of the hyperlinks, added hyperlinks to explained terms used and integrated the links into the text by using the titles of the documents being referred to.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.

**Comment by MikeMcC399** [comment]
Both PRs (#2255 and #2256) are now merged, so this issue can be considered resolved.

The (optional new) suggested links to Wikipedia were removed before merging.

The last point in the list (Provide contact details and documentation for potential providers of a validation service) is covered in a separate issue (#2218).
