### ISSUE TITLE
`rat_what_if_positive_result` shows PDF placeholder

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2254]
## Where to find the issue
- https://www.coronawarn.app/de/faq/#rat_what_if_positive_result
- https://www.coronawarn.app/en/faq/#rat_what_if_positive_result

## Describe the issue
The FAQ entry shows a PDF placeholder: 
<img width="1000" alt="Bildschirmfoto 2021-12-27 um 20 34 21" src="https://user-images.githubusercontent.com/67682506/147501925-681fb4e3-7a72-4c24-8dfd-0d9a2f704e12.png">

## Suggested change
Remove the placeholder or show the PDF instead of the placeholder.

## Additional information
I will take a look at this and see whether I am able to fix this.

**Comment by Ein-Tim** [comment]
<img width="879" alt="Bildschirmfoto 2021-12-28 um 12 07 22" src="https://user-images.githubusercontent.com/67682506/147560111-8b51ef46-e7c5-4328-ae56-a64e59a49fd7.png">

Locally, I have no problem viewing the preview, there is no placeholder but the actual PDF shown. 

As I can't fix something I can't reproduce locally, I can't fix this issue myself, sorry.

Maybe @MikeMcC399 has an idea, I guess this could be related to CSP, or something similar which is applied on the PROD server but not on local builds.

**Comment by dsarkar** [comment]
@Ein-Tim 

file should be renamed .png (small):

This works: https://www.coronawarn.app/assets/documents/DE_CWA_RKI-Plakat_Schnelltests_v2-kl-1.PNG
This does not work: https://www.coronawarn.app/assets/documents/DE_CWA_RKI-Plakat_Schnelltests_v2-kl-1.png

you are using mac, then it works locally! 


Do you want to provide PR?

**Comment by Ein-Tim** [comment]
@dsarkar 

So PDF -> png? 

Yes, I'm using the latest macOS.

I can provide a PR!

**Comment by MikeMcC399** [comment]
If you make the change for a PR on an operating system which is insensitive to filename case, then you may need to use git to rename the file:

`git mv src/assets/documents/DE_CWA_RKI-Plakat_Schnelltests_v2-kl-1.PNG src/assets/documents/DE_CWA_RKI-Plakat_Schnelltests_v2-kl-1.png`

At least on Windows the change is otherwise not recognized.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> So PDF -> png?

Not "PDF", "PNG".

**Comment by Ein-Tim** [comment]
@MikeMcC399 

But at the moment, the file is a PDF, or am I mistaken? 

The file: https://www.coronawarn.app/assets/documents/DE_CWA_RKI-Plakat_Schnelltests_v2-kl.pdf

**Comment by MikeMcC399** [comment]
@Ein-Tim 
There are two files involved. One is a png, the other is a pdf.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Ah, now I understand! I'm on my phone currently, so sorry for the questions! I will prepare a PR later on (:
