### ISSUE TITLE
Refused to apply inline style (app.js)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2258]
## Where to find the issue

https://www.coronawarn.app/en/

## Describe the issue

An error message "Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' *.coronawarn.app"." appears in the Google Chrome console when viewing https://www.coronawarn.app/en/.

## Steps to reproduce

1. Open Google Chrome
2. Press F12 (Developer Tools) and select `Console`
3. Enter https://www.coronawarn.app/en/ in address field
Note error message:

"Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' *.coronawarn.app". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback."

linked to https://www.coronawarn.app/assets/js/app.js

This error also occurs when running locally with
`npm start` and viewing http://localhost:8000/en/ with Google Chrome.

## Suggested change

Please check if this error needs to be addressed or if it can be ignored.

**Comment by MikeMcC399** [comment]
It is interesting to see from "View page source" of https://www.coronawarn.app/en/ that 

`<meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' 'unsafe-eval' *.coronawarn.app; img-src 'self' *.coronawarn.app data:" />` 

is now set from PR https://github.com/corona-warn-app/cwa-website/pull/2247, however the error message has not changed and it still suggests for instance adding` 'unsafe-inline' `.

So it appears that the `Content-Security-Policy` in the page source is ignored and is being overridden by server setup parameters.

**Comment by mtb77** [comment]
Hi @MikeMcC399 that's correct. The CSP is just set for testing purposes as the server settings will override the settings in the page.

**Comment by dsarkar** [comment]
@MikeMcC399 As discussed with @mtb77 we can ignore these messages. We suggest closing this issue. Thanks!

**Comment by MikeMcC399** [comment]
@dsarkar 
Thank you for your feedback. I can't see anything actually wrong on the page https://www.coronawarn.app/en/ so I will close as you suggest.
