### ISSUE TITLE
Make FAQ article text hidden until expanded

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2259]
## Where to find the issue

- https://www.coronawarn.app/en/faq/ "Frequently Asked Questions about the Corona-Warn-App" and
- https://www.coronawarn.app/de/faq/ "Häufig gestellte Fragen zur Corona-Warn-App"

## Describe the issue

Over the past 18 months the FAQs have grown extensively and now cover a vast amount of material. Especially on a mobile device there is a massive amount of text to scroll through to find a certain article, even if the results are shortened by using a search term. It has become quite difficult to find information.

## Suggested change

Change the FAQ articles so that only the titles are displayed by default.

- Add a function to expand one article e.g. https://www.coronawarn.app/en/faq/#who_can_help
- Add a function to expand all articles from one section e.g. from https://www.coronawarn.app/en/faq/#support
- Add a function to expand all articles 
- Add a function to search only in titles

An example of an FAQ which displays only titles initially is https://digitaler-impfnachweis-app.de/en/faq.

## Benefits

Only displaying the titles by default means that it is easier to scroll though the titles to find subject matter of interest because the amount of text to be viewed is then much limited. The article body is not displayed until needed.

**Comment by Ein-Tim** [comment]
PR: #2261

**Comment by MikeMcC399** [comment]
Thanks to @browkin for PR #2261!

I did not realise that the functionality to collapse an individual FAQ article was already built in to the web! The long dash at the end of each title currently collapses each article, then a plus symbol is displayed which allows the article to be displayed fully.

So now, with PR #2261, each article will start collapsed.

**Comment by dsarkar** [comment]
@MikeMcC399 

1.
I wonder if we should keep the "mini-indexes" open?
https://www.coronawarn.app/en/faq/#check_in_index

2. 
We probably should do such indexes for each section, and then keep those open.

**Comment by MikeMcC399** [comment]
@dsarkar 
It definitely makes sense to have articles, which are indexes of other articles, open by default.

For the future, I'm not sure the best way to do this. I would only create extra manual indexes if users will need them to find an article. Manual indexes are more difficult to maintain.

**Comment by MikeMcC399** [comment]
The main request from this issue has been fulfilled by PR #2261.

This issue is now being closed and the remaining enhancement suggestions are transferred to a new issue #2273.
