### ISSUE TITLE
Very large interactive graphics in Science 2

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2272]
## Where to find the issue

https://www.coronawarn.app/en/science/2021-07-08-science-blog-2/#51-distribution-by-district

## Describe the issue

https://www.coronawarn.app/en/science/2021-07-08-science-blog-2/#51-distribution-by-district contains a large (5.5 MB) interactive graph ("Fig. 6: EDUS participants by 3-digit postcode and district.").

This shows as a poor performance score with Lighthouse "Avoid enormous network payloads" and prevents migration to Node 16 because Panini cannot process the amount of data and it produces an error:

```
Error: Panini: rendering error occured.
RangeError: Maximum call stack size exceeded
```

See also https://github.com/corona-warn-app/cwa-website/issues/2155#issuecomment-998550089 in "Website migration steps for Nodejs 16"

### Performance report

Execute:
1. `npm install lighthouse -g`
2. `lighthouse https://www.coronawarn.app/en/science/2021-07-08-science-blog-2/ --view`

Note very low performance score of 16 and diagnostic "Avoid enormous network payloads".

### Panini issue

On Ubuntu, execute:

1. `nvm install lts/gallium`
2. `nvm use lts/gallium`<br>shows `Now using node v16.13.1 (npm v8.1.2)`
3. `npm ci`
4. `npm run build`<br>Panini fails with

```
'pages' errored after xx s
Error: Panini: rendering error occured.
RangeError: Maximum call stack size exceeded
```

To revert after test:
1. `nvm use lts/fermium`
2. `npm ci`
3. `npm run build`

## Suggested change

Remove "Fig. 6: EDUS participants by 3-digit postcode and district." https://www.coronawarn.app/en/science/2021-07-08-science-blog-2/#51-distribution-by-district as an interactive graph and leave only the static graph.

**Comment by brifemu** [comment]
@MikeMcC399 
FYI https://github.com/corona-warn-app/cwa-website/pull/2278

**Comment by MikeMcC399** [comment]
Thanks to @brifemu for the PR!

- PR #2278 solves the issue with Panini, which was a gating factor for migration to Node 16 (see #2155).

The PR does not solve this performance point. There is still 5MB of data transported to the user's browser. I'm not sure how important this is in practice. Mobile devices already receive only the static graphs.

**Comment by MikeMcC399** [comment]
I am closing this issue now, since the major problem with Panini is solved.

Embedding the graph data for the interactive graphs into the `index.md` / `index_de.md` source files affects all the science blogs, so this should be addressed separately if it is found to be causing a general problem for users.
