### ISSUE TITLE
Enhancements to FAQ article expansion and collapsing

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2273]
## Where to find the issue

- https://www.coronawarn.app/en/faq/ "Frequently Asked Questions about the Corona-Warn-App" and
- https://www.coronawarn.app/de/faq/ "Häufig gestellte Fragen zur Corona-Warn-App"

## Describe the issue

- PR https://github.com/corona-warn-app/cwa-website/pull/2261 has implemented displaying FAQ articles collapsed by default. 
- This is a follow-on from issue https://github.com/corona-warn-app/cwa-website/issues/2259.

## Suggested enhancements

1. Add a function to expand all articles from one section e.g. from https://www.coronawarn.app/en/faq/#support
2. Add a function to expand all articles - Implemented: see PR #2293
3. Add a function to search only in titles

**Comment by Ein-Tim** [comment]
Additional request: Currently, when one navigates to an entry from one of the indexes, the entry stays collapsed. IHMO, it should be expanded in this case.

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/2293 expands and collapses all articles which addresses suggestion 2.

**Comment by MikeMcC399** [comment]
Closing this issue since the FAQ https://www.coronawarn.app/en/faq/ has been redesigned for better usability. If I have any suggestions for the new FAQ layout I will make new posts.
