### ISSUE TITLE
Incorrect instructions to delete a Rapid Test Profile for Android

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2280]
## Where to find the issue

- https://www.coronawarn.app/en/faq/#rat_profile_create_edit_delete "How can I create, edit and remove a rapid test profile?"
- https://www.coronawarn.app/de/faq/#rat_profile_create_edit_delete "Wie kann ich ein Schnelltest-Profil anlegen, bearbeiten und entfernen?"

## Describe the issue

The Android app text associated with deleting a Rapid Test Profile has been changed multiple times through different versions and the FAQ instructions are now inaccurate.

- https://www.coronawarn.app/en/faq/#rat_profile_create_edit_delete "How can I create, edit and remove a rapid test profile?"

Version | Text (EN) | Text (DE)
--- | --- | ---
2.3 - 2.5 | Remove | Entfernen
2.6 - 2.14 | Delete Rapid Test Profile | Schnelltest-Profil entfernen
2.15 | Delete Rapid Test Profile | Schnelltest-Profil löschen

The confirmation text in English has been consistently "DELETE" and in German consistently "LÖSCHEN" throughout all versions.

## Suggested change

Change "remove" in title to "delete"
"How can I create, edit and remove a rapid test profile?"

Change "entfernen" in title to "löschen"
"Wie kann ich ein Schnelltest-Profil anlegen, bearbeiten und entfernen?"

Wie kann ich ein Schnelltest-Profil anlegen, bearbeiten und entfernen?

Adapt Android text according to above table.

**Comment by MikeMcC399** [comment]
I can submit a PR for the Android changes, however I suspect that the text for iOS may also need changing, so I will first wait for feedback.

**Comment by Ein-Tim** [comment]
FYI: I posted the steps under iOS in https://github.com/corona-warn-app/cwa-wishlist/issues/517#issuecomment-1004993072

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thank you for your video. That only covered the English text, but I saw from the iOS repo that the German text is now the same as on Android, so I had enough information to update the FAQs.

**Comment by MikeMcC399** [comment]
- PR #2281 is now submitted to update the FAQs.

**Comment by MikeMcC399** [comment]
This issue is now resolved due to PR #2281 (and #2285).
