### ISSUE TITLE
API-Endpoint

### ISSUE THREAD

**Issue by JonathanN1203** [corona-warn-app/cwa-website#2283]
Servus,

Spricht etwas dagegen, das man folgende Links in seiner Webseite nutzt um die Daten von der CWA abzufragen
https://obs.eu-de.otc.t-systems.com/obs-public-dashboard/json/v1/cwa_public_dashboard_data.json
https://obs.eu-de.otc.t-systems.com/obs-public-dashboard/json/v1/nested_cwa_public_dashboard_data.json

Liebe Grüße
Jonathan

**Comment by dsarkar** [comment]
@JonathanN1203 Thanks for the question. We will come back to you.


---
Corona-Warn-App Open Source Team

**Comment by JonathanN1203** [comment]
@dsarkar is it allowed to use the links?

**Comment by dsarkar** [comment]
@JonathanN1203 Let's say it this way: This is data which is publicly available, so I cannot see why one should not be able to use it.

**Comment by Ein-Tim** [comment]
@JonathanN1203 Was your question sufficiently answered by @dsarkar or are we still waiting for final feedback here?
