### ISSUE TITLE
Analysis page sometimes shows "No data to display" although reloading the site shows data 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2286]
## Where to find the issue
- https://www.coronawarn.app/de/analysis/
- https://www.coronawarn.app/en/analysis/

## Describe the issue
The CWA dashboard sometimes shows "No data to display" although the data is actually available when reloading the page. 

https://user-images.githubusercontent.com/67682506/148298367-5e1f1df5-6f0d-4d18-a73c-969038914289.mov

## Suggested change
I have no idea when this issue occurs and can't reliable reproduce it.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

In your title you wrote the word "sontemis". Did you perhaps mean "sometimes"?

I would simply suspect a transient network issue if you get the error message "No Data to display" which disappears when you refresh the page.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks, yes, this was a typo. I corrected it.

I'm not too sure whether this is really a network issue, as I can access all other pages correctly and I monitored my network connection on the second monitor and did not see an issue. However, I'll try to reproduce this and dive deeper.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The data comes from the network location https://obs.eu-de.otc.t-systems.com/ which is different to the network location https://www.coronawarn.app/, so you may be able to access other pages successfully at the same time as having difficulty in getting data for the https://www.coronawarn.app/en/analysis/ page.

If it happens again, you could try accessing https://obs.eu-de.otc.t-systems.com/obs-public-dashboard/json/v1/nested_cwa_public_dashboard_data.json directly in a separate browser window.

You could also try network troubleshooting. In a bash terminal on Windows, that would be:

```
tracert obs.eu-de.otc.t-systems.com
Tracing route to obs.lz01.eu-de.otc.t-systems.com [80.158.24.237]
```

**Comment by Ein-Tim** [comment]
@MikeMcC399 

What do you think of this? This time, I encountered this on my phone. However, I solved it without reloading the page (which underlines the fact that the data is already there, or?).

Take a look:

https://user-images.githubusercontent.com/67682506/148525413-4c3d038b-d098-4086-9421-3bb474f5c5e7.MOV

**Comment by MikeMcC399** [comment]
@Ein-Tim 

We probably need feedback from the JavaScript experts to explain what is happening. I would still guess that it is due to network latency / delays / other issues.

Since there are multiple IP addresses associated with the name `obs.eu-de.otc.t-systems.com` there may be load balancer hardware in the Open Telekom Cloud or other technology involved. I couldn't see anything wrong when I looked yesterday.

```
nslookup obs.eu-de.otc.t-systems.com
Server:  nsrcustm1-m1-01.mip-platform.net
Address:  2a02:2457:30c:101::11

Non-authoritative answer:
Name:    obs.lz01.eu-de.otc.t-systems.com
Addresses:  80.158.25.237
          80.158.24.238
          80.158.25.134
          80.158.24.237
          80.158.25.133
          80.158.25.132
Aliases:  obs.eu-de.otc.t-systems.com


```

**Comment by Ein-Tim** [comment]
Okay, maybe @brifemu could take a look.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
If you could catch the error when you have the browser in developer mode, that would show more.

I realised also that if the webpage cannot get the data from 
`https://obs.eu-de.otc.t-systems.com/obs-public-dashboard/json/v1/nested_cwa_public_dashboard_data.json`
it falls back to downloading from
`https://www.coronawarn.app/analyseData.json`
instead.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I'll try my best!

**Comment by brifemu** [comment]
I have tried to simulate the error and have not been able to. I have tried by simulating a slow connection, cutting the download during the page load, but I have not gotten a similar result. I'll keep trying to reproduce it these days.

**Comment by Ein-Tim** [comment]
Thank you @brifemu!

I will try my best to capture this in the dev console.

**Comment by Ein-Tim** [comment]
I just experienced this again. There seems to be nothing helpful in the console:


https://user-images.githubusercontent.com/67682506/149553820-f93c371a-8292-44c8-8ad2-fdd5e3cde0da.mov

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Which browser are you using?
I would be looking in the Network (Netzwerk) tab for issues since the data is fetched over the network.
You would need to have this open **before** the error occurs (at least that is the way that Chrome and Firefox work).

**Comment by Ein-Tim** [comment]
@MikeMcC399

As always, I'm using Safari. I also think it's necessary to open the console before the issue occurs, I will try to reproduce it with the console active.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Are you still seeing this issue?

**Comment by Ein-Tim** [comment]
I will try to reproduce it.

**Comment by Ein-Tim** [comment]
I'll close this issue for now, as it is neither easy to reproduce nor a problem many users are experiencing. Additionally, it can easily be worked around.
