### ISSUE TITLE
Wrong "Daily count" on the figures "Test results - PCR tests" and "Test results - Rapid antigen tests" on the analysis page

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2287]
## Your Question

* Website URL Path: https://www.coronawarn.app/en/analysis/
* Line / Paragraph: "Test results" and then "Test results - PCR tests" and/or "Test results - Rapid antigen tests" 

What does "Daily count" mean? It is shown above the positive tests and I would guess that this means that on this date x persons were tested positive. But why isn't "Daily count" shown above "Invalid" and "Negative" too? This does not really make sense to me, as all the data shown there is the "Daily count", or? 

When I switch to the "Sorted by calendar week" view this makes even less sense to me. 

Here's a screenshot: 

![Bildschirmfoto 2022-01-05 um 23 37 36](https://user-images.githubusercontent.com/67682506/148299562-fcd780b8-9dfa-4cde-99d3-d828770ee40f.png)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

It's a formatting and labelling bug.

## Steps to reproduce

1. Open https://www.coronawarn.app/en/analysis/
2. View "Transmitted and registered test results" graph using default selections (Last 28 days, Daily)
3. Click on "PCR tests"
4. Hover with the mouse over the graph
5. Note the data formatting

The label "Daily count" is below a separating line and above the value and label for "Positive"

## Expected display

The "Daily count" label should not be displayed.
The Positive value should be directly below the Negative value without any separating line.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I also thought that this might be a bug! Thanks for confirming. 

@dsarkar Please, take a look at this. Thanks.

**Comment by MikeMcC399** [comment]
This is an area that @brifemu has worked on in the past.  He probably has a public holiday today though.

**Comment by brifemu** [comment]
@Ein-Tim 
FYI https://github.com/corona-warn-app/cwa-website/pull/2290

**Comment by MikeMcC399** [comment]
@Ein-Tim 

It's up to you if you want to change the description, but now the bug has been identified, a title such as:

Wrong "Daily count" label on Analysis / Test result page

would be closer to describing the real issue.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I changed the title, thanks.

I can confirm that this issue has been fixed, so closing this.
