### ISSUE TITLE
No need to wait 24 hours before opening the app as suggested on website

### ISSUE THREAD

**Issue by MikeJayDee** [corona-warn-app/cwa-website#230]
## Where to find the issue

On the homepage of the website coronawarn.app the fourth the pieces of advice under "This is how the app works best" is to **_"open the app once a day after 24 hours."_**

It has also been communicated via the press that opening after less than 24 hours could be problematic; a Spiegel Online article states: _"Wenn die App beispielsweise schon nach 23 Stunden und 59 Minuten geöffnet wird, kann dies laut einem SAP-Sprecher dazu führen, dass dann nicht die tagesaktuelle Liste aller als infiziert bestätigten App-Nutzerinnen und -Nutzer abgerufen wird."_

## Describe the issue
At least based on my experience on Android, I don't think that it is correct that one needs to wait for 24 hours to initiate a new check. My understanding is that it is possible to make one check every calendar day UTC (i.e. between 2 am CEST on one day and 2 am CEST on the next day).

**This means that you can open the app at any time during the day**; if an automatic background check has been done between 2 a.m. and the time of opening the app, no new check will be initiated. If no check has been initiated yet since 2 a.m., the check will be carried out at the time the app is opened.

Crucially, if background checks are for some reason not working, **there is no problem to open the app on one day at 18:00, and at 10:00 on the next day**. In both cases, the app will update correctly when opening the app. And there is certainly no issue if you open the app at 15:01 on one day, and at 14:59 on the next day.

## Suggested change
The advice should read _"To be on the safe side, open the app once a day"_ instead of _"To be on the safe side, open the app once a day after 24 hours"_.  

## Caveat
Please note that I only use Android, and am not certain that the behaviour is exactly the same on iOS.

**Comment by tkowark** [comment]
The behaviour on iOS is indeed different, as the quota there is only reset after 24h. To avoid confusion by creating an `if android then do x, if ios then do y` kind of structure, it was settled to go for the one size fits all hint.

We'll discuss if and how we can get more specific for Android.

For version 1.2 there is a feature in progress that shows when the next update is possible, at least for manual mode. We'll have to check whether this will show different timers for Android and iOS.

**Comment by MikeJayDee** [comment]
I see. That's of course unfortunate; the implementation on Android is more user-friendly.

**Comment by MikeMcC399** [comment]
https://www.coronawarn.app/en/blog/2020-11-25-corona-warn-app-version-1-7/ says:

"With Corona-Warn-App Version 1.7, the exposure check can be run several times a day so that users are informed about possible risk encounters sooner. This repeated daily check is performed automatically. However, it requires a Wi-Fi connection. The standard daily exposure check is still performed once a day, no matter if the smartphone is connected to a Wi-Fi network or not."

so don't know what should happen to the recommendation:

"4. To be on the safe side, open the app once a day after 24 hours"

on https://www.coronawarn.app/en/ in the section "**This is how the app works best**".

Is it still necessary? Does "after 24 hours" need to be part of the recommendation?

**Comment by Ein-Tim** [comment]
@MikeMcC399 
Hourly packages are only fetched if the phone uses WLan and not Mobile Data, users who are always using Mobile Data (weak/no Internet, unlimited Mobile Data contract) should still wait 24h to ensure a check...

But I think something like:
"Open the App regularly, best once a day." 
would be sufficent.

**Comment by MikeMcC399** [comment]
It depends if the background updates are now considered reliable or not. See https://github.com/corona-warn-app/cwa-app-android/issues/933#issuecomment-735723472 where the Android hot topic "Background update does not work, despite v.1.1.1 and “prioritized background activity”" is considered for closure.

**Comment by dsarkar** [comment]
Hi all, thanks for all the comments. PR with a fix is prepared.
