### ISSUE TITLE
Plain links in yesterdays blog post

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2308]
## Where to find the issue
- https://www.coronawarn.app/de/blog/2022-01-11-cwa-omikron/
- https://www.coronawarn.app/en/blog/2022-01-11-cwa-omikron/

## Describe the issue
At the very end of the blog post, it links to another blog post. This link is visible in plain text.

## Suggested change
Don't use plain text links.

## Additional information
I'll provide a PR for this.

**Comment by MikeMcC399** [comment]
@Ein-Tim

Thank you for volunteering! Something like

"Lesen Sie den Blog-Artikel [Was tun bei einer roten Kachel?](/de/blog/2021-12-15-cwa-red-tile-guidance/) für mehr Informationen."

would be much better. Or maybe you can integrate it into the previous sentence better than that.

Could you also correct the missing `&nbsp;` in `z.B.`?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Will do that, PR follows by today's evening.

**Comment by Ein-Tim** [comment]
PR #2309 created.
