### ISSUE TITLE
Inconsistent use of terms for Contact Journal

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2315]
## Where to find the issue

https://www.coronawarn.app/

## Describe the issue

The app uses the terms:
- Journal / Contact Journal (EN)
- Tagebuch / Kontakt-Tagebuch (DE)

Blogs, FAQ and Glossary are inconsistent.

Additional English terms used:
- Contact diary

Alternate German spelling used:
- Kontakttagebuch

When searching, if different terms are used for the same object, then the results will not be consistent.

Readers may also be confused by the random use of different terms.

## Suggested change

Align all terms in the Blogs, FAQ and Glossary https://www.coronawarn.app/ to use the same terms and spelling as the app:
- Journal / Contact Journal (EN)
- Tagebuch / Kontakt-Tagebuch (DE)

**Comment by MikeMcC399** [comment]
Please let me know if you would like a PR for this.

The glossary should certainly use the same name as the app.
I would also expect the FAQ to be consistent.

Regarding the blogs: it feels a bit like rewriting history to make changes there, but I think that it would also be beneficial to clean them up in this regard.

**Comment by dsarkar** [comment]
@MikeMcC399 Blog should be aligned as well.

**Comment by MikeMcC399** [comment]
- The issue is fixed by PR #2317 which is already merged, however
- this has caused a side-effect with the Cypress test suite, which should be fixed by PR https://github.com/corona-warn-app/cwa-website/pull/2318
