### ISSUE TITLE
Analysis graph full-screen display too large

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2321]
## Where to find the issue

- https://www.coronawarn.app/en/analysis/ "Corona-Warn-App (CWA): Key performance indicators"
- https://www.coronawarn.app/de/analysis/ "Corona-Warn-App (CWA): Kennzahlen"

## Describe the issue

Full-screen display of any graph on https://www.coronawarn.app/en/analysis/ sometimes displays the graph larger than the available browser window.

## Steps to reproduce

1. Open browser and resize to take one half of screen height and one half of screen width (this effectively uses one quarter of the screen's available area)
2. Open https://www.coronawarn.app/en/analysis/ in the existing browser window
4. Scroll down to Downloads graph
5. Click on the full-screen icon of the Downloads graph
6. Note that the graph extends vertically outside of the viewable area

Reproducible with:
- Google Chrome
- Mozilla Firefox

## Expected behavior

The full-screen display option in the analysis graphs should display the full graph inside the available browser window display area.

## Suggested change

Change the graph resizing to use the available browser area.

**Comment by MikeMcC399** [comment]
- PR #2323 improves the situation. The displayable part of re-sized graph now fits in the window, 
- however I am seeing a lot of white graph below the legend:

![image](https://user-images.githubusercontent.com/66998419/149338587-9563aff5-a1e9-4124-b25e-3adc16ec7d27.png)

This is on both Google Chrome and Mozilla Firefox.

**Comment by dsarkar** [comment]
related issue:
- vertical screen
- OS: Windows 10 Enterprise (Version 10.0.18363 Build 18363)
- Browser: Firefox (Version 91.4.0esr (32-Bit))
- Auflösung: 1080 x 1920

![image](https://user-images.githubusercontent.com/1409741/149752445-3d7ead07-cf6c-43e8-8a34-9b0db7c738d6.png)

**Comment by MikeMcC399** [comment]
It is also possible to select full screen, which can display a graph with no scroll-bar, depending on the size / geometry of the browser window. Then if the browser window size is reduced the graph does not resize, it is cut off and there is no scroll-bar to correct the situation.

**Comment by MikeMcC399** [comment]
- PR #2350 does not fix the remaining issue mentioned in https://github.com/corona-warn-app/cwa-website/issues/2321#issuecomment-1012137062. This is reproducible using the steps in the original post.

- Additional steps to test in Windows 11:
1. Open a Chrome window and resize to one third standard using Windows 11 built-in snap-to window resizing.
2. Open https://www.coronawarn.app/en/analysis/ in the existing browser window
Scroll down to Downloads graph.
Click on the full-screen icon of the Downloads graph
Note that the graph is fully displayed and is lacking a scroll-bar.
3. Resize to one quarter window. Graph is cut off and no vertical scroll-bar is available.
4. Click graph full-screen icon twice to recover.

**Comment by brifemu** [comment]
@MikeMcC399 
FYI: https://github.com/corona-warn-app/cwa-website/pull/2375

**Comment by MikeMcC399** [comment]
The only remaining cosmetic issue is when clicking on the full-screen icon as in the original steps to reproduce, the window does not scroll to the graph. The size of the graph does fit the window though.

**Comment by MikeMcC399** [comment]
@brifemu 
This is the result of clicking on the full-screen icon. The graph has not scrolled into view:

![image](https://user-images.githubusercontent.com/66998419/151572961-2f754a19-9a13-4192-ab74-34e35555d742.png)

Is this something that you will fix?

**Comment by MikeMcC399** [comment]
- The original issue is resolved. 
- A remaining issue is transferred to https://github.com/corona-warn-app/cwa-website/issues/2499
