### ISSUE TITLE
"No Data to display" message in Analysis

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2325]
## Where to find the issue

- https://www.coronawarn.app/en/analysis/ "Corona-Warn-App (CWA): Key performance indicators"
- https://www.coronawarn.app/de/analysis/ "Corona-Warn-App (CWA): Kennzahlen"

## Describe the issue

If all available data is deselected from any of the graphs on the Analysis page, then a message "No Data to display" is displayed.

1. The message in English is incorrectly capitalized.
2. The English language message is shown on the German screen.

## Steps to reproduce

1. Open https://www.coronawarn.app/en/analysis/ in browser
2. Take default "Last 28 days" and "Daily" selections
3. Select "7-day moving average"
4. On Downloads graph click "Total", "Android" and "iOS"
5. Note the message "No Data to display"

![no data to display EN](https://user-images.githubusercontent.com/66998419/149337273-bafa3cb1-11dd-4e8f-8295-84c8d11e9d89.jpg)

6. Switch to https://www.coronawarn.app/de/analysis/ and notice that the same English language message is output on the German screen.

![no data to display DE](https://user-images.githubusercontent.com/66998419/149337295-4690efc5-d19e-4e59-9ad0-cc481429c4ff.jpg)

## Expected behavior 

1. The English language message should be consistently capitalized, either as "No data to display" or "No Data to Display".
2. On the German screen the message should be in German.

## Suggested change

1. Change the message in English to "No data to display"
2. Ensure that a different, and German language, message is displayed on the German screen such as "Keine Daten"

Alternatively, if this message only appears if all data has been de-selected, change the message to:
1. "No data selected for display"
2. "Keine Daten zum Anzeigen ausgewählt"

**Comment by brifemu** [comment]
@MikeMcC399 
FYI: https://github.com/corona-warn-app/cwa-website/pull/2327

**Comment by MikeMcC399** [comment]
- Resolved through PR #2327.
