### ISSUE TITLE
Button "Collapse/Expand all" toggles instead of collapsing/expanding all articles

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#2335]
## Where to find the issue
https://www.coronawarn.app/de/faq/
https://www.coronawarn.app/en/faq/

## Describe the issue
Button "Collapse/Expand all" toggles instead of collapsing/expanding all articles

## Suggested change

- all articles should be collapsed or expanded

**Comment by MikeMcC399** [comment]
@dsarkar 
It works for me, but maybe I don't understand the problem?

My experience is like this:

Open https://www.coronawarn.app/en/faq/
    All articles are collapsed, except the Glossary, which shows "A"
Click on "Expand/Collapse all"
    All articles are expanded
Click on "Expand/Collapse all" (again)
   All articles are collapsed

**Comment by dsarkar** [comment]
@MikeMcC399 If you open some FAQ articles and others are closed then if you push the button, the ones open will close and vice verse.

**Comment by MikeMcC399** [comment]
@dsarkar 

Thank you for explaining. Now I understand!

**Comment by Ein-Tim** [comment]
Fixed by #2346.
