### ISSUE TITLE
`vac_booster_jj` needs to be updated to new J&J situation

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2345]
## Where to find the issue
- https://www.coronawarn.app/de/faq/#vac_booster_jj
- https://www.coronawarn.app/en/faq/#vac_booster_jj

## Describe the issue
The FAQ entry handles a second shot after a J&J vaccination, however, this is actually not the case, see https://www.pei.de/DE/newsroom/dossier/coronavirus/coronavirus-inhalt.html
This was also communicated on Twitter: https://twitter.com/BMG_Bund/status/1482754976921399306?s=20

## Suggested change
Make sure the FAQ entry does not implicates that a second vaccination after J&J is a booster. 

---
Internal Tracking ID: [EXPOSUREAPP-13651](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13651)

**Comment by MikeMcC399** [comment]
The question is now for the app whether it has to apply new special rules for existing J&J vaccination certificates showing 1/1, and whether new certificates for J&J will be issued as 1/2, which would need no special handling.  So probably the issue needs to be raised for the app also in https://github.com/corona-warn-app/cwa-documentation.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I think this is covered in https://github.com/corona-warn-app/cwa-documentation/issues/807.

**Comment by MikeMcC399** [comment]
@Ein-Tim
> I think this is covered in [corona-warn-app/cwa-documentation#807](https://github.com/corona-warn-app/cwa-documentation/issues/807).

You are right, however there is a new issue https://github.com/corona-warn-app/cwa-documentation/issues/812 which specifically describes the J&J change and I think this is good to have as a separate issue to follow.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Do you think that additional changes to the two FAQ articles are still necessary:

- https://www.coronawarn.app/en/faq/#vac_booster_jj "Why does a 14-day wait for full vaccine protection after a booster vaccination appear in the Corona-Warn-App?"
- https://www.coronawarn.app/de/faq/#vac_booster_jj "Warum erscheint in der Corona-Warn-App eine 14-tägige Wartezeit bis zum vollen Impfschutz nach einer Auffrischimpfung?"

The reference https://www.pei.de/DE/newsroom/dossier/coronavirus/coronavirus-inhalt.html that you including in your issue description is no longer the official legal definition. Instead § 22a Impf-, Genesenen- und Testnachweis bei COVID-19; COVID-19-Zertifikate; Verordnungsermächtigung from `Infektionsschutzgesetz - IfSG` has replaced this definition.

The new definitions are quite complicated!

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> The new definitions are quite complicated!

Absolutely! That's why I'm unsure, but I think, a second shot after J&J is still only the end of the basic immunization, isn't it?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> I think, a second shot after J&J is still only the end of the basic immunization, isn't it?

I'm not a lawyer, but I read "Abweichend von Satz 3 liegt in den in Satz 3 Nummer 1 bis 3 genannten Fällen ein vollständiger Impfschutz bis zum 30. September 2022 auch bei einer Einzelimpfung vor; an die Stelle der zweiten Einzelimpfung tritt die erste Einzelimpfung." to mean that if a person got a J&J vaccination at the time when it was labelled 1/1, rather than 1/2 that the 1/1 dose now counts as a full vaccination until Sep 30, 2022.

It would be good to get that confirmed or denied!

**Comment by Ein-Tim** [comment]
🙋🏻‍♂️ Working on this.

**Comment by Ein-Tim** [comment]
I stopped working on this some time ago as this was a bit too complex for me.

**@ Open-Source-Team**, please take a look at it!

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for pinging, we will have a look how to update this article

**Comment by MikeMcC399** [comment]
@dsarkar 

J&J has become quite complicated due to certificate reissue and multiple changes in regulations. Perhaps this article needs to be split up so that it is manageable, readable and understandable? I am not surprised to read that it is too complex for @Ein-Tim . It is also too complex for me.

**Comment by Ein-Tim** [comment]
@dsarkar Could you please investigate whether this issue is still applicable?

**Comment by dsarkar** [comment]
@Ein-Tim Sure, we will have a look at this one.

**Comment by Ein-Tim** [comment]
@dsarkar What was the result of your investigation?

**Comment by MikeMcC399** [comment]
- This issue becomes obsolete after May 1, 2023. See PR https://github.com/corona-warn-app/cwa-website/pull/3474

![image](https://user-images.githubusercontent.com/66998419/235130412-5bb76eee-513c-4052-8948-3c72aa18cace.png)

**Comment by Ein-Tim** [comment]
@MikeMcC399 I plan on going through all the issues which are still open, and I created and close these after May 1.

**Comment by Ein-Tim** [comment]
This issue is obsolete.
