### ISSUE TITLE
Suggestion to change Analysis topic to "Dashboard"

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2352]
## Where to find the issue

- https://www.coronawarn.app/en/analysis/ "Corona-Warn-App (CWA): Key performance indicators"
- https://www.coronawarn.app/de/analysis/ "Corona-Warn-App (CWA): Kennzahlen"

## Describe the issue

The topic text at the top of the pages
- https://www.coronawarn.app/en/analysis/ "Corona-Warn-App (CWA): Key performance indicators"
- https://www.coronawarn.app/de/analysis/ "Corona-Warn-App (CWA): Kennzahlen"

is called:
- Analysis (English)
- Analyse (German)

This does not fit with the text at the bottom of the pages which says:
- Further dashboards (English)
- Weitere Dashboards (German)

![Analyse](https://user-images.githubusercontent.com/66998419/149947071-084dda96-e10c-41d8-9a1f-2ba7645aaee6.jpg)

Furthermore, as brought up in PR https://github.com/corona-warn-app/cwa-website/pull/2331, there is a jarring difference on the German page between the menu text "Analysis" and the topic text "Analyse".

The term "Analysis" could in any case be considered a misnomer, since the data on the page is not analyzed, it consists solely of certain counts displayed in relation to dates.

## Suggested change

Replace the topic text using "Dashboard" in English and in German. This resolves all discrepancies. Dashboard is also a better description of the display type of the data, which is not analyzed, only displayed.

The page is already being referred to elsewhere as a dashboard - see https://www.coronawarn.app/en/faq/#numbers_RKI.

Change these two lines:

https://github.com/corona-warn-app/cwa-website/blob/abe8f761c6a66ab1c757523bb20726d54bd153ef/src/data/analyse_en.json#L4

https://github.com/corona-warn-app/cwa-website/blob/abe8f761c6a66ab1c757523bb20726d54bd153ef/src/data/analyse_de.json#L4

to use the text "Dashboard".

The German page would then look like this:

![Dashboard suggestion](https://user-images.githubusercontent.com/66998419/149947387-f965e288-3ba6-48de-abea-07461788d525.jpg)

**Comment by MikeMcC399** [comment]
@HelTob / @dsarkar 

Would you agree to change the topic label to "Dashboard" at the top of:

- https://www.coronawarn.app/en/analysis/ "Corona-Warn-App (CWA): Key performance indicators" and
- https://www.coronawarn.app/de/analysis/ "Corona-Warn-App (CWA): Kennzahlen"

like this:

![Dashboard suggestion](https://user-images.githubusercontent.com/66998419/149947387-f965e288-3ba6-48de-abea-07461788d525.jpg)

It would be good to get your feedback.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Just a small side-question:
when you write "IHMO" do you mean "In My Humble Opinion", because it that case the abbreviation would be "IMHO" or is there some other meaning for "IHMO"?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The order of the letters I H M O does not spell "In My Honest Opinion" either.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Right, my life is a lie! 😀

I will use IMO ("In my opinion") in the future, thanks for making me aware of this!

**Comment by MikeMcC399** [comment]
@Ein-Tim 
It was an off-topic post in issue 3698 of the Android repo. I don't want to post the full hyperlink here, otherwise GitHub will autolink the issues.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Okay, thank you! No more off-topic comments now! 😉

**Comment by MikeMcC399** [comment]
@browkin 
- Thank you very much for progressing this suggestion with your (draft) PR #2390!

Do we need agreement from anybody else to implement this change? For example from @HelTob?

**Comment by dsarkar** [comment]
@MikeMcC399 We forwarded this suggestion. Thanks!

**Comment by HelTob** [comment]
Hi there,

thank you very much for your suggestions. We are discussing the topic internally and will adjust the title of the page as soon as possible. 

Best regards,
Tobias

**Comment by MikeMcC399** [comment]
- PR #2390 is still a work-in-progress

**Comment by MikeMcC399** [comment]
- PR #2390 is now merged. Thanks for taking on the suggestion and changing the menu label to "Dashboard" as well as the topic label. This makes it all much more consistent.

Closing as this suggestion is now implemented.
