### ISSUE TITLE
Adapt FAQ to the changes to come regarding free PCR-tests

### ISSUE THREAD

**Issue by achisto** [corona-warn-app/cwa-website#2371]
As you may have heard in the media ([tagesschau](https://www.tagesschau.de/inland/innenpolitik/ueberblick-bund-laender-101.html), [tagesspiegel](https://www.tagesspiegel.de/politik/keine-lockerungen-aber-oeffnungsperspektive-das-plant-kanzler-scholz-beim-corona-gipfel/28000394.html), [Zeit](https://www.zeit.de/politik/deutschland/2022-01/bund-laender-treffen-pcr-tests-beschraenkung-antigen-schnelltests)) it is almost certain that restrictions for free PCR-tests are coming soon. As tagesspiegel writes:

> Wenn bei allen anderen Personengruppen [als Personal insbesondere in Krankenhäusern, in Praxen, in der Pflege, Einrichtungen der Eingliederungshilfe und für Personen mit dem Risiko schwerer Krankheitsverläufe] ein Antigen-Schnelltest positiv ausfällt, soll dagegen auf eine bisher erfolgte Bestätigung durch einen PCR-Test verzichtet werden.

Currently the [FAQ-entry](https://www.coronawarn.app/de/faq/#rat_what_if_positive_result
) "Wie handele ich, wenn mein Schnelltest-Ergebnis positiv ist?" partly reads:

> In Fall eines positiven Testergebnisses sollten Sie Ihr Testergebnis teilen und umgehend einen PCR-Test machen, um das Ergebnis zu bestätigen oder zu widerlegen.

With a new TestV around the corner this may not be longer possible without paying for the test out of your own pocket. The FAQ.-entry should be adapted quickly, so that people not reading the news and TestV know what they can and need to do.

Same goes for [another FAQ-entry](https://www.coronawarn.app/de/faq/#rat_red_card_which_test) "Wenn ich eine hohe Risikobegegnung in der App angezeigt bekomme, d. h. eine rote Karte/Kachel, sollte ich dann einen Schnelltest oder PCR-Test machen?"

> Wenn die Corona-Warn-App Ihnen eine Begegnung mit erhöhtem Risiko (rote Kachel) anzeigt, sollten Sie einen PCR-Test machen und sich in Quarantäne begeben.

Currently some federal states offer free PCR tests with a red warning, others don't and some of the ones that used to offer free PCR tests are already restricting access.

Technically both entries are not wrong in itself or contain false information because out of a medical perspective it certainly would be best to get a PCR test. However the situation doesn't allow for free PCR-tests and paying for one is not feasibly for everyone, both should be taken into account in the FAQs' information.

---
Internal Tracking ID: [EXPOSUREAPP-11553](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11553)

**Comment by Ein-Tim** [comment]
@achisto 

The iOS app also suggest to get a PCR test at the moment. The text change was not yet done under Android (see https://github.com/corona-warn-app/cwa-documentation/issues/813). 
Would you like to open a new issue in the iOS repo for this?

**Comment by achisto** [comment]
@Ein-Tim that's a good idea. Will try to find time for it this evening!

**Comment by dsarkar** [comment]
@achisto FAQ articles have been updated some time ago. I suggest closing this issue.
