### ISSUE TITLE
Links to cwa-documentation/master

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2384]
## Where to find the issue

https://www.coronawarn.app

## Describe the issue

The default branch of https://github.com/corona-warn-app/cwa-documentation was renamed from `master` to `main` on Jan 27, 2022 (see https://github.com/corona-warn-app/cwa-documentation/issues/826#issuecomment-1023016964).

Links in https://www.coronawarn.app which explicitly reference the `master `branch https://github.com/corona-warn-app/cwa-documentation/tree/master are covered by GitHub's "Moved Permanently" function (see https://github.com/github/renaming). The Cypress testsuite
`npm test`
continues to run successfully despite this change.

A cleaner solution, which does not rely on redirects, would be to update the links.

## Suggested change

Change hyperlinks in https://www.coronawarn.app like:

- https://github.com/corona-warn-app/cwa-documentation/blob/master or
- https://github.com/corona-warn-app/cwa-documentation/tree/master

to refer to the `main` branch instead of the `master` branch.

**Comment by MikeMcC399** [comment]
Please let me know if you want a PR to implement the link updates.

**Comment by MikeMcC399** [comment]
@dsarkar 

I have a PR prepared and I will hold back until there is a quieter period with no releases before submitting.

**Comment by MikeMcC399** [comment]
PR #2416 now submitted to update the links from this repository to the [cwa-documentation](https://github.com/corona-warn-app/cwa-documentation) repository, so that the links use the new name of the default branch `main` instead of `master`, which no longer exists.

**Comment by MikeMcC399** [comment]
- PR #2416 is now merged and the issue is resolved.

**Comment by dsarkar** [comment]
@MikeMcC399 Morning! Thanks for the PR again!

**Comment by MikeMcC399** [comment]
@dsarkar Good morning to you too!

**Comment by MikeMcC399** [comment]
- One of the links from PR https://github.com/corona-warn-app/cwa-website/pull/2416 seems to have been accidentally reverted by PR https://github.com/corona-warn-app/cwa-website/pull/2434.

In https://www.coronawarn.app/en/faq/results/#client_server "How do the server and device communicate with each other?" the article links to https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md whereas it should link to https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md.

I will submit a new PR to reapply this fix.

**Comment by MikeMcC399** [comment]
- PR #2663 was submitted and merged.

There are no more references to `/cwa-documentation/blob/master` remaining in the web sources.

Closing as re-resolved.
