### ISSUE TITLE
Minimum operating system requirements FAQ does not cover storage & memory

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2385]
## Where to find the issue

FAQ:

- https://www.coronawarn.app/en/faq/#minimum_requirements "What are the minimum operating system requirements for my phone?"
- https://www.coronawarn.app/de/faq/#minimum_requirements "Welche Systemvoraussetzungen muss mein Smartphone erfüllen?"

## Describe the issue

The storage and memory requirements for the Corona-Warn-App for the iOS Exposure Notification Framework and the Google Exposure Notification System are not listed in the FAQ article covering minimum operating system requirements.

On Android I have seen more than 2GB of data stored by the Google Play services app which hosts the ENS. Especially on older devices with less storage capacity, this may cause an issue.

Referring to https://www.coronawarn.app/en/analysis/ the 7-day moving average sharing behaviour shows a peak of 48,452 on Jan 25, 2022. This is more than 3 times higher than the previous peak of 15,319 on Nov 29, 2021. More shared data means more downloaded data onto devices.

## Suggested change

Research the amount of storage and memory required for iOS and Android devices. Add this information to the FAQ article.

## Reference

- Issue https://github.com/corona-warn-app/cwa-app-android/issues/4732

---
Internal Tracking ID: [EXPOSUREAPP-11626](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11626)

**Comment by Ein-Tim** [comment]
Under iOS the space consumed by the ENF can't be find out easily, as the framework is part of the system and the storage diagram does not split the point "Systemdaten" into any other points.

I could do the test and delete the CWA as well as delete all data of the ENF and monitor whether the shown size of "Systemdaten" changes but I think it would be better if this is done by the project team in a controlled environment.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I think this is a task for developers who are deeply into the structures. They may also have contacts to Apple and Google who they could refer to.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I also think so (: Enjoy your evening!

**Comment by MikeMcC399** [comment]
@Ein-Tim Thanks and likewise to you!

**Comment by MikeMcC399** [comment]
- This issue is also related to https://github.com/corona-warn-app/cwa-app-android/issues/4753, since according to research by @vaubaehn, low free disk space can result in extremely high mobile data usage (> 2GB / month) , with unexpected financial impact for users assuming zero cost for CWA data usage.

**Comment by vaubaehn** [comment]
Hi @MikeMcC399 
Thanks for taking care about that subject in this place!

**Comment by MikeMcC399** [comment]
@vaubaehn 
> Thanks for taking care about that subject in this place!

- On the subject of FAQ documentation of CWA memory requirements, the response has been limited to the allocation of an Internal Tracking ID: [EXPOSUREAPP-11626](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11626).

- I see that you have the active technical participation of @thomasaugsten and administrative support from @dsarkar in the issue https://github.com/corona-warn-app/cwa-app-android/issues/4753 from @dadosch.

Hopefully we will see some effective action soon.

**Comment by MikeMcC399** [comment]
- For Android, CWA version [2.19.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.19.1), released today, March 22, 2022, includes PR https://github.com/corona-warn-app/cwa-app-android/pull/4929 to reduce memory usage. This is in response to issue https://github.com/corona-warn-app/cwa-app-android/issues/4732.
- Would it now be possible to get some developer feedback to post into the FAQ article "[What are the minimum operating system requirements for my phone?](https://www.coronawarn.app/en/faq/#minimum_requirements)", or into a new FAQ article, so that storage requirements of the app are described?

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> according to *** we cannot give estimates currently.
