### ISSUE TITLE
Search function for the blog

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2387]
## Feature description
The blog should have a search function, similar to the FAQ.

## Problem and motivation
During the last 1 1/2 years, there were more than 65 blog posts published. A search function would really help to find information which is there, but "still far away" (-;

## Is this something you're interested in working on
I can definitely review PRs, etc., but I can't implement this on my own.

**Comment by MikeMcC399** [comment]
It would make sense to have an blog search integrated into the website.

A browser search of https://www.coronawarn.app/en/blog/ can only search in the headline text of the blogs, not in the body. There is no function to expand all blogs to display all text to search in.

**Comment by Ein-Tim** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/2531 is offering an implementation for this.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Will you check? It looks good to me.

- PR #2531 has been merged and the deploy issues have been solved

- Credit on Twitter https://twitter.com/coronawarnapp/status/1524283790230794242?s=20&t=--WOErLs9l2tvgTO6K_gAw for the enhancement has gone to the "Entwickler-Team". Kudos should be going to @Crystalskulls! Well done!

**Comment by Crystalskulls** [comment]
@MikeMcC399 

Thank you for the kudos. I am happy to be a contributor of the website. The development team always thanks me in my PR's, so everything is fine :)

**Comment by Ein-Tim** [comment]
The search works flawlessly. Thanks to @Crystalskulls for implementing!
