### ISSUE TITLE
Inconsistent use of "Risikobegegnung(en)" and "Risiko-Begegnung(en)" in the German FAQ

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2392]
## Where to find the issue
In the German FAQ: https://www.coronawarn.app/de/faq/

## Describe the issue
The FAQ uses both spellings, "Risikobegegnung(en)" and "Risiko-Begegnung(en)".

## Suggested change
The app itself uses "Risiko-Begegnung(en)". The website should be aligned to the app.

## Additional information
I will provide a PR for this change.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The term "Risikobegegnung" is also used in the Blog. It should be decided if this should also be changed to "Risiko-Begegnung".

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, certainly. In the next days, I will address this issue and #2393 in separate PRs. These PRs only change the FAQ, but if decided, the blogs can also be changed.
