### ISSUE TITLE
Inconsistent use of "Diagnostic key(s)" and "Diagnosis key(s)" in the English FAQ

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2393]
## Where to find the issue
In the English FAQ: https://www.coronawarn.app/en/faq/

## Describe the issue
The FAQ uses both, "diagnostic key(s)" and "diagnosis key(s)". Only one term should be used. 

## Suggested change
In the [Solution Architecture Document](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md) only the term "Diagnosis key(s)" is used. The website should be aligned to the documentation. 

## Additional information
I will provide a PR for this change.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

According to the [Google documentation](https://developers.google.com/android/exposure-notifications/exposure-notifications-api) `diagnosis key` is the term used, which also agrees with the [Solution Architecture document](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md).

For example: "The ExposureWindow class stores a duration of up to 30 minutes, during which beacons from a diagnosis key were observed."

As you say, `diagnostic key` is inconsistent and should be changed.

**Comment by dsarkar** [comment]
Good morning! 
@Ein-Tim @MikeMcC399 Thanks....
