### ISSUE TITLE
Deprecation of node-sass

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2412]
## Where to find the issue

https://github.com/corona-warn-app/cwa-website/blob/master/package.json
https://github.com/corona-warn-app/cwa-website/blob/master/gulpfile.js 

## Describe the issue

According to https://www.npmjs.com/package/node-sass "Node Sass" used by cwa-website is deprecated:

"Warning: LibSass and Node Sass are deprecated. While they will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto [Dart Sass](https://sass-lang.com/dart-sass)."

## Suggested change

Migrate from [node sass](https://www.npmjs.com/package/node-sass) to [Dart Sass](https://sass-lang.com/dart-sass) see https://sass-lang.com/blog/libsass-is-deprecated which says:

"If you’re a user of Node Sass, migrating to Dart Sass is straightforward: just replace node-sass in your package.json file with sass."

however the change is not quite so simple. To remediate 
`Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.`
`More info and automated migrator: https://sass-lang.com/d/slash-div`
it is necessary to run the migrator.

1. `npm uninstall node-sass`
2. `npm install sass@latest`
3. Replace `node-sass` by `sass` in `gulpfile.js`
4. `npm install -g sass-migrator`
5. `sass-migrator division **/*.scss`

---
Internal Tracking ID: [EXPOSUREAPP-14243](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14243)

**Comment by MikeMcC399** [comment]
@svengabr 

I suggest to monitor the need for migrating to node-sass. If everything is working at the moment, then there is no need to migrate. This post was triggered by the error message from @Ein-Tim in https://github.com/corona-warn-app/cwa-website/pull/2282#pullrequestreview-872434206:

`Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Node.js 16.x`

In the meantime @Ein-Tim says that node 16 is working in his environment.

**Comment by svengabr** [comment]
According to @Ein-Tim, the error does no longer happen and was a temporal issue. See here: https://github.com/corona-warn-app/cwa-website/issues/2411#issuecomment-1030032102

> I can confirm what @svengabr stated in [#2282 (comment)](https://github.com/corona-warn-app/cwa-website/pull/2282#issuecomment-1029792377), I did not encounter any errors during the build process. I don't know why I encountered the error `Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Node.js 16.x` yesterday evening. My apologies to @MikeMcC399 & @svengabr for any extra work caused!

**Comment by MikeMcC399** [comment]
@svengabr 
I agree that @Ein-Tim said it was only a temporary testing issue which he has now resolved. As far as I can see everything is working and there is no urgent need to make any changes in this respect.

If you think that addressing the deprecation of `node-sass` by migrating to `sass `is something which might soon be done, then I suggest to leave this issue open as a reminder.

If there are no near-term plans to do this, then I suggest closing the issue.

**Comment by svengabr** [comment]
Not having any intentions of migrating for the moment so this issue will be closed.

**Comment by MikeMcC399** [comment]
- I suggest to re-open this issue if PR #3180 is attempting to resolve it. (I can't do this myself since it was closed by @svengabr.)
