### ISSUE TITLE
FAQ says booster rules will be updated

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2417]
## Where to find the issue

- https://www.coronawarn.app/en/faq/#vac_cert_booster_info "How do I become aware of booster vaccinations in the context of Corona?"
- https://www.coronawarn.app/de/faq/#vac_cert_booster_info "Wie erfahre ich von Auffrischimpfungen im Kontext von Corona?"

## Describe the issue

The [FAQ article](https://www.coronawarn.app/en/faq/#vac_cert_booster_info ) says: 

"How long someone is effectively protected by a COVID-19 vaccination (basic immunization) depends on several factors and can therefore not be answered in general terms according to current knowledge. For this reason, the corresponding CWA rules for vaccination schedules and booster vaccinations are continually reviewed and adapted in coordination with the RKI according to developments and new findings."

The commitment to "continually review and adapt" is not being kept. RKI publishes updated written recommendations, however these have not been translated into CWA rules. 

- See for instance https://github.com/corona-warn-app/cwa-documentation/issues/814.

## Suggested change

If the rules are no longer being updated then the description in the FAQ needs to be changed to say that.

---
Internal Tracking ID: EXPOSUREAPP-11721

**Comment by svengabr** [comment]
Internal Tracking ID: EXPOSUREAPP-11721

**Comment by svengabr** [comment]
Thanks, @MikeMcC399, we will discuss this topic internally. I created a Jira issue to keep track of it.
