### ISSUE TITLE
Plain (S)CSS/HTML/JS or Framework?

### ISSUE THREAD

**Issue by ArnoMatzpohl** [corona-warn-app/cwa-website#2423]
Hi,
I'm interested to contribute on this project, but it's really hard to read this code to be honest.
It seems like you are using no Framework, is that right?
Please correct me if I'm wrong and tell me which framework is used in this project! 😅

Thanks in advance :)

**Comment by MikeMcC399** [comment]
@ArnoMatzpohl 

I don't think the tools used to build this website qualify to be called a Framework.

If you want to contribute, then you should read the [README](https://github.com/corona-warn-app/cwa-website/blob/master/README.md) which tells you how to build and run the website. It also includes a link to the [docs folder](https://github.com/corona-warn-app/cwa-website/tree/master/docs) which contains some more information. [CHANGE_WEBSITE_CONTENT](https://github.com/corona-warn-app/cwa-website/blob/master/docs/CHANGE_WEBSITE_CONTENT.md) for instance says: "The Website is created from a set of pages, templates, and json data using [panini](https://github.com/foundation/panini)."

The `npm `modules, including from the [gulp](https://www.npmjs.com/package/gulp) suite which are used are all listed in [package.json](https://github.com/corona-warn-app/cwa-website/blob/master/package.json).

**Comment by MikeMcC399** [comment]
@dsarkar 
I suggest to close, since the question is answered and no further feedback has been given by the question's author.
