### ISSUE TITLE
R 2.18 update FAQ #admission_policy 

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#2429]
## Where to find the issue

**DE** https://www.coronawarn.app/de/faq/#admission_policy 
**EN** https://www.coronawarn.app/en/faq/#admission_policy 

## Suggested change

- Add more info regarding 2G+ to FAQ article
- Split large article into:
  - Grundlegendes zur Anzeige des Status-Nachweises. 
https://www.coronawarn.app/de/faq/#admission_policy 
  - Was bedeutet konkret der 2G+-Status-Nachweis? 
https://www.coronawarn.app/de/faq/#admission_policy_2gplus 
  - Wird meine Auffrischimpfung berücksichtigt? 
https://www.coronawarn.app/de/faq/#admission_policy_2gplus_booster 
  - Wie verwende ich die kombinierte 2G+-Anzeige? 
https://www.coronawarn.app/de/faq/#admission_policy_2gplus_howto 
  - Warum wird der 2G+Status-Nachweis nicht angezeigt, obwohl ich ein Impf oder Genesenenzertifikat und einen negativen Test habe? 
https://www.coronawarn.app/de/faq/#admission_policy_2gplus_not_shown 

---
Internal Tracking ID: [EXPOSUREAPP-11773](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11773)
related issues: https://github.com/corona-warn-app/cwa-documentation/issues/851

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/2461 seems to be addressing this issue.
