### ISSUE TITLE
English app download buttons on German page

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2431]
## Where to find the issue

https://www.coronawarn.app/de/

## Describe the issue

The section on the German-language page https://www.coronawarn.app/de/ displays download buttons for Apple and Google labelled in English instead of in German:

- https://www.coronawarn.app/assets/img/App_Store_Badge_US-UK.svg "Download on the App Store"
- https://www.coronawarn.app/assets/img/google-play-badge.svg "GET IT ON Google Play"

![CWA_download](https://user-images.githubusercontent.com/66998419/153818716-1c90bc13-6718-4e21-aee5-f586f30e7170.jpg)

These are the same images as are used on the English language page https://www.coronawarn.app/en/.

## Suggested change

https://www.coronawarn.app/de/ should use German-language buttons on the German-language page https://www.coronawarn.app/de/. See https://www.bundesregierung.de/breg-de/themen/corona-warn-app for examples of the buttons with German text:

- "Laden im App Store"
- "JETZT BEI Google Play"

![Breg_download](https://user-images.githubusercontent.com/66998419/153818763-ca13056e-6959-44e9-acf0-70215b1d5d63.jpg)

The equivalent buttons on the English-language page https://www.coronawarn.app/en/ should stay labelled in English. This means that additional German Apple/Google Store images need to be imported into the web and linked to the pages using language-dependent images for the download buttons.

---
Internal Tracking ID: [EXPOSUREAPP-11892](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11892)

**Comment by Ein-Tim** [comment]
PR #2488 was merged. Can this issue be closed?

**Comment by MikeMcC399** [comment]
@Crystalskulls 
- Thank you for contributing PR #2488 to fix this issue! It has gone into production and looks good.
