### ISSUE TITLE
Wrong sentence in PDF document linked to from `rat_what_if_positive_result`

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2432]
## Where to find the issue
German FAQ entry: https://www.coronawarn.app/de/faq/#rat_what_if_positive_result -> PDF linked

## Describe the issue
The PDF includes the sentence:
![Bildschirmfoto 2022-02-15 um 20 23 11](https://user-images.githubusercontent.com/67682506/154133870-36776896-e3b3-4c89-9c07-3ac9ee02abaf.png)

The sentence "Nutzen Sie über die Corona-Warn-App weiter und beachten Sie bitte auch die AHA+L-Regeln!" makes no sense. 

## Suggested change
The sentence should be: "Nutzen Sie die Corona-Warn-App weiter und beachten Sie bitte auch die AHA+L-Regeln!"

---
Internal Tracking ID: [EXPOSUREAPP-11874](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11874)

**Comment by MikeMcC399** [comment]
The PDF which needs correcting is https://www.coronawarn.app/assets/documents/DE_CWA_RKI-Plakat_Schnelltests_v2-kl.pdf and was provided by RKI.

The source on GitHub is https://github.com/corona-warn-app/cwa-website/blob/master/src/assets/documents/DE_CWA_RKI-Plakat_Schnelltests_v2-kl.pdf
