### ISSUE TITLE
FAQ search doesn't search in Glossary

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2433]
## Where to find the issue

https://www.coronawarn.app/en/faq/?search=

## Describe the issue

The FAQ search does not find terms in the Glossary.

## Steps to reproduce

1. In search field of https://www.coronawarn.app/en/faq/ enter "OHA".
2. Note the message "We searched all questions, but didn't find anything with this search term. Please try it again with another term."
3. Look further down the page and confirm that the term "OHA" is shown in https://www.coronawarn.app/en/faq/#glossary_android.

## Suggested change

Extend the search to cover the contents of the Glossary.

---
Internal Tracking ID: [EXPOSUREAPP-11760](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11760)

**Comment by dsarkar** [comment]
@MikeMcC399 will be fixed. We are redesigning the whole FAQ part.

**Comment by dsarkar** [comment]
I think, you will see and be able to test the PR soon.

**Comment by brifemu** [comment]
FYI: https://github.com/corona-warn-app/cwa-website/pull/2434

**Comment by MikeMcC399** [comment]
@brifemu 
- Thanks for the cross-link to the new PR #2434.

I tried searching for the term OHA, as described here in the steps to reproduce, using the fork from the PR and it did not find the term in the Glossary.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for testing. I confirm, there seems to be a bug still.

**Comment by dsarkar** [comment]
@MikeMcC399 in glossary search is only in titles implemented.

**Comment by MikeMcC399** [comment]
@dsarkar 
I see that PR #2434 has now been improved to search in the Glossary text. Searching for "OHA" now finds the right entry.

**Comment by MikeMcC399** [comment]
- This issue is resolved by https://github.com/corona-warn-app/cwa-website/pull/2434 (FAQ re-design).
