### ISSUE TITLE
German FAQ entry "[Apple/iOS]: ENErrorDomain-Fehler 11" asking people to create duplicates

### ISSUE THREAD

**Issue by daimpi** [corona-warn-app/cwa-website#244]
## Where to find the issue
The German ENError 11 FAQ entry: https://www.coronawarn.app/de/faq/#ENError11

## Describe the issue
The German entry (in contrast to the [English one](https://www.coronawarn.app/en/faq/#ENError11)) asks users under iOS 13.6 which still experience this error, to open a new issue in the iOS repository. This leads to the creation of many duplicates of https://github.com/corona-warn-app/cwa-app-ios/issues/972.

## Suggested change
Align the German entry with the English one, by asking users to comment in https://github.com/corona-warn-app/cwa-app-ios/issues/972 if they still experience the problem under iOS 13.6.

**Comment by tkowark** [comment]
Thanks for spotting that. I was already wondering where these still come from. I guess a test might be helpful here
