### ISSUE TITLE
Cypress fails testing link to Wiley Online Library

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2490]
## Where to find the issue

- https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/ "Explanation of the statistic tiles in the Corona-Warn-App"
- https://www.coronawarn.app/de/blog/2021-08-05-statistictiles/ "Erläuterung der Statistikkacheln in der Corona-Warn-App"

## Describe the issue

The Cypress test `check_links.js` fails with an HTTP 503 error (Service Unavailable) when testing the link to https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1.

```
[RESPONSE 503] https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1 on 'http://localhost:8000/de/blog/2021-08-05-statistictiles' 
[RESPONSE 503] https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1 on 'http://localhost:8000/en/blog/2021-08-05-statistictiles'
````

The site https://onlinelibrary.wiley.com appears to be now using DDoS protection by [Cloudflare](https://www.cloudflare.com/5xx-error-landing/). This is a new situation. Previously checks to this website were not causing an error response.

## Steps to reproduce

Open a web browser and check that the link https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1 is available when accessed manually.

Execute
`npm run test:open`
In Cypress console select `check_links.js` to execute this test.

Note 2 failed tests and examine contents of log file
`cwa-website/cypress/logs/broken_links_result.txt`

## Suggested change

Options:

1. Ignore HTTP 503 (Service Unavailable) as a hard error. Instead, treat HTTP 503 as a temporary error and show success, or
2. Do not test https://onlinelibrary.wiley.com

---
Internal Tracking ID: [EXPOSUREAPP-12411](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12411)

**Comment by MikeMcC399** [comment]
Perhaps @brifemu could look at the best way to resolve this issue?

**Comment by brifemu** [comment]
Hi @MikeMcC399  it is a pleasure to be able to communicate with you again after such a long time. I have created a PR for this problem, it is a temporary PR. I have left a small comment in the PR about how to fix this error in the future. Right now I am quite busy with several projects, so I will personally take care of this in depth in a few weeks.

#2554

**Comment by MikeMcC399** [comment]
@brifemu 

Thank you for giving your attention to this issue!

- PR #2554 needs a tweak to work. I will comment in the PR.

**Comment by MikeMcC399** [comment]
- This issue is now resolved through PR #2554.

The output from the Cypress test suite (`npm test`) is
`  √  All specs passed!  `

**Comment by MikeMcC399** [comment]
@brifemu 

- PR https://github.com/corona-warn-app/cwa-website/pull/2434 has caused PR #2554 to be reverted.

https://github.com/corona-warn-app/cwa-website/blob/eae3ba81c1f28a0564467e543b6cbe868e0ef1f1/cypress/integration/check_links.js

is missing the entry

'https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1'

I will submit a new PR to put this back again.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/2574 is submitted to fix this issue again.

**Comment by MikeMcC399** [comment]
Resolved once again.
