### ISSUE TITLE
Add more helpful information to `recovered` FAQ entry

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2492]
## Where to find the issue
DE: https://www.coronawarn.app/de/faq/#recovered
EN: https://www.coronawarn.app/en/faq/#recovered

## Describe the issue
The FAQ entry is not really helpful, it states that it is possible to continue using the app after registering a positive test in it without resetting it, but it does not give any details or informs the user that the positive test has to be deleted. 

## Suggested change
Add a step by step guide on what to do if the user wants to continue to use the app as before, after registering a positive test in the app.

## Additional information
I will provide a PR for this change. 

---
Internal Tracking ID: [EXPOSUREAPP-5975](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5975)

**Comment by Ein-Tim** [comment]
PR #2493 opened addressing this issue.

**Comment by Ein-Tim** [comment]
@dsarkar 

Could you let us know what the content of the JIRA ticket 5975 is? It's quite an old ticket, isn't it?

**Comment by dsarkar** [comment]
@Ein-Tim it is a ticket I created some time ago for exactly the same reason, i.e. to extend this FAQ article.
