### ISSUE TITLE
[svengbr ?] Is text compression enable?

### ISSUE THREAD

**Issue by Julian-B90** [corona-warn-app/cwa-website#25]
## Is text compression enable?

* Website URL Path: https://www.coronawarn.app/
* Description: 
Maybe the website can you gzip, Brotli or deflat

https://web.dev/uses-text-compression

**Comment by SebastianWolf-SAP** [comment]
Thanks for the report. We will follow-up with the colleague who are responsible for the hosting!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by ingomc** [comment]
Text Compression is also mentioned in #60

**Comment by corneliusroemer** [comment]
Dear maintainers, any update since this was raised two weeks ago? @SebastianWolf-SAP @tkowark @jakobmoellersap

**Comment by Ein-Tim** [comment]
@svengabr Are you able to answer this question?

**Comment by Ein-Tim** [comment]
@corneliusroemer Asked for an update because 2 weeks passed and this issue was not answered, now nearly 2 years passed and it still remains unanswered.

This seems like an easy to answer question, I wonder if there is no one available to answer it?

**Comment by MikeMcC399** [comment]
- https://github.com/corona-warn-app/cwa-website/issues/60 already answered the question in June 2020 that text compression is not enabled.

https://developers.google.com/web/tools/lighthouse documents how to use Lighthouse.

**Comment by MikeMcC399** [comment]
@Julian-B90 

- If your question is answered, can this issue be closed?

- #60 would remain open with the suggestion to enable text compression

**Comment by svengabr** [comment]
I once again asked the server administrators for an update in EXPOSUREAPP-8525

**Comment by larswmh** [comment]
We got feedback and received the information that compressing will not be implemented. 

Due to this feedback, we're closing this issue now.

**Comment by MikeMcC399** [comment]
@larswmh 

Did you receive any explanation why text compression will not be enabled?
