### ISSUE TITLE
FAQ entry on iOS 14 beta update

### ISSUE THREAD

**Issue by daimpi** [corona-warn-app/cwa-website#250]
## Where to find the issue

This issue concerns the FAQ entry on iOS 14 beta: https://www.coronawarn.app/en/faq/#ios_14_beta

## Describe the issue

The FAQ entry states that the iOS 14 beta doesn't support ENF, but the latest iOS beta (beta 4) [added support for ENF](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes/):

![grafik](https://user-images.githubusercontent.com/22129968/89328323-86e35680-d68d-11ea-8f3b-4c099fd26d6d.png)

## Suggested change

Update the FAQ entry to state that when using the iOS 14 beta, beta 4 or higher is required to run CWA.

**Edit**: relevant caveats: https://github.com/corona-warn-app/cwa-app-ios/issues/749#issuecomment-668723159

**Comment by GPclips** [comment]
Hello @daimpi,

thanks for your investigation and helping us to keep the FAQ up to date. 
This has been corrected today and therefore I will go on and close the bug.

Best Regards,
LMM

Corona-Warn-App Open Source Team
