### ISSUE TITLE
Merge FAQ entries `risk_encounter_different_devices` & `dissimilar_indication_of_risk_status`

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2536]
## Where to find the issue
- https://www.coronawarn.app/de/faq/#risk_encounter_different_devices
- https://www.coronawarn.app/en/faq/#risk_encounter_different_devices
- https://www.coronawarn.app/de/faq/#dissimilar_indication_of_risk_status
- https://www.coronawarn.app/en/faq/#dissimilar_indication_of_risk_status

## Describe the issue
The FAQ entries mentioned above cover exactly the same & answer the same question. They should be merged.

## Suggested change
Remove `dissimilar_indication_of_risk_status`, as it does not give any information which `risk_encounter_different_devices` does not give. 
Add a FAQ redirect from `dissimilar_indication_of_risk_status` to `risk_encounter_different_devices`.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
- Thank you for writing about this issue. I noticed it too and I was going to suggest combining the two articles through PR https://github.com/corona-warn-app/cwa-website/pull/2529 however the PR was merged too fast for me to complete my comments.
- I wonder how far away the new FAQ layout is? Perhaps in the new FAQ scheme the older article https://www.coronawarn.app/en/faq/#dissimilar_indication_of_risk_status could be marked as obsolete without deleting it? Maybe @dsarkar / @svengabr could share the plans for the new FAQ if they are ready to be shared?

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 I think we talk about a week or so...

**Comment by Ein-Tim** [comment]
@MikeMcC399 I think a redirect makes most sense, I also shared this entry multiple times on Twitter.

@dsarkar Please let me know what you want.

**Comment by Ein-Tim** [comment]
I would like to start working on a PR for this on the weekend. Please @dsarkar, let me know what you prefer? Adding a redirect or deleting the entry?
Also, should I branch on the FAQ rework branch so that my PR can be merged into this branch or should I branch on `master`?

**Comment by Ein-Tim** [comment]
🙋🏻‍♂️ FYI: I will start working on this today.

@svengabr Could you let me know if my Suggested Change in the OP would be approved if provided via PR? Then I know I'm not doing unnecessary work :D

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Did you notice that the two articles are now in two different sections?

- https://www.coronawarn.app/en/faq/#dissimilar_indication_of_risk_status is in https://www.coronawarn.app/en/faq/results/#risk_assessment

- https://www.coronawarn.app/en/faq/results/#risk_encounter_different_devices is in https://www.coronawarn.app/en/faq/results/#app_features_risk_assessment

I still think that your suggestion to redirect `#dissimilar_indication_of_risk_status` to `#risk_encounter_different_devices` and to then remove the first article makes sense.

**Comment by Ein-Tim** [comment]
PR #2673 provided, addressing this issue.
