### ISSUE TITLE
2.19 blog post neither mentions DCC reissuance feature nor the ability to register rt-PCR tests

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2541]
## Where to find the issue
DE: https://www.coronawarn.app/de/blog/2022-03-16-cwa-2-19
EN: https://www.coronawarn.app/de/blog/2022-03-16-cwa-2-19/

## Describe the issue
The blog post neither mentions the DCC reissuance feature nor the ability to register rt-PCR tests.

## Suggested change
Add some information about DCC reissuance feature & the ability to register rt-PCR tests.

**Comment by dsarkar** [comment]
@Ein-Tim 

Version 2.19 has been technically prepared to exchange certificates or register PCR rapid tests and transmit test results. Once the certificate exchange rules are implemented and PCR quick test QR codes are issued, these two features will be available to CWA users. We will provide timely information on these features in the form of a blog and/or FAQ.

**Comment by Ein-Tim** [comment]
@dsarkar 

Okay thanks. I wanted to make this sure because the New Features screen in the app mentions these features.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- PR #2544 you mentioned was subsequently reverted by PR https://github.com/corona-warn-app/cwa-website/pull/2545 both from @HannaHei

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> the New Features screen in the app mentions these features.

I checked for the Android 2.19.x releases and the information about "Registration of Rapid PCR Tests" was removed in the 2.19.2 release.

Is that the same for the latest iOS 2.19.x version as well?

**Table for CWA Android New Features**
Feature | 2.19.0 | 2.19.1 | 2.19.2
--- | --- | --- | ---
Registration of Rapid PCR Tests | yes | yes | -
Certificate Assignment | yes | yes | yes
Certificate Update | yes | yes | yes
