### ISSUE TITLE
Google Play Store needed?

### ISSUE THREAD

**Issue by okievv** [corona-warn-app/cwa-website#255]
I tried installing the CWA on my Android smartphone. It did not work properly - it was claiming that I would need to update Play Store services. For sure, I had disabled this service because I have never used Play Store and also don't intend to do so.

For testing purposes (in order to narrow down the issue) I had enabled Play Store services today. The first thing that I was requested to is to log in with my Google account - that I don't have.

Do I really need a Google account, and what good is it?
This raises a serious concern. CWA was developed to keep data protection policies. On the other hand, am I requested to open a Google account and provide my private personal data there?! This would lead any data protection compliance ad absurdum.

Or, did I miss anything?

**Comment by GPclips** [comment]
Hello @okievv,

thanks for reaching out and asking that question. To implement the Exposure Notification API, Google is using the Google Play Services application. Therefore you have to have the Google Play Services in place to be able to use the API in combination with the Corona-Warn app. We do have a FAQ article which summarizes this: https://www.coronawarn.app/de/faq/#googleplay
https://www.coronawarn.app/en/faq/#googleplay

Regarding your question, if you need to have a Google account to use the Google Play Services. This really is a question for Google. You will find a quick description about the Google Play Services in the PlayStore, you can access via your desktop computer: https://play.google.com/store/apps/details?id=com.google.android.gms&hl=de

You can reach out to Google using the speech bubble in the top right corner of the link I shared with you. 

Thank you,
LMM

Corona-Warn-App Open Source Team

**Comment by stevie21** [comment]
Hi okievv,
do you still have the problem? Did you read my comment under above link from daimpi?

**Comment by okievv** [comment]
let me try, I was hiking in the mountains today to escape the weather conditions...

**Comment by okievv** [comment]
Hi @stevie21 ,
as a desperate action, I had re-enabled to Play Store services on my mobile. First smoke tests did not show any change.
In the meantime, after a couple of days, I have tried to re-install CWA. There was an Android update in the meantime, too, but I don't have any clue whether this was supporting my issue.
When I just tried - I could successfully install CWA without the app complaining about missing Playstore access, and now it seems up and running to me. 
Thank you, and all other ones who cared about this.

**Comment by stevie21** [comment]
Hi @okievv,
this sounds good. When i read your first entry, then i can say to you, that we are on a simliar wave.
I also do not want to have a google account, so that my handy is probably a open book for google.
My handy is my private, and should not be open for google or whatsapp etc.
But this must everybody decide for himself. I hope that your CWA will run well now. 
kind regards:
stevie21

**Comment by stevie21** [comment]
Hi @okievv,
now i have got the following link from vaubaehn,

[https://www.apkmirror.com/apk/robert-koch-institut/]

who is somehow the supervisor of error: 
"Fehler bei Kommunikation mit Google API (39508) #774"
I am involved in this error #774.
This seems to me that we can download next version 1.2.0 cwa apk from there on a supported way of Robert Koch Institut.

**Comment by tkowark** [comment]
Thanks all for your proposals. As mentioned in the [FAQ](https://www.coronawarn.app/de/faq/#apk), there is currently no APK delivery planned and you can track wishlist item https://github.com/corona-warn-app/cwa-wishlist/issues/57 for any updates on the subject. To keep the website repo manageable, we'll close the issue accordingly.
