### ISSUE TITLE
Outdated personal data statement

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2559]
## Where to find the issue

- https://www.coronawarn.app/en/
- https://www.coronawarn.app/de/

## Describe the issue

The statement on https://www.coronawarn.app/en/ under the heading "Data Privacy and Safety", sub-heading "Two objectives" is very outdated. It says:

Only personal data needed for the following two objectives will be processed:
1. Assess personal risk of infection
2. Learn COVID-19 test results faster.

![image](https://user-images.githubusercontent.com/66998419/159119582-e1106493-d77c-47d1-a8fe-8bcf1eca5b56.png)

The [Privacy notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) 16 March 2022, version 2.19 identifies many other data categories which are not mentioned in the above statement:

- Data about your COVID vaccination (data in the COVID vaccination certificate)
- Data about your recovery (data in the COVID recovery certificate)
- Data in the COVID test certificate
- Booking information
- Usage data (data sharing)
- Participation in a survey
- Contents of the error reports
- Confirmation of the authenticity of your app

## Suggested change

Review the section "Two objectives".

Possibly:

- remove it or
- bring it up to date in detail or
- make it more general and refer to the [Privacy notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) document

## Related issue

- https://github.com/corona-warn-app/cwa-website/issues/1729

---
Internal Tracking ID: [EXPOSUREAPP-12902](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12902)

**Comment by Ein-Tim** [comment]
I think this and the `personal_data` FAQ entry should be changed to just point to the Privacy notice. Everything else does not really make sense, IHMO.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> I think this and the personal_data FAQ entry should be changed to just point to the Privacy notice. Everything else does not really make sense, IHMO.

This is also my feeling. I believe that the Open Source Team themselves need to make the decision on this important topic. It should not have to be a community decision.

> IHMO

Friendly reminder: if you are trying to write an abbreviation for "In My Honest Opinion", then the letters come in the order [IMHO](https://en.wiktionary.org/wiki/IMHO), not IHMO! 🙂

**Comment by ahodzic2** [comment]
@MikeMcC399 @Ein-Tim It looks like the Data Privacy Document piece within that same section already contains links to the current PDF as well as a link to /en/privacy for previous versions of the PDF. I would think having another subsection right next to the Data Privacy Document subsection that merely points to the PDF as well would be a bit repetitive/unnecessary.

I would think removing this subsection entirely or updating the objectives to be a bit more up to date would be the two better options. If agreed upon, once the Open Source Team weighs in I can get a PR together (if that's ok with you @MikeMcC399 )

**Comment by MikeMcC399** [comment]
@ahodzic2 

Yes, I'm in favour of just removing that part. It's really up to the Open Source Team to comment now. Right now though they are busy trying to get the new FAQ structure fixed and "out-of-the-door".

Normally for issues that I have submitted myself I would also submit the corresponding PR myself, providing I have the technical ability to solve the issue. That is the case here as well. If there is any doubt about what is wanted by the Open Source Team I would clarify that first before PR submission, as it would only create unnecessary work to submit something which would not get approved.

Thanks for your offer in any case.

**Comment by ahodzic2** [comment]
> @ahodzic2
> 
> Yes, I'm in favour of just removing that part. It's really up to the Open Source Team to comment now. Right now though they are busy trying to get the new FAQ structure fixed and "out-of-the-door".
> 
> Normally for issues that I have submitted myself I would also submit the corresponding PR myself, providing I have the technical ability to solve the issue. That is the case here as well. If there is any doubt about what is wanted by the Open Source Team I would clarify that first before PR submission, as it would only create unnecessary work to submit something which would not get approved.
> 
> Thanks for your offer in any case.

Thank you for the clarification @MikeMcC399 . Looking to get more involved with open source projects as part of my graduate studies so that breakdown definitely helps with understanding the process better :)

**Comment by MikeMcC399** [comment]
@dsarkar 

Do you want me to submit a PR for this? It's a non-urgent tidy-up task.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for your offer, let me clarify internally first. I guess your proposal 

> make it more general and refer to the [Privacy notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) document

is the way to go.

**Comment by MikeMcC399** [comment]
@dsarkar 

Thanks for picking this up.

- make it more general and refer to the [Privacy notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) document - is best, as it should then not need updating again
- remove it - is simplest

**Comment by dsarkar** [comment]
@MikeMcC399 Suggestion:

**Objectives**
Only personal data needed for the following objectives will be processed:
1. Assess personal risk of infection
2. Learn COVID-19 test results faster.
3. Regarding other objectives see the [privacy notice](https://www.coronawarn.app/en/privacy/).

**Comment by MikeMcC399** [comment]
- PR #2750 submitted to resolve this issue
