### ISSUE TITLE
Science 5 graph labels missing years

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2568]
## Where to find the issue

https://www.coronawarn.app/de/science/2022-03-03-science-blog-5/ "Wie viele aktive Nutzende hat die Corona-Warn-App?"

## Describe the issue

Some of the graphs in the [Science 5 blog](https://www.coronawarn.app/de/science/2022-03-03-science-blog-5/) "Wie viele aktive Nutzende hat die Corona-Warn-App?" cover multiple years, however the x-axis do not have year labels on them.

- Abb. 3: Anzahl rot und grün gewarnter Personen pro warnende Person im zeitlichen Verlauf.
- Abb. 4: Positivenanteil nach Risikobenachrichtigung im zeitlichen Verlauf (PCR).
- Abb. 5: Positivenanteil nach Risikobenachrichtigung im zeitlichen Verlauf (RAT).
- Abb. 6: Anteil der Nutzenden, bei denen die Risikoermittlung nicht möglich ist (CWA-Datenspende).
- Abb. 10: Aus dem Anteil der Datenspendenden resultierende Schätzung der Anzahl der aktiven Nutzenden.
- ~~Abb. 14: Kennzahlen zur Installation (Google).~~ Plotly - resolved
- ~~Abb. 15: Angaben zur Installation (Apple).~~ Plotly - resolved
- ~~Abb. 16: Verschiedene Schätzungen von aktiven Nutzenden (im erweiterten Sinne).~~ Plotly - resolved

## Suggested change

Add notation for the years to the labelling of the graphs which cover a time period.

---
Internal Tracking ID: [EXPOSUREAPP-14114](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14114)

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/2567 covers the plotly graphs

**Comment by dsarkar** [comment]
@MikeMcC399 FYI PR https://github.com/corona-warn-app/cwa-website/pull/3136
