### ISSUE TITLE
FAQ contents cut off in list in narrow browser window

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2579]
## Where to find the issue

https://www.coronawarn.app/en/faq/results/

## Describe the issue

After selecting a section heading in the left-side menu if the browser window is narrow then the resulting scrolled list is truncated.

## Steps to reproduce

Google Chrome Desktop Version 99.0.4844.82 (Official Build) (64-bit)

1. Open https://www.coronawarn.app/en/faq/results/ in browser using full screen width
2. View the section in the menu bar on the left with header "App Features" and note there are 12 sub-headings, starting with "Risk Assessment" and ending with "Other features"

![App features](https://user-images.githubusercontent.com/66998419/160165153-264c2321-ab92-4cb7-976f-55f656363c77.jpg)

3. Reduce the width of the browser window to the minimum
4. Scroll down until "What to do, if?" and note that all 12 sub-heading from "App Features" can be displayed
5. Click on right-arrow towards the bottom left
6. Click on "App Features"

![Left menu](https://user-images.githubusercontent.com/66998419/160165339-b552947b-ece2-4d96-b67e-173b635f8517.jpg)

7. Click on "App Features" to expand this section

![Section App features](https://user-images.githubusercontent.com/66998419/160165701-816adf59-6524-4cf4-95d5-525b4cd4f3bb.jpg)

8. Scroll down and notice that the last sub-heading shown is "Check-in" and the last FAQ article displayed in the scrolled list is "Can this information be voluntarily communicated to the health authority? If so, what information is flowing?" This is not the last article from "Check-in" so this sub-heading is truncated. Also the sub-heading "Other features" is not displayed

![Truncated list](https://user-images.githubusercontent.com/66998419/160165715-4c355de9-15d7-42df-a9ca-2cf385fd39e7.jpg)

## Expected results

The scrolled list of FAQ topics should contain all articles from the selected section even if the browser is shrunk to minimum width.

## Workaround

If viewing on a mobile device in portrait orientation, change to landscape orientation and the full list is shown.

---
Internal Tracking ID: EXPOSUREAPP-12445

**Comment by svengabr** [comment]
@MikeMcC399 thanks for your detailed report! I created a Jira issue: EXPOSUREAPP-12445

**Comment by MikeMcC399** [comment]
- After merging of PR #2600 this issue is no longer reproducible.

Closing as resolved.
