### ISSUE TITLE
Article not scrollable on mobile device

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2580]
## Where to find the issue

https://www.coronawarn.app/en/faq/results/

## Describe the issue

https://www.coronawarn.app/en/faq/results/#further_details is truncated if selected through "App Features" > "Other features" and device is in portrait orientation.

## Steps to reproduce

Google Chrome on Android

1. Open https://www.coronawarn.app/en/faq/results/ in Google Chrome with mobile device in portrait orientation
2. Tap right-arrow
3. Tap "Other features" under "App Features"
4. Tap "In-App statistics starting with release 1.1"
5. Note that article is displayed, however only the first paragraph is visible

![image](https://user-images.githubusercontent.com/66998419/160274689-1a4dcf20-21c6-473d-bcf2-84def122dd51.png)

The issue can also be simulated in Google Chrome Desktop. Press F12 (or Ctrl+Shift+I) for developer tools, toggle the device toolbar (Ctrl+Shift+M) and select Samsung Galaxy A51/A71.  Then follow the above steps to reproduce.

## Expected results

The full text of the article https://www.coronawarn.app/en/faq/results/#further_details should be displayed in portrait mode.

## Workaround

Rotate the device to landscape orientation.

---
Internal Tracking ID: EXPOSUREAPP-12452

**Comment by svengabr** [comment]
Internal Tracking ID: EXPOSUREAPP-12452

**Comment by MikeMcC399** [comment]
- This issue is no longer reproducible.

- I suspect that https://github.com/corona-warn-app/cwa-website/pull/2600 may have solved the issue.
