### ISSUE TITLE
Extend Cypress testing for FAQs on mobile-sized browser

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2585]
## Feature description

Add testing to the Cypress suite in https://github.com/corona-warn-app/cwa-website/tree/master/cypress/integration to cover the correct display of FAQ articles in a browser window using a size which is typical of one on a conventional mobile device smartphone in portrait orientation.

### Problem

1. PR https://github.com/corona-warn-app/cwa-website/pull/2434 has implemented a redesign of the CWA FAQs on https://www.coronawarn.app/en/faq/ and https://www.coronawarn.app/de/faq/.
2. The redesign has caused access from embedded links in the CWA on mobile devices to fail to display the requested FAQ article. Either the article is not displayed at all or it is not displayed expanded. See issue https://github.com/corona-warn-app/cwa-website/issues/2577.
3. The Cypress test suite, run using `npm test`, did not identify these issues prior to Move-To-Production.

### Motivation

Running the Cypress test suite should give a high level of confidence that the website performs as needed and should provide good information to avoid publishing content which breaks the interface between CWA on the mobile device and FAQ content on https://www.coronawarn.app.

## Is this something you're interested in working on

I don't have the skills to write Cypress tests. I'm happy to review any PR which adds this functionality though.

---
Internal Tracking ID: [EXPOSUREAPP-13405](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13405)

**Comment by MikeMcC399** [comment]
- Resolving the issue https://github.com/corona-warn-app/cwa-website/issues/2668 would help to make testing the availability of the expected FAQ URLs simpler.

**Comment by MikeMcC399** [comment]
Perhaps the first step should be a Cypress test which checks that all URLs which the app uses are in fact present in the web.

**Comment by MikeMcC399** [comment]
- Regarding the [comment above](https://github.com/corona-warn-app/cwa-website/issues/2585#issuecomment-1091949585) I added the enhancement request #2909.

**Comment by MikeMcC399** [comment]
- https://github.com/corona-warn-app/cwa-website/issues/2914 is another issue which only occurs on a mobile device and which was not caught by Cypress tests.

**Comment by chrisenitan** [comment]
It seems most of the links to the website are now being tested on https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/app_to_web.js on https://github.com/corona-warn-app/cwa-website/pull/2949
- So my focus was mostly on testing the Faq page on both mobile and a desktop view in

**Comment by chrisenitan** [comment]
It seems most of the links to the website are now being tested on https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/app_to_web.js on https://github.com/corona-warn-app/cwa-website/pull/2949
- So my focus was mostly on testing the Faq page on both mobile and a desktop view in https://github.com/corona-warn-app/cwa-website/pull/2967

**Comment by thorbenkuro** [comment]
@MikeMcC399 Thank you for reporting the issue and @chrisenitan thank you for your pull request! We have created an internal ticket for it.
Internal Tracking ID: [EXPOSUREAPP-13405](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13405)

**Comment by MikeMcC399** [comment]
@chrisenitan 

Thank you for responding to this issue!

- Since your PR https://github.com/corona-warn-app/cwa-website/pull/2967 has now been merged, I will close the issue.
