### ISSUE TITLE
Extend Cypress testing to check video links

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2590]
## Feature description

Add video link testing to the Cypress suite in https://github.com/corona-warn-app/cwa-website/tree/master/cypress/integration.

### Problem

1. PR https://github.com/corona-warn-app/cwa-website/pull/2434 has implemented a redesign of the CWA FAQs on https://www.coronawarn.app/en/faq/ and https://www.coronawarn.app/de/faq/.
2. The redesign has caused a video link to fail. See issue https://github.com/corona-warn-app/cwa-website/issues/2588.
3. The Cypress test suite, run using `npm test`, did not identify this issue prior to Move-To-Production.

One of the missed bad links was in https://www.coronawarn.app/en/faq/results/index.html with the contents

`<video src='../../assets/video/erklaerfilm_en.mp4' class='w-100' controls='' alt='Corona-Warn-App - explanatory film'></video>`. 

Although at the time the Cypress test suite was not scanning in the the `/faq/results` directory, even if it had have been scanning there, it was not actually checking video links.

### Motivation

Running the Cypress test suite should give a high level of confidence that the website performs as needed, including ensuring that links to videos are correct.

## Is this something you're interested in working on

I don't have the skills to write Cypress tests. I'm happy to review any PR which adds this functionality though.

**Comment by ahodzic2** [comment]
@MikeMcC399 

If no one else takes a stab at it, I can take a look and see if I can get a PR together this weekend. Had quite a good time with the last cypress issue.

**Comment by dsarkar** [comment]
Hi @ahodzic2, thanks for offering assistance here. PR will be appreciated!

**Comment by ahodzic2** [comment]
Got a bit delayed this weekend, will start looking into this today :)

**Comment by ahodzic2** [comment]
I've been battling with this over the last few days and I've gotten the script written to grab video elements, ensure they are paused initially, play the video, ensure they play. However, I am running into 2 issues that have stalled my progress:

1. If I "break" the video by messing with the source, it throws a silent exception but ultimately the test passes.
2. If I run my script for a page that does not contain a video element, the test for that page throws an error and breaks. Ideally if there isn't a video element on a given page, it would allow the test to pass but maybe just indicate no video element found. OR only pass pages that contain videos, in which case the failed test would indicate an issue with a video element.

Going to give it another go, but may end up passing along what I have so far for someone else to try their hand.

**Comment by ahodzic2** [comment]
@dsarkar Yes, will do. I've been a bit occupied this past week or two but I agree a PR could get some helpful eyes on what I have together so far 🙂

**Comment by MikeMcC399** [comment]
@ahodzic2 

Thanks for taking a look at this. My idea was just to check out that the links to the videos are correct i.e. that the target address exists, not to actually try to run the video. Maybe my idea isn't what Cypress is designed to do though. I'm trying to get familiar with Cypress, however I'm not at the stage where I can make suggestions yet.

**Comment by ahodzic2** [comment]
@MikeMcC399 

Yeah that is certainly part of what I would like the test to capture. Currently, I just can't get the script to mark any sort of issue with the video as a failure (problematic source being one of those issues). The other problem currently is that if there is no video on the page, it marks that as a failure, when it would ideally recognize there is no video and mark it as passed and move on.

I've been juggling a few projects, but hopefully once I get the PR open and some initial code presented, someone may just be able to help me with what feels like the missing 20%.

**Comment by ahodzic2** [comment]
Just to update the group:

Things got a bit hectic on my side after picking up this Issue. I'll get back to work on this and create a PR by the end of the weekend to collaborate with others if I'm still stuck.

**Comment by MikeMcC399** [comment]
@ahodzic2 

Please note that the Cypress version has been updated to 9.6.1.

I'm not sure which tests you are implementing. It would be good if they are quick to run and do not try to run each video, which would take longer. In my opinion it would be sufficient if the tests just make sure that the videos exist at the location which tries to call them.

**Comment by ahodzic2** [comment]
@MikeMcC399 

I did see the thread related to the Cypress update. Thank you for the heads up!

My plan is to have it make sure the video is playable, which does not require it to play the entire video. My roadblocks have been related to my inexperience with the particular syntax. I think with some help from the community (PR still on course for this weekend) and/or some additional research, I should have a solution ready to test videos efficiently 😁.

**Comment by ahodzic2** [comment]
I have updated my clone to capture the updated version of Cypress.

The PR was created as discussed/requested (https://github.com/corona-warn-app/cwa-website/pull/2907#issue-1244597659). I am going to keep trying to figure out the last remaining items, but perhaps someone with more experience with JS/Cypress will solve it faster than I can.

More to come! :)

**Comment by MikeMcC399** [comment]
- PR #2949 is consolidating PRs to implement this suggestion.

**Comment by ahodzic2** [comment]
https://github.com/corona-warn-app/cwa-website/pull/2950 Resolves this issue.
