### ISSUE TITLE
Unable to expand FAQ entries

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2592]
## Where to find the issue
- https://www.coronawarn.app/en/faq
- https://www.coronawarn.app/de/faq

## Describe the issue
FAQ entries can't be expanded in some circumstances and thus the content can't be seen.

## Steps to reproduce this issue

1. Type "When do I receive my PCR test result in the app?" in the FAQ search
2. Expand the section "App Features"
3. Attempt to expand any FAQ entry in this section

## Suggested change
Make it possible to expand the FAQ entries.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Are you doing this on a mobile device?

It makes a difference whether you have a wide browser window (like on a desktop) or a narrow browser window (like on a mobile device in portrait mode).

**Comment by Ein-Tim** [comment]
Clsoing in favor of the more detailed report #2594.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I'm sorry that I duplicated your issue and it was not intentional. I just got a bit confused about the purpose of the other issue I'm afraid!

**Comment by Ein-Tim** [comment]
@MikeMcC399 

No problem!
