### ISSUE TITLE
Glossary links to other Glossary articles fail after search

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2596]
## Where to find the issue

https://www.coronawarn.app/en/faq/

## Describe the issue

If a Glossary article is displayed following a search, then links to other Glossary articles do not work and there is no error message.

## Steps to reproduce

1. In Google Chrome Desktop full screen width
2. Open https://www.coronawarn.app/en/faq/
3. In FAQ search field enter "country of arrival", click Search
4. Note that browser address field now shows `https://www.coronawarn.app/en/faq/results/?search=country+of+arrival&topic=all`

![country of arrival](https://user-images.githubusercontent.com/66998419/160289673-7262c41f-9e30-449f-9165-9e74a2034c46.jpg)

5. Click on Digital COVID Certificates
6. Note that nothing happens
7. The hyperlink is trying to access `https://www.coronawarn.app/en/faq/results/?search=country+of+arrival&topic=all#glossary_digital_certificate`

## Expected results

If a Glossary article is viewed following a search, then any links it contains to other Glossary articles should work the same as if the original Glossary article had been opened directly instead of through a search.

In the above steps to reproduce, if the Glossary article https://www.coronawarn.app/en/faq/results/#glossary_business_rules is opened directly, then the link to https://www.coronawarn.app/en/faq/results/#glossary_digital_certificate works correctly.

---
Internal Tracking ID: EXPOSUREAPP-12447

**Comment by svengabr** [comment]
Internal Tracking ID: EXPOSUREAPP-12447

**Comment by MikeMcC399** [comment]
- This is possibly related to https://github.com/corona-warn-app/cwa-website/issues/2668.

**Comment by MikeMcC399** [comment]
In the previous FAQ layout the URL `https://www.coronawarn.app/en/faq/results/?search=country+of+arrival&topic=all#glossary_digital_certificate` would open the correct glossary article `https://www.coronawarn.app/en/faq/#glossary_digital_certificate`.

The mechanism is described in the [FAQ_SEARCH_SUMMARY.md](https://github.com/corona-warn-app/cwa-website/blob/master/docs/FAQ_SEARCH_SUMMARY.md#url-parameters) document:

"If, in addition to the search parameter, a hash (e.g., #ios_136) is part of the url to address one entry directly, the search parameter is ignored."

So the change of how this works in the new FAQ layout is a regression from the previous FAQ layout and system.

**Comment by dsarkar** [comment]
@MikeMcC399 Fixed.

**Comment by MikeMcC399** [comment]
- PR #2715 fixed this issue.
