### ISSUE TITLE
Enable http2

### ISSUE THREAD

**Issue by Julian-B90** [corona-warn-app/cwa-website#26]
For better performance enable http2.

### Introduction to HTTP/2
https://developers.google.com/web/fundamentals/performance/http2

**Comment by SebastianWolf-SAP** [comment]
Thanks for the report. We will follow-up with the colleague who are responsible for the hosting!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by SebastianWolf-SAP** [comment]
It seems that http/2 is currently not supported. As the impact is probably not that big, we won't follow-up on a dedicated implementation of http/2.

Thank you for your understanding!

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team
