### ISSUE TITLE
FAQ search input boxes do not resize dynamically

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2601]
## Where to find the issue

https://www.coronawarn.app/en/faq/

## Describe the issue

If the FAQ https://www.coronawarn.app/en/faq/ page is reduced from wide to narrow, then the boxes are not reorganized and the content is not readable.

## Steps to reproduce

1. Open https://www.coronawarn.app/en/faq/ in Google Chrome Desktop using full-screen width

![FAQ search 1](https://user-images.githubusercontent.com/66998419/160383030-7545fff3-ca37-405a-b404-460c49f5d5c1.jpg)

2. Drag the side of the browser window to reduce the width to the minimum

![FAQ search 2](https://user-images.githubusercontent.com/66998419/160383064-ee215a86-1942-4b98-9956-19d05bee41f1.jpg)

3. Note that the hint text in the search field is no longer readable, nor is the default text in the category field readable.

## Suggested change

If the window is dynamically resized, then adjust the placement of the search boxes and button accordingly, so the contents is always readable.

## Workaround

Press F5 (refresh) to redraw the screen.

![FAQ search 3](https://user-images.githubusercontent.com/66998419/160383089-7a442b48-cbcd-45b8-8024-332a4d37bf36.jpg)

**Comment by svengabr** [comment]
Closed as I am not fine with the changes made to the layout. 

The changed version looks like this on mobile:
![2022-03-30 14_00_04-Open-Source-Projekt Corona-Warn-App – FAQ](https://user-images.githubusercontent.com/4686874/160837988-301cba54-d2b3-480e-8e00-933e9b92dc6a.png)

I expect a mobile-first solution like this:
![2022-03-30 14_28_00-Open-Source-Projekt Corona-Warn-App – FAQ](https://user-images.githubusercontent.com/4686874/160838088-0316a796-88a0-4d98-b9f3-3a9d50ab883d.png)

**Comment by MikeMcC399** [comment]
@svengabr 

- I also tried out the PR #2638 before you closed it and I found it did not solve the issue. I was just about to re-check that I had not made a mistake when I tested it, but you got there first!

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/2646 is resolving the issue for https://www.coronawarn.app/en/faq/results/.
