### ISSUE TITLE
Out of date information in `vac_cert_red_warning` & `voluntary_self_quarantine` reg. entitlement to free corona test with increased risk encounter(s)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2607]
## Where to find the issue
- https://www.coronawarn.app/en/faq/results/#vac_cert_red_warning
- https://www.coronawarn.app/de/faq/results/#vac_cert_red_warning
- https://www.coronawarn.app/en/faq/results/#voluntary_self_quarantine 
- https://www.coronawarn.app/de/faq/results/#voluntary_self_quarantine

## Describe the issue
The FAQ entry states: 
"In case of an increased risk warning (red tile), you are entitled to a free test. This does not necessarily have to be a PCR test."

This statement is no longer true, see https://github.com/corona-warn-app/cwa-documentation/issues/877.

## Suggested change
Remove the sentence.

## Additional information
PR follows soon.

**Comment by svengabr** [comment]
Related to https://github.com/corona-warn-app/cwa-documentation/issues/877 which I have already closed.
The team is already working on an overhaul of "Handlungshinweise" and agreed to not make any text changes to the sentence 

`"Bei einer Warnung über ein erhöhtes Risiko (\"Rote Kachel\") haben Sie Anspruch auf einen kostenlosen Test. Dies muss nicht notwendigerweise ein PCR-Test sein."`

Once the rework is done, we will update the FAQ accordingly

**Comment by Ein-Tim** [comment]
Thank you @svengabr! 

Could you please reopen the issue in the documentation repo, as the problem I reported was not fixed?

Thanks!

**Comment by MikeMcC399** [comment]
There is an explicit notice about this in https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html#c23926

![image](https://user-images.githubusercontent.com/66998419/161303404-5fbf3412-cf6d-4bb8-96ee-3b1a55ce6001.png)

**Comment by Ein-Tim** [comment]
@MikeMcC399 Thanks!

This again underlines that saying that there is an entitlement for a free test with an increased risk encounter in the CWA is just **not** true.

**Comment by MikeMcC399** [comment]
@svengabr

The paragraph in the [TestV](https://www.buzer.de/Neue_Coronavirus-Testverordnung.htm) §2 Absatz 2, Nummer 5 which said "Personen, die durch die Corona-Warn-App des Robert Koch-Institutes eine Warnung mit der Statusanzeige erhöhtes Risiko erhalten haben," was repealed on Feb 11, 2022. See https://www.buzer.de/gesetz/14991/al164021-0.htm for a comparison of versions.

It seems a long time to get the CWA FAQs updated accordingly where the FAQ text no longer conforms to the regulations which were changed more than two months ago. Also it means that the CWA FAQs are not in line with the [website information from the Bundesministerium für Gesundheit](https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html#c23926). 

Do you have a planned date for the change in the meantime?

---

https://www.coronawarn.app/en/faq/results/#vac_cert_red_warning
![vac_cert_red_warning](https://user-images.githubusercontent.com/66998419/164983664-84e78a15-7e85-489a-a202-8d7aa5007968.jpg)

---

https://www.coronawarn.app/en/faq/results/#voluntary_self_quarantine
![voluntary_self_quarantine](https://user-images.githubusercontent.com/66998419/164983685-c3e5aeaf-12b9-4832-b79e-e1743d092a29.jpg)

---

- https://github.com/corona-warn-app/cwa-documentation/issues/877 has been reopened.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Alright: Proposal in order to be more specific at least in the FAQ use the sentence or similar: 

> Es besteht der Anspruch für eine kostenfreie Antigen-Schnelltestung nach § 4a Satz 1 Testverordnung (Bürgertestung) zur Verfügung.

**Comment by dsarkar** [comment]
@Ein-Tim  actually the sentence is wrong: Better:

" Es besteht der Anspruch für eine kostenfreie Antigen-Schnelltestung nach § 4a Satz 1 Testverordnung (Bürgertestung)"

**Comment by Ein-Tim** [comment]
@dsarkar Thanks! PR follows later today.

**Comment by MikeMcC399** [comment]
https://www.duden.de/rechtschreibung/Anspruch

"Anspruch auf ..." instead of "Anspruch für ..."?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I'd use this text: 

> Es besteht der Anspruch auf eine kostenfreie Antigen-Schnelltestung nach § 4a Satz 1 Testverordnung (Bürgertestung

**Comment by MikeMcC399** [comment]
@Ein-Tim 

That looks correct according to https://www.gesetze-im-internet.de/coronatestv_2021-10/__4a.html!

Maybe more details should be provided though, as in the quote from BMG.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I'll start a PR with only the text I quoted above and we can then there discuss whether more details should be added.

**Comment by Ein-Tim** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/2921 provided.
