### ISSUE TITLE
Cypress check_anchor_links.js misses issues in FAQ

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2613]
## Where to find the issue

[cypress/integration/check_anchor_links.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/check_anchor_links.js)

## Describe the issue

The Cypress test [cypress/integration/check_anchor_links.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/check_anchor_links.js) does not find anchor link issues in the new FAQ structure under https://www.coronawarn.app/en/faq/results/ and https://www.coronawarn.app/de/faq/results/

## Steps to reproduce

Manually introduce a bad anchor link into `/src/data/faq.json`.

`npm run test:open`
Select `check_anchor_links.js`
Note that the bad anchor link is not found

## Suggested change

Add the directories:

- `/en/faq/results/` and
- `/de/faq/results/`

to 

[cypress/integration/check_anchor_links.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/check_anchor_links.js)

This is however not sufficient as then the test fails with a syntax error:

```
  1) Check for broken anchor links
       "/de/faq/results/" - Check for broken anchor links:
     Error: Syntax error, unrecognized expression: #
```

**Comment by MikeMcC399** [comment]
This issue needs assistance from the Open Source Team (@brifemu / @larswmh ?) regarding the syntax error preventing an update to cover testing the new directories `/faq/results`.

**Comment by ahodzic2** [comment]
@MikeMcC399 I can try to take a gander at it and see if I can assist. Not exactly my cup of tea either but I've got some time later and a willingness to try/learn ;)

**Comment by MikeMcC399** [comment]
@ahodzic2 
If you learn Cypress you will not be alone. See https://www.npmtrends.com/cypress for download trends.

**Comment by ahodzic2** [comment]
@MikeMcC399 I was taking a look at it yesterday and I suspect that it may be having an issue with a particular anchor. From the test results it does successfully get and test a number of anchor links under en/faq/results/ and de/faq/results but then throws that syntax error.

Will continue to play around with it today/tomorrow and see if I can pinpoint the issue.

**Comment by MikeMcC399** [comment]
@ahodzic2 
You are right that it successfully executes some tests before it stops with the syntax error. 
It appears that it cannot deal with the html code `<a href='#'`.

**Comment by ahodzic2** [comment]
@MikeMcC399 correct, that's what I'm seeing as well. I believe it's based on the .get() method not being able to handle the ID selector (#) when the ID is blank.
See [https://github.com/cypress-io/cypress/issues/15020](https://github.com/cypress-io/cypress/issues/15020)

Possible solutions I have in mind would be:

- Account for these instances in check_anchor_links.is
Or
- Reference href='#' another way in the faq.json and faq_de.json.

More to come.

**Comment by ahodzic2** [comment]
@MikeMcC399 I think I've done it. Doing some additional testing to make sure the results are accurate, but if they are then I can send out a PR for this and open a separate issue for any broken anchor links. More to come shortly!

**Comment by ahodzic2** [comment]
@MikeMcC399 I believe the issue is the new FAQ URLs such as "/en/faq/results/?search=&topic=all". When you are at `/en/faq/results/` and select the small FAQ header above the App Features header, the URL flashes "/en/faq/results/?search=&topic=all#" for a quick moment before settling on "/en/faq/results/?search=&topic=all".

I believe based on how the `check_anchor_links.js` file splits the URL on "#" this causes issues when the [1] element of the resulting array is referenced as in this scenario the [1] element is "" and therefore we see the resulting syntax error.

I added an additional line in `check_anchor_links.js` to handle these scenarios and I was able to run a successful test and find some broken anchor links (Which I will open a new issue and separate PR for).

I'll send out a PR for this issue shortly.

**Comment by MikeMcC399** [comment]
@ahodzic2 
Thanks for the research and feedback! I need to step back and let the Open Source Team comment about your findings and suggestions to fix the Cypress script.

It is excellent that you were able to find some broken links. Without having `check_anchor_links.js` properly checking `/faq/results`, which is the most volatile area of the website, we are flying blind!

**Comment by ahodzic2** [comment]
@MikeMcC399 I created a PR for my proposed update to `check.anchor.links.js` (#2656) so the Open Source Team and others can see the proposed update and provide comments as fit.

I'll create a separate PR to differentiate between the actual cypress test and link issues in /faq/results/ and the Open Source Team can provide input accordingly.

Ended up down a rabbit hole working on this Cypress item. Makes for a good night of sleep :)

**Comment by MikeMcC399** [comment]
Thanks to @ahodzic2 for investigating the Cypress test 
[cypress/integration/check_anchor_links.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/check_anchor_links.js), adding the directories `/en/faq/results` and `/de/faq/results` and resolving the syntax issue arising! 👍🏻 

The steps
`npm run test:open`
Select `check_anchor_links.js`

cause the test to run to completion. Bad links in 
-  `/en/faq/results` and 
- `/de/faq/results` 
are now identified.

Therefore this issue is now resolved.

See also:
- https://github.com/corona-warn-app/cwa-website/issues/2666
- https://github.com/corona-warn-app/cwa-website/pull/2657

**Comment by MikeMcC399** [comment]
Alternative confirmation as follows:

`npx cypress run -s cypress/integration/check_anchor_links.js -c baseUrl=https://coronawarn.app`

This command runs `check_anchor_links.js` on the production website https://coronawarn.app in headless mode using the default Electron browser.

```
$ npx cypress run -s cypress/integration/check_anchor_links.js -c baseUrl=https://coronawarn.app


====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    7.7.0                                                                              │
  │ Browser:    Electron 89 (headless)                                                             │
  │ Specs:      1 found (check_anchor_links.js)                                                    │
  │ Searched:   cypress\integration\check_anchor_links.js                                          │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  check_anchor_links.js                                                           (1 of 1)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating


  Check for broken anchor links
    √ Check if txt results exist
    √ "/de" - Check for broken anchor links (4683ms)
    √ "/en" - Check for broken anchor links (2385ms)
    √ "/de/eventregistration/" - Check for broken anchor links (1747ms)
    √ "/en/eventregistration/" - Check for broken anchor links (1770ms)
    √ "/de/community/" - Check for broken anchor links (1085ms)
    √ "/en/community/" - Check for broken anchor links (1386ms)
    √ "/de/analysis/" - Check for broken anchor links (2713ms)
    √ "/en/analysis/" - Check for broken anchor links (1826ms)
    √ "/de/blog/archiv/" - Check for broken anchor links (1961ms)
    √ "/en/blog/archive/" - Check for broken anchor links (1423ms)
    √ "/de/screenshots/" - Check for broken anchor links (1562ms)
    √ "/en/screenshots/" - Check for broken anchor links (2237ms)
    √ "/de/faq/" - Check for broken anchor links (1715ms)
    √ "/de/faq/results/" - Check for broken anchor links (3021ms)
    √ "/en/faq/" - Check for broken anchor links (799ms)
    √ "/en/faq/results/" - Check for broken anchor links (3605ms)
    √ "/de/rat-partner/" - Check for broken anchor links (1924ms)
    √ "/en/rat-partner/" - Check for broken anchor links (1281ms)
    √ "/de/privacy/" - Check for broken anchor links (831ms)
    √ "/en/privacy/" - Check for broken anchor links (931ms)
    √ "/de/terms-of-use/" - Check for broken anchor links (1072ms)
    √ "/en/terms-of-use/" - Check for broken anchor links (1367ms)
    √ "/de/event-qr-code-guide/" - Check for broken anchor links (2874ms)
    √ "/en/event-qr-code-guide/" - Check for broken anchor links (2011ms)
    √ "/de/blog/" - Check for broken anchor links (1389ms)
    √ "/en/blog/" - Check for broken anchor links (1697ms)
    √ "/de/science/" - Check for broken anchor links (1054ms)
    √ "/en/science/" - Check for broken anchor links (1101ms)
    √ "/de/simple-language/" - Check for broken anchor links (4813ms)
    √ "/en/simple-language/" - Check for broken anchor links (1016ms)
    √ "/de/sign-language/" - Check for broken anchor links (1710ms)
    √ "/en/sign-language/" - Check for broken anchor links (2467ms)

  Check for broken anchor links on entries
    √ "/de/blog/" entries - Check for broken links (3517ms)
    √ "/en/blog/" entries - Check for broken links (2101ms)
    √ "/de/science/" entries - Check for broken links (967ms)
    √ "/en/science/" entries - Check for broken links (786ms)


  37 passing (1m)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        37                                                                               │
  │ Passing:      37                                                                               │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     1 minute, 9 seconds                                                              │
  │ Spec Ran:     check_anchor_links.js                                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ √  check_anchor_links.js                    01:09       37       37        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    √  All specs passed!                        01:09       37       37        -        -        -
```
