### ISSUE TITLE
FAQ entry `dcc_replacement` needed

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2623]
## Where to find the issue
Seems like users who are offered to get their certificate reissued will find a link to the FAQ entry https://www.coronawarn.app/de/faq/results/#dcc_replacement / https://www.coronawarn.app/en/faq/results/#dcc_replacement (see https://github.com/corona-warn-app/cwa-app-ccl/pull/61).

## Describe the issue
The FAQ entry does not exists.

## Suggested change
Add the FAQ entry.

**Comment by MikeMcC399** [comment]
@Ein-Tim

I don't think this functionality is live at this time:

@dsarkar wrote in https://github.com/corona-warn-app/cwa-website/issues/2541#issuecomment-10691431332 "Version 2.19 has been technically prepared to exchange certificates or register PCR rapid tests and transmit test results. Once the certificate exchange rules are implemented and PCR quick test QR codes are issued, these two features will be available to CWA users. We will provide timely information on these features in the form of a blog and/or FAQ."

**Comment by Ein-Tim** [comment]
PR https://github.com/corona-warn-app/cwa-app-ccl/pull/57, which enabled the reissuance feature was merged into `main`. Afterwards, the Pre-Release version https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v1.2.2, which would be the next version. 
I asked @mlenkeit for an update in https://github.com/corona-warn-app/cwa-app-ccl/pull/57#issuecomment-1082102063.

Anyways, I opened this issue to be a kind of reminder so that this is not forgotten.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Mine too, but did you remember that it can take up to 24h till all phones are updated. So it could be possible that 1.2.2 or 1.2.3 is already released.

I don't think so, but I just want to make sure that this is on track and nobody forgets to add the FAQ entry.

**Comment by mlenkeit** [comment]
@Ein-Tim thanks for raising this, we are aware of the missing FAQ entry.

The CCL version 1.2.3, which uses the FAQ link, is not set live yet.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim PR is on its way. PR https://github.com/corona-warn-app/cwa-website/pull/2630

**Comment by mlenkeit** [comment]
The FAQ entry is available and the CCL update is also live now, should roll out to all devices within the next 24 hours.
