### ISSUE TITLE
Search result counter in the bread crumbs is wrong for glossary entries

### ISSUE THREAD

**Issue by Crystalskulls** [corona-warn-app/cwa-website#2626]
## Where to find the issue

https://www.coronawarn.app/en/faq/
https://www.coronawarn.app/de/faq/

## Describe the issue

The search result counter in the bread crumbs only counts matches in the glossary title. If a search term is only present in a glossary description the counter is not incremented.

## Steps to reproduce

1. Open https://www.coronawarn.app/en/faq/
2. Enter "Rules" in the search field, category "All", click on the search button
3. In the left hand menu click on "Glossary A-Z"
4. Notice, that the search counter result in the bread crumbs is wrong.

<img width="1351" alt="faq_search_result_counter" src="https://user-images.githubusercontent.com/25111875/160690155-1dc8c5ec-bdd9-4113-a175-62859006bea2.png">

## Suggested change
The search result counter should increment if the search term matchs the glossary element "title" or "description".

I would like to work on this issue and create a PR

**Comment by Crystalskulls** [comment]
Since my last PR #2625 the bread-topic for the glossary shows the result count. I'm sorry for this, i will fix this along with this issue
<img width="1351" alt="faq-bread-topic" src="https://user-images.githubusercontent.com/25111875/161069130-5a2e59e0-79d9-4187-b2c3-236a526541d5.png">

**Comment by svengabr** [comment]
While I can see the issue when clicking on `Glossary` is gone with your code change, there is still some off behavior with the search results in general. Not related to this PR.

![2022-03-31 16_41_44-rdp - 192 168 178 36_3389 - Remotedesktopverbindung](https://user-images.githubusercontent.com/4686874/161083259-d7de7595-995e-430a-bcb5-ab118a760cbe.png)

**Comment by MikeMcC399** [comment]
@Crystalskulls 

Since I could not find an corresponding open issue according to your comments, I opened a new issue https://github.com/corona-warn-app/cwa-website/issues/2760.
