### ISSUE TITLE
Reduce "14" to "10" where it corresponds to the days of the risk calculation

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-website#2670]
## Where to find the issue
e.g. https://www.coronawarn.app/de/faq/results/#new_device :
Falls Sie innerhalb der 14 Tage auf COVID-19 getestet wurden, tragen Sie den PCR-Test-QR-Code auf Ihrem neuen Gerät ein. Ist das Testergebnis positiv, sollten Sie das Testergebnis auf beiden Geräten teilen. Für das Teilen eines Testergebnisses auf mehreren Geräten beachten Sie bitte den FAQ Eintrag [Wie teile ich ein positives Testergebnis auf mehreren Geräten?](https://www.coronawarn.app/de/faq/results/#test_multiple_devices).

Nach 14 Tagen enthält Ihr altes Gerät keine relevanten Einträge für die Risiko-Ermittlung mehr. Sie brauchen den Risikostatus auf diesem Gerät dann nicht weiter zu beachten und können die Corona-Warn-App dort entfernen.

## Describe the issue
Only 10 days are relevant now.

## Suggested change
Change everywhere "14 days" to "10 days" (of course in both languages).

**Comment by MikeMcC399** [comment]
@DerVogel2020 

Thanks for bringing this up!

- https://www.coronawarn.app/en/faq/results/#new_device unfortunately was not changed at all.
- https://www.coronawarn.app/de/faq/results/#new_device was already changed in the first paragraph:

"Damit Sie trotzdem über mögliche Risiko-Begegnungen informiert werden, empfehlen wir Ihnen, den Risikostatus auf dem alten Gerät noch mindestens 14 Tage (10 Tage ab Version 2.20) zu beobachten, nachdem Sie die Corona-Warn-App auf dem neuen Gerät installiert haben."

So I suggest that instead of changing 14 days to 10 days, it needs to list both. To simplify the text, the first mention defines the version differences and thereafter write `14 or 10 days` (EN)  `14 bzw. 10 Tage` (DE) without mentioning the version.

**Comment by amouzayanni** [comment]
@MikeMcC399

Hello! I'm working with @ahodzic2 and I'd like to resolve this issue if you'd like it done.

**Comment by MikeMcC399** [comment]
@amouzayanni 

@DerVogel2020 has contributed in the past, so might also want to provide a PR. Other than that I suggest waiting for feedback from the Open Source Team. I'm not the one to decide, since I am a community contributor with no official capacity.

**Comment by DerVogel2020** [comment]
@amouzayanni From my point of view, it seems difficult to determine all relevant code lines. So feel free to provide a PR.

**Comment by amouzayanni** [comment]
Will do! I'll get that pull request ready ASAP.

**Comment by amouzayanni** [comment]
After reviewing the German FAQ, I no longer feel comfortable making changes to it since I fear the language barrier would prevent me from being accurate. I've finished the English FAQ and I'm ready to make the pull request. Will someone else be able to complete the German FAQ?

**Comment by Ein-Tim** [comment]
@amouzayanni 

For sure. 

Will you invite me to access your repo so that I can push the changes there?

**Comment by amouzayanni** [comment]
@Ein-Tim

Just sent the invitation. Thanks for the help! I'd be happy to get in touch, how should I do so?

**Comment by Ein-Tim** [comment]
@amouzayanni 

You can use this invitation link to join our [Slack channel](https://github.com/corona-warn-app/cwa-documentation/issues/379): https://join.slack.com/t/covidapps/shared_invite/zt-1704ve9qo-XI_1bKwa2eHle4g44AepHw

**Comment by MikeMcC399** [comment]
Regarding my [comment ](https://github.com/corona-warn-app/cwa-website/issues/2670#issuecomment-1087666828) about considering the case of changing the app during the 14 or 10 days, I went through two scenarios:

- a person goes on vacation to another EU country
- a person moves permanently to another EU country

where the other EU country has their own app and the move happens during this period. I think in both cases that it would be quite unlikely that the user would install a different app on the old phone during these two weeks. So I would ignore this case.

Sorry for making this more complicated than it need have been. I was just trying to make sure we didn't give users incorrect information.

**Comment by ahodzic2** [comment]
I believe with the PR merged this issue can be closed?
