### ISSUE TITLE
FAQ #news backwards compatibility

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2671]
## Where to find the issue

- https://www.coronawarn.app/en/faq/#news

## Describe the issue

The previous FAQ web layout contained an anchor [#news](https://www.coronawarn.app/en/faq/#news). There is no equivalent anchor in the current FAQ layout.

![FAQ previous news](https://user-images.githubusercontent.com/66998419/161486460-bcb68a20-0499-43cc-a751-d7e3917af941.jpg)

Attempting to access https://www.coronawarn.app/en/faq/#news displays the complete FAQ.

- This issue follows on from https://github.com/corona-warn-app/cwa-website/issues/2582.

## Steps to reproduce

Attempt to access https://www.coronawarn.app/en/faq/#news in a web browser.

## Suggested change

- Although @dsarkar wrote in https://github.com/corona-warn-app/cwa-website/pull/2598 "#news --> section is not needed, this was a wild set of different articles which can be found in the correct topic now" I suggest the anchor would be good to use to point to the real places to read the news about the Corona-Warn-App.

Add a new FAQ article `#news`, for instance in the App Features / Other features section (https://www.coronawarn.app/en/faq/results/#other_features), which answers the question "Where can I find news on the Corona-Warn-App? and describes:
1. The Blog https://www.coronawarn.app/en/blog/ and
2. The Twitter channel https://twitter.com/coronawarnapp

as sources of news.

**Comment by Ein-Tim** [comment]
Another suggestion redirect from #news to the blog.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> Another suggestion redirect from #news to the blog.

I prefer to have an explicit FAQ article https://www.coronawarn.app/en/faq/results/#news 
- it allows to mention the Blog and Twitter together
- the existing redirect mechanism only redirects between FAQs
- there is another redirect mechanism between Blogs
- the two do not overlap

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I agree with you, keeping FAQ redirects and blog redirects separate makes most sense.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim That is a good idea, indeed. Thanks for the suggestion.

**Comment by MikeMcC399** [comment]
@dsarkar 

Would you like a PR from me to implement this suggestion? It would be quite a simple text addition.

**Comment by larswmh** [comment]
@MikeMcC399 we would appreciate a PR for this and have actually already worked on a text for this. 

"Wo kann ich Neuigkeiten über die Corona-Warn-App finden?

Im Blog werden in regelmäßigen Abständen Informationen zu neuen Versionen der Corona-Warn-App veröffentlicht. Zusätzlich erscheinen bei Bedarf Informationen zu verschiedenen Themen, wie beispielsweise zu Verhaltensempfehlungen bei einer roten Kachel.
Des Weiteren werden Neuigkeiten über die Corona-Warn-App auf Twitter veröffentlicht. Insbesondere dort hat man als Nutzer die Möglichkeit, themenbezogene Fragen zu stellen und wird unter der hilfreichen Community auf eine Antwort stoßen."

What do you think about this?

**Comment by MikeMcC399** [comment]
@larswmh 

The text (with integrated links) looks good to me. If you already have an English translation maybe you could post it, otherwise I will translate it to English.

@Ein-Tim 
Perhaps you could comment if the Twitter description is accurate since you are very active in the Twitter community?

**Comment by larswmh** [comment]
@MikeMcC399 my suggestion for the English translation:

Where can I find news on the Corona-Warn-App?

Information on new versions of the Corona-Warn-App is frequently published in the blog. Occasionally, information on various topics is published as well, such as recommendations on how to behave in the event of a red tile.
Additionally, news about the Corona-Warn-App are published on Twitter. Especially there, users have the opportunity to ask topic-related questions and will come across an answer among the helpful community.

**Comment by Ein-Tim** [comment]
> Perhaps you could comment if the Twitter description is accurate since you are very active in the Twitter community?

Yep, sounds good to me.

**Comment by MikeMcC399** [comment]
@larswmh / @Ein-Tim 
Thanks for your inputs and comments. I will submit a PR for this. I will change the English a bit to make it flow better. Also "news" is an uncountable noun, so "news is published", not "news are published" https://dictionary.cambridge.org/grammar/british-grammar/news.

**Comment by MikeMcC399** [comment]
- I have added the new FAQ article `#news` as PR #2682, which is now ready for review.

**Comment by MikeMcC399** [comment]
The following FAQ articles were published through PR #2682 to resolve this issue:

- https://www.coronawarn.app/en/faq/results/#news "Where can I find news on the Corona-Warn-App?"
- https://www.coronawarn.app/de/faq/results/#news "Wo kann ich Neuigkeiten über die Corona-Warn-App finden?"
