### ISSUE TITLE
Missing blog translations into English

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2683]
## Where to find the issue

- https://www.coronawarn.app/en/blog/2022-01-21-cwa-uhrzeit-rote-kachel/ "Warum zeigt die Corona-Warn-App bei einer roten Kachel die genaue Uhrzeit und den Ort der Begegnung nicht an?"

- https://www.coronawarn.app/en/blog/2022-01-11-cwa-omikron/ "Wird die CWA an die Omikron-Variante angepasst?"

- https://www.coronawarn.app/en/blog/2021-05-11-how-to-rapid-test-integration/ "Corona-Schnelltest per App: So funktioniert die Registrierung für dm, EcoCare und testbuchen.de/No-Q"

## Describe the issue

- https://www.coronawarn.app/en/blog/2022-01-21-cwa-uhrzeit-rote-kachel/ "Warum zeigt die Corona-Warn-App bei einer roten Kachel die genaue Uhrzeit und den Ort der Begegnung nicht an?"

"CWA Team, on January 21, 2022
English version coming soon"

- https://www.coronawarn.app/en/blog/2022-01-11-cwa-omikron/ "Wird die CWA an die Omikron-Variante angepasst?"

"CWA Team, on January 11, 2022
Aktualisiert am 21. Januar 2022 um 08:30 Uhr; English version coming soon"

- https://www.coronawarn.app/en/blog/2021-05-11-how-to-rapid-test-integration/ "Corona-Schnelltest per App: So funktioniert die Registrierung für dm, EcoCare und testbuchen.de/No-Q"

"Hanna Heine, on May 11, 2021
Currently, German version only."

---
The annotations about planned English-language versions of blog articles in German are out of date.

"soon" and "currently" implies a short time-frame, perhaps days or even a week or two. Three months and one year delay does not fit the text.

## Suggested change

For all blog articles available in German only, harmonize the annotation to say "German version only" without any hint or promise of a translation. The does not prevent a translation being published at some later date.

- https://www.coronawarn.app/en/blog/2022-01-21-cwa-uhrzeit-rote-kachel/ "Warum zeigt die Corona-Warn-App bei einer roten Kachel die genaue Uhrzeit und den Ort der Begegnung nicht an?"

- https://www.coronawarn.app/en/blog/2022-01-11-cwa-omikron/ "Wird die CWA an die Omikron-Variante angepasst?"

- https://www.coronawarn.app/en/blog/2021-05-11-how-to-rapid-test-integration/ "Corona-Schnelltest per App: So funktioniert die Registrierung für dm, EcoCare und testbuchen.de/No-Q"

**Comment by MikeMcC399** [comment]
If desired I will submit a PR to make the suggested blog changes.

**Comment by MikeMcC399** [comment]
A better solution would be to translate the German titles into English, remove the German text from the English blog and provide text to say that the article is available in German only and add a link to the German blog `/de/blog`. I could do this as well as an alternative.

**Comment by molarya1** [comment]
Hey @MikeMcC399 @dsarkar have we made any progress on this issue? If not, it would be great if I could get involved here and take charge - please do let me know!

**Comment by MikeMcC399** [comment]
@molarya1 
> have we made any progress on this issue? If not, it would be great if I could get involved here and take charge - please do let me know!

I am waiting for feedback from the Open Source Team about what they would like done. This is not an urgent issue however. I expect they will be busy with the next release when they get back to work after the Easter public holidays, so it could well take some time.

If the Open Source Team gives feedback then I would provide the PR, as I wrote previously in https://github.com/corona-warn-app/cwa-website/issues/2683#issuecomment-1088343020. You are welcome to get involved by providing feedback on the PR if I submit one, but I don't see the scope for you to take charge, since I am already handling it from the community side.

**Comment by molarya1** [comment]
> @molarya1
> 
> > have we made any progress on this issue? If not, it would be great if I could get involved here and take charge - please do let me know!
> 
> I am waiting for feedback from the Open Source Team about what they would like done. This is not an urgent issue however. I expect they will be busy with the next release when they get back to work after the Easter public holidays, so it could well take some time.
> 
> If the Open Source Team gives feedback then I would provide the PR, as I wrote previously in [#2683 (comment)](https://github.com/corona-warn-app/cwa-website/issues/2683#issuecomment-1088343020). You are welcome to get involved by providing feedback on the PR if I submit one, but I don't see the scope for you to take charge, since I am already handling it from the community side.

Gotcha, def makes sense - will be on standby and looking out for the PR to provide feedback once it's available!

**Comment by MikeMcC399** [comment]
@dsarkar 

Does the Open Source Team have any feedback on this issue? Just for example, from https://www.coronawarn.app/en/blog/2022-01-21-cwa-uhrzeit-rote-kachel/:

![image](https://user-images.githubusercontent.com/66998419/168769037-a5b07b84-3059-4857-ab6a-28a45cbde46f.png)

Is a translation really "coming soon" or has it been delayed or cancelled?

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for pinging me. Will check.

**Comment by MikeMcC399** [comment]
@dsarkar 

I can certainly submit a PR to change the text to "German version only".

What do you think about my suggestion from https://github.com/corona-warn-app/cwa-website/issues/2683#issuecomment-1088399694:

"A better solution would be to translate the German titles into English, remove the German text from the English blog and provide text to say that the article is available in German only and add a link to the German blog `/de/blog`."

Would this be OK, or do you just want the simple solution?

**Comment by dsarkar** [comment]
@MikeMcC399 Sure, let me check first with @HannaHei before changing this.

**Comment by MikeMcC399** [comment]
@dsarkar 

- I have first submitted PR #2899 for the simple text change. If the more comprehensive change is wished for, then I will do a second PR.

**Comment by MikeMcC399** [comment]
@dsarkar 
Good morning @dsarkar ! Thank you for merging PR #2899!

I will leave this issue open until I hear back from you, whether @HannaHei would like the other changes I proposed implemented (see https://github.com/corona-warn-app/cwa-website/issues/2683#issuecomment-1128889196).

**Comment by dsarkar** [comment]
@MikeMcC399 The other changes you are proposed are accepted! I understand that you will provide a PR, correct? Thanks!

**Comment by MikeMcC399** [comment]
@dsarkar 
> The other changes you are proposed are accepted! I understand that you will provide a PR, correct?

Thanks again for coordinating. Yes, I will supply a PR for this change.

**Comment by MikeMcC399** [comment]
- This issue is now resolved through a second PR #2902

**Comment by MikeMcC399** [comment]
There is another German-language article https://www.coronawarn.app/en/blog/2021-02-23-corona-warn-app-survey/ "Corona-Warn-App Survey" in the English-language blogs.

I missed converting this article, however since it is short, and the title is correct English I plan to leave it as it is.

- There is in any case an open issue https://github.com/corona-warn-app/cwa-website/issues/1877 on this blog article. Apart from the allocation of Internal Tracking ID: [EXPOSUREAPP-11551](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11551) there has not been any feedback about the issue raised.
