### ISSUE TITLE
New critical npm security vulnerabilities

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2685]
## Your Question

- Previous to PR https://github.com/corona-warn-app/cwa-website/pull/2504
`npm audit` output was
`35 vulnerabilities (1 low, 18 moderate, 16 high)`

- After merge of this PR
`npm audit` output is
`43 vulnerabilities (1 low, 18 moderate, 19 high, 5 critical)`

so 3 high and 5 critical vulnerabilities have been added.

Is this a concern or can it be ignored?

**Comment by svengabr** [comment]
We are currently working on many different tasks on the website. We will make sure to have a look at the vulnerabilities once all the merging is done. I'm expecting some more package.json changes soon.

**Comment by MikeMcC399** [comment]
@svengabr 

I'm glad to hear that you will be looking at this. I had got used to seeing the high vulnerabilities, but critical vulnerabilities took it up a notch! This also caused dependabot alerts to be triggered on my fork.

It seems that the problem is caused by the addition of
https://www.npmjs.com/package/gulp-modify-file v1.0.1 published 4 years ago which depends on 
https://www.npmjs.com/package/lodash 1.0.2 that seems to be about 9 years old.

Also https://www.npmjs.com/package/lodash.template called up by `gulp-modify-file` is triggering an alert.

You might want to look for alternatives to `gulp-modify-file`.

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/2754 should resolve this issue. It removes the dependency on `gulp-filelist` and `gulp-modify-file`.

**Comment by MikeMcC399** [comment]
`npm audit` now says:

`38 vulnerabilities (1 low, 18 moderate, 19 high)`

so the critical vulnerabilities have been removed and therefore this issue, which was about additional critical vulnerabilities, can be closed.
