### ISSUE TITLE
FAQ menu is cut off for no reason

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2690]
## Where to find the issue
- https://www.coronawarn.app/de/faq/results/
- https://www.coronawarn.app/en/faq/results/

## Describe the issue
The FAQ menu is sometimes cut off for no obvious reason: 
![Bildschirmfoto 2022-04-05 um 20 35 50](https://user-images.githubusercontent.com/67682506/161826670-2cf91a0b-65c0-42b5-8d4f-529f05766730.png)

## Stepps to reproduce
1. Access e.g. https://www.coronawarn.app/de/faq/results/#interoperability_countries via a dekstop browser
2. See that the menu is cut off although there is enough space on the bottom available

**Comment by Ein-Tim** [comment]
Confirm fixed with https://github.com/corona-warn-app/cwa-website/pull/2698.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Are you also seeing a horizontal scroll bar for the menu when you view https://www.coronawarn.app/de/faq/results/?

![image](https://user-images.githubusercontent.com/66998419/162003182-3cd5cab9-03c9-4301-9494-8734bbb8389e.png)

even when the browser window is very wide.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- I submitted https://github.com/corona-warn-app/cwa-website/issues/2701 for the horizontal scroll-bar issue. There is one long German word "Hintergrundaktualisierung" which caused this issue.
