### ISSUE TITLE
Incomplete sitemap published

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2694]
## Where to find the issue

- https://www.coronawarn.app/en/sitemap/index.html
- https://www.coronawarn.app/de/sitemap/index.html

## Describe the issue

The sitemap published to the production site contains almost no detail. Building locally with `npm run build` there is a lot more detail, however this command may need to be executed twice.

![image](https://user-images.githubusercontent.com/66998419/161922415-b63d1d65-101a-4d70-ac62-bb97a3aa3d78.png)

## Expected behaviour

The sitemap should show a lot of detail, like the following:

![image](https://user-images.githubusercontent.com/66998419/161922604-a7859bea-861f-4c11-9ea4-567bdbbfe6fa.png)

**Comment by MikeMcC399** [comment]
I also noticed that some of the titles used in the sitemap are a bit untidy, like the inconsistent use of space after the dash and writing terms together in English which should be separated. I'll open another issue about this.

**Comment by MikeMcC399** [comment]
@svengabr 

- The issue is also reproducible locally.

In local clone delete the generated file `cwa-website/src/data/sitemaplist.json`

Execute `npm start`
Open http://localhost:8000/en/sitemap/
Note incomplete Sitemap

Kill Browsersync session
Execute `npm start` again
Refresh page http://localhost:8000/en/sitemap/ with F5
Now full Sitemap is shown


- Presumably there is something wrong in the ordering of execution. I haven't looked more deeply into it though. Perhaps @ibexad from PR https://github.com/corona-warn-app/cwa-website/pull/2504 should be taking a look?

**Comment by svengabr** [comment]
@MikeMcC399 thanks for finding this issue. I will have a look into it!

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/2754 may fix this issue

**Comment by MikeMcC399** [comment]
The sitemap on

- https://www.coronawarn.app/en/sitemap/index.html and
- https://www.coronawarn.app/de/sitemap/index.html

now contains correct content.
