### ISSUE TITLE
FAQ suggests new country store availabilities may be added

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2711]
## Where to find the issue

- https://www.coronawarn.app/en/faq/results/#international "In which international app stores is the app available?"
- https://www.coronawarn.app/de/faq/results/#international "In welchen internationalen App Stores ist die App verfügbar?"

## Describe the issue

- https://www.coronawarn.app/en/faq/results/#international "In which international app stores is the app available?" contains the paragraph:

"More countries are currently being checked and will be released in the App Stores step by step. The Robert Koch Institute asks for your understanding that it cannot provide any information on specific countries and the status of their release during the ongoing review process."

- https://www.coronawarn.app/de/faq/results/#international "In welchen internationalen App Stores ist die App verfügbar?" contains the paragraph:

"Weitere Länder werden im Moment geprüft und schrittweise in den App Stores freigegeben. Das Robert Koch-Institut bittet um Verständnis, dass es während des laufenden Überprüfungsprozesses zu konkreten Ländern und dem Status ihrer Freigabe keine Auskunft erteilen kann."

---
The whole of the article is written as though the process of adding new countries is active and ongoing. In fact it seems that there is no longer any active process at RKI to add new countries. With the exception of the addition of Ukraine (see also blog https://www.coronawarn.app/en/blog/2022-03-30-cwa-2-20/ "CWA 2.20: Corona-Warn-App Available in Ukrainian Language"), the list has been stable and not been extended for a long time. 

## Suggested change

Review the complete wording and statements from RKI in the FAQ article listed above concerning the addition of new countries to the list of app store availability.

If there is currently no active process at RKI and no expectation by RKI that new countries will be added, then the text should be changed accordingly. It should be avoided that expectations be set through the FAQ article which are unlikely to be met.

---
Internal Tracking ID: [EXPOSUREAPP-12705](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12705)

**Comment by dsarkar** [comment]
Hi @MikeMcC399, I will check if we can change this text. Note, only recently the app is available in the Ukrainian stores.

**Comment by MikeMcC399** [comment]
@dsarkar 

Thank you for checking. I did actually mention Ukraine in the issue, however this is an exception, and I assume this is due to the refugee situation. If there are no plans for RKI to add other countries in the near future then it would be better to get the text changed.

**Comment by MikeMcC399** [comment]
- See PR #2713
