### ISSUE TITLE
Allow Cypress test suite to run on https://www.coronawarn.app without errors

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2714]
## Current Implementation

The [Cypress test suite](https://github.com/corona-warn-app/cwa-website/tree/master/cypress) for the [cwa-website](https://github.com/corona-warn-app/cwa-website/) is designed to run on a local pre-production instance of the web running on http://localhost:8000. See
https://github.com/corona-warn-app/cwa-website/blob/64d4f24367e85ca7091064e25a0fdf2975df6423/cypress.json#L2

It is possible to override the `baseUrl` parameter to request that the production web at https://www.coronawarn.app is tested, however one of the six tests fails, so the complete test is marked as unsuccessful.

Executing `npx cypress run -c baseUrl=https://www.coronawarn.app` from the locally cloned root directory of [cwa-website](https://github.com/corona-warn-app/cwa-website/) results in an error from the test [/cypress/integration/blog_spec.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/blog_spec.js). All the other tests run successfully.

```
       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ √  applink_spec.js                          00:02        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ×  blog_spec.js                             00:06        2        -        2        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  check_anchor_links.js                    00:16       37       37        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  check_links.js                           08:13       37       37        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  hotline_spec.js                          668ms        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ √  pages/eventRegistration.js               00:14        6        6        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ×  1 of 6 failed (17%)                      08:55       86       84        2        -        -
```

[/cypress/integration/blog_spec.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/blog_spec.js) has been written to test only on a local copy where a special test page `2099-01-01-visual-test-page` is manually added to the blog. This is done locally through the command `npm run test:prepare`. The test fails on the production web https://www.coronawarn.app because the visual test page is missing.

## Suggested Enhancement

It would not be appropriate to try to add `2099-01-01-visual-test-page` to the blog directory on the production web at https://www.coronawarn.app, so in order to get the test to run successfully on the production web the test would need to be modified.

Add logic to [/cypress/integration/blog_spec.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/blog_spec.js) so that it does not attempt to test `2099-01-01-visual-test-page` when running on https://www.coronawarn.app.

## Expected Benefits

The option to test the production web fully and receive a success message from the complete Cypress suite may be helpful to ensure that the publication process has worked correctly.

**Comment by MikeMcC399** [comment]
Implementation requires Cypress and JavaScript (JS) skills. I am not at this level, so I'm happy for anybody else to pick this up.

**Comment by MikeMcC399** [comment]
@dsarkar / @10delin 

- I was a little surprised by the "enhancement" in PR #2719 which commented out the use of `2099-01-01-visual-test-page` in the Cypress tests, whichever web instance is being tested. That was not what I had imagined as the solution.
- On reflection it seems that the test was introduced at the beginning of the project, when there was no blog content. In the meantime there is plenty of real blog content and there is no need for a special test page.
- From my point of view PR #2719 can be processed.
- In addition I would follow up with a separate PR submission to remove the `2099-01-01-visual-test-page` from other places.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for your feedback. I agree with you that we can use that "simple" solution provided by @10delin at this stage of the project.

**Comment by MikeMcC399** [comment]
- PR #2719 removes the dependency in [/cypress/integration/blog_spec.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/blog_spec.js) on the test blog  `2099-01-01-visual-test-page` 
- `$ npx cypress run -c baseUrl=https://www.coronawarn.app` now runs successfully to completion
- I will follow up with a new issue description to clean up
