### ISSUE TITLE
FAQ faded out topic list

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2733]
## Where to find the issue

https://www.coronawarn.app/en/faq/

## Describe the issue

https://www.coronawarn.app/en/faq/ in wide-screen mode shows sections and topics side-by-side. The list of topics fades out at the bottom without showing all topics.

This reduces the usefulness of this view when there is plenty of browser real-estate available and the user could scroll down if necessary.

## Steps to reproduce

Open https://www.coronawarn.app/en/faq/ in a web browser on a desktop using the full width of the screen
Notice that the list of topics is truncated.

App Features stops at "Check-in" which is faded out
Troubleshooting stops at "iOS" which is faded out

![image](https://user-images.githubusercontent.com/66998419/162765546-435949d4-2f11-4070-bfc1-84c9042bea9f.png)

## Suggested change

On the wide-screen view of https://www.coronawarn.app/en/faq/ do not fade-out topics. Show all topics and allow the user to scroll down if necessary.

**Comment by larswmh** [comment]
Good morning @MikeMcC399, this is working as intended and was agreed on with the stakeholders.

---
Corona-Warn-App Open Source Team

**Comment by larswmh** [comment]
@MikeMcC399 a PR has been opened adressing the different amount of topics listed below the sections, as topics should only be faded out once 6 are listed. Your suggestion to highlight these selected topics in the full list has been forwarded.

**Comment by dsarkar** [comment]
@MikeMcC399 Yes, the lengths of the lists should have been the same. We will have a look later how to improve the design by vertically aligning the lists.

**Comment by larswmh** [comment]
Good morning @MikeMcC399,
- PR #2741 added a sixth topic to the "App Features" section so that the number of hidden topics does not differ between sections
- PR #2808 fixed the vertical alignment of FAQ topics 

Would you like to close this issue or are there any other issues left that were not adressed?

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Good morning @larswmh 

I will close this enhancement request and re-submit with an updated description.
