### ISSUE TITLE
FAQ topic or individual URL not shown in address bar

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2735]
## Where to find the issue

https://www.coronawarn.app/en/faq/results/

## Describe the issue

If an FAQ topic is selected in the menu, the browser shows the topic but does not change the URL displayed in the address bar.

The same for a specific FAQ article.

- This follows on from a related issue https://github.com/corona-warn-app/cwa-website/issues/2668.

## Steps to reproduce

Open https://www.coronawarn.app/en/faq/results/ in a desktop browser using the full screen width
Note that the browser address bar shows the URL https://www.coronawarn.app/en/faq/results/
Click on any topic in the left-hand menu
Note that the topic is shown on the right-hand side
Note also that the contents of the browser address bar have not changed

## Expected behaviour

The contents of the address bar should reflect the FAQ contents currently being shown.

If, for instance, the user clicks on "Tests" in the menu list of https://www.coronawarn.app/en/faq/results/, then the browser address bar should show https://www.coronawarn.app/en/faq/results/#test corresponding to the FAQ contents being displayed.

If the user then clicks on "When do I receive my PCR test result in the app?" to display the contents of this FAQ, then the browser address bar should show https://www.coronawarn.app/en/faq/results/#result_time

If the user then clicks on "Expand/Collapse all" and then clicks on "Link to this answer" from the next FAQ, then the browser address bar should show https://www.coronawarn.app/en/faq/results/#QRcodes.

**Comment by Ein-Tim** [comment]
Closely related: 

If you access the FAQ page using a direct anchor link to e.g. https://www.coronawarn.app/en/faq/results/#result_time & then click on "Link to this answer" on any other FAQ entry, the URL is not updated. 

I will open an issue for this soon.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

You're probably right, but while you were writing I created #2736. Sorry, I will still leave it open to keep everything clean.

**Comment by MikeMcC399** [comment]
- This issue has been resolved by PR #2786 from @JoseRosso
