### ISSUE TITLE
"Link to this answer" does not work if FAQ page is accessed via anchor link or "Link to this answer" was used once before

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2736]
## Where to find the issue
- https://www.coronawarn.app/de/faq
- https://www.coronawarn.app/en/faq

## Describe the issue
If the FAQ page is accessed using an anchor link or the "Link to this answer" feature was used once before & the option "Link to this answer" is clicked on any FAQ entry, the URL in the address bar of the browser is not updated. So "Link to this answer" actually does nothing in this case. 

## Suggested change
Fix this issue.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Please check if you think this is now fixed.
