### ISSUE TITLE
Switzerland listed as active

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2737]
## Where to find the issue

https://www.coronawarn.app/en/faq/results/#interoperability_countries

## Describe the issue

In the FAQ article https://www.coronawarn.app/en/faq/results/#interoperability_countries it says:

"In order to also enable warnings between users of the Swiss coronavirus app and the Corona-Warn-App, the RKI also operates another exchange server together with Switzerland (Federal Office of Public Health of the Swiss Confederation)."

and further below it lists Switzerland as active since 24.03.2021

The Swiss "Bundesamt für Gesundheit BAG" https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/swisscovid-app-und-contact-tracing.html#1074592515 however says:

"**Temporary suspension**

Now that the isolation requirement has been lifted, the conditions for the effective continued operation of the SwissCovid app are no longer in place, at least temporarily. For this reason the Federal Council has decided to suspend the SwissCovid app for the time being. This is in line with the legal basis, which provides for the system to be deactivated if it is no longer needed to combat the pandemic. However, we continue to keep a close eye on the epidemiological situation and will resume operation of the SwissCovid app if it becomes necessary to do so. For this reason we will maintain the necessary IT infrastructures in the background."

There are further details in German under https://www.fedlex.admin.ch/eli/cc/2022/207/de

## Suggested change

Mark the SwissCovid app as temporarily suspended in the CWA FAQs. Although the connection between Switzerland and Germany may still be running, if the SwissCovid app is no longer active and no longer providing data, then the info in the FAQs should be changed in order not to mislead users who might think they would still get current exposure data from Switzerland.

---
Internal Tracking ID: [EXPOSUREAPP-12772](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12772)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for rising the issue. See PR #2739.

**Comment by MikeMcC399** [comment]
@dsarkar 

I saw in the app that Switzerland still shown in the overview and it is no longer shown in the detailed list of countries.

On Android, tap on "EXPOSURE LOGGING ACTIVE"
EU and Swiss flag are shown.

Tap on Transnational Exposure Logging and scroll down
There is no Swiss flag and no country name "Switzerland" in the list of countries.

That looks OK for the time-being anyway. If Switzerland declares a "Permanent suspension", then the display and text would need to be reviewed. At the moment they only declared "Temporary suspension".
