### ISSUE TITLE
Overlapping text on FAQ overview (DE)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2742]
## Where to find the issue

https://www.coronawarn.app/de/faq/

## Describe the issue

![image](https://user-images.githubusercontent.com/66998419/162962599-4d41d2fb-4658-4018-8adc-28c1a49dd873.png)

## Steps to reproduce

Open https://www.coronawarn.app/de/faq/ in web browser on desktop with wide screen.
Scroll down to "Themenbereiche"
Gradually reduce the width of the browser window and note that there are text overlaps.

## Suggested change

Add soft hyphens for long words

**Comment by MikeMcC399** [comment]
If you wish, I can submit a PR to tackle this issue.

**Comment by dsarkar** [comment]
@MikeMcC399 PR will be appreciated! Thanks!

**Comment by MikeMcC399** [comment]
@dsarkar 

- I have submitted PR #2744 to resolve this issue.
