### ISSUE TITLE
FAQ list of topics does not correctly link to the sections on mobile / small screen sizes

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2753]
## Where to find the issue
- https://www.coronawarn.app/de/faq/
- https://www.coronawarn.app/en/faq/

## Describe the issue
If I select a topic, the page does not scroll to the correct section. Here's a video which makes clear what the problem is: 

https://user-images.githubusercontent.com/67682506/163357772-024f6bc3-1557-4d0c-88c8-1e0b9f3a05f0.mp4

## Expected behavior
Only the topic chosen should be displayed and not the whole list.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Good catch!

Could you say which topic you tapped on? I couldn't see that from watching the video.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I tapped on "Positiver Test".

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Thanks. I can reproduce that in Google Chrome simulating a mobile device.

1. Open https://www.coronawarn.app/de/faq/
2. Scroll down to "Positiver Test" and tap it
3. Scroll down to results and note that list starts with "Was tun, wenn? / Rote Karte"

Expected:

The displayed list should start at "Positiver Test"

**Comment by Ein-Tim** [comment]
Issue resolved, closing.
