### ISSUE TITLE
Search in Glossary returns double count

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2760]
## Where to find the issue

https://www.coronawarn.app/en/faq/ Search

## Describe the issue

If an FAQ search term is found in a Glossary article in the title and in the text, then the search result shows 2 matches instead of 1 match in the breadcrumbs part.

This problem was mentioned by @svengabr in https://github.com/corona-warn-app/cwa-website/issues/2626#issuecomment-1084687029, also @Crystalskulls wrote in https://github.com/corona-warn-app/cwa-website/issues/2626#issuecomment-1084762548 that he would create an issue for that. I could not find a issue for this though.

## Steps to reproduce

1. Open https://www.coronawarn.app/en/faq/ in browser
2. Enter "community management" in search field (Type the word you are looking for)
3. Select "Glossary" in the search drop-down menu
4. Click "Search"
5. Note that one article (https://www.coronawarn.app/en/faq/results/#glossary_community_management) is found, however the breadcrumbs show "FAQ / Glossary / Search result: 2 results found"

OR

more simply, open https://www.coronawarn.app/en/faq/results/?search=community+management&topic=glossary in Google Chrome.

![Glossary search count](https://user-images.githubusercontent.com/66998419/163579410-0b32051d-98d6-4d5d-831b-70431d897285.jpg)

For comparison:
- search for "error report" (example with term only found in title) - result is 1 (correct)
- search for "malfunction" (example with term only found in Glossary article text) - result is 1 (correct)
- search for "EFGS" in "App Features" - result is 1 (correct)

## Expected behaviour

1. The count should correspond to the number of articles found containing the text. The title and the text should not be counted separately in the Glossary. The count should behave the same way as for sections other than the Glossary in the FAQ
2. The breadcrumbs search result count should agree with the count in the left-hand menu

**Comment by MikeMcC399** [comment]
- Thanks to @Crystalskulls for PR #2763!

This issue is now resolved. The result of https://www.coronawarn.app/en/faq/results/?search=community+management&topic=glossary is

![image](https://user-images.githubusercontent.com/66998419/163706226-872da711-bb9e-4339-81a0-f2a56d04dce8.png)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for feedback/checking!
