### ISSUE TITLE
Always take & deliver screenshots of all screens in the app, to avoid using screenshots of the wrong OS & out of date screenshots

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2761]
## Current implementation 

The screenshot delivery seems to essentially only add screenshots of screens which were added new to the app. It seems like it does not provide any updates to already existing screenshots, although they might be out of date or screenshots from the wrong OS were used, because screenshots from the correct OS are missing.

## Suggested enhancement

The process should be improved significantly:
1. Screenshots of all screens of the next version of the app should be taken 
2. The screenshots which were taken should be (automatically) compared to the screenshots displayed on https://www.coronawarn.app/en/screenshots.
3. If a change has been noticed, the updated screenshots should be included in the next screenshot delivery. 

**Newly taken screenshots which show exactly the same as screenshots which are already displayed on the screenshots page, should NOT be provided.**

## Problem and motivation
Currently, there are many issues with the screenshot page, see the table below:

| Link | Type of issue |
|---|---|
| https://www.coronawarn.app/en/screenshots/#ios_cards | Wrong OS |
| https://www.coronawarn.app/en/screenshots/#ios_journal | Out of date |
| https://www.coronawarn.app/en/screenshots/#ios_rat | Out of date |
| https://www.coronawarn.app/en/screenshots/#ios_booster_note | Out of date |
| https://www.coronawarn.app/en/screenshots/#android_cards | Wrong OS |
| https://www.coronawarn.app/en/screenshots/#android_journal | Out of date |
| https://www.coronawarn.app/en/screenshots/#android_check_in | Out of date | 
| https://www.coronawarn.app/en/screenshots/#android_rat | Out of date |
| https://www.coronawarn.app/en/screenshots/#android_certificates | Out of date |
| https://www.coronawarn.app/en/screenshots/#android_test_certificate | Out of date |
| https://www.coronawarn.app/en/screenshots/#android_vaccination_certificate | Out of date |
| https://www.coronawarn.app/en/screenshots/#android_check_validity_certificate | Wrong OS |
| https://www.coronawarn.app/en/screenshots/#android_invalid_certificate | Wrong OS |
| https://www.coronawarn.app/en/screenshots/#android_booster_note | Out of date |

**This list may be incomplete! This list does not include issues like missing screenshots or wrong screenshot order.**

**Comment by Ein-Tim** [comment]
@dsarkar / @larswmh / @svengabr 

Will you mirror this to JIRA and push it forward? If not, there should be a note added to the page that the screenshots do not necessarily reflect the actual implementation.

**Comment by MikeMcC399** [comment]
Please add the https://github.com/corona-warn-app/cwa-website/labels/screenshots label to this issue.

**Comment by Ein-Tim** [comment]
This issue has become obsolete as the team has been improving the process step by step with every release.
