### ISSUE TITLE
Remove `certificate_check` screenshots from screenshot page

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2762]
## Where to find the issue
- https://www.coronawarn.app/en/screenshots/#ios_certificate_check
- https://www.coronawarn.app/de/screenshots/#ios_certificate_check
- https://www.coronawarn.app/en/screenshots/#android_certificate_check
- https://www.coronawarn.app/de/screenshots/#android_certificate_check

## Describe the issue
The feature "Certificate check for bookings" is not in use at the moment, as there is no validation service provider. The feature is de facto on ice without any process expected in the next months.
Thus, the screenshots should be removed from the page. 

## Suggested change
Remove the screenshots from the page. 

## Additional information
PR follows tomorrow. 

---
Internal Tracking ID: [EXPOSUREAPP-12844](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12844)

**Comment by Ein-Tim** [comment]
PR #2764 provided.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks, PR approved and merged.

**Comment by Ein-Tim** [comment]
Closing as fixed via PR https://github.com/corona-warn-app/cwa-website/pull/2764.
