### ISSUE TITLE
Bad links to latest blog in sitemap

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2765]
## Where to find the issue

- https://www.coronawarn.app/en/sitemap/
- https://www.coronawarn.app/de/sitemap/

## Describe the issue

Each of the two sitemaps has one bad link, which is to the latest blog post for the 2.20 app version.

- https://www.coronawarn.app/en/sitemap/ links incorrectly to https://www.coronawarn.app/en/sitemap/de/blog/2022-03-30-cwa-2-20 for "CWA 2.20: Corona-Warn-App Available in Ukrainian Language"

- https://www.coronawarn.app/de/sitemap/ links incorrectly to https://www.coronawarn.app/de/sitemap/de/blog/2022-03-30-cwa-2-20 for "CWA 2.20: Corona-Warn-App jetzt auf Ukrainisch"

## Steps to reproduce

- Open https://www.coronawarn.app/en/sitemap/ and click on first blog link note 404 error.
- Open https://www.coronawarn.app/de/sitemap/ and click on first blog link note 404 error.

## Suggested change

Correct the links in

https://github.com/corona-warn-app/cwa-website/blob/8386a4debaea98573d3b0c5b0583b7821d1b015c/src/data/sitemap.json#L195-L196

`url` should start with `/en`

https://github.com/corona-warn-app/cwa-website/blob/8386a4debaea98573d3b0c5b0583b7821d1b015c/src/data/sitemap_de.json#L195-L196

`url` should start with `/de`

**Comment by MikeMcC399** [comment]
- PR #2766 corrects this issue.

**Comment by dsarkar** [comment]
@MikeMcC399 thanks for reporting this issue. PR approved.

**Comment by MikeMcC399** [comment]
This issue is confirmed resolved.

Tested with `npm run test:open`
select `check_links.js` to run this test.

The sitemap directories `/de/sitemap/` and `/en/sitemap/` show a green tick, which confirms a successful test.

![image](https://user-images.githubusercontent.com/66998419/163773758-b9defdc7-9b3f-4b30-9688-a971d222637c.png)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for confirming.
