### ISSUE TITLE
Typos in Event QR-Code form (EN)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2769]
## Where to find the issue

https://www.coronawarn.app/en/eventregistration/

## Describe the issue

For Event types on the Event QR-Code form in the English language version (https://www.coronawarn.app/en/eventregistration/) for the End Date and Time field labels there is:

1. a missing space after "Date"
2. a superfluous "t" at the end of the word "Time"

![Event registration typos](https://user-images.githubusercontent.com/66998419/163718485-10984ea3-0468-488f-8b3f-880f2520498e.jpg)

## Steps to reproduce

1. Open https://www.coronawarn.app/en/eventregistration/ in web browser
2. In the Place/Event drop-down, select one of the Event types, such as "Club activities"
4. Scroll down to the Start / End fields and note a formatting error and typo for the End date and time

## Suggested change

Modify the English language QR-Code form for the End Date and Time field labels to:

1. add a space after "Date"
2. remove the letter "t" at the end of the word "Time"

**Comment by MikeMcC399** [comment]
- PR #2770 submitted to resolve this issue.

**Comment by MikeMcC399** [comment]
## Verification

Open https://www.coronawarn.app/en/eventregistration/ in web browser
Select "Club activities"
View labels for End Date and Time

![image](https://user-images.githubusercontent.com/66998419/163774443-c34d3718-64e1-42c8-a03f-37ca9cb28590.png)

Execute the following
`npx cypress run -s cypress/integration/pages/eventRegistration.js -c baseUrl=https://coronawarn.app`
from the root directory of a cloned copy of the cwa-website repository
Check for 6 tests passing, 0 tests failing

```
       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ √  pages/eventRegistration.js               00:16        6        6        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    √  All specs passed!                        00:16        6        6        -        -        -

```

Tests passed, so now closing.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for verification!
