### ISSUE TITLE
FAQ wrong Risk Assessment content shown in wide browser

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2771]
## Where to find the issue

https://www.coronawarn.app/en/faq/ > App Features > Risk Assessment

## Describe the issue

Clicking "Risk Assessment" in the "App Features" column in a desktop web browser on the https://www.coronawarn.app/en/faq/ page causes "Risk Assessment" from "Technical Context" to be shown. This is the wrong "Risk Assessment" topic (right topic, wrong topic section).

The issue is not reproducible if the browser is narrow and the topics are listed top-to-bottom only, then the correct section is displayed.

## Steps to reproduce

1. Open https://www.coronawarn.app/en/faq/ in Google Chrome desktop web browser with wide screen
2. In "App Features" column, click on "Risk Assessment" (links to https://www.coronawarn.app/en/faq/results/?search=&topic=application#app_features_risk_assessment)
3. Note that "FAQ / Technical Context / Risk Assessment" is shown in the breadcrumbs

OR

1. Open https://www.coronawarn.app/en/faq/results/?search=&topic=application#app_features_risk_assessment in a desktop web browser
2. Note that "FAQ / Technical Context / Risk Assessment" is shown in the breadcrumbs
3. Compare to the result of opening https://www.coronawarn.app/en/faq/results/#app_features_risk_assessment
4. In this case "FAQ / App Features / Risk Assessment" is shown

## Expected behaviour

If "Risk Assessment" in "App Features" column is clicked in a desktop web browser on the https://www.coronawarn.app/en/faq/ page, then the topics from "App Features" should be shown, not the ones from "Technical Context".

The breadcrumb list should show "FAQ / App Features / Risk Assessment" not "FAQ / Technical Context / Risk Assessment" 

https://www.coronawarn.app/en/faq/results/#app_features_risk_assessment should be displayed, not
https://www.coronawarn.app/en/faq/results/#risk_assessment

## Additional information

The [FAQ_SEARCH_SUMMARY.md](https://github.com/corona-warn-app/cwa-website/blob/master/docs/FAQ_SEARCH_SUMMARY.md#url-parameters) document says:

"If, in addition to the search parameter, a hash (e.g., #ios_136) is part of the url to address one entry directly, the search parameter is ignored."

so the fact that https://www.coronawarn.app/en/faq/results/?search=&topic=application#app_features_risk_assessment does not open https://www.coronawarn.app/en/faq/results/#app_features_risk_assessment is also a regression from the previous FAQ search system.

**Comment by MikeMcC399** [comment]
Sorry. I don't have a solution for this issue.

**Comment by MikeMcC399** [comment]
This issue is also reproducible for "Certificates" which has entries in both the "App Features" and "Troubleshooting" sections.

Selecting "Certificates" in "App Features" displays instead "Certificates" in the "Troubleshooting" section. 🙁

**Comment by MikeMcC399** [comment]
- This issue has been resolved by #2786.

**Comment by dsarkar** [comment]
Thanks for reporting!
