### ISSUE TITLE
FAQ Certificates topics from wrong section shown for #eu_dcc

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2779]
## Where to find the issue

https://www.coronawarn.app/en/faq/results/#eu_dcc

## Describe the issue

Opening https://www.coronawarn.app/en/faq/results/#eu_dcc in a desktop wide browser displays the topics from "FAQ / Troubleshooting / Certificates" instead of the topics from "FAQ / App Features / Certificates"

## Steps to reproduce

1. Open https://www.coronawarn.app/en/faq/results/#eu_dcc in Google Chrome desktop wide browser
2. Note that "FAQ / Troubleshooting / Certificates" is shown

![FAQ Troubleshooting Certificates](https://user-images.githubusercontent.com/66998419/163962619-ccd2c010-c0a5-4f82-94d0-41f67a461222.jpg)

## Expected behaviour

Opening https://www.coronawarn.app/en/faq/results/#eu_dcc in a desktop wide browser should result in "FAQ / App Features / Certificates" being shown.

![FAQ App Features Certificates](https://user-images.githubusercontent.com/66998419/163962650-9f3ff567-e8fa-4748-919d-776dd460bcf2.jpg)

In https://www.coronawarn.app/en/faq/results/index.html 
```
<div id="eu_dcc" class="section-container">     
<h3 class="section-title">Certificates</h3>
```
is located inside
```
<h1 id="application" class="topic-title mb-4">App Features</h1>
```
so "App Features" should be shown, not 
```
<div id="support_certificates" class="section-container">     
<h3 class="section-title">Certificates</h3>
```
from
```
<h1 id="support" class="topic-title mb-4">Trouble&shy;shooting</h1>
```

## Related issues

- https://github.com/corona-warn-app/cwa-website/issues/2773
- https://github.com/corona-warn-app/cwa-website/issues/2771

**Comment by MikeMcC399** [comment]
The behaviour has now changed and the link https://www.coronawarn.app/en/faq/results/#eu_dcc does not open any certificate section.

**Comment by larswmh** [comment]
@MikeMcC399 from what I can see right now this is fixed, can you confirm?

**Comment by MikeMcC399** [comment]
@larswmh 

> from what I can see right now this is fixed, can you confirm?

Agreed. The issue is no longer reproducible.
