### ISSUE TITLE
Problem with FAQ entry `hc_prefix_invalid` / `hc_invalid_prefix` / redirects

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2792]
## Where to find the issue
- https://www.coronawarn.app/de/faq/#hc_prefix_invalid
- https://www.coronawarn.app/en/faq/#hc_prefix_invalid

## Describe the issue
The iOS app links to https://www.coronawarn.app/en/faq/#hc_prefix_invalid, which was deleted and a redirect was added to https://www.coronawarn.app/en/faq/results/#eu_dcc. This means, currently, users of the iOS app do not see any helpful information in the iOS app if there is an error with the certificate scanning.

Under Android @MikeMcC399 opened https://github.com/corona-warn-app/cwa-app-android/issues/5099. 

## Suggested change
There are two ways this issue could be fixed: Restore the old behavior of the FAQ or adapt the apps.

## Relaxed issues
- https://github.com/corona-warn-app/cwa-app-android/issues/5099
- https://github.com/corona-warn-app/cwa-app-ios/issues/4463

**Comment by Ein-Tim** [comment]
Corresponding iOS issue: https://github.com/corona-warn-app/cwa-app-ios/issues/4461

**Comment by Ein-Tim** [comment]
@dsarkar Are you fine with me providing a PR for this change?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Why do you think `#hc_invalid_prefix` has been deleted?

Are you having problems displaying https://www.coronawarn.app/en/faq/results/#hc_invalid_prefix ?

![image](https://user-images.githubusercontent.com/66998419/164066345-968a000e-5afa-4fa4-b3fe-7f5eaa538458.png)

(In any case #eu_dcc would be the wrong URL for troubleshooting.)

**Comment by Ein-Tim** [comment]
@MikeMcC399 Ah, the problem is a different one:

The iOS app links to https://www.coronawarn.app/de/faq/results/#hc_prefix_invalid, while the correct entry is https://www.coronawarn.app/en/faq/results/#hc_invalid_prefix.

So this is a problem which should be fixed on iOS side, I guess?

**Comment by Ein-Tim** [comment]
This is a problem in the iOS app and should be solved there.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I will take a look tomorrow. I'm not sure whether the app or the website needs changing. I would also look at the old web and find out whether the link was broken there.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks, I quickly looked at it myself. Using the `old-faq` of your fork of the cwa-website repository, I see that the anchor always was `hc_invalid_prefix` and not `hc_prefix_invalid`.

See:
https://github.com/MikeMcC399/cwa-website/blob/8a841ee08a3a76fd2b758f3fb36ff24da105a3ef/src/data/faq.json#L228

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I suggest you re-open this issue or open a new one.

The issue is not that `#hc_prefix_invalid` was deleted, but that there is a mismatch between the iOS / Android app links and the website. (Sorry I didn't notice that in my initial reply.)

My suggestion for resolution, since it affects both iOS and Android, would be to change the id of the FAQ article from `hc_invalid_prefix` to `hc_prefix_invalid` on the website which would match the internal error code `HC_PREFIX_INVALID`.

Then add an FAQ redirect from `hc_invalid_prefix` to `hc_prefix_invalid` just in case it has been bookmarked elsewhere.

That would require no change to the apps and would be quick to implement.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

No reason to apologize, we both missed the real reason why the link is not working first.

I will provide a PR as @MikeMcC399 suggest, if I get a GO from @dsarkar. 

Thanks for your help here and elsewhere Mike, appreciate it!

**Comment by Ein-Tim** [comment]
@dsarkar Could you let me know if the change @MikeMcC399 suggested would be approved? I'd like to provide a PR for this.

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Thanks for analysing this issue. PR will be appreciated very much and accepted!

**Comment by Ein-Tim** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/2796 created.

**Comment by MikeMcC399** [comment]
@dsarkar / @Ein-Tim 

- The change was introduced on Feb 1, 2022 with https://github.com/corona-warn-app/cwa-website/pull/2373

`hc_prefix_invalid` was renamed to `hc_invalid_prefix` 
and
`hc_prefix_invalid` was redirected to `eu_dcc` where it remains today

This needs to be reviewed in the context of the FAQ site reorganization, whether it is still the right construction.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The statement in the title of this issue is incorrect.
"FAQ entry hc_prefix_invalid deleted without redirect added"

https://github.com/corona-warn-app/cwa-website/blob/6af1b6b1ce70f9d705e7f79657a811ea0ff5d0ba/src/data/faq_redirects.json#L6

`hc_prefix_invalid` redirects to `eu_dcc`

**Comment by Ein-Tim** [comment]
This means the iOS app is currently linking to `eu_dcc` which seems to be the wrong place to link to if a certificate is already registered / a certificate is invalid, etc.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim I see: I remember why that was done. There is the inconsistency between Android and iOS, so we put the error message articles on top of the "certificated" eu_dcc section. In the meanwhile this got "lost" ...

**Comment by dsarkar** [comment]
![image](https://user-images.githubusercontent.com/1409741/164194585-b54d4049-401a-4ab9-9d8a-8291553a2b95.png)

**Comment by Ein-Tim** [comment]
Sorry, I don't understand this anymore and won't follow up on this anymore. I think the app code needs changing to fix this mess, but I don't think this should be done from the community.

Please close this issue if you want to open another one so that the real issue can be tracked in a clean issue. I'm closing my PR now.

**Comment by MikeMcC399** [comment]
@dsarkar 

You probably should review with the iOS and Android developers. Especially due to the split in the FAQs between App Features and Troubleshooting.

@Ein-Tim 

You and I may have made some incorrect analysis in these steps, but thanks to your efforts an overall issue has been identified. Well done for that! 👏🏻

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks to you both. I understand the best solution would be to adapt the link in the iOS app to be the same as in the Android app. Will try to push that forward.

**Comment by Ein-Tim** [comment]
Thank you very much @dsarkar. I created an issue in the iOS repo of this: https://github.com/corona-warn-app/cwa-app-ios/issues/4463

**Comment by MikeMcC399** [comment]
@dsarkar 

> I understand the best solution would be to adapt the link in the iOS app to be the same as in the Android app. Will try to push that forward.

- The link in the Android app `#eu_dcc` does not give the desired result. See issue https://github.com/corona-warn-app/cwa-app-android/issues/5099
- If your suggestion is to use `#hc_already_registered` in both iOS and Android, that would probably make sense.

**Comment by Ein-Tim** [comment]
@MikeMcC399 The problem is that the iOS app currently only has one link for all problems, so currently a link to https://www.coronawarn.app/en/faq/results/#support_certificates makes the most sense under iOS, for all errors OR my enhancement request https://github.com/corona-warn-app/cwa-app-ios/issues/4463 gets implemented and iOS is aligned to Android.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Thanks for pointing out the differences between iOS and Android! The developers will need to put their heads together if there is to be a common solution.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Do you think that a change is needed to the website? If not, then probably this issue should be closed. You already wrote in the header that this issue is out of date.

**Comment by Ein-Tim** [comment]
If this issue is closed, there is no other one open where this issue can be addressed. As I said in my comment above, I don't understand the situation anymore, so I can't follow up with another issue at the moment, sorry.
Maybe you could open a follow up issue in the documentation repository? Then I would close this one.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- For Android, I think the only issue is the one I described in https://github.com/corona-warn-app/cwa-app-android/issues/5099, however there has been no feedback on this issue and it is not mirrored to Jira, so I don't know what will happen to it.
- For iOS, you opened the issue https://github.com/corona-warn-app/cwa-app-ios/issues/4463

I don't know either what an additional issue would be, so I cannot describe one at this time.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I'm unsure how to proceed here. IMO it's really important that this get's fixed, and I only opened an enhancement request and no bug report. I would like to wait for feedback from @dsarkar here. I hope that's ok for you @MikeMcC399!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I need to wait for feedback on https://github.com/corona-warn-app/cwa-app-android/issues/5099 so I guess waiting is OK for now.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Okay, thanks! Enjoy your weekend!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Your title says "Problem with FAQ entry hc_prefix_invalid / hc_invalid-prefix / redirects"

- #hc_prefix_invalid redirects to #eu_dcc

- `hc_invalid-prefix` seems to be a typo and probably `hc_invalid_prefix` is intended

- #hc_invalid_prefix is not a redirect. It is the direct anchor of an article "Error 'HC_PREFIX_INVALID'"

 I am still unclear how you want to handle this issue and what exactly you think the issue is.

- There has been no concrete feedback on https://github.com/corona-warn-app/cwa-app-android/issues/5099

**Comment by Ein-Tim** [comment]
@MikeMcC399 

The current problem I see: The iOS app links to https://www.coronawarn.app/en/faq/#hc_prefix_invalid, which was deleted and a redirect was added to https://www.coronawarn.app/en/faq/results/#eu_dcc. This means, currently, users of the iOS app do not see any helpful information in the iOS app if there is an error with the certificate scanning.

Under Android you should know the problem, as you opened https://github.com/corona-warn-app/cwa-app-android/issues/5099. 

There are two ways this issue could be fixed: Restore the old behavior of the FAQ or adapt the apps.

I left this issue open for visibility reasons. If you think I should close this issue, let me know (:

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- I suggest you copy your text to the top of this issue (First and third paragraph) so it is clear what problem you see and what you expect could be done
- You could also correct the typo in the title "hc_invalid-prefix" => "hc_invalid_prefix"
- and leave the issue open

**Comment by Ein-Tim** [comment]
Will do so @MikeMcC399! Thanks & have a nice weekend!

**Comment by Ein-Tim** [comment]
This issue was never addressed, and I also don't expect it to be addressed anymore, as the CWA project went into ramp-down mode. I'm therefore closing this issue now.
