### ISSUE TITLE
FAQ Outdated information about EU project

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2797]
## Where to find the issue

https://www.coronawarn.app/en/faq/results/#vac_cert_eu "Why has no joint EU-wide project been called out for proposal for a certificate?"

## Describe the issue

The FAQ article https://www.coronawarn.app/en/faq/results/#vac_cert_eu "Why has no joint EU-wide project been called out for proposal for a certificate?" is outdated, irrelevant and misleading to users at this stage. EU certificates have been implemented and are in wide use since July 2021. Support for the certificates was introduced into CWA with versions 2.3 - 2.5 during June and July 2021.

![EU project](https://user-images.githubusercontent.com/66998419/164212681-a70bcabd-5152-464f-b6e0-809484a5b3e8.jpg)

The article is in a prominent place at the **top** of the section App Features > Certificates https://www.coronawarn.app/en/faq/results/#eu_dcc which detracts from useful information in this topic list.

![Certificates topic list](https://user-images.githubusercontent.com/66998419/164212785-30868cb8-797c-4386-8606-85c8e5d7f701.jpg)

## Suggested change

1. Remove the FAQ article https://www.coronawarn.app/en/faq/results/#vac_cert_eu "Why has no joint EU-wide project been called out for proposal for a certificate?"

2. Redirect https://www.coronawarn.app/en/faq/results/#vac_cert_eu "Why has no joint EU-wide project been called out for proposal for a certificate?" to https://www.coronawarn.app/en/faq/results/#eu_dcc_which "Which EU certificates are supported?". The latter article includes a link to https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en which provides detailed information about EU certificates.

![EU certificates](https://user-images.githubusercontent.com/66998419/164212826-d066ddd3-7a40-40fb-8faa-e1ce3304324f.jpg)

The suggested change applies to English and German FAQs correspondingly.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks, will rise that topic internally.

**Comment by MikeMcC399** [comment]
@dsarkar 

Thanks for getting this discussed internally!

I raised this issue mainly because it was at the top of the list. I thought about suggesting to move it to the bottom, but I think that removing it completely would be better.

(By the way raise and rise are easily confused - see https://dictionary.cambridge.org/grammar/british-grammar/raise-or-rise. For issues it is always raise. Hope you don't mind me mentioning that for the future!)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for you comment, and of course, regarding your last sentence, I don't mind, on the contrary, I appreciate it!

**Comment by dsarkar** [comment]
@MikeMcC399 PR with your suggested changes will be accepted.

**Comment by Ein-Tim** [comment]
> [...] I think that removing it completely would be better.

Btw, I agree on this. Removing it makes most sense.

Have a good night everyone!

**Comment by MikeMcC399** [comment]
@dsarkar 
> PR with your suggested changes will be accepted.

Good morning! and thank you for coordinating the pre-approval of the suggestion.

- I have submitted PR #2799 with the changes.

**Comment by MikeMcC399** [comment]
- This issue is resolved by PR #2799
