### ISSUE TITLE
Spikes in iOS daily download numbers

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2801]
The graphs of daily downloads for iOS show spikes with days which have very high numbers and these are 3 or 4 times the daily average.

Are these correct numbers or is there an artefact in these iOS daily download numbers making them incorrect? There are no spikes in the corresponding Android daily download numbers.

https://www.coronawarn.app/en/analysis/ select "Last 6 months" and "Daily", then view Downloads graph.

For iOS showing 7-day moving average and daily count:
![image](https://user-images.githubusercontent.com/66998419/164423063-f08d1658-4515-4e53-9524-991bf9bed87e.png)

For Android showing 7-day moving average and daily count:

![image](https://user-images.githubusercontent.com/66998419/164423496-a8acc90d-04a3-420a-9a6f-940eaf2742ad.png)

Comparing iOS and Android 7-day moving averages, the iOS numbers look distorted, although both are following similar trends:

![image](https://user-images.githubusercontent.com/66998419/164424418-bdd73651-2da0-4426-9521-b3dc7bca4330.png)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the question, will forward it. Stand by, please.

**Comment by MikeMcC399** [comment]
There was another lower spike lately in the iOS download figures for June 1 and June 2, 2022. It's hard to know if the download figures are correct without some sort of explanation of the spikes that only occur on iOS download figures, not on Android download figures.

**Comment by MikeMcC399** [comment]
@dsarkar 
> Stand by, please.

Still waiting for meaningful feedback.

June 29, 2022 iOS download 107 130.
Compare to previous normal day 5 645 downloads of CWA iOS app. The spike is around 20 times higher than the average daily figure.

I do not trust the iOS download figures to be accurate with these unexplained spikes. Perhaps iOS is counting downloads where the user is updating the app? CWA 2.24 was released on June 29, 2022. I always assumed that download numbers are **new** users not ones downloading a updated version. Maybe this is an incorrect assumption?

**Comment by larswmh** [comment]
@MikeMcC399 

Thank you for your patience on this issue. 

From insights within App Store Connect (Apple's counterpart to Google Play Console), we were able to identify these unusually high download spikes as so-called "Institutional Purchases". 
"Institutional Purchases" are app downloads by "Apple Business Manager" / "Apple School Manager", which is a service that offers business or educational institutions to download apps for volume distribution. (you can read more about it [here](https://developer.apple.com/support/volume-purchase-and-custom-apps/))

With this in mind, we're now confident that this is not an error, but businesses / educational institutions providing our app to their devices.

**Comment by MikeMcC399** [comment]
@larswmh 

Thanks to you and your colleagues for searching the unusual download spikes in iOS. Since you say that you are confident that the data is correct I will now close the issue.
