### ISSUE TITLE
Outdated instructions for Prioritized Background Activity

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2812]
## Where to find the issue

- https://www.coronawarn.app/en/faq/results/#battery_optimization_background "[Google/Android]: Battery optimization is not automatically disabled after activating the prioritized background activity"
- https://www.coronawarn.app/de/faq/results/#battery_optimization_background "[Google/Android]: Batterieoptimierung wird nicht automatisch abgeschaltet nachdem die priorisierte Hintergrundaktivität aktiviert wurde"
- https://www.coronawarn.app/en/faq/results/#no_risk_update "[Google/Android]: My risk status hasn't been updated for over a day. An internet connection was available, what's wrong?"
- https://www.coronawarn.app/de/faq/results/#no_risk_update "[Google/Android]: Mein Risikostatus wurde seit über einem Tag nicht mehr aktualisiert. Internet war aber verfügbar, was läuft hier falsch?"

## Describe the issue

Since CWA Android 1.6.0 it is not possible to set Prioritized Background Activity in the app (see https://github.com/corona-warn-app/cwa-app-android/issues/1606#issuecomment-744571331).

CWA 1.5 | CWA 1.6 and later
--- | ---
![Prioritized Background Activity 1 5 1](https://user-images.githubusercontent.com/66998419/165034684-40abfee7-e5ca-45e9-a3d2-222e98e96fe5.jpg) |  ![Prioritized Background Activity 1 6 1](https://user-images.githubusercontent.com/66998419/165034703-604b2d57-d365-4d2d-8f66-db87f4624b08.jpg)

https://www.coronawarn.app/en/faq/results/#battery_optimization_background implies that switching on the prioritized background activity on Android devices is done directly in CWA.

https://www.coronawarn.app/en/faq/results/#no_risk_update includes two paragraphs which seem out of date:

"In the power-saving settings of your phone, you can make sure that there's an exception set for the Corona-Warn-App:

Unfortunately, in some phones, you might not be able to activate the prioritized background activity in the app settings. You can still activate the prioritized background activity: You do so directly in the energy saving settings. of your phone. Set an exception for the Corona-Warn-App. If this still doesn't update the risk status automatically in the background, please create a comment in GitHub issue 933, giving your phone type and the installed versions of the app and of the COVID-19 exposure notifications."

Since CWA 1.6 the prioritized background activity is not activated in the app settings, so how can the above still apply? The detailed instructions earlier in the article should be sufficient.

## Suggested change

1. ~~For `#battery_optimization_background` add comment that starting from CWA 1.6 Prioritized Background Activity is set directly in the operating system and no longer in the app. Refer to `#no_risk_update` for detailed instructions.~~

2. ~~Move `#battery_optimization_background` to `#resolved` section above `#huawei_honor` since this is the most closely related article.~~

3. For `#no_risk_update` remove the two outdated paragraphs referring to problems activating the prioritized background activity in the app settings.

- Edit: Suggestions 1 and 2 are obsolete due to PR https://github.com/corona-warn-app/cwa-website/pull/1085.

---
Internal Tracking ID: [EXPOSUREAPP-14431](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14431)

**Comment by MikeMcC399** [comment]
Before I do the work to submit PRs for this issue I would welcome feedback if my assessment is correct. It seems strange that the FAQs have been apparently out of date for such a long time with no comment about it.

To keep PRs clearer I would submit one PR for #battery_optimization_background and another one for #no_risk_update.

**Comment by MikeMcC399** [comment]
- This is related also to the issue https://github.com/corona-warn-app/cwa-app-android/issues/2683

**Comment by larswmh** [comment]
If I'm understanding this correctly, the only remaining problem is with the two paragraphs in `#no_risk_update`. `#battery_optimization_background` was previously deleted and now redirects to `#no_risk_update`.  

After double checking with a team member, we've came to the conclusion that those two paragraphs you mentioned can be deleted.
Are you still interested in working on this, or would you like us to submit a PR for this?

**Comment by MikeMcC399** [comment]
@larswmh

- You are right. PR https://github.com/corona-warn-app/cwa-website/pull/1085 resolved part of this issue. I have updated the original posting accordingly.

- I will submit a PR to delete the two outdated paragraphs.
