### ISSUE TITLE
GitHub label "Fix xx.x" does not render in Markdown issues / PRs

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2820]
The GitHub function [Reference labels in Markdown](https://github.blog/changelog/2022-02-03-reference-labels-in-markdown/) does not work for labels containing `.` like https://github.com/corona-warn-app/cwa-website/labels/Fix%202.22 although it does work fine for other labels like https://github.com/corona-warn-app/cwa-website/labels/mirrored-to-jira when these URLs are used in the Markdown text of an issue or a PR.

There are two workarounds:

1) when using a URL for a label containing a `.` convert this character into `%2E` for example `https://github.com/corona-warn-app/cwa-website/labels/Fix%202%2E22` renders correctly as https://github.com/corona-warn-app/cwa-website/labels/Fix%202%2E22
2) rename each of the labels using `.` and replace this character with `-`. (This is not a good workaround however, because it would break any links using the first workaround.)

Perhaps the Open Source Team could consider raising this as a support issue with GitHub? Since I have only a free-of-charge account on GitHub I am not entitled to support, although I did bring up the topic in the GitHub Community https://github.community/t/markdown-rendering-labels-containing-period/247409.

This issue affects all of the [corona-warn-app](https://github.com/corona-warn-app) repositories using version labels. I'm only posting here though.

**Comment by dsarkar** [comment]
@MikeMcC399 ok, thanks for reporting and providing a solution.

**Comment by MikeMcC399** [comment]
@dsarkar 

- I have described this issue now in https://github.com/github/feedback/discussions/15742#discussion-4040910. Perhaps there will be some feedback there from the GitHub people.

**Comment by MikeMcC399** [comment]
Since I have reported this issue to GitHub Feedback (see above), I will close the issue here and leave it to the GitHub team to decide if any action will be taken.

I created a demo issue https://github.com/MikeMcC399/label-test/issues/2 and some text description in https://github.com/MikeMcC399/label-test.
