### ISSUE TITLE
Is the website only down for me?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2822]
I somehow can't reach https://coronawarn.app currently. Is it only down for me?

**Comment by Ein-Tim** [comment]
UptimeRobot also detects this issue: https://stats.uptimerobot.com/gKg1ZCqKJv

**Comment by Ein-Tim** [comment]
That's the issue I receive on my iPhone: 
<img src="https://user-images.githubusercontent.com/67682506/165746737-0b622059-0a1b-4583-950a-59532a979190.png" width="300">

**Comment by Ein-Tim** [comment]
Now it works again, UptimeRobot also shows the page as UP again. 

@dsarkar / @thomasaugsten was there an incident? Was the main server CWA contacts for DKs also affected?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Was the main server CWA contacts for DKs also affected?

The page https://stats.uptimerobot.com/gKg1ZCqKJv shows no incidents and 100.00% availability over the last 90 days for "Main Server (svc90.main.px.t-online.de)" with details on https://stats.uptimerobot.com/gKg1ZCqKJv/790438384

so, no.

**Comment by Ein-Tim** [comment]
Thanks @MikeMcC399, you're right.


Closing this issue.

**Comment by thomasaugsten** [comment]
There was an unexpected long downtime for a maintenance update.
