### ISSUE TITLE
Infinite loop using bookmarked search (414 Request-URI Too Large)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2837]
## Where to find the issue

https://www.coronawarn.app/de/faq/?search=luca#check_in_luca (quoted in auto-reply to the e-mail address [CoronaWarnApp@rki.de](mailto:CoronaWarnApp@rki.de)).

## Describe the issue

When using the bookmarked link https://www.coronawarn.app/de/faq/?search=luca#check_in_luca the web goes into an infinite loop, displays no results and the URL shown in the address bar contains multiple instances of the string `/results`, for instance:

https://www.coronawarn.app/de/faq/?search=lucaresults/results/results/results/results/results/results/results/results/results/results/results/results/results/results/results/#check_in_luca (interrupted)

## Steps to reproduce

In Google Chrome paste https://www.coronawarn.app/de/faq/?search=luca#check_in_luca into address bar and press enter

After waiting some time as the URL gets longer and longer, it finally fails with the error message:

`414 Request-URI Too Large`

## Expected behaviour

1. No infinite loop
2. Adherence to https://github.com/corona-warn-app/cwa-website/blob/master/docs/FAQ_SEARCH_SUMMARY.md#url-parameters<br><br>"_If, in addition to the search parameter, a hash (e.g., #ios_136) is part of the url to address one entry directly, the search parameter is ignored._"<br><br>thus the URL https://www.coronawarn.app/de/faq/?search=luca#check_in_luca should be resolved to https://www.coronawarn.app/de/faq/#check_in_luca and this in turn to https://www.coronawarn.app/de/faq/results/#check_in_luca

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reporting. We will have a look at this.

**Comment by MikeMcC399** [comment]
- This issue should be resolved by PR #2846

**Comment by MikeMcC399** [comment]
The infinite loop issue does not occur, however currently https://www.coronawarn.app/de/faq/?search=luca#check_in_luca does not show the right page.

- See also issue #2861
