### ISSUE TITLE
`rat-partner` page needs updating to reflect registration stop

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2856]
## Where to find the issue
- https://www.coronawarn.app/en/rat-partner/
- https://www.coronawarn.app/de/rat-partner/

## Describe the issue
The `rat-partner` was not updated to reflect that new testing stations can't register anymore to get connected to the CWA system. 

## Suggested change
Update the page, e.g. with the same note also published on https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki.

---
Internal Tracking ID: [EXPOSUREAPP-13019](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13019)

**Comment by Ein-Tim** [comment]
With https://github.com/corona-warn-app/cwa-map-public-frontend/releases/tag/v1.3.2 everything reg. becoming a RAT partner has been removed from the RAT testing stations map.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> with the same not also published on 

Did you mean "note" instead of "not"?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, thanks for spotting this typo!

**Comment by Ein-Tim** [comment]
- This has been addressed with PR https://github.com/corona-warn-app/cwa-website/pull/2889

I'm closing this issue now.
