### ISSUE TITLE
Legacy FAQ links stopped working

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2868]
## Where to find the issue

https://www.coronawarn.app/en/faq/

## Describe the issue

FAQ Links using the legacy format `https://www.coronawarn.app/en/faq/#FAQ_article_anchor` no longer open the article `https://www.coronawarn.app/en/faq/results/#FAQ_article_anchor`

## Steps to reproduce

Try to open https://www.coronawarn.app/en/faq/#where_can_i_get_tested in a webbrowser

Note that the article is not opened. Instead the page https://www.coronawarn.app/en/faq/ is presented.

## Suggested change

Check whether the updated deployment is responsible for this issue.

**Comment by MikeMcC399** [comment]
Since the FAQ links used in CWA make use of legacy format, this means that the app links to the FAQ do not currently work.

See
https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/values/links.xml for an example Android file specifying external links.

**Comment by dsarkar** [comment]
@MikeMcC399 Fixed.
