### ISSUE TITLE
Website menu can't be opened

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2869]
## Where to find the issue

- www.coronawarn.app

## Describe the issue

On my iPhone XR with the latest version of iOS, I can't get the menu to open. Regardless where I click ok the symbol, it does not open. 

## Suggested change
Fix the issue.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

It seems this is one of several problems caused by the changed deployment. See also https://github.com/corona-warn-app/cwa-website/issues/2861#issuecomment-1122543585.

**Comment by Ein-Tim** [comment]
I'm closing this issue in favour of #2870.
