### ISSUE TITLE
Suggest to update Cypress to version 9.6.1

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2900]
## Suggestion

Upgrade Cypress from version 7.7.0 to version 9.6.1 to take advantage of bug fixes and added functionality.

Version 7.7.0 was released on July 7, 2021<br>
Version 9.6.1 is currently the latest version, which was released on May 9, 2022

See [Cypress Changelog](https://docs.cypress.io/guides/references/changelog) for full details of bug fixes and functional enhancements.

PR https://github.com/corona-warn-app/cwa-website/pull/2067 (merged on Nov 29, 2021) already prepared the scripts `cypress:run:chrome` and `cypress:run:firefox` to run in `headed` mode explicitly, required for the migration from Cypress 7 to Cypress 8:
https://github.com/corona-warn-app/cwa-website/blob/f158245917ab1ac0bed8d0f676774fd0206223fa/package.json#L12-L13 No additional migration tasks are necessary. See also [Cypress Migration Guide](https://docs.cypress.io/guides/references/migration-guide) for reference.

## Installation

```bash
npm ci
npm install cypress@9 --save-dev
```

Also execute:

`npx browserslist@latest --update-db`

### Standalone test

Execute:

```bash
npx cypress open
```
causes the Cypress test runner to open. It should show Version 9.6.1 at the bottom right. Close the test runner.

### Integrated tests

The following command tests the web using Google Chrome:
`npm run test:chrome`

The next command tests the web using Mozilla Firefox:
`npm run test:firefox`

The above commands should run without errors.

## Impact / Risk

Since Cypress is not part of the [build](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) and [deploy](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/deploy-master.yml) workflow, this is a low-risk update.

Web contributors can execute `npm ci` to update their local copy of Cypress. If Cypress is not immediately updated locally there is no impact because there are no other incompatibilities introduced. The scripts in [package.json](https://github.com/corona-warn-app/cwa-website/blob/master/package.json) are upwards and downwards compatible.

**Comment by MikeMcC399** [comment]
I have this change prepared and tested. Please let me know if the Open Source Team will accept a PR to update Cypress to 9.6.1.

**Comment by dsarkar** [comment]
Hi @MikeMcC399, thanks for opening this issue. Yes, PR will be appreciated.

**Comment by MikeMcC399** [comment]
@dsarkar

Thanks for your confirmation!

- I submitted PR #2901.
