### ISSUE TITLE
Add FAQ entry reg. what to do when the user is getting the "Überprüfen Sie die Gültigkeit Ihrer Zertifikate." notification

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2903]
## Where to find the issue

n/a

## Describe the issue

There are many users on Twitter asking for what to do when they get the soon expiring notification for their certificates. The problem is not that the app shows that the certificate is expiring soon, but that the user does not know what the app means with "Gültigkeit ihrer Zertifikate". See https://twitter.com/fimedien/status/1527240307540123649?s=21&t=5ZyLNMDh7-BsnKm1DUcu0A, https://twitter.com/micwim/status/1527174192344584192?s=21&t=5ZyLNMDh7-BsnKm1DUcu0A & https://twitter.com/silkezie/status/1527165089933148160?s=21&t=5ZyLNMDh7-BsnKm1DUcu0A.

## Suggested change
Add a FAQ entry: "Ich bekomme eine Nachricht, die Gültigkeit meiner Zertifikate zu überprüfen. Was bedeutet das?"

## Additional information 
I will (for sure) help the currently affected users on Twitter, however, I guess this question will arise more often in the next time, so it definitely makes sense to add a FAQ entry.
I could provide a PR, but I think this should be done by the team.

---
Internal Tracking ID: [EXPOSUREAPP-12829](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12829)

**Comment by dsarkar** [comment]
@Ein-Tim Stand by, we are preparing a FAQ. Thanks.

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/2904

**Comment by MikeMcC399** [comment]
https://www.coronawarn.app/en/faq/results/#dcc_replacement_howto says:

![image](https://user-images.githubusercontent.com/66998419/169870596-71e5cc55-5ae6-47b9-8dde-03826823e97e.png)

so I guess the current advice is to wait (for CWA 2.23, which is not explicitly named).

**Comment by Ein-Tim** [comment]
Closing as implemented, see @MikeMcC399's comment above.
