### ISSUE TITLE
Extend Cypress testing to coronawarn.app links used by CWA app

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2909]
## Feature description

Add testing to the Cypress suite in https://github.com/corona-warn-app/cwa-website/tree/master/cypress/integration to cover the links to https://coronawarn.app which are used by the CWA Android and iOS apps.

### Problem

1. In March 2022 PR https://github.com/corona-warn-app/cwa-website/pull/2434 implemented a redesign of the CWA FAQs on https://www.coronawarn.app/en/faq/ and https://www.coronawarn.app/de/faq/.
2. The redesign caused access from embedded links in the CWA on mobile devices to fail to display the requested FAQ article. Either the article was not displayed at all or it was not displayed expanded. See issue https://github.com/corona-warn-app/cwa-website/issues/2577.
3. The Cypress test suite, run using `npm test`, did not identify these issues prior to Move-To-Production.

The underlying issues have been fixed, however there is still no Cypress test available which would have flagged these issues.

- This is related to the suggestion https://github.com/corona-warn-app/cwa-website/issues/2585 which was more concerned with the FAQ display on a mobile device. It did not consider other links used by the app.

### Motivation

Running the Cypress test suite should give a high level of confidence that the website performs as needed and should provide good information to avoid publishing content which breaks the interface between CWA on the mobile device and content on https://coronawarn.app.

---
Internal Tracking ID: [EXPOSUREAPP-13210](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13210)

**Comment by MikeMcC399** [comment]
Does it make sense to add this Cypress test functionality now? On the Android side I can only see [release/2.23.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.23.x) as upcoming version. I can't see any 2.24.x or 3.0 so I don't know if there are going to be any more changes after the release of 2.23.

If there will be more changes on the app side and on the web site that would benefit from having a test in place, then it would be worthwhile to add a test.

I do have a new Cypress test prepared which does this test. I only want to submit it as a PR if it really adds value at this stage of the project. Do let me have feedback!

**Comment by larswmh** [comment]
Thanks for your enhancement request @MikeMcC399. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13210](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13210)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@svengabr 

- Since you are planning to put effort into adding a Cypress workflow (see https://github.com/corona-warn-app/cwa-website/issues/2892), please take a look at the suggestion here to add tests for links on the website which are used in the app. I can submit a PR to implement it if you are interested.

**Comment by MikeMcC399** [comment]
@svengabr 

> sure you can add it if you like, much appreciated! 

Thanks! I will do that soon.

> I am focusing on the part of adding the new workflow YAML and testing everything locally using ACT https://github.com/nektos/act

I not familiar with ACT, but that definitely sounds like it is worth looking at! Thanks for sharing.

I have a couple of suggestions about the implementation of this enhancement as I was already experimenting with how to do it:

1. Exclude `check_links.js` from the tests, since this test is flaky and takes a very long time to run. I would move it to a separate folder, so it is easier to exclude using the `--spec` switch.
2. Since the check is not going to be a regular CI check on incoming commits, it would be easiest just to run cypress against the production instance of the server i.e. `--config baseUrl=https://coronawarn.app`. You don't need to build the web and fire up a test server in that case.

**Comment by MikeMcC399** [comment]
- PR #2935 is submitted

**Comment by MikeMcC399** [comment]
- PR #2935 flows into PR #2949 to implement this suggestion.
