### ISSUE TITLE
Release 2.24 Updates

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#2924]
- [x] Screenshots
https://github.com/corona-warn-app/cwa-website/pull/2944
- [x]  Gulpfile iOS and Android 2.24.0
- [x] Sitemap
- [x] Update FAQ/Glossary articles
- [x] Blog

---
**Release 2.24**
 Blog
  - DE https://www.coronawarn.app/de/blog/2022-06-xx-cwa-2-24/
  - EN https://www.coronawarn.app/en/blog/2022-06-xx-cwa-2-24/
- #2944
  - DE https://www.coronawarn.app/de/screenshots/ 
  - EN  https://www.coronawarn.app/en/screenshots/
- FAQ
  - https://github.com/corona-warn-app/cwa-website/pull/2983
    - DE: https://www.coronawarn.app/de/faq/results/#eu_dcc_export_error
    - EN: https://www.coronawarn.app/en/faq/results/#eu_dcc_export_error
  - https://github.com/corona-warn-app/cwa-website/pull/2961
    - DE: https://www.coronawarn.app/de/faq/results/#eu_dcc_export
    - EN: https://www.coronawarn.app/en/faq/results/#eu_dcc_export
- Privacy notice (no update)
  - DE https://www.coronawarn.app/de/privacy/
  - EN https://www.coronawarn.app/en/privacy/ 

---
**Other new or updated content (Unrelated to 2.24)**

- #1085 
  - DE [#battery_optimization_background](https://www.coronawarn.app/de/faq/results/#battery_optimization_background)
  - EN [#battery_optimization_background](https://www.coronawarn.app/en/faq/results/#battery_optimization_background)
- #2940 
  - DE [Blog](https://www.coronawarn.app/de/blog/2022-06-01-cwa-2-23/)
  - EN [Blog](https://www.coronawarn.app/en/blog/2022-06-01-cwa-2-23/)
- #2941 
  - DE [check_in_qr_warning_procedure](https://www.coronawarn.app/de/faq/results/#check_in_qr_warning_procedure)[check_in_qr_warning_how](https://www.coronawarn.app/de/faq/results/#check_in_qr_warning_how) [in_a_nutshell](https://www.coronawarn.app/de/faq/results/#in_a_nutshell)
- #2942 
  - DE [iOS](https://www.coronawarn.app/de/screenshots/#ios_certificate_reissuance) [Android](https://www.coronawarn.app/de/screenshots/#android_certificate_reissuance) | [Zertifikate drucken](https://www.coronawarn.app/de/screenshots/#android_print_certificate) 
  - EN [iOS](https://www.coronawarn.app/en/screenshots/#ios_certificate_reissuance) [Android](https://www.coronawarn.app/en/screenshots/#android_certificate_reissuance)
- #2946 
  - DE [android_certificate_reissuance](https://www.coronawarn.app/de/screenshots/#android_certificate_reissuance)
  - EN [android_certificate_reissuance](https://www.coronawarn.app/en/screenshots/#android_certificate_reissuance)
- #2948 
  - DE [iOS: Risiko-Karten](https://www.coronawarn.app/de/screenshots/#ios_cards)
  - EN [iOS: Risk Cards](https://www.coronawarn.app/en/screenshots/#ios_cards)
- #2949 
- #2950 
- #2954 
  - DE [#dcc_replacement_issues](https://www.coronawarn.app/de/faq/results/#dcc_replacement_issues)
  - EN [#dcc_replacement_issues](https://www.coronawarn.app/en/faq/results/#dcc_replacement_issues)
- #2956 
  - DE [#dcc_replacement_issues](https://www.coronawarn.app/de/faq/results/#dcc_replacement_issues)
  - EN [#dcc_replacement_issues](https://www.coronawarn.app/en/faq/results/#dcc_replacement_issues)
- #2964 
  - DE [Dashboard](https://www.coronawarn.app/de/analysis/)
  - EN [Dashboard](https://www.coronawarn.app/en/analysis/)
- #2971 
  - DE [#dcc_replacement_issues](https://www.coronawarn.app/de/faq/results/#dcc_replacement_issues)
  - EN [#dcc_replacement_issues](https://www.coronawarn.app/en/faq/results/#dcc_replacement_issues)
- #2972 
  - DE [#glossary_pcr_test](https://www.coronawarn.app/de/faq/results/#glossary_pcr_test)
  - EN [#glossary_pcr_test](https://www.coronawarn.app/en/faq/results/#glossary_pcr_test)
- #2973
- #2979 
  - DE [#rat_tan_hotline](https://www.coronawarn.app/de/faq/results/#rat_tan_hotline)
  - EN [#rat_tan_hotline](https://www.coronawarn.app/en/faq/results/#rat_tan_hotline)
- #2982
  - DE [#interoperability_countries](https://www.coronawarn.app/de/faq/results/#interoperability_countries)
  - EN [#interoperability_countries](https://www.coronawarn.app/en/faq/results/#interoperability_countries)
- #2984 
  - DE [#voluntary_self_quarantine](https://www.coronawarn.app/de/faq/results/#voluntary_self_quarantine) | [#vac_cert_red_warning](https://www.coronawarn.app/de/faq/results/#vac_cert_red_warning)
  - EN [#voluntary_self_quarantine](https://www.coronawarn.app/en/faq/results/#voluntary_self_quarantine) | [#vac_cert_red_warning](https://www.coronawarn.app/en/faq/results/#vac_cert_red_warning)

Internal Tracking ID: [EXPOSUREAPP-13270](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13270)

**Comment by MikeMcC399** [comment]
@larswmh 
I suggest to add:

- https://www.coronawarn.app/en/faq/#eu_dcc_export_error
- https://www.coronawarn.app/de/faq/#eu_dcc_export_error

to this issue list. 

- The new articles are added via PR #2983.
