### ISSUE TITLE
Certificate reissue screenshots for Android problems

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2943]
## Where to find the issue

- https://www.coronawarn.app/en/screenshots/#android_certificate_reissuance
- https://www.coronawarn.app/de/screenshots/#android_certificate_reissuance

## Describe the issue

https://www.coronawarn.app/assets/screenshots/2-23/en/android/DccReissuanceConsentFragment_1.png

1. There is a mixture of English and German text
2. There are two 2 of 2 vaccination certificates with almost the same date

https://www.coronawarn.app/assets/screenshots/2-23/de/android/DccReissuanceConsentFragment_1.png

1. There are two 2 of 2 vaccination certificates with almost the same date

## Suggested change

1. English screenshot should only have English text
2. Instead of 2 vaccination certificates there should be one vaccination certificate on one certificate of recovery, like for iOS

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks, we will have a look at this.
