### ISSUE TITLE
Please rebase release/2.24

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2957]
Could you please open a draft PR to collect the changes for the 2.24 release and rebase the https://github.com/corona-warn-app/cwa-website/tree/release/2.24 branch?

There is a new app link which I would like to add to the Cypress test `app_to_web.js`:

`<string name="certificate_export_all_error_dialog_faq_link">"https://www.coronawarn.app/en/faq/#eu_dcc_export_error"</string>`

however the `app_to_web.js` test is not included in [release/2.24](https://github.com/corona-warn-app/cwa-website/tree/release/2.24) yet, so I can't easily submit a PR for the necessary changes.

The FAQ article https://www.coronawarn.app/en/faq/#eu_dcc_export_error does not yet exist, so any PR to update the test data needs to go into the `release/2.24 branch` and not the `master` branch otherwise it would cause the test to fail.

**Comment by larswmh** [comment]
Good morning @MikeMcC399,

I have opened a draft pull request for the [release/2.24](https://github.com/corona-warn-app/cwa-website/tree/release/2.24) branch in #2959.

**Comment by MikeMcC399** [comment]
Good morning @larswmh!

- Thank you very much for rebasing. I have submitted https://github.com/corona-warn-app/cwa-website/pull/2960 now.
