### ISSUE TITLE
Add #eu_dcc_export_error FAQ EN & DE articles

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2958]
## Where to find the issue

FAQs and Cypress test

## Describe the issue

The following links are being added to the CWA 2.24 app:

- https://www.coronawarn.app/en/faq/#eu_dcc_export_error
- https://www.coronawarn.app/de/faq/#eu_dcc_export_error

1. The articles do not exist (yet)
2. The Cypress test [cypress/integration/app_to_web.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/app_to_web.js) does not test for the new links

## Suggested change

1. Add the articles
2. Modify the test data [cypress/fixtures/appToWebLinks.json](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/fixtures/appToWebLinks.json) to add the new anchor `#eu_dcc_export_error`

## Background information

- The links were added to CWA Android [release/2.24.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.24.x) through PR https://github.com/corona-warn-app/cwa-app-android/pull/5271 and are included in [v2.24.0-rc.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.24.0-rc.1) and later builds.

- For CWA iOS PR https://github.com/corona-warn-app/cwa-app-ios/pull/4619 adds the link.

---
Internal Tracking ID: [EXPOSUREAPP-13399](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13399)

**Comment by MikeMcC399** [comment]
I will submit a PR to update the test data [cypress/fixtures/appToWebLinks.json](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/fixtures/appToWebLinks.json) to add the new anchor `#eu_dcc_export_error`.

- To do that, I need an updated release/2.24 branch (see https://github.com/corona-warn-app/cwa-website/issues/2957).

- I assume that the Open Source Team will provide the article text for `#eu_dcc_export_error`.

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/2960 is submitted

Waiting for the articles now.

**Comment by dsarkar** [comment]
DRAFT R 2.24 FAQ #eu_dcc_export_error

**DE** Titel: Fehlermeldung 'Druckversion anzeigen nicht möglich'

Body:

Sie erhalten die Fehlermeldung 'Druckversion anzeigen nicht möglich' bei dem Versuch alle Zertifikate zu exportieren, wenn nur folgende Digitalen COVID Zertifikate der EU in der Corona-Warn-App abgelegt sind:
-	Testzertifikate, die älter als 72 h sind
-	gesperrte Zertifikate.

Testzertifikate, die älter als 72 h sind, haben keinen praktischen Nutzen mehr. Sollte es sich in Ihrem Fall um ein oder mehrere gesperrte Zertifikate handeln, wenden Sie sich bitte an den Austeller des/der Zertifikate(s).

Siehe auch :
https://www.coronawarn.app/de/faq/results/#eu_dcc_export 
Wie erstelle ich einen Ausdruck meines Digitalen COVID Zertifikates der EU?

---

**EN** Titel: Error 'Cannot display print version'

Body:

You will receive the error message 'Cannot display print version' when trying to export all certificates if only the following Digital COVID certificates of the EU are stored in the Corona-Warn-App:
- test certificates that are older than 72 h
- revoked certificates.

Test certificates older than 72 h have no practical use anymore. If your case involves one or more blocked certificates, please contact the issuer of the certificate(s).

See also:
How do I create a printout of my EU Digital COVID Certificate?
https://www.coronawarn.app/en/faq/results/#eu_dcc_export

**Comment by Ein-Tim** [comment]
@dsarkar AFAIK only for certificates which were issued in Germany a print version can be displayed. This should also be mentioned.

**Comment by Ein-Tim** [comment]
@dsarkar 

Shall I ask why this makes sense or do we just accept this?

**Comment by dsarkar** [comment]
@Ein-Tim I'd suggest the latter ;-)

**Comment by MikeMcC399** [comment]
@dsarkar 

---
Austeller => Aussteller 

---
"Digital COVID certificates of the EU" is a literal translation of the German term "Digitalen COVID Zertifikate der EU", however in English we are using the term "EU Digital COVID Certificate" see https://www.coronawarn.app/en/faq/results/#glossary_dcc

**Comment by dsarkar** [comment]
Corresponding sentence added https://github.com/corona-warn-app/cwa-website/issues/2958#issuecomment-1161912531. Also more specific wich route was taken to export, i.e. "all DCCs" or "single, selected DCC".

**Comment by MikeMcC399** [comment]
@dsarkar 

Will you convert your text from https://github.com/corona-warn-app/cwa-website/issues/2958#issuecomment-1161912531 into a PR now?

**Comment by larswmh** [comment]
@MikeMcC399

> @dsarkar
> 
> Will you convert your text from [#2958 (comment)](https://github.com/corona-warn-app/cwa-website/issues/2958#issuecomment-1161912531) into a PR now?

This is currently being worked on and the PR should be opened soon

**Comment by MikeMcC399** [comment]
The following PRs resolve the points raised in this issue pending release of CWA 2.24:

- PR https://github.com/corona-warn-app/cwa-website/pull/2983
- PR https://github.com/corona-warn-app/cwa-website/pull/2960

This issue is resolved:

- Closing in favour of umbrella issue https://github.com/corona-warn-app/cwa-website/issues/2924
