### ISSUE TITLE
Dashboard info heading overlaps cancel box

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2966]
## Where to find the issue

- https://www.coronawarn.app/en/analysis/
"Warnings received by data donors"

- https://www.coronawarn.app/de/analysis/
"Von Datenspendenden empfangene Warnungen"

## Describe the issue

The heading of "Warnings received by data donors" (EN) and "Von Datenspendenden empfangene Warnungen" can overlap the cancel box at certain browser window widths.

## Steps to reproduce

1. Open https://www.coronawarn.app/en/analysis/ in Google Chrome on a wide desktop
2. Click on the Information icon "i" of the graph "Warnings received by data donors"
3. Gradually reduce the width of the browser and notice that at a certain width the title text and the box containing the X for cancel overlap.

![image](https://user-images.githubusercontent.com/66998419/174341649-1c58e4ff-a33f-44a9-9f81-f56556808c4a.png)

This is more noticeable for the equivalent German text "Von Datenspendenden empfangene Warnungen" which can even overlap at full browser width.

The issue is also reproducible with Mozilla Firefox.

## Expected behaviour

The heading text should not overlap with the cancel box.

---
Internal Tracking ID: [EXPOSUREAPP-13402](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13402)

**Comment by brifemu** [comment]
@MikeMcC399 FYI #2975
