### ISSUE TITLE
Terms for rapid tests in TAN hotline article

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2978]
## Where to find the issue

- https://www.coronawarn.app/en/faq/results/#rat_tan_hotline "Can I share my positive rapid antigen test or PCR rapid test result via the TAN hotline?"

- https://www.coronawarn.app/de/faq/results/#rat_tan_hotline "Kann ich mein positives Schnelltest- oder PCR-Schnelltest-Ergebnis über die TAN-Hotline teilen?"

## Describe the issue

The terms for the two types of rapid test (antigen and PCR) used in the above FAQ articles regarding the TAN hotline are not used consistently. The article terms are also not linked to the glossary entries.

## Suggested change

Make the terms consistent and link them to the glossary entries:

- https://www.coronawarn.app/en/faq/results/#glossary_rapid_antigen_test "Rapid Antigen Test"
- https://www.coronawarn.app/en/faq/results/#glossary_rapid_pcr_test "Rapid PCR Test"
- https://www.coronawarn.app/de/faq/results/#glossary_rapid_antigen_test "Antigen-Schnelltest"
- https://www.coronawarn.app/de/faq/results/#glossary_rapid_pcr_test "PCR-Schnelltest"

**Comment by thorbenkuro** [comment]
@MikeMcC399 Thank you for reporting the issue and providing a PR!
