### ISSUE TITLE
Cypress migration to 10.2?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2980]
I noticed that the latest version of Cypress (10.2) includes support for M1: see [Cypress 10.2.0: Run tests up to 2x faster on Apple silicon (M1)](https://cypress-io.ghost.io/blog/2022/06/21/cypress-10-2-0-run-tests-up-to-2x-faster-on-apple-silicon-m1/). 

I don't use that environment myself, but it could be helpful for others.

I will take a look at the impact and report back here.

Is there any interest in migrating or should we leave the version at the current 9.6.1?

**Comment by MikeMcC399** [comment]
At this time Cypress 10.x.x may not be stable enough to want to migrate to it unless there is a strong need. Nevertheless I wanted to share the results below. It would be possible to migrate from 9.6.1 to 10.2.0 and the existing test specs all work after migration.

## Issue

[cwa-website](https://github.com/corona-warn-app/cwa-website) is currently configured to use Cypress version 9.6.1. This version does not support the Apple M1 ARM architecture natively and requires Rosetta to run. (See blog [Running Cypress on the Apple M1 ARM Architecture using Rosetta 2](https://www.cypress.io/blog/2021/01/20/running-cypress-on-the-apple-m1-silicon-arm-architecture-using-rosetta-2/)).

Cypress 10.2.0 introduces M1 support and alleviates this issue. See blog [Cypress 10.2.0: Run tests up to 2x faster on Apple silicon (M1)](https://cypress-io.ghost.io/blog/2022/06/21/cypress-10-2-0-run-tests-up-to-2x-faster-on-apple-silicon-m1/)

## Possible change

Update [cwa-website](https://github.com/corona-warn-app/cwa-website) to Cypress 10.2.0.

See [Cypress Changelog](https://docs.cypress.io/guides/references/changelog).

## Impact

Cypress 10 introduces breaking changes due to the new functionality of component testing which is added alongside the existing end-to-end testing (e2e). For instance, new folders are introduced, so that the existing `cypress/integration` folder is migrated to `cypress/e2e`. Also test specs are renamed: `app_to_web.js` becomes `app_to_web.cy.js`. See the [Cypress Migration Guide](https://docs.cypress.io/guides/references/migration-guide) for more detail.

In Cypress 10 the "Run all specs" is no longer available in the UI. Only individual tests can be run from the UI. To run all tests the CLI needs to be used. See [Discussion: 'Run all specs' removal in Cypress 10](https://github.com/cypress-io/cypress/discussions/21628).

## Migration Steps

Close or merge any existing PRs relating to Cypress tests otherwise these PRs will become stranded and will not work as intended if merged without modification after the Cypress version is migrated.

### Install Cypress 10

1.  `npm install -D cypress@latest` (installs cypress@10.2.0 - see [Changelog](https://docs.cypress.io/guides/references/changelog))
2.  `npx cypress open`
3.  Click "Continue to Cypress 10"

### Migration tool

In the migration tool which automatically starts in the Cypress test runner:
1. Click "Rename these specs for me"
2. Click "Rename the support file for me"
3. Click "Migrate the configuration for me"
   
- "E2E Testing" is now marked as "Configured"
- "Component Testing" is left as "Not Configured"

4. Close Cypress test runner window

### Post installation

1. Edit [.github/workflows/cypress-test-prod.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/cypress-test-prod.yml) and change cypress spec folder from `integration` to `e2e` i.e. `spec: cypress/e2e/*.js`
2. Modify the `cypress:open` script in [package.json](https://github.com/corona-warn-app/cwa-website/blob/master/package.json) to use `e2e` and browser Chrome i.e. `"cypress:open": "cypress open --e2e --browser chrome"`
3. Update [README.md](https://github.com/corona-warn-app/cwa-website/blob/master/README.md) regarding change of folder and removal of all tests option in `open` command.

## Verification

Execute the following and check that all tests pass:
```
npm run test:chrome
npm run test:firefox
npm run test
npx cypress run -s 'cypress/e2e/*.js' -c baseUrl=https://coronawarn.app --headless --browser chrome
```

Execute
`npm run test:open`
and check that the list of e2e test specs is shown immediately and the default browser is Chrome.
Select and run one of the tests listed, such as `mime.cy.js`.

Test on:
- Windows 11
- Ubuntu 20.04
- macOS

**Comment by MikeMcC399** [comment]
I suggest to close this issue unless there is a current need to migrate to Cypress 10.2.0.

**Comment by Ein-Tim** [comment]
I would benefit from adding native support for Apple Silicon in Cypress as I'm using an Apple M1 chip.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> I would benefit from adding native support for Apple Silicon in Cypress as I'm using an Apple M1 chip.

- Thank you for your input! See the new enhancement request: https://github.com/corona-warn-app/cwa-website/issues/3100
