### ISSUE TITLE
2.24 Android Screenshots show removed renewal text

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2988]
## Where to find the issue

- https://www.coronawarn.app/assets/screenshots/2-24/en/android/TestCertificateDetailsFragment__2.png
- https://www.coronawarn.app/assets/screenshots/2-24/de/android/TestCertificateDetailsFragment__2.png
- https://www.coronawarn.app/assets/screenshots/2-24/en/android/RecoveryCertificateDetailsFragment_recovered_2.png
- https://www.coronawarn.app/assets/screenshots/2-24/de/android/RecoveryCertificateDetailsFragment_recovered_2.png

## Describe the issue

The text "Please make sure to get a new digital certificate in time" (EN) or "Bitte bemühen Sie sich rechtzeitig darum, einen neuen digitalen Nachweis ausstellen zu lassen." (DE) has been removed in CWA 2.24 however there are screenshots published for the 2.24 release which still show this text.

- See PR https://github.com/corona-warn-app/cwa-app-android/pull/5282 and issue https://github.com/corona-warn-app/cwa-documentation/issues/899

## Suggested change

Replace the screenshots with correct ones taken from CWA 2.24 Android.

**Comment by larswmh** [comment]
@MikeMcC399 thanks for opening this issue. With the abovementioned PR, this has been fixed.
