### ISSUE TITLE
Wrong label for "Melden" on map portal in FAQ #test_result_issues

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2995]
### Articles

- https://www.coronawarn.app/en/faq/results/#test_result_issues "What can I do if I have not received my test result or test certificate?"

- https://www.coronawarn.app/de/faq/results/#test_result_issues "Was kann ich tun, wenn ich mein Testergebnis oder Testzertifikat nicht erhalten habe?"

### Image

- https://www.coronawarn.app/assets/img/faq/schnelltestportal_issue_fig1.png

## Describe the issue

1. The above FAQ articles say that "Fehler melden" should be clicked on, however the button on https://map.schnelltestportal.de/ for reporting an issue is now labelled "Melden".
2. The screenshot https://www.coronawarn.app/assets/img/faq/schnelltestportal_issue_fig1.png shows "Fehler melden" instead of "Melden"

FAQ screenshot:
![image](https://user-images.githubusercontent.com/66998419/177045791-45e671ab-488b-470f-9cd0-78932589455a.png)

Screenshot from https://map.schnelltestportal.de/:
![image](https://user-images.githubusercontent.com/66998419/177046028-c8e36aca-eb2c-4c1b-863d-df0f3afef6a1.png)

## Suggested change

1. Change the text in `#test_result_issues` from "Fehler melden" to "Melden".
2. Replace the screenshot [src/assets/img/faq/schnelltestportal_issue_fig1.png](https://github.com/corona-warn-app/cwa-website/blob/master/src/assets/img/faq/schnelltestportal_issue_fig1.png) Fig 1 / Abb 1 with an image showing "Melden" instead of "Fehler melden"

## Background information

https://github.com/corona-warn-app/cwa-map-public-frontend/commit/67123cadb683854d4748598126a3fd496f77643a from Dec 8, 2021 changed the text on the button from "Fehler melden" to "Melden".

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.
