### ISSUE TITLE
Missing relationship attributes on external links

### ISSUE THREAD

**Issue by larswmh** [corona-warn-app/cwa-website#3031]
## Where to find the issue

FAQ

## Problem and suggested change

This issue was brought up by @MikeMcC399 in recently submitted PR [#3030](https://github.com/corona-warn-app/cwa-website/pull/3030#issuecomment-1185457029)

There has never been a written policy here about external links but for consistency `rel='noopener noreferrer'` would need to be added to ensure security for external links, such as

`<a href='https://tools.rki.de/PLZTool/en-GB' target='_blank'>Robert Koch Institute Tool: Health authority by postal code or place</a>`

---
Internal Tracking ID: [EXPOSUREAPP-13638](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13638)

**Comment by MikeMcC399** [comment]
@larswmh 

I researched this some time ago, but didn't share the results. It seems like a good time now.

1. If the attributes are needed, should both `'noopener noreferrer'` be specified or is `'noopener'` enough? 
    - https://mathiasbynens.github.io/rel-noopener/ (See Recommendations)
    - https://stackoverflow.com/questions/57628890/why-people-use-rel-noopener-noreferrer-instead-of-just-rel-noreferrer.
2. Is `rel='noopener'` / `rel='noopener noreferrer'` needed on all types of external links or only ones which use `target='_blank'`?
    - https://web.dev/external-anchors-use-rel-noopener/

It would be good to define a standard for the cwa-website for future work.

**Comment by MikeMcC399** [comment]
Is this still necessary? It seems that these recommendations came about due to security issues in old browsers. Perhaps it can now be assumed that these browsers are no longer in use? This is a question for the security experts!

**Comment by svengabr** [comment]
Let's keep `'noopener noreferrer'` for all external links. This would in my opinion be the best idea since not everyone uses modern browsers.

**Comment by MikeMcC399** [comment]
@svengabr 

> Let's keep 'noopener noreferrer' for all external links. 

Thank you for providing this guideline! Perhaps this could be added as a guideline for reference to the documentation e.g. to [docs/CHANGE_WEBSITE_CONTENT.md](https://github.com/corona-warn-app/cwa-website/blob/master/docs/CHANGE_WEBSITE_CONTENT.md).

It might also be worth setting up a Cypress test to check for this convention.

**Comment by MikeMcC399** [comment]
@larswmh 

Will you implement this change? It seems like you are quite good with Regex 🙂 !

**Comment by MikeMcC399** [comment]
- In addition to PR #3032 from @larswmh I submitted some tweaks to links in PR #3033.
