### ISSUE TITLE
Document FAQ link attribute conventions

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3034]
## Where to find the issue

[Website Content Change](https://github.com/corona-warn-app/cwa-website/blob/master/docs/CHANGE_WEBSITE_CONTENT.md) document.

## Describe the issue

The recently introduced FAQ link conventions for `target` and `rel` HTML attributes are not described in the cwa-website reference documentation.

@larswmh wrote in https://github.com/corona-warn-app/cwa-website/pull/3030#issue-1305917705

"With this PR, any link in the FAQ opens up in a new tab."

@svengabr wrote in https://github.com/corona-warn-app/cwa-website/issues/3031#issuecomment-1185530636

"Let's keep 'noopener noreferrer' for all external links. This would in my opinion be the best idea since not everyone uses modern browsers."

## Suggestion

Add the following section at the bottom of the document 
[Website Content Change](https://github.com/corona-warn-app/cwa-website/blob/master/docs/CHANGE_WEBSITE_CONTENT.md) document:

---

`## Links on FAQ pages`

The following conventions should be followed for links in the FAQ sources [/src/data/faq.json](https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq.json) and [/src/data/faq_de.json](https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq_de.json):

- All internal and external links on the FAQ pages should use the HTML hyperlink attribute `target='_blank'` to open in a new frame. This provides a consistent user experience and works around an issue with the back arrow button in the FAQ Glossary.
- External links should use the HTML hyperlink attribute `rel='noopener noreferrer'` to avoid a cross-domain security issue in older browsers when the link also contains `target='_blank'`.
- Internal links should **not** contain the attribute `rel='noopener noreferrer'`. There is no security issue for internal links.

Examples:

- External link: `<a href='https://www.digitaler-impfnachweis-app.de/en/covpasscheck-app/' target='_blank' rel='noopener noreferrer'>Check EU COVID certificates directly via app</a>`
- Internal link: `<a href='#test_cert' target='_blank'>Test Certificate</a>`

---
Internal Tracking ID: [EXPOSUREAPP-13653](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13653)

**Comment by MikeMcC399** [comment]
This is a suggestion for a documentation addition to assist contributors to the FAQs.

If there is agreement about this, then I would submit a PR to add the text above.

**Comment by larswmh** [comment]
@MikeMcC399 thanks for opening this issue. We think your suggested text is good and would appreciate if you submitted a PR for it.
Internal Tracking ID: [EXPOSUREAPP-13653](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13653)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@larswmh 

- Thank you for the agreement about the text! I have submitted PR #3035 with the additional text for the [Website Content Change](https://github.com/corona-warn-app/cwa-website/blob/master/docs/CHANGE_WEBSITE_CONTENT.md) document.

**Comment by MikeMcC399** [comment]
- This suggestion is implemented through PR #3035.
