### ISSUE TITLE
RKI's and CWA's screenshots about "Check-In" are out of date...

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-website#3036]
## Where to find the issue
... on RKI's website:
["**Corona-Warn-App: Erstellen eines QR-Codes zur Eventregistrierung**" / "Creation of a QR code for event registration"](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Event-QR-Code.html); see downloadable PDF from 04/28/2021.

## Describe the issue
The Screenshots under “Are you planning an event?” / “**Check-In**” to create an QR-Code are out of date under RKI's website (see above).

Please refer:
[Take a Look (Version 2.14) Android - "**Check In**"](https://www.coronawarn.app/en/screenshots/#android_check_in)  _or_
[Take a Look (Version 2.14) iOS - "**Check In - Scan QR-Code**"](https://www.coronawarn.app/en/screenshots/#ios_check_in) / [Take a Look (Version 2.14) iOS - "**Check In - Create QR-Code**"](https://www.coronawarn.app/de/screenshots/#ios_check_in_create_event).

Cross References:

_1_. [[CWA vs. Luca]: Promotion of the CWAs "Check-in" functionality ...](https://github.com/corona-warn-app/cwa-wishlist/issues/690#issue-1059341487).
_2_. [Add CWA logo in the middle of generated event QR-Codes](https://github.com/corona-warn-app/cwa-website/issues/1702#issue-987872541).

## Suggested change
Update of the screenshots on the RKI / PDF pages.
And, if necessary, adapt the texts in relation to cross-reference _1_.

## Update!
Not only the RKI pages are 'out of date', but also the "check-in" screenshots in the CWA documentation (at least those on Android). (I cannot check iOS.) 
Details see: Links under "Please refer".

On the one hand, the [Android screenshots](https://www.coronawarn.app/en/screenshots/#android_check_in) are probably from an earlier CWA version; see pictures 6 of 8 and 8 of 8.
On the other hand, the [Android documentation](https://www.coronawarn.app/en/screenshots/#android_screenshots) only has the heading "Check-in" while the [iOS documentation](https://www.coronawarn.app/en/screenshots/#ios_screenshots) have the headings "Check-In - Scan QR Code" and "Check-in - Create QR Code".
This applies to the German and English documentation.

On the one hand, the screenshots are probably from an earlier CWA version; see pictures 6 of 8 and 8 of 8.
On the other hand, the Android screenshots only have the heading "**Check-in**" while the iOS screenshots have the headings "**Check-In - Scan QR Code**" and "**Check-in - Create QR Code**".
This applies to the German and English documentation. 

These points also need to be corrected / harmonized. 

---
Internal Tracking ID: [EXPOSUREAPP-13644](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13644)

**Comment by MikeMcC399** [comment]
@dsarkar 

Are you logging both the [RKI website](https://rki.de/cwa) and the [cwa-website](https://www.coronawarn.app/) issue under Internal Tracking ID: [EXPOSUREAPP-13644](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13644)?

The original issue was only about content on the [RKI website](https://rki.de/cwa).

Are far as I can see the [cwa-website](https://www.coronawarn.app/) issue which is mentioned in the Update section of the OP is already resolved.

**Comment by dsarkar** [comment]
@MikeMcC399 CWA website issue only. We resolved it by manually creating screenshots, the internal ticket handles automatic screenshots.

**Comment by MikeMcC399** [comment]
@dsarkar 

Should this issue stay open if the CWA website issue is resolved and the RKI issue can't be dealt with here?

**Comment by Jo-Achim** [comment]
Thanks, @MikeMcC399.
