### ISSUE TITLE
Link to RKI archived app statistics gives 404 error

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3046]
## Where to find the issue

- https://www.coronawarn.app/en/faq/results/#numbers_RKI "Where can I find numbers and statistics about the Corona-Warn-App?
- https://www.coronawarn.app/de/faq/results/#numbers_RKI "Wo finde ich Zahlen und Statistiken über die Nutzung der Corona-Warn-App?
- https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/ "Explanation of the statistic tiles in the Corona-Warn-App"
- https://www.coronawarn.app/de/blog/2021-08-05-statistictiles/ "Erläuterung der Statistikkacheln in der Corona-Warn-App"

## Describe the issue

1. The above CWA pages include a link to https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html which gives error 404 file not found ("Diese Seite gibt es nicht.")
![image](https://user-images.githubusercontent.com/66998419/180640375-5c0e7d91-f89e-4247-a99d-a1ec71be4a62.png)

2. Since the app uses the blog link to explain statistics, the error also affects the app

## Steps to reproduce

1. Open the above links and click on the RKI link https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html
2. For the app, scroll down to statistics tiles, tap on icon top right of "Warnings by App Users". Scroll down to the bottom and click on blog link. In web browser scroll down to 'Tile "Warnings by App Users"' then at the bottom of this section under References tap on [1]RKI - WarnApp Kennzahlen.
3. Execute `npx cypress run -s cypress/integration/hybrid/check_links.js -c baseUrl=https://coronawarn.app`

## Suggestion

Remove references to the removed RKI Key Performance Indicator archive from the FAQ articles and from the blog article.

---
Internal Tracking ID: [EXPOSUREAPP-13688](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13688)

**Comment by MikeMcC399** [comment]
- PR #3047 submitted to resolve this issue

**Comment by Ein-Tim** [comment]
@MikeMcC399

What's your take on replacing the 404 link with one to https://www.coronawarn.app/de/blog/2021-10-01-facts-and-figures/ instead of removing it completely? I have no strong opinions in either directions.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> What's your take on replacing the 404 link with one to https://www.coronawarn.app/de/blog/2021-10-01-facts-and-figures/ instead of removing it completely? I have no strong opinion in either direction.

Thanks for your comments. I had forgotten about this blog posting and you are right that this would be a possibility to link to. I will put the PR into draft status and wait for feedback from the Open Source Team.

**Comment by MikeMcC399** [comment]
- PR #3047 has been merged. As commented in https://github.com/corona-warn-app/cwa-website/pull/3047#issuecomment-1193285878 the only additional information available from links in the blog post https://www.coronawarn.app/de/blog/2021-10-01-facts-and-figures/ concerned hotline statistics which have not been published since September 2021.
- The hard error executing `npx cypress run -s cypress/integration/hybrid/check_links.js -c baseUrl=https://coronawarn.app` has been resolved.
- As in the past, the test is not 100% reliable due to network connections to third-party sites such as https://www.instagram.com and https://plotly.com/. When it fails, the best option is to run the test again.
- Closing as resolved.
