### ISSUE TITLE
Slow FAQ article display on mobile

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3051]
## Where to find the issue

https://www.coronawarn.app/en/faq/results FAQ detail page

## Describe the issue

Displaying an FAQ article on a mobile device is slow. Typically it takes 8 seconds.

### Manual measurements

In Google Chrome on mobile Android device, bookmark the following URLs:

Label | URL
--- | ---
FAQ_1 | https://www.coronawarn.app/en/faq/#further_details
FAQ_2 | https://www.coronawarn.app/en/faq/results/#further_details
Blog_1 | https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/

Load times in seconds in Google Chrome. First figure is manually measured. Figure in brackets ( )  is from Google Chrome developer, Network tab "Finish" duration:

URL | Android 12 | Windows 11
--- | --- | ---
FAQ_1 | 8 (6.35) | 3 (1.67)
FAQ_2 | 7 (5.85) | 3 (1.88)
Blog_1 | 2 (1.42) | < 1 (0.545)

Android and Windows connected to same WLAN.
Remote connect to Android according to https://developer.chrome.com/docs/devtools/remote-debugging/
In Android 12 with reload icon.
In Windows 11 with Ctrl-F5 to reload page without cache.

### Lighthouse measurements

In Google Chrome Incognito window, open https://www.coronawarn.app/en/faq/results Press F12
Select Lighthouse
Select Navigation / Mobile / Performance
Click "Analyze page load"
Note Performance score 50
First Contentful Paint 8.2 s
Time to Interactive 9.3 s

## Expectation

FAQ display in less than 2 seconds on real mobile device.
Lighthouse Time to Interactive on simulated mobile device also less than 2 seconds.

---
Internal Tracking ID: [EXPOSUREAPP-13694](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13694)

**Comment by MikeMcC399** [comment]
- https://github.com/corona-warn-app/cwa-documentation/issues/912 is related.

**Comment by larswmh** [comment]
Thanks for your report @MikeMcC399. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13694](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13694)

---
Corona-Warn-App Open Source Team
