### ISSUE TITLE
2.25 blog: Picture comparison doesn't work on mobile devices

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#3061]
## Where to find the issue
- https://www.coronawarn.app/en/blog/2022-07-27-cwa-2-25/
- https://www.coronawarn.app/de/blog/2022-07-27-cwa-2-25/

## Describe the issue
The blog post which announces version 2.25 includes a paragraph where the guidelines of version 2.24 are compared to the ones in version 2.25. For this, two pictures are shown next to each other with the description "Left: Guidelines in case of a low risk (green tile) before, right: Guidelines in case of a low risk (green tile) as of version 2.25". However, on a mobile device, the pictures aren't shown next to each other but first the one from version 2.24 and then the one from version 2.25.

## Suggested change
Fix this issue somehow. It seems to confuse users, see https://twitter.com/longvaccvoyager/status/1552892613828780033?s=20&t=YMr0t8j1x_3WJncy98sWqQ.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for reporting. We will think about a fix.
