### ISSUE TITLE
TAN procedure FAQ: State an exact number of days how long the app needs to be installed

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#3064]
## Feature description

Currently, the FAQ entry https://www.coronawarn.app/en/faq/results/#tan_procedure, states:
"To reasonably record encounters through contact tracing and alert these contacts, the Corona alert app [sic!] must be installed on the smartphone for at least a period of time; the TAN hotline will verify that period."

Please add the exact number of days how long the app needs to be installed so that a TAN is issued. 

## Problem and motivation
Clearer information.

**Comment by MikeMcC399** [comment]
Also, if this is a fixed rule, then the app should be enhanced to inform the user not to request a TAN unless it has been installed for the minimum duration.

The app is able to determine how long it was installed and it already outputs this information in the risk status tile if it has only been installed for a short period of time.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- This issue is related to your wishlist item https://github.com/corona-warn-app/cwa-wishlist/issues/871
- When the TAN hotline is shut down after CWA 3.0 is released then this issue will no longer be applicable

**Comment by Ein-Tim** [comment]
@MikeMcC399 True, I'll wait until version 3.0 is released, after that I will close this issue. 

Also, general information: I will wait until version 3.1 has been released, after that I will review all issues opened by me in one of the cwa repositories and assess whether they are still relevant even in the ramp down phase or if they can be closed!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- In the text you quoted in the OP the name of the app was corrected in https://github.com/corona-warn-app/cwa-website/pull/3067. It now says:<br><br>"To reasonably record encounters through contact tracing and alert these contacts, the Corona-Warn-App must be installed on the smartphone for a minimum period of time; the TAN hotline will verify that period."

- The necessary number of days have however never been published.

**Comment by Ein-Tim** [comment]
This issue will be obsolete when the TAN hotline is shut down on 31. Jan. 2023.

**Comment by Ein-Tim** [comment]
I'm closing this issue now as it will be obsolete very soon and I don't expect any changes on this anymore before the hotline shuts down.
