### ISSUE TITLE
Translation issues for Science 5 (EN) graphs

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3065]
## Where to find the issue

https://www.coronawarn.app/en/science/2022-03-03-science-blog-5/

## Describe the issue

These are issues with the graphs included after merge of the Science 5 article translation into English. See PR https://github.com/corona-warn-app/cwa-website/pull/3058.

### Fig 1: Tests provided and accessed via the CWA and their results.

- Typo: `Possitive test results (accessed)`
should be "Positive"

### Fig 3: Number of individuals who received a red and green warning per individual providing a warning in chronological sequence.

- Missing closing bracket on y-axis `Number of warning individuals (per individual providing a warning`

- Multiple years shown with no year specified

### Figure 4: Positivity rate after risk notification in chronological sequence (PCR)

- y-axis is labelled `Percentage of individuals that tested positive` and `Percentage` is also used to label graph data, however the numbers on the y-axis are a fraction not a percentage. In German the term "Positivenanteil" is used.

- Multiple years shown with no year specified

### Figure. 5: Positivity rate after risk notification. The number of new infections in chronological sequence (RAT).

- Similar comment to above regarding the incorrect use of the term "Percentage" for the y-axis.

- Multiple years shown with no year specified

### Figure 6: Percentage of users, for whom the risk determination is not possible (CWA data donation).

- Similar comment to above regarding the incorrect use of the term "Percentage" for the y-axis.

- Multiple years shown with no year specified

- Typo: `White tail` should be `White tile`

### Figure 10: Estimation of the number of active users resulting from the percentage of the individuals donating data.

- Untranslated label `Mittelwert der letzten 30 Tage` is in German

### Figure 11: Comparison of download numbers and active users or active apps, respectively, for Corona-Warn-App, and SwissCovidApp.

- Untranslated label `Aktive Nutzende` is in German

### Figure 12: Active devices in the narrower sense) via downloads of daily key files (TSI).

- Dates are in German format e.g. `6. Dec`. English dates do not use a "."

### Figure 13: Active devices (in the narrower sense) after days since last accessing the daily key files (TSI)

- Untranslated x-axis label `Tag`

### Figure 15: Information relating to the installation (Apple).

- Untranslated term `Hochrechnung` is in German

### Figure 16: Various estimations of active users (in the broader sense).

- Untranslated terms `Mittelwert`, `Heuristik` and `Warnende` are in German

## Suggestion

Correct translation issues in graphs and republish.

**Comment by christianneu** [comment]
Issue was fixed, therefore I would close it.

**Comment by MikeMcC399** [comment]
@christianneu 

> Issue was fixed, therefore I would close it.

None of these issues have been fixed. For example Fig. 1 from https://www.coronawarn.app/en/science/2022-03-03-science-blog-5/ still has the typo "Possitive", which should be "Positive" in it.

![image](https://user-images.githubusercontent.com/66998419/185358731-eea4f27b-6345-4574-8563-f5cd61cee4b9.png)

Please check and re-open.

**Comment by MikeMcC399** [comment]
This issue was closed by the Open Source Team in error. None of the problems described in this issue have been fixed. Please re-open.

**Comment by MikeMcC399** [comment]
@corona-warn-app/cwa-moderators

- Please re-open this issue which was closed by mistake. The problems in this issue have not been addressed.  I cannot re-open it myself since it was closed by @christianneu who made the incorrect statement in https://github.com/corona-warn-app/cwa-website/issues/3065#issuecomment-1219224665 "Issue was fixed".

**Comment by MikeMcC399** [comment]
- Reposted to #3079.
