### ISSUE TITLE
FAQ article with legacy link not displayed after visiting main FAQ page

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3070]
## Where to find the issue

https://www.coronawarn.app/en/faq/ and https://www.coronawarn.app/en/faq/results/

## Describe the issue

If an attempt is made to display an FAQ article with a legacy link `https://www.coronawarn.app/en/faq/<#article_hash>` (such as used by the CWA Android and iOS apps) directly after having visited the FAQ overview page https://www.coronawarn.app/en/faq/ then no article is shown. The display stays at the overview page.

### In browser

1. Open Google Chrome
2. Paste `https://www.coronawarn.app/en/faq/` into the address bar and press `Enter`
3. Note that the page "How can we help you?" is shown
4. Paste `https://www.coronawarn.app/en/faq/#android_location` into the address bar and press `Enter`
5. Note that the page display does not change. It still shows the contents from `https://www.coronawarn.app/en/faq/`
6. Press `<F5>` to reload the page
7. Now the article `https://www.coronawarn.app/en/faq/results/#android_location`is shown

### With Cypress
Save the following code into cypress/e2e/faq_page_change.cy.js

```
it("Show problem with FAQ article display", () => {
    cy.visit("/en/faq/");
    cy.visit("/en/faq/#android_location");
    cy.get("#android_location");
});
```

Run it with
`npx cypress open -c baseUrl=https://www.coronawarn.app`
Modify `baseUrl` also to `https://coronawarn.app` and `http://localhost:8000` for different test conditions.

For `http://localhost:8000` use `npm start` in a separate window to start the local server.

Select browser to test in Cypress test runner and click on `faq_page_change.js` to run test.

#### Results

 | `baseUrl` \ Browser          | Chrome 104 | Firefox 103 | Electron 94 |
 | -------------------------- | ---------- | ----------- | ----------- |
 | https://www.coronawarn.app | (1)        | (1)         | (1)         |
 | https://coronawarn.app     | (2)        | (2)         | (2)         |
 | http://localhost:8000      |  No error  |  No error  | (1)         |

 Errors:
 (1) "Timed out retrying after 4000ms: Expected to find element: #android_location, but never found it."
 (2) "Timed out after waiting 100000ms for your remote page to load.
Your page did not fire its load event within 100000ms."

## Expected behaviour

Visiting a legacy FAQ link, such as `https://www.coronawarn.app/en/faq/#android_location` directly after having visited the FAQ overview page `https://www.coronawarn.app/en/faq/` should result in a redirection to the `faq/results` page, in this example to `https://www.coronawarn.app/en/faq/results/#android_location`.

The FAQ article should be displayed.

---
Internal Tracking ID: [EXPOSUREAPP-14106](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14106)

**Comment by MikeMcC399** [comment]
Most users will not notice this issue. I noticed it when I was researching a Cypress test to take the links directly from the app. This is based on ideas from PR https://github.com/corona-warn-app/cwa-website/pull/2968 and from @brifemu / @svengabr.

**Comment by Ein-Tim** [comment]
I **can** reproduce this issue with the following environment:

- macOS Monterey 12.5
- Edge Version 103.0.1264.77 (Official Build) (arm64)

I **can't** reproduce this issue with the following environment:

- macOS Monterey 12.5
- Safari Version 15.6

---

I therefore guess that this has a combination of root causes, on one side something in Chromium and on the other side how the redirecting is implemented on the CWA website.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I don't know why you can't reproduce the issue on Safari.

The Cypress test fails on Electron, Chrome, Firefox and Edge.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Most probably Safari implemented something in a different way then the other browsers. 

Let's wait for feedback from the devs.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Did you run the Cypress test with Safari or did you only test manually with Safari?

**Comment by Ein-Tim** [comment]
@MikeMcC399 I only tested manually.

**Comment by MikeMcC399** [comment]
Revised test for Cypress

Save the following code into cypress/integration/faq_page_change.js

```
it("Show problem with FAQ article display", () => {
    cy.visit("/en/faq/");
    cy.visit("/en/faq/#android_location");
    cy.get("#android_location");
});
```

Run it with
`npx cypress open -c baseUrl=https://www.coronawarn.app`
Modify `baseUrl` also to `https://coronawarn.app` and `http://localhost:8000` for different test conditions.

For `http://localhost:8000` use `npm start` in a separate window to start the local server.

Select browser to test in Cypress test runner and click on `faq_page_change.js` to run test.


### Results

 | `baseUrl` \ Browser          | Chrome 104 | Firefox 103 | Electron 94 |
 | -------------------------- | ---------- | ----------- | ----------- |
 | https://www.coronawarn.app | (1)        | (1)         | (1)         |
 | https://coronawarn.app     | (2)        | (2)         | (2)         |
 | http://localhost:8000      |  -         |  -          | (1)         |

 Errors:
 (1) "Timed out retrying after 4000ms: Expected to find element: #android_location, but never found it."
 (2) "Timed out after waiting 100000ms for your remote page to load.
Your page did not fire its load event within 100000ms."

**Comment by larswmh** [comment]
Thanks for your report @MikeMcC399. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-14106](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14106)

---
Corona-Warn-App Open Source Team
