### ISSUE TITLE
Open Source Team support in August 2022

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3072]
@dsarkar 

In https://github.com/corona-warn-app/cwa-app-ios/issues/4602#issuecomment-1205004898 you wrote:

> FYI, in August we, @larswmh, @svengabr, and @dsarkar from the Corona-Warn-App Open Source Team, will have only very sporadically a look here at the GitHub repositories of the CWA project.

That is quite a surprise, although I did notice that there had been no other activity from the team since last weekend.

I submitted three PRs with corrections for the website. 

- ~~https://github.com/corona-warn-app/cwa-website/pull/3066~~ (merged)
- https://github.com/corona-warn-app/cwa-website/pull/3067
- ~~https://github.com/corona-warn-app/cwa-website/pull/3068~~ (merged)

Will you (or somebody else) process these PRs? @corona-warn-app/cwa-moderators ?

**Comment by Ein-Tim** [comment]
I will also add the following questions here:

- What is the plan reg. mirroring issues to JIRA? Will this be done by the developers themselves?
- What about the CWA website? CMs always were responsible for updating its content, merging & reviewing PRs, etc.?
- Is this _break_ only planned for August or for an undefined period of time?

**Comment by Ein-Tim** [comment]
FYI @MikeMcC399, from @GisoSchroederSAP's statement in https://github.com/corona-warn-app/cwa-app-ios/issues/4602#issuecomment-1205273865:

> Regarding the WebPage, which is an important part of the CWA communication and documentation, we will also continue to work on necessary changes/updates.

**Comment by MikeMcC399** [comment]
Closing, as now 2 of the 3 PRs have been merged.

- Following up in https://github.com/corona-warn-app/cwa-website/pull/3067 which is still open
