### ISSUE TITLE
FAQ Link #vac_cert_booster does not display requested FAQ section on mobile device

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3073]
## Where to find the issue

https://www.coronawarn.app/en/faq/#vac_cert_booster

## Describe the issue

If the FAQ link "For further information, please see our FAQ page." (https://www.coronawarn.app/en/faq/#vac_cert_booster) is followed in the CWA app under "Note on Booster Vaccination" and the mobile device is in portrait mode, then no useful information is shown in the web browser. Instead only top-level FAQ topics are shown.

### In app

Mobile device is connected via WLAN

1. Tap Scan and scan in a 2/2 vaccination certificate
2. Tap back-arrow
3. Tap Certificates
4. Tap right-arrow
5. Tap "Note on Booster Vaccination"
6. Tap on link at bottom of text to Rule DE-BNR-0110 "For further information, please see our FAQ page."
7. Note that browser first goes to https://www.coronawarn.app/en/faq/#vac_cert_booster then to https://www.coronawarn.app/en/faq/results/#vac_cert. The display however shows only topic sections.

Edit: The above steps work in CWA 2.25. Starting with CWA 2.26 the target link has changed and the steps no longer show the issue.

### In browser

1. Open Google Chrome on a desktop
2. Press F12 for developer mode
3. Toggle device toolbar and select Samsung Galaxy A51/71 in portrait mode with throttling set to Mid-tier mobile
4. Paste https://www.coronawarn.app/en/faq/#vac_cert_booster into address field and press `Enter`
5. Note that only section headers are shown and these do not lead to information about vaccination certificate boosters.

![image](https://user-images.githubusercontent.com/66998419/183151644-3408efe0-cdca-4156-b2de-0abf77156b05.png)

## Expectation

When using the link on a mobile device to open https://www.coronawarn.app/en/faq/#vac_cert_booster, the section FAQ > App Features > Vaccination Certificates should be shown.

![vac_cert](https://user-images.githubusercontent.com/66998419/183306803-aad12662-7ac8-42b7-9027-c6e495416a35.jpg)

## Workarounds

1. The following is not a useful work around in practice, however it shows that the issue is with the website in portrait mode.<br>In the app "Steps to reproduce" above, before tapping on the link "For further information, please see our FAQ page.", turn the mobile device into landscape mode.
2. Scroll up to search field. Enter word "booster", select section "App Features", tap "Search". Scroll down to search results.

## Background information

Before the FAQs were reorganized, the link https://www.coronawarn.app/en/faq/#vac_cert_booster displayed a list of links:

![old-vac_cert_booster](https://user-images.githubusercontent.com/66998419/183575279-74e26e54-0c04-4fb4-b34c-3bc378a5385a.jpg)

This list was removed and the nearest equivalent was the section heading above this list which is https://www.coronawarn.app/en/faq/#vac_cert.

---
Internal Tracking ID: [EXPOSUREAPP-14102](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14102)

**Comment by MikeMcC399** [comment]
- This issue may be mitigated by CCL PR https://github.com/corona-warn-app/cwa-app-ccl/pull/90 which changes the FAQ anchor in use from [#vac_cert_booster](https://www.coronawarn.app/en/faq/results/#vac_cert_booster) to [#vac_booster_basics](https://www.coronawarn.app/en/faq/results/#vac_booster_basics). Although the PR is merged, it is not yet in production (see https://github.com/corona-warn-app/cwa-app-ccl/issues/88#issuecomment-1223713618).

**Comment by MikeMcC399** [comment]
This issue is mitigated by CCL 3.2.1, however the underlying website issue is still present and the steps to reproduce using a desktop browser simulating a mobile device are still able to demonstrate the issue:

### In browser

1. Open Google Chrome on a desktop
2. Press F12 for developer mode
3. Toggle device toolbar and select Samsung Galaxy A51/71 in portrait mode with throttling set to Mid-tier mobile
4. Paste https://www.coronawarn.app/en/faq/#vac_cert_booster into address field and press `Enter`
5. Note that only section headers are shown and these do not lead to information about vaccination certificate boosters.

![image](https://user-images.githubusercontent.com/66998419/183151644-3408efe0-cdca-4156-b2de-0abf77156b05.png)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reporting. FYI PR https://github.com/corona-warn-app/cwa-website/pull/3138
