### ISSUE TITLE
Cypress failure (403 forbidden) checking EU cert json spec

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3076]
## Where to find the issue

- https://www.coronawarn.app/en/faq/results/#vac_booster_jj "Why does a 14-day wait for full vaccine protection after a booster vaccination appear in the Corona-Warn-App?"
- https://www.coronawarn.app/de/faq/results/#vac_booster_jj "Warum erscheint in der Corona-Warn-App eine 14-tägige Wartezeit bis zum vollen Impfschutz nach einer Auffrischimpfung?"

## Describe the issue

FAQ https://www.coronawarn.app/en/faq/results/#vac_booster_jj links to the European Commission document https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf (Guidelines on Technical Specifications for EU Digital COVID Certificates JSON Schema Specification). When the Cypress test `hybrid/check_links.js` is run, it fails with an HTTP 403 error (forbidden).

## Steps to reproduce

Execute:
`npm run test:open`
select `hybrid/check_links.js`

View the file `cypress/logs/broken_links_result.txt`

```
==================== Broken links ====================

[RESPONSE 403] https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf on '/de/faq/results/' 
[RESPONSE 403] https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf on '/en/faq/results/'
```

## Analysis

A manual HTTP GET request to https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf using [Postman](https://www.postman.com/) also returns an HTTP 403 error, Generated by cloudfront (CloudFront).

Accessing
https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf via web browser shows that the document has been moved permanently (HTTP 301) to 
https://health.ec.europa.eu/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf and then moved temporarily (HTTP 302) to https://health.ec.europa.eu/system/files/2021-06/covid-certificate_json_specification_en_0.pdf

Changing the link's domain from `ec.europa.eu` to `health.ec.europa.eu` does not change the 403 (forbidden) error condition under Cypress or Postman, so it seems that CloudFront has implemented security to prevent automatic requests from succeeding.

European Commission specifications are indexed under:

https://health.ec.europa.eu/ehealth-digital-health-and-care/ehealth-and-covid-19_en

## Suggestion

Change the document link domain from `ec.europa.eu` to `health.ec.europa.eu` to match the links on the EU overview page https://health.ec.europa.eu/ehealth-digital-health-and-care/ehealth-and-covid-19_en.

Add https://health.ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf to the `allowlist` array of `check_links.js` to prevent testing and receiving a 403 (forbidden) error.

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/3077 is submitted to resolve this issue.

Currently there is an unrelated issue with the domain https://www.t-systems.com/ which is returning a 403 forbidden error. Presumably, this is a temporary issue only. This causes the Cypress test `check_links.js` to fail.

**Comment by christianneu** [comment]
Thanks for the fix! :-)
