### ISSUE TITLE
Translation issues for Science 5 (EN) graphs

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3079]
Reposted from https://github.com/corona-warn-app/cwa-website/issues/3065 where the issue was mistakenly closed.

## Where to find the issue

https://www.coronawarn.app/en/science/2022-03-03-science-blog-5/

## Describe the issue

These are issues with the graphs included after merge of the Science 5 article translation into English. See PR https://github.com/corona-warn-app/cwa-website/pull/3058.

### Fig 1: Tests provided and accessed via the CWA and their results.

- Typo: `Possitive test results (accessed)`
should be "Positive"

### Fig 3: Number of individuals who received a red and green warning per individual providing a warning in chronological sequence.

- Missing closing bracket on y-axis `Number of warning individuals (per individual providing a warning`

- Multiple years shown with no year specified

### Figure 4: Positivity rate after risk notification in chronological sequence (PCR)

- y-axis is labelled `Percentage of individuals that tested positive` and `Percentage` is also used to label graph data, however the numbers on the y-axis are a fraction not a percentage. In German the term "Positivenanteil" is used.

- Multiple years shown with no year specified

### Figure. 5: Positivity rate after risk notification. The number of new infections in chronological sequence (RAT).

- Similar comment to above regarding the incorrect use of the term "Percentage" for the y-axis.

- Multiple years shown with no year specified

### Figure 6: Percentage of users, for whom the risk determination is not possible (CWA data donation).

- Similar comment to above regarding the incorrect use of the term "Percentage" for the y-axis.

- Multiple years shown with no year specified

- Typo: `White tail` should be `White tile`

### Figure 10: Estimation of the number of active users resulting from the percentage of the individuals donating data.

- Untranslated label `Mittelwert der letzten 30 Tage` is in German

### Figure 11: Comparison of download numbers and active users or active apps, respectively, for Corona-Warn-App, and SwissCovidApp.

- Untranslated label `Aktive Nutzende` is in German

### Figure 12: Active devices in the narrower sense) via downloads of daily key files (TSI).

- Dates are in German format e.g. `6. Dec`. English dates do not use a "."

### Figure 13: Active devices (in the narrower sense) after days since last accessing the daily key files (TSI)

- Untranslated x-axis label `Tag`

### Figure 15: Information relating to the installation (Apple).

- Untranslated term `Hochrechnung` is in German

### Figure 16: Various estimations of active users (in the broader sense).

- Untranslated terms `Mittelwert`, `Heuristik` and `Warnende` are in German

## Suggestion

Correct translation issues in graphs and republish.

---
Internal Tracking ID: [EXPOSUREAPP-14097](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14097)

**Comment by larswmh** [comment]
@MikeMcC399 thanks for your report. I have provided a fix for this in #3129
