### ISSUE TITLE
Outdated wait time (3 months) for 1st booster in FAQ

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3080]
## Where to find the issue

- https://www.coronawarn.app/en/faq/results/#vac_booster_basics "What is a booster vaccination and how does it appear in the CWA?"
- https://www.coronawarn.app/de/faq/results/#vac_booster_basics "Was ist eine Auffrischimpfung und wie wird sie in der CWA dargestellt?"

## Describe the issue

The above FAQ says "A booster vaccination (revaccination) is a vaccination process designed to refresh waning vaccination protection after basic immunization. In most cases, but not always, it takes place according to the recommendations of the authorities after a period of 3 months after the last vaccination procedure. (Example: completion of the vaccination series for basic immunization on 08 Jan 2022, possible booster vaccination on: 08 Apr 2022)".

The German STIKO authority now recommends a 6 month's, not 3 month's wait for the 1st booster. (See [Epidemiologisches
Bulletin 3 2022](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/33_22.pdf?__blob=publicationFile) Stand: 18.08.2022, Page 10, Table 4.) This means that the FAQ is not in alignment with the latest official recommendations.

## Suggestion

Update the FAQ according to the 21st STIKO recommendations, having regard also to the outcome of issue https://github.com/corona-warn-app/dcc-rule-translation/issues/10 questioning whether the app will also be updated to use a recommended wait time of 6 months in the BNR rules.

---
Internal Tracking ID: [EXPOSUREAPP-14105](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14105)

**Comment by MikeMcC399** [comment]
The web page https://www.zusammengegencorona.de/impfen/#id-862101356 from Bundesministerium für Gesundheit (BMG)

"Mit dem "Impf-Guide" zu Ihrer persönlichen Impfempfehlung

Der Impf-Guide hilft Ihnen ganz konkret: Wird eine Corona-Schutzimpfung von der Ständigen Impfkommission (STIKO) für Sie empfohlen? Falls ja, mit welchem Impfstoff? Und wann ist der richtige Zeitpunkt?"

implements the 6 month rule for booster vaccinations. In addition this guide is much finer tuned to the different age groups. Perhaps the link should be added to the CWA FAQs to give more accurate advice?

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for your suggestions! PR https://github.com/corona-warn-app/cwa-website/pull/3140
