### ISSUE TITLE
Request for release branches for 2.26 and 2.27

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3084]
Please create new branches:

`release/2.26`
`release/2.27`

in this repository.

- According to the [CCL 3.2](https://github.com/corona-warn-app/cwa-app-ccl/milestone/5) milestone CCL will start using the FAQ anchor `#vac_booster_basics` (see PR https://github.com/corona-warn-app/cwa-app-ccl/pull/90) with the release of the CWA 2.26 app.
- Also due to feature additions for CWA 2.27 there is expected to be a link to a new FAQ article regarding mask rules (see for instance screenshot in PR https://github.com/corona-warn-app/cwa-app-android/pull/5492). The anchor is expected to come from CCL.

For both these cases the new FAQ anchors provided by CCL should be prepared for the respective release by adding them to [cypress/fixtures/appToWebLinks.json](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/fixtures/appToWebLinks.json) and queuing the changes in the corresponding release branch (rather than merging directly into the `master` branch).

**Comment by MikeMcC399** [comment]
- Since there was no response so far to this request, I submitted PR https://github.com/corona-warn-app/cwa-website/pull/3086 with the `master` branch as target.

**Comment by GisoSchroederSAP** [comment]
Thank you, @MikeMcC399 , for taking action. 
We are aware of prep steps to be done for the next release(s) and will act accordingly.

**Comment by MikeMcC399** [comment]
Closing, since branch [release/2.26](https://github.com/corona-warn-app/cwa-website/tree/release/2.26) has now been created.
`release/2.27` will be a separate step.
