### ISSUE TITLE
Update `further_details` FAQ entry with information on weekend numbers

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#3087]
## Suggested enhancement
Add information on why the statistic numbers in the CWA may be inaccurate on weekends (& Mondays) to the FAQ entry
- https://www.coronawarn.app/en/faq/results/#further_details
- https://www.coronawarn.app/de/faq/results/#further_details

## Problem and motivation
Currently CWA just shows numbers like "1" or "2" on the "Reported New Infections" statistic tiles which leads many users to wonder if the app is broken or something else went wrong.

See also https://github.com/corona-warn-app/cwa-wishlist/issues/845.

## Is this something you're interested in working on

Yes, I would suggest to add the text (or a slightly adjusted one) which is shown on the [RKI COVID-19 Germany dashboard](https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4) on weekends which is:
"Da am Wochenende nur noch wenige Gesundheitsämter und Landesbehörden Daten an das RKI übermitteln, werden keine Daten am RKI eingelesen, sodass es bei den absoluten Fallzahlen keine Veränderung zum Vortag gibt. Die Änderung der 7-Tage-Inzidenz im Vergleich zum Vortag beruht lediglich auf einer Änderung des Bezugszeitraums (jeweils 7 Tage vor dem Tag der Berichterstattung)."

**Comment by MikeMcC399** [comment]
Just to provide a concrete example from the tile "Confirmed New Infections" for today, Monday, August 29, 2022 looks as though the data feed must be broken and there is no explanation for this in the app or in the FAQs.

Normally you could expect the number of new infections to be close to the 7-Day-Average. The number 1 for the daily report and 33,303 for the 7-Day-Average are however completely different.

If numbers are not reported to RKI at all at weekends then it calls into question the value of publishing daily figures in the app.

![image](https://user-images.githubusercontent.com/66998419/187266870-110942a2-e449-45e6-bd73-30d8c4fc1f11.png)

The full help text from https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4 is below (click on arrow on left of screen) :

![image](https://user-images.githubusercontent.com/66998419/187268882-2a51331f-1c4e-477a-9c2f-74f7bba1ae23.png)

**Comment by MikeMcC399** [comment]
Tuesday, August 30, 2022
![image](https://user-images.githubusercontent.com/66998419/187386525-750438ad-ce99-4072-a01a-7e601985dea9.png)

**Comment by Ein-Tim** [comment]
@MikeMcC399 

The numbers from Monday, which are displayed today in the CWA, seem more realistic and closer to the actual "Infektionsgeschehen".

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The Tuesday number partially compensates for the Monday number. The Tuesday number is 68% more than the 7-Day-Average.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, seems like the in-app explanation text will be extended. The question is: Should the FAQ be extended with the same text?

I leave this to the team to decide (@christianneu).

**Comment by MikeMcC399** [comment]
It looks like the 1% rule was already implemented. Yesterday (Monday) the app was showing data from last Friday. Today (Tuesday) it is showing the data from yesterday (Monday).

**Comment by Ein-Tim** [comment]
@MikeMcC399 

- I guess https://github.com/corona-warn-app/cwa-server/pull/1893 is already in production.

I don't think the FAQ needs updating at this point, so I'm closing this issue.
