### ISSUE TITLE
FAQ Search breaks literally displayed hyperlinks

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3088]
## Where to find the issue

https://www.coronawarn.app/en/faq/

## Describe the issue

If a search term is found in a hyperlink in the FAQs, where the literal text of the hyperlink is displayed (rather than a text description) then clicking on the hyperlink fails. For example, searching for "reopen" breaks the hyperlink https://reopen.europa.eu/en.

## Steps to reproduce

1. Open https://www.coronawarn.app/en/faq/ in web browser
2. Type "reopen" (without quotes) into search field and click on "Search"
3. Click on "Expand/Collapse all"
4. Scroll down to https://reopen.europa.eu/en 
![click reopen](https://user-images.githubusercontent.com/66998419/188665084-854da88b-a9cd-4998-a0ca-6fdbfd944624.jpg)

5. Click on this link (which expands to `https://%3Cspan%20class%3D%27highlight%27%3Ereopen%3C/span%3E.europa.eu/en`) and note that the site cannot be reached. 
![site cant be reached](https://user-images.githubusercontent.com/66998419/188665126-11e4854e-d1e7-474b-a30a-9504c4832bf1.jpg)

The source shows the modified element as follows:

`<a href="https://<span class='highlight'>reopen</span>.europa.eu/en" target="_blank" rel="noopener noreferrer" tabindex="-1">https://reopen.europa.eu/en</a>`

Searching for "https:", and then clicking on a link, produces a 404 error.

## Suggestion

When highlighting a search term which has been found, do not modify a hyperlink destination address (`href`). Only text which is normally visible should be highlighted.

---
Internal Tracking ID: [EXPOSUREAPP-14101](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14101)

**Comment by brianebeling** [comment]
Hey @MikeMcC399

I fixed the issue. Thank you for reporting it!
Please let us know, in the case it doesn't work as expected or if there is an edge case.
