### ISSUE TITLE
FAQ should inform that it's normal under iOS that background checks are shifted back daily for 2 hours

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#309]
## Feature description

The FAQ should inform that under iOS the background checks are postponed by ± 2 hours daily and that this, at the moment, is expected behaviour.

## Problem and motivation

For _normal_ users it can be very confusing that the checks are not always made at the same time daily. See f.e.: [this comment from somebody who's confused because of this and thinks the App is not working correctly](https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-678782205)

**Comment by tkowark** [comment]
Added with https://github.com/corona-warn-app/cwa-website/pull/310
