### ISSUE TITLE
Missing 2.26 screenshots

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3094]
## Where to find the issue

https://www.coronawarn.app/en/screenshots/

## Describe the issue

There is no screenshot information for the current version of the app 2.26, released on Aug 31, 2022 (see https://www.coronawarn.app/en/blog/2022-08-31-cwa-2-26/).

## Steps to reproduce

Go to https://www.coronawarn.app/en/screenshots/
Look for "Version 2.26" in version drop-down list. Note that it is missing.

## Suggestion

- Either add a message in the 2.25 screenshot description to say that the screenshots also apply to version 2.26 or
- add a new screenshot page for 2.26

---
Internal Tracking ID: [EXPOSUREAPP-14015](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14015)

**Comment by MikeMcC399** [comment]
- No response received, and now 2.27 has been released. 
- See issue #3110

**Comment by dsarkar** [comment]
@MikeMcC399 FYI PR https://github.com/corona-warn-app/cwa-website/pull/3118

**Comment by MikeMcC399** [comment]
The text

"With this update we provide new and enhanced features:

Updated behavioral recommendations: The behavioral recommendations for increased risk have been updated. Among other things, this concerns recommendations for reducing contacts or wearing masks. The recommendations for low risk have also been adapted."

has been copied from 2.25 and is not correct for 2.26.

Refer to 
- https://www.coronawarn.app/en/blog/2022-08-31-cwa-2-26/ and
- https://www.coronawarn.app/en/blog/2022-07-27-cwa-2-25/

**Comment by Ein-Tim** [comment]
@MikeMcC399 Sorry, I didn't check the content of the PR! Good that you spotted that! 

Comment above was hidden.

**Comment by MikeMcC399** [comment]
https://www.coronawarn.app/en/sitemap/ should include 2.25 screenshot archive

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for pointing out the bugs. Fix PR https://github.com/corona-warn-app/cwa-website/pull/3119

**Comment by MikeMcC399** [comment]
https://www.coronawarn.app/en/screenshots/ includes an incorrectly written date:

"August 31th, 2022"

Either

"August 31st, 2022" (see https://en.wikipedia.org/wiki/English_numerals#Ordinal_numbers) or
"August 31, 2022"

would be correct.

**Comment by larswmh** [comment]
Thanks for the information @MikeMcC399! I have created a PR to fix this issue #3123
