### ISSUE TITLE
Add information on how to receive a certificate of recovery to the FAQs

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#3098]
## Feature description

The FAQs should hold information on how & where the user is able to obtain an EU digital COVID certificate of recovery.

## Problem and motivation
In the past I explained how to get such a certificate quite often on Twitter. It seems like the information is not yet easy to find for most users, so a CWA FAQ entry would help here.

Some examples of me explaining this:
- https://twitter.com/EinTim2/status/1567153516199772162?s=20&t=sTTtSs-hSmZA7wdLdOGfWw
- https://twitter.com/EinTim2/status/1548698786968616961?s=20&t=sTTtSs-hSmZA7wdLdOGfWw
- https://twitter.com/EinTim2/status/1544757643423936513?s=20&t=sTTtSs-hSmZA7wdLdOGfWw
- https://twitter.com/EinTim2/status/1544696752493805569?s=20&t=sTTtSs-hSmZA7wdLdOGfWw

## Is this something you're interested in working on

Yes

---
Internal Tracking ID: [EXPOSUREAPP-14047](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14047)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

See also https://www.zusammengegencorona.de/faqs/corona-im-alltag/aktuelle-regelungen/#id-38c1e969-6acd-552d-ae67-39f28fa75975

![image](https://user-images.githubusercontent.com/66998419/189531744-5e32e743-30b0-4a0f-b529-cf07e40b9d46.png)

and https://digitaler-impfnachweis-app.de/faq

![image](https://user-images.githubusercontent.com/66998419/189531903-7cac7ec3-a5ab-4354-bdc3-559ba1b2b2ba.png)

**Comment by Ein-Tim** [comment]
@MikeMcC399 Thanks for the references! The problem is that also these articles aren't really concrete on how to obtain the certificate.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> The problem is that also these articles aren't really concrete on how to obtain the certificate.

I don't understand. Both articles say where to get a Certificates of Recovery. The second article explicitly says:

"Das digitale Genesenenzertifikat erhalten Sie in Gesundheitsämtern, Arztpraxen und Apotheken."

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Sorry for not being clear, I mean they don't sate for example that you need your ID card or the "Befundbrief".

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> I mean they don't sate for example that you need your ID card or the "Befundbrief".

I'm not sure that the CWA FAQs should go into this level of detail about what a pharmacy will ask for. If you are going to the doctor then they may already have the information. For pharmacies I saw a very detailed document https://www.abda.de/fileadmin/user_upload/assets/Corona/COVID-19-Zertifikate/COVID-19-Zertifikate_Handlungshilfe.pdf however I cannot say if this is completely up-to-date.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I know what you mean and will take it into consideration.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I updated the PR to not mention 180 days (technical limit for creation of recovery certificates) but only 90, to be consistent with other sources. 

I will leave the PR as it is for now and will wait for feedback form the Open-Source-Team.
