### ISSUE TITLE
Update Cypress to latest version (10)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3100]
This is a follow-on Cypress enhancement request from the closed issue "Cypress migration to 10.2?" https://github.com/corona-warn-app/cwa-website/issues/2980.

In the meantime the npm package [Cypress](https://www.npmjs.com/package/cypress) 10.11 has been released. No further releases of the Cypress 9.x series are expected.

## Issue

[cwa-website](https://github.com/corona-warn-app/cwa-website) is currently configured to use Cypress version 9.7.0 This version does not support the Apple M1 ARM architecture natively and requires Rosetta to run. (See blog [Running Cypress on the Apple M1 ARM Architecture using Rosetta 2](https://www.cypress.io/blog/2021/01/20/running-cypress-on-the-apple-m1-silicon-arm-architecture-using-rosetta-2/)).

Cypress 10.2.0 introduces M1 support and alleviates this issue for this version and later versions. See blog [Cypress 10.2.0: Run tests up to 2x faster on Apple silicon (M1)](https://cypress-io.ghost.io/blog/2022/06/21/cypress-10-2-0-run-tests-up-to-2x-faster-on-apple-silicon-m1/)

## Suggested change

Update [cwa-website](https://github.com/corona-warn-app/cwa-website) to the latest version of Cypress, which is currently [10.11.0](https://docs.cypress.io/guides/references/changelog#10-11-0).

See [Cypress Changelog](https://docs.cypress.io/guides/references/changelog).

## Impact

Cypress 10 introduces breaking changes due to the new functionality of component testing which is added alongside the existing end-to-end testing (e2e). For instance, new folders are introduced, so that the existing `cypress/integration` folder is migrated to `cypress/e2e`. Also test specs are renamed: `app_to_web.js` becomes `app_to_web.cy.js`. See the [Cypress Migration Guide](https://docs.cypress.io/guides/references/migration-guide) for more detail.

In Cypress 10 the "Run all specs" is no longer available in the UI. Only individual tests can be run from the UI. To run all tests the CLI needs to be used. See [Discussion: 'Run all specs' removal in Cypress 10](https://github.com/cypress-io/cypress/discussions/21628).

## Migration Steps

Close or merge any existing PRs relating to Cypress tests otherwise these PRs will become stranded and will not work as intended if merged without modification after the Cypress version is migrated.

### Install Cypress 10

1.  `npm install -D cypress@latest` (installs cypress@10.11.0 - see [Changelog](https://docs.cypress.io/guides/references/changelog))
2.  `npx cypress open`
3.  Click "Continue to Cypress 10"

### Migration tool

In the migration tool which automatically starts in the Cypress UI:
1. Click "Rename these specs for me"
2. Click "Rename the support file for me"
3. Click "Migrate the configuration for me"
   
- "E2E Testing" is now marked as "Configured"
- "Component Testing" is left as "Not Configured"

4. Close Cypress test runner window

### Post installation

1. Edit [.github/workflows/cypress-test-prod.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/cypress-test-prod.yml) 
    - change cypress spec folder from `integration` to `e2e` i.e. `spec: cypress/e2e/*.js`
    - ensure `cypress-io/github-action@v4` with v4 or later version of the action is specified (see https://github.com/cypress-io/github-action/releases) 
3. Modify the `cypress:open` script in [package.json](https://github.com/corona-warn-app/cwa-website/blob/master/package.json) to use `e2e` and browser Chrome i.e. `"cypress:open": "cypress open --e2e --browser chrome"`
4. Update [README.md](https://github.com/corona-warn-app/cwa-website/blob/master/README.md) regarding change of folder and removal of "all tests" option in `open` command.

## Verification

Execute the following and check that all tests pass:
```
npm run test:chrome
npm run test:firefox
npm run test
npx cypress run -s 'cypress/e2e/*.js' -c baseUrl=https://coronawarn.app --headless --browser chrome
```

Execute
`npm run test:open`
and check that the list of `e2e` test specs is shown immediately and the default browser is Chrome.
Select and run one of the tests listed, such as `mime.cy.js`.

Test on:
- Windows 11
- Ubuntu 20.04
- macOS

Test the workflow [.github/workflows/cypress-test-prod.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/cypress-test-prod.yml) and ensure that it passes.

---

- Note that there is currently an issue with a warning message "Couldn't find tsconfig.json. tsconfig-paths will be skipped". See issue 22273 in https://github.com/cypress-io/cypress/issues/22273. This warning can be ignored.

---
Internal Tracking ID: [EXPOSUREAPP-14080](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14080)

**Comment by MikeMcC399** [comment]
- The Open Source Team can respond if this enhancement request to update Cypress from 9.x to 10.x is desired. I already tested the migration to Cypress 10.7.0 locally, however I will not submit a PR unless there is feedback that a submitted PR would be merged.

- There is also an open Cypress PR https://github.com/corona-warn-app/cwa-website/pull/3086, submitted 2 weeks ago. Since the `fixtures` file modified by this PR is not affected by the migration from Cypress 9.x to 10.x there is no dependency, however it would still be useful to have this PR merged.

**Comment by MikeMcC399** [comment]
Updated OP due to release of Cypress 10.8.0.

**Comment by MikeMcC399** [comment]
@dsarkar 

> thank you very much for the suggestion, we will have a look at this!

Thank you also for your interest. I did a brief test with the latest Cypress version (10.9.0 released on Sep 27, 2022) and the tests ran successfully.

**Comment by dsarkar** [comment]
@MikeMcC399 If you submit your PR we will have a look at it and test it und if applicable merge it. Thanks.

**Comment by MikeMcC399** [comment]
@dsarkar 

> If you submit your PR we will have a look at it and test it und if applicable merge it.

- Thank you for your comment! I have submitted PR #3137. It is currently in draft state until I have retested it. I will test on Windows and Ubuntu. I don't have a Mac to test on, so hopefully somebody else will be able to test the Mac environment.

**Comment by dsarkar** [comment]
@MikeMcC399 Thank you very much for providing the PR. Indeed, we will test including the Mac environment.

**Comment by MikeMcC399** [comment]
It appears that the web does not successfully build on a native Apple M1 ARM environment, so if there is no complete web to test the Cypress test suite cannot run successfully in this environment either.

At the moment I therefore do not see significant advantage of migrating to Cypress 10 and so I have set the PR https://github.com/corona-warn-app/cwa-website/pull/3137 back to Draft status. Please let me know if anybody sees an advantage to migrate to Cypress 10 for other environments apart from the native Apple M1 ARM, i.e. Ubuntu, Windows and Apple (non-M1 ARM).

**Comment by dsarkar** [comment]
@MikeMcC399 I think for the time being we should not migrate to Cypress 10, since there are no apparent advantages right now. The main benefit would be the support of the Apple M1 processor. I would suggest not to close this issue, we can continue to investigate how to get it running Apple M1 machines at a later stage (which, I guess, will be appreciated also by @Ein-Tim). Thanks to you, @MikeMcC399, and all others for the effort invested so far.

**Comment by MikeMcC399** [comment]
@dsarkar 

Thank for providing your opinion. I have closed PR #3137, since at this time there is no advantage to carrying out further testing under the circumstances that you and I have described.

I agree to leave the issue open as you suggest.

**Comment by brianebeling** [comment]
There seems to be a workaround for building on M1 chips.
https://github.com/sass/node-sass/issues/3033#issuecomment-766794942

Maybe that's of interest to you. I'm also curious if that works for you, feel free to report back, thanks!

**Comment by MikeMcC399** [comment]
@brianebeling 

Thanks for your comment! I don't own or use any Apple hardware myself. Hopefully your tip will be helpful for others though.

It seems the best environment for testing is still Ubuntu, which also mirrors the environment that the GitHub runners are set up to use. M1 seems to crop up in multiple places concerning compatibility issues.

**Comment by MikeMcC399** [comment]
- Hopefully the workaround for node-sass mentioned in https://github.com/corona-warn-app/cwa-website/issues/3100#issuecomment-1293171741 (above) is no longer necessary, since PR https://github.com/corona-warn-app/cwa-website/pull/3180 has removed the dependency on node-sass.

- It would be good to hear from each of the testers with M1 hardware if `npm run build` is now working correctly (independently of Cypress). @Ein-Tim reported in https://github.com/corona-warn-app/cwa-website/pull/3137#issuecomment-1290868315 that he has no problems at the moment. I wonder if that is the same for @larswmh and @mtb77?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I re-checked just now, everything works on my environment.

**Comment by MikeMcC399** [comment]
@dsarkar 

Since the build on M1 is now working, would it be a good time to reactive this enhancement request and get a PR submitted for the currently latest version of Cypress (10.11.0)?

**Comment by dsarkar** [comment]
@MikeMcC399 Indeed, let's do that!

**Comment by MikeMcC399** [comment]
@dsarkar

Thanks for your confirmation!

- I submitted https://github.com/corona-warn-app/cwa-website/pull/3197 which I have already tested on a private copy of cwa-website

**Comment by MikeMcC399** [comment]
- PR #3197 is merged
- For this and other recent PR execute for instance:

```js
git switch master
git fetch upstream
git merge upstream/master
npm ci
```

in order to have the correct npm packages installed.

If you have trouble running Cypress the first time, try
`npx cypress open`
to get Cypress to initialize itself independently. It will give an error because it can't access localhost, but then you can èxecute for instance:
`npm run test:open`

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I would be interested to hear if Cypress testing now works for you. If you find any problem, please feel free to open a new issue.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, it works now! Only problem I have: When I enter `npm run test` it will start and set up a localhost instance, but I don't have Chrome installed and thus the test fails. I was able to select using Microsoft Edge, which I actually have installed on my machine, using the Cypress console. 

Also, the `applink.cy.js` always fails, see the screenshots below.

![Bildschirm­foto 2022-11-01 um 13 16 51](https://user-images.githubusercontent.com/67682506/199230547-27a343f9-343b-49ca-a19f-5620b227c540.png)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

It's good news to hear that Cypress is working for you! 🚀 Thank you for your feedback!

The scripts are set up for Chrome & Firefox only, so they are not optimised for default Mac usage.

I can't say why the `applink.cy.js` test fails for you. If I run the test using Edge 107 on Windows 11 there is no error.

If you think that further investigations and / or changes need to be made, then please transfer to a new open issue, so we can focus on this specifically. At least your initial findings are very encouraging!

**Comment by Ein-Tim** [comment]
@MikeMcC399 I think I can live with both of these things, as I can manually confirm that the app badges work, and they are rarely changed. So I won't open a new issue. Thanks for your support!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

If you are comfortable with what you have, then you don't need to try the following, but theoretically one possibility could be:

Execute
`npm start`
in one terminal window, then in a separate terminal window execute
`npx cypress run --headed --browser safari`

**Comment by Ein-Tim** [comment]
@MikeMcC399 Thanks, I will try that!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Sorry, I should have checked, but in fact Safari is only supported experimentally in Cypress.

See https://docs.cypress.io/guides/guides/launching-browsers

**Comment by Ein-Tim** [comment]
@MikeMcC399 No problem! Maybe I will open an enhancement request to add support for this experimental feature to the cwa-website repo, but I will have to study the documentation first.

**Comment by larswmh** [comment]
@MikeMcC399 

> I wonder if that is the same for @larswmh

Still failing at gulp-imagemin unfortunately. Running `npm run build` on master results in:
```
[16:35:13] TypeError in plugin "gulp-imagemin"
Message:
    function_ is not a function
Details:
    fileName: /Users/lars/Documents/GitHub/cwa-website/src/assets/img/App_Store_Badge_DE.svg
    domainEmitter: [object Object]
    domainThrown: false
```

**Comment by larswmh** [comment]
@MikeMcC399 

> Would you like to open a new issue here to track?

Thanks for your findings! I've created a separate issue for this at https://github.com/corona-warn-app/cwa-website/issues/3202

**Comment by MikeMcC399** [comment]
- Issue #3202 is now resolved and https://github.com/corona-warn-app/cwa-website/blob/master/README.md#requirements has had the following text added to it:

"In case you use a Mac computer with Apple Silicon, make sure that [Rosetta](https://support.apple.com/en-us/HT211861) is installed."

macOs users with M1 ARM hardware should be able to use:

`npm test`

to build and test the cwa-website now.
