### ISSUE TITLE
Github button looks like a download button.

### ISSUE THREAD

**Issue by Incognito** [corona-warn-app/cwa-website#311]
## Where to find the issue
The main page.

## Describe the issue
There's a big "github" call to action on the main page. This is only meaningful to a very small percentage of the population: those those who program, or are very close to programming jobs.

For everyone else in the world it looks exactly like the "download now" button they've been trained to click on on every website with this layout. Regular folks don't expect to see the source code, especially when they aren't told it will be the source code.

People don't read text on websites.

![bitmap](https://user-images.githubusercontent.com/379322/88166691-f4b46a80-cc17-11ea-846d-df3392d7ce43.png)

What would my grandparents think?

## Suggested change
Replace it with a link to download and install the app, or make it more obvious this isn't the link that 99.9% of people want. I wouldn't even link to it, I would just say "The code is on github" and keep a link to github in the footer.

Improving the visits-to-downloads conversion rate here could actually save a life.

**Comment by tkowark** [comment]
The main purpose of the is to promote the open source project. To this end, having the GitHub link front and center just makes sense.
 
In the meantime, this might have changed and we probably have many visitors who might not even be interested in going to GitHub in the first place. For them, finding the app download link (for their respective OS) is more important and catered to through the banner on the bottom of the page. 

Other visitors will probably just go directly to the FAQ page or blog and never even see the home page. And when searching for Corona-Warn-App, this page is by far not the first target on Google.

We still want as many people as possible to engage on GitHub by letting us know about their problems, suggesting new features, etc. Hence, I will leave the button as-is for the time being.

If anybody has a good idea of how to balance these two aspects, we're more than happy to have a look at a respective PR.

**Comment by MikeMcC399** [comment]
@Incognito 

Several changes have been made since this issue was opened almost two years ago.

I don't see the position and wording of the GitHub logo to be confusing any more and the download information now pops up to be displayed prominently.

I suggest to close this issue as resolved.

The screenshots below display what https://www.coronawarn.app/en/ and https://www.coronawarn.app/de/ now show related to GitHub and download buttons:

![image](https://user-images.githubusercontent.com/66998419/158058091-adce7d21-94a6-4f67-afd8-ce3bb0020343.png)

**Comment by Incognito** [comment]
Thank you
