### ISSUE TITLE
Missing 2.27 screenshots

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#3110]
## Where to find the issue
 [coronawarn.app/en/screenshots](https://www.coronawarn.app/en/screenshots/)
 
 ## Describe the issue
 There is no screenshot information for the current version of the app 2.27, released on Sep 28, 2022 (see https://www.coronawarn.app/en/blog/2022-09-28-cwa-2-27/).
 
 ## Steps to reproduce
 Go to https://www.coronawarn.app/en/screenshots Look for "Version 2.27" in version drop-down list. Note that it is missing.
 
 ## Suggestion
 * Either add a message in the 2.25 screenshot description to say that the screenshots also apply to version 2.26 & 2.27 or
 * add a new screenshot page for 2.27

## Credits
I took over the issue description from @MikeMcC399's issue #3094. 

---
Internal Tracking ID: [EXPOSUREAPP-14065](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14065)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> There is no screenshot information for the current version of the app 2.26, released on Sep 28, 2022

You mean 2.27.

**Comment by Ein-Tim** [comment]
@MikeMcC399

Thanks, fixed.

**Comment by Ein-Tim** [comment]
@dsarkar You added the "Fix 2.27" label but nothing changed with the release of version 2.27. The screenshots are still missing.

**Comment by dsarkar** [comment]
@Ein-Tim We are going to provide screenshots. I added the label, since it is related to 2.27 although delivered late. Idea is that it might be easier to find PR/issue related to a release.

**Comment by Ein-Tim** [comment]
- This issue has been fixed with https://github.com/corona-warn-app/cwa-website/pull/3131.
