### ISSUE TITLE
FAQ #admission_policy exclamation mark formatting fails

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3111]
## Where to find the issue

- https://www.coronawarn.app/en/faq/results/#admission_policy "General information about the status proof display"
- https://www.coronawarn.app/de/faq/results/#admission_policy "Grundlegendes zur Anzeige des Status-Nachweises"

## Describe the issue

See https://github.com/corona-warn-app/cwa-website/pull/3106#discussion_r983313000

![image](https://user-images.githubusercontent.com/66998419/192998568-d7c6cded-3518-41fd-8fe0-97698b7d8775.png)

The red exclamation mark does not work on the production server:

`https://www.coronawarn.app/en/faq/results/#admission_policy`
`Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' *.coronawarn.app". Either the 'unsafe-inline' keyword, a hash ('sha256-4mA4kAfnM5r+JCidOfyFBsKJX9I1Y9++qVctls/q/XI='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`

![image](https://user-images.githubusercontent.com/66998419/192998824-820454e5-522c-4996-ae5a-a6b01b687e4f.png)

The sentence looks very strange, with an exclamation mark at the beginning of the sentence, no space between the exclamation mark and the first letter "T" and no period "." at the end of the sentence.

## Other issues

The date in the English text https://www.coronawarn.app/en/faq/results/#admission_policy is formatted using German formatting. "September 28, 2022" would be better. Also the previous date of update "Updated on March 30, 2022: " could be removed. There is no such update date shown in the German FAQ entry https://www.coronawarn.app/de/faq/results/#admission_policy.

---
Internal Tracking ID: [EXPOSUREAPP-14046](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14046)

**Comment by dsarkar** [comment]
Hi @MikeMcC399,

Thanks for reporting: PR https://github.com/corona-warn-app/cwa-website/pull/3113.
