### ISSUE TITLE
Add FAQ entry reg. vaccination protection for children under 12

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#3112]
## Enhancement description

Please add a FAQ entry explaining why children below the age of 12 with two vaccinations don't count as fully vaccinated anymore, as of 01.10.22.
The STIKO only recommends 2 vaccinations for healthy children, so many parents believe it is a mistake that the app shows that children under 12 also need a booster to continue to count as fully vaccinated. See e.g. this GitHub Issue: https://github.com/corona-warn-app/cwa-wishlist/issues/862

## Problem and motivation
Make it clearer for the parents to understand why their children need a booster.

---
Internal Tracking ID: [EXPOSUREAPP-14041](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14041)
Internal Tracking ID: [EXPOSUREAPP-14164](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14164)

**Comment by Ein-Tim** [comment]
Proof that this is a relevant FAQ topic:
- https://twitter.com/paulinepauline/status/1576095586604191751?s=46&t=PIC2asSNKsOAsrUrNZLihQ
- https://twitter.com/jenswiese/status/1576097524263583744?s=46&t=PIC2asSNKsOAsrUrNZLihQ
- https://twitter.com/rrehtla1/status/1576098408074354688?s=46&t=PIC2asSNKsOAsrUrNZLihQ
- https://twitter.com/kruegerol/status/1576100584406777856?s=46&t=PIC2asSNKsOAsrUrNZLihQ
- https://twitter.com/muc_neko/status/1576100777570930689?s=46&t=PIC2asSNKsOAsrUrNZLihQ
- https://twitter.com/berichtenswert/status/1576102620351328257?s=46&t=PIC2asSNKsOAsrUrNZLih
- https://twitter.com/elbeelfe/status/1576109978959507456?s=46&t=PIC2asSNKsOAsrUrNZLihQ
-

**Comment by Ein-Tim** [comment]
The problem with FAQ entries is always: When they are added, people don't ask the question anymore. So I suggest to either add an article very soon or don't do it (-:

**Comment by dsarkar** [comment]
@Ein-Tim FYI, this topic has been raised internally and there is awareness about this issue, however, we have to agree with other stakeholders on the content of possible FAQ text. Thanks for opening this issue.

**Comment by GisoSchroederSAP** [comment]
All,
thanks for the comments and for the activity here.

The difference between the legislation and the STIKO recommendation is known to all parties involved. The BMG was already informed in the spring season. After legal evaluation the authorities released a result stating that 

- The Infection protection Act (IfSG) is the one and only source of truth regarding the rules to be considered in the CWA.
- Regarding minors/children, for cross-border travel the digital COVID certificate will be accepted for an unlimited period of time once the vaccination series is completed.
- The IfSG does not differentiate between children and adults when issuing or mapping individual vaccinations in the digital COVID certificate.

Subsequently, the CWA does not currently differentiate between minors/children and adults based on age. The app may indicate and "incomplete vaccination status" and might even suggest the possibility of a booster vaccination. 

To be clear: We are allowed to refer to the BMG's evaluation result for support and community cases, but we do not have official permission to publish the full explanation in the public FAQ.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

Does this mean that a FAQ entry simply stating that the IFSG does not differentiate between ages can't be published? The reason why no differentiation is done is not important for the CWA FAQs IMO.

**Comment by GisoSchroederSAP** [comment]
If that would help, we can take this in consideration. 
However, IMHO most of the users will not "arrive" at that FAQ article, but will shoot their statement/question immediately after they recognize the kids are treated no longer as "fully vaccinated" anymore.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP Right, as I stated above, it's too late now probably. You could consider extending the BNR, however. 

I leave it you whether to close or leave this issue open.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

See also https://github.com/corona-warn-app/cwa-app-ios/issues/4826.

Adding a FAQ entry would still make sense in my opinion.

**Comment by GisoSchroederSAP** [comment]
The topic is still not solved, but in heavy discussion with BMG; we expect a statement about the _way forward_ from there _soon_ . Until then, no additional public communication is permitted, sorry.
I keep ou posted about the progress.

**Comment by dsarkar** [comment]
@Ein-Tim FYI https://github.com/corona-warn-app/cwa-website/pull/3156
