### ISSUE TITLE
Broken Cypress test eventRegistration.js

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3115]
## Where to find the issue

[eventRegistration.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/eventRegistration.js)

## Describe the issue

The Cypress test [eventRegistration.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/eventRegistration.js) fails due to text changes made in PR https://github.com/corona-warn-app/cwa-website/pull/3093

## Suggested change

The Cypress test checks for the exact text match from:

https://github.com/corona-warn-app/cwa-website/blob/218de1eb4c2d4437a8da001182126ee529b57a27/cypress/fixtures/copy/stringEn.json#L4

and from:

https://github.com/corona-warn-app/cwa-website/blob/218de1eb4c2d4437a8da001182126ee529b57a27/cypress/fixtures/copy/stringDe.json#L4

These texts need to be changed.

---
Internal Tracking ID: [EXPOSUREAPP-14072](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14072)

**Comment by chrisenitan** [comment]
I want to update this but before then, perhaps we could 
- replace string assertions with DOM element assertion OR
- reduce the length of assertions to something stable (if we know which part of that statement would be stable)

Any suggestions?

**Comment by Ein-Tim** [comment]
I will provide a PR simply fixing this issue by aligning the statements in about an hour or so. Any further discussion about how to improve the test should be made on e it's fixed, I think.

**Comment by Ein-Tim** [comment]
I will provide a PR simply fixing this issue by aligning the statements in about an hour or so. Any further discussion about how to improve the test should be made on e it's fixed, I think.

**Comment by Ein-Tim** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/3116 provided.

**Comment by dsarkar** [comment]
Hi @MikeMcC399, @chrisenitan,

we have merged @Ein-Tim 's PR for the moment, we might think of a better solution at some point!

Thanks everybody!
