### ISSUE TITLE
Cypress test fails redirect check

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3146]
## Where to find the issue

[cypress/fixtures/appToWebLinks.json](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/fixtures/appToWebLinks.json)

## Describe the issue

Due to the FAQ link redirection introduced by PR https://github.com/corona-warn-app/cwa-website/pull/3138, the Cypress test [cypress/integration/app_to_web.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/integration/app_to_web.js) fails. This in turn causes the workflow [.github/workflows/cypress-test-prod.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/cypress-test-prod.yml) to fail.

FAQ `#vac_cert_booster` originally redirected to `#vac_cert`
PR https://github.com/corona-warn-app/cwa-website/pull/3138 changed it to redirect to `#vac_booster_basics` instead.

## Steps to reproduce

Execute
`npm run test:open`
select `app_to_web.js`

Note test failure:

`Timed out retrying after 4000ms: expected '#vac_booster_basics' to equal '#vac_cert'`

See also Action log https://github.com/corona-warn-app/cwa-website/actions/runs/3263826648.

## Suggestion

Modify the redirect check for `#vac_cert_booster` to check that it redirects to `#vac_booster_basics` by changing the test data in [cypress/fixtures/appToWebLinks.json](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/fixtures/appToWebLinks.json)

---
Internal Tracking ID: [EXPOSUREAPP-14156](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14156)

**Comment by MikeMcC399** [comment]
I will submit a PR to correct this issue.

**Comment by MikeMcC399** [comment]
- PR #3147 is submitted to resolve this issue

**Comment by dsarkar** [comment]
Good Morning @MikeMcC399, 
Thanks for reporting and providing a fix.
