### ISSUE TITLE
Action cypress-test-prod.yml triggers `set-output` deprecation warning

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3149]
## Where to find the issue

https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/cypress-test-prod.yml with logs in 
https://github.com/corona-warn-app/cwa-website/actions/workflows/cypress-test-prod.yml

## Describe the issue

Since the daily run https://github.com/corona-warn-app/cwa-website/actions/runs/3233412749 of the workflow [actions/workflows/cypress-test-prod.yml](https://github.com/corona-warn-app/cwa-website/actions/workflows/cypress-test-prod.yml) on Oct 12, 2022 a GitHub warning is shown each day:

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

## Steps to reproduce

View the action log of [actions/workflows/cypress-test-prod.yml](https://github.com/corona-warn-app/cwa-website/actions/workflows/cypress-test-prod.yml).

## Analysis

The workflow [.github/workflows/cypress-test-prod.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/cypress-test-prod.yml) uses:

- actions/checkout@v3
- cypress-io/github-action@v4 from https://github.com/cypress-io/github-action

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ says:

"Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions."

`cypress-io/github-action` v4.2.0 [package.json](https://github.com/cypress-io/github-action/blob/30008f1458a5a2c97054bfe118fe33d75976c482/package.json#L35) is still using an older version which is less than the required v1.10.0 of [actions/core](https://github.com/actions/toolkit/tree/main/packages/core):
    `"@actions/core": "1.8.2"`
so the maintainers of https://github.com/cypress-io/github-action need to update this dependency.

## Suggestion

Watch for solution in https://github.com/cypress-io/github-action/releases.

It seems that the warning is related to logging results in the Cypress Dashboard, which is not used in https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/cypress-test-prod.yml, however according to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ the related commands are planned to be disabled by GitHub in future, which in turn may ultimately cause the workflow to fail.

---
Internal Tracking ID: [EXPOSUREAPP-14160](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14160)

**Comment by brianebeling** [comment]
Hey @MikeMcC399! Thanks for letting us know, I also noticed it when looking into the pipelines recently. The issue has time until roughly the 31st May 2023 as functionality currently is unaffected. When I have some downtime I will look into it though.

**Comment by MikeMcC399** [comment]
@brianebeling 

Thanks for posting the date "31st May 2023", so there is no urgency here.

The warning message "The set-output command is deprecated and will be disabled soon." was less explicit about the schedule!

It may be worth updating to `cypress-io/github-action@v4` sometime in the near future, even if there is no immediate benefit.

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/3197 took the opportunity to update to using the latest (v4) version of https://github.com/cypress-io/github-action. The best outcome now will be that the maintainers of the action will update it, and no code changes in the workflow of cwa-website will be necessary.
- Continue to monitor.

**Comment by MikeMcC399** [comment]
This issue is resolved. Today's run of [.github/workflows/cypress-test-prod.yml ](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/cypress-test-prod.yml) with [action log](https://github.com/corona-warn-app/cwa-website/actions/runs/3572538159/jobs/6005540245) showed no deprecation message from https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

The resolution came from the new release [cypress-io/github-action v4.2.2](https://github.com/cypress-io/github-action/releases/tag/v4.2.2) yesterday.

No change to [.github/workflows/cypress-test-prod.yml ](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/cypress-test-prod.yml) on cwa-website was necessary since the fix was put into a minor version update of [cypress-io/github-action](https://github.com/cypress-io/github-action/) and the cwa-website workflow had already been updated to use the v4 (latest) version of [cypress-io/github-action](https://github.com/cypress-io/github-action/) in https://github.com/corona-warn-app/cwa-website/blob/c45d265f8206bc1d252a421c0c53cb489b1b8069/.github/workflows/cypress-test-prod.yml#L20-L27
