### ISSUE TITLE
Multiple issues for links in FAQ #mask_rules

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3150]
## Where to find the issue

Links in 
- https://www.coronawarn.app/en/faq/results/#mask_rules "Mask Feature"
- https://www.coronawarn.app/de/faq/results/#mask_rules "Maskenpflicht / Maskenpflichtbefreiung"

specifically:

- https://www.bundesregierung.de/breg-de/themen/coronavirus/infektionsschutzgesetz-2068856
- https://www.bundesgesundheitsministerium.de/coronavirus.html#c23063
- [https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#\_\_bgbl\_\_%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187](https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187)

### Link relevance

1. The content of the link https://www.bundesgesundheitsministerium.de/coronavirus.html#c23063 has changed since the [#mask_rules](https://www.coronawarn.app/en/faq/results/#mask_rules) FAQ was published on Sep 23, 2022. https://web.archive.org/web/20220925053332/https://www.bundesgesundheitsministerium.de/coronavirus.html#c23063 shows that the contents were previously relevant, however this link contains dynamic content and today the link points to "Aktuelles / 14.10.2022 / Lauterbach startet Corona-Kampagne „Ich schütze mich“" which is about ensuring vaccination protection, not primarily about mask wearing. The link no longer helps to understand the FAQ article. 

2. [https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#\_\_bgbl\_\_%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187](https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187) points to "Gesetz zur Stärkung des Schutzes der Bevölkerung und insbesondere vulnerabler Personengruppen vor COVID-19". Most of the text concerns changes to the Infektionsschutzgesetz (IfSG), so citing this law is redundant to the link https://www.bundesregierung.de/breg-de/themen/coronavirus/infektionsschutzgesetz-2068856 which already covers the changes to IfSG relating to masks in a readable way. The actual text changes are covered in IfSG [§ 28a](https://www.gesetze-im-internet.de/ifsg/__28a.html), [§ 28b](https://www.gesetze-im-internet.de/ifsg/__28b.html) & [§ 28c](https://www.gesetze-im-internet.de/ifsg/__28c.html). The link to [Bundesgesetzblatt Teil I, 2022, Nr. 32 vom 16.09.2022 Seite 1454](https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187) is factually correct, however it is very unhelpful for a lay-reader, since the relevant information about mask wearing is buried in other irrelevant legal text.

### Link presentation

1. Other lists of links on the FAQ page are presented as an HTML unordered list, so that a bullet point shows before each entry. This has not been done for this list of links, instead the links are separated only by a new line `<br>`.
   
2. The page URLs are used as the link description. Link best practice in https://web.dev/link-text/#link-text-best-practices says:<br><br>"Don't use the page's URL as the link description unless you have a good reason to do so, such as referencing a site's new address."

### Link security

Each of the links is using the `target='_blank'` attribute without specifying a `rel` attribute.

[Links on FAQ pages](https://github.com/corona-warn-app/cwa-website/blob/master/docs/CHANGE_WEBSITE_CONTENT.md#links-on-faq-pages) says:

"External links should use the HTML hyperlink attribute `rel='noopener noreferrer'` to avoid a cross-domain security issue in older browsers when the link also contains `target='_blank'`."

## Suggestion

Review the links.

Possibly the links:
- https://www.bundesgesundheitsministerium.de/coronavirus.html#c23063
- [https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#\_\_bgbl\_\_%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187](https://www.bgbl.de/xaver/bgbl/start.xav?startbk=Bundesanzeiger_BGBl&jumpTo=bgbl122s1454.pdf#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl122s1454.pdf%27%5D__1663765059187)

could be removed without loss of understanding for the FAQ article.

- For https://www.bundesregierung.de/breg-de/themen/coronavirus/infektionsschutzgesetz-2068856 
change the link description to "Corona-Schutzmaßnahmen – was ab Oktober 2022 gilt", add `rel='noopener noreferrer'`

Similarly if the other links are kept then add an appropriate link description and the `rel` attribute.

If multiple links are kept, then change the presentation to an unordered list.

---
Internal Tracking ID: [EXPOSUREAPP-14165](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14165)

**Comment by MikeMcC399** [comment]
There may be different opinions about what changes should be made, so in the first step I will leave it to the Open Source Team to respond.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for opening this issue; we will have a look at this. Internal Tracking ID: [EXPOSUREAPP-14165](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14165)

**Comment by MikeMcC399** [comment]
- PR #3157 is addressing this issue.
