### ISSUE TITLE
Add Cypress test for FAQ link conventions

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3158]
## Current Implementation

The Cypress test suite does not test for FAQ links abiding by the conventions specified in [docs/CHANGE_WEBSITE_CONTENT: "Links on FAQ pages"](https://github.com/corona-warn-app/cwa-website/blob/master/docs/CHANGE_WEBSITE_CONTENT.md#links-on-faq-pages).

## Related issues / pull requests

- https://github.com/corona-warn-app/cwa-website/pull/3030
- https://github.com/corona-warn-app/cwa-website/issues/3031
- https://github.com/corona-warn-app/cwa-website/pull/3032
- https://github.com/corona-warn-app/cwa-website/issues/3034
- https://github.com/corona-warn-app/cwa-website/pull/3035

## Suggested Enhancement

Implement a Cypress test which checks for conformance with the conventions specified in [docs/CHANGE_WEBSITE_CONTENT: "Links on FAQ pages"](https://github.com/corona-warn-app/cwa-website/blob/master/docs/CHANGE_WEBSITE_CONTENT.md#links-on-faq-pages):

---

The following conventions should be followed for links in the FAQ sources [/src/data/faq.json](https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq.json) and [/src/data/faq_de.json](https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq_de.json):

- All internal and external links on the FAQ pages should use the HTML hyperlink attribute `target='_blank'` to open in a new frame. This provides a consistent user experience and works around an issue with the browser back arrow button in the FAQ Glossary.
- External links should use the HTML hyperlink attribute `rel='noopener noreferrer'` to avoid a cross-domain security issue in older browsers when the link also contains `target='_blank'`.
- Internal links should **not** contain the attribute `rel='noopener noreferrer'`. There is no security issue for internal links.

Examples:

- External link: `<a href='https://www.digitaler-impfnachweis-app.de/en/covpasscheck-app/' target='_blank' rel='noopener noreferrer'>Check EU COVID certificates directly via app</a>`
- Internal link: `<a href='#test_cert' target='_blank'>Test Certificate</a>`

---

## Expected Benefits

An automatically executed Cypress test helps to ensure consistency in the way that FAQ links are formed. This enhances both the user experience and security.

---
Internal Tracking ID: [EXPOSUREAPP-14213](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14213)

**Comment by MikeMcC399** [comment]
I already prepared this Cypress test in July 2022 before the Open Source Team / Community Management was stopped on August 4, 2022, and I then forgot about it until I noticed some link issues and Community Management was reinstated.

If you would like me to submit this test as a PR, please let me know.

- The test will fail until PR https://github.com/corona-warn-app/cwa-website/pull/3157 is merged. The PR fixes incorrect link attributes.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the suggestion, very much appreciated. Indeed, we would like to review your PR.

**Comment by MikeMcC399** [comment]
@dsarkar 

> Thanks for the suggestion, very much appreciated. Indeed, we would like to review your PR.

- Thanks in return for your interest! I have submitted PR #3159 to implement this enhancement.

I noticed whilst I was testing this PR that the build and deploy scripts are successful, however they now include deprecation warnings for node 12, so I will submit this as issues.

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/3159 is now merged, so this enhancement request has been fulfilled.
