### ISSUE TITLE
Deploy workflow shows deprecation notice

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3162]
## Where to find the issue

https://github.com/corona-warn-app/cwa-website/actions/workflows/deploy-master.yml

## Describe the issue

https://github.com/corona-warn-app/cwa-website/actions/workflows/deploy-master.yml shows the deprecation notice:

"prod

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, actions/setup-node, actions/checkout"

## Steps to reproduce

View logs in https://github.com/corona-warn-app/cwa-website/actions/workflows/deploy-master.yml

## Suggestion

[.github/workflows/deploy-master.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/deploy-master.yml) uses:

- `actions/checkout@v2`
- `actions/setup-node@v2`

Update

- `actions/checkout@v2` to `actions/checkout@v3` (see https://github.com/actions/checkout/releases/tag/v3.0.0)
- `actions/setup-node@v2` to `actions/setup-node@v3` (see https://github.com/actions/setup-node/releases/tag/v3.0.0)

---
Internal Tracking ID: [EXPOSUREAPP-14217](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14217)

**Comment by MikeMcC399** [comment]
Since I cannot test the [deploy](https://github.com/corona-warn-app/cwa-website/actions/workflows/deploy-master.yml) workflow, I don't want to submit a PR for this issue and I leave it to the Open Source Team to review and change if necessary.

The necessary changes are quite simple and they are the same as for the build workflow (see https://github.com/corona-warn-app/cwa-website/pull/3161).

**Comment by dsarkar** [comment]
@MikeMcC399 Great! https://github.com/corona-warn-app/cwa-website/actions/runs/3298074699

**Comment by MikeMcC399** [comment]
@dsarkar / @brifemu 

Thanks for processing the suggestion! The workflow log @dsarkar linked to shows success with no deprecation warning.
