### ISSUE TITLE
[R 3.0] Release updates

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#3175]
- [ ] Blog
  - [ ] **EN** https://www.coronawarn.app/en/blog/2023-01-18-cwa-3-0/
  - [ ] **DE** https://www.coronawarn.app/de/blog/2023-01-18-cwa-3-0/ 
- [x] Screenshots https://github.com/corona-warn-app/cwa-website/pull/3298
  - [x] **EN** https://www.coronawarn.app/en/screenshots/
  - [x] **DE** https://www.coronawarn.app/de/screenshots/ 
  - [x] new screenshots
  - [x] new release introduction 
  - [x] release date 
- [ ] Privacy notice https://github.com/corona-warn-app/cwa-website/pull/3173
  - [ ] **EN** https://www.coronawarn.app/en/privacy/
  - [ ] **DE** https://www.coronawarn.app/de/privacy/ 
  - [ ] add new docs (3)
  - [ ] release date 
- [x] FAQ/Glossary
  - [ ] FAQ updates/new articles ? 
  - [ ] Update FAQ article "Statistics"
  https://github.com/corona-warn-app/cwa-website/pull/3317
    - [ ] [In-App statistics](https://www.coronawarn.app/en/faq/results/#further_details)
    - [ ] [In-App Statistiken](https://www.coronawarn.app/de/faq/results/#further_details) 
  - [x] Update FAQ articles mentioning "TAN-Hotline/Verification-Hotline"
    - [ ] [Was mache ich, wenn ich mehrere PCR-Test-QR-Codes habe?](https://www.coronawarn.app/de/faq/results/#QRcodes)
    - [ ] [What to do with several PCR-Test QR codes?](https://www.coronawarn.app/en/faq/results/#QRcodes)
    - [ ] [Wie teile ich ein positives Testergebnis auf mehreren Geräten?](https://www.coronawarn.app/de/faq/results/#test_multiple_devices)    
    - [ ] [How do I share a positive test result on multiple devices?](https://www.coronawarn.app/en/faq/results/#test_multiple_devices)
    - [ ] [Kann ich positive Testergebnisse aus anderen Ländern eingeben?](https://www.coronawarn.app/de/faq/results/#test_in_other_country)
    - [ ] [Can I enter positive test results from other countries?](https://www.coronawarn.app/en/faq/results/#test_in_other_country)
    - [ ] [Wer hilft bei Fragen zur Corona-Warn-App?](https://www.coronawarn.app/de/faq/results/#who_can_help)
    - [ ] [Who can help with questions regarding the Corona-Warn-App?](https://www.coronawarn.app/en/faq/results/#who_can_help)
    - [ ] [So erreichen Sie uns](https://www.coronawarn.app/de/faq/results/#international_phone_numbers)
    - [ ] [How to reach us](https://www.coronawarn.app/en/faq/results/#international_phone_numbers)
    - [ ] [Ich habe einen PCR-Test-QR-Code eingescannt, aber das Testergebnis konnte über Tage nicht abgerufen werden.](https://www.coronawarn.app/de/faq/results/#qr_test)
    - [ ] [I have scanned a PCR-Test QR code, but the test result could not be retrieved for days.](https://www.coronawarn.app/en/faq/results/#qr_test)
    - [ ] [Ich bin gehörlos oder schwerhörig. Telefonieren ist problematisch für mich. Worauf muss ich bei der Nutzung der App achten?](https://www.coronawarn.app/de/faq/results/#hearing_impaired)
    - [ ] [I'm deaf or hard of hearing, so making phone calls is a problem for me. What do I have to keep in mind when I'm using the app?](https://www.coronawarn.app/en/faq/results/#hearing_impaired)
    - [ ] [Exposure Notification Express (ENE)](https://www.coronawarn.app/de/faq/results/#ene)
    - [ ] [Exposure Notification Express (ENE)](https://www.coronawarn.app/en/faq/results/#ene)
    - [ ] [Ich wurde positiv getestet. Warum erhält eine Person im gleichen Haushalt keine Risikowarnung?](https://www.coronawarn.app/de/faq/results/#pos_test_no_risk_encounter)
    - [ ] [I tested positive. Why does a person in the same household not receive a risk warning?](https://www.coronawarn.app/en/faq/results/#pos_test_no_risk_encounter)
    - [ ] [Rote Karte? So geht es zum Corona Test](https://www.coronawarn.app/de/faq/results/#red_card_how_to_test)
    - [ ] [Red Card? How to go through Corona testing](https://www.coronawarn.app/en/faq/results/#red_card_how_to_test)
    - [ ] #3328
    - [ ] [Can I be identified as COVID-19-positive by network traffic monitoring?](https://www.coronawarn.app/en/faq/results/#traffic_monitoring)
    - [ ] [Wie ist gewährleistet, dass ich bei der Nutzung der Corona-Warn-App anonym bleibe?](https://www.coronawarn.app/de/faq/results/#anonymous)
    - [ ] [How do you guarantee that I remain anonymous when using the Corona-Warn-App?](https://www.coronawarn.app/en/faq/results/#anonymous)
    - [ ] [Kann ich mein positives Antigen-Schnelltest- oder PCR-Schnelltest-Ergebnis über die TAN-Hotline teilen?](https://www.coronawarn.app/de/faq/results/#rat_tan_hotline)
    - [ ] [Can I share my positive rapid antigen test or rapid PCR test result via the TAN hotline?](https://www.coronawarn.app/en/faq/results/#rat_tan_hotline)
    - [ ] [TAN-Verfahren](https://www.coronawarn.app/de/faq/results/#tan_procedure)
    - [ ] [TAN Procedure](https://www.coronawarn.app/en/faq/results/#tan_procedure)
    - [ ] [Glossar: TAN](https://www.coronawarn.app/de/faq/results/#glossary_tan)
    - [ ] [Glossary: TAN](https://www.coronawarn.app/en/faq/results/#glossary_tan)
  - [x] Update FAQ articles mentioning "In Vertretung warnen" 
  https://github.com/corona-warn-app/cwa-website/pull/3312
    - [ ] [Wie kann ich in Vertretung warnen?](https://www.coronawarn.app/de/faq/results/#warn_for_others)
    - [ ] [How can I warn for others?](https://www.coronawarn.app/en/faq/results/#warn_for_others)
    - [ ] [Kann ich die Stellvertreter-Funktion nutzen, egal welchen QR-Code ich eingescannt habe?](https://www.coronawarn.app/de/faq/results/#check_in_luca_warn_for_others)
    - [ ] [Can I warn for others regardless of which QR code I have scanned?](https://www.coronawarn.app/en/faq/results/#check_in_luca_warn_for_others)
   - [x] Update/New FAQ articles in regarding the "Introduction of SRS for reporting infections"
      - https://github.com/corona-warn-app/cwa-website/pull/3322
      -  [ ] [Wie kann ich andere Nutzer warnen, wenn ich positiv getestet worden bin?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_how_to)
      - [ ] [How can I warn other users if I have tested positive?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_how_to)
      - [ ] [Fehlermeldung "Andere warnen nicht möglich": Warum kann ich momentan andere nicht warnen?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_error)
      - [ ] [Error message "You Cannot Warn Others": Why can't I warn others at the moment?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_error)
      - [ ] [Werden trotz der neuen Funktion die Ergebnisse auch weiterhin digital in die App übertragen?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_digital_result)
      - [ ] [Will the results still be transferred digitally to the app despite the new function?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_digital_result)
      - [ ] [Ich habe mein positives Ergebnis nicht über die App erhalten – kann ich meine Kontakte trotzdem warnen?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_external_result)
      - [ ] [I did not receive my positive result via the app - can I still warn my contacts?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_external_result)
      - [ ] [Muss ich trotzdem die Hotline anrufen?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_hotline)
      - [ ] [Do I still have to call the hotline?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_hotline)
      - [ ] [Muss ich auf Version 3.0 umsteigen, oder läuft meine aktuelle Version der CWA weiter?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_version)
      - [ ] [Do I need to upgrade to version 3.0, or will my current version of CWA continue to run?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_version)
      - [ ] [Muss ich einen PCR-Test machen, nachdem ich mit einem positiven Selbsttest gewarnt habe?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_pcr_after_self_test)
      - [ ] [Do I have to do a PCR test after I have warned with a positive self-test?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_pcr_after_self_test)
      - [ ] [Was passiert, wenn ich nach einem positiven Selbsttest noch einmal mit einem positiven PCR-Test warne? Geht das überhaupt?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_warn_twice)
      - [ ] [What happens if I warn again with a positive PCR test after a positive self-test? Is that even possible?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_warn_twice)
      - [ ] [Einige Tage nach dem letzten positiven Test bin ich beim Selbsttest noch immer positiv. Soll ich nochmal warnen?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_still_positive)
      - [ ] [A few days after the last positive test, I am still positive on the self-test. Should I warn again?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_still_positive)
      - [ ] [Muss ich ein Foto meines Tests machen, um den Test nachzuweisen?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_photo)
      - [ ] [Do I need to take a picture of my test to prove the test?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_photo)
      - [ ] [Wie oft kann ich ohne TAN warnen?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_how_often)
      - [ ] [How often can I warn without TAN?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_how_often)
      - [ ] [Kann ich in Vertretung von Familienmitgliedern warnen, z. B. für mein infiziertes Kind?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_family)
      - [ ] [Can I warn on behalf of family members, such as my infected child?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_family)
      - [ ] [Ich war bei einer Veranstaltung per QR-Code eingecheckt. Kann ich die Gäste des Events mit der Funktion warnen? Bleibe ich dabei anonym?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_event)
      - [ ] [I was checked in to an event via QR code. Can I warn the guests of the event with the function? Will I remain anonymous in the process?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_event)
      - [ ] [Muss ich nach einem positiven (Selbst-)Test in Isolation?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_isolation)
      - [ ] [Do I have to go into isolation after a positive (self-)test?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_isolation)
      - [ ] [Wenn ich wieder einen negativen Schnelltest habe, kann ich die Isolation dann beenden?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_negative)
      - [ ] [If I have another negative rapid test, can I end the isolation?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_negative)
      - [ ] [Wird das positive Testergebnis bzw. das Warnen in meinem Kontakt-Tagebuch vermerkt?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_contact_journal)
      - [ ] [Will the positive test result or warning be noted in my contact journal?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_contact_journal)
      - [ ] [Kann ich für einen Selbsttest ein offizielles digitales Zertifikat erhalten?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_self_test_certificate)
      - [ ] [Can I get an official digital certificate for a self-test?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_self_test_certificate)
      - [ ] [Kann ich einen registrierten positiven Testbefund als Krankschreibung nutzen?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_sickness_certificate)
      - [ ] [Can I use a registered positive test result as a sickness certificate?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_sickness_certificate)
      - [ ] [Wie lange bleibt der Test in der App zu sehen?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_in_app_display)
      - [ ] [How long will the test remain visible in the app?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_in_app_display)
      - [ ] [Stoppt nach dem Teilen des positiven Ergebnisses meine Risiko-Ermittlung?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_risk_assessment)
      - [ ] [After sharing the positive result, does my risk assessment stop?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_risk_assessment)
      - [ ] [Unterscheidet die Risikoberechnung bei einer Warnung auf meinem Smartphone je nach Test-Art, mit der gewarnt wurde?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_risk_assessment_different)
      - [ ] [Does the risk calculation for a warning on my smartphone differ depending on the test type used to warn?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_risk_assessment_different)
      - [ ] [Können Warnungen verschiedener Testarten unterschieden werden?](https://www.coronawarn.app/de/faq/results/#warn_without_tan_differentiate_warning)
      - [ ] [Can warnings of different test types be differentiated?](https://www.coronawarn.app/en/faq/results/#warn_without_tan_differentiate_warning)
- [ ] appToWebLinks.json:     
  - [x] "appVersionLast": "3.0" https://github.com/corona-warn-app/cwa-website/pull/3172/commits/03c2093b0678147a3732570ee1d2c202853bcf52 https://github.com/corona-warn-app/cwa-website/commit/64e690e52532f2a18ba5a320255fe94463d0f499
  - [x] new link "#warn_without_tan" https://github.com/corona-warn-app/cwa-website/pull/3172/commits/27e96cc7df5cb0b48fbff309c7af9d1a22d83a59
- [ ] Sitemap DE https://github.com/corona-warn-app/cwa-website/pull/3172/commits/baef16b4cacd2b469b0ba5ae444f30caae8b702c / EN https://github.com/corona-warn-app/cwa-website/pull/3172/commits/7df8cfb65bc6c97dc3ff74ba2711a2a67b81aa73
  - [ ] Blog 3.0:  release date, DE/EN title
  - [x] Screenshots 2.28 
- [ ] Footer (TAN) 
- [x] Gulpfile: iOS 3.0.0, Android 3.0.0 https://github.com/corona-warn-app/cwa-website/pull/3172/commits/9a3670ea84eaa853c737c7b62087c13cb389a283
--------------------------------------------------------------------------------------------------------------------------------------------
Other new or updated content (some updates are unrelated to release 3.0)

•	Create build-and-test workflow #3319 
•	Bump luxon from 3.1.1 to 3.2.1 #3318 
•	Delete duplicate video "erklaervideo_gebärdensprache.mp4" #3316 
•	Add markdown-link-check and checklinks script #331
•	Fix link in CONTRIBUTING.md #3311 
•	Update FAQ_SEARCH_SUMMARY: Invalid gulpfile link #3310 
•	Add short Cypress test script npm run test:short #3309 
•	Fix FAQ #update_faq: Missing target='_blank' #3306 
•	Update FAQ #update_faq: Link to GitHub file history #3302 
•	Update FAQ #cause2001: Add hints to restart device & try with mobile data #3301 
•	Bump copyright year in footer #3300 
•	Bump copyright year in README.md #3299 
•	Npm full update #3296 
•	Remove obsolete FAQ information about Prioritized Background Activity #3292 
•	Change Cypress baseURL to https://www.coronawarn.app #3288 
•	Cypress test remove dependency on cypress-io/github-action #3277 
•	Correct CWA name to Corona-Warn-App in web active pages #3275 
•	Reformat faq json source #3274 
•	Bump decode-uri-component from 0.2.0 to 0.2.2 #3272 
•	Remove role="main" from layout files #3271  
•	Update WRITE_BLOG_POSTS.md for images #3270 
•	Update Datenschutz-Folgenabschätzung (DSFA) #3268 
•	Outdated terms of use on website #3267 
•	Replace child main in faq by div section #3265 
•	Remove extra span end tag from faq breadcrumbs #3263  
•	Faq backup update #3260 
•	Remove incorrect br end tags in Blog 2.28 #3259 
•	Correct wrong br in faq results #3258 
•	Change video alt to aria-label in science and sign-language #3256 
•	Center the FAQ lists #3255 
•	Fix table tags in #interoperability_countries (DE) #3254 
•	Fix stray link in FAQ #mutation (DE) #3252 
•	Removed outdated and duplicated FAQ #multiple_exposure_checks (DE) #3250 
•	Update .browserslistrc #3248 
•	Science blog 6 (German) #3243 
•	refactoring the tag center from HTML4 to HTML5 #3241 
•	Bump engine.io from 6.2.0 to 6.2.1 #3240 
•	Simplify iOS troubleshooting FAQs earlier than 1.5.3 #3239 
•	Close unclosed div in FAQs #3237 
•	Remove obsolete reference to Berlin § 8a regulation #3232 
•	Fix list termination in FAQ error_log #3230 
•	Change video alt attribute to aria-label #3228 
•	Reorder screen-reader title for icons in navigation header #3226 
•	Correct copyright footer closing div #3224 
•	Fix FAQ #tan_procedure formatting issues #3222 
•	Update traffic_monitoring #3220 
•	Fix img width attribute in 2.18 blog #3219 
•	Correct width attributes in img tags #3218 
•	Replace spaces in FAQ hyperlinks #3216 
•	Replace / remove lt and gt comparison operators in FAQs #3214 
•	Convert app navigation symbols ">" and "->" to legal HTML #3213 
•	Remove spaces in hotline URIs (EN) #3211 
•	Fix FAQ (EN) #test_result_issues bolding of "PCR test" term #3209 
•	Properly close link in #vac_cert_invalid (EN) #3207 
•	Add Cypress cache housekeeping instructions to README #3205 
•	Update README.md: Include Rosetta requirement #3203 
•	Correct Cypress message formatting for softAssert in headless mode #3201 
•	Correct wrong anchor tags in Accessibility #3199 
•	Migrate to Cypress 10.11.0 #3197 
•	Uninstall unneeded gulp plugins (gulp-load-plugins and gulp-uglify) #3196 
•	Fix experimental json import in gulpfile.mjs #3195 
•	Migrate npm yargs package to v17.6.0 (latest version) #3191 
•	Migrate cwa-website to Node.js 18 (Active LTS) #3189 
•	Bump current Android app version #3188 
•	Add emergentalliance.org to check links exceptions #3185 
•	dependency Update to fix Nodev18 #3183 
•	Update blog: Remove outdated link #3182 
•	Refactor gulpfile from CommonJS to ECMAScript modules (ESM) #3181
•	Replaces node-sass with sass #3180 
•	Add basic immunisation and booster vaccines to glossary #3179 
•	[FAQ] move text from #vac_status to #vac_children #3178 
•	Update reference to Node.js 16 (Maintenance) #3177 
•	Delete downloads.html #3171 
•	rename files 2 #3170 
•	rename files #3169 

---
Internal Tracking ID: [EXPOSUREAPP-14193](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14193)

**Comment by MikeMcC399** [comment]
Android has apparently moved from a 2.29 release to [Release 3.0.x](https://github.com/corona-warn-app/cwa-app-android/milestone/66) including the introduction of SRS for reporting infections and removal of the TAN hotline. This will have a significant impact on the website assuming that this version is released.

**Comment by MikeMcC399** [comment]
iOS has also moved to [release/3.0.x](https://github.com/corona-warn-app/cwa-app-ios/tree/release/3.0.x), which is their default branch.

**Comment by larswmh** [comment]
@MikeMcC399 

The roll out began today at 16:30
