### ISSUE TITLE
Migrate to Node.js 18 Active LTS version

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3186]
## Current Implementation

cwa-website workflows currently specify Node.js 16 (lts/gallium) in

- https://github.com/corona-warn-app/cwa-website/blob/f00df30852b835110db29b2718133d353c4c15b6/.github/workflows/build.yml#L19-L22

- https://github.com/corona-warn-app/cwa-website/blob/f00df30852b835110db29b2718133d353c4c15b6/.github/workflows/deploy-master.yml#L30-L33

### Status change in Node.js releases

As [Node.js 16](https://nodejs.org/download/release/latest-v16.x/) with codename 'Gallium' moved from status *Active LTS* to *Maintenance* on October 25, 2022, [Node.js 18](https://nodejs.org/en/blog/release/v18.12.0/) with codename 'Hydrogen' moved at the same time to status *Active LTS*. LTS means Long Term Support and the [Node.js Release schedule](https://github.com/nodejs/release#release-schedule) explains in detail about the available Node.js versions and their status.

## Suggested Enhancement

Update workflows to use Node.js 18 ('Hydrogen'). This is currently shown on https://nodejs.org/en/ as 18.12.0 LTS "Recommended For Most Users".

Notes:

1. GitHub's [actions/setup-node](https://github.com/actions/setup-node) allows using Node.js 18 although it is not yet cached into the [Ubtuntu 20.04 runner](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md)
2. ~~npm package [webpack](https://www.npmjs.com/package/webpack) must be updated from version 4 to 5 otherwise `npm run build` produces the error "Error: error:0308010C:digital envelope routines::unsupported"~~
3. ~~npm package [webpack-stream](https://www.npmjs.com/package/webpack-stream) must be updated from version 5 to at least version 6 in combination with the webpack update to v5, otherwise the FAQ redirects do not work. v7 is the latest version and this also works with webpack v5.~~

### Steps to migrate

1. Workflow: change `node-version:` from `'lts/gallium'` to `'lts/hydrogen'`
2. npm packages:
    - ~~Update [webpack](https://www.npmjs.com/package/webpack) from version 4.46.0 to 5.74.0 (latest).~~
    - ~~Update [webpack-stream](https://www.npmjs.com/package/webpack-stream) from 5.2.1 to 7.0.0 (latest)~~
    - Edit: the above two packages were already updated by PR https://github.com/corona-warn-app/cwa-website/pull/3183
3. Update [README: Requirements](https://github.com/corona-warn-app/cwa-website/blob/master/README.md#requirements) to refer to Node.js 18

## Expected Benefits

- Align to the preferred Long Term Support version of Node.js (see [Node.js 18](https://nodejs.org/en/blog/release/v18.12.0/)).

- ~~Reduce number of vulnerabilities from 37 to 34 due to necessary npm package updates~~<br>Edit: Not relevant if no new npm packages are installed.

---
Internal Tracking ID: [EXPOSUREAPP-14247](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14247)

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/3187 submitted to implement this suggestion

**Comment by MikeMcC399** [comment]
- New PR https://github.com/corona-warn-app/cwa-website/pull/3189 submitted, since PR https://github.com/corona-warn-app/cwa-website/pull/3183 already updated the npm packages

**Comment by MikeMcC399** [comment]
- PR #3189 has been merged, so the suggestion has been implemented.

**Comment by dsarkar** [comment]
@MikeMcC399 Also here, thanks a lot for providing a PR!

**Comment by MikeMcC399** [comment]
@dsarkar

> Also here, thanks a lot for providing a PR!

My pleasure!
