### ISSUE TITLE
Uninstall npm package gulp-load-plugins

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3192]
## Current Implementation

- https://github.com/corona-warn-app/cwa-website/blob/14346df15158c57fbf7ad44f54ef6a326134d32c/package.json#L41

installs the npm package [gulp-load-plugins](https://www.npmjs.com/package/gulp-load-plugins). 

- The use of this package was removed through PR https://github.com/corona-warn-app/cwa-website/pull/3181. 

- The npm package [gulp-load-plugins](https://www.npmjs.com/package/gulp-load-plugins) use was removed and replaced by individual imports of gulp modules. This is because it produced the error `TypeError: Cannot read properties of undefined (reading 'filename')` in an ESM environment.

## Suggested Enhancement

Uninstall the unused npm package [gulp-load-plugins](https://www.npmjs.com/package/gulp-load-plugins).

## Expected Benefits

Removing unused external software components reduces exposure to security and compatibility issues.

---
Internal Tracking ID: [EXPOSUREAPP-14268](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14268)

**Comment by dsarkar** [comment]
@MikeMcC399 Same here, thanks for the "house-keeping"!

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/3196 resolves this issue.

- Logically, uninstall of gulp-load-plugins belonged to PR https://github.com/corona-warn-app/cwa-website/pull/3181 however I deferred the uninstall due to a potential conflict with PR https://github.com/corona-warn-app/cwa-website/pull/3183 which was making major changes to npm packages, hence a separate issue and PR.
