### ISSUE TITLE
Uninstall npm package gulp-uglify

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3193]
## Current Implementation

https://github.com/corona-warn-app/cwa-website/blob/14346df15158c57fbf7ad44f54ef6a326134d32c/package.json#L47

installs the npm package [gulp-uglify](https://www.npmjs.com/package/gulp-uglify). This package is not used.

## Suggested Enhancement

Uninstall the unused npm package [gulp-uglify](https://www.npmjs.com/package/gulp-uglify).

## Expected Benefits

Removing unused external software components reduces exposure to security and compatibility issues.

---
Internal Tracking ID: [EXPOSUREAPP-14268](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14268)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reporting and providing PR for "clean-up" !

**Comment by MikeMcC399** [comment]
@dsarkar

> Thanks for reporting and providing PR for "clean-up" !

- It seems that `gulp-uglify` was never used. I noticed this when I was doing the work for https://github.com/corona-warn-app/cwa-website/pull/3181

Thanks also to you for handling the PRs promptly. This makes it much easier, especially when the PRs are interrelated.
