### ISSUE TITLE
Cypress it.skip fails

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3198]
## Where to find the issue

Cypress tests under development in cypress/e2e.

## Describe the issue

If a Cypress test is changed from `it` to `it.skip` for debugging purposes, other tests which do not have the `skip` attribute applied do not run and the following error is produced:

```
TypeError
The following error originated from your test code, not from Cypress.

> Cannot set properties of undefined (setting 'body')
```

This is a development issue only. It does not affect the website itself.

- It is related to the open issue https://github.com/corona-warn-app/cwa-website/issues/3010 

- The issue occurs following the migration PR https://github.com/corona-warn-app/cwa-website/pull/3197 which updated cwa-website to use Cypress 10.11.0 instead of Cypress 9.7.0.

## Steps to reproduce

Create a new test spec `test.skip.cy.js` in `cypress/e2e/` with the following contents:

```
it("test 1 - run this", () => { 
    cy.log("test 1 log")
});
it.skip("test 2 - skip this", () => { 
    cy.log("test 2 log")
});
```

Execute `npm run test:open`
Select `test.skip.cy.js`

This produces the error `> Cannot set properties of undefined (setting 'body')` and no tests are executed.

### Regression with Cypress 10.11.0

Going back one minor version from Cypress 10.11.0 to 10.10.0 removes the issue:

Execute:
`npm install cypress@10.10.0`

Repeat the above test.

test 1 runs, test 2 is skipped. This is correct.

### Regression with monkey-patch

`npm install cypress@latest`
Edit `cypress/support/e2e.js` and remove all code starting with the comment line
`// soft assert for finding broken links, see also check_links.js`
to the end of the file.

Repeat the test.

test 1 runs, test 2 is skipped. This is correct.

## Code issue

[cypress/support/e2e.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/support/e2e.js)

contains the code

https://github.com/corona-warn-app/cwa-website/blob/a0c749adcb8e197c7eaf054631a2db26de11a5d0/cypress/support/e2e.js#L93-L109

that modifies the standard behaviour of Cypress / mocha.

- It was introduced through PR https://github.com/corona-warn-app/cwa-website/pull/1786

Without this code, `it.skip` works as expected.

## Reference

Cypress documentation

[Excluding and Including Tests](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Excluding-and-Including-Tests)

_"To skip a specified suite or test, append `.skip()` to the function. All nested suites will also be skipped."_

## Suggestion

Since this is a minor development issue only, I suggest no change at this time.

---
Internal Tracking ID: [EXPOSUREAPP-14292](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14292)

**Comment by MikeMcC399** [comment]
I will try to get feedback on this issue from public forums. The monkey-patch was posted on [Stackoverflow](https://stackoverflow.com/questions/55868107/does-cypress-support-soft-assertion), however it is unsupported code which goes deeply into the workings of Cypress. It doesn't seem like there is any open source maintenance for this code at this time.

**Comment by MikeMcC399** [comment]
- Reported to https://github.com/cypress-io/cypress/issues/24525

**Comment by MikeMcC399** [comment]
- Cypress product support declined the support issue https://github.com/cypress-io/cypress/issues/24525 and closed it since they do not support monkey-patches. This is understandable because monkey-patches use undocumented interfaces and change the behaviour of the product.

**Comment by brianebeling** [comment]
Hey @MikeMcC399 

Internally, we don't work with test skipping. We would support downgrading a minor version, assuming no functionality breaks. Do you want to work on that and verify nothing breaks? Otherwise, we can do it when we have some space for it, but it wouldn't be a high priority for us.

**Comment by brianebeling** [comment]
@MikeMcC399 

Great, thank you! I wasn't aware there is already activity from cypress's side. Then we will monitor how things go and come back to the issue when there is a fix.
