### ISSUE TITLE
Misleading FAQ information regarding uninstall with multiple apps

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#320]
## Where to find the issue
https://www.coronawarn.app/en/faq/#delete_random_ids 4th paragraph or
https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq.json line 409

## Describe the issue
The FAQ says:
"On Android devices, the log is deleted if Corona-Warn-App was the last app using the framework on the device. If you have SwissCovid or Immuni installed in addition to the Corona-Warn-App, the log will only be removed if these additional apps are de-installed or you manually trigger deletion of the exposure log."

By experiment with CWA and SwissCovid installed I find that uninstalling either app and leaving the other app installed will remove all log entries which are linked to the app being uninstalled and which are displayed under
Settings > Google > COVID-19 exposure notifications > Exposure checks

So I think that the FAQ is misleading. For me the log is the history displayed as described above. In this definition of "log" the log is not fully preserved until the last COVID-19 app is uninstalled.

Also the effect of uninstalling one app is to pass on ownership of the API to the remaining app, if this app did not previously own the API. I haven't found any documentation which describes that only one app can be active towards the Google Exposure Notification System at any one time.

## Suggested change
Perhaps the FAQ should be referring to Temporary Exposure Keys and Rotating Proximity Identifiers (RPIs) (observed and sent)? The term "log" as used in the FAQ needs to be explained.
Refer to terms used on https://developers.google.com/android/exposure-notifications/exposure-notifications-api#architecture 

Also, since this is functionality from the Exposure Notification System, Google could be encouraged to elaborate their own documentation regarding these points on the [Google API for Exposure Notifications](https://developers.google.com/android/exposure-notifications/exposure-notifications-api) documentation site.

**Comment by vaubaehn** [comment]
@MikeMcC399 :+1:  very nice to check it out, actually!

@tkowark : last week, @thomasaugsten announced to check out with google in regard to behaviours of ENF -> [here](https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-678692188) . Maybe he already has some news to fresh-up the FAQ in that point? Additionally, would it be possible to validate, if only the logs are erased, or also the own TEKs/collected RPIs? If that happened, woudn't be good... Could you find out something about it, @MikeMcC399 ? I can only guess, that this new (?) behaviour of erasing logs (and TEKs/RPIs?) has been introduced by the [magic configuration change](https://github.com/corona-warn-app/cwa-app-android/issues/933#issuecomment-677463999).... Would be good to know, whether this is an unintentional bug in ENF, or a new 'feature'.

**Comment by tkowark** [comment]
I'll check with the other thomas regarding the current state. 

As a suggestion: I would remove the part that mentions any assumed behavior and simply urge people to not uninstall the app  unless explicitly instructed to do so since we cannot guarantee that the collected TEKs / RPIs will be retained and provide links to the framework documentation. Does that sound reasonable to you?

**Comment by vaubaehn** [comment]
For me sounds like the best possible advice in the current situation. Thank you, Thomas!

**Comment by MikeMcC399** [comment]
@tkowark 

> As a suggestion: I would remove the part that mentions any assumed behavior and simply urge people to not uninstall the app unless explicitly instructed to do so since we cannot guarantee that the collected TEKs / RPIs will be retained and provide links to the framework documentation. Does that sound reasonable to you?

It is reasonable to only use the information from the `stop()` method [Exposure Notification API Methods](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#methods) and say that uninstalling CWA deletes the database and keys from the device. If Google hasn't documented how they handle uninstallation of multiple apps, then leave that description out.

`stop()` 
Disables the broadcast and scan process. You can call this directly. It's also called when a user uninstalls the app. When it’s called as part of the uninstallation process, the database and keys are deleted from the device.

**Comment by tkowark** [comment]
@MikeMcC399 @vaubaehn #323 should now makes this clearer. Could you kindly have a look before we merge the PR?

**Comment by MikeMcC399** [comment]
@tkowark 
I took a look and the English version in https://github.com/corona-warn-app/cwa-website/pull/323 looks fine. For the German version you are using the terms "Deinstallieren" and "Löschen" interchangeably. On my my phone only "Deinstallieren" is offered as an option, so maybe you should stick to this term and not use "Löschen"?

**Comment by vaubaehn** [comment]
I made some minor additions for the first line as a comment inside the pull request. I'm confused, if the second line shows up as deleted? that was not my intention...
But that's just my suggestion, @MikeMcC399  should decide :)

**Comment by tkowark** [comment]
Thanks a lot to both of you! I'll rework that tomorrow.

**Comment by vaubaehn** [comment]
Thank you, @tkowark , and have a nice week-end!
