### ISSUE TITLE
Pruning Cypress cache to reclaim disk space

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3204]
Cypress caches a binary copy of itself for every version which has been installed on a machine.

`npx cypress cache list --size`
shows which versions are cached and how much disk space they take up.

`npx cypress version`
shows the current version.

`npx cypress cache prune`
cleans up the cache and removes versions apart from the current version.

Perhaps this information should be added to the [README](https://github.com/corona-warn-app/cwa-website/blob/master/README.md) file? Each cached Cypress version takes about 0.5 GB of disk space.

## Reference

[Cypress documentation: Guides: Command Line : `cypress cache [command]`](https://docs.cypress.io/guides/guides/command-line#cypress-cache-command)

**Comment by Ein-Tim** [comment]
Thanks for this issue, Mike! This just saved me around 1 GB of disk space!

**Comment by MikeMcC399** [comment]
- PR submitted for this #3205

I'm closing this issue, since the PR can stand on its own.
