### ISSUE TITLE
"PCR tests" not bolded in FAQ #test_result_issues

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3208]
## Where to find the issue

https://www.coronawarn.app/en/faq/results/#test_result_issues

## Describe the issue

In the FAQ article https://www.coronawarn.app/en/faq/results/#test_result_issues "What can I do if I have not received my test result or test certificate?" the text "PCR tests" in the following should appear in bold font.

![PCR tests](https://user-images.githubusercontent.com/66998419/202152812-09ec8374-2a8d-4584-8eff-1200f1799451.jpg)

Compare to the equivalent German language article https://www.coronawarn.app/de/faq/results/#test_result_issues

## Suggestion

Correct the badly-formed HTML `</b>PCR tests</b>`

---
Internal Tracking ID: [EXPOSUREAPP-14340](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14340)

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/3209 submitted to resolve this issue.

**Comment by brianebeling** [comment]
Thanks for noticing the issue and providing a fix!

**Comment by MikeMcC399** [comment]
@brianebeling 

> Thanks for noticing the issue and providing a fix!

- You're welcome! Thanks for merging!

- This is a by-product of troubleshooting PR https://github.com/corona-warn-app/cwa-website/pull/3179 and running the [W3C Markup Validation Service](https://validator.w3.org/) on the FAQ pages. This throws up hundreds of errors. I will take a look to see which ones should be corrected and which can be ignored.
