### ISSUE TITLE
Reserved HTML characters "<" and ">" used in FAQs

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3212]
## Where to find the issue

FAQs

- https://www.coronawarn.app/en/faq/results/
- https://www.coronawarn.app/de/faq/results/

## Describe the issue

There is a lot of incorrect literal usage of the characters `<` and `>` in the FAQs. These are characters reserved to delimit HTML tags.

These are used in:

1. Mathematical comparisons, such as `>= 63dB`
2. In a sequence of instructions, such as `'Settings' -> 'Reset App'` and `'Security & Location' > 'Location' > 'App level permissions'`

## Suggestion

Replace literal usage of the reserved characters `<` and `>` in the FAQs by their escaped equivalents as follows

| Character | Escaped<br>character |
| --------- | -------------------- |
| `<`       | `&lt;`               |
| `>`       | `&gt;`               |

## References

- https://developer.mozilla.org/en-US/docs/Glossary/Entity#reserved_characters

---
Internal Tracking ID: [EXPOSUREAPP-14343](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14343)

**Comment by MikeMcC399** [comment]
I have not done any work on this yet and I will wait for feedback first. 

If this is something which should be cleaned up, then it would also be an opportunity to standardize on the way that navigating menus should be described. There is a mixture of `>` and `->`. Which of these is the preferred notation? For example:

- `'Settings' -> 'Reset App'` or
- `'Settings' > 'Reset App'`

**Comment by larswmh** [comment]
@MikeMcC399 

> I have not done any work on this yet and I will wait for feedback first.
> 
> If this is something which should be cleaned up, then it would also be an opportunity to standardize on the way that navigating menus should be described. There is a mixture of `>` and `->`. Which of these is the preferred notation? For example:
> 
> * `'Settings' -> 'Reset App'` or
> * `'Settings' > 'Reset App'`

Thanks for opening this issue. I agree that it would be a good opportunity to standardize the way navigation menus should be described and I think we should go with `>` as the preferred notation. Should we prepare a PR for this or are you interested in working on this?

**Comment by MikeMcC399** [comment]
@larswmh 

> Should we prepare a PR for this or are you interested in working on this?

I'm happy to prepare a PR for the changes.

**Comment by MikeMcC399** [comment]
The following PRs have been submitted to resolve this issue:

- #3213 
- #3214 

I split the changes into two separate PRs to make reviewing the changes simpler, since there were two different causes for the problem.

**Comment by MikeMcC399** [comment]
Since both the above PRs have been merged, this issue is now resolved.
