### ISSUE TITLE
Wrong syntax for image width in FAQs

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3217]
## Where to find the issue

- https://www.coronawarn.app/en/faq/results/#interoperability_countries
- https://www.coronawarn.app/de/faq/results/#interoperability_countries
- https://www.coronawarn.app/en/faq/results/#rat_what_if_positive_result
- https://www.coronawarn.app/de/faq/results/#rat_what_if_positive_result

## Describe the issue

Some  `img` tags specify the width including the dimension `px`. This is not legal HTML syntax. Pixels are implicit and should not be literally specified (see [Reference](#reference) below).

## Steps to reproduce

Search for regex `width=\s*\d+px` in FAQ source inside `img` tags

## Suggestion

Remove the `px` (pixel) unit from the width attribute inside `img` tags.

## Reference

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-width

"width
The intrinsic width of the image in pixels. Must be an integer without a unit."

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/3218 submitted to resolve this issue

**Comment by brianebeling** [comment]
Leaving this issue open as of now, because additional work is required
https://github.com/corona-warn-app/cwa-website/pull/3218#issuecomment-1318717079

It might be a good idea to create a new issue for the instances outside the FAQ - but I need time to check if there even are more.

**Comment by MikeMcC399** [comment]
@brianebeling 

> Leaving this issue open as of now, because additional work is required
https://github.com/corona-warn-app/cwa-website/pull/3218#issuecomment-1318717079
>
> It might be a good idea to create a new issue for the instances outside the FAQ - but I need time to check if there even are that many more.

- This issue was only for the FAQ, since this is what I am concentrating on at the moment.

- Nevertheless I have submitted PR https://github.com/corona-warn-app/cwa-website/pull/3219 which resolves the only other incorrect instances of `img` tags with `px` in the `width` attribute outside of the FAQs.

**Comment by MikeMcC399** [comment]
The FAQ issue described here is resolved.
