### ISSUE TITLE
Missing bullet character in FAQ #tan_procedure

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3221]
## Where to find the issue

- https://www.coronawarn.app/en/faq/results/#tan_procedure "TAN Procedure"
- https://www.coronawarn.app/de/faq/results/#tan_procedure "TAN-Verfahren"

## Describe the issue

In the FAQ article https://www.coronawarn.app/en/faq/results/#tan_procedure in the section "Further information" the last link has no bullet point. It also fails an HTML validator test.

![tan-procedure-bullet](https://user-images.githubusercontent.com/66998419/202651513-bd4eb7d4-b552-4de8-90a2-30e263b74773.jpg)

The same problem exists in the equivalent German FAQ https://www.coronawarn.app/de/faq/results/#tan_procedure

### Manual view

View the article https://www.coronawarn.app/en/faq/results/#tan_procedure and note the missing bullet character in the last line of links.

### Automated test

Run https://validator.w3.org/ on 

- https://www.coronawarn.app/en/faq/results/
- https://www.coronawarn.app/en/faq/results/

Note error

"Element a not allowed as child of element ul in this context."
`?</a></li><a href='#qr_test' target='_blank'>FAQ:`

## Suggestion

Add a missing `<li>` tag.

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/3222 resolves this issue

**Comment by MohamedZaghdoudi** [comment]
Hey @MikeMcC399 , thanks for the feedback. I will take a look  and add the bullet.

**Comment by MikeMcC399** [comment]
@MohamedZaghdoudi 

> I will take a look and add the bullet.

You don't need to add the bullet yourself, I already submitted PR #3222 to add the bullet. Please take a look at the PR.
