### ISSUE TITLE
The titel Sections is not in the center-position 

### ISSUE THREAD

**Issue by MohamedZaghdoudi** [corona-warn-app/cwa-website#3233]
> Where to find the issue: 

https://www.coronawarn.app/en/faq/

> Describe the issue: 

the Position of Sections is not in the Center .

> Suggestion : 

switch in _reboot.scss the position from text-align from "$body-text-align " to "center"

**Comment by MikeMcC399** [comment]
@MohamedZaghdoudi 

- Why is this closed? Normally you would close an issue after it has been resolved through merging a PR.

- I commented on the issue #3234 which you opened. Unfortunately it has some major side-effects.

- I have also noticed that there is a lot of use of the `<center>` tag on many pages, however this tag, which was already deprecated in HTML4, is not supported in HTML5, so in fact this is a general issue on the website.

**Comment by MikeMcC399** [comment]
- See also related issue https://github.com/corona-warn-app/cwa-website/issues/3235

**Comment by MohamedZaghdoudi** [comment]
@MikeMcC399 okay i will see it now

**Comment by MikeMcC399** [comment]
@MohamedZaghdoudi 

Maybe you could also correct a typo in the subject?

 "tittel" should be "title"

**Comment by MohamedZaghdoudi** [comment]
@MikeMcC399 thank you for your feedback . It is done.

**Comment by MikeMcC399** [comment]
@MohamedZaghdoudi 

In English it is spelled "[title](https://dictionary.cambridge.org/dictionary/english/title)" not "titel".

**Comment by brianebeling** [comment]
Closing this issue as it became a bit misleading. Originally we wanted to recenter the content under "Sections". It looks a bit misaligned. We did not want to center the headline itself. 

Please refer to: https://github.com/corona-warn-app/cwa-website/issues/3246

**Comment by MikeMcC399** [comment]
@brianebeling 

I agree that this was a confusing issue. Also the suggested resolution to edit [_reboot.scss](https://github.com/corona-warn-app/cwa-website/blob/master/src/assets/scss/_reboot.scss) did not work and probably was not the right place to make a single layout change anyway.

[_reboot.scss](https://github.com/corona-warn-app/cwa-website/blob/master/src/assets/scss/_reboot.scss) looks like it comes from
https://github.com/twbs/bootstrap/blob/main/scss/_reboot.scss as described in https://getbootstrap.com/docs/4.0/content/reboot/.
