### ISSUE TITLE
Use of `<center>` tag

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3235]
## Where to find the issue

- https://www.coronawarn.app/en/faq/
- https://www.coronawarn.app/en/event-qr-code-guide/
- https://www.coronawarn.app/en/science/2022-03-03-science-blog-5/
- Multiple Blog pages under https://www.coronawarn.app/en/blog/

and the German language equivalents.

## Describe the issue

All pages on https://www.coronawarn.app/ are marked up with

`<!DOCTYPE html>`

according to each of the `*.html` files in [src/layouts](https://github.com/corona-warn-app/cwa-website/tree/master/src/layouts). This indicates that the page content is HTML5.

The tag `<center>` is used on many pages, however this tag, which was already deprecated in HTML4, is not supported in HTML5.

#### FAQ

https://www.coronawarn.app/en/faq/

```html
<center><a href="results" class="no-decoration">View all topics and all questions</a></center>`
```

#### Event QR-Code Guide

https://www.coronawarn.app/en/event-qr-code-guide/

```html
<p><hr/> We explicitly point out that you should <b>not</b> set the checkmark at the following pop-up window. The installation can also be done without this additional option. <br/> <br/> <center> <b>Window text : </b> <br/> <em>Some npm modules need to be compiled from C/C++ when installing. If you want to be able to install such modules, some tools (Python and Visual Studio Build Tools) need to be installed. <br> <br> [ ] Automatically install the necessary tools. Note that this will also install Chocolatey. The script will pop-up in a new window after the installation completes. <br> <br> Alternatively, follow the instructions at https://github.com/nodejs/node-gyp#on-windows to install the dependencies yourself. </em> </center>  </p>`
```

#### Science 5

https://www.coronawarn.app/en/science/2022-03-03-science-blog-5/

```html
<center><img src="/assets/img/science/2022-03-03-science-blog-5/math1_en.png" class="figure-img img-fluid" width=60% alt="Mathematische Formel"/></center>`
```

#### Blog

https://www.coronawarn.app/en/blog/2022-10-26-cwa-2-28/

```html
<center> 
<img src="/assets/img/blog/2022-10-26-cwa-2-28/pandemic-radar.jpg" title="Kachel Pandemieradar" style="align: center" width=250>
</center>
```

## Suggestion

- Review if the `cwa-website` should continue to use the deprecated / unsupported `<center>` tag.

- If it should no longer be used then convert the center formatting to use [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS).

## References

- [HTML `<!DOCTYPE>` Declaration](https://www.w3schools.com/tags/tag_doctype.asp)
- [HTML `<center>` Tag](https://www.w3schools.com/tags/tag_center.asp)
- [MDM: `<center>`: The Centered Text element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center)
- https://caniuse.com/mdn-html_elements_center

---
Internal Tracking ID: [EXPOSUREAPP-14424](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14424)

**Comment by MohamedZaghdoudi** [comment]
@MikeMcC399  I think if we change it to css will be better

**Comment by MikeMcC399** [comment]
A related problem in the blogs is the use of the undefined CSS property `align` in the attribute `style="align: center"`.

**Comment by MikeMcC399** [comment]
The documentation https://github.com/corona-warn-app/cwa-website/blob/master/docs/WRITE_BLOG_POSTS.md which recommends:

```
<p align="center">
  <img src="./logo.png" width="235">
</p>
```

needs to be updated. `align="center"` is an obsolete recommendation and needs to be replaced by an example using CSS.

## Reference

- https://html.spec.whatwg.org/multipage/obsolete.html#non-conforming-features (includes `align` on `p` as obsolete)

**Comment by MikeMcC399** [comment]
It seems that cwa-website layouts are built using bootstrap so I wonder if the recommendation for centering should be based on [Bootstrap V4 - Text alignment](https://getbootstrap.com/docs/4.0/utilities/text/#text-alignment), for example:

`<p class="text-left">Left aligned text on all viewport sizes.</p>`

which has changed to `text-start` in [Bootstrap V5 - Text alignment](https://getbootstrap.com/docs/5.2/utilities/text/#text-alignment) for the support of Right-To-Left (RTL) languages.

**Comment by brianebeling** [comment]
> It seems that cwa-website layouts are built using bootstrap so I wonder if the recommendation for centering should be based on [Bootstrap V4 - Text alignment](https://getbootstrap.com/docs/4.0/utilities/text/#text-alignment), for example:
> 
> `<p class="text-center">Center aligned text on all viewport sizes.</p>`

Absolutely. @MohamedZaghdoudi Follow the bootstrap recommendation, please. 😄
