### ISSUE TITLE
FAQ Sections is not centered

### ISSUE THREAD

**Issue by brianebeling** [corona-warn-app/cwa-website#3246]
## Where to find the issue
https://www.coronawarn.app/en/faq/

## Describe the issue

Centering:
![image](https://user-images.githubusercontent.com/12231155/204078797-4994bbc1-b610-4e60-86b8-a058d8b410dd.png)

## Suggested change
 Move the content (and title) to the right

**Comment by Ein-Tim** [comment]
I think e.g. "Check-in" & "iOS" are one purpose only slightly visible, to make it clear to the user that there is more to that then only the topics that are shown. I really like this, as it is quite a low-key way to tell the user: "Hey, there's more!".

Centering the whole list makes sense.

Btw, I think in your title "had" should be "has".

**Comment by MikeMcC399** [comment]
The logic seems to be a bit strange. The list can have indexed and non-indexed titles. Only the indexed titles are shown in https://www.coronawarn.app/en/faq/. If there are 7 or more titles (whether they are shown or not) then the last title in the list is faded out. It would be more intuitive to view if the number of displayed titles is limited to the same number. So you would need to count the number of displayed titles instead of the number of all titles.

**Comment by MikeMcC399** [comment]
Please note when making changes to this layout that it is dynamic, according to the browser width.

**Comment by brianebeling** [comment]
> I think e.g. "Check-in" & "iOS" are one purpose only slightly visible, to make it clear to the user that there is more to that then only the topics that are shown. I really like this, as it is quite a low-key way to tell the user: "Hey, there's more!".
> 
> Centering the whole list makes sense.
> 
> Btw, I think in your title "had" should be "has".

Whoops, you are right. I slipped, thanks for letting me know!

> The logic seems to be a bit strange. The list can have indexed and non-indexed titles. Only the indexed titles are shown in [coronawarn.app/en/faq](https://www.coronawarn.app/en/faq/). If there are 7 or more titles (whether they are shown or not) then the last title in the list is faded out. It would be more intuitive to view if the number of displayed titles is limited to the same number. So you would need to count the number of displayed titles instead of the number of all titles.

For now I removed the visibility thing. I wasn't realizing its a feature and not a bug. For some reason it does look off to me. At the moment I can't pintpoint what it is though..

**Comment by MikeMcC399** [comment]
@brianebeling 

For the positioning I suggest you check out [Bootstrap flex](https://getbootstrap.com/docs/4.6/utilities/flex/) which is already in use on this page. `d-flex justify-content-center` with` text-center` and `text-left` in the right places may be all that is needed.

**Comment by MikeMcC399** [comment]
@brianebeling 

Let me know if you want a PR for this. I tried out my suggestion from above ^^ and it seemed to work, including with various browser widths.

**Comment by brianebeling** [comment]
@MikeMcC399 That'd be great. I can review it right now as well. I will let @MohamedZaghdoudi know that he can stop working on this! Thanks!

**Comment by MikeMcC399** [comment]
@brianebeling 

- I have submitted https://github.com/corona-warn-app/cwa-website/pull/3255 to center the FAQ section list. I also centered the title because it looked better that way. Screenshots are in the PR.

**Comment by MohamedZaghdoudi** [comment]
@MikeMcC399  thank you very much for your work.

**Comment by MikeMcC399** [comment]
@brianebeling 

- Will you close this issue now that PR #3255 has been merged?

**Comment by brianebeling** [comment]
Ah, yes, thank you. I clocked out yesterday and was in a hurry. Closing this now. 😄
