### ISSUE TITLE
main role (ARIA) not recommended

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3266]
- This issue follows on from a comment in issue https://github.com/corona-warn-app/cwa-website/issues/3264.

## Where to find the issue

- https://www.coronawarn.app/en/
- https://www.coronawarn.app/de/

## Describe the issue

Pages on the https://www.coronawarn.app/ website use the following main declaration with `role="main"`

```html
    <main id="main" class="main-content" role="main" tabindex="-1">
```
From https://w3c.github.io/html-aria/#rules-wd

"It is NOT RECOMMENDED for authors to set the ARIA role and aria-* attributes to values that match the implicit ARIA semantics defined in either table. Doing so is unnecessary and can potentially lead to unintended consequences."

## Steps to reproduce

Run https://validator.w3.org/ on 

- https://www.coronawarn.app/en/ 
- https://www.coronawarn.app/en/blog/
- https://www.coronawarn.app/en/science/
  
and note the warning message:

"The main role is unnecessary for element main."

Also check

- https://www.coronawarn.app/en/unknown

and select "Validate error pages" before clicking on "Check".

## Suggestion

Remove `role="main"` from layout html files in [src/layouts](https://github.com/corona-warn-app/cwa-website/tree/master/src/layouts)

## References

- https://w3c.github.io/html-aria/#rules-wd
- https://w3c.github.io/html-aria/#el-main

**Comment by MikeMcC399** [comment]
Please let me have feedback about this issue which is related to accessibility. https://w3c.github.io/html-aria/#rules-wd clearly says:

"It is NOT RECOMMENDED for authors to set the ARIA role and aria-* attributes to values that match the implicit ARIA semantics defined in either table. Doing so is unnecessary and can potentially lead to unintended consequences."

however the validator "only" classes it as a warning not an error.

I'm happy to submit a PR if the suggested change should be made. Please let me know if the problem should be addressed or left unchanged.

**Comment by brianebeling** [comment]
Hey @MikeMcC399, thanks for the issue. I'd suggest to fix this eventually, but to prioritize the remaining issues in the w3c validator, that are classified as above warnings.

**Comment by MikeMcC399** [comment]
@brianebeling 

Many thanks for your feedback! I will submit a PR for this issue so it can be ticked off, even if there is no urgency.

**Comment by MikeMcC399** [comment]
- PR #3271 is submitted to resolve this issue
