### ISSUE TITLE
Spelling of Corona-Warn-App

### ISSUE THREAD

**Issue by brianebeling** [corona-warn-app/cwa-website#3273]
## Where to find the issue

Use the Visual Studio Code "Search" feature or similar and search for "Corona Warn App" and variations like "Corona-Warn App"

"Corona Warn App"
![image](https://user-images.githubusercontent.com/12231155/205481149-86aaff4f-534f-4535-8ae7-bca80658dab5.png)

"Corona-Warn App"
![image](https://user-images.githubusercontent.com/12231155/205481140-c099f995-f0a0-4d18-aaab-702af5a44520.png)

## Describe the issue

The naming is not consistent

## Suggested change

Change to Corona-Warn-App

**Comment by MikeMcC399** [comment]
@brianebeling 

Good catches!  The historical blog entries have  previously been considered to be frozen as published and we have generally only touched them to correct links if they become broken, so would I suggest not to make text changes to these articles.

**Comment by MikeMcC399** [comment]
@brianebeling 

- I have submitted https://github.com/corona-warn-app/cwa-website/pull/3275 for the places which I think should be changed.
