### ISSUE TITLE
Badges for Open Source Team members

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3278]
Would it be possible to make Open Source Team members show up here as "Members" or "Collaborators"?

Posts from regular contributors @brianebeling, @MohamedZaghdoudi, @GisoSchroederSAP and @HelTob show with a  "Contributor" badge which is the same as a community member like me who has contributed to the `master` branch. @mtb77, @larswmh and @dsarkar however show with "Member" badges which makes more sense to be able to identify who is here in an "official" capacity.

**Comment by brianebeling** [comment]
Mh, that is weird. For me it shows correctly as Member. It should for anyone that is part of the Corona-Warn-App Team. 🤔 
Is that something you can choose somewhere and I just missing it?
