### ISSUE TITLE
References to TAN Hotline in footer

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3331]
## Where to find the issue

Footer of all pages on https://www.coronawarn.app "Hotline TAN"

## Describe the issue

References to the TAN Hotline in the footer do not say that the hotline will be discontinued.

## Suggestion

Add an extra line to the footer in the column under Hotline TAN:

- until Jan 31, 2023 (EN)
- bis 31. Jan 2023 (DE)

This can be implemented in [src/data/global.json](https://github.com/corona-warn-app/cwa-website/blob/master/src/data/global.json) with the addition of:

```
{
  "title": "until Jan 31, 2023",
  "url": "/en/blog/2023-01-18-cwa-3-0/"
}
```
and
```
{
  "title": "bis 31. Jan 2023",
  "url": "/de/blog/2023-01-18-cwa-3-0/"
}
```
underneath the phone number links, which provides both the information about the date and a link to the CWA 3.0 blog. On a mobile device it appears as follows:

![image](https://user-images.githubusercontent.com/66998419/213377836-c2eb4203-a091-4e21-a343-2bb1acc5f2fd.png)

## References

https://www.coronawarn.app/en/blog/2023-01-18-cwa-3-0/ says "... the operation of the verification hotline will be discontinued as of 31.01.2023."

**Comment by Ein-Tim** [comment]
I rather suggest to simply remove this part of the footer on 01. Feb 2023. It saves work and I don't see the need to add a disclaimer now. 

This issue is also applicable to https://github.com/corona-warn-app/cwa-event-landingpage

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> I rather suggest to simply remove this part of the footer on 01. Feb 2023. It saves work and I don't see the need to add a disclaimer now.

That is an alternative which would also mean adapting the Cypress test https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hotline.cy.js to remove the Hotline TAN check.

> This issue is also applicable to https://github.com/corona-warn-app/cwa-event-landingpage

You might like to open an issue there.

**Comment by Ein-Tim** [comment]
> > I rather suggest to simply remove this part of the footer on 01. Feb 2023. It saves work and I don't see the need to add a disclaimer now.
> 
> That is an alternative which would also mean adapting the Cypress test [`master`/cypress/e2e/hotline.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hotline.cy.js?rgh-link-date=2023-01-18T17%3A08%3A36Z) to remove the Hotline TAN check.

Yeah, but I don't see a way around that. Leaving the number of the TAN hotline in the footer after 31. Jan 2023 is not necessary. It should be removed on that date.

> > This issue is also applicable to [corona-warn-app/cwa-event-landingpage](https://github.com/corona-warn-app/cwa-event-landingpage)
> 
> You might like to open an issue there.

I'll do that!

**Comment by MikeMcC399** [comment]
This can be implemented simply in [src/data/global.json](https://github.com/corona-warn-app/cwa-website/blob/master/src/data/global.json) with the addition of:

```
{
  "title": "until Jan 31, 2023",
  "url": "/en/blog/2023-01-18-cwa-3-0/"
}
```
and
```
{
  "title": "bis 31. Jan 2023",
  "url": "/de/blog/2023-01-18-cwa-3-0/"
}
```
underneath the phone number links, which provides both the information about the date and a link to the CWA 3.0 blog.

**Comment by MikeMcC399** [comment]
The implementation of this suggestion is in branch https://github.com/MikeMcC399/cwa-website/tree/hotline-tan. If you want a PR for this, then please tell me.

**Comment by larswmh** [comment]
@MikeMcC399 

We would appreciate if you could provide a PR containing your suggested changes. Thanks for offering!

**Comment by MikeMcC399** [comment]
@larswmh 

- I have submitted PR https://github.com/corona-warn-app/cwa-website/pull/3332 to add the extra line to the footer
