### ISSUE TITLE
"Sharing behaviour" graph on CWA Dashboard page needs update

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#3337]
## Where to find the issue
- https://www.coronawarn.app/en/analysis/ Graph "Sharing behaviour"
- https://www.coronawarn.app/de/analysis/ Graph "Teilungsverhalten"

## Describe the issue
There are only two categories, "QR codes" & "teleTANs" but now with version 3.0 we also have self reported warnings. This should be another category.

## Suggested change
Make sure that the corresponding data to self reported warnings exist and extend the page. 

---
Internal Tracking ID: [EXPOSUREAPP-14614](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14614)

**Comment by dsarkar** [comment]
We are in contact with the stakeholders about this issue.

**Comment by Ein-Tim** [comment]
@dsarkar 

I'd like to push this issue and urge the team to get this fixed/implemented ASAP.
As we can see on https://www.coronawarn.app/en/analysis/ in the graph "Warnings received by data donors", since January 12 there is a clear trend upwards. It would be really interesting to see how many of these warnings were caused by self reported infections!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Good observation! I captured the graph for "Warnings received by data donors" beginning Jan 1, 2023:

![image](https://user-images.githubusercontent.com/66998419/215041810-b939d162-ede8-490c-b4ea-0eb5ccae732c.png)

**Comment by dsarkar** [comment]
Good morning @MikeMcC399  and @Ein-Tim! We are aware of the interest to publish the SRS data on a separate tab on the third graph. The topic was discussed with stakeholders and it is now up to them to get to a decision. Thanks for sharing your thoughts on the topic!

**Comment by MikeMcC399** [comment]
@dsarkar 

Did the stakeholders make a decision? Was it not clear that there would be a need to publish SRS data when it was introduced?

![image](https://user-images.githubusercontent.com/66998419/217863862-395ec093-5b45-483d-9376-42413853d7c7.png)

**Comment by dsarkar** [comment]
@MikeMcC399  We are currently evaluating the possibility and options for displaying SRS warnings. Currently, there is no final decision for this feature or a release date.

**Comment by MikeMcC399** [comment]
@dsarkar 

Since March 1, 2023 there is no longer a warning process for OEGD and 10C QR codes. The only method left is "warn without a TAN" and the statistics on https://www.coronawarn.app/en/analysis/ do not include these numbers.

**Comment by brianebeling** [comment]
> @dsarkar 
> 
> Since March 1, 2023 there is no longer a warning process for OEGD and 10C QR codes. The only method left is "warn without a TAN" and the statistics on https://www.coronawarn.app/en/analysis/ do not include these numbers. 

Hi Mike, thanks for the heads-up. We have made the change to include this (and other minor improvements).

This topic specifically is always a bit delicate and has to receive several rounds of reviews, but everyone involved wants to get this out as soon as possible.

**Comment by brianebeling** [comment]
Fixed with https://github.com/corona-warn-app/cwa-website/pull/3421
