### ISSUE TITLE
Screenshots page: Version 3.0 screenshots aren't from version 3.0

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#3342]
## Where to find the issue
- https://www.coronawarn.app/de/screenshots/#android_screenshots
- https://www.coronawarn.app/en/screenshots/#android_screenshots
- https://www.coronawarn.app/de/screenshots/#ios_screenshots
- https://www.coronawarn.app/en/screenshots/#ios_screenshots

## Describe the issue
There are multiple screenshots on the page which weren't actually taken on version 3.0 of the Corona-Warn-App, but must have been taken on an earlier version.

## Suggested change
Update the page with screenshots actually taken on version 3.0 of the CWA. 

---
Internal Tracking ID: [EXPOSUREAPP-14645](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14645)

**Comment by dsarkar** [comment]
Good morning @Ein-Tim, we will check this. Thanks.
