### ISSUE TITLE
Inconsistent use of date formats in FAQ

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#3345]
## Where to find the issue
EN FAQ

## Describe the issue
Inconsistent use of date formats

## Suggested change
See https://github.com/corona-warn-app/cwa-website/pull/3344#issuecomment-1401508445

---
Internal Tracking ID: [EXPOSUREAPP-14625](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14625)

**Comment by MikeMcC399** [comment]
In http://localhost:8000/en/faq/results/#mutation the grammar is incorrect

"To date, the risk assessment was improved and adapted on the Feb 23, 2021, on the Mar 19, 2021 and on the Apr 16, 2021."

should be

"To date, the risk assessment was improved and adapted on Feb 23, 2021, on Mar 19, 2021 and on Apr 16, 2021."

without "the".

Perhaps this could also be corrected in this PR?

**Comment by MikeMcC399** [comment]
http://localhost:8000/en/faq/results/#rooted_devices

shows "24 January, 2023" which should be "January 24, 2023"

**Comment by MikeMcC399** [comment]
- https://github.com/corona-warn-app/cwa-website/pull/3352 is another PR addressing this topic

**Comment by dsarkar** [comment]
@MikeMcC399 thanks for assisting, all PRs merged now.
