### ISSUE TITLE
Cypress Issues 

### ISSUE THREAD

**Issue by brianebeling** [corona-warn-app/cwa-website#3366]
Originally posted by **MikeMcC399** January 31, 2023
- PR https://github.com/corona-warn-app/cwa-website/pull/3296 from @brianebeling updated [start-server-and-test](https://github.com/bahmutov/start-server-and-test) from 1.14.0 to 1.15.2.

- Now when Cypress tests are run, there is a message "is responding with HTTP status code NaN" instead of "is responding with HTTP status code 200".

- I reported this regression in issue https://github.com/bahmutov/start-server-and-test/issues/349.</div>

Originally posted by **MikeMcC399** January  4, 2023

There are two errors which show up in the logs of https://github.com/corona-warn-app/cwa-website/actions/workflows/cypress-test-prod.yml

```text
Opening Cypress...
[2230:0104/090407.741839:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Couldn't find tsconfig.json. tsconfig-paths will be skipped
```

These are known Cypress issues and neither of these messages cause a problem to the cwa-website Cypress test, so they can be ignored for practical purposes.

I did however log them as reproducible issues in the hope that the Cypress experts may fix them in a future Cypress version:

- https://github.com/cypress-io/cypress/issues/25357 (Obsolete because of the workaround)
- https://github.com/cypress-io/cypress/issues/25335

---
That seem to be most of the current, non important, Cypress or related issues from the to be disabled discussions

**Comment by brianebeling** [comment]
This is FIY only and we need to wait on a fix from Cypress. Not reverting as its not actively breaking anything.
Thanks again for creating the issue initially Mike!

**Comment by MikeMcC399** [comment]
@brianebeling 

> we need to wait on a fix from Cypress.

The package [start-server-and-test](https://github.com/bahmutov/start-server-and-test) is not maintained by Cypress.io. It belongs to bahmutov who used to work for Cypress, but not any more. This package does not actually use Cypress automatically.

I will also monitor the progress and remind him if necessary. I have given him a few PRs lately which he has also merged.

The other issues which you have now bundled into this issue are actually owned by Cypress and I am working with them to get them resolved.

They are all just cosmetic issues as far as we know.

**Comment by MikeMcC399** [comment]
- PR #3381 provides a workaround for one of the issues bundled here

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/3386

**Comment by MikeMcC399** [comment]
@brianebeling 

I suggest not to bundle multiple issues into one GitHub issue in future as the status becomes very difficult to follow.
