### ISSUE TITLE
Mobile display of "Where can I get tested?" not optimized

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3369]
## Current Implementation

The FAQ article [Where can I get tested?](https://www.coronawarn.app/en/faq/results/#where_can_i_get_tested) is not optimized for display on a mobile device.

After tapping in the app on

Manage Your Tests and Warn Others > Find Testing Center

the web browser refreshes twice before it finally shows "Where can I get tested?".

On my Android Galaxy A50 the link to map.schnelltestportal.de is not displayed and I have to scroll down to find it.

![image](https://user-images.githubusercontent.com/66998419/217460509-17bf88df-7857-4305-b824-bc879d108163.png)

## Suggested Enhancement

1. Add the link [map.schnelltestportal.de](https://map.schnelltestportal.de/) to the top of the article.
2. Move the See also "What can I do if I have not received my test result or test certificate?" to the bottom of the article.
3. link the image https://www.coronawarn.app/assets/img/faq/schnelltestportal_1.jpeg to [map.schnelltestportal.de](https://map.schnelltestportal.de/)

## Expected Benefits

Easier use of "Find Testing Center" from app so that the link to [map.schnelltestportal.de](https://map.schnelltestportal.de/) can be found more easily.

---
Internal Tracking ID: [EXPOSUREAPP-14708](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14708)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the suggestions, we are looking at this issue.

**Comment by MikeMcC399** [comment]
@dsarkar / @larswmh 

Many thanks for addressing this issue!
