### ISSUE TITLE
Cypress check_links fails on GitHub and locally

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3391]
When check_links is run on GitHub it may show the error message

"We detected that the Chromium Renderer process just crashed."

and then fail.

On a local system it may fail with the Chrome "Aw, snap!" memory failure message.

## Where to find the issue

[cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js)

## Describe the issue

If an attempt is made to run [cypress/e2e/hybrid/check_links.cy.js](https://github.com/corona-warn-app/cwa-website/blob/master/cypress/e2e/hybrid/check_links.cy.js) in a GitHub workflow, the workflow fails.

Cypress is currently configured with version 10.11.0.

### On GitHub

For test purposes
- modify [.github/workflows/build-and-test.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build-and-test.yml) and change the test selection from `cypress/e2e/*.js` to `cypress/e2e/hybrid/*.js`
- run the workflow

### Locally

Chrome 109 on Windows 11

```bash
nvm use 18
npm ci
npm run test:open
```
select Chrome browser and `hybrid/check_links` test to run

The error message "Error code: Out of Memory" may also appear here, similar to on GitHub.
It is possible to workaround this by logging out (to kill all Chrome processes) and logging in again, however it shows that the memory usage of the test is not robust.

## Analysis

There are two failures:

1.  In the archive blog section
```text
1) "/de/blog/archiv/" - Check for broken links
1) "/en/blog/archive/" - Check for broken links
```
2. Crash after completing check of /en/sitemap and starting check of /de/blog (Check for broken links on entries)

## Cypress logs

```text

  Check for broken links
    ✓ Check if txt results exist (36ms)
    ✓ "/de" - Check for broken links (27736ms)
    ✓ "/en" - Check for broken links (24969ms)
    ✓ "/de/eventregistration/" - Check for broken links (1919ms)
    ✓ "/en/eventregistration/" - Check for broken links (1947ms)
    ✓ "/de/community/" - Check for broken links (3134ms)
    ✓ "/en/community/" - Check for broken links (1430ms)
    ✓ "/de/analysis/" - Check for broken links (8578ms)
    ✓ "/en/analysis/" - Check for broken links (6430ms)
    1) "/de/blog/archiv/" - Check for broken links
    2) "/en/blog/archive/" - Check for broken links
    ✓ "/de/screenshots/" - Check for broken links (33985ms)
    ✓ "/en/screenshots/" - Check for broken links (33400ms)
    ✓ "/de/faq/" - Check for broken links (3489ms)
    ✓ "/de/faq/results/" - Check for broken links (123820ms)
    ✓ "/en/faq/" - Check for broken links (3885ms)
    ✓ "/en/faq/results/" - Check for broken links (117297ms)
    ✓ "/de/rat-partner/" - Check for broken links (5084ms)
    ✓ "/en/rat-partner/" - Check for broken links (3782ms)
    ✓ "/de/privacy/" - Check for broken links (26846ms)
    ✓ "/en/privacy/" - Check for broken links (28015ms)
    ✓ "/de/terms-of-use/" - Check for broken links (2324ms)
    ✓ "/en/terms-of-use/" - Check for broken links (2384ms)
    ✓ "/de/event-qr-code-guide/" - Check for broken links (1701ms)
    ✓ "/en/event-qr-code-guide/" - Check for broken links (1240ms)
    ✓ "/de/blog/" - Check for broken links (9628ms)
    ✓ "/en/blog/" - Check for broken links (6559ms)
    ✓ "/de/science/" - Check for broken links (2661ms)
    ✓ "/en/science/" - Check for broken links (2265ms)
    ✓ "/de/simple-language/" - Check for broken links (1499ms)
    ✓ "/en/simple-language/" - Check for broken links (875ms)
    ✓ "/de/sign-language/" - Check for broken links (2249ms)
    ✓ "/en/sign-language/" - Check for broken links (918ms)
    ✓ "/de/sitemap/" - Check for broken links (4493ms)
    ✓ "/en/sitemap/" - Check for broken links (4294ms)

  Check for broken links on entries

We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed

```

---
Internal Tracking ID: [EXPOSUREAPP-](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-)

**Comment by MikeMcC399** [comment]
I will look at resolving this issue, which has two root causes.

The main problem is checking the blogs which means that one test tries to check more than 4400 links. The results of each test are stored in browser memory, which overloads the browser.

**Comment by MikeMcC399** [comment]
I am looking at restricting the checks in `blogs` and `science` to only the main section, since the `header` and `footer` are always the same. That would reduce the number of tests, reduce memory requirements and speed up the tests.

**Comment by MikeMcC399** [comment]
- The additional of the reference table at the top of the blog (see PR https://github.com/corona-warn-app/cwa-website/pull/3338) means that blog entries listed in this table are now having their links checked twice, which is further increasing the memory load.

**Comment by MikeMcC399** [comment]
I'm hitting different issues trying to resolve this, so I'm wondering if it is necessary. If are going to be a lot of website changes and the website is going to continue for some time, then it would be worthwhile to try and get the `check_links` Cypress test cleaned up. Does the Open Source Team have an opinion on this? Would you want to put effort into it from your side?

**Comment by MikeMcC399** [comment]
- I have submitted PR https://github.com/corona-warn-app/cwa-website/pull/3394 which removes more than 7000 redundant link checks and solves the problem of the browser crashing.

**Comment by dsarkar** [comment]
@MikeMcC399 Good morning, we will have a look at it. Thanks!

**Comment by MikeMcC399** [comment]
Good morning @dsarkar !

Thank you. I think this is a good fix. It is very simple, has a big impact and the tests I made were successful.

**Comment by MikeMcC399** [comment]
I verified that PR #3394 fixes the main issue here, so I will close this. There are other issues when testing on GitHub and I will raise these separately.
