### ISSUE TITLE
Is iOS 14 Public Beta 6 supported?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#340]
## Your Question
The [FAQ](https://www.coronawarn.app/en/faq/?search=Beta#ios_14_beta) only states that iOS 14 Beta 4 isn't supported, that implicit that everything above Beta 4 is supported, is this correct? 
If not please update the FAQ.

**Comment by mtb77** [comment]
Hi @Ein-Tim,

basically speaking Beta software can not be officially supported, even if the App is running without problems. As the ENF is included in iOS 14 since Beta 4 I would recommend to keep the entry as it is. 
Do you agree?

Cheers,

Sascha

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Hey @mtb77 

I would recomend to update the FAQ to:

>With iOS 14 Beta 4, the Exposure Notification framework is available. But this version is still under development and is not public. The Corona-Warn-App does not support iOS 14 Beta. See the iOS & iPadOS 14 Beta Release Notes.

> Mit iOS 14 Beta 4 ist das Exposure Notification Framework inzwischen verfügbar. Dennoch ist diese Version noch in Entwicklung und ist nicht für den Betrieb auf produktiven Geräten vorgesehen. Die Corona-Warn-App unterstützt die iOS 14 Beta nicht. Siehe iOS & iPadOS 14 Beta Release Notes.

I would love to open a PR for this but I'm not sure how I do it correctly, so sorry.

**Comment by mtb77** [comment]
I created a pull request and will close this issue now 

Cheers,

Sascha

Corona-Warn-App Open Source Team
