### ISSUE TITLE
Add a workflow to check Markdown links

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3407]
This is a suggestion to add a workflow to check Markdown links.

## Current situation

The local command

`npm run checklinks`

is available to check links in Markdown documents such as the [README](https://github.com/corona-warn-app/cwa-website/blob/master/README.md) file which are targeted at contributors and maintainers of the repository.

There is however no automated trigger to run this check.

(Note that Markdown documents which are website source documents are already checked through a separate process after they are transformed into HTML pages.)

## Suggestion

Add a new workflow to [.github/workflows](https://github.com/corona-warn-app/cwa-website/tree/master/.github/workflows) to run the `checklinks` script to check links in Markdown documents.

---
Internal Tracking ID: [EXPOSUREAPP-14845](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14845)

**Comment by MikeMcC399** [comment]
Please let me know if you would like a workflow for this and I will submit a new PR.

- It would complement the new workflow in PR https://github.com/corona-warn-app/cwa-website/pull/3402

**Comment by larswmh** [comment]
Hey @MikeMcC399, thanks for offering your assistance on this. We would appreciate if you could provide a PR for this. I've just merged the PR mentioned in your previous comment

**Comment by MikeMcC399** [comment]
@larswmh 

Thank you for your confirmation! I did want to check with you before I opened a PR.

- The PR is https://github.com/corona-warn-app/cwa-website/pull/3408 and it is ready for your review now.
