### ISSUE TITLE
Simplify testing description in README

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3410]
This is a suggestion to simplify the information in the [README](https://github.com/corona-warn-app/cwa-website/blob/master/README.md) document regarding testing. Over time this section has grown and now that several workflows have been implemented, it is not necessary to keep all the information at the top level of the documentation hierarchy.

## Current situation

The [README: Testing](https://github.com/corona-warn-app/cwa-website/blob/master/README.md#testing) section contains detailed information on testing with Cypress.

In the meantime most of the tests are integrated into workflows and do not need to be run manually.

## Suggestion

Move detailed testing information from [README: Testing](https://github.com/corona-warn-app/cwa-website/blob/master/README.md#testing) into a new docs/TESTING.md file.

- In the [README](https://github.com/corona-warn-app/cwa-website/blob/master/README.md) file provide instructions for information contributors.
- In the new TESTING.md file provide more detailed information about manually running tests and include instructions for Cypress test maintainers.

---
Internal Tracking ID: [EXPOSUREAPP-14856](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14856)

**Comment by brianebeling** [comment]
Thanks Mike, some housekeeping is definitely due. The question is where to put the information.

A) in the docs folder 
B) in the root folder 

Considering that the docs folder contains file actively needed to work on this project I would like to propose to put it there as well,
post a default one liner for testing and link to the full documentation from the readme.

**Comment by MikeMcC399** [comment]
@brianebeling 

I plan to add a document TESTING.md to the docs folder. I just need to proof-read what I have already written and I will post a new PR soon.

**Comment by MikeMcC399** [comment]
- See PR https://github.com/corona-warn-app/cwa-website/pull/3413
