### ISSUE TITLE
Screenshots says no new features 

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3462]
The message in https://www.coronawarn.app/en/screenshots/

"With this update we are fixing bugs in the app. It does not contain any new features."

conflicts with the statement in https://www.coronawarn.app/en/faq/results/#ramp_down_features

"A reduction in functionality will be implemented in Release 3.2, but this will not be activated until May 1, 2023. Up to and including April 30, 2023, releases 3.1 and 3.2 of the app will therefore not differ in functionality."

**Comment by Ein-Tim** [comment]
I tend to say that this is OK, as this is also how the blog describes the new version as well as how the update information in the app store handles it.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The blog https://www.coronawarn.app/en/blog/2023-04-19-cwa-3-2/ makes no statement about the content of CWA 3.2.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Exactly, in the past new features were always announced via the blog, but not this time.

Also, https://github.com/corona-warn-app/cwa-app-android/releases/tag/v3.2.0 doesn't include any "New Features" paragraph like in the past when new features were implemented, but not this time.

But that's just my two cents.

**Comment by MikeMcC399** [comment]
I guess it depends what you mean by a "feature". If a feature is only something which provides a new function, which is visible in the UI then this is correct.

My understanding of a feature is however broader than that and I consider the additional functions which aid ramp-down, such as switching off Exposure Notifications automatically and changing the layout / and reducing the content of the UI to be a feature. So the features that I am talking about are to remove functionality, not to add it.

However this is described, I think it could be added to the screenshot text to say that CWA 3.2 prepares for the ramp-down.

On a separate point, will there be a new screenshot page published showing the screens after April 30, 2023?

**Comment by MikeMcC399** [comment]
I'm closing this issue. Since CWA 3.2 itself installs with the message "It does not contain any new features", then this is probably the message which should be reflected elsewhere.
