### ISSUE TITLE
Broken link zusammengegencorona wann-muss-ich-in-quarantaene-und-wann-nicht

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3475]
https://www.zusammengegencorona.de/covid-19/wann-muss-ich-in-quarantaene-und-wann-nicht/

found in 

https://www.coronawarn.app/de/faq/results/#quarantine_measures
https://www.coronawarn.app/de/faq/results/#voluntary_self_quarantine

Gives error 404 - not found

I suggest to delete the link in the FAQ.

---
Internal Tracking ID: [EXPOSUREAPP-15087](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15087)

**Comment by larswmh** [comment]
Thanks for your report @MikeMcC399. We're currently considering various ways to handle broken links, as it was internally decided not to delete them from now on. This is similiar to the approach we're taking with the FAQ entries in general. 

We will come back to you here once we have an update on this.

**Comment by MikeMcC399** [comment]
@larswmh 

- Since this is a more general topic, I added a new discussion point https://github.com/corona-warn-app/cwa-website/discussions/3476

**Comment by MikeMcC399** [comment]
If it is not planned to delete the link then this issue becomes obsolete.
