### ISSUE TITLE
Test Links workflow always fails

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3478]
- The [.github/workflows/test-check_links.yml](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/test-check_links.yml) fails permanently.

- This is due to https://github.com/corona-warn-app/cwa-website/issues/3475

## Suggestion

Since it was decided to no longer maintain links, the workflow will always fail.

The suggestion is to disable the workflow

https://github.com/corona-warn-app/cwa-website/blob/f46176e9c2c76876ea45bb8cf9aba3a13569541f/.github/workflows/test-check_links.yml#L10-L12

See [Disabling and enabling a workflow](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow).

---
Internal Tracking ID: [EXPOSUREAPP-15134](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15134)

**Comment by MikeMcC399** [comment]
See for instance Job [4848120363](https://github.com/corona-warn-app/cwa-website/actions/runs/4848120363):

![image](https://user-images.githubusercontent.com/66998419/235407446-0a713cbc-7ae1-4628-a0cf-1a1f68c004ee.png)

**Comment by larswmh** [comment]
Thanks for your suggestion @MikeMcC399. We've disabled the workflow for now.

**Comment by MikeMcC399** [comment]
@larswmh 

The organization needs to make a decision about which pages on the website will be maintained and which pages are allowed to have errors. I have some ideas about how to modify the Cypress tests for this, so let me know if you want some assistance. So long as the website continues to operate, it should use Cypress to help maintain as much quality as is necessary.

**Comment by larswmh** [comment]
@MikeMcC399 

> The organization needs to make a decision about which pages on the website will be maintained and which pages are allowed to have errors. I have some ideas about how to modify the Cypress tests for this, so let me know if you want some assistance. So long as the website continues to operate, it should use Cypress to help maintain as much quality as is necessary.

Thanks for offering your assistance! We also think that Cypress tests should continue to operate as much as possible. What we're thinking of is only checking FAQ entries that are not declared as outdated.

**Comment by MikeMcC399** [comment]
@larswmh 

> Thanks for offering your assistance! We also think that Cypress tests should continue to operate as much as possible. What we're thinking of is only checking FAQ entries that are not declared as outdated.

You also have to consider blogs which will age and over time some of their links can also be expected to fail.
