### ISSUE TITLE
3.2 Screenshots mostly no longer valid

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3481]
The introductory text for https://www.coronawarn.app/en/screenshots/ should say that many screens are not displayed after April 30, 2023 when the app functionality was reduced to certificates and contact journal.

Alternatively there could be a new screenshot page for CWA after EOL showing only the screens still showing.

---
Internal Tracking ID: [EXPOSUREAPP-14765](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14765)
Internal Tracking ID: [EXPOSUREAPP-14634](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14634)

**Comment by Ein-Tim** [comment]
FYI: https://github.com/corona-warn-app/cwa-website/issues/3484#issuecomment-1532025010

And, FYI two, the way I suggest solving this is to update the text
"With this update we are fixing bugs in the app. It does not contain any new features." to "With this update we are fixing bugs in the app. It does not contain any new features. Please note that the screenshots show the implementation before CWA functionality has been reduced on May, 1. (insert a link to the blog here"

I will provide a PR with this suggestion.
