### ISSUE TITLE
Science 5 links to unavailable end-point svc90.main.px.t-online.de

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3514]
The Science 5 blogs

- https://www.coronawarn.app/en/science/2022-03-03-science-blog-5/
- https://www.coronawarn.app/de/science/2022-03-03-science-blog-5/

refer to the disabled exposure notification endpoint http://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date. This URL currently returns HTTP error 404 (not found).

> A further option for estimating the active apps/devices (in the narrower sense) are the [files of the daily keys](http://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date) downloaded by the users of the CWA and provided via the CWA backend.

This link should be removed from the Science 5 blogs.

**Comment by MikeMcC399** [comment]
- Related to the unanswered discussion in https://github.com/corona-warn-app/cwa-website/discussions/3476.

**Comment by Ein-Tim** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/3515

I will point attention to the discussion thread you referred to above, Mike!
