### ISSUE TITLE
@corona-warn-app/cwa-moderators error in CODEOWNERS file

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3538]
[CODEOWNERS](https://github.com/corona-warn-app/cwa-website/blob/master/CODEOWNERS) includes `@corona-warn-app/cwa-moderators` which produces an error

![image](https://github.com/corona-warn-app/cwa-website/assets/66998419/474733ab-6168-4f11-98bb-fc078a51e188)

**Comment by MikeMcC399** [comment]
Also mentioned in [CONTRIBUTING > Engaging in Our Project](https://github.com/corona-warn-app/cwa-website/blob/master/CONTRIBUTING.md#engaging-in-our-project).

**Comment by MikeMcC399** [comment]
Closing due to lack of response on this topic.

**Comment by Ein-Tim** [comment]
@dsarkar please take a look and let me know whether action from our side is required.
