### ISSUE TITLE
Enhance FAQ entry for green/low risk encounters

### ISSUE THREAD

**Issue by daimpi** [corona-warn-app/cwa-website#365]
## Feature description
This is a followup to issue https://github.com/corona-warn-app/cwa-website/issues/307 and PR #319.

The current [FAQ entry](https://www.coronawarn.app/en/faq/#encounter_but_green) on green encounters reads:
>All active Corona-Warn-Apps regularly download the diagnosis keys released on the Corona-Warn-App server and pass them on to the operating system in batches through an interface. The app checks whether any of these received, recorded rolling proximity identifiers match any of the diagnosis keys. If there is a match, this means the following: The user’s smartphone encountered the smartphone of a person who has uploaded a diagnosis key on the day to which the diagnosis key belongs.
>
>In the next step, the app analyzes all the matching rolling proximity identifiers for each diagnosis key, to estimate how long the exposure lasted in total on the day in question and how close the smartphones were to each other on average during the exposure. The distance is calculated from the measured reduction in strength of the Bluetooth signal, which is specified in dB (decibel). All exposures for a diagnosis key that lasted less than 10 minutes in total (regardless of how close the smartphones came during that time) or during which the smartphones were more than 8 meters (73 dB attenuation) apart on average (regardless of how long the exposure lasted) are rated as harmless.
>
>The remaining encounters are rated collectively according to their distance and duration as well as the presumed infectiousness of the other person(s). This rating doesn't always yield an increased risk. This is why the Corona-Warn-App can display encounters, but the risk status stays the same.
>
>For more details about risk assessment, including a sample calculation, see https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md.

I propose the following changes (changes in **bold**):
- "The user’s smartphone encountered the smartphone of a person who has **subsequently** uploaded **their ~~a~~** diagnosis key**s ~~on the day to which the diagnosis key belongs~~**."
The corrected version then reads:  
"The user’s smartphone encountered the smartphone of a person who has subsequently uploaded their diagnosis keys."

Imho the previous version of this statement could be misunderstood to say that the diagnosis key the user matched with was uploaded on the same day the encounter happened which is o/c not the case. This change removes the ambiguity from the statement. Speaking of a specific day in the context of green encounters anyway isn't that useful imho given that green encounters don't show the day on which they happened in CWA.

- "This rating doesn't always yield an increased risk **in which case those encounters - together with the harmless encounters from above - will be shown in the Corona-Warn-App but the risk status will stay the same. ~~This is why the Corona-Warn-App can display encounters, but the risk status stays the same.~~**"
The corrected version then reads: 
"This rating doesn't always yield an increased risk in which case those encounters - together with the harmless encounters from above - will be shown in the Corona-Warn-App but the risk status will stay the same."

This change removes ambiguity on whether "very low risk encounters" (<10min or >73 dB) are shown as "green-/low risk" encounters (which they are) and makes clear that all encounters will be shown at least as green-/low-risk encounters in CWA . 

I've focused on the English version of the FAQ entry for now, but once this version is in a state which makes everyone happy I'd o/c also translate those changes for the [German version](https://www.coronawarn.app/de/faq/#encounter_but_green) 🙂. 

I'd be interested what you think of the proposed changes @svengabr @mtb77 @Ein-Tim 🙂. 
## Problem and motivation
As I [stated](https://github.com/corona-warn-app/cwa-website/pull/319#discussion_r486221652) in the discussion of  #319:
>  The new formulation does indeed fix the repetition, but unfortunately introduces ambiguity whether those "very low risk encounters" (<10min or >73 dB) are shown as "green-/low risk" encounters (which they are). If you're interested I can try to come up with a formulation which unites both aspects later today 🙂

This suggestion should reduce ambiguity in this FAQ entry and give users a clearer picture on how encounters which don't change the overall risk status can happen in CWA.

## Is this something you're interested in working on
Yes. PR: https://github.com/corona-warn-app/cwa-website/pull/366

**Comment by Ein-Tim** [comment]
I think this would be a very good improvement because iwith these changes it is 100% clear that every contact with a positive tested Person recorded by the App will be shown to the user.
PR looks good to me, If you want I could translate the changes into German @daimpi (But you would have to open a PR for the German Version aswell, don't (yet) know how to do it right 😅👍)

Great work Daniel!

**Comment by daimpi** [comment]
@Ein-Tim I'm glad you like it 🙂. 

If you want to work on the German version I'd certainly welcome that. My plan was to change both (English & German version) with PR #366. If you want I can give you access to my fork from which you should be able to directly contribute to the PR afaik. Is this something you'd be interested in? 🙂

**Comment by Ein-Tim** [comment]
@daimpi 

Yes, I would definitely be interested in this.
But maybe we first look what @svengabr and @mtb77 say, just to be sure that these changes are welcome 👍

**Comment by daimpi** [comment]
Sounds good 👍 

I'll invite you to my fork in the meantime 🙂.

**Comment by mtb77** [comment]
I will close this issue in favor of the PR #366
