### ISSUE TITLE
FAQ entry "[Google/Android]: Exposures are displayed for more than 14 days" is outdated

### ISSUE THREAD

**Issue by daimpi** [corona-warn-app/cwa-website#382]
## Where to find the issue
The [German](https://www.coronawarn.app/de/faq/#status_14) and [English](https://www.coronawarn.app/en/faq/#status_14) FAQ entries for "[Google/Android]: Exposures are displayed for more than 14 days".

## Describe the issue
These entries are part of the "Notifications" category and state:
> For some phones running Android, the exposures currently are displayed for more than 14 days. We're working on fixing this display error. You'll find up-to-date information in [GitHub issue 911](https://github.com/corona-warn-app/cwa-app-android/issues/911).

While this issue has actually been resolved in the meantime with the release of CWA 1.3.

## Suggested change
Move those entries to the "Resolved" category and state that the issue has been resolved with the release of CWA 1.3.

**Comment by mtb77** [comment]
Fixed already on the website - thanks for reporting @daimpi !

Cheers,
Sascha
--
Corona-Warn-App Open Source Team

**Comment by daimpi** [comment]
Thanks @mtb77. 

Just a small remark: the new entry states
> UPDATE: Fixed in 1.2.

But [actually](https://github.com/corona-warn-app/cwa-app-android/issues/911#issuecomment-671270561) it was only fixed with CWA 1.3 😉.
