### ISSUE TITLE
New FAQ entry needed "Nach dem Update auf iOS 14 wurde die Risikoermittlung deaktiviert"

### ISSUE THREAD

**Issue by loki-cui** [corona-warn-app/cwa-website#388]
DE:

**[Apple/ iOS] Die Risikoermittlung lässt sich nach dem Update auf iOS 14 nicht mehr aktivieren**

Nach dem Update auf iOS 14 melden einige Nutzer, dass die Risikoermittlung deaktiviert wurde und nicht mehr eingeschaltet werden kann. 

Dieses Problem ist bereits der Entwicklung gemeldet und sie arbeiten an einer Lösung. Um die App bis zur Behebung des Fehlers in vollem Umfang nutzen zu können, gehen Sie bitte wie folgt vor: 

'Einstellungen' > 'Begegnungsüberprüfungen' > 'Aktive Region' (Corona-Warn-App) > 'Corona-Warn-App' > 'Begegnungsinformationen teilen' einmal aus- und wieder einschalten.

Wenn der Fehler weiterhin auftritt, obwohl Sie alle Schritte ausgeführt haben, müssen Sie die Anwendung 1x zurücksetzen und neu installieren.  Ihre gesammelten Zufallscodes gehen dabei nicht verloren ([siehe auch hier](https://www.coronawarn.app/de/faq/#delete_random_ids)). Es dauert jedoch 24 Stunden bis die App wieder auf die bisher gesammelten Daten zurückgreift.  

EN:

**[Apple/ iOS] Risk exposure can no longer be activated after updating to iOS 14**

After updating to iOS 14, some users report that risk exposure has been disabled and can no longer be turned on. 

This problem has already been reported to development and they are working on a solution. To be able to use the app to its full extent until the bug is fixed, please follow these steps: 

Open 'Settings' > 'Exposure notifications' > 'Active region' (Corona-Warn-App) > 'Corona-Warn-App' > Switch 'Share exposure information' off and on again.

If the error still occurs although you have performed all steps, you have to reset and reinstall the application once.  Your collected random ids will not be lost ([see also here](https://www.coronawarn.app/de/faq/#delete_random_ids)). However, it will take 24 hours until the app resumes the data collected so far.

**Comment by cebor** [comment]
Issue persists for me in version 1.3.2 on iOS 14.0.1.

Can anybody confirm this?

**Comment by thomasaugsten** [comment]
Which issue exactly and since when you have this issue

**Comment by cebor** [comment]
Hi @thomasaugsten,

If you do the following its not possible to enable Exposure Logging in the app again:

Open 'Settings' > 'Exposure notifications' > 'Active region' (Corona-Warn-App) > 'Corona-Warn-App' > Switch 'Share exposure information' off and on again.

Only way to enable it again is to reset and reinstall the app.

**Comment by thomasaugsten** [comment]
When you did this you get the notification to check the active app in the iOS settings. Did you check if the app is in the active region?

**Comment by cebor** [comment]
Yes, seems to be all correct. Active region is Germany. I did not get any notification, just did to tests if all is running well.

**Comment by klaus357** [comment]
Nothing helps. I can‘t select an active Region in ‚Begegnungsmitteilungen’ in the IOS. After selecting ‚Begegungsmitteilungen‘ of the Corona- App I geht an empty Screen except of the headline. :-(
IOS 14.0.1, Deinstall/install Corona App, Reset Settings of IOS (a lot of work!)

**Comment by mtb77** [comment]
Quick fix: In the iOS settings
1. switch off WLAN
2. activate the region
3. in the active region, deactivate and reactivate the "share meeting transmission".
4. switch WLAN back on

**Comment by klaus357** [comment]
Unfortunately this also didn’t help. 

I even switched off additionally the mobile net. Then I got the message “Das kann einige Minuten dauern” but nothing happened after about 20 Minutes. 

:-(

Best regards

Klaus

**Comment by thomasaugsten** [comment]
This error doesn't fit to this settings. Can you please provide a screenshot of this error?
I attached a video about the activation process.
![RPReplay_Final1601361637](https://user-images.githubusercontent.com/6367738/94523303-42111180-0231-11eb-9146-acae73cbb531.gif)

**Comment by klaus357** [comment]
Sorry for the late answer, the mail was in the unknown folder. 

Here is the flow:





At the end everything is like it was at the beginning 

Best regards 

Klaus
