### ISSUE TITLE
Illogical value for font-family attribute

### ISSUE THREAD

**Issue by ulrichstark** [corona-warn-app/cwa-website#39]
https://github.com/corona-warn-app/cwa-website/blob/3849875c7db2407bdf0f76ad8d08c14750800877/src/assets/scss/_variables.scss#L401

1. `Roboto` is a duplicate entry in the list (quotations make no difference if font family doesnt contain any spaces)
2. the generic font family `sans-serif` in the middle of the list makes it impossible for the following entries ever being used

**Comment by charakterziffer** [comment]
About your point 2: The fonts after `sans-serif` are there for emojis. They will be used when the default sans hasn’t emojis.
