### ISSUE TITLE
FAQ: Matched Key Count (Apple) | Number of matches (Android)

### ISSUE THREAD

**Issue by phil-dreher** [corona-warn-app/cwa-website#398]
Hi everyone,

I have a question (or issue?) concerning the wording in the description (and possibly also the naming in the iOS app) of the reported matches.

The description reads: "This is the **number of keys that your phone collected** for which there is a matching diagnosis key. ..."
(my highlighting, https://www.coronawarn.app/en/faq/#keys_matches)

However, the CWA documentation, as well as Google's documentation of the API for Exposure Notifications state, that the user's devices do not share and collect "keys" via bluetooth - which I would understand as the "temporary exposure keys" and/or "diagnosis keys" in this context (which are generated daily and only sent to the server in case of a positive test result) - but "rolling proximity identifiers" or "non-identifiable Bluetooth beacons" (which are generated every 10-20 minutes based on the temporary exposure keys).
(https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md | https://developers.google.com/android/exposure-notifications/meaningful-exposures | https://developers.google.com/android/exposure-notifications/exposure-notifications-api#glossary)

This in turn would mean either that the "Number of matches" refers to one or more _downloaded_ (not "collected") diagnosis key that match an unidentified number of RPIs on the device, or that it does _not_ refer to matching diagnosis keys, but to one ore more matching RPIs connected to one diagnosis key downloaded from the server (in which case it would also be wrongly named in the iOS app).

The question behind this is: what does a higher "Number of matches" for one daily entry/daily temporary exposure key on my device mean? Does it mean that I definitely encountered several positive persons in one day, or that I possibly encountered the same positive person several times?

Thank you for your answers!
phil

**Comment by daimpi** [comment]
> The description reads: "This is the number of keys that your phone collected for which there is a matching diagnosis key. ..."

You're correct, the formulation in the FAQ is not very precise in this regard. 

> Matched Key Count (Apple) | Number of matches (Android)

is actually the number of Diagnosis Keys (DKs) for which your phone collected at least one matching RPI.

For a more detailed explanation see my post here: https://github.com/corona-warn-app/cwa-app-ios/issues/1096#issuecomment-688235743

**Comment by phil-dreher** [comment]
Ok, thank you for the clarification!

**Comment by svengabr** [comment]
Thank you very much for your input @daimpi
