### ISSUE TITLE
[Android] Text change: 9002 Error Recovery Notice

### ISSUE THREAD

**Issue by svengabr** [corona-warn-app/cwa-website#429]
## Scope:
Adjust the texts introduced by https://github.com/corona-warn-app/cwa-app-android/pull/1254/files with the next text and FAQ link.

## New German text in-app popup error message:
> Aufgrund eines technischen Problems wurde Ihre App zurückgesetzt. Dies hat keine Auswirkung auf die Risiko-Ermittlung und damit auf Ihren Risikostatus. Sie werden weiterhin über Risiko-Begegnungen benachrichtigt und können andere warnen, falls Sie positiv auf COVID-19 getestet wurden. Durch das Zurücksetzen der App gehen aber zuvor eingelesene QR-Codes für die elektronische Benachrichtigung über Ihre Testergebnisse verloren. Bitte wenden Sie sich an Ihren Hausarzt oder Labor, um Ihr Testergebnis zu erfahren.

## FAQ link:
(to be created, please already use it in the app)
https://www.coronawarn.app/de/faq/#cause9002_recovery

## Background:
This is in response to community feedback: https://github.com/corona-warn-app/cwa-app-android/pull/1254#issuecomment-700923352

---
Internal Tracking ID: EXPOSUREAPP-3106

**Comment by svengabr** [comment]
Still waiting for the final texts

**Comment by svengabr** [comment]
We need to create a FAQ entry that is a little bit more detailed than the error message mentioned in the issue description.

**Comment by vaubaehn** [comment]
Placeholder: Proposal for FAQ entry (related to https://github.com/corona-warn-app/cwa-app-android/pull/1254#issuecomment-704899062)

Delayed till tonight!

**Comment by vaubaehn** [comment]
Hi @svengabr , the proposal for [FAQ-entry 9002_recovery arrived](https://github.com/corona-warn-app/cwa-website/issues/429#issuecomment-705450112)!

Hi @d4rken and @thomasaugsten , would you kindly review the text for technical accuracy? Thanks very much in advance!

**Comment by SabineLoss** [comment]
Reviewed by UA --- Please find here my proposal (Text shortened a little bit and changed to German comma placement ;-)) We'll adapt the english text accordingly as soon as the technical accuracy has been checked.  

[Google/Android]: Meldung: "Etwas ist schiefgelaufen. Aufgrund eines technischen Problems wurde Ihre App zurückgesetzt." #cause9002_recovery

Ab Corona-Warn-App Version 1.5.0 oder höher kann es vorkommen, dass Sie nach dem Öffnen der App die Benachrichtigung „Etwas ist schiefgelaufen. Aufgrund eines technischen Problems wurde Ihre App zurückgesetzt.“ sehen.

Was ist passiert?
Beim Zugriff auf die Datenbank ist es zu einem Fehler gekommen, der dazu führt, dass nicht mehr auf die verschlüsselten Daten zugegriffen werden kann. Die Corona-Warn-App hat diesen Fehler erkannt und die Datenbanken automatisch zurückgesetzt, so dass der Zugriff nun wieder funktioniert und die Corona-Warn-App Sie weiterhin über Ihren Risikostatus informieren kann. Weitere technische Details zu diesem Problem finden Sie unten.

Was sollten Sie beachten?
Das Zurücksetzen der Datenbanken hat keine Auswirkung auf die Risiko-Ermittlung und damit auch nicht auf Ihren Risikostatus. Alle aufgezeichneten Begegnungen mit anderen Personen, die die App nutzen, bleiben erhalten. Sie werden weiterhin über Risiko-Begegnungen benachrichtigt und können andere warnen, falls Sie positiv auf COVID-19 getestet wurden.

Falls Sie aber einen QR-Code für die elektronische Benachrichtigung über einen COVID-19-Test eingelesen haben und Ihnen das Testergebnis bislang noch nicht in der App übermittelt wurde, ist durch das Zurücksetzen der Datenbanken die Registrierung des Tests für die elektronische Übermittlung verloren gegangen. Aus Datenschutzgründen kann der QR-Code leider nicht mehr erneut eingelesen werden. Bitte wenden Sie sich an Ihren Arzt oder das Labor, um Ihr Testergebnis zu erfahren.

Durch das Zurücksetzen der Daten geht auch die Information verloren, wie lange Ihre App bereits aktiv war (die Anzahl der aktiven Tage wird auf 0 gesetzt). Gegebenenfalls wurden auch Einträge aus der Historie der Begegnungsaufzeichnungen entfernt, die Sie über die Einstellungen zu Ihrem Google-Konto erreichen. Dies hat jedoch keine Auswirkungen auf die Risiko-Ermittlung und Ihren Risikostatus. Spätestens nach 24 Stunden sollte Ihnen Ihr Risikostatus wieder angezeigt werden und neue Einträge in der Historie der Begegnungsaufzeichnungen sollten erscheinen.

Technischer Hintergrund
Die Corona-Warn-App wurde mit höchsten Ansprüchen an den Datenschutz entwickelt. Dafür werden einerseits Daten verschlüsselt abgespeichert und andererseits der Programmcode der App öffentlich zur Begutachtung zur Verfügung gestellt (Open-Source-Ansatz). Um eine Datenverschlüsselung für eine App zu realisieren, greifen Entwickler gerne auf in der Vergangenheit bereits gut erprobte Programmmodule zurück, die von anderen Entwicklern ebenfalls als Open-Source zur Verfügung gestellt werden. Auf diese Weise kann Transparenz für sämtliche Bestandteile der Corona-Warn-App gewährleistet werden. Erst kürzlich wurde bekannt, dass ein Verschlüsselungsmodul, das auch von der Corona-Warn-App genutzt wird, fehlerhaft funktioniert, wenn der im Android Betriebssystem integrierte Speicher für Schlüssel oder Passwörter nicht zuverlässig reagiert. Dieser Fehler führt dazu, dass eine verschlüsselte Datenbank nicht mehr geöffnet werden kann. Das wiederum führt dazu, dass einige Nutzer die Meldung "Ursache: 9002 Etwas ist schief gelaufen (sqlite)" sehen oder sich die App nicht mehr öffnen lässt. Selbstverständlich wird die Corona-Warn-App vor jeder Veröffentlichung eines Updates gründlich getestet. Allerdings trat dieser Fehler während der Tests nie auf und er lässt sich auch jetzt nur schwer reproduzieren.

Allen beteiligten Seiten arbeiten fieberhaft an einer Behebung des Fehlers.

**Comment by d4rken** [comment]
@vaubaehn Looks good from a technical POV.

**Comment by vaubaehn** [comment]
Hi @d4rken , thanks for your review!

Hi @SabineLoss ,
> Please find here my proposal [...] and changed to German comma placement ;-)

this is how I express and live freedom in Arts ;)

**Comment by svengabr** [comment]
Thank you very much for your input @vaubaehn!

I did the required code changes and created a pull request https://github.com/corona-warn-app/cwa-website/pull/443

**Comment by vaubaehn** [comment]
So we have a date: 17.10.2020
Do you feel like integrating bold formatting for few sentences like in my proposal to your PR?
Do you feel like integrating the links to other FAQ sections like in my proposal to your PR?

**Comment by svengabr** [comment]
Ah yes, of course, @vaubaehn! Sorry, that slipped through since I was using the reviewed Revision from Sabine. I will add the links so they will be ready for the release.

**Comment by vaubaehn** [comment]
@svengabr
lgtm 👍
