### ISSUE TITLE
[iOS] Add FAQ entry: Clarify whether Power Saving Mode disables background updates

### ISSUE THREAD

**Issue by heinezen** [corona-warn-app/cwa-website#435]
Apple's power saving mode disables background activity in the app according to: https://support.apple.com/de-de/HT205234

We already have a similar FAQ  Entry for Android power saving modes (https://www.coronawarn.app/de/faq/#no_risk_update). A similar issue for Apple does make sense, since background updates are critical for the functionality of the App.

## Suggested changes

1. Inform users about the problems with Apple's power saving mode
2. Deliver instructions on how to disable power saving mode

**Comment by Ein-Tim** [comment]
@heinezen 
Are you sure that also Background Updates from CWA are blocked.
I unfortunately can't remember wehre but somewhere in the iOS Repo I read that the Background Updates are still continued, even in Power Saving Mode. Maybe you'll first clarify this with the other Devs/Apple?

**Comment by heinezen** [comment]
@Ein-Tim 
This issue is made mainly for discussion on how we clarify it and to not forget about it :)
I've edited the issue to reflect that we are still discussing it. Some AppStore reports suggest that power saving settings are a problem and the information from Apple's side is really not that clear. I think you are refering to https://github.com/corona-warn-app/cwa-app-ios/issues/650 (?).

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
> I think you are refering to corona-warn-app/cwa-app-ios#650 ?

Yes I am, thanks for the Link 👍

> This issue is made mainly for discussion on how we clarify it and to not forget about it :)

Perfect, thanks for your quick response. 

If you want I could do a test:
I can go into Power Saving mode on my second phone, an iPhone 6s which I never use and which always has good internet & a full battery. 

That would be definitely only one part of the testing which has to be done to clarify this, but it could be a hint 

So lemme know if this is welcome by you (-:

**Comment by heinezen** [comment]
> If you want I could do a test:
> I can go into Power Saving mode on my second phone, an iPhone 6s which I never use and which always has good internet & a full battery.

Of course! More information is always better. Thanks for contributing!

**Comment by Ein-Tim** [comment]
@heinezen 
Okay, left my phone (iPhone 6s) in Power Saving mode for the last 4 days and yep, CWA always done an check in the background.
So theoretically  the Background Task is running and (how I've seen) Fallback Strategies are also working.

But please note:
This Test was on a phone which had between 100 and 30%, had always good Internet and wasn't used for other things. 
The most users will turn Power Saving Mode on when they have low battery (>20%) and I personally think that iOS will reduce Background Tasks more and more if the Battery gets emptier and emptier.

So I think a FAQ entry would be good, but I'm still thinking how to formulate it.

**Comment by heinezen** [comment]
@Ein-Tim 

Thanks so much for testing this. Looks like background activity is not affected by default then, at least in your case. However, that begs the question why some users still reported it as an issue. Maybe there are other issues at play for them.

I've also looked around a bit more and there's no official clarification from Apple that I can find. So the only conformation that it works is https://github.com/corona-warn-app/cwa-app-ios/issues/650#issuecomment-644878582. https://support.apple.com/de-de/HT205234 is very broad and not very informative from a CWA point of view. 

We'll have to talk to the devs so they can maybe get a reconfirmation from Apple. From the feedback we get, we can hopefully draft something more informative.

----
Corona-Warn-App Open Source Team

**Comment by svengabr** [comment]
@heinezen is there still the need in writing or updating any FAQ entry? If not, you could consider closing this issue.

**Comment by heinezen** [comment]
@svengabr I am currently waiting for more information from SAP on this.

Should not be closed until we get a clarification from their side.

**Comment by heinezen** [comment]
We finally got feedback from the testing labs and will start drafting an FAQ entry soon.

**Comment by heinezen** [comment]
Addressed in #552

**Comment by Ein-Tim** [comment]
Perfect, looks good to me 👍
