### ISSUE TITLE
FAQ entry "Error when communicating with Google API (39508)"  improvement

### ISSUE THREAD

**Issue by daimpi** [corona-warn-app/cwa-website#439]
## Where to find the issue
[German](https://www.coronawarn.app/de/faq/#API39508) and [English](https://www.coronawarn.app/en/faq/#API39508) FAQ entry for the API 39508 issue.

## Describe the issue
The entry currently instructs the users to wait for 24h, but if this doesn't help it directs them to call the hotline or open an issue on Github:
> If it still occurs afterwards, please call the hotline or open an issue on GitHub.

As this issue most likely cannot be solved by the user in such cases, redirecting them to the hotline unnecessarily increases load for them and creating a new issue leads to duplicates on Github.

## Suggested change
Redirecting such cases (where the issue didn't disappear after 24h) to the [already existing GH issue](https://github.com/corona-warn-app/cwa-app-android/issues/1021) would be a better approach imo.

Also: maybe you could say that a fix for this problem will be rolled out with CWA 1.5 which is currently targeted for release at the end of October.

**Comment by heinezen** [comment]
You are probably right that it creates a lot of unnecessary duplicates.

I propose we change it to the following:

> If it still occurs afterwards, please comment in the [associated GitHub issue](https://github.com/corona-warn-app/cwa-app-android/issues/1021) and provide the following information about your phone:
>   * Device name
>   * Android version
>   * CWA App version

----

> Sofern die Meldung auch nach 24h weiterhin auftritt, schreiben Sie bitte einen kurzen Kommentar im zugehörigen Github Issue zusammen mit folgender Information über Ihr Gerät:
>   * Name des Geräts
>   * Androidversion
>   * Appversion der CWA

Additionally, one of the screenshots from the issue thread should be copied to the first comment, so that people can compare their error with that.

What do you think @daimpi ?

**Comment by daimpi** [comment]
@heinezen sounds good to me 👍.

**Comment by PalminX** [comment]
With the delay in a fix (with CWA 1.5), it is extremely important to update the FAQ as soon as possible, the current state is extremely confusing for end users.

**Comment by svengabr** [comment]
Thank you for your feedback @daimpi! I have added the texts from @heinezen to the FAQ website.
