### ISSUE TITLE
FAQ intra-links problem when using search

### ISSUE THREAD

**Issue by daimpi** [corona-warn-app/cwa-website#440]
## Where to find the issue
On the [FAQ page](https://www.coronawarn.app/en/faq/) (English and German).

## Describe the issue
If you enter a search-term (e.g. "[matches](https://www.coronawarn.app/en/faq/?search=matches)") you will be presented with a selection of FAQ entries matching this keyword. If those entries (e.g. the one for "What do the exposure check logs show?") contain a link to another FAQ entry, left-clicking this link will not open the linked FAQ entry if the linked entry is not also part of the search results selection (opening the link in a new tab works though).

## Suggested change
Clicking (or tapping on a smartphone) should bring you to the linked FAQ entry.

**Comment by svengabr** [comment]
Thanks for your report @daimpi! In my eyes, this was a critical issue and I did publish a hotfix to restore this basic functionality.
