### ISSUE TITLE
New FAQ-entry reg. Interop-Gateway-Services 

### ISSUE THREAD

**Issue by loki-cui** [corona-warn-app/cwa-website#447]
URLs to be used: 

**DE**
https://www.coronawarn.app/de/faq/#interoperability_countries 

Gemeinsam mit der EU-Kommission wurde eine Infrastruktur für einen sicheren Informationsaustausch entwickelt, die als sog. “Interoperability Gateway” bezeichnet wird. Dieses Gateway ermöglicht, dass die Corona-Warn-App über Landesgrenzen hinaus funktioniert und auch im Ausland potentielle Warnmeldungen empfangen werden können. 

Nachstehend finden Sie eine Liste der derzeit teilnehmenden Länder und Angaben zu den zuständigen Gesundheitsbehörden: 
(Stand: 14.10.2020)

[Pls. implement & format the following information as table]

**Land:**
Kroatien
(ab 30.10.2020)

**Verantwortlicher:**
AZOP Croatian Personal Data Protection Agency

**Kontaktdaten:**
AZOP Croatian Personal Data Protection Agency
Selska cesta 136
10000 Zagreb
Croatia     
E-Mail: azop@azop.hr       
Telefon: + 385 14609000

**Land:**
Tschechien
(ab 31.10.2020)

**Verantwortlicher:**
Ministry of Health

**Kontaktdaten:**
Ministry of Health
Palackého náměstí 4
120 00 Praha 2
Czech Republic      
E-Mail: mzcr@mzcr.cz 
Telefon: +420 224971111

**Land:**
Dänemark
(ab 27.10.2020)

**Verantwortlicher:**
Styrelsen for Patientsikkerhed (Danish Patient Safety Authority)

**Kontaktdaten:**
Styrelsen for Patientsikkerhed
Islands Brygge 67
2300 København S
Denmark
E-Mail: stps@stps.dk
Telefon: +45 72286600

**Land:**
Deutschland
(ab 17.10.2020)

**Verantwortlicher:**
Robert-Koch-Institut

**Kontaktdaten:**
Robert-Koch-Institut
Nordufer 20
13353 Berlin
Germany
E-Mail: CoronaWarnApp@rki.de
Telefon: +49 30187540

**Land:**
Irland
(ab 19.10.2020)

**Verantwortlicher:**
Health Service Executive

**Kontaktdaten:**
Dr Steevens’ Hospital
Steevens Lane
Dublin 8
Irland
E-Mail: cio@hse.ie
Telefon: +353 87 688   3565

**Land:**
Italien
(ab 19.10.2020)

**Verantwortlicher:**
Ministry of Health

**Kontaktdaten:**
Ministry of Health
Viale Giorgio Ribotta 5
00144 Rome
Italy       
E-Mail: segretariato.generale@sanita.it
Telefon: +39 65994694546

**Land:**
Lettland
(ab 19.10.2020)

**Verantwortlicher:**
Centre for Disease Prevention and Control

**Kontaktdaten:**
Centre for Disease Prevention and Control
Duntes Street 22, k-5
LV-1005 Riga
Latvia
E-Mail: pasts@spkc.gov.lv        
Telefon: +371 67501590

**EN**
https://www.coronawarn.app/de/faq/#interoperability_countries

Together with the European Commission, an infrastructure for secure information exchange has been developed, known as the "Interoperability Gateway". This gateway enables the Corona Warn App to operate across national borders and to receive potential warning messages abroad. 

Below is a list of currently participating countries and details of the responsible health authorities: 
(status: 14.10.2020)

[Pls. implement & format the following information as table]

**Country:**
Croatia
(from 30.10.2020)

**Data controller:**
AZOP Croatian Personal Data Protection Agency

**Contact details:**
AZOP Croatian Personal Data Protection Agency
Selska cesta 136
10000 Zagreb
Croatia     
E-Mail: azop@azop.hr       
Phone: + 385 14609000

**Country:**
Czech Republic
(from 31.10.2020)

**Data controller:**
Ministry of Health

**Contact details:**
Ministry of Health
Palackého náměstí 4
120 00 Praha 2
Czech Republic      
E-Mail: mzcr@mzcr.cz 
Phone: +420 224971111

**Country:**
Denmark
(from 27.10.2020)

**Data controller:**
Styrelsen for Patientsikkerhed (Danish Patient Safety Authority)

**Contact details:**
Styrelsen for Patientsikkerhed
Islands Brygge 67
2300 København S
Denmark
E-Mail: stps@stps.dk
Phone: +45 72286600

**Country:**
Germany
(from 17.10.2020)

**Data controller:**
Robert-Koch-Institut

**Cotact detailsr:**
Robert-Koch-Institut
Nordufer 20
13353 Berlin
Germany
E-Mail: CoronaWarnApp@rki.de
Phone: +49 30187540

**Country:**
Ireland
(from 19.10.2020)

**Data controller:**
Health Service Executive

**Contact details:**
Dr Steevens’ Hospital
Steevens Lane
Dublin 8
Irland
E-Mail: cio@hse.ie
Phone: +353 87 688   3565

**Country:**
Italy
(from 19.10.2020)

**Data controller:**
Ministry of Health

**Contact details:**
Ministry of Health
Viale Giorgio Ribotta 5
00144 Rome
Italy       
E-Mail: segretariato.generale@sanita.it
Phone: +39 65994694546

**Country:**
Latvia
(from 19.10.2020)

**Data controller:**
Centre for Disease Prevention and Control

**Contact details:**
Centre for Disease Prevention and Control
Duntes Street 22, k-5
LV-1005 Riga
Latvia
E-Mail: pasts@spkc.gov.lv        
Phone: +371 67501590

**Comment by MikeMcC399** [comment]
@loki-cui @svengabr 

It seems like there should also be a change to the following [FAQ text](https://www.coronawarn.app/en/faq/#test_in_other_country) on Oct 17, 2020.

>### Can I enter positive test results from other countries?
>Unfortunately not. Every positive test result that you enter in the app must be verified by labs before. The labs make sure that the result is not entered wrongly or on false pretense. At the moment, only labs in Germany are connected for verification. Therefore, you cannot enter a positive result that was tested in another country, for example, the Netherlands.

**Comment by loki-cui** [comment]
@MikeMcC399 : Thanks for your feedback. We will clarify this and amend the text if necessary.

**Comment by loki-cui** [comment]
@MikeMcC399 : The FAQ-entry reg. other countries ([link](https://www.coronawarn.app/en/faq/#test_in_other_country) is not obsolete and will stay the same as it will not be possible to enter a positive test result from a foreign country. But in case you return from your vacation abroad and are positive tested, you can warn all people you met during the last 14 days  And you'll also receive warnings during your vacation or business trip abroad as the keys are exchanged between the participating countries.

**Comment by MikeMcC399** [comment]
@loki-cui 
Thank you for clarifying about https://www.coronawarn.app/en/faq/#test_in_other_country and I apologise for hijacking this thread! Good luck with the release!

**Comment by uschindler** [comment]
@loki-cui but if you have a sheet of paper with a positive result, you can call hotline to get a tele tan. They will do test questions if the document you have is real and then provide a teletan. Why should this not work with a test from Netherlands.

I have for example a (luckily negative) result from Hospital Notaufnahme (I had an urgency with Blinddarm) that was handed out to me in the Arztbrief when released from Hospital, so it's just some line in the lab results of the multi page letter. If that would have been positive, I would have called the Hotline to get a Teletan.
Where is the difference between a test result from a german Hospital Notaufnahme to a foreign result? I can scan and fax it to hotline, if needed. 😉

**Comment by loki-cui** [comment]
@uschindler: This process is correct for Germany. But every positive test result that you enter in the app must be verified by labs before. The labs make sure that the result is not entered wrongly or on false pretense. At the moment, only labs in Germany are connected for verification. Therefore, you cannot enter a positive result that was executed in another country, for example, the Netherlands. Sorry for only copying the content from a FAQ entry, but this is the best answer I can provide.

**Comment by stefanb** [comment]
Where does the above list of countries and their health authorities come from? 
What is the process of including additional countries, eg Slovenia?

**Comment by MikeMcC399** [comment]
@stefanb 
> Where does the above list of countries and their health authorities come from?
What is the process of including additional countries, eg Slovenia?

If you don't get an answer here, you might try the contacts listed in the [EU press-release - Coronavirus: Commission starts testing interoperability gateway service for national contact tracing and warning apps Sep 14, 2020](https://ec.europa.eu/commission/presscorner/detail/en/IP_20_1606).

The [European Commission](https://ec.europa.eu/info/index_en) hosts a page [eHealth and COVID-19](https://ec.europa.eu/health/ehealth/covid-19_en) however I couldn't find any process or contact details there.
