### ISSUE TITLE
[iOS]: Minimum OS requirement will change to 13.6 with release 1.5

### ISSUE THREAD

**Issue by loki-cui** [corona-warn-app/cwa-website#452]
Pls. update the following FAQ entries and pages with regards to the amended minimum OS requirements: With release 1.5 onwards, the minimum requirement is 13.6 (and no longer 13.5). This has no effect on the supported devices. The iPhone 6s is still the "oldest" phone supported.

https://www.coronawarn.app/de/faq/#minimum_requirements
https://www.coronawarn.app/de/faq/#ios135

plus home: "So funktioniert die App am besten" 
![image](https://user-images.githubusercontent.com/69584390/96224735-56bf0a80-0f90-11eb-847b-52208e05107b.png)

and EN version.

**Comment by daimpi** [comment]
Maybe would be good to maintain those versions centrally as [suggested](https://github.com/corona-warn-app/cwa-website/issues/292) by @tkowark for the current app version 🙂.

**Comment by loki-cui** [comment]
@svengabr : Can you have another look at the proposal?

**Comment by svengabr** [comment]
I will add the versions to a central location starting with the app release 1.5+

**Comment by Ein-Tim** [comment]
@svengabr maybe you could in the same steps also take a look at my PR #438 and update the Link on the Main Page 👍

**Comment by svengabr** [comment]
@Ein-Tim done!
