### ISSUE TITLE
FAQ entry "[Apple/iOS]: 'COVID-19 exposure logging... - Weekly Update'" is outdated

### ISSUE THREAD

**Issue by daimpi** [corona-warn-app/cwa-website#454]
## Where to find the issue
The [German](https://www.coronawarn.app/de/faq/#notif_weekly_update) and [English](https://www.coronawarn.app/en/faq/#notif_weekly_update) FAQ entry regarding "[Apple/iOS]: 'COVID-19 exposure logging... - Weekly Update'"

## Describe the issue
Those entries are part of the "Notifications" category and they don't mention that the issue they're describing [has actually been resolved](https://github.com/corona-warn-app/cwa-app-ios/issues/1011#issuecomment-702004886) with ~the latest iOS version~ iOS 13.7.

## Suggested change
Move those entries to the "Resolved" category and ask users to update to the latest iOS version in order to avoid those confusing iOS notifications.

**Comment by ndegendogo** [comment]
> issue they're describing has actually been resolved with the latest iOS version.

Exactly which iOS version is resolving this?
I have heard user reports on observed behaviour of beta versions so far only ...

**Comment by Ein-Tim** [comment]
@ndegendogo 
Since iOS 13.7 this Notification isn't existing anymore.

**Comment by daimpi** [comment]
@ndegendogo 
> I have heard user reports on observed behaviour of beta versions so far only ...

Does this mean you heard from users with beta version who experienced this problem (i.e. weird iOS Notifications about "number of contacts") or does this mean you heard from them that this issue is resolved?

**Comment by ndegendogo** [comment]
well - my understanding is that Apple changed this from weekly to monthly notification. But, yes, I think additionally they have changed the message

**Comment by Ein-Tim** [comment]
@ndegendogo 
Yes, the message doesn't include any number anymore

**Comment by loki-cui** [comment]
@heinezen : Can you pls. take over this issue? There is indeed no weekly reporty anymore. I suggest to move the FAQ-entry to "Geklärt/ Solved" and add a respective comment.

**Comment by ndegendogo** [comment]
iOS 13.7 ( and probably all newer) has a setting where you can deactivate this (meanwhile monthly) notification.

**Comment by Ein-Tim** [comment]
Yes, iOS 14 and above also have this Option @ndegendogo

**Comment by daimpi** [comment]
Is this option by default on or off? 

If I understand you correctly @Ein-Tim this notification doesn't include anything on the number of contacts anymore, right?
> Yes, the message doesn't include any number anymore

**Comment by Ein-Tim** [comment]
@daimpi 
Its turned on by default and yes there is nothing included anymore but the message (which said something like: "Dein iPhone sucht weiterhin für dich nach Kontakten mit [...]"
Will send you a screenshot when I receive this notification the next time 👍

**Comment by heinezen** [comment]
@loki-cui On it!

**Comment by Ein-Tim** [comment]
@daimpi 
There you go:
![B5076FE0-2570-4920-B7A4-0D2747CAE362](https://user-images.githubusercontent.com/67682506/97262419-1463bc00-1821-11eb-969c-518c177cb843.png)

**Comment by svengabr** [comment]
@Ein-Tim Do you suggest re-opening the issue and change the text accordingly from weekly update to monthly update?

**Comment by Ein-Tim** [comment]
@svengabr 
No I do not think this is necessary, with the explanation how to turn it off in the current FAQ Entry everything should be clear 👍
Posted the Screenshot only to show @daimpi how the Message looks like, sorry for the confusion

**Comment by svengabr** [comment]
Alright, thanks for the clarification!

**Comment by Ein-Tim** [comment]
@svengabr You marked the Issue https://github.com/corona-warn-app/cwa-app-ios/issues/1096 as hot topic, but we 
a) now have a FAQ entry about this and 
b) Apple solved this Issue in iOS 13.7 and above
so maybe you could remove the label and close the Issue? 
Thanks!

**Comment by heinezen** [comment]
@Ein-Tim We have fixed the labelling ad closed the issue :)
