### ISSUE TITLE
Restaurant mode

### ISSUE THREAD

**Issue by dstango** [corona-warn-app/cwa-website#462]
## Feature description

Consider adding the option to "check in" at a restaurant or other public place. It could be an addition (or possibly substitute) to the usual list where one has to put his/her name. 

Instead of the usual bluetooth-id of other users, the app would take a note of an id of a place. This could simply be the geolocation of the place on google maps or the likes, or the name on google maps (or any other choosen map provider), or some other suitable location identifier. 

Example szenario:
I open the app and check in at cafe "Chat noir". The app takes a note of the place and time. I could either use the geo location to identify the place, or type in a location identifier visible at the cafe's menu, wall, or registration form. 
I might choose to have the app check out automatically when I leave the place or (if I'm not comfortable with the app constantly tracking my geolocation) might say: I intend to stay for 2 hours. I might check out early,  but making that mandatory would probably not work well, as it's likely one might forget it when leaving. 
It would be a political decision whether I would be relieved from putting my name into the list. (Probably I would for the time being tick a box on whatever form saying I also did a app check in, informing the Gesundheitsamt that I can get my information that way. )

Two days later another guest gets diagnosed with corona. He tells the Gesundheitsamt to have been at Cafe "Chat noir" and the time. The guest doesn't have to be a user of the app. The Gesundheitsamt then triggers a corona warning for the cafe and time window. This warning gets added to the central list of infected persons (which is now expanded to "possibly infected places"). If the corona patient is a user of the app himself the place gets added to the list automatically. 

The next time my app updates its database it receives the location id together with the time. It matches it with my "checked in places" and tells me that I might have been in a risky place at the time reported. 

## Problem and motivation

The benefit of the app is available currently limited to people that mutually use the app, which is only a fraction of the population. This would extend the usefulness by:
- adding warnings about encounters with people that don't use the app themselves
- releaving the burden of the Gesundheitsämter in contacting people after an infection, as they can easily contact the people at risk in a batch
- if a political decision would be taken for a "form waiver" if I use the app it would provide a big incentive for people to use the app, which would also increase the overall usefulness as the user number increases. 

Further extensions might include support for
- Corona-Restaurant-beacons that would make manual check in superfluous
- support for table numbers or the likes
- in larger locations (big restaurant with several rooms) it might be a good idea to have sublocations (room numbers or similar) to limit the number of false positives. 

## Is this something you're interested in working on

I can provide ideas, but I"m currently not deep enough in the technology used for the app to help developing the code base.

**Comment by dstango** [comment]
Only after writing this idea down I realized that it probably the wrong repository, was it seems to be about the website only. So I cross posted it here: https://github.com/corona-warn-app/cwa-backlog/issues/32
Please consider deleting or closing it here if it's the wrong place or help me find the right place to post this suggestion. Thank you!

**Comment by Ein-Tim** [comment]
@dstango Could you close your Issue here and see my comment in the Documentation Repo.
Thanks.

**Comment by dstango** [comment]
yes, sorry. Read it there.
