### ISSUE TITLE
HTTP request to /assets/img/icons/ results in a 403

### ISSUE THREAD

**Issue by mfranzke** [corona-warn-app/cwa-website#47]
## Where to find the issue
https://www.coronawarn.app/en/

## Describe the issue
When analyzing the network requests, a 403 on the request https://www.coronawarn.app/assets/img/icons/ comes up:
![image](https://user-images.githubusercontent.com/787658/84587555-75659700-ae20-11ea-9021-7f1f32add896.png)

## Suggested change
Could be related to the entry `/cwa-website/src/data/global.json` on line 3, but not sure so far how this actually works.

**Comment by tkowark** [comment]
These requests seem to have been a byproduct of the issue fixed in this PR: https://github.com/corona-warn-app/cwa-website/pull/46

At least I can no longer reproduce the 403s. Please let us know if the error still occurs on your end.

**Comment by mfranzke** [comment]
Me neither. Thanks.
