### ISSUE TITLE
Incorrect instructions for accessing list of countries in Android app

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#482]
## Where to find the issue
https://www.coronawarn.app/en/blog/2020-10-19-version-1-5/ 
"New features: Corona-Warn-App Version 1.5 is now available for download
Janina Hoerdt on October 19, 2020"

Section **Support of the EU Interoperability Gateway**
last sentence "A list of participating countries is accessible via the detail screen of the risk assessment."

## Describe the issue
In CWA Android 1.5.0 the detail screen of the risk assessment does not show a list of participating countries.
The screenshot shown is not from the detail screen.

## Suggested change
For Android: A list of participating countries is accessible via the three dot menu on the top right of the app. Select Settings then Exposure Logging followed by Transnational Exposure Logging.

**Comment by GisoSchroederSAP** [comment]
Very attentive, Mike, thank you. Your feedback is much appreciated. 
I'm going to forward your feedback to the team that hosts the blog entries. They will correct the entries.

**Comment by heinezen** [comment]
Fixed by https://github.com/corona-warn-app/cwa-website/commit/ed8af93023ae3b70a4f5a4780ff5d49a218905df

**Comment by MikeMcC399** [comment]
@heinezen 

The text has been changed to:
> Android users can find a list of participating countries via the three dot menu on the top right of the home screen of the app. There the user has to select “Settings”, followed by “Exposure Logging” and last “Transnational Exposure Logging” to get access. However, iOS users can get access to this list via “Exposure Logging” on the top of the home of the app, where they have to go to “Transnational Exposure Logging” afterwards to see all the participating countries at a glance.

In fact, the instructions for iOS (which are simpler than the ones quoted for Android) also work on Android. So it would be possible to simplify the text and combine it to be the same instructions for both Android and iOS.

**Comment by heinezen** [comment]
@MikeMcC399 You're right. I'll make a PR!
