### ISSUE TITLE
Blog unclear about chosen EU Interoperability Gateway mode

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#483]
## Where to find the issue
https://www.coronawarn.app/en/blog/2020-10-19-version-1-5/
"New features: Corona-Warn-App Version 1.5 is now available for download
Janina Hoerdt on October 19, 2020"

Section **Support of the EU Interoperability Gateway**
Third paragraph. _Learn more about the European interoperability gateway service in the [blog](https://news.sap.com/2020/10/eu-corona-gateway-live/) of Juergen Mueller, member of the Board of Management of SAP SE and Chief Technology Officer (CTO), and Adel Al-Saleh, member of the Board of Management of Deutsche Telekom AG and CEO of T-Systems. 

linking to https://news.sap.com/2020/10/eu-corona-gateway-live/
About SAP SE / SAP News Center / Technology
**EU-Corona Gateway: We Are Live!**
October 19, 2020 by Juergen Mueller, Adel Al-Saleh

### Flexibility

Countries that connect their back ends to the gateway can flexibly define how information about an infection flows toward and out of the gateway. The gateway offers three options for the interaction between national back ends and corona apps:

1. One Europe: All diagnostic keys from all participating countries are distributed via the national and European gateway to all app users from all participating countries.
2. Traveler: On the devices of travelers, travelers download the diagnostic keys of all participating countries. On the devices of non-travelers, domestic users download not only the domestic diagnostic keys but also the keys of all people traveling.
3. Country of Interest: Diagnostic keys of travelers are shared, in addition to the country of residence, only with selected and relevant countries.

## Describe the issue
The reader is left guessing which of the three modes ("One Europe", "Traveler" or "Country of Interest") has been chosen by Germany and whether this is a permanent choice or whether it may be modified with experience of how the system operates.

## Suggested change
Add information to the https://www.coronawarn.app/en/blog/2020-10-19-version-1-5/ blog and / or to the FAQ https://www.coronawarn.app/en/faq/ to clarify which mode is in use. It seems we are operating in "One Europe" mode, since the user is given no choice. I would still appreciate confirmation from the experts though!

**Comment by GisoSchroederSAP** [comment]
Thanks, Mike, for pointing out the missing piece. 
In short: Yes, your assumption is correct. To reduce complexity (and UI screens) and to simplify the EFGS handling, our App and backend currently implements the "One Europe" approach.

**Comment by MikeMcC399** [comment]
I see that the blog https://www.coronawarn.app/en/blog/2020-10-19-version-1-5/ now refers to "One Europe" which therefore resolves the issue I reported:

> The gateway service ensures the pseudonymization and security of the shared keys, which means that the identity of the users remains hidden. At the same time, it acts as a universal “translator”, allowing the various IT systems in the individual countries to communicate with each other. If a new app is connected to the gateway, each country can also flexibly decide how the information about an infection is transmitted. Thereby the German Corona-Warn-App uses the option called **“One Europe”**. According to this, all diagnostic keys from all participating countries are distributed via the national and European gateway to all app users from all participating countries. Learn more about the European interoperability gateway service in the [blog](https://news.sap.com/2020/10/eu-corona-gateway-live/) of Juergen Mueller, member of the Board of Management of SAP SE and Chief Technology Officer (CTO), and Adel Al-Saleh, member of the Board of Management of Deutsche Telekom AG and CEO of T-Systems.

Thank you @GisoSchroederSAP for responding and getting the blog enhanced! 👏

**Comment by heinezen** [comment]
Fixed in https://github.com/corona-warn-app/cwa-website/commit/ed8af93023ae3b70a4f5a4780ff5d49a218905df
