### ISSUE TITLE
Gibt es einen RSS Feed für das zugehörige Blog?

### ISSUE THREAD

**Issue by klaas** [corona-warn-app/cwa-website#498]
Gibt es einen RSS Feed für https://www.coronawarn.app/de/blog/ ?

**Comment by svengabr** [comment]
Hello @klaas, unfortunately, there is currently no RSS Feed available for the Blog page.

This could be requested as a new wishlist item in our wishlist repository:
https://github.com/corona-warn-app/cwa-wishlist

Best regards,
SG

Corona-Warn-App Open Source Team
