### ISSUE TITLE
Move FAQ entry regarding backup problems on iOS to solved Section

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#504]
## Where to find the issue

https://www.coronawarn.app/en/faq/?search=Backup#migration_Apple
https://www.coronawarn.app/de/faq/?search=Backup#migration_Apple

## Describe the issue & Suggested Change 

Since the App now works correctly after restoring it from a Backup, this entry should be moved to the Solved Section.

**Comment by loki-cui** [comment]
@Ein-Tim: That's correct -> This bug was fixed (EXPOSUREAPP-2323) with release 1.5. Thanks for pointing this out. 

@dsarkar : Can you take over pls? -> Amend the text and move it to the "Geklärt/ solved" section? Thx :)

**Comment by Ein-Tim** [comment]
@loki-cui 
I opened a PR for this myself, if you want you can take a look at it and merge it 👍
