### ISSUE TITLE
App error link https://www.coronawarn.app/de/faq/#10 does not redirect to explicit FAQ entry

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#511]
## Where to find the issue
https://www.coronawarn.app/de/faq/

## Describe the issue
Android CWA 1.5.0 error message link 
[`https://www.coronawarn.app/de/faq/#10`](https://www.coronawarn.app/de/faq/#10)
shown in https://github.com/corona-warn-app/cwa-app-android/issues/1459#issuecomment-715794387 does not redirect to
[`https://www.coronawarn.app/de/faq/#API10`](https://www.coronawarn.app/de/faq/#API10), instead it lands on the top level of 
https://www.coronawarn.app/de/faq/.

## Suggested change
I'm guessing, but probably:

Add redirect
    "10": "API10",
to https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq_redirects.json

## Notes
Currently the text on [`https://www.coronawarn.app/de/faq/#API10`](https://www.coronawarn.app/de/faq/#API10) only describes a resolved condition. It does not help with the current issue from https://github.com/corona-warn-app/cwa-app-android/issues/1459.
When the app issue leading to API error 10 in CWA Android 1.5.0 is better understood, it may be able to update the FAQ entry accordingly.

**Comment by heinezen** [comment]
Thanks Mike,

I've added https://github.com/corona-warn-app/cwa-website/pull/513 to address this.

CH

----
Corona-Warn-App Open Source Team
