### ISSUE TITLE
Use of term Exposure Notifications Framework on Android

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#515]
## Where to find the issue 
[`https://www.coronawarn.app/en/faq`](https://www.coronawarn.app/en/faq) "Frequently Asked Questions about the Corona-Warn-App"

and specifically:

- [`https://www.coronawarn.app/en/faq/#ENF_version`](https://www.coronawarn.app/en/faq/#ENF_version) "[Google/Android]: Which version of the COVID-19 Exposure Notification Framework is currently installed?"
- [`https://www.coronawarn.app/en/faq/#API10`](https://www.coronawarn.app/en/faq/#API10) "[Google/Android]: Error when communicating with Google API(10)"

## Describe the issue
For Android systems the [CWA FAQ](https://www.coronawarn.app/en/faq) should refer to Exposure Notifications **System** (ENS) not Exposure Notification(s) **Framework** (ENF).

The installed UI (see screen shot below) calls it by the name Exposure Notifications System as does the help reference https://support.google.com/android/answer/9888358?hl=en.
Google's blog July 31, 2020 https://blog.google/inside-google/company-announcements/update-exposure-notifications/ also refers to Exposure Notifications System using the acronym ENS. In fact Google consistently uses the term Exposure Notifications System and never Exposure Notifications Framework. See also https://developers.google.com/android/exposure-notifications/exposure-notifications-api left-hand menu "Exposure Notifications system".

"Framework" seems to be a term used only by Apple e.g. https://developer.apple.com/documentation/exposurenotification.

![ENSs](https://user-images.githubusercontent.com/66998419/97270121-e8e7ce00-182e-11eb-9903-4277e549d03f.jpg)

## Suggested change
Change references for Google/Android entries in the FAQ: 

- from Exposure Notification(s) Framework to Exposure Notifications System (plural)
- from ENF to ENS

To avoid breaking the link [`https://www.coronawarn.app/en/faq/#ENF_version`](https://www.coronawarn.app/en/faq/#ENF_version) either leave it the way it is or change it to `https://www.coronawarn.app/en/faq/#ENS_version` and add a redirection from `ENF_version` to `ENS_version`

**Comment by svengabr** [comment]
Thank you for your suggestion @MikeMcC399, I will change the wording accordingly.
