### ISSUE TITLE
[Android] New FAQ entry needed: background prioritization

### ISSUE THREAD

**Issue by loki-cui** [corona-warn-app/cwa-website#516]
## Where to find the issue
not yet communicated or published under coronawarn.app

## Describe the issue
The following behaviour could be validated for some Android devices: 
- Start the CWA
- Select the menu option "Einstellungen" and then click on the menu item "Priorisierte Hintergrundaktivität"
- Activate the slidebar "Priorisierte Hintergrundaktivität"
- The battery optimization of the CWA task is not turned off on OS level

Thus, the settings within the app are inconsistent with device settings

Known workaround: restart of the device.

## Suggested change
Pls. create a FA-entry for Android users to point out this behaviour.

Proposal
**DE**
Wenn Sie die priorisierte Hintergrundaktivität auf einigen Android-Geräten einschalten, wird die Batterieoptimierung für die Corona-Warn-App auf Betriebssystemebene nicht ausgeschaltet. Dies ist eine bekannte Einschränkung für eine begrenzte Anzahl von Android-Geräten. Um die Batterieoptimierung entsprechend zu deaktivieren, starten Sie Ihr Gerät neu.

**EN**
When you switch on the prioritized background activity on some Android devices, the battery optimization for the Corona-Warn-App is not turned off on OS level. This is a known limitation for a limeted number of Android devices. To turn off the battery optimization accordingly, restart your device.

**Comment by svengabr** [comment]
@loki-cui The FAQ entry was created and is now online.

https://www.coronawarn.app/en/faq/#battery_optimization_background
https://www.coronawarn.app/de/faq/#battery_optimization_background

**Comment by MikeMcC399** [comment]
@svengabr 
There's minor typo in https://www.coronawarn.app/en/faq/#battery_optimization_background 
This is a known limitation for a **limeted** number of Android devices.

That should be "limited", not "limeted".
Sorry that I didn't catch this earlier!

**Comment by svengabr** [comment]
@MikeMcC399 thanks for your finding, I will correct this!
