### ISSUE TITLE
[iOS] New FAQ-entry reg. beta versions

### ISSUE THREAD

**Issue by loki-cui** [corona-warn-app/cwa-website#520]
## Where to find the issue
not communicated on coronawarn.app anymore. There used to be an entry reg. iOS 14.0 beta, but this was closed after the release of iOS 14.0

## Describe the issue
When Apple released 14.2 beta 3 a lot of users could not use the app anymore and saw the error message "EN code 2"
See https://github.com/corona-warn-app/cwa-app-ios/issues/1339

## Suggested change
Pls. create again a FAQ entry as beta versions are officially not supported. Of course any hints regarding potential incompatibilities are welcome, but they should be addressed under https://github.com/corona-warn-app/cwa-app-ios/issues

Proposal for the FAQ-entry:

**DE**
_Ich teste eine Beta-Version von iOS. Warum wird die Corona-Warn-App noch nicht unterstützt?_
Wir unterstützen offiziell keine Beta-Versionen der jeweiligen Betriebssysteme. Diese sind noch in der Entwicklung und nicht für den produktiven Betrieb vorgesehen.
Wenn Sie als Teilnehmer am Apple Beta Software-Programm jedoch frühzeitig auf potentielle Fehler oder Inkompatibilitäten hinweisen möchten, nehmen wir Ihr Feedback gerne auf Github entgegen:  https://github.com/corona-warn-app/cwa-app-ios/issues

**EN**
_I am testing a beta version of iOS. Why is the Corona-Warn-App not yet supported?_
We do not officially support beta versions of the respective operating systems. These are still in development and not intended for productive operation.
However, if you as a participant in the Apple beta software programme would like to point out potential errors or incompatibilities at an early stage, we are happy to receive your feedback on Github: https://github.com/corona-warn-app/cwa-app-ios/issues

**Comment by svengabr** [comment]
The old FAQ entry was removed a while back because it was specific for iOS 14 Beta 4. I will add a new entry without any version specific anchor link then.
```
{
    "title": "[Apple/iOS]: I'm testing the beta version of iOS 14. Why is Corona-Warn-App not yet supported?",
    "anchor": "ios_14_beta",
    "active": true,
    "textblock": [
        "Even though with iOS 14 Beta 4, the Exposure Notification framework is available now, the Corona-Warn-App does not support iOS 14 Beta-Versions. The Beta-Versions are <a href='https://developer.apple.com/support/beta-software/' target='_blank' rel='noopener noreferrer'>still under development</a> and are not public. See the <a href='https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes' target='_blank' rel='noopener noreferrer'>iOS & iPadOS 14 Beta Release Notes</a>."
    ]
},
```

**Comment by svengabr** [comment]
@loki-cui I did create the new FAQ entries:

https://www.coronawarn.app/en/faq/#beta_ios
https://www.coronawarn.app/de/faq/#beta_ios
