### ISSUE TITLE
Redactional terminology changes für german FAQ

### ISSUE THREAD

**Issue by svengabr** [corona-warn-app/cwa-website#524]
## Where to find the issue
https://www.coronawarn.app/de/faq/

## Describe the issue
[Terminologie Abgleich FAQ.docx](https://github.com/corona-warn-app/cwa-website/files/5458284/Terminologie.Abgleich.FAQ.docx)

## Suggested change
Various grammatical and terminology changes, see the attached word document.

**Comment by heinezen** [comment]
Addressed in #526

**Comment by Ein-Tim** [comment]
Still needed?

**Comment by heinezen** [comment]
"Corona Warn App" --> "Corona-Warn-App"

in english version of the FAQ

https://github.com/corona-warn-app/cwa-website/pull/814#discussion_r566266247

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 

Six months have gone by and the file attached to this issue is quite out of date. Perhaps this issue can be closed in favor of #971?
