### ISSUE TITLE
FAQ - Differences in lists of federated countries for European Federation Gateway Service (EFGS)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#525]
## Your Question
Which is the most reliable source of information for which countries have gone live with the European Federation Gateway Service (EFGS)?

1. List of Transnational exposure logging countries in CWA app?
2. List of countries on [CWA FAQ - "In which countries   can the Corona Warn App be used?"](https://www.coronawarn.app/en/faq/#interoperability_countries) ?
3. List of countries on [europa.de - "Mobile contact tracing apps in EU Member States"](https://ec.europa.eu/info/live-work-travel-eu/health/coronavirus-response/travel-during-coronavirus-pandemic/mobile-contact-tracing-apps-eu-member-states_en)?

The following table shows which countries are shown in which information source:

Country | CWA App display | CWA FAQ | EU List
-- | -- | -- | --
Croatia |   | planned | No
Czech Republic |  | planned | No  
Denmark | shown | 06.11.2020 | No
Germany | shown | 17.10.2020 | Yes
Ireland | shown | 19.10.2020 | Yes
Italy | shown | 19.10.2020 | Yes
Latvia | shown | 06.11.2020 | Yes
Spain | shown | 06.11.2020 | Yes
 |   |   | 
Date | Nov 6, 2020  | Nov 6, 2020 16:00 | Nov 6, 2020

---

This is what CWA Android 1.5.1 was showing on November 1, 2020. See above table for updated list.

![Transnational logging](https://user-images.githubusercontent.com/66998419/97798899-9fcabc00-1c2a-11eb-8153-20e5b3e7dbf4.jpg)

**Comment by heinezen** [comment]
@MikeMcC399 Transferred to the website repo because it is mostly relevant for the FAQ.

We will have a look at this and update the relevant dates and countries.

----
Corona-Warn-App Open Source Team

**Comment by thomasaugsten** [comment]
I think there is at the moment no consolidated list of the connected countries. But the configured countries in the CWA are the countries package which are downloaded from the EFGS by the CWA server.

**Comment by thomasaugsten** [comment]
Here the official document
https://ec.europa.eu/info/live-work-travel-eu/health/coronavirus-response/travel-during-coronavirus-pandemic/mobile-contact-tracing-apps-eu-member-states_en

**Comment by MikeMcC399** [comment]
@thomasaugsten 
> I think there is at the moment no consolidated list of the connected countries. 

I thought the European Union's list of countries on europa.de - "[Mobile contact tracing apps in EU Member States](https://ec.europa.eu/info/live-work-travel-eu/health/coronavirus-response/travel-during-coronavirus-pandemic/mobile-contact-tracing-apps-eu-member-states_en)" that I referred to in the original post was the consolidated list of countries, but maybe I am interpreting this page incorrectly? It does not specifically say that the column "Interoperable - can this app already talk to another app?" means that the country is live on the European Federation Gateway Service (EFGS), but I can't think of what this is supposed to mean otherwise.

**Comment by thomasaugsten** [comment]
This list is correct and they are connected to the EFGS but we doing last tests to consume this new EFGS data on our side. Then we will add this countries to our app without an app update.

**Comment by MikeMcC399** [comment]
@heinezen 
CWA Android is still only showing only Germany, Ireland & Italy.
The dates for Croatia, Czech Republic and Denmark are all in the past.

So the FAQ still contains out of date information in https://www.coronawarn.app/en/faq/#interoperability_countries.

**Comment by MikeMcC399** [comment]
https://github.com/corona-warn-app/cwa-website/issues/544 from @loki-cui is addressing this issue I see,

I will close this issue as soon as the CWA app agrees with the FAQ https://www.coronawarn.app/en/faq/#interoperability_countries.

**Comment by MikeMcC399** [comment]
The list has been updated through #545 however the way it is worded, gives the impression that Croatia and Czech Republic are already live.

https://www.coronawarn.app/en/faq/#interoperability_countries
Below is a list of currently participating countries and details of the responsible health authorities:
Croatia
Czech Republic

with no date. It would be better to write "planned" against these two countries instead.

**Comment by thomasaugsten** [comment]
The App is now using keys from spain, denmark and lativa you can also see the updated list in the app.
The FAQ is also updated for croatia and czech is not perfect we expect a go live in the next week.

**Comment by MikeMcC399** [comment]
@thomasaugsten 
> The App is now using keys from spain, denmark and lativa you can also see the updated list in the app.
> The FAQ is also updated for croatia and czech is not perfect we expect a go live in the next week.

Thank you for letting us know that Croatia and Czech Republic are coming this week. 
I will close this issue now.

Here is what the app is showing today, Nov 9, 2020:

![Country list](https://user-images.githubusercontent.com/66998419/98518187-581de300-226f-11eb-848b-bbf8944c5743.jpg)

**Comment by MikeMcC399** [comment]
Croatia joined on 16.11.2020.
