### ISSUE TITLE
Corona

### ISSUE THREAD

**Issue by Marewski** [corona-warn-app/cwa-website#527]

**Comment by Ein-Tim** [comment]
Hi @Marewski 
Where is the Issue?

**Comment by MikeMcC399** [comment]
This looks like a mistaken input and should probably be closed.

**Comment by dsarkar** [comment]
Dear @Marewski,

Since this seems a mistake I will close this issue. Should you wish to report an issue, please, open a new one. Thank you!

Best wishes,
DS

Corona-Warn-App Open Source Team
