### ISSUE TITLE
Handling positive test results with 2 smartphones

### ISSUE THREAD

**Issue by loki-cui** [corona-warn-app/cwa-website#528]
## Where to find the issue
not yet covered under coronawarn.app

## Describe the issue
A lot of people are using 2 devices (business and private device) during the week. When it comes to the scan of a QR-code or the sharing of a positive test result, this is only possible via one device. Thus, a reccomendation how to handle such a situation is needed

## Suggested change
Create an FAQ-entry with the following information:

**DE**
_Wie teile ich ein positives Testergebnis auf mehreren Geräten?_

Wenn Sie mehr als ein Smartphone besitzen und bspw. eines beruflich und eines privat nutzen, empfehlen wir die Installation der CWA zunächst auf Ihrem privaten Gerät. Auch der Scan von QR-Codes und das Teilen eines positiven Ergebnisses sollte zuerst über das private Gerät erfolgen. Wenn Sie darüber hinaus auch über Ihr Firmengerät ein positives Ergebnis teilen möchten, geht dies ausschließlich über eine sog. TeleTAN. Mit einem positiven Testergebnis erhalten Sie unter +49 800 7540002 eine 10-stellige TAN mit der das Testergebnis ebenfalls in der App registriert werden kann. Achtung: Die TAN Nummer ist nur eine Stunde gültig. 

**EN**
_How do I share a positive test result on multiple devices?_

If you have more than one smartphone (e.g. work and private), we recommend that you install the CWA on your private device first. Also, when scanning QR codes and sharing a positive result, we recommend that you first use your private device. If you additionally want to share a positive result via your company device or any other additional smartphone, this can be done via a so-called TeleTAN. By contacting +49 800 7540002 with a positive test result, you will receive a 10-digit TAN with which the test result can also be registered in the app.  Please note: The TAN number is only valid for one hour.

**Comment by MikeMcC399** [comment]
Great suggestion! I'm sure that there are significant numbers of CWA users with work and private phones.

If this suggestion is implemented, it might be a good time to parameterize the telephone numbers in the .json faq files so the telephone numbers are maintained in one place and not copied and pasted everywhere. A similar enhancement was done for version numbers in the FAQs to keep them consistent.

**Comment by heinezen** [comment]
Hey @MikeMcC399,

Can you make a separate issue for your suggestion with the telephone numbers (so it isn't forgotten when we merge #530 and close this issue)?

Thanks,
CH

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 
> Can you make a separate issue for your suggestion with the telephone numbers (so it isn't forgotten when we merge #530 and close this issue)?

Good suggestion! When I researched this topic I realized also that there are other inconsistencies that are better handled in a separate issue. 

I have opened https://github.com/corona-warn-app/cwa-website/issues/533.
