### ISSUE TITLE
Link to Deutsche Telekom Corona Warn App Update-Podcast

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#529]
## Feature description

Provide a link on the [Corona Warn App Open Source website](https://www.coronawarn.app/en/) (https://www.coronawarn.app/en/) to the [Deutsche Telekom Corona Warn App Update-Podcast](https://www.telekom.com/de/medien/podcasts/corona-warn-app) (https://www.telekom.com/de/medien/podcasts/corona-warn-app) site.

The last one which was [Podcast \#9](https://cdn.podigee.com/media/podcast_25685_coronawarnapp_der_digitale_virus_wachhund_episode_314001_corona_warn_app_9.mp3?v=1604073600&source=feed) has the following summary:

"Ob die Steigerung der Infektionszahlen sich positiv auf die Downloadzahlen der App auswirken, ob der hohe Datenschutzstandard gerechtfertigt ist und welche Neuerungen es in der App gibt, das und einige andere Fragen beantwortet Adrian Sanchez von der Telekom gemeinsam mit Hilmar Schepp, Pressesprecher #SAP und Nicole Schmidt, Pressesprecherin #Telekom."

The information could possibly be linked into the Blog or have its own separate Telekom / SAP podcast link.

## Problem and motivation
The podcasts provide important new information about the Corona Warn App.

Communicating to the user base promotes better usage by people who already have the app installed, they may also be motivated to encourage other people to install the app as well. Higher usage improves the overall effectiveness of the warning system by increasing the probability of encounters being registered.

---
Internal Tracking ID: [EXPOSUREAPP-5319](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5319)

**Comment by Ein-Tim** [comment]
@MikeMcC399 
Just a small note:
I would link the Podcast only on the German Page (www.coronawarn.app/de), since it's German 👍🙂

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> I would link the Podcast only on the German Page (www.coronawarn.app/de/), since it's German 👍🙂

Don't forget the bilingual audience 😉!
https://www.coronawarn.app/en/blog/2020-10-09-facts-and-figures/ is posted to the English version of the blog and is simply labelled "(German versions only)". That could be done similarly for the podcast information.

**Comment by MikeMcC399** [comment]
[Corona Warn App Podcast #10](https://cdn.podigee.com/media/podcast_25685_coronawarnapp_der_digitale_virus_wachhund_episode_343958_corona_warn_app_10.mp3?v=1608044285&source=feed) is now showing on the https://www.telekom.com/de/medien/podcasts/corona-warn-app site:

"Auch ein halbes Jahr nach dem Start der Corona-Warn-App und mehr als 24 Millionen Downloads stellen die Nutzer viele Fragen. Adrian Sanchez von der Telekom geht gemeinsam mit Hilmar Schepp, Pressesprecher #SAP und Nicole Schmidt, Pressesprecherin #Telekom, solchen Fragen nach wie: Beeinflussen dicke Winterjacken die Genauigkeit der App? Werden Risikobegegnungen mit der gleichen Person mehrfach gezählt? Und auch auf die Frage „Erfasst die App Risikobegegnungen durch Hauswände?“ gibt es eine Antwort."

The contents of the podcast bears remarkable similarity to what has been published to https://www.coronawarn.app/en/faq/#risk_assessment via https://github.com/corona-warn-app/cwa-website/pull/646 and to the open issue https://github.com/corona-warn-app/cwa-website/issues/636 giving the impression this was a scripted interview.

**Comment by MikeMcC399** [comment]
There have not been any new podcasts for 8 weeks, so I withdraw this request.

**Comment by MikeMcC399** [comment]
I will revive this request, since there is a new podcast just published to https://www.telekom.com/de/medien/podcasts/corona-warn-app

**Corona Warn App \#11**

Die Risikoberechnung in der Corona-Warn-App wird umgestellt. Warum das so ist und das mit den aktuellen Virus-Mutationen zu tun hat, darüber klären Experten auf. Hilmar Schepp, Pressesprecher SAP, und Nicole Schmidt, Pressesprecherin Telekom, im Gespräch mit Thomas Klingbeil, Softwarespezialist bei SAP, und Dr. Justus Benzler, Epidemiologe am Robert Koch - Institut.

[Podcast download](https://cdn.podigee.com/media/podcast_25685_coronawarnapp_der_digitale_virus_wachhund_episode_388184_corona_warn_app_11.mp3)

**Comment by dsarkar** [comment]
@MikeMcC399 ok, thanks, any suggestion where to collect such links? FAQ? Blog post?

**Comment by MikeMcC399** [comment]
@dsarkar 
>any suggestion where to collect such links? FAQ, News section? Blog post?

Each new podcast could be a separate blog post on https://www.coronawarn.app/en/blog/. It should be possible for SAP to coordinate that point with Hilmar Schepp, Pressesprecher SAP to see if he supports doing that.

**Comment by dsarkar** [comment]
@MikeMcC399 ok, will forward your suggestion. Thanks.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-5319](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5319)

**Comment by MikeMcC399** [comment]
@dsarkar 
Should we close this?

https://github.com/corona-warn-app/cwa-website/pull/908 adds the text:

"Wer noch etwas tiefer in das Thema der Risikoberechnung einsteigen möchte, kann sich Folge 11 des Corona-Warn-App-Podcasts anhören. In der neuen Folge erklären Thomas Klingbeil, Software-Entwickler bei SAP und Dr. Justus Benzler, Epidemiologe am Robert Koch-Institut, die Risikoberechnung im Detail: [#CoronaWarnApp – Der digitale Virus-Wachhund - Folge 11 - YouTube](https://www.youtube.com/watch?v=OzGdXCl6Ozw&feature=youtu.be)"

so at least German readers are informed about the podcast on YouTube (which is a different source to https://cdn.podigee.com/media/podcast_25685_coronawarnapp_der_digitale_virus_wachhund_episode_388184_corona_warn_app_11.mp3 but the same content).

**Comment by dsarkar** [comment]
@MikeMcC399 
https://www.coronawarn.app/de/blog/2021-02-23-corona-warn-app-risk-calculation-optimization/
yes, just realized, that it was done! Up to you, if you want to suggest anything else. I think we can close this one, and suggest that podcasts, in general, could be linked in the blog post, as it was done today.

**Comment by MikeMcC399** [comment]
@dsarkar 
I will close this. Hopefully it means that the channel between the podcast producers and the blog journalists is now permanently open.
