### ISSUE TITLE
FAQ: Inconsistent phone number format and naming for hotlines

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#533]
## Where to find the issue
**Frequently Asked Questions about the Corona-Warn-App**
https://www.coronawarn.app/en/faq/ (English)
https://www.coronawarn.app/de/faq/ (German)
 
## Describe the issue

Frequently Asked Questions about the Corona-Warn-App make multiple references to phone numbers using different nomenclatures and formats for the phone numbers:

### https://www.coronawarn.app/en/faq/ (English)

The technical hotline (telephone 0800 7540001)
The telephone hotline (+49 800 7540001) 

The TAN hotline (telephone 0800 7540002)
call the hotline at +49 800 7540002
Call the verification hotline (+49 800 7540002)

### https://www.coronawarn.app/de/faq/ (German)
Die technische Hotline (Telefon 0800 7540001)
Die Hotline (+49 800 7540001)

Die TAN-Hotline (Telefon 0800 7540002)
rufen Sie die Hotline unter der +49 800 7540002 an
Rufen Sie die Verifizierungs-Hotline (+49 800 7540002) an

The different names for the same numbers is confusing. 

## Suggested change

Use the international phone number format and the following names:
+49 800 7540001 Technical hotline / technische Hotline
+49 800 7540002 TAN hotline / TAN-Hotline

Also parameterize the numbers and names to ease consistent appearance in FAQ text.

**Comment by heinezen** [comment]
The different nomenclatures should be harmonized in #530 (see #528 for reference).

**Comment by MikeMcC399** [comment]
According to PR https://github.com/corona-warn-app/cwa-website/pull/757 the international phone numbers have been converted to local phone numbers.

I can't see any change to the names used to refer to the two different numbers.

### English

0800 7540001 is called:
- technical hotline
- telephone hotline
- Hotline App

0800 7540002 is called:
- TAN hotline
- hotline
- verification hotline
- Hotline TAN

### German

0800 7540001 is called:
- technische Hotline
- telephone hotline
- Hotline

0800 7540002 is called:
- TAN-Hotline
- Hotline
- Verifizierungs-Hotline

**Comment by MikeMcC399** [comment]
I suggest for the hotline 0800 7540001 to standardize on the name used in the FAQs:

**EN**
- technical hotline

**DE**
- technische Hotline

in the FAQs. If there is agreement on this I can submit a PR regarding the technical hotline only.

---
For the hotline 0800 7540002 it is unclear to me what the best standard name in the FAQs should be. The app (1.12.0) now says "Call the nationwide hotline and request a TAN" (EN) or "Rufen Sie die bundesweite Hotline an und fragen Sie nach einer TAN" (DE).

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the suggestions.

@GisoSchroederSAP I think the proposal 

> 
> EN
> 
> technical hotline
> DE
> 
> technische Hotline

 https://github.com/corona-warn-app/cwa-website/issues/533#issuecomment-784968766 for ...0001 makes sense to harmonize the FAQs

regarding ...0002 to be more specific TAN-Hotline / TAN hotline, see comment above:

> For the hotline 0800 7540002 it is unclear to me what the best standard name in the FAQs should be. The app (1.12.0) now says "Call the nationwide hotline and request a TAN" (EN) or "Rufen Sie die bundesweite Hotline an und fragen Sie nach einer TAN" (DE).

**Comment by MikeMcC399** [comment]
@dsarkar

Do you want me to submit a PR to harmonize the naming of the hotlines in the FAQs?

Language \ Number  | 0800 7540001 | 0800 7540002
--- | --- | ---
EN | technical hotline |  TAN hotline
DE | technische Hotline | TAN-Hotline

The main page https://www.coronawarn.app/ uses the short terms
Hotline App and Hotline TAN for both languages EN and DE.

**Comment by dsarkar** [comment]
@MikeMcC399 Hi Mike, thanks for collecting the info. I will be more than happy if you want to submit a PR. Mnay thanks!

**Comment by MikeMcC399** [comment]
@dsarkar 
Thank you for the confirmation!
I have now submitted PR https://github.com/corona-warn-app/cwa-website/pull/929 to harmonize the hotline naming.
