### ISSUE TITLE
Blog: Facts and figures lagging behind RKI sitepublications

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#534]
## Where to find the issue
https://www.coronawarn.app/en/blog/2020-10-09-facts-and-figures/
Current facts and figures - an interim balance

## Describe the issue
The last weekly status report "Current facts and figures - an interim balance" is from Oct 23, 2020 which is from Friday, the week before last. The [RKI site](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html) "Übersicht zu aktuellen und früherer Zahlen und Fakten zur Corona-Warn-App" is more up-to-date.

## Suggested change
Add the [latest status reports from RKI site](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html) to 
https://www.coronawarn.app/en/blog/2020-10-09-facts-and-figures/ and  to 
https://www.coronawarn.app/de/blog/2020-10-09-facts-and-figures/

Currently https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html is showing 

https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/Kennzahlen_30102020.pdf?__blob=publicationFile from Oct 30, 2020 which is not published to the [CWA blog](https://www.coronawarn.app/en/blog/).

**Comment by MikeMcC399** [comment]
There is another new status report from RKI, dated today, Nov 6, 2020
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/Kennzahlen_06112020.pdf?__blob=publicationFile

BTW: There is an RSS feed to RKI [Robert Koch-Institut: Neuartiges Coronavirus (2019-nCoV)](https://www.rki.de/SiteGlobals/Functions/RSSFeed/RSSGenerator_nCoV.xml?nn=2444038) which alerted me to this new report.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Is the problem solved with #540, #541, #542, #543?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
>Is the problem solved with #540, #541, #542 (not yet merged), #543?

In short: yes. The [blog](https://www.coronawarn.app/en/blog/2020-10-09-facts-and-figures/) is now updated with the latest status report from today Nov 6, 2020.

The [RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html) and [Open Source blog](https://www.coronawarn.app/en/blog/2020-10-09-facts-and-figures/) sites have different contents with different missing report dates. As long as the latest report is shown by the [Open Source blog](https://www.coronawarn.app/en/blog/2020-10-09-facts-and-figures/) then I am satisfied and so I will close this issue.

---
https://www.coronawarn.app/en/blog/2020-10-09-facts-and-figures/ shows:
![Blog status overview](https://user-images.githubusercontent.com/66998419/98378413-45749580-2046-11eb-8be1-ab47c3434a5c.jpg)

---
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html shows:
![RKI status overview](https://user-images.githubusercontent.com/66998419/98378455-54f3de80-2046-11eb-9470-bd5b941b0cee.jpg)
