### ISSUE TITLE
FAQ: Location does not apply to Android 11

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#539]
## Where to find the issue 
https://www.coronawarn.app/en/faq/#android_location
"[Google/Android]: When activating exposure logging or Bluetooth I'm asked to activate my location. Do I have to do this?"

## Describe the issue
The requirement to enable Use location in order to access Bluetooth Low Energy, required for CWA, has been removed for COVID-19 apps starting with Android 11. (See https://support.google.com/android/answer/9930236 and https://developers.google.com/android/exposure-notifications/implementation-guide#locationless_scanning_in_android_11.)

## Suggested change
Add text to the article https://www.coronawarn.app/en/faq/#android_location to explain that it does not apply to Android 11.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I could at this to #535 if you want? 

I would write:

`AKTUELL: Wenn Sie Android 11 benutzen, müssen Sie die Standortverwendung nicht mehr aktvieren um die App zu benutzen.`

`UPDATE: If you are using Android 11, you don't have to activate the location to use the App.`

If this is correct and you are happy with this I would add it to the PR and mark the PR that it also closes this Issue 👍

**Comment by MikeMcC399** [comment]
Hi @Ein-Tim 

I appreciate your offer, however I think we should keep the subjects in different PRs to keep it clean. #535 is about the hotlines. I'd also like to wait for first feedback here from the Open Source Team and in the related topic I raised today in https://github.com/corona-warn-app/cwa-app-android/issues/1541. I would be happy to draft a separate PR myself in fact, now that I've done it once, I know how the process works.

Luckily there aren't too many users on Android 11 yet, so I don't think that many are getting confused by the FAQ at this time.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Totally understandable! Yes let's wait for feedback first and for sure you can draft a PR yourself! Thanks for your always kind replies! 🙂

**Comment by dsarkar** [comment]
Dear @MikeMcC399,

Would you agree with something like that?

AKTUELL: Wenn Sie Android 11 und die Corona-Warn-App ab Version 1.4 benutzen, müssen Sie die Standortverwendung nicht mehr aktivieren, um die Corona-Warn-App zu nutzen. Diese für Android Version 11 nicht zutreffende Benachrichtigung wird in einem der nächsten Updates der Corona-Warn-App entfernt.

UPDATE: If you are using Android 11 and the Corona-Warn-App version 1.4 or above, you don't have to "allow location access" in order to use the Corona-Warn-App. This notification is not applicable for Android 11 phones and will be removed in one of the following updates of the Corona-Warn-App for Android Version 11 phones.

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Hi @dsarkar 

Thank you for picking up this suggestion to modify
https://www.coronawarn.app/en/faq/#android_location and 
https://www.coronawarn.app/de/faq/#android_location!

For both texts replace Version 1.4 with 1.5. The Version 1.4 was never released to Google Play Store. The version went from Version 1.3.1 to Version 1.5.0 (you can check in https://www.apkmirror.com/apk/robert-koch-institut/corona-warn-app/).

> AKTUELL: Wenn Sie Android 11 und die Corona-Warn-App ab Version **1.4** benutzen, müssen Sie die Standortverwendung nicht mehr aktivieren, um die Corona-Warn-App zu nutzen. Diese für Android Version 11 nicht zutreffende Benachrichtigung wird in einem der nächsten Updates der Corona-Warn-App entfernt. 

Suggest:

AKTUELL: Wenn Sie Android 11 und die Corona-Warn-App ab Version 1.5 benutzen, müssen Sie die Standortverwendung nicht mehr aktivieren, um die Corona-Warn-App zu nutzen. Diese für Android Version 11 nicht zutreffende Benachrichtigung wird in einem der nächsten Updates der Corona-Warn-App entfernt. 

> UPDATE: If you are using Android 11 and the Corona-Warn-App version **1.4** or above, you don't have to "allow location access" in order to use the Corona-Warn-App. This notification is not applicable for Android 11 phones and will be removed in one of the following updates of the Corona-Warn-App **for Android Version 11 phones**.

For the English version, I suggest removing the final "for Android Version 11 phones." which is not necessary and does not match the German text. So the English text would read:

UPDATE: If you are using Android 11 and the Corona-Warn-App version 1.5 or above, you don't have to "allow location access" in order to use the Corona-Warn-App. This notification is not applicable for Android 11 phones and will be removed in one of the following updates of the Corona-Warn-App.
