### ISSUE TITLE
Corona-Warn app in foreign app sores

### ISSUE THREAD

**Issue by wolfgang35435** [corona-warn-app/cwa-website#547]
I have Chinese friends working in Germany since many years.
They cannot use the Corona-Warn app on their iPhones because it is not available in the Chinese App store. They cannot switch to the German app store because they have an Apple Music subscription.

Why not make the App available internationally?

## Your Question

* Website URL Path:
* Line / Paragraph:
* Question:

**Comment by Ein-Tim** [comment]
@wolfgang35435 
Please take a look at this FAQ Entry: https://www.coronawarn.app/en/faq/#international

**Comment by heinezen** [comment]
Hello @wolfgang35435 ,

As @Ein-Tim said, FAQ entry https://www.coronawarn.app/en/faq/#international should answer your question. Particularly this line:

> After a detailed examination of the situation it was determined that for legal reasons any publication of the Corona-Warn-App in App Stores outside of Germany is currently only possible after a case-by-case assessment.

Countries are added one by one after resolving and clarifying legal issues. You can also request support for a specific country in the [wishlist repository](https://github.com/corona-warn-app/cwa-wishlist/issues).

I hope that answers your question.

Regards
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
@wolfgang35435 We'll close this issue because your question was answered. Please notify us if the information we provided was not sufficient.

Regards,
CH

----
Corona-Warn-App Open Source Team
