### ISSUE TITLE
FAQ: Advice on Problems when using the QR code difficult to understand

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#549]
## Where to find the issue
https://www.coronawarn.app/en/faq/?search=qr
"Problems when using the QR code"

## Describe the issue
The FAQ article [**Problems when using the QR code**](https://www.coronawarn.app/en/faq/?search=qr) describes two different actions:
1. Scanning the QR code
2. Retrieving the test results

and the issues in the description are mixed together.

## Suggested change
Re-write the article so that troubleshooting steps attempted action / problem condition / recommended recovery action are clearly listed and separated. Background information can be listed after the recommended steps are provided.

**Comment by heinezen** [comment]
Please review https://github.com/corona-warn-app/cwa-website/pull/663

**Comment by MikeMcC399** [comment]
The change was to
https://www.coronawarn.app/en/faq/#qr_test and introduced
https://www.coronawarn.app/en/faq/#qr_scan

**Comment by dsarkar** [comment]
@MikeMcC399, you proposing any changes in the text, or re-structuring the FAQ on QR code related issues/topics?

**Comment by MikeMcC399** [comment]
@dsarkar 
>  you proposing any changes in the text, or re-structuring the FAQ on QR code related issues/topics?

Sorry if the comment was confusing! I was just adding a comment to another old issue that the FAQ had been split into two and I wanted to document it here as a conclusion to this issue because it wasn't so easy to read the results of the PR #663.

No action needed. Thanks!

**Comment by dsarkar** [comment]
No worries at all, @MikeMcC399!
