### ISSUE TITLE
Provide simplified "How does the app work" section

### ISSUE THREAD

**Issue by fitsch** [corona-warn-app/cwa-website#55]
## Where to find the issue
On the landing page for both German and English versions

## Describe the issue
Many people are very critical with regards to data protection and privacy. I know that you guys have been doing a tremendous job in this regard (thanks!), and it would thus be great if the app is used widely. Technology is only one aspect though. We should also make sure that people with concerns can understand why this app is no threat to their privacy.

The homepage is giving an explanation of this in the "How does the app work" section. However it is in my opinion too hard to understand for anyone who does not have a technology background. It mentions frameworks, identifiers, cryptographical keys, backend, and so on. I would assume that a majority of people would not be able to understand this, maybe leading to a reduced acceptance.

## Suggested change
Provide a "How does the app work" version in simplified English and German (could be text or even video). It should be explained in such a way that it can be understood by the "average citizen" (i.e. without technology background or university degree).
There could still be a more detailed, technology-oriented explanation on a second level for those people who want to dive deeper of course.

SAP has tons of UA experts that are surely happy to support.

**Comment by MikeJayDee** [comment]
The [DP3T comic](https://github.com/DP-3T/documents/tree/master/public_engagement/cartoon) or the [slide deck of Apple/Google](https://blog.google/documents/66/Overview_of_COVID-19_Contact_Tracing_Using_BLE_1.pdf) are both quite good in my view. Is this something you had in mind?

**Comment by corneliusroemer** [comment]
Maintainers, your feedback is requested :) @SebastianWolf-SAP @tkowark @jakobmoellersap

**Comment by tkowark** [comment]
In the meantime, we both simplify the language (as much as possible - this is the website for the open source project, after all) but also linked the explanatory video available on the official app website.
