### ISSUE TITLE
FAQ: Enhancements of the app 

### ISSUE THREAD

**Issue by loki-cui** [corona-warn-app/cwa-website#556]
## Where to find the issue
not communicated yet

## Describe the issue
There is no official statement yet reg. enhancements of the app. Thus, the following general statement from RKI, SAP and Telekom shall be published. 

## Suggested change

**DE**
Das RKI als Herausgeber der App und das Bundesministerium für Gesundheit prüfen gemeinsam mit Deutsche Telekom und SAP stetig mögliche Weiterentwicklungen sowie die eingehenden Weiterentwicklungsvorschläge. Hierunter fällt auch, ob weitere Informationen in die App integriert werden können, beispielsweise zum aktuellen Pandemiegeschehen.

**EN**
The RKI as the publisher of the app and the Federal Ministry of Health, in co-operation with Deutsche Telekom and SAP, are constantly reviewing possible further developments as well as incoming development proposals. This also includes whether further information can be integrated into the app, for example on the latest pandemic situation.

**Comment by dsarkar** [comment]
@loki-cui, add this as the second paragraph of "Helft uns, die Corona-Warn-App zu verbessern" on the main webpage?

**Comment by MikeMcC399** [comment]
@dsarkar 
> add this as the second paragraph of "Helft uns, die Corona-Warn-App zu verbessern" on the main webpage?

The text fits into what is already written under the heading of 
https://www.coronawarn.app/en/
**This is how the app works best**

which says currently:

"Comissioned by the Robert Koch Institute, we - Deutsche Telekom and SAP - continue to work together with our partners Apple and Google on optimizing the app to make it even more robust. For that purpose we will continue to intensively incorporate the information that we receive via the various channels into our development process. Here we have briefly summarized the most important tips for using the app:"

I think somebody needs to combine / replace the text under "This is how the app works best". It doesn't make sense to put the new text under "Help us improve the Corona-Warn-App" as well.

**Comment by loki-cui** [comment]
@MikeMcC399: You are right! Thanks for your sharp eye ;) I'll take the point back and discuss this.

**Comment by loki-cui** [comment]
I'd like to follow the proposal from @MikeMcC399 and combine the new and the already exising information under

https://www.coronawarn.app/de/ - https://www.coronawarn.app/en/
So funktioniert die App am besten - This is how the app works best

as follows:

**DE**
Das RKI als Herausgeber der App und das Bundesministerium für Gesundheit prüfen gemeinsam mit Deutsche Telekom und SAP stetig mögliche Weiterentwicklungen sowie die eingehenden Weiterentwicklungsvorschläge. Hierunter fällt auch, ob weitere Informationen in die App integriert werden können, beispielsweise zum aktuellen Pandemiegeschehen. Dafür werden wir die Hinweise, die wir über die verschiedenen Kanäle erhalten, weiterhin intensiv in unseren Entwicklungsprozess einbeziehen. Hier haben wir die wichtigsten Hinweise für die Nutzung der App kurz zusammengefasst: [weiter mit der existierenden Aufzählung]]

**EN**
The RKI as the publisher of the app and the Federal Ministry of Health, in co-operation with Deutsche Telekom and SAP, are constantly reviewing possible further developments as well as incoming development proposals. This also includes whether further information can be integrated into the app, for example on the latest pandemic situation. For that purpose we will continue to intensively incorporate the information that we receive via the various channels into our development process. Here we have briefly summarized the most important tips for using the app: [continue with existing bullet point....]

**Comment by MikeMcC399** [comment]
@loki-cui 
In your original post you wrote "_There is no official statement yet reg. enhancements of the app._" however the Federal Government published official information in https://www.bundesregierung.de/breg-de/suche/videoschaltkonferenz-der-bundeskanzlerin-mit-den-regierungschefinnen-und-regierungschefs-der-laender-am-16-november-2020-1811820

Maybe we could link to this information, or perhaps RKI would like to write it in their own way, also in English?

Videoschaltkonferenz der Bundeskanzlerin mit den
Regierungschefinnen und Regierungschefs der Länder
am 16. November 2020
See page 9, section 9 "Die Corona-Warn-App (CWA)"
Received via NINA push notification.
"In den kommenden sechs Wochen wird die CWA drei weitere Updates erhalten. Dadurch wird der Warnprozess vereinfacht sowie automatische Erinnerungen nach Positivtestung an eine noch nicht erfolgte Warnung der eigenen Kontaktpersonen implementiert, ein Mini-Dashboard mit aktuellen Informationen zum Infektionsverlauf integriert, die Messgenauigkeit durch die Umstellung auf die neue Schnittstelle von google/apple verbessert sowie die Intervalle für die Benachrichtigung über eine Warnung erheblich reduziert. Weitere Umsetzungen, wie die Einbindung eines Kontakttagebuchs werden aktuell geprüft und wenn möglich zeitnah in 2021 umgesetzt."

**Comment by loki-cui** [comment]
@MikeMcC399 : This was discussed with SAP and the RKI, and it was decided to communicate only a general statement about the cooperation of the parties involved and the further development of the app. All strategic or political information and statements should not be shared via the open source website. And I actually think this is a good approach, although I am in principle a fan of a coordinated and bundled communication ;)

**Comment by MikeMcC399** [comment]
@loki-cui 
> ... it was decided to communicate only a general statement about the cooperation of the parties involved and the further development of the app. All strategic or political information and statements should not be shared via the open source website. 

I am sorry, but not surprised, about the decision, because it merely confirms the information politics in the Open Source Website so far.

It makes the Open Source site somewhat one-sided though, because on the one hand, users are actively encouraged to contribute, on the other hand the information flow back in the opposite direction from the product owners to contributing users is not summarized until each new version is actually released. Also note the reference to "transparency" below from the top of the page https://www.coronawarn.app/en/.

![help us improve](https://user-images.githubusercontent.com/66998419/99967406-22611a00-2d98-11eb-8535-6c1ebb064f47.jpg)

**Comment by GisoSchroederSAP** [comment]
@All, 
let me step in here, please. I really like to emphasize the value and benefit that comes with the engagement of the community to help us develop, hardening and enhancing the Corona-Warn-App.

However, I don't want to play the single-sided game here.  If we all take a step back,  we act as _partners_ to make the App working. To make this _partnership_ happen we agree on a consensus - there is a set of framing conditions and rules that describe the way we work, the possibilities and limits of the approach chosen. 

With respect to the above conversation, I want to make clear:

- Yes, we still believe in and live the Open Source apporach - the source code is open and available for all those that are interested.
- Yes, we love the input from the engaged community and share it _on a daily basis_ with the DEV team and as with the project team of all involved parties.
- Yes, as soon as possible we share news and results from the decision making process.
- And yes,  we would love to shorten this decision making process  in many cases, like you would.

I am pretty sure, you all are aware this project is driven by multiple parties, including the community - you guys. This diversity comes with challanges that need to be balanced. 
And it comes with a clear guidance: All strategic and political statements about the App, about the pandemic situation and about the decisions made (enhancements, feature requests, avilability dates etc) have to be _approved by and announced_ by the stakeholder parties first, before we are permitted to spread the word.

I hope, you can accept this and still will support the App. With this, I also agree on @loki-cui 's summary - the Open Source channel (dealing with the open source code of the App) can only provide general statements

> "about the cooperation of the parties involved and the further development of the app"

As you, @MikeMcC399, already pointed out properly, there *are* already other sources to communicate the strategic and political announcements. 

Thank you.
