### ISSUE TITLE
FAQ Entry about failing Exposure Checks under iOS with 1.6.0 is outdated

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#558]
## Where to find the issue

https://www.coronawarn.app/de/faq/#expcheck_160
https://www.coronawarn.app/en/faq/#expcheck_160

## Describe the issue
> We are working on a solution for this error.

The error was [solved](https://github.com/corona-warn-app/cwa-app-ios/issues/1497#issuecomment-725598643) with 1.6.1

## Suggested change
Update the FAQ Entry and move it to the solved section.
@dsarkar created the Entry so maybe he could also update it?

**Comment by MikeMcC399** [comment]
Also please update the latest version variable for iOS. See https://github.com/corona-warn-app/cwa-website/issues/559.

**Comment by Ein-Tim** [comment]
Closed via #561
