### ISSUE TITLE
Old app version 1.5.x shown instead of current 1.6 version

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#559]
## Where to find the issue 
https://www.coronawarn.app/en/
This is how the app works best
1. Download the current version of the app (iOS: 1.5.3 or Android: 1.5.1)

## Describe the issue
The main page https://www.coronawarn.app/en/ has not been updated after the release of CWA 1.6.x. It still shows the previous 1.5.x version as the current version.

https://apps.apple.com/de/app/corona-warn-app/id1512595757 lists iOS version 1.6.1 with date Nov 11, 2020.
https://play.google.com/store/apps/details?id=de.rki.coronawarnapp lists Android version 1.6.0 with date Nov 9, 2020.

## Suggested change
Update [gulpfile.js](https://github.com/corona-warn-app/cwa-website/commits/master/gulpfile.js) with new values for
[ios.current-app-version]
[android.current-app-version]

Review release process to ensure that a release of a new version to either of the app stores includes updating the website in addition.

**Comment by heinezen** [comment]
Fixed in #580
