### ISSUE TITLE
Enhance FAQ-entry "Wer hilft bei Fragen zur Corona-Warn-App?"

### ISSUE THREAD

**Issue by loki-cui** [corona-warn-app/cwa-website#560]
## Where to find the issue

https://www.coronawarn.app/de/faq/#who_can_help
https://www.coronawarn.app/en/faq/#who_can_help

## Describe the issue

In order to ease the search for relevant information, it was proposed by several users to enhance the information that is summarized under the above mention FAQ-entry

## Suggested change

After the following sentence, it makes sense to link the user to the RKI tool that shows the responsible health authorities:

>  Falls das Testergebnis nicht in der Corona-Warn-App abrufbar ist, sollte das zuständige Fachpersonal, Testcenter oder Gesundheitsamt kontaktiert werden, um das Testergebnis zu erhalten.

Pls. add [RKI PLZ Tool](https://tools.rki.de/PLZTool) in order to allow the user to directly search for the correct health authority by postal code or place

**Comment by dsarkar** [comment]
@loki-cui 
See the screenshots below. Shall I create PR for these changes?
![image](https://user-images.githubusercontent.com/1409741/98940015-9c68e780-24ea-11eb-8ae7-17dce7ece398.png)

![image](https://user-images.githubusercontent.com/1409741/98940061-b1457b00-24ea-11eb-8dfc-1066e6b87a8b.png)

**Comment by heinezen** [comment]
Closed via #562

**Comment by svengabr** [comment]
Thanks!
