### ISSUE TITLE
Telephone number in footer not place correctly

### ISSUE THREAD

**Issue by Lucurus** [corona-warn-app/cwa-website#57]
## Where to find the issue

https://www.coronawarn.app/en/ in the footer

## Describe the issue

When opening the website on a mobile device, the telephone number is not fully displayed. 

Here tested on an iPhone 11 Pro Max

![IMG_2579](https://user-images.githubusercontent.com/10774221/84710877-5fadba00-af65-11ea-9b63-62c90b6c7e5d.png)

## Suggested change

The placement of the telephone number should adapt to smaller screen sizes.

**Comment by SebastianWolf-SAP** [comment]
Yes, we are aware of this issue. We will have a look. In the meantime: Contributions are appreciated! :)

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by corneliusroemer** [comment]
Someone was 2 min faster, I didn't expect a duplicate to be opened within seconds before I post.

In my case it's Android 10 OnePlus 6T Chrome.

**Comment by corneliusroemer** [comment]
@SebastianWolf-SAP if you give us a slice of the 20 million ;)

**Comment by Lucurus** [comment]
@SebastianWolf-SAP Thanks for the update! Sorry for not contributing myself but it has been ages since I’ve worked on a website, I didn’t want to submit something that takes more time reviewing that developing. ;)

Thanks and good luck tomorrow!

**Comment by SebastianWolf-SAP** [comment]
Still a lot of activity here. ;) We might all be a little sleepless tonight, I understand that... There is an interim fix ready - it's still not ideal, but at least we shouldn't have the ugly cut-off anymore.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by Lucurus** [comment]
Haha, that could be true...!

Confirmed working on my side, thanks for the quick implementation.
