### ISSUE TITLE
Cannot add label to issue

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#574]
## Where to find the issue 
https://github.com/corona-warn-app/cwa-website/blob/master/CONTRIBUTING.md#issues-and-planning

### Issues and Planning
advises

"Please apply one or more applicable [labels ](https://github.com/corona-warn-app/cwa-website/labels) to your issue so that all community members are able to cluster the issues better."

I have Contributor status and I cannot add a label, so something is wrong.

## Suggested change
Either remove the advice to add labels or enable users, who are not Members, to add labels.

**Comment by heinezen** [comment]
Fixed in #652
