### ISSUE TITLE
FAQ: Multiple exposure checks not currently accurate

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#578]
## Where to find the issue 
https://www.coronawarn.app/en/faq/#multiple_exposure_checks
"My exposure log shows multiple, simultaneous checks for exposures. Is that an error?"

## Describe the issue
It is no longer true that there are multiple, simultaneous checks for exposures. In CWA Android 1.7.x with only mobile network connectivity there is one check per day done, plus additional checks every 4 hours when WiFi is available. In no cases are there "multiple, simultaneous checks for exposures". The multiple simultaneous checks disappeared with the release of version 1.6.0.

## Suggested change
Remove the article or mark it obsolete since it describes previous versions only.

**Comment by Ein-Tim** [comment]
@MikeMcC399 iOS also modified this (with iOS 13.7 and higher)

**Comment by heinezen** [comment]
Addressed in #644
