### ISSUE TITLE
Checking PR builds not triggering for forks

### ISSUE THREAD

**Issue by heinezen** [corona-warn-app/cwa-website#579]
CI checks for PRs from forks are not executing or are not reported properly. After submitting the PR, the status remains at

> *Expected — Waiting for status to be reported*

![grafik](https://user-images.githubusercontent.com/6852422/99190277-ea3d5400-2765-11eb-9742-c40514b87f5c.png)

Branches from members in the Github repo are unaffected.

**Comment by svengabr** [comment]
My process is to push the fork to origin, this will trigger the CI and the checks will run automatically.

**Comment by MikeMcC399** [comment]
@svengabr 
Just to be clear: this is your process on the receiving side of a pull request from a fork and not something I need to do differently as a submitter from a fork? Correct?

**Comment by heinezen** [comment]
@svengabr I can do this, but outside contributors can't. For them, it's also more crucial that we can check the build for errors because otherwise I would have to clone and check their fork locally.

**Comment by heinezen** [comment]
Fixed in #601
