### ISSUE TITLE
[svengbr] Differences in package-lock.json from nodejs

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#584]
## Your Question 
Following instructions from https://github.com/corona-warn-app/cwa-website#getting-started
I downloaded version 14.15.0 LTS (includes npm 6.14.8) from https://nodejs.org/en/
then ran 
`npm install`
which prompted me to install security fixes, and I did that.

This has updated package-lock.json to have different values from the https://github.com/corona-warn-app/cwa-website/blob/master/package-lock.json in the master branch.

How can these differences be reconciled? Do I need to install a different version of nodejs or does master need updating with security patches?

Here is a snippet of differences:
```
     "bl": {
-      "version": "1.2.2",
-      "resolved": "https://registry.npmjs.org/bl/-/bl-1.2.2.tgz",
-      "integrity": "sha512-e8tQYnZodmebYDWGH7KMRvtzKXaJHx3BbilrgZCfvyLUYdKpK1t5PSPmpkny/SgiTSCnjfLW7v5rlONXVFkQEA==",
+      "version": "1.2.3",
+      "resolved": "https://registry.npmjs.org/bl/-/bl-1.2.3.tgz",
+      "integrity": "sha512-pvcNpa0UU69UT341rO6AYy4FVAIkUHuZXRIWbq+zHnsVcRzDDjIAhGuuYoi0d//cwIwtt4pkpKycWEfjdV+vww==",
       "requires": {
         "readable-stream": "^2.3.5",
         "safe-buffer": "^5.1.1"
       }
```
git diff output is attached.
 
[git_diff.txt](https://github.com/corona-warn-app/cwa-website/files/5545877/git_diff.txt)

**Comment by MikeMcC399** [comment]
Would it be better to have used
`npm ci` instead of
`npm install` on the local copy of the repo?
See https://stackoverflow.com/questions/53469032/using-npm-ci-instead-of-npm-install-for-deterministic-project-setup

The repo already contains the file https://github.com/corona-warn-app/cwa-website/blob/master/package-lock.json so it seems to meet the prerequisites for using `npm ci`.

After reverting `package-lock.json` I tried `npm ci` and it got rid of the git diff(erences). 🙂

**Comment by MikeMcC399** [comment]
I ran through this in a clean VM and it seems that `npm ci` instead of `npm install` is the way to go.

```
install atom 1.53.0
install git 2.29.2.2
install node.js 14.15.0 accepting defaults
Select Automatically install the necessary tools.

in local directory
git clone https://github.com/<github username>/cwa-website (from fork)
git checkout -b npm-test
npm ci
npm run build
npm start (Website is displayed in browser)
git diff (shows no differences)
```

**Comment by svengabr** [comment]
@MikeMcC399 thanks for your detailed input!

I had this on my desk to fix the dependencies for quite some time now. Yesterday I did already increase the bl version [here](https://github.com/corona-warn-app/cwa-website/pull/594).

I have updated the `package-lock.json` and no more warnings appear for me now.

Pull Request: https://github.com/corona-warn-app/cwa-website/pull/606

**Comment by MikeMcC399** [comment]
@svengabr 
Thank you for updating the dependencies.

Now 
```
npm ci 
npm audit
```
shows
```
found 0 vulnerabilities
 in 1564 scanned packages
```

and
`run install`
shows
`found 0 vulnerabilities`

**Comment by MikeMcC399** [comment]
@svengabr 
There is one remaining issue caused by 
"cypress-plugin-snapshots": "^1.4.3"

I sent mail to 'corona-warn-app.opensource@sap.com' with some screen shots.

**Comment by MikeMcC399** [comment]
Closing, since this issue is a mixture of several different topics.
Dependabot alerts need to be addressed as a matter of routine by the repo maintainer.
