### ISSUE TITLE
Favicon as SVG

### ISSUE THREAD

**Issue by Clashbestie** [corona-warn-app/cwa-website#59]
Add a Favicon as SVG would be better because only one line is needed to tell the browser where it is located and it will look good in any size.

**Comment by weissjulian** [comment]
Hello Clashbestie, Internet Explorer and many mobile browsers do not support SVG favicons and Safari does not officially support them. Therefore SVG icons would not work everywhere. 
And this is not really a bug, it works. Or does it not work for you?
Best regards

**Comment by tkowark** [comment]
Yes, unfortunately some legacy there. We'll stick to the PNG versions
