### ISSUE TITLE
Website lacks many Security- and Privacy Features

### ISSUE THREAD

**Issue by TomTeeJay** [corona-warn-app/cwa-website#6]
Disclaimer: I am not sure if the website issues for https://www.coronawarn.app should be post here. So please feel free to forward this to whom is responsible for)

Though the website claims to be privacy-friendly, there are still these issues:

- Unsafe TLS Encryption Configuration
  TLS 1.3 is not enabled, TLS 1.0 is still active (!)
  Please check Ciphers aswell.
- CSP (Content Security Policy) is missing
- "no-referrer" tag is missing. Referers are told to 3rd parties.
- Several X-Headers (X-Content-Type, X-Frame, X-XSS-Protection) are missing

Please use common test suites to check website for security and privacy:

- https://observatory.mozilla.org/
- https://webbkoll.dataskydd.net/de
- https://www.ssllabs.com/ssltest/

**Comment by Julian-B90** [comment]
The following resource can´t be found
https://www.coronawarn.app/assets/css/ajax-loader.gif

<img width="451" alt="Bildschirmfoto 2020-06-02 um 22 07 39" src="https://user-images.githubusercontent.com/4377396/83564817-a3dc9b80-a51d-11ea-9a7b-09c944b70459.png">

**Comment by tkowark** [comment]
@Julian-B90 I'll create a new issue from your last comment

**Comment by SebastianWolf-SAP** [comment]
Sorry that it took a while, but finally all mentioned issues should be fixed. See also the results on:
- https://observatory.mozilla.org/analyze/coronawarn.app
- https://webbkoll.dataskydd.net/de/results?url=http%3A%2F%2Fcoronawarn.app
- https://www.ssllabs.com/ssltest/analyze.html?d=coronawarn.app
- https://www.ssllabs.com/ssltest/analyze.html?d=www.coronawarn.app

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
