### ISSUE TITLE
FAQ: How to view participating countries - Step 3 is wrong

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#608]
## Where to find the issue
https://www.coronawarn.app/en/faq/#interoperability_countries
To view more information in the app, tap

1. 'EXPOSURE LOGGING ACTIVE/STOPPED'
2. Then tap 'Transnational Exposure Logging'.
3. At last click on 'Participating Countries'.

## Describe the issue
On CWA Android 1.6.1 only two taps are necessary to show Participating Countries. Step 3 in the instructions is not right because Transnational Exposure Logging Participating Countries is one element in the UI.

---
Tap on EXPOSURE LOGGING ACTIVE

![EN Main screen](https://user-images.githubusercontent.com/66998419/99841479-83a5a500-2b6e-11eb-8085-f4dfa36af921.jpg)

---
Tap on Transnational Exposure, Logging Participating Countries

![EN Exposure Logging](https://user-images.githubusercontent.com/66998419/99841934-3ece3e00-2b6f-11eb-93eb-4c7825918c72.jpg)

---
In Transnational Exposure Logging, scroll down to the list of countries

![EN TNS scroll](https://user-images.githubusercontent.com/66998419/99841976-50afe100-2b6f-11eb-8438-6188ac133bd7.jpg)

---
![EN Country list](https://user-images.githubusercontent.com/66998419/99842141-966ca980-2b6f-11eb-8eaf-86da3a7c8d55.jpg)

## Suggested change
Check that CWA iOS behaves the same way as CWA on Android.

If yes, then replace Step 3 with:
"scroll down to the list of countries".

**Comment by Ein-Tim** [comment]
@MikeMcC399 iOS behaves like Android.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for the confirmation about iOS!
