### ISSUE TITLE
[svengbr] cypress-plugin-snapshots causes GitHub Dependabot message

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#615]
## Where to find the issue
https://github.com/corona-warn-app/cwa-website/blob/master/package.json

Line 54
```
"devDependencies": {
   ...
    "cypress-plugin-snapshots": "^1.4.4",
   ...  
}
```

## Describe the issue
This is a follow-on to [Differences in package-lock.json from nodejs](https://github.com/corona-warn-app/cwa-website/issues/584) concerning the web test environment.

cypress-plugin-snapshots defined in the `devDependencies` object of [package.json](https://github.com/corona-warn-app/cwa-website/blob/master/package.json) causes the github Dependabot to warn that jpeg-js needs to be updated to >=0.4.0, however that is not possible because of dependencies defined in the package cypress-plugin-snapshots@1.4.3.

Dependabot advises:
`cypress-plugin-snapshots@1.4.4 requires jpeg-js@^0.3.4 via a transitive dependency on @jimp/jpeg@0.10.3`

There is further information in https://github.com/advisories/GHSA-w7q9-p3jq-fmhm.

Edit:
Originally 
    "cypress-plugin-snapshots": "^1.4.3",
now
    "cypress-plugin-snapshots": "^1.4.4",
and the issue is the same.

**Comment by DawChihLiou** [comment]
Link to PR https://github.com/meinaart/cypress-plugin-snapshots/pull/159 in `cypress-plugin-snapshots`

**Comment by MikeMcC399** [comment]
@DawChihLiou 
Thanks for drawing the attention to the issue in the cypress-plugin-snapshots repo!

https://github.com/oliver-moran/jimp/blob/master/README.md#notice-of-potentially-breaking-change includes:

> ## Notice of potentially breaking change
>
> As of v0.10.4, core-js is no longer included with jimp or its extensions. If you rely on core-js, install it with either `yarn add core-js` or `npm i core-js`

which may make fixing the dependencies more complicated.

At least now the issue has been reported in the correct place.

**Comment by DawChihLiou** [comment]
Glad to help!
Updating `@jimp` alone should be sufficient. I double checked and there's no dependencies depend on `core-js` other than `@jimp` in the plugin.

**Comment by MikeMcC399** [comment]
@DawChihLiou 
Nobody has responded to your PR https://github.com/meinaart/cypress-plugin-snapshots/pull/159 yet. In fact, the repo https://github.com/meinaart/cypress-plugin-snapshots/pulse/monthly show little activity,  and there haven't been any commits pushed to master there in the last month. 😞

**Comment by MikeMcC399** [comment]
@DawChihLiou 
I was notified that your PR https://github.com/meinaart/cypress-plugin-snapshots/pull/159 was merged! 🎉 

I guess the maintainer needs to release a new version (currently at https://github.com/meinaart/cypress-plugin-snapshots/releases/tag/v1.4.4) before this makes any difference externally. I looks like they are bundling together quite a few different changes, so let's wait and see!

**Comment by DawChihLiou** [comment]
Awesome! Thanks for keeping an eye on it!

**Comment by MikeMcC399** [comment]
https://github.com/meinaart/cypress-plugin-snapshots/releases/tag/v1.4.4 is still the latest release from over one year ago with no sign of a new release.

GitHub regularly identifies dependabot alerts in this repository, so it does not seem necessary to single out this particular one.

Closing as unresolved.
