### ISSUE TITLE
Website responds with 504

### ISSUE THREAD

**Issue by nils4cosee** [corona-warn-app/cwa-website#62]
## Where to find the issue

Disable you browser-cache, then go to

https://www.corona-warn-app.de

## Describe the issue

The website seems to be under a lot of load right now. When I request it, most of the time,

```
This page isn’t working
www.corona-warn-app.de took too long to respond.

HTTP ERROR 504
```

The site beyond the redirect works fine...

## Suggested change

Maybe the redirecting servers have to be scaled up.

**Comment by montogeek** [comment]
Do you mean https://www.coronawarn.app/en/ ?

**Comment by nils4cosee** [comment]
when you open the app and click on the "share" butt, a message will be generated that leads to https://www.corona-warn-app.de

That was the page I meant. But it seems to work better now.

**Comment by tkowark** [comment]
Thanks for your message. This repository is only for the coronawarn.app page (for the open source community), not the official app website, which is https://www.corona-warn-app.de
