### ISSUE TITLE
FAQ entries reg. exposure check every 24 hrs need to be updated

### ISSUE THREAD

**Issue by loki-cui** [corona-warn-app/cwa-website#628]
## Where to find the issue
e.g. https://www.coronawarn.app/de/faq/#risk_update_24

## Describe the issue
All entries reg. the exposure check once every 24 hrs need to be updated as the check cycle was increased with release 1.7 and higher. See also the new [blog post](https://www.coronawarn.app/en/blog/2020-11-25-corona-warn-app-version-1-7/) 
"With Corona-Warn-App Version 1.7, the exposure check can be run several times a day so that users are informed about possible risk encounters sooner. This repeated daily check is performed automatically. However, it requires a Wi-Fi connection. The standard daily exposure check is still performed once a day, no matter if the smartphone is connected to a Wi-Fi network or not."

## Suggested change
All entries need to be reviewed and adapted. 
Pls. keep in mind that WLAN is required for multiple (= up to 6) checks per days. While using mobile data, it stays with the check once every 24 hrs due to the zero rating commitment of the network providers.

**Comment by MikeMcC399** [comment]
Here is a list of articles which are affected:

FAQ Link
--
https://www.coronawarn.app/en/faq/#multiple_exposure_checks
https://www.coronawarn.app/en/faq/#exposure_check
https://www.coronawarn.app/en/faq/#risk_update_24

**Comment by heinezen** [comment]
Resolved by #632
