### ISSUE TITLE
FAQ: Updates for changed exposure check strategy

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#629]
## Where to find the issue

FAQ Link
-- |
https://www.coronawarn.app/en/faq/#multiple_exposure_checks
https://www.coronawarn.app/en/faq/#exposure_check
https://www.coronawarn.app/en/faq/#risk_update_24

and corresponding https://www.coronawarn.app/de/faq/ German language articles.

## Describe the issue

According to the blog article [Corona-Warn-App Version 1.7 can perform the exposure check several times a day](https://www.coronawarn.app/en/blog/2020-11-25-corona-warn-app-version-1-7/) the exposure check strategy has changed with the release of CWA V1.7. This makes the text of several FAQ articles out of date.

The article says:

"With Corona-Warn-App Version 1.7, the exposure check can be run several times a day so that users are informed about possible risk encounters sooner. This repeated daily check is performed automatically. However, it requires a Wi-Fi connection. The standard daily exposure check is still performed once a day, no matter if the smartphone is connected to a Wi-Fi network or not."

FAQ Link | Current text (partial extract)
-- | --
https://www.coronawarn.app/en/faq/#multiple_exposure_checks | It is therefore not an error   that multiple, seemingly simultaneous entries are visible in the exposure   check history. (See also https://github.com/corona-warn-app/cwa-website/issues/578.)
https://www.coronawarn.app/en/faq/#exposure_check | When the app was running   constantly during the last two weeks, you should see 14 checks within the   last 24 hours.
https://www.coronawarn.app/en/faq/#risk_update_24 | Updating only around every 24   hours is due to API restrictions and to ensure consistency between the   Corona-Warn-App versions for iOS and Android.

## Suggested change

1. Review each of the articles and modify the text so that it agrees with the blog.
2. Check that the detailed behavior of the app is described correctly for the currently released version.

**Comment by Ein-Tim** [comment]
See also: #628

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> See also: #628

Whoops! Somehow I missed this new issue. I will close my issue and add the information to the existing issue.
