### ISSUE TITLE
Untrusted root ca certificate https://corona-warn-app.de/ 

### ISSUE THREAD

**Issue by manuros** [corona-warn-app/cwa-website#63]
The URL used in the iOS applications:
https://corona-warn-app.de/
Shows a certificate error due to untrusted root CA on MacOS/Chrome and iOS/Safari

![Screen Shot 2020-06-16 at 09 34 10](https://user-images.githubusercontent.com/5741593/84745319-b2fb2900-afb4-11ea-8cb5-0616d72e8e97.png)
.

**Comment by n-thumann** [comment]
Hm, I am unable to reproduce this error. Both https://corona-warn-app.de/ and its redirect to https://www.bundesregierung.de/breg-de/themen/corona-warn-app are validly signed by TeleSec. Tested on macOS Firefox, Chrome and Safari. Maybe try refreshing your caches? ✌️

**Comment by tkowark** [comment]
Thanks for spotting that issue. This should be solved throughout the day when the certificate reached all necessary caches.

Furthermore, please note that this repository is for the open source community website (coronawarn.app), not the app website (corona-warn-app.de)
