### ISSUE TITLE
New FAQ entry reg. bluetooth measurements

### ISSUE THREAD

**Issue by loki-cui** [corona-warn-app/cwa-website#636]
## Where to find the issue
no details yet

## Describe the issue
There are a lot of questions on how the acquisition of the Bluetooth signal exactly works and there is no FAQ entry to answer such questions.

## Suggested change
Pls. find below some first proposals that could be added in the section "Application" / "Anwendung" 

**DE**

### Wie funktioniert die Erfassung via Bluethooth-Signal und welche Logik steckt dahinter?

**Wie lang muss die Begegnung sein, damit sie gezählt wird?** 
Die durch die Corona-Warn-App genutzte Schnittstelle der jeweiligen Geräte führt alle 3 bis 5 Minuten einen 4-sekündigen Scan durch. Damit eine Begegnung sicher erfasst wird, muss sie mindestens 5 Minuten andauern. Das bedeutet aber auch, dass eine sehr kurze Begegnung erfasst werden kann, sofern sie in den 4-sekündigen Scanvorgang fällt. Zum Beispiel kann eine 4-sekündige Begegnung an der Ampel zur Anzeige einer Begegnung mit einem niedrigen Risiko führen.

**Werden Begegnungen, die nicht in diesen Scan-Vorgang fallen, dann nicht gezählt?**
Das ist richtig. Allerdings werden Begegnungen gemäß der Vorgaben des Robert-Koch-Instituts erst gezählt, wenn sie über mehrere Minuten angedauert haben, d.h. implizit eh innerhalb mehrere Scanvorgänge erfasst wurden.

**Was ist der maximale Abstand, damit eine Begegnung erfasst wird?**
Es werden alle Begegnungen so lange gezählt, wie das Bluetooth-Signal reicht. Auf freier Sicht der Handys kann die Sichtweise durchaus 15m oder mehr betragen. 

**Wie ist die Reichweite des Bluetooth-Signals und wie verändert es sich bei Dämpfung (Handy in der Tasche, etc.)?**
Eine Anzeige von Risikobegegnungen wird in der Regel nicht beeinträchtigt und eventuelle Umgebungseinflüsse sind in unserem Berechnungsalgorithmen berücksichtigt. Mit Bluetooth Low Energy (LE) haben wir aber auch eine Technik im Einsatz, die durch Umgebungsfaktoren beeinflussbar ist.

**EN**

### How does the acquisition via Bluetooth signal actually work and what is the logic behind it?

**How long must the encounter be for it to be counted?**
The interface of the respective devices used by the Corona-Warn-App carries out a 4-second scan every 3 to 5 minutes. For an encounter to be reliably detected, it must last at least 5 minutes. However, this also means that a very short encounter can be detected, provided it falls within the 4-second scan. For example, a 4-second encounter at a traffic light can result in a low-risk encounter being displayed.

**Are encounters that do not fall within this scan not counted?**
This is correct. However, according to the specifications of the Robert Koch Institute, encounters are only counted if they have lasted for several minutes, i.e. if they have been implicitly recorded within several scanning processes anyway.

**What is the maximum distance for an encounter to be recorded?**
All encounters are counted as long as the Bluetooth signal lasts. On free view of the cell phones, the visibility can be 15m or more. 

**What is the range of the Bluetooth signal and how does it change with attenuation (cell phone in the pocket, etc.)?**
A display of risk encounters is usually not affected and possible environmental influences are taken into account in our calculation algorithm. With Bluetooth Low Energy (LE), however, we also have a technology in use that can be influenced by environmental factors.

**Comment by loki-cui** [comment]
@MikeMcC399 : Would you mind reading the English version? ;)

**Comment by Ein-Tim** [comment]
@loki-cui 
I think it would be good to not use "Bluetooth LE" but rather the full term: "Bluetooth Low Energy". 
This will help non-technical users to understand it better, I think 👍

**Comment by MikeMcC399** [comment]
@loki-cui 
> Would you mind reading the English version? ;)

I'm happy to do that!

In both languages Bluetooth is spelled incorrectly in the title as "Bluthooth".
Also in the title of this issue "New FAQ entry reg. blutooth measurments" bluetooth and measurements are spelled incorrectly.

I have some problems with the German text though, before I get to the English translation! Maybe you could get it put into a PR so it can be commented on line by line?

**Comment by dsarkar** [comment]
- Corrected Bluetooth in the text
- Low Energy added

**Comment by MikeMcC399** [comment]
@dsarkar 
It's a minor point, but "measurments" in the title of the issue is still spelled incorrectly.
I'm just working on some detailed comments on the English text and I will post them later today.

**Comment by loki-cui** [comment]
Okay, changing LE to Low Energy and correct the obvious misspelling in 'Bluethooth' is done ;)

What do you think about a content change in such a direction? (I'll start with DE only and will only do a translation if we agree on the content)

### Wie funktioniert die Erfassung von Begegnungen via Bluethooth-Signal und wie wird mein Infektionsrisiko berechnet?

Das Infektionsrisiko wird aus folgenden Faktoren berechnet:

(1)	Dauer der Begegnung
(2)	Abstand bei der Begegnung 
(3)	Zeit, die seit der Begegnung vergangen ist
(4)	Infektiosität (abgeleitet aus der Information, wann und ob die Symptome eingesetzt haben)

Überschreitet der daraus ermittelte Risikowert eine [Schwelle](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation), die das Robert Koch-Institut vorgibt, erhalten die Benutzer*innen eine Benachrichtigung über ein erhöhtes Infektionsrisiko. Sollten die genannten Schwellenwerte unterschritten worden sein, sind zwar die Bedingungen für eine Begegnung mit erhöhtem Risiko nicht erfüllt, die Anzahl an Begegnungen würde sich aber trotzdem erhöhen. 

**Wie lang muss die Begegnung sein, damit sie gezählt wird?**
Die durch die Corona-Warn-App genutzte Schnittstelle der jeweiligen Geräte führt alle 3 bis 5 Minuten einen 4-sekündigen Scan nach anderen Geräten durch. Sehr kurze Begegnungen - bspw. eine Begegnung an einer Ampel oder auf einem Parkplatz - können daher zwar in den Scan-Vorgang fallen, werden jedoch nur als Begegnung mit niedrigem Risiko aufgeführt. Abhängig von der Dauer, Abstand, Zeit und Infektiosität dieser Begegnung, erhalten die Nutzer*innen eine Meldung mit entsprechend niedrigem Risiko (grün) oder hohem Risiko (rot). 

**Wie ist die Reichweite des Bluetooth-Signals?**
Es werden alle Begegnungen so lange gezählt, wie das Bluetooth-Signal reicht. Auf freier Sicht der Handys kann die Sichtweise durchaus 15m oder mehr betragen.

**Wie verändert sich die Reichweite bei Dämpfung (Handy in der Tasche, etc.)?**
Die Anzeige von Risikobegegnungen wird in der Regel nicht beeinträchtigt und eventuelle Umgebungseinflüsse wurden in den Berechnungsalgorithmen berücksichtigt. Mit Bluetooth Low Energy haben wir aber jedoch eine Technik im Einsatz, die durch Umgebungsfaktoren beeinflussbar ist.

**Wie verhält sich die Corona-Warn-App, wenn eine infizierte Person in einem Abstand von 5 bis 10 Metern am Haus vorbeiläuft? Wird diese „Begegnung“ erfasst?**
Selbst wenn es in dieser Situation nicht zu einer Begegnung mit einem erhöhten Risiko kommt, ist es technisch durchaus möglich, dass die Kennung anderer Nutzer*innen empfangen wurde, beispielsweise, wenn das eigene Telefon auf der Fensterbank lag. Durch diese „Begegnung“ würde sich zwar keine Begegnung mit erhöhtem Risiko ergeben, durchaus aber die Anzahl der Begegnungen verändern.

**Comment by MikeMcC399** [comment]
@loki-cui 
Since you asked me to comment on the original English version, that is what I did. I will still let you have these comments, even though you have now re-written the German text. You might see what I was having difficulty with in the first version. I will look at your new German version.

I think anything you write should be based on explaining, extending or translating what is already in the app documentation on https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md

**Comment by MikeMcC399** [comment]
@loki-cui 
The comments are now obsolete, but I am posting them anyway.

Original text | Comments
-- | --
How does   the acquisition via Bluetooth signal actually work and what is the logic   behind it? |  
**How   long must the encounter be for it to be counted? | Suggest: "How long must the   encounter last for it to be counted?"
The   interface of the respective devices used by the Corona-Warn-App carries out a   4-second scan every 3 to 5 minutes. | Suggest: "Each mobile   device used by the Corona-Warn-App carries out a 4-second scan every 3 to 5   minutes."
For an   encounter to be reliably detected, it must last at least 5 minutes. | This isn't about reliably   detecting. It is about registering the encounter as a candidate for increased   risk, if in addition the encounter was also measured as close enough.   Suggest: "For an encounter to be used in the evaluation for increased   risk, it must last at least 5 minutes, which means that it must have been   detected at least in two consecutive scans." This however contradicts   what it said in   https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md   "All encounters for a diagnosis key that lasted less than 10 minutes in   total (regardless of how close the smartphones came during that time) or   during which the smartphones were more than 8 meters (>73 dB attenuation)   apart on average (regardless of how long the encounter lasted) are discarded   as negligible risk."
However,   this also means that a very short encounter can be detected, provided it   falls within the 4-second scan. | "this" in this   sentence refers to the first sentence of the paragraph, so it is difficult to   understand.
For   example, a 4-second encounter at a traffic light can result in a low-risk   encounter being displayed. | You could combine the two   sentences and say: "A short single encounter during the 4-second scan,   such as at a traffic light, can be later used in the evaluation for low   risk."
**Are   encounters that do not fall within this scan not counted? | This is a double negative.   Suggest "What happens to encounters outside the 4-second scan?"
This is   correct. | This sentence answers the   question in the sub-title. If the title is changed then the answer would need   to be changed to "Encounters outside the 4-second scan are not   registered."
However,   according to the specifications of the Robert Koch Institute, encounters are   only counted if they have lasted for several minutes, i.e. if they have been   implicitly recorded within several scanning processes anyway. | This sentence answers another   question, but this question was already answered in the previous sub-title.   Also it introduces the Robert Koch Institute in the middle of the   explanation, which is confusing, as though this is the only place where RKI   has something to say. Suggest removing this sentence and adding an   explanation into the sentence about 5 minutes as already written above.
**What   is the maximum distance for an encounter to be recorded? |  
All   encounters are counted as long as the Bluetooth signal lasts. | This sentence sounds like it is   describing time not distance. Suggest: "All encounters are recorded   independently of the distance."
On free   view of the cell phones the visibility can be 15m or more. | Signals from the Bluetooth Low   Energy technology used by the Corona-Warn-App can reach other mobile devices   which are 15 meters distant or even further away outdoors. Any encounters   which were more than 8 meters away are however discarded in the risk assessment.
**What   is the range of the Bluetooth signal and how does it change with attenuation   (cell phone in the pocket, etc.)? | This question is mixed up with   the previous one. I suggest removing this question and combining with the   previous one.
A   display of risk encounters is usually not affected and possible environmental   influences are taken into account in our calculation algorithm. With   Bluetooth LE, however, we also have a technology in use that can be   influenced by environmental factors. | This contradicts what it said in   https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md.   Environment does affect the signal and cannot be taken into account. The   mobile device can't detect for instance if there is a physical separation   between another device, such as in an apartment block with a wooden floor /   ceiling between flats on adjacent floors.

**Comment by loki-cui** [comment]
> @loki-cui
> Since you asked me to comment on the original English version, that is what I did. I will still let you have these comments, even though you have now re-written the German text. You might see what I was having difficulty with in the first version. I will look at your new German version.
> 
> I think anything you write should be based on explaining, extending or translating what is already in the app documentation on https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md

Sorry that our work has overlapped ;) Hope the new proposal fits better. 

We'd like to enhance the FAQ section by less technical information in order to also provide some basic information for "normal users" that just want to understand the app better. So please consider this in your review :)

**Comment by MikeMcC399** [comment]
@loki-cui 
At first glance, your new proposal is much more readable. I will take a detailed look at it soon.

In the heading:
"Wie funktioniert die Erfassung von Begegnungen via **Bluethooth**-Signal und wie wird mein Infektionsrisiko berechnet?"
Bluetooth is still spelled incorrectly though.

**Comment by heinezen** [comment]
> **Wie ist die Reichweite des Bluetooth-Signals?**
> Es werden alle Begegnungen so lange gezählt, wie das Bluetooth-Signal reicht. Auf freier Sicht der Handys kann die Sichtweise durchaus 15m oder mehr betragen.

I think this section could use some improvement.

Suggestions:

> Wie ist die Reichweite des Bluetooth-Signals?

Wie **groß** ist die Reichweite des Bluetooth-Signals?

> Es werden alle Begegnungen so lange gezählt, wie das Bluetooth-Signal reicht.

Alle Begegnungen in Reichweite des Bluetooth-Signals werden erfasst.

> Auf freier Sicht der Handys kann die Sichtweise durchaus 15m oder mehr betragen.

* I don't think "Sichtweise" and "freie Sicht" are applicable here
* Imo this sentence should come first as it contains the most relevant info

Wenn sich zwischen den Geräten keine Hindernisse befinden, kann die Reichweite durchaus 15m oder mehr betragen.

**Comment by daimpi** [comment]
@MikeMcC399 
Very good points 👍 
I just want to stress your last point as it is still relevant for the [new version](https://github.com/corona-warn-app/cwa-website/issues/636#issuecomment-737833825):


> Original text |	Comments
> ------------ |--------
> A display of risk encounters is usually not affected and possible environmental influences are taken into account in our calculation algorithm. With Bluetooth LE, however, we also have a technology in use that can be influenced by environmental factors. |	This contradicts what it said in [corona-warn-app/cwa-documentation@`master`/cwa-risk-assessment.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md). Environment does affect the signal and cannot be taken into account. The mobile device can't detect for instance if there is a physical separation between another device, such as in an apartment block with a wooden floor / ceiling between flats on adjacent floors.

This is a very important point: in the best case (calibrated) BLE attenuation works as a noisy proxy for distance, but in non-optimal conditions this becomes very unreliable to put it mildly (cf. e.g. [here](https://github.com/corona-warn-app/cwa-documentation/issues/394#issuecomment-691083023) and [here](https://github.com/corona-warn-app/cwa-documentation/issues/321)). And contrary to the original text there is actually **no** mechanism within CWA or ENF which would mitigate this at least not to my knowledge.

**Comment by loki-cui** [comment]
sorry for closing and opening ->pressed the wrong button by mistake...

**Comment by loki-cui** [comment]
Thank you all for your feedback. We're trying to take everything into account, but as the issue will be completey revised and splitted into separate questions after the release 1.9.1, I'd to close this one.

**Comment by vaggelisdouros** [comment]
2 questions from my side:

a) can you provide the formula that translates the bluetooth signal attenuation (measured in dB) into distance (measured in meters)? In multiple cases, it is mentioned that a 73 dB attenuation corresponds to a distance of 8 meters, whereas 55 dB are translated into 1.5 meters, but i have not found the formula used or at least a reference to a paper/textbook.

b) In the updated diagram for risk calculation with enf v2, it is unclear to me how the time where the signal attenuation is  between 63 dB and 73 dB is taken into account. Unless there is a typo, It seems that this signal is considered harmless and does not take part in the calculation of the weighted exposure time (even with a 0.5 coefficient), therefore i do not really understand whether the threshold is set to 73 db or 63 dB [https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf](url)
