### ISSUE TITLE
New FAQ entry reg. the assessment of risk encounters 

### ISSUE THREAD

**Issue by loki-cui** [corona-warn-app/cwa-website#637]
## Where to find the issue
no details yet

## Describe the issue
There are a lot of questions on how to assess the risk status, Thus, it makes sense to add some further explantions.

## Suggested change
Pls. find below some first proposals that could be added in the section "Application" / "Anwendung".
Again: The first proposal only in DE. The translation can be easily added later. 

### Nach welchen Kriterien werden Begegnungen bewertet und wie unterscheiden sich die Handlungsempfehlungen?

Die Corona-Warn-App hat drei verschiedene Statusanzeigen: "unbekanntes Risiko" (grau), "niedriges Risiko" (grün) und "erhöhtes Risiko" (rot). 

Bei der Status­anzeige „un­be­kanntes Risiko“ war die Risiko-E­rmittlung noch nicht lange genug aktiv, so dass keine Risiko­-Berech­nung vor­ge­nommen werden konnte.
Wenn Ihnen auf Ihrem Smartphone Begegnungen mit erhöhtem oder niedrigen Risiko angezeigt werden, dann bedeutet dies, dass Ihr Smartphone und das einer Person, die sich später in der App als infiziert gemeldet hat, in den vergangenen 14 Tagen  per Bluetooth Diagnoseschlüssel ausgetauscht haben. Auf Basis verschiedener Kriterien [Link zu späteren FAQ-Eintrag https://github.com/corona-warn-app/cwa-website/issues/636] wird diese Begegnung dann mit einem erhöhten oder geringen Infektionsrisiko eingestuft.

Wird Ihnen ein "niedriges Risiko" (grün) angezeigt, bedeutet es, dass sie Ihr Infektionsrisiko als gering einschätzt. Zusätzlich dazu informiert die App Sie aber, dass Ihr Smartphone sehr wohl eine oder mehrere Begegnungen in den vergangenen 14 Tagen mit (später positiv getesteten) Personen aufgezeichnet hat und zeigt auch an, wie viele. Die App zeigt in diesem Fall folgenden Hinweis an: "Ein niedriges Risiko besteht insbesondere dann, wenn sich Ihre Begegnung auf einen kurzen Zeitraum oder einen größeren Abstand beschränkt hat. Sie müssen sich keine Sorgen machen, und es besteht kein besonderer Handlungsbedarf."

Wird Ihnen ein "erhöhtes Risiko" (rot) angezeigt, sollten Sie zu Hause bleiben und Ihre direkten Kontakte reduzieren. Setzen Sie sich mit Ihrem Hausarzt, dem ärztlichen Bereitschaftsdienst unter 116117 oder dem Gesundheitsamt in Verbindung, um das weitere Vorgehen abzustimmen. Die Entscheidung, ob ein sog. PCR-Test durchgeführt wird, obliegt in letzter Instanz Ihrem Arzt. Sowohl das [RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Buerger/Orientierungshilfe_Buerger_de.pdf?__blob=publicationFile) als auch das [Bundesministerium für Gesundheit](https://www.bundesgesundheitsministerium.de/fileadmin/Dateien/3_Downloads/C/Coronavirus/Verordnungen/Corona-Test-VO_BAnz_AT_141020.pdf) haben jedoch entsprechende Orientierungshilfen bzw. Empfehlungen veröffentlicht.

**Ich habe die Meldung bekommen, dass ich eine niedrige Risikobegegnung hatte. Am nächsten Tag war sie wieder weg. Sollte das nicht erst nach 14 Tagen gelöscht werden?**
Sobald die App die aktuellen Diagnoseschlüssel (Positivkennungen) vom Server lädt, wird eine Überprüfung des Kontaktprotokolls durchgeführt. Dabei wird für jeden der letzten 14 Tage, für den Diagnoseschlüssel vorhanden sind, eine separate Überprüfung des Kontaktprotokolls durchgeführt. Das bedeutet also, die App gleicht die Begegnungen der letzten 14 Tage mit den Positivkennungen ab, um zu überprüfen, ob es zu einem Kontakt mit einer  positiv getesteten Person gekommen ist. Ist die Meldung über eine Begegnung mit niedrigem Risiko nach einem Tag verschwunden, bedeutet das, dass die entsprechende Begegnung in diesem Fall länger als 14 Tage zurückliegt.

**Ich habe in der App die Meldung bekommen, dass ich zwei Risiko-Begegnungen hatte. Die Statusanzeige ist aber grün geblieben. Muss ich mir Sorgen machen?**
Nein, denn auf Grundlage der Daten der Risiko-Ermittlung wird das Infektionsrisiko als niedrig eingestuft, da sich die Begegnung auf einen kurzen Zeitraum und/oder einen größeren Abstand beschränkt hat. Sie müssen sich keine Sorgen machen und es besteht kein besonderer Handlungsbedarf. Es wird empfohlen, sich an die allgemein geltenden Abstands- und Hygieneregeln zu halten. Sie müssen sich bei Begegnungen mit niedrigem Risiko nicht testen lasten. Die Verhaltensvorschläge sowie Infos zum Ermittlungszeitraum als auch zum Infektionsrisiko finden Nutzer*innen in der App selbst, wenn sie auf „Niedriges Risiko“ mit dem Finger tippen.

**Sind neue Begegnungen bei roter Statusanzeige solche mit niedrigem oder erhöhtem Risiko?**
Wenn Sie in der aktuellen Version der App (1.7.1) eine rote Statusanzeige (erhöhtes Risiko) haben, werden alle zukünftigen Risikokontakte auch mit erhöhtem Risiko angezeigt. Das passiert auch, wenn es sich möglicherweise um Kontakte mit eigentlich niedrigem Risiko handelt. Dieses Verfahren soll in den kommenden Updates der Corona-Warn-App geändert werden.

**Werden Risikobegegnungen mit der gleichen Person mehrfach am Tag gezählt?**
Mit der aktuellen Version des Exposure Notification Frameworks (V1), der Schnittstelle für Corona-Apps von Apple und Google, wird eine Person als eine Begegnung pro Tag gezählt. 

**Wird eine Begegnung an verschiedenen Tagen mit ein und derselben Person mehrfach gezählt?** 
Ja. Mit der aktuellen Version des Exposure Notification Frameworks (V1), der Schnittstelle für Corona-Apps von Apple und Google, wird eine Person als eine Begegnung pro Tag gezählt. Das heißt: eine Person, der ich gestern und heute begegnet bin, wird als zwei Begegnungen gezählt. Ein Tag ist hierbei als Mitternacht „UTC“ bis Mitternacht „UTC“ des Folgetages definiert.

**Warum erscheint keine rote Warnmeldung trotz Risikokontakt?**
Nach Eingabe eines positiven Testergebnisses kann es in Einzelfällen bis zu 48 Stunden dauern, bis in der Corona-Warn-App der anderen Nutzer*innen Risikobegegnungen mit einer roten Warnmeldung angezeigt werden.

Grundsätzlich ist auch zu berücksichtigen, dass die Smartphones der Personen, die im gleichen Haushalt leben, auch in unterschiedlichen Bereichen der Wohnung abgelegt werden (andere Räume, Etagen) und so die notwendigen Mindestvoraussetzungen für Dauer und Abstand bei einem Kontakt mit erhöhtem Risiko nicht oder zumindest nicht lang genug erfüllt werden.
Die aktuelle Version (V1) des Exposure Notification Framework (ENF, Schnittstelle für die COVID-19-Begegnungsaufzeichnungen) berechnet den Mittelwert der Entfernung zu einem bestimmten Kontakt im Laufe des Tages. Diesen Mittelwert verwendet die Corona-Warn-App für die Risikoermittlung. Wenn die Smartphones in einem gemeinsamen Haushalt beispielsweise für 8 Stunden etwa 6 Meter auseinanderlagen und dann für eine Stunde nur 2 Meter, dann liegt der Durchschnittswert nicht innerhalb der Kriterien für ein erhöhtes Risiko. Eine Umstellung auf die Nachfolgerversion des ENF (weiterhin kompatibel zu allen bisher nutzbaren Geräten) nutzt andere Algorithmen und erlaubt so eine differenziertere Betrachtung der Risikobegegnungen. Diese Umstellung auf die Nachfolgeversion erfolgt in einem der nächsten Updates.

**Comment by MikeMcC399** [comment]
@loki-cui 
This looks very good and understandable!

There is a typo in the following sentence:
"das t" should be removed, where I marked it in bold.

"Wird Ihnen ein "erhöhtes Risiko" (rot) angezeigt, sollten Sie zu Hause bleiben und Ihre direkten Kontakte reduzieren. Setzen Sie sich mit Ihrem Hausarzt, dem ärztlichen Bereitschaftsdienst unter 116117 oder dem Gesundheitsamt in Verbindung, um **das t** das weitere Vorgehen abzustimmen."

The whole article is written against the current app, so remember that the article will need to be revised as soon as the app version using ENF v2 is released.

**Comment by loki-cui** [comment]
@MikeMcC399 : thank you! So if nobody else complains, I'd like to publish this as soon as possible :) Typo is already corrected.

**Comment by daimpi** [comment]
@loki-cui (cc: @hoehleatsu) general this looks good to me 👍 🙂

I'm not entirely sure about the last explanation though: 
> **Warum erscheint keine rote Warnmeldung trotz Risikokontakt?**
> […]
> Die aktuelle Version (V1) des Exposure Notification Framework (ENF, Schnittstelle für die COVID-19-Begegnungsaufzeichnungen) berechnet den Mittelwert der Entfernung zu einem bestimmten Kontakt im Laufe des Tages. Diesen Mittelwert verwendet die Corona-Warn-App für die Risikoermittlung. Wenn die Smartphones in einem gemeinsamen Haushalt beispielsweise für 8 Stunden etwa 6 Meter auseinanderlagen und dann für eine Stunde nur 2 Meter, dann liegt der Durchschnittswert nicht innerhalb der Kriterien für ein erhöhtes Risiko.[…]

My understanding of *ENF v1 legacy mode* so far was that time is accumulated separately in the 3 respective buckets (low-mid-high attenuation) over all positive contacts (cf. Fig. 13 in the [solution architecture doc](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation)). I wasn't aware of any averaging that happens, could you elaborate a bit more on how this happens?

**Comment by daimpi** [comment]
@loki-cui on a more general note: given that ENF v1 legacy mode will soon be ditched (in CWA 1.8) and that ENF v2 works quite differently, maybe it would make sense to already fully adjust the text for the new mode and hold off with publishing those entries until CWA 1.8 is released (currently CWA 1.8 has already reached version RC 6 under iOS)? This would avoid having to do double work for entries which are only relevant for the short time window that ENF v1 legacy still has to live ^^.

**Comment by heinezen** [comment]
My only suggestions would be to trim some of the longer sentences and use present tense + active speech. This is more "engaging", especially for the longer/technical sections :)

Examples:

> Bei der Status­anzeige „un­be­kanntes Risiko“ war die Risiko-E­rmittlung noch nicht lange genug aktiv, so dass keine Risiko­-Berech­nung vor­ge­nommen werden konnte.

Bei der Status­anzeige „un­be­kanntes Risiko“ ist die Risiko-E­rmittlung noch nicht lange genug aktiv, um eine Risikoermittlung vorzunehmen.

> Wird Ihnen ein "niedriges Risiko" (grün) angezeigt, bedeutet es, dass sie Ihr Infektionsrisiko als gering einschätzt.

Zeigt die App ein "niedriges Risiko" (grün) an, schätzt sie Ihr Infektionsrisiko als gering ein.

> Zusätzlich dazu informiert die App Sie aber, dass Ihr Smartphone sehr wohl eine oder mehrere Begegnungen in den vergangenen 14 Tagen mit (später positiv getesteten) Personen aufgezeichnet hat und zeigt auch an, wie viele.

Zusätzlich informiert Sie die App darüber, ob und wie viele Begegnungen mit später positiv getesteten Personen sie in den letzten 14 Tagen aufgezeichnet hat.

----

Other than that, I see no real issues, except a more general problem with the terminology we use in the app here:

> **Ich habe in der App die Meldung bekommen, dass ich zwei Risiko-Begegnungen hatte. Die Statusanzeige ist aber grün geblieben. Muss ich mir Sorgen machen?**
> Nein, denn auf Grundlage der Daten der Risiko-Ermittlung wird das Infektionsrisiko als niedrig eingestuft, da sich die Begegnung auf einen kurzen Zeitraum und/oder einen größeren Abstand beschränkt hat. Sie müssen sich keine Sorgen machen und es besteht kein besonderer Handlungsbedarf. [...]

For someone without much technical knowledge, it might feel like a contradiction when something is called a **risk** encounter, but the FAQ basically says "This is fine. You have nothing to worry about".

**Comment by hoehleatsu** [comment]
> I'm not entirely sure about the last explanation though:
> 
> > **Warum erscheint keine rote Warnmeldung trotz Risikokontakt?**
> > […]
> > Die aktuelle Version (V1) des Exposure Notification Framework (ENF, Schnittstelle für die COVID-19-Begegnungsaufzeichnungen) berechnet den Mittelwert der Entfernung zu einem bestimmten Kontakt im Laufe des Tages. Diesen Mittelwert verwendet die Corona-Warn-App für die Risikoermittlung. Wenn die Smartphones in einem gemeinsamen Haushalt beispielsweise für 8 Stunden etwa 6 Meter auseinanderlagen und dann für eine Stunde nur 2 Meter, dann liegt der Durchschnittswert nicht innerhalb der Kriterien für ein erhöhtes Risiko.[…]
> 
> My understanding of _ENF v1 legacy mode_ so far was that time is accumulated separately in the 3 respective buckets (low-mid-high attenuation) over all positive contacts (cf. Fig. 13 in the [solution architecture doc](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation)). I wasn't aware of any averaging that happens, could you elaborate a bit more on how this happens?

I would also be rather curious how to interpret this. How exactly is one exposure defined. If I read the FAQ this means you can have a close household member, with many many episodes of contact over one day, but this is in v1 summarised into one **exposure** for a given day. As a consequence this could mean:

Close family contacts staying the night in different bedrooms and only meeting for breakfast and dinner + some chats during the day, as an average for the exposure as one entry, might fail to qualify as a risk contact?

This is IMO part of the explanation of what happened in Denmark (see press reports linked in this [issue](https://github.com/PersonalDataIO/CoronaRiskScoring/issues/21)). As also mentioned in my [blog post](https://staff.math.su.se/hoehle/blog/2020/09/17/gaen_riskscoring.html) as serious problem is that the source code of v1 of the GAEN framework is not available, so one can check what really happens...

**Comment by MikeMcC399** [comment]
This is what RKI publishes as an explanation on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html with reference to the German-language document https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/cwa-risk-assessment.de.md

![image](https://user-images.githubusercontent.com/66998419/101150164-27d42500-3620-11eb-9f45-60d4313d22dc.png)

**Comment by MikeMcC399** [comment]
The issue https://github.com/corona-warn-app/cwa-documentation/issues/453 is still open and addresses the fact that the reference English language documentation https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md is out of date regarding the introduction of onset of symptoms with the release of CWA V1.5 on October 19, 2020. The parameter onset of symptoms is not mentioned in the documentation.

The German translation https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/cwa-risk-assessment.de.md is also out of date.

If the document cwa-risk-assessment (and translation) cannot be updated in a timely manner then this proposed FAQ entry needs to explain about the changes in the risk calculation caused by use of the onset of symptoms data.

**Comment by loki-cui** [comment]
After reading through all the feedback, I amended the text as follows: 

**DE**

### Nach welchen Kriterien werden Begegnungen bewertet und wie unterscheiden sich die Handlungsempfehlungen?

Die Corona-Warn-App hat drei verschiedene Statusanzeigen: "unbekanntes Risiko" (grau), "niedriges Risiko" (grün) und "erhöhtes Risiko" (rot). 

Bei der Status­anzeige „un­be­kanntes Risiko“ ist die Risiko-E­rmittlung noch nicht lange genug aktiv, um eine Risikoermittlung vorzunehmen.
Wenn Ihnen auf Ihrem Smartphone Begegnungen mit erhöhtem oder niedrigen Risiko angezeigt werden, dann bedeutet dies, dass Ihr Smartphone und das einer Person, die sich später in der App als infiziert gemeldet hat, in den vergangenen 14 Tagen  per Bluetooth Diagnoseschlüssel ausgetauscht haben. Auf Basis verschiedener Kriterien wird diese Begegnung dann mit einem erhöhten oder geringen Infektionsrisiko eingestuft.

Zeigt die App ein "niedriges Risiko" (grün) an, schätzt sie Ihr Infektionsrisiko als gering ein. Zusätzlich dazu informiert die App Sie aber, dass Ihr Smartphone sehr wohl eine oder mehrere Begegnungen in den vergangenen 14 Tagen mit (später positiv getesteten) Personen aufgezeichnet hat und zeigt auch an, wie viele. Die App zeigt in diesem Fall folgenden Hinweis an: "Ein niedriges Risiko besteht insbesondere dann, wenn sich Ihre Begegnung auf einen kurzen Zeitraum oder einen größeren Abstand beschränkt hat. Sie müssen sich keine Sorgen machen, und es besteht kein besonderer Handlungsbedarf."

Wird Ihnen ein "erhöhtes Risiko" (rot) angezeigt, sollten Sie zu Hause bleiben und Ihre direkten Kontakte reduzieren. Setzen Sie sich mit Ihrem Hausarzt, dem ärztlichen Bereitschaftsdienst unter 116117 oder dem Gesundheitsamt in Verbindung, um das weitere Vorgehen abzustimmen. Die Entscheidung, ob ein sog. PCR-Test durchgeführt wird, obliegt in letzter Instanz Ihrem Arzt. Sowohl das [RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Buerger/Orientierungshilfe_Buerger_de.pdf?__blob=publicationFile) als auch das [Bundesministerium für Gesundheit](https://www.bundesgesundheitsministerium.de/fileadmin/Dateien/3_Downloads/C/Coronavirus/Verordnungen/Corona-Test-VO_BAnz_AT_141020.pdf) haben jedoch entsprechende Orientierungshilfen bzw. Empfehlungen veröffentlicht.

**Ich habe die Meldung bekommen, dass ich eine niedrige Risikobegegnung hatte. Am nächsten Tag war sie wieder weg. Sollte das nicht erst nach 14 Tagen gelöscht werden?**
Sobald die App die aktuellen Diagnoseschlüssel (Positivkennungen) vom Server lädt, wird eine Überprüfung des Kontaktprotokolls durchgeführt. Dabei wird für jeden der letzten 14 Tage, für den Diagnoseschlüssel vorhanden sind, eine separate Überprüfung des Kontaktprotokolls durchgeführt. Das bedeutet also, die App gleicht die Begegnungen der letzten 14 Tage mit den Positivkennungen ab, um zu überprüfen, ob es zu einem Kontakt mit einer  positiv getesteten Person gekommen ist. Ist die Meldung über eine Begegnung mit niedrigem Risiko nach einem Tag verschwunden, bedeutet das, dass die entsprechende Begegnung in diesem Fall länger als 14 Tage zurückliegt.

**Ich habe in der App die Meldung bekommen, dass ich zwei Begegnungen mit niedrigem Risiko hatte. Die Statusanzeige ist aber grün geblieben. Muss ich mir Sorgen machen?**
Nein, denn auf Grundlage der Daten der Risiko-Ermittlung wird das Infektionsrisiko als niedrig eingestuft, da sich die Begegnung auf einen kurzen Zeitraum und/oder einen größeren Abstand beschränkt hat. Sie müssen sich keine Sorgen machen und es besteht kein besonderer Handlungsbedarf. Es wird empfohlen, sich an die allgemein geltenden Abstands- und Hygieneregeln zu halten. Sie müssen sich bei Begegnungen mit niedrigem Risiko nicht testen lasten. Die Verhaltensvorschläge sowie Infos zum Ermittlungszeitraum als auch zum Infektionsrisiko finden Nutzer*innen in der App selbst, wenn sie auf „Niedriges Risiko“ mit dem Finger tippen.

**Sind neue Begegnungen bei roter Statusanzeige solche mit niedrigem oder erhöhtem Risiko?**
Wenn Sie in der aktuellen Version der App (1.7.1) eine rote Statusanzeige (erhöhtes Risiko) haben, werden alle zukünftigen Risikokontakte auch mit erhöhtem Risiko angezeigt. Das passiert auch, wenn es sich möglicherweise um Kontakte mit eigentlich niedrigem Risiko handelt. Dieses Verfahren soll in den kommenden Updates der Corona-Warn-App geändert werden.

**Werden Risikobegegnungen mit der gleichen Person mehrfach am Tag gezählt?**
Mit der aktuellen Version des Exposure Notification Frameworks (V1), der Schnittstelle für Corona-Apps von Apple und Google, wird eine Person als eine Begegnung pro Tag gezählt. 

**Wird eine Begegnung an verschiedenen Tagen mit ein und derselben Person mehrfach gezählt?** 
Ja. Mit der aktuellen Version des Exposure Notification Frameworks (V1), der Schnittstelle für Corona-Apps von Apple und Google, wird eine Person als eine Begegnung pro Tag gezählt. Das heißt: eine Person, der ich gestern und heute begegnet bin, wird als zwei Begegnungen gezählt. Ein Tag ist hierbei als Mitternacht „UTC“ bis Mitternacht „UTC“ des Folgetages definiert.


**EN**

### By which criteria are encounters evaluated and how do the recommendations for action differ?

The Corona Warn App has three different status indicators: "unknown risk" (grey), "low risk" (green) and "increased risk" (red). 

With the status display "unknown risk", the risk determination is not active long enough to perform a risk determination.
If you see high-risk or low-risk encounters on your smartphone, it means that your smartphone and that of a person who later reported themselves as infected in the app have exchanged diagnostic keys via Bluetooth in the past 14 days. Based on various criteria this encounter is then classified as having an increased or low risk of infection.

If the app shows a "low risk" (green),  the relevant threshold values have not been exceeded. Nevertheless, the app also informs you that your smartphone has recorded one or more encounters with (later positively tested) persons in the past 14 days and also shows how many. In this case, the app will display the following message: "A low risk exists in particular if your encounter was limited to a short period of time or a longer distance. You do not need to worry, and there is no particular need for action."

If you get a "increased risk" (red), you should stay at home and reduce your direct contacts. Contact your general practitioner, the medical on-call service at 116117 or the health department to discuss how to proceed. The decision whether a so-called PCR test is performed is ultimately up to your doctor. However, both the [RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Buerger/Orientierungshilfe_Buerger_de.pdf?__blob=publicationFile) and the [Federal Ministry of Health](https://www.bundesgesundheitsministerium.de/fileadmin/Dateien/3_Downloads/C/Coronavirus/Verordnungen/Corona-Test-VO_BAnz_AT_141020.pdf) have published corresponding guidelines and recommendations.

**I received the message that I had a low risk encounter. The next day it was gone again. Shouldn't this be deleted after 14 days?**
As soon as the app downloads the current diagnostic keys (positive IDs) from the server, a check of the contact log is performed. For each of the last 14 days for which diagnostic keys are available, a separate contact log check is performed. This means that the app compares the encounters of the last 14 days with the positive IDs to check whether there has been a contact with a person who tested positive. If the message about a low-risk encounter disappears after one day, this means that the corresponding encounter was more than 14 days ago in this case.

**I got the message in the app that I had two low risk encounters. But the status indicator remained green. Should I be worried?
No, because based on the data of the risk assessment, the risk of infection is considered low because the encounter was limited to a short period of time and/or a longer distance. You do not need to worry and there is no particular need for action. It is recommended to follow the generally applicable rules of distance and hygiene. You do not need to test yourself in low risk encounters. Users can find the suggested behavior as well as information about the time of detection and the risk of infection in the app itself when they tap on "Low risk" with their finger.

**Are new encounters with a red status display low risk or increased risk?
If you have a red status indicator (increased risk) in the current version of the app (1.7.1), all future risk contacts will also be shown with increased risk. This happens even if the contacts are low risk contacts. This procedure will be changed in the upcoming updates of the Corona-Warn-App.

**Are risk encounters with the same person counted several times a day?**
With the current version of the Exposure Notification Framework (V1), the interface for Corona-Apps from Apple and Google, one person is counted as one encounter per day. 

**Is an encounter on different days with one and the same person counted several times?** 
Yes, with the current version of the Exposure Notification Framework (V1), the interface for Apple's and Google's corona apps, one person is counted as one encounter per day. This means: a person I met yesterday and today is counted as two encounters. One day is defined as midnight "UTC" until midnight "UTC" of the following day.

**Comment by loki-cui** [comment]
> @loki-cui (cc: @hoehleatsu) in general this looks good to me 👍 🙂
> 
> I'm not entirely sure about the last explanation though:
> 
> > **Warum erscheint keine rote Warnmeldung trotz Risikokontakt?**
> > […]
> > Die aktuelle Version (V1) des Exposure Notification Framework (ENF, Schnittstelle für die COVID-19-Begegnungsaufzeichnungen) berechnet den Mittelwert der Entfernung zu einem bestimmten Kontakt im Laufe des Tages. Diesen Mittelwert verwendet die Corona-Warn-App für die Risikoermittlung. Wenn die Smartphones in einem gemeinsamen Haushalt beispielsweise für 8 Stunden etwa 6 Meter auseinanderlagen und dann für eine Stunde nur 2 Meter, dann liegt der Durchschnittswert nicht innerhalb der Kriterien für ein erhöhtes Risiko.[…]
> 
> My understanding of _ENF v1 legacy mode_ so far was that time is accumulated separately in the 3 respective buckets (low-mid-high attenuation) over all positive contacts (cf. Fig. 13 in the [solution architecture doc](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation)). I wasn't aware of any averaging that happens, could you elaborate a bit more on how this happens?

I actually need to foward this question to the more technical guys within this community as I'm not fully sure if I can answer this question correctly. What I can assure you, is that the text was technically proofread before I added it here.

**Comment by loki-cui** [comment]
> The issue [corona-warn-app/cwa-documentation#453](https://github.com/corona-warn-app/cwa-documentation/issues/453) is still open and addresses the fact that the reference English language documentation https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md is out of date regarding the introduction of onset of symptoms with the release of CWA V1.5 on October 19, 2020. The parameter onset of symptoms is not mentioned in the documentation.
> 
> The German translation https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/cwa-risk-assessment.de.md is also out of date.
> 
> If the document cwa-risk-assessment (and translation) cannot be updated in a timely manner then this proposed FAQ entry needs to explain about the changes in the risk calculation caused by use of the onset of symptoms data.

According to my information, the team is currently working on updating the documenation. But due to the short release cycles and fixes in between this was not feasible so far.

**Comment by MikeMcC399** [comment]
@loki-cui 
The updated German text in https://github.com/corona-warn-app/cwa-website/issues/637#issuecomment-740464337 looks (almost) good to publish! Well done!

Change
> Sie müssen sich bei Begegnungen mit niedrigem Risiko nicht testen lasten.

to
Sie müssen sich bei Begegnungen mit niedrigem Risiko nicht testen lassen.

---

For the English text:

Change
>With the status display "unknown risk", the risk determination is not active long enough to perform a risk determination.

to
With the status display "unknown risk", the risk determination has not been active long enough to perform a risk determination.

Change
> You do not need to test yourself in low risk encounters.

to
You do not need to get yourself tested after low risk encounters.

**Comment by loki-cui** [comment]
@MikeMcC399 : Thanks! Already corrected in the upper post.

**Comment by MikeMcC399** [comment]
@loki-cui 
There is now a space missing after the "." and before the "Y" in "hygiene.You".
It should be "hygiene. You".

**Comment by heinezen** [comment]
Please make all further remarks/correction requests in the new PR https://github.com/corona-warn-app/cwa-website/issues/637

----
Corona-Warn-App Open Source Team
