### ISSUE TITLE
Use WebP Images with PNG Fallback to improve performance

### ISSUE THREAD

**Issue by dannylinden** [corona-warn-app/cwa-website#64]
To create a significant reduce of loading time, bandwidth, render time we can generate WebP Images out of PNG/JPEG on the Build Process.

To support Browser without WebP support (Safari) we can still add PNG/JPEG as Fallback.

**Comment by dannylinden** [comment]
Pull Request ready for review. Homepage. e.g. for the Homepage (en) its improved the transfered data by ~34% (843kb vs 537kb)

<img width="1680" alt="webp_comparison" src="https://user-images.githubusercontent.com/5121876/84749719-8828c900-afe4-11ea-8dc9-056d3c4b3ef6.png">

**Comment by corneliusroemer** [comment]
Maintainers, your feedback is requested :) @SebastianWolf-SAP @tkowark @jakobmoellersap

**Comment by dannylinden** [comment]
Cause no feedback for 10 day, can I friendly remind? @SebastianWolf-SAP @tkowark @jakobmoellersap

**Comment by dannylinden** [comment]
Cause no feedback for 10 day, can I friendly remind? @SebastianWolf-SAP @tkowark @jakobmoellersap @corneliusroemer

**Comment by tkowark** [comment]
Yes, of course. Sorry for the delay. I will review open PRs today!
