### ISSUE TITLE
Include workaround reg. switching to new phone 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#647]
## Where to find the issue
Could be included here:
https://www.coronawarn.app/de/faq/#backup
https://www.coronawarn.app/en/faq/#backup

## Describe the issue
This FAQ Entry is not very helpful for normal users (see f.e.: https://github.com/corona-warn-app/cwa-app-ios/issues/1613) . They are left alone with the information that CWA-Data was not transferred to their new device, but the FAQ does not inform them how to solve this problem.

## Suggested change
Include:

**German**: 

>Um sicherzugehen das Sie über alle Kontakte informiert werden, ist es notwendig, dass sie auf ihrem alten Gerät die Corona-Warn App noch 14 Tage lang regelmäßig öffnen, um zu sehen, ob diese Ihnen Begegnungen anzeigt.
Sollten Sie innerhalb dieser 14 Tage positiv getestet werden, sollten Sie das Testergebnis auf beiden Geräten teilen, damit alle Kontakte informiert werden können. 
Eine Anleitung, wie sie Ihr Testergebnis auf mehreren Geräten teilen könnn, finden Sie [hier](https://www.coronawarn.app/de/faq/#test_multiple_devices).

**English** (cc @MikeMcC399):

>To make sure that you are informed about all contacts, it is necessary that you open up the Corona-Warn App on your old device regularly for 14 days to see if it shows encounters.
If you test positive within these 14 days, you should share the test result on both devices so that all contacts can be informed. For instructions on how to share your test result on multiple devices, see [here](https://www.coronawarn.app/de/faq/#test_multiple_devices).

## Additional Information
I can open a PR if these Changes are welcome.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
There is another open issue https://github.com/corona-warn-app/cwa-website/issues/411 on this topic, so please consider adding your suggestions to the existing issue and closing this one.
Certainly it is good to refer to the existing FAQ https://www.coronawarn.app/en/faq/#test_multiple_devices as you have done.

**Comment by Ein-Tim** [comment]
@MikeMcC399 
Thanks for the hint, normally I always search for Issues, this time I didn't 😅
Will close this Issue and add my proposal to this Issue.
