### ISSUE TITLE
FAQ entry: [Apple/iOS]: 'COVID-19 exposure logging... - Weekly Update'

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#650]
## Your Question

* Website URL Path: https://www.coronawarn.app/en/faq/#notif_weekly_update
* Line / Paragraph: 
* Question: Is/was there something similar on Android phones? If so, we should adapt FAQ.

**Comment by heinezen** [comment]
Not one that I know of. This type of notification was exclusive to iOS.
