### ISSUE TITLE
FAQ update Netherlands

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#655]
## Suggested change

Name of controller: Minister of Health, Welfare and Sports 
	Postal address: Postbus 16114, 2500 BC, The Hague 
	Email address: CIBG-eHealth-EU@minvws.nl or FG-VWS@minvws.nl 
	Phone number: +31703405487

**Comment by MikeMcC399** [comment]
I have logged an issue under https://github.com/corona-warn-app/cwa-app-android/issues/1872 because on one Android device (my main productive one) Netherlands is not appearing. Strangely though on another Android test device is does appear in the list. I don't have any explanation for this!
