### ISSUE TITLE
Apple made ENF available for iOS 12.5

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#665]
## Where to find the issue
F.e.: https://www.coronawarn.app/de/faq/#minimum_requirements & https://www.coronawarn.app/de/faq/#ios135

## Describe the issue
As of today, with the release of iOS 12.5, Apple made the ENF available for older iPhones.
Source: https://developer.apple.com/documentation/exposurenotification/supporting_exposure_notifications_in_ios_12_5

## Suggested change
Change any reference that Apple released the ENF with iOS 13.5 and because of this you cannot support older iPhones. 
Also, it should be clarified if you will support iOS 12.5 and if yes, the FAQ has to be updated.

When changing this, please keep in mind that:
> iOS 13.0 to 13.4 doesn’t support Exposure Notifications

So, don't just write: "iOS 12.5 and above support ENF", since this is not true...

---

## Related Issues
- https://github.com/corona-warn-app/cwa-app-ios/issues/1682
- https://github.com/corona-warn-app/cwa-website/issues/639

**Comment by MikeMcC399** [comment]
This is related to the Android issue for [FAQ: Google ENS incompatible with Android 5.0 (API 21) given as outdated reason for non-support in CWA](https://github.com/corona-warn-app/cwa-website/issues/639) https://github.com/corona-warn-app/cwa-website/issues/639.

Note also the statement from the Federal Government
https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636 
under the heading "**What are the minimum device requirements?**"

"The Federal Government has asked the companies involved to conduct a technical review with the manufacturers of the operating systems, to check whether there are further possibilities to also technically integrate older smartphones, and open the interface to them."

**Comment by Ein-Tim** [comment]
#670 confirms that we will see CWA on iOS 12.5. 

The whole FAQ has to be updated according to this. Good that we have the `[ios.minimum-required-os-version]` in the [gulpfile.js](https://github.com/corona-warn-app/cwa-website/blob/master/gulpfile.js)
