### ISSUE TITLE
Update FAQ-entry: https://www.coronawarn.app/de/faq/#encounter_criteria

### ISSUE THREAD

**Issue by loki-cui** [corona-warn-app/cwa-website#675]
## Where to find the issue
https://www.coronawarn.app/de/faq/#encounter_criteria
https://www.coronawarn.app/en/faq/#encounter_criteria

## Describe the issue
With the release 1.9.1 for iOS and Android, the text needs some minor amendments.

## Suggested change

**DE**

Die Berechnung Ihres individuellen Infektionsrisikos basiert auf folgenden Faktoren:

(1) Dauer der Begegnung
(2) Abstand bei der Begegnung
(3) Zeit, die seit der Begegnung vergangen ist
(4) Infektiosität (abgeleitet aus der Information, wann und ob die Symptome eingesetzt haben)

Überschreitet der daraus ermittelte Risikowert eine [Schwelle](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation), die das Robert Koch-Institut vorgibt, erhalten die Benutzer eine Benachrichtigung über ein erhöhtes Infektionsrisiko. 

Die Corona-Warn-App hat drei verschiedene Statusanzeigen, die dieses Infektionsrisiko verdeutlichen: "unbekanntes Risiko" (grau), "niedriges Risiko" (grün) und "erhöhtes Risiko" (rot).

Bei der Status­anzeige „un­be­kanntes Risiko“ ist die Risiko-E­rmittlung noch nicht lange genug aktiv, um eine Risikoermittlung vorzunehmen.

Wenn Ihnen auf Ihrem Smartphone Begegnungen mit erhöhtem oder niedrigen Risiko angezeigt werden, dann bedeutet dies, dass Ihr Smartphone und das einer Person, die sich später in der App als infiziert gemeldet hat, in den vergangenen 14 Tagen per Bluetooth Diagnoseschlüssel ausgetauscht haben. Auf Basis der oben genannten Kriterien wird diese Begegnung dann mit einem erhöhten oder geringen Infektionsrisiko eingestuft.

Zeigt die App ein "niedriges Risiko" (grün) an, schätzt sie Ihr Infektionsrisiko als gering ein. Zusätzlich dazu informiert die App Sie aber, dass Ihr Smartphone sehr wohl eine oder mehrere Begegnungen in den vergangenen 14 Tagen mit (später positiv getesteten) Personen aufgezeichnet hat und zeigt auch an, an wie vielen Tagen dies der Fall war. Ab der Version 1.9.1 der App sehen die Nutzer somit die Anzahl an Tagen, an denen Risikobegegnungen stattgefunden haben, und nicht mehr die Anzahl an Begegnungen. Zusätzlich wird folgender Hinweis angezeigt: "Ein niedriges Risiko besteht insbesondere dann, wenn sich Ihre Begegnung auf einen kurzen Zeitraum oder einen größeren Abstand beschränkt hat. Sie müssen sich keine Sorgen machen, und es besteht kein besonderer Handlungsbedarf."

Wird Ihnen ein "erhöhtes Risiko" (rot) angezeigt, sollten Sie zu Hause bleiben und Ihre direkten Kontakte reduzieren. Setzen Sie sich mit Ihrem Hausarzt, dem ärztlichen Bereitschaftsdienst unter 116117 oder dem Gesundheitsamt in Verbindung, um das weitere Vorgehen abzustimmen. Die Entscheidung, ob ein sog. PCR-Test durchgeführt wird, obliegt in letzter Instanz Ihrem Arzt. Sowohl das [RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Buerger/Orientierungshilfe_Buerger_de.pdf?__blob=publicationFile) als auch das [Bundesministerium für Gesundheit](https://www.bundesanzeiger.de/pub/publication/oP6RjNyQGYnROEn0YzL/content/oP6RjNyQGYnROEn0YzL/BAnz%20AT%2001.12.2020%20V1.pdf?inline) haben jedoch entsprechende Orientierungshilfen bzw. Empfehlungen veröffentlicht. Die App zeigt ab Version 1.9.1 zudem an, an welchen Tag (innerhalb der letzten 14 Tage) letztmalig eine Begegnung mit erhöhtem Risiko stattgefunden hat. Hier sehen Sie nun ein genaues Datum, um Ihre Kontakte bzw. Ihr Verhalten an diesem Tag besser nachvollziehen zu können. 

**EN**

The calculation of your individual risk is based on the following factors:

(1) duration of the encounter
(2) Distance at the time of the encounter
(3) Time that has elapsed since the encounter
(4) Infectiousness (derived from information on when and whether symptoms occur).

If the calculated risk exceeds a certain [threshold](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation) specified by the Robert Koch Institute, users will receive a notification regarding an increased risk.

The Corona Warn App has three different status indicators that indicate this risk: "unknown risk" (grey), "low risk" (green) and "increased risk" (red).

With the status display "unknown risk", the risk determination has not been active long enough to perform a risk determination.

If you see high-risk or low-risk encounters on your smartphone, it means that your smartphone and that of a person who later reported themselves as infected in the app have exchanged diagnostic keys via Bluetooth in the past 14 days. Based on the above mentiond criteria, this encounter is then classified as having an increased or low risk of infection.

If the app shows a "low risk" (green), the relevant threshold values have not been exceeded. Nevertheless, the app also informs you that your smartphone has recorded one or more encounters with (later positively tested) persons in the past 14 days and also shows on how many days this was the case. As of version 1.9.1 of the app, users will see the number of days on which risk encounters have taken place, rather than the number of encounters. In addition, the following note is displayed: "A low risk exists in particular if your encounter was limited to a short period of time or a longer distance. You do not need to worry, and there is no particular need for action."

If you get a "increased risk" (red), you should stay at home and reduce your direct contacts. Contact your general practitioner, the medical on-call service at 116117 or the health department to discuss how to proceed. The decision whether a so-called PCR test is performed is ultimately up to your doctor. However, both the [RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Buerger/Orientierungshilfe_Buerger_de.pdf?__blob=publicationFile) and the [Federal Ministry of Health](https://www.bundesanzeiger.de/pub/publication/oP6RjNyQGYnROEn0YzL/content/oP6RjNyQGYnROEn0YzL/BAnz%20AT%2001.12.2020%20V1.pdf?inline) have published corresponding guidelines and recommendations. As of version 1.9.1, the app also shows the last time (within the last 14 days) an encounter with increased risk took place. You can now see an exact date to better track your contacts or behavior on that specific day.

**Comment by MikeMcC399** [comment]
@loki-cui 
I could not find the threshold using the [link ](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation) in the sentence:

"If the calculated risk exceeds a certain [threshold ](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation) specified by the Robert Koch Institute, users will receive a notification regarding an increased risk."

Is this the same as `min-risk-score` in `app-config.yaml` referred to by the document https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md => [App Configuration, including minimum risk score](https://github.com/corona-warn-app/cwa-server/blob/master/services/distribution/src/main/resources/main-config/app-config.yaml)?

```
# min-risk-score: exposure incidents with scores lower than the value of this property will be excluded by the ExposureNotification framework.

min-risk-score: 11
```

**Comment by loki-cui** [comment]
The link was only added for information purposes. In case, some users are interested in the complex logic behind the calculation of the risk score, they can do so. If not, the word 'threshold' seems to be an appropriate word to describe that certain pre-conditions need to be fulfilled before the encounter is considered as "low" or "high".

Regarding your other question, I am not 100% sure. I would assume so, but maybe some other members or contributors can shed some more light here ;)

**Comment by MikeMcC399** [comment]
@loki-cui 
> The link was only added for information purposes. In case, some users are interested in the complex logic behind the calculation of the risk score, they can do so. If not, the word 'threshold' seems to be an appropriate word to describe that certain pre-conditions need to be fulfilled before the encounter is considered as "low" or "high".

Thank you for explaining the reasoning behind the link. If I follow a link to the word "threshold" / "Schwelle", I would expect to get exactly an explanation of the threshold, but I don't.

If you want to provide only more detail about the risk calculation in general, then I suggest linking through the words "calculation risk" / "Risikowert" instead.

The other point to consider is whether it is better to link to the documents:

- https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md
- https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/cwa-risk-assessment.de.md

which are available in English and German, instead of linking to

- https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation

 which is only available in English.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the suggestion. We will merge the PR related to release 1.9.1 and then review your suggestions. Thanks!
