### ISSUE TITLE
Feature Request: Move the App-Store-Icons to the top of the page...

### ISSUE THREAD

**Issue by ischilling** [corona-warn-app/cwa-website#70]
## Where to find the issue
Open the website under https://www.coronawarn.app/de/ or https://www.coronawarn.app/en/

## Describe the issue
The buttons for iOS and Google are on the bottom and should be, as with https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch, at least in the top region.

## Suggested change
The links should be moved to the top or at least added there in addition.

**Comment by zoellner** [comment]
And also added to the "Where can I get the app?" section in the FAQ

**Comment by tkowark** [comment]
Since the icons are sticky for the initial scrolling and very prominent when looked at on mobile devices. The team decided that  this should suffice in terms of visibility.
