### ISSUE TITLE
Make individual FAQs deeplinkable by providing IDs plus maybe link address directly copiable

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-website#71]
The FAQs https://www.coronawarn.app/en/faq/ are a great resource.

There is a lot of information. Unfortunately, it's not possible to deeplink to particular questions at the moment, since the divs don't have any unique ids.

So please add ids.

In addition, ideally at the bottom right for every question a copiable link, so that the answer can be shared when answering questions on Social Media or in Whatsapp groups.

**Comment by SebastianWolf-SAP** [comment]
Thanks for this request, fixed with 28aca5259b108d66c69010e26f9f865e089006c9 and e3b7ce442db50e457cd09d945510922162c777e9.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
