### ISSUE TITLE
BReg FAQ website English improvements needed

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#711]
## Where to find the issue
https://www.bundesregierung.de/corona-warn-app-faq-englisch referred to by the FAQ link `main_about_link` in the CWA app.

Open issues reviewed for page status date:
Wednesday, 10. February 2021

## Describe the issue
The English language version of the FAQs https://www.bundesregierung.de/corona-warn-app-faq-englisch is missing information which is contained in the German language version https://www.bundesregierung.de/corona-warn-app-faq.

- ~~No link to the Blog https://www.coronawarn.app/en/blog/~~
- ~~No link to the English language FAQs https://www.coronawarn.app/en/faq/~~
- The FAQs links are only to the German language FAQs https://www.coronawarn.app/de/faq/ and these are hidden in the individual Q&As
- ~~There is also a blog link in the text to the German blog https://www.coronawarn.app/de/blog/2020-12-28-corona-warn-app-version-1-10/~~
- ~~The text is still at the CWA app 1.7 level and is not updated to 1.9~~
- ~~Most URLs in the English text are just text and not hyperlinks~~

This is a follow-on to https://github.com/corona-warn-app/cwa-wishlist/issues/165#issuecomment-747919353.

## Suggested change

- ~~The section at the top of https://www.bundesregierung.de/corona-warn-app-faq-englisch should link directly to the English language Blog https://www.coronawarn.app/en/blog/ and English language FAQs https://www.coronawarn.app/en/faq/~~ (checked corrected on Feb 1, 2021)
- Links in the individual Q&A sections to the FAQs should refer to the English language FAQs https://www.coronawarn.app/en/faq/ 
- ~~The same for any explicit links to blog entries: these should link to the English language version e.g. https://www.coronawarn.app/en/blog/2020-12-28-corona-warn-app-version-1-10/~~ (checked corrected on Feb 1, 2021)
- ~~Technical information should be revised to reflect the state of the CWA app at the version 1.9 release level.~~ (mostly corrected Dec 23, 2020, followed by update to 1.11 checked on Feb 1, 2021 )
- ~~URLs should be converted to clickable links~~ (corrected Dec 23, 2020)
- ~~The status date at the bottom of the page, which currently says "Monday, 19. October 2020" should be updated to the date of the last edit.~~

---
Internal Tracking ID: [EXPOSUREAPP-4481](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4481)

**Comment by MikeMcC399** [comment]
https://www.bundesregierung.de/corona-warn-app-faq-englisch redirects to
https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636 and which now shows the following. The text does refers to FAQ and Blog. However these words are not hyperlinked so they are not helpful to the user.

- FAQ needs to be linked to https://www.coronawarn.app/en/faq/ 
- Blog needs to be linked to https://www.coronawarn.app/en/blog/.

![BReg_en](https://user-images.githubusercontent.com/66998419/102694303-6670fe80-4220-11eb-9137-b9544229ecce.jpg)

---
Compare to 
https://www.bundesregierung.de/corona-warn-app-faq redirecting to
https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392
which does contain correct links to (German language) FAQ and Blog.

![BReg_de](https://user-images.githubusercontent.com/66998419/102694420-3aa24880-4221-11eb-876e-99eae29d3119.jpg)

The German text does not exclude public holidays, which **are** excluded in the English text, **and** are excluded in the **German** text in the FAQs on https://www.coronawarn.app/de/faq/#who_can_help. So that is a discrepancy which should be resolved.

**Comment by dsarkar** [comment]
Alright, good points. We will raise this internally soon. Thanks, DS.

**Comment by dsarkar** [comment]
Thanks again for all the details. Added all these issues to the related ticket.

  
Best wishes,
DS

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-4481](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4481)

**Comment by MikeMcC399** [comment]
@dsarkar 
> Added all these issues to the related ticket.

Thank you! 

Also it looks like an error was made when the page https://www.bundesregierung.de/corona-warn-app-faq-englisch was updated with details for 1.9 because there are now two sections without a title that just show a ➕ sign.

![image](https://user-images.githubusercontent.com/66998419/103343453-65479900-4a8c-11eb-9ca9-6fd3225228fb.png)

**Comment by dsarkar** [comment]
@MikeMcC399, indeed, added that issue to the ticket. Thanks.

**Comment by MikeMcC399** [comment]
I'm just wondering what is happening at the Bundespresseamt who are responsible for the FAQ site which the CWA app links to.

The missing hyperlinks to the SAP-maintained Blog and FAQ are still missing in the header of the English language FAQ page as I reported in https://github.com/corona-warn-app/cwa-website/issues/711#issuecomment-748496862 more than one month ago.

![BReg_en](https://user-images.githubusercontent.com/66998419/102694303-6670fe80-4220-11eb-9137-b9544229ecce.jpg)

Without the links, the sentence "Answers from the developers (including SAP) to the most common technical questions about the Corona-Warn-App can be found in this FAQ and Blog ..." is of no use to a reader.

**Comment by GisoSchroederSAP** [comment]
After contacting the responsible person at Referat 311 – Finanzen, Wirtschaft, Digitalpolitik und Verkehr I got response the change/update was forwarded to the respective Internet/IT guys. I'm sure they will do their job, it just takes time in the public sector.

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP 
Thank you for following up with your government contacts!

I appreciate that there is a massive amount of rapidly changing information regarding [Coronavirus](https://www.bundesregierung.de/breg-de/themen/coronavirus) on the website of the Bundesregierung and I can well imagine that there might be a resource overload.

**Comment by GisoSchroederSAP** [comment]
All,
today, I sent another collection of hints regarding English FAQ  to the respective BPA department:
* Wrong or missing heading fonts
* Missing FAQ and Blog link to coronawarn.app on the English FAQ version
* Inconsistent layout in German (with line item expansion feature) and English website (without line item expansion)

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP 
Thanks to your efforts the major issues have been fixed!

**Outstanding changes needed**

On https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636, in the following sections, change https://www.coronawarn.app/de/faq/ (German language) to https://www.coronawarn.app/en/faq/ (English language):

- What are the minimum device requirements?
- How are data security and data protection ensured for the Corona-Warn-App?

**Comment by heinezen** [comment]
@MikeMcC399 Thanks. We've added these issues to our list in the Jira ticket.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Most of the original issues have been resolved. For reasons of clarity I move the remaining unresolved issue to a new entry "BReg FAQ English articles link to German CWA FAQ" https://github.com/corona-warn-app/cwa-website/issues/913 and now close this one.

The reference Internal Tracking ID: EXPOSUREAPP-4481 has also been copied over to the new issue.
