### ISSUE TITLE
FAQ: Add equivalent distances to dB levels in FAQs

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#712]
## Where to find the issue

- https://www.coronawarn.app/en/faq/#encounter_count_19
- https://www.coronawarn.app/de/faq/#encounter_count_19
- https://www.coronawarn.app/en/faq/#encounter_19_calc
- https://www.coronawarn.app/de/faq/#encounter_19_calc

## Describe the issue

Some FAQ articles explain risk calculations referring to dB levels. There is no display of dB levels in the CWA so these figures have no meaning to the majority of app users. I imagine also that most readers will not know that dB is a logarithmic scale.

## Suggested change

Add explanatory distance levels to the dB levels referred to in the FAQs.

According to https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md#procedure
in section "Procedure", 3rd paragraph:
"each dB value is associated with a particular distance".

Attenuation | Distance
--- | ---
55 dB | 1.5m
63 dB | 3m
73 dB | 8m

Alternatively, use the definitions provided by @heinezen in https://github.com/corona-warn-app/cwa-documentation/issues/484#issuecomment-781382074 and add these to the FAQs:

* <55 dB is very close
* 55-63 dB is mid-range
* 63-73 dB is far away
* \>73dB is very far away

**Comment by dsarkar** [comment]
OK, sounds good to me. Will be included.

**Comment by vaggelisdouros** [comment]
2 questions from my side:

a) can you provide the formula that translates the bluetooth signal attenuation (measured in dB) into distance (measured in meters)? In multiple cases, it is mentioned that a 73 dB attenuation corresponds to a distance of 8 meters, whereas 55 dB are translated into 1.5 meters, but i have not found the formula used or at least a reference to a paper/textbook.

b) In the updated diagram for risk calculation with enf v2, it is unclear to me how the time where the signal attenuation is between 63 dB and 73 dB is taken into account. Unless there is a typo, It seems that this signal is considered harmless and does not take part in the calculation of the weighted exposure time (even with a 0.5 coefficient), therefore i do not really understand whether the threshold is set to 73 db or 63 dB https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf

**Comment by MikeMcC399** [comment]
@vaggelisdouros 
These are good questions. I suggest you submit them as two separate questions through [documentation question](https://github.com/corona-warn-app/cwa-documentation/issues/new?labels=question&template=03_questions.md).

Note that Google states in https://developers.google.com/android/exposure-notifications/ble-attenuation-overview#distance-proxy:

**Attenuations as distance proxy**
"Attenuation is a very noisy proxy of distance. A very low attenuation indicates a very high probability of a short distance, but a high attenuation can be caused by many phenomena and is not always indicative of a long distance."

You may also find some interesting background reading in https://developers.google.com/android/exposure-notifications/ble-attenuation-overview concerning the calibration procedure for Bluetooth Low Energy (BLE).

**Comment by dsarkar** [comment]
Suggestion: Add an explanatory note at the end of both FAQs.

EN:

"
---

**Explanatory note:**
**Attenuation (dB) versus distance (m)** 

According to https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md "each dB value is associated with a particular distance:

Attenuation (dB) | Distance (m)
--- | ---
55  | 1.5 
63  | 3 
73  | 8 

"

**Comment by dsarkar** [comment]
And just for the fun of it:

![image](https://user-images.githubusercontent.com/1409741/104049170-ca199680-51e4-11eb-83ab-83bb31702c89.png)

**Comment by MikeMcC399** [comment]
@dsarkar 
> Suggestion: Add an explanatory note at the end of both FAQs.

The text would be more readable to add the equivalents in-line. For instance in https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md there is an example of how it is expressed:

"All encounters for a diagnosis key that lasted less than 10 minutes in total (regardless of how close the smartphones came during that time) or during which the smartphones were more than 8 meters (>73 dB attenuation) apart on average (regardless of how long the encounter lasted) are discarded as negligible risk."

So, for instance in https://www.coronawarn.app/en/faq/#encounter_count_19

"The signal attenuation must have been below 73dB for at least 10 minutes within the 30-minute window" might become
"The signal attenuation must have been below 73dB (equivalent to a distance of less than 8 meters) for at least 10 minutes within the 30-minute window"

**Comment by Ein-Tim** [comment]
If you add this, please write a disclaimer like this: https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md#L49

**Comment by heinezen** [comment]
I think it is better to wait for the doc updates before we add these numbers to the FAQ. The dB levels are not exactly equivalent to distances. There are **ranges** of dB levels associated with distances based on empiric research. We have to consider this before we write anything in the FAQ.

The upcoming documentation updates should address this better, so we hopefully can use a condensed version of the explanations made there.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Unfortunately there is still no updated [cwa-risk-assessment.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md) published - see https://github.com/corona-warn-app/cwa-documentation/issues/453, where the publication schedule is continually delayed.

The meaning of dB levels in the [FAQs](https://www.coronawarn.app/en/faq/) is still mostly unexplained and non-technical readers will have difficulty interpreting the information.

**Comment by dsarkar** [comment]
@heinezen @MikeMcC399 I think we can go ahead and implement @MikeMcC399's suggestion? In parenthesis approximate distances (or ranges). So far, this parameter has not been changed in the risk calculation (time has been).  Overall it will help the reader to understand better how it is done. (The non-technical inclined reader will think of music/volume/speakers if at all). So let's do it. Again, we can always specify more details later.

**Comment by heinezen** [comment]
I forgot to mirror this here, but I have answered the related questions in https://github.com/corona-warn-app/cwa-documentation/issues/484 a while ago. The answer was based on developer feedback.

In short: equivalences to distances should **not** be used.

> The translation of signal attenuation to distance is not described by an equation, i.e. there is no formula that directly calculates the distance from signal attenuation. Given examples of attentuation-distance pairs (such as 73 dB --> >8m) should be seen as guidance values. The attenuation ranges used by the app's calculation are based on empiric research that - as far as I understand - examined which attenuation intervals would indicate that devices are close enough for the transmission of the virus.
>
> * \>73dB is very far away
> * 63-73 is far away
> * 55-63 is mid-range
> * <55 is very close

**Comment by MikeMcC399** [comment]
@heinezen / @dsarkar 

The explanation should be published to the FAQs. So far, the answer has only been posted to GitHub, not to the FAQs.

**Comment by MikeMcC399** [comment]
https://www.coronawarn.app/en/faq/#encounter_19_calc
https://www.coronawarn.app/de/faq/#encounter_19_calc
are in the process of being revised through https://github.com/corona-warn-app/cwa-website/pull/1050

**Comment by MikeMcC399** [comment]
@heinezen / @dsarkar 

Could this information about the meaning of dB levels be added to the FAQs or perhaps now to the FAQ glossary?

>The translation of signal attenuation to distance is not described by an equation, i.e. there is no formula that directly calculates the distance from signal attenuation. Given examples of attentuation-distance pairs (such as 73 dB --> >8m) should be seen as guidance values. The attenuation ranges used by the app's calculation are based on empiric research that - as far as I understand - examined which attenuation intervals would indicate that devices are close enough for the transmission of the virus.
>
>\>73dB is very far away
63-73 is far away
55-63 is mid-range
<55 is very close
