### ISSUE TITLE
Add "Enhancement" and "Feature" labels to website issues

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-website#72]
Right now there's only "Bug", "Question" and "Anything else" available as labels for website issues.

I had enhancement/feature requests but couldn't label them appropriately.

Please add these two labels as they exist on the app repos.

**Comment by ischilling** [comment]
Same for me, which is why I just added "Feature Request" to my issues headline meanwhile.

**Comment by tkowark** [comment]
Closed with 608096d9870ea16c061e2a5a07c0cc73efeb38e6
