### ISSUE TITLE
`encounter_but_green` FAQ entry needs update

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#720]
## Where to find the issue
https://www.coronawarn.app/de/faq/#encounter_but_green
https://www.coronawarn.app/en/faq/#encounter_but_green

## Describe the issue
Parts of this FAQ entry are outdated since the release of CWA 1.9.1 which upgraded to v2 of ENF/ENS.

>together with the harmless encounters from above - will be shown in the Corona-Warn-App

This is not true anymore (see [this](https://github.com/corona-warn-app/cwa-app-ios/issues/1703#issuecomment-746834311) comment from @thomasaugsten. With v2 of ENF/ENS encounters which are not relevant get filtered out by the App and are not shown to the user).

## Suggested change
Update the FAQ entry. This is very important since users with Low-Risk encounters will see a link in the App which brings them to this entry.

**Comment by heinezen** [comment]
Addressed in #727 with a further clarification that the harmless encounters ae filtered out.
