### ISSUE TITLE
FAQ: Missing text in English error message for [Apple/iOS]: ENErrorDomain-Error 13

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#726]
## Where to find the issue
**[Apple/iOS]: ENErrorDomain-Error 13**
https://www.coronawarn.app/en/faq/#ENError13 

## Describe the issue
The English error message in https://www.coronawarn.app/en/faq/#ENError13 is still incorrectly rendered as:
"Error 13: Your exposure to today has already been carried out. Please try again in 24 hours."

whereas, according to the original post #713 it should be:
"Error 13: Your exposure logging for today has already been carried out. Please try again in 24 hours."

This is a follow-on from the closed issue #715.

## Suggested change
Replace the error message in https://www.coronawarn.app/en/faq/#ENError13 by
"Error 13: Your exposure logging for today has already been carried out. Please try again in 24 hours."

**Comment by heinezen** [comment]
Fixed in https://github.com/corona-warn-app/cwa-website/pull/728. Sry for missing this detail.
