### ISSUE TITLE
GDPR and BDSG compliance not given on Homepage of Corona Warn App

### ISSUE THREAD

**Issue by ischilling** [corona-warn-app/cwa-website#73]
Homepage: https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch

I am sure this issue is wrongly placed here - on the other hand I hope this is the short way; I just tried for an hour to figure out who is responsible for the homepage, but as so often in Germany, no one seems to be responsible.

## Where to find the issue
https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch 

## Describe the issue
There are social network icons wrongly placed on the homepage which do ! send referrer information to its owners, here twitter, facebook, instagram and youtube, also they definitely transfer the visitors IP on the social networks servers, ready for analysis..

It shouldn't be news that this wasn't nor isn't allowed under BDSG nor GDPR and its predecessors.

These social buttons **have to be explicit turned on by a user** **and** the **user must explictly accept** this **before** the buttons are activated.

I think, in times were we discuss months about data security regarding our Corona Warn App, such a (minor) flaw shouldn't happen. Nor should it start a new discussion like 'if they do not protect data here, how should this be the case for the app... Alu heads even might find this good for a new 'the theory'...

At least, it seems as if the icons are not downloaded directly from facebook & co, but still, the information given about the "consequences" by clicking them is in this form not right.

## Suggested change
2014, 6 years ago, heise.de started a project [c't shariff](https://www.heise.de/newsticker/meldung/c-t-entwickelt-datenschutzfreundliche-Social-Media-Buttons-weiter-2466687.html) that handles this issue (btw. that was two years before GDPR ;).

I suggest to implement the  current version of this project or similar projects, of which you can easily find several.

**Comment by corneliusroemer** [comment]
Yeah definitely wrong here. Tried Impressum? Surely there's a webmaster. Not that they will do anything about it.

It would help if you linked supporting evidence for your claim that "These social buttons have to be explicit turned on by a user and the user must explicitly accept this before the buttons are activated."

**Comment by hangy** [comment]
You could try a mail to the person responsible for data security (datenschutzbeauftragte@bpa.bund.de).

**Comment by tkowark** [comment]
Yep, please use the respective channels for the page (e.g., the mail from the imprint). Since the coronawarn.app site hopefully does not have these issues, I'll close that ticket.
