### ISSUE TITLE
FAQ entries (`minimum_requirements` & `#ios135`) are outdated

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#737]
## Where to find the issue
https://www.coronawarn.app/en/faq/#minimum_requirements & https://www.coronawarn.app/en/faq/#ios135
https://www.coronawarn.app/de/faq/#minimum_requirements & https://www.coronawarn.app/de/faq/#ios135

## Describe the issue
English `minimum_requirements` entry is contradictory in itself:
>The Exposure Notification API was introduced with iOS 13.5, so your operating system needs to be iOS 13.7 or higher.

This entry also needs to be update so that it says that iOS 13.7 or higher is necessary.

German `minimum_requirements` entry says that the ENF was introduced with iOS 13.7, what is not true: 
>Die Version des Betriebssystems muss iOS 13.7 oder höher sein, da mit dieser Version die Exposure Notification API eingeführt wurde.

---

`#ios135` says that iOS 13.6 or higher is required, it needs to be update so that it says that iOS 13.7 or higher is required.

(Source for iOS 13.7: https://apps.apple.com/de/app/corona-warn-app/id1512595757)

---
Internal Tracking ID: [EXPOSUREAPP-4479](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4479) (RKI)
Internal Tracking ID: EXPOSUREAPP-4481 (Bundesregierung)

**Comment by MikeMcC399** [comment]
The FAQ linked to by the app i.e. https://www.bundesregierung.de/corona-warn-app-faq-englisch says:
"The app runs on iOS smartphones from the iPhone 6s upwards using iOS 13.5, and on Android-based smartphones from Android 6 upwards."

The RKI page https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html also quotes iOS 13.5:

Aktuell kann die Corona-Warn-App auf den folgenden Betriebssystemen installiert werden:
...
iOS: ab iOS 13.5: Die App läuft auf iOS-Smartphones ab dem iPhone 6s. Die Version des Betriebssystems muss iOS 13.5 oder höher sein, da mit dieser Version die Exposure Notification API eingeführt wurde.

The App Store https://apps.apple.com/de/app/corona-warn-app/id1512595757 requires a higher iOS version
Kompatibilität Erfordert iOS 13.7 oder neuer. Kompatibel mit iPhone.

So, depending where you look, you may be good with iOS 13.5, or perhaps 13.6 or even 13.7. 😕

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks for the hint! I was not aware that they changed the required iOS Version to 13.7... 
As you probably know, the information in the App Store is correct and also the most important one (AppStore will block downloads from users how are not running iOS 13.7 or higher)

The RKI page is out of scope for me, but I will change this Issue.

**Comment by dsarkar** [comment]
@MikeMcC399, @Ein-Tim ok, thanks! We will cross-check this information. DS

**Comment by dsarkar** [comment]
Internal Tracking ID: EXPOSUREAPP-4479 (RKI)
