### ISSUE TITLE
[Blog] RSS/Atom feed

### ISSUE THREAD

**Issue by darkdragon-001** [corona-warn-app/cwa-website#740]
## Where to find the issue
/de/blog

## Describe the issue
I would like to follow your blog with my RSS reader. There is no RSS/Atom feed linked in the metadata of the html website.

## Suggested change
Create RSS feed (XML version of the articles) and link it in `<head>` via `<link rel="alternate" type="application/rss+xml" title="RSS" href="/feed.xml">`.

**Comment by Ein-Tim** [comment]
Hey @darkdragon-001 👋🏻

Thank you for your proposal.
For feature request, we normal use the [CWA-Wishlist Repository](https://github.com/corona-warn-app/cwa-wishlist). 
In this repository, we also already have a open Issue requesting this: https://github.com/corona-warn-app/cwa-wishlist/issues/237.

Please follow up there if necessary or monitor it for any updates and close this Issue 👍



Stay safe and healthy!
