### ISSUE TITLE
FAQ: Consent field number changed on form 10C/OEGD to Field 8

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#748]
## Where to find the issue
First paragraph of English / German FAQs:

https://www.coronawarn.app/en/faq/#qr_test
**I have scanned a QR code, but the test result could not be retrieved for days.**

"If you have scanned your QR code into the App after a Corona test and do not receive a test result via the App within a few days, it is possible that the respective laboratory is not yet fully cooperating with the Corona-Warn-App or the field 9 'Consent of the insured person to transmit the test result for the purpose of the Corona-Warn-App' has not been ticked in the form."

https://www.coronawarn.app/de/faq/#qr_test
**Ich habe einen QR Code eingescannt, aber das Testergebnis konnte über Tage nicht abgerufen werden.**

"Sofern Sie nach einem Corona-Test Ihren QR-Code in die App eingescannt haben und innerhalb von wenigen Tagen kein Testergebnis über die App mitgeteilt bekommen, könnte es sein, dass das entsprechende Labor noch nicht vollständig mit der Corona-Warn-App zusammenarbeitet oder das Feld 9 'Einverständnis des Versicherten zum Übermitteln des Testergebnisses für Zwecke der Corona-Warn-App' im Formular nicht markiert wurde."

## Describe the issue
The FAQ article refers to:
- Feld 9 'Einverständnis des Versicherten zum Übermitteln des Testergebnisses für Zwecke der Corona-Warn-App' (German)
- field 9 'Consent of the insured person to transmit the test result for the purpose of the Corona-Warn-App' (English)

The field is now numbered 8, not 9, however the field numbering is not seen by the CWA app user.

The text in German on the Form is:
- Das Einverständnis des Versicherten zum Übermitteln des Testergebnisses für Zwecke der Corona-Warn-App auf den vom RKI betriebenen Server wurde erteilt. (10C) or
- Das Einverständnis des Getesteten zum Übermitteln des Testergebnisses für Zwecke der Corona-Warn-App auf den vom RKI betriebenen Server wurde erteilt. (OEGD)
so the person can be either a "Versicherter" or a "Getesteter" which is not reflected in the FAQ.

There is no English text on either of the forms. Enclosing the consent text in quotes in the FAQ makes it look like this is a literal quote from an English language form.

## Suggested change
- Remove the field number (9) reference in the FAQ.
- Change quote regarding the exact text to descriptive text regarding consent.

### English text suggestion

"If you scanned your QR code into the App after a Corona test and did not receive a test result via the App within a few days, it is possible that the respective laboratory is not fully linked with the Corona-Warn-App or the consent field was not ticked on the test submission form to the laboratory to allow it to transmit the test result to the Corona-Warn-App."

### German text suggestion

"Sofern Sie nach einem Corona-Test Ihren QR-Code in die App eingescannt haben und innerhalb von wenigen Tagen kein Testergebnis über die App mitgeteilt bekommen, könnte es sein, dass das entsprechende Labor noch nicht vollständig mit der Corona-Warn-App zusammenarbeitet oder die Übermittlungsfreigabe des Testergebnisses an die Corona-Warn-App über das entsprechende Feld im Laborauftragsformular zum Testen nicht erteilt wurde."

## References

Kassenärztliche Bundesvereinigung - Ausfuellhilfe.zip
`ftp://ftp.kbv.de/ita-update/Blankoformulare/10C_OEGD/Ausfuellhilfe.zip`
=> elektronische Ausfuellhilfe_MU 10C.pdf and elektronische Ausfuellhilfe_OEGD.pdf

[elektronische Ausfuellhilfe_MU 10C.pdf](https://github.com/corona-warn-app/cwa-website/files/5759999/elektronische.Ausfuellhilfe_MU.10C.pdf)
[elektronische Ausfuellhilfe_OEGD.pdf](https://github.com/corona-warn-app/cwa-website/files/5760000/elektronische.Ausfuellhilfe_OEGD.pdf)

**Comment by heinezen** [comment]
I would still include the name of the submission form, so that the patient has some indication on what to ask for (if they would want to invvestigate this with their doctor). Otherwise I think the suggestions are good 👍 

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 
> I would still include the name of the submission form ...

The names of the two forms are 10C and OEGD. Do you want to name the forms now? They were not named before.

Because the consent field is not numbered on either of the printed forms I suggested not using the field number as a reference. 

Below is the 10C form from `ftp://ftp.kbv.de/ita-update/Blankoformulare/10C_OEGD/Muster.zip`
![KBV_10C_MUSTER_1 2021](https://user-images.githubusercontent.com/66998419/103671013-a3582780-4f7a-11eb-8393-0eb9e1e0dd9e.jpg)

---
and the OEGD form from the same source as above.

![KBV_OEGD_MUSTER_1 2021](https://user-images.githubusercontent.com/66998419/103671510-4d37b400-4f7b-11eb-8984-05381ee50d75.jpg)

**Comment by heinezen** [comment]
The forms also have version numbers, but I don't think we need those. There is always a consent field.

I have changed you text suggestion slightly with mention of the forms

> If you scanned your QR code into the App after a Corona test and did not receive a test result via the App within a few days, it is possible that 
> * the respective laboratory is not fully linked with the Corona Warn App backend
> * the consent field allowing the transmit of the test result to the Corona-Warn-App was not ticked on the submission form (10C/OEGD) sent by your doctor to the laboratory.

**Comment by MikeMcC399** [comment]
@heinezen 
That looks very good.
Just one point, "transmit" should be "transmission" in

"... the consent field allowing the transmit ..."

**Comment by heinezen** [comment]
@MikeMcC399 Fixed in the PR :)

https://github.com/corona-warn-app/cwa-website/pull/766

**Comment by MikeMcC399** [comment]
@heinezen 
LGTM ✔️ 🙂
