### ISSUE TITLE
FAQ: Advice to check test submission form practicable?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#749]
## Where to find the issue
Second paragraph of English / German FAQs:

https://www.coronawarn.app/en/faq/#qr_test
**I have scanned a QR code, but the test result could not be retrieved for days.**

"Please check whether the laboratory with which the doctor or the test center works is connected to the Corona-Warn-App and whether field 9 is checked on the form. Only then is it ensured that the procedure used works with the Corona-Warn-App."

https://www.coronawarn.app/de/faq/#qr_test
**Ich habe einen QR Code eingescannt, aber das Testergebnis konnte über Tage nicht abgerufen werden.**

"Erkundigen Sie sich daher bitte, ob das Labor, mit dem der Arzt oder das Testcenter zusammenarbeiten an die Corona-Warn-App angebunden ist und Feld 9 auf dem Formular angekreuzt ist. Nur dann ist sichergestellt, dass das genutzte Verfahren mit der Corona-Warn-App funktioniert."

## Describe the issue
The FAQ advises to check the test submission form. The situation described by the FAQ is that the user has been waiting for days for a test result to be shown in the app. 

According to the documentation on the KBV server `ftp://ftp.kbv.de/ita-update/Blankoformulare/10C_OEGD`, the forms are split into a laboratory part and a patient part. Presumably the patient would never receive the laboratory part and therefore will not be able to check the consent field. There is no consent field on the patient part of the form.

The second paragraph of the quoted FAQ also refers to the field 9 of the forms which has now changed to field 8 (see https://github.com/corona-warn-app/cwa-website/issues/748).

## Suggested change
- Remove the reference to checking the form in the second paragraph.

## References

Kassenärztliche Bundesvereinigung - Formular Muster
`ftp://ftp.kbv.de/ita-update/Blankoformulare/10C_OEGD/Muster.zip`

[Muster_10Ca_E (1_2021).pdf](https://github.com/corona-warn-app/cwa-website/files/5760091/Muster_10Ca_E.1_2021.pdf)
[Muster_10Cb_E (1_2021).pdf](https://github.com/corona-warn-app/cwa-website/files/5760092/Muster_10Cb_E.1_2021.pdf)
[Muster_OEGDa_E (12_2020).pdf](https://github.com/corona-warn-app/cwa-website/files/5760093/Muster_OEGDa_E.12_2020.pdf)
[Muster_OEGDb_E (12_2020).pdf](https://github.com/corona-warn-app/cwa-website/files/5760094/Muster_OEGDb_E.12_2020.pdf)

**Comment by dsarkar** [comment]
@MikeMcC399, Thanks. I see more or less what you are  saying. If I read it this way: "Erkundigen Sie sich daher bitte, ob ... Feld 9 auf dem Formular angekreuzt ist." it sounds ok. the "und" serperates it maybe too far from "Erkundigen". 

Suggestion:

"Erkundigen Sie sich daher bitte, ob das Labor, mit dem der Arzt oder das Testcenter zusammenarbeiten an die Corona-Warn-App angebunden ist. **Ausserdem,  fragen Sie bitte nach, ob das Feld 9 (alteres Form-Blatt) bzw. Feld 8 (aktuelles Form-Blatt)  auf dem Formular angekreuzt ist. Mit diesem Kreuz geben Sie das Einverständnis zum Übermitteln des Testergebnisses für Zwecke der Corona-Warn-App auf den vom RKI betriebenen Server.** 
Nur dann ist sichergestellt, dass das genutzte Verfahren mit der Corona-Warn-App funktioniert."


Furthermore, I suggest we add the following:

"
Bitte wenden Sie sich an uns, sollte sich dabei z.B: herausstellen, dass
- das Labor nicht angebunden ist
- sie zwar ein Test-Ergebnis vorliegen haben, aber die Corona-Warn-App dieses Test-Ergebnis nicht übermittelt hat  

Sie haben folgende Möglichkeiten uns zu kontaktieren:
- Hotline ...
- E-mail ...
- GitHub issue 400
 "

**Comment by MikeMcC399** [comment]
@dsarkar 
This issue needs to be read together with "FAQ: Consent field number changed on form 10C/OEGD to Field number 8" https://github.com/corona-warn-app/cwa-website/issues/748 where I suggested removing any direct reference to a field number on the form, so we probably need to discuss the outcome of #748 first.

I like the suggestion about giving some way to report back issues  about problems with the QR code transmission. Would the RKI email-address mailto:CoronaWarnApp@rki.de be good for that type of feedback?

**Comment by dsarkar** [comment]
> so we probably need to discuss the outcome of #748 first.

ok! 

> Would the RKI email-address mailto:CoronaWarnApp@rki.de be good for that type of feedback?

Will check internally.

**Comment by MikeMcC399** [comment]
@dsarkar 
If the advice in you posted is now standard, then it should be added to the FAQ.

![1](https://user-images.githubusercontent.com/1409741/104491439-88b52c80-55d2-11eb-8dbc-408b9e75528d.jpg)

**Comment by MikeMcC399** [comment]
@dsarkar 
There is a related post from @GisoSchroederSAP in https://github.com/corona-warn-app/cwa-wishlist/issues/270#issuecomment-760971411 so it would be good to get the information about how to provide feedback on QR process issues published into the FAQ.

**Comment by heinezen** [comment]
We solved this in https://github.com/corona-warn-app/cwa-website/pull/766 and https://github.com/corona-warn-app/cwa-website/pull/811 didn't we? Or is there still something missing? @MikeMcC399 

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 

If the Open Source Team wants to get feedback about a successful QR Code scan which doesn't result in a test result being delivered to the CWA, then there should be a paragraph added to "I have scanned a QR code, but the test result could not be retrieved for days." https://www.coronawarn.app/en/faq/#qr_test to describe how to give feedback.

The other FAQ article "I get an error while scanning the QR code. What can I do?" https://www.coronawarn.app/en/faq/#qr_scan, which describes how to give feedback, is only for a scan failure, not for scan success followed by no test result delivery.

**Comment by heinezen** [comment]
@MikeMcC399 I made https://github.com/corona-warn-app/cwa-website/pull/832 that adds this to the FAQ. Please check if I addressed that correctly :)

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 
#832 LGTM and I put some additional comments into the PR. Thank you!
