### ISSUE TITLE
Missing information that the GAP design itself is vulnerable to profiling and possibly de-anonymizing infected persons

### ISSUE THREAD

**Issue by eyecatchup** [corona-warn-app/cwa-website#75]
There are several privacy-related FAQ on the website, such as "Können die übermittelten Informationen zu mir und meinen früheren Aktivitäten zurückverfolgt werden?". Unfortunately, the answer to this particular question is not complete, in my honest opinion.

Since there is [empirical evidence in real-world scenarios](https://arxiv.org/pdf/2006.05914.pdf), that the GAP Exposure Notification API itself is a source of risk, I would expect, to be fully transparent, a hint in the FAQ, that **the current GAP design _is_ in fact vulnerable to profiling and possibly de-anonymizing infected persons**.

**Comment by eyecatchup** [comment]
I understand, that it's not a great selling point. However, you should be 100% transparent and I think you're not. No feedback at all? @SebastianWolf-SAP @tkowark

**Comment by tkowark** [comment]
Dear @eyecatchup ,

thanks for your concerns and sorry for the delay in response.

Regarding the article you cited, we'd like to answer the following:

As developers of the Corona-Warn-App, we are in constant exchange with the developers of the technologies that the app is based on - that, of course, includes security of the solution.
These technologies are amongst others the Exposure Notification API or Bluetooth and have been implemented by the respective vendors in their mobile operating systems Android and iOS.

Based on this exchange, for example with Google, we can say that nothing that is implemented in this article changes Googles assessment that the Exposure NotificationAPI is more secure than alternative solutions and they have considered many sophisticated, hypothetically possible cyber attacks in its design.

The referenced article further is a pre-print that does not conclusively consider factors such as likelihood of success or required effort. We'd like to point you to [this Twitter thread](https://twitter.com/pavel23/status/1271881305614057474), that focuses on exactly these factors.

We ask the community to report potential vulnerabilities in the underlying technologies, such as the Exposure Notification API, directly to the respective vendors to guarantee a direct flow of information and allow for timely fixes of potential issues.

Best regards,
TK
Corona-Warn-App Open Source Team
