### ISSUE TITLE
FAQ: Missing mention of 116117 app and website for Corona Test

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#751]
## Where to find the issue
https://www.coronawarn.app/en/faq/#encounter_criteria
<b>By which criteria are encounters evaluated and how do the recommendations for action differ?</b>

## Describe the issue
Only the phone number 116117 is mentioned in the [FAQ article](https://www.coronawarn.app/en/faq/#encounter_criteria), not the [www.116117.de](https://www.116117.de/de/index.php) website nor the Apple and Google apps 116117.app

https://www.coronawarn.app/en/faq/#encounter_criteria "By which criteria are encounters evaluated and how do the recommendations for action differ?" says:

"If you get a "increased risk" (red), you should stay at home and reduce your direct contacts. Contact your general practitioner, <b>the medical on-call service at 116117</b> or the health department to discuss how to proceed."

### Website www.116117.de

is a German-language website: Patientenservice 116117: [www.116117.de](https://www.116117.de/de/index.php) 
which contains links via https://www.116117.de/de/coronavirus.php#content753 to book a Corona test.

### Apple and Google 116117.app

The [www.116117.de](https://www.116117.de/de/index.php) website advertises the "App des Patientenservice" for download:

- [116117.app on App Store](https://apps.apple.com/de/app/116117-app/id1465237675) for Apple iOS
- [116117.app on Google Play Store](https://play.google.com/store/apps/details?id=de.kvdigital.nfa) for Android

The app has a special button for Corona Test.
![116117app_Main](https://user-images.githubusercontent.com/66998419/103515577-4885d980-4e6f-11eb-9326-7ebc2da02095.jpg)

---
![116117app_Terminbuchung](https://user-images.githubusercontent.com/66998419/103515588-4c196080-4e6f-11eb-903c-0f49008dea4b.jpg)

## Suggested change
Add a reference to the website www.116117.de and to the two 116117.apps to the FAQs. Either:
- to the existing FAQ articles https://www.coronawarn.app/en/faq/#encounter_criteria and https://www.coronawarn.app/de/faq/#encounter_criteria or
- in a separate new FAQ article covering the Patientenservice 116117

or perhaps both.

Note that both the website and the app display only in the German language.

**Comment by heinezen** [comment]
I have added the information in https://github.com/corona-warn-app/cwa-website/pull/752 . A new FAQ entry is not necessary I think, but I expanded the entry https://www.coronawarn.app/de/faq/#encounter_criteria with one sentence:

**German**
> Sie können zudem die Webseite oder die App (Play Store, App Store) des ärztlichen Bereitschaftsdienstes nutzen, um direkt einen Termin zu vereinbaren.

**English**
> You can also book appointment's directly via the 116117 on-call service's website or app (Play Store, App Store).
