### ISSUE TITLE
FAQ: New status setting for consent to share test result

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#753]
## Your Question

CWA Version 1.9.1 introduced new logic concerning registering a test and consenting in advance to sharing results. 

**Should this be explained in the FAQs?**

---
The blog post https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/ mentioned the changes without giving details:

"In addition, the **process** from scanning the QR code of a test result to sharing the diagnosis keys has been improved in order to **encourage more users** to share their diagnosis keys and warn others with their positive test result. The developers are working with Google and Apple to further improve and optimize this process."

---
Before registering a test using a QR code the following screen is displayed:
![Consent when registering test](https://user-images.githubusercontent.com/66998419/103682650-72332380-4f89-11eb-9a35-ee89f6a96729.jpg)

---
After granting consent by tapping "AGREE" the user has not only registered their test, they have also pre-approved sharing a positive result.

The consent to share a positive result can be withdrawn and there is a new slider in the UI to control this status:

![Warn others consent setting](https://user-images.githubusercontent.com/66998419/103682996-e8378a80-4f89-11eb-8371-c131ef037bf4.jpg)

**Comment by MikeMcC399** [comment]
When an Android user scans a QR code they will be shown a Google dialog "Notify others if you test positive?" which sets the Google status "Automatically notify others". See [Google Exposure Notification release notes, v1.8, January 2021](https://developers.google.com/android/exposure-notifications/release-notes#v18_january_2021). The Google status stays set even if consent is withdrawn in CWA. The Google status can be changed directly in the Google UI.

![Automatically notify others](https://user-images.githubusercontent.com/66998419/111291856-e6eca300-8647-11eb-9e71-b43cf76b56c5.jpg)

**Comment by Ein-Tim** [comment]
Is there any development on this issue? It wasn't even mirrored to JIRA. Perhaps @dsarkar want to pick this up? 

Enjoy Saturday!

**Comment by MikeMcC399** [comment]
Closing, since this functionality is no longer new and there has been no negative feedback on it in GitHub since introduction. It was part of the 1.9.1 release from December 2020.

Also, there has been no reaction from the Open Source Team.
