### ISSUE TITLE
Remove +49 from 0800 numbers

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#755]
not international number
Stand by for an internatinal number

https://www.coronawarn.app/de/faq/#qr_test
https://www.coronawarn.app/de/faq/#available_languages
https://www.coronawarn.app/de/faq/#QRcodes
https://www.coronawarn.app/de/faq/#test_in_other_country

**Comment by MikeMcC399** [comment]
+49 800 numbers are also listed at the bottom of
https://www.coronawarn.app/en/ and https://www.coronawarn.app/de/

**Comment by dsarkar** [comment]
@MikeMcC399 ok, thanks
