### ISSUE TITLE
FAQ remove test_in_other_country 

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#760]
## Suggested change

Remove /#test_in_other_country 
0800 not international number. Standby for new FAQ and tel number.

https://www.coronawarn.app/de/faq/#test_in_other_country
https://www.coronawarn.app/en/faq/#test_in_other_country

**Comment by dsarkar** [comment]
Remove:

                    {
                        "title": "Can I enter positive test results from other countries?",
                        "anchor": "test_in_other_country",
                        "active": true,
                        "textblock": [
                            "If you are in another EU country or in one of <a href='https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Tests.html' target='_blank' rel='noopener noreferrer'>these countries</a> and have made a molecular biological test (PCR test) which is positive, you can upload it to the Corona-Warn-App. To do so, it is necessary to verify your identity by calling the hotline 0800 7540002. You will receive a 10-digit TAN with which the test result can be registered in the app. Attention: The TAN is only valid for one hour!"
                        ]
                    },

**Comment by dsarkar** [comment]
Remove:

                    {
                        "title": "Kann ich positive Testergebnisse aus anderen Ländern eingeben?",
                        "anchor": "test_in_other_country",
                        "active": true,
                        "textblock": [
                            "Wenn Sie sich im EU-Ausland oder in einem <a href='https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Tests.html' target='_blank' rel='noopener noreferrer'>dieser Staaten</a> befinden und dort einen molekularbiologischen Test (PCR-Test) gemacht haben, der positiv ist, können Sie diesen in Ihrer Corona-Warn-App hochladen. Dafür müssen Sie sich unter der Hotline 0800 7540002 verifizieren lassen. Sie erhalten eine 10-stellige TAN, mit der das Testergebnis in der App registriert werden kann. Achtung: Die TAN ist nur eine Stunde gültig!"
                        ]
                    },

**Comment by MikeMcC399** [comment]
@dsarkar / @loki-cui 
It is not so good to just delete this section without explanation. If somebody clicks on a link https://www.coronawarn.app/en/faq/#test_in_other_country or https://www.coronawarn.app/de/faq/#test_in_other_country to this section which has been saved somewhere else, like in a GitHub issue, they will just end up in the FAQ section with all the titles showing and no text.

If the instructions are currently not valid then it would be better to add a line at the top of the existing section saying that the instructions are currently not correct and will soon be revised.

What has gone wrong with the international use of the 0800 7540001 / 7640002 numbers by the way? Was it a technical or organisational problem to limit the use to calls from Germany? The 0800 that the Deutsche Telekom offers can be made available internationally.

**Comment by dsarkar** [comment]
@MikeMcC399 

Suggestion:

Add a sentence at the top:

"
UPDATE: 
Note that currently, the hotline 0800 7540002 (as well as hotline 0800 7540001) can only be reached from Germany. We will update you soon with any further developments on this issue.
"

**Comment by MikeMcC399** [comment]
@dsarkar 

Your text is the best way to inform users at this time. Thank you for taking on my suggestion. 🙂

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for pointing the problem with removing the entire FAQ entry!

DE suggestion:

"
AKTUELL:
Bitte beachten Sie, dass zur Zeit die Hotline 0800 7540002 (sowie die Hotline 0800 7540001) nur von Deutschland aus erreicht werden kann. Wir werden sie zeitnah über Neuigkeiten zu dieser Anlegelenheit informieren.
"

**Comment by MikeMcC399** [comment]
@dsarkar 
>Thanks for pointing the problem with removing the entire FAQ entry!

You are very welcome!

There are two typos in the German text:

Wir werden sie ...
=> Wir werden Sie ...
Anlegelenheit 
=> Angelegenheit

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks!
