### ISSUE TITLE
Blog post December 17, 2020 note: Number of transmission risk level

### ISSUE THREAD

**Issue by Ben220** [corona-warn-app/cwa-website#765]
## Where to find the issue
https://github.com/corona-warn-app/cwa-website/blob/master/blog/2020-12-17-risk-calculation-enf-2-0/index.md
https://github.com/corona-warn-app/cwa-website/blob/master/blog/2020-12-17-risk-calculation-enf-2-0/index_de.md

## Describe the issue
Mention of only VII (7) transmission risk level instead of VIII (8), while the nomalized risk factor is given as 0.6 to 1.6 (Division by 5) acc. to the linked diagram: 
https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf

This holds true for the English as well as the German version of the blogpost. 

## Suggested change
Changing the number of transmission risk level to VIII (8).

---
[EXPOSUREAPP-4529](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4529)

**Comment by MikeMcC399** [comment]
@Ben220 
It looks like you found a typo! It also affects the same description which can be found on:

https://www.coronawarn.app/en/faq/#encounter_19_calc
"Based on the transmission risk level (III to **VII**), only a factor between 0.6 and 1.6 is determined."
should be changed to
"Based on the transmission risk level (III to VIII), only a factor between 0.6 and 1.6 is determined."
 
https://www.coronawarn.app/de/faq/#encounter_19_calc
"Basierend auf dem Transmission Risk Level (III bis **VII**) wird nur ein Faktor zwischen 0,6 und 1,6 ermittelt."
which should be changed to
"Basierend auf dem Transmission Risk Level (III bis VIII) wird nur ein Faktor zwischen 0,6 und 1,6 ermittelt."

**Comment by dsarkar** [comment]
Dear @Ben220, @MikeMcC399,

Thank you for your contributions.

We have created a ticket for the bug (Internal Tracking ID: EXPOSUREAPP-4529) in the internal Jira system. Before changing, I asked for feedback, but seems a typo.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
[PR](https://github.com/corona-warn-app/cwa-website/pull/788) fixing this, ready to merge, when you got feedback @dsarkar.

**Comment by dsarkar** [comment]
@Ben220,  @MikeMcC399, @Ein-Tim,

https://github.com/corona-warn-app/cwa-website/blob/master/blog/2020-12-17-risk-calculation-enf-2-0/index.md
https://github.com/corona-warn-app/cwa-website/blob/master/blog/2020-12-17-risk-calculation-enf-2-0/index_de.md

have been updated.


I think we can close this issue.

**Comment by dsarkar** [comment]
I will update the FAQ as well. 

Thanks to everybody!

**Comment by dsarkar** [comment]
@Ein-Tim you have a PR regarding this issue. The .md files have been changed already. The FAQ has conflicts. Do you want to adapt your PR, or shall I do it? Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar Will quickly adapt the PR, saw #821 a second ago.

**Comment by dsarkar** [comment]
@Ein-Tim ... ok, thanks.

**Comment by Ein-Tim** [comment]
@dsarkar #823

**Comment by dsarkar** [comment]
@Ben220 Thanks for spotting this issue. Feel free to close this issue.

**Comment by dsarkar** [comment]
OK, I closed it accidentally, but I guess it's fine.
