### ISSUE TITLE
BReg FAQ: Unreadable headings

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#769]
## Where to find the issue
From web browser: https://www.bundesregierung.de/corona-warn-app-faq-englisch 

Through app:
1. Device language is set to English
2. Select FAQ in app
3. scroll down 

Site status listed as Tuesday, 29. December 2020

## Describe the issue
The headings of three sections are not readable since the text overlaps itself

- How does using the Corona-Warn-App affect the battery life and storage space of smartphones?
- Why do we need a central server for a distributed solution? Isn’t that a contradiction?
- Is the "increased risk" warning by the Corona-Warn-App enough for sick leave or ordering quarantine?

---
![Unreadable subheadings](https://user-images.githubusercontent.com/66998419/104446685-1a08ac80-559b-11eb-8b15-3c29b9596128.jpg)

---
## Suggested change

Something has gone wrong with the formatting of the page https://www.bundesregierung.de/corona-warn-app-faq-englisch 
Compared to the German language page https://www.bundesregierung.de/corona-warn-app-faq the + / - to open and close FAQ sections is missing on the English language page.

---
Internal Tracking ID: [EXPOSUREAPP-4481](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4481)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal Tracking ID: EXPOSUREAPP-4481.

**Comment by GisoSchroederSAP** [comment]
Besides the fact, the above-mentioned URL [https://www.bundesregierung.de/corona-warn-app-faq-englisch] is not reachable (HTTP 404) but the URL [https://www.bundesregierung.de/corona-warn-app-faq-1758636] provide the English FAQ, 
unfortunately, I cannot reproduce the described behavior - maybe this is related to the used local browser. 

However, as I investigated there are two sections with a different font-setting on that FAQ page, I'm going to inform our contact at BPA (Bundespresseamt), which is responsible and capable in that matter.

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP
The URL https://www.bundesregierung.de/corona-warn-app-faq-englisch
comes from the string `main_about_link` embedded in the Android app at

https://github.com/corona-warn-app/cwa-app-android/blob/4f7664467cb9be280f39e5e61f9e0eb5f6063613/Corona-Warn-App/src/main/res/values/strings.xml#L205-L206

https://www.bundesregierung.de/corona-warn-app-faq-englisch responds with http 301 "Moved Permanently" and refers to the new location
https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636 (similar to the URL you quoted).

I can't say why you were getting a 404 error. I can't reproduce that problem.

The screen shot in the original issue report is **not** reproducible viewing the page in Android using Samsung Internet 13.2.1.70, however the problem **does** show using:

- Google Chrome Version 87.0.4280.141 under Android and
- Mozilla Firefox 84.1.4 under Android

The issues are also visible using Chrome, Firefox and Edge browsers under Microsoft Windows.

Thank you for contacting BPA about the English page.

BTW the German page https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392 has a confusing double date at the bottom 
Stand: 25. November 2020
Dienstag, 29. Dezember 2020

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP 
The bad headings on
https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636
are fixed and the page is showing a status date
Monday, 25. January 2021 (so the double status date is also fixed).

**Comment by Ein-Tim** [comment]
I'm still able to reproduce this on an iPhone 6s:

![IMG_5672DC2287E5-1](https://user-images.githubusercontent.com/67682506/106360449-c0351000-6318-11eb-956a-5c19621d7ddc.jpeg)

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for reporting the issue with https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636

The page now has an update status date of Friday, 29. January 2021.

I can reproduce the heading issue on a Samsung device using Samsung Internet browser Version 13.2.1.70 and Google Chrome Version 88.0.4324.93 running on Android.

On a large screen running on a Microsoft Windows machine with Google Chrome 88.0.4324.104 the issue is noticeable if the window width is reduced to a minimum (like a mobile phone in portrait orientation).

The German FAQ page https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392 does not show the problem with the headings. On the German page each of the headings is linked to a ➕ sign which can be clicked to expand the FAQ article.  On the English page there are no longer ➕ signs. They have disappeared. The article appear in full and there is no function to expand or collapse an article.

I have re-opened the issue and I need to retract the statement to @GisoSchroederSAP that the issue is fixed. 😞

**Comment by GisoSchroederSAP** [comment]
All,
I sent another collection of hints regarding English FAQ  to the respective BPA department:
* Wrong or missing heading fonts
* Missing FAQ and Blog links to coronawarn.app on the English FAQ version
* Inconsistent layout in German (with line item expansion feature) and English website (without line item expansion)

Internal tracking IDs 4479 and 4481 are updated accordingly.

Thanks @Ein-Tim, @MikeMcC399, and @dsarkar for your ongoing engagement. I'll try to follow-up on those issues as soon as I can. However, with respect to #303 there is one decision that should no longer questioned, please:
There will not be *one* combined FAQ somewhere, the hierarchy is clear and fix: The [federal FAQ](https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392) comes first. From there, they will link to other sites like the [technical FAQ] (https://www.coronawarn.app/de/faq/) or to the [RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/nCoV.html). 
I hope you all can accept this hierarchy, even if this may lead to misplaced FAQ items or overlaps.

Thank you all.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

Thank you for all your work and also clarifying that the FAQ hierarchy is fix. 
I accept this, although I think that another hierarchy would make more sense, but I won't complain since this is a bit nitpicky IMHO 😅

Thanks for answering on a Saturday evening, have a nice week-end ❤

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP

Thank you again for following up with BPA!

Please let us know the preferred way to report issues with the [Federal FAQs](https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392) managed by BPA. Should we continue to use https://github.com/corona-warn-app/cwa-website/issues even though the source of the [Federal FAQs](https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392) is not mirrored in this repository?

**Comment by GisoSchroederSAP** [comment]
Yes, please stay with the current procedure. From GitHub input we create internal issues to follow up with the proper parties (DEV, communications, BPA, RKI...) . This gives us the chance to track the issues with standard tools and to collect similar items (I'm quite convinced BPA rather prefers the bundled website issues than separate tickets).
Thank you for your support here - many eyes uncover way more than two eys of an old man ;-)

**Comment by MikeMcC399** [comment]
I am seeing the English FAQ page https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636 displaying correctly now on Android and Windows .

The page still shows Friday, 29. January 2021 at the bottom though.

@Ein-Tim would you like to check on iOS?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Seems fixed, now correctly displayed via Safari in-App browser on iOS.

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP - Thank you for working with BPA to get this fixed!
@Ein-Tim Thanks to you also for your support!

Now closing as fixed.
