### ISSUE TITLE
[Android/Google] Where to find Exposure Checks

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#785]
## Where to find the issue

FAQ Website, multiple locations

- https://www.coronawarn.app/de/faq/#exposure_check

- https://www.coronawarn.app/en/faq/#keys_matches
https://github.com/corona-warn-app/cwa-website/issues/785#issuecomment-760794603

## Describe the issue

Google Expossure notifications UI has changed

## Suggested change

Adapt FAQ entries

EN: 

- Where to find Exposure Checks:
Settings -> Google -> COVID-19 Exposure Notification  -> 3-dot overflow menu (top right corner) -> Exposure Checks 

- Export exposure checks:
Settings -> Google -> COVID-19 Exposure Notification  -> 3-dot overflow menu (top right corner) -> Exposure Checks -> Export exposure checks 

- Delete exposure checks:
Settings -> Google -> COVID-19 Exposure Notification  -> 3-dot overflow menu (top right corner) -> Exposure Checks  -> Delete exposure checks

**Comment by MikeMcC399** [comment]
@dsarkar 
Did you get any documentation from Google or do you have to "reverse engineer" the changes to describe them?

I am still wondering how Google can dynamically change the working of the Exposure Notifications System. It looks like they feed some parameters to devices and it is not just a case of downloading a new version of Google Play services.

**Comment by dsarkar** [comment]
@MikeMcC399 will forward this question. Thanks.

**Comment by MikeMcC399** [comment]
@dsarkar 
>Where to find Exposure Checks:
Settings -> COVID-19 Exposure Notification -> 3-dot overflow menu (top right corner) -> Exposure Checks

From Android Settings, you need to select Google first before COVID-19 Exposure Notifications can be selected. So the instructions should be:

Where to find Exposure Checks:
Settings -> Google -> COVID-19 Exposure Notification -> 3-dot overflow menu (top right corner) -> Exposure Checks

The same for the other entries.

**Comment by ucmichan** [comment]
Also the first part of the point "Exposure Checks" in the FAQ needs to be changed:
https://www.coronawarn.app/en/faq/#keys_matches

It reads:

"This value does not reflect the number of encounters. Please tap one level further: This is where the checks of up to 15 days are logged (today plus the last 14 days). Selecting an entry leads to a detailed view with the corresponding time stamps and the number of matched keys."

As the UI was changed, the first 2 sentences are obsolete or need to be changed, I guess.

**Comment by molarya1** [comment]
Hi @dsarkar has this issue been attended to/completed, or is it still open/available to be worked on? If still open, would love to get involved here!

**Comment by dsarkar** [comment]
@MikeMcC399 OK, thank you.
