### ISSUE TITLE
Non-CWA QR Codes

### ISSUE THREAD

**Issue by heinezen** [corona-warn-app/cwa-website#797]
Some tests are not involved with the CWA infrastructure (see https://github.com/corona-warn-app/cwa-wishlist/issues/270#issuecomment-762492944) and have their own workflow and testing backend. The patients making these tests can receive a QR Code, but this QR Code is **not** compatible with the CWA. The CWA should throw an error message for incompatible QR codes. QR codes from these tests are usually compatible with another app or website from the respective testing center.

## Proposal

Amend https://www.coronawarn.app/en/faq/#qr_scan for this scenario. There should be a new section **The code is incompatible with the CWA** that explains the problem and the solution.

**Comment by MikeMcC399** [comment]
@heinezen 
The QR code scan error handling should be refined and this would need an enhancement request.

At the moment the error message is:
`submission_qr_code_scan_invalid_dialog_headline` / `submission_qr_code_scan_invalid_dialog_body`

<string name="submission_qr_code_scan_invalid_dialog_headline">**QR code is invalid**</string>
<string name="submission_qr_code_scan_invalid_dialog_body">"The QR code is invalid or has been registered on another smartphone already. You will receive your test result from the test center or laboratory regardless of the validity of the QR code. If you are diagnosed with coronavirus, the public health authority will be notified through the legally prescribed channel and will contact you."</string>

If the QR code is invalid then the error message should say only that and be separate from the error message where the QR code has the correct format, but has already been registered. In other words, the above error message needs to be split into two different error messages.

Should I submit this to the wishlist?

**Comment by MikeMcC399** [comment]
@heinezen 
I have added a new wishlist item https://github.com/corona-warn-app/cwa-wishlist/issues/343 since @ndegendogo provided some information about a concrete case of scanning in a QR code from a different lab system.

**Comment by MikeMcC399** [comment]
Here is some suggested text:

**The code you received is not designed for the Corona-Warn-App**

Compare the bottom half of the example form on https://www.kbv.de/media/sp/Ansichtsexemplar_Muster10C.pdf with the form's QR code you are trying to scan into the Corona-Warn-App. A correct form explicitly refers to the Corona-Warn-App. If this reference is missing on the form you are using, then it is unlikely to be compatible with the Corona-Warn-App. Follow any instructions on your form to discover how it is intended to be used or contact the doctor or organisation which gave you the form to find out more.

**The code you received is designed for the Corona-Warn-App and there is a printing error**

If the form you are using looks like the bottom half of the example form https://www.kbv.de/media/sp/Ansichtsexemplar_Muster10C.pdf and you have not previously scanned it in, then there may be a printing error. If you think that you are scanning in the correct form and you are having unexplained errors, you can report this by e-mail to corona-warn-app.opensource@sap.com. Please include the information about where the form came from to allow a direct follow-up with the doctor or lab involved. You might also be able to gain some more information if you have a QR scanner app installed on your mobile device. Use this to scan in the QR code and compare it with an example of a correct QR code designed for the Corona-Warn-App and converted to text
https://localhost/?3D6D08-3567F3F2-4DCF-43A3-8737-4CD1F87D6FDA.


See also statement in https://github.com/corona-warn-app/cwa-wishlist/issues/270#issuecomment-765298531 posted by @dsarkar

**Comment by heinezen** [comment]
@MikeMcC399 I've incorporated a lot of your suggestions. Thank you!

I only made a few changes to condense the information in the entry:

* These non-CWA QR codes do not always come with a form. They sometimes only come on a strip of paper (not great). The FAQ now always suggests getting in contact with the doctor's office or test center for further instructions.
* Users probably don't know what lab is involved, so I only included the recommendation to send the doctor's/test center's contact information in the mail. I added a recommendation to include a scan of the form in the mail.
* I did not include the recommendation to scan the QR Code with another app and checking the URL text because it will not always look the same (the regex is lax and allows slightly different URLs ). In my opinion, this had the potential to create more confusion and achieves little because you still cannot do anything with a QR code decoded to URL format.

https://github.com/corona-warn-app/cwa-website/pull/811

**Comment by MikeMcC399** [comment]
@heinezen 
I agree with your comments and your FAQ text covers everything. I just saw two small points to be corrected, which I commented on in #811.

It's good to have a copy of the standard form linked into the FAQ. That will make it much easier for users to see if they have the right form.
