### ISSUE TITLE
Unknown Risk status no longer used

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#802]
## Where to find the issue
https://www.coronawarn.app/en/faq/#encounter_criteria
https://www.coronawarn.app/de/faq/#encounter_criteria

## Describe the issue
https://www.coronawarn.app/en/faq/#encounter_criteria includes the text:

"The Corona Warn App has three different status indicators that indicate this risk: "unknown risk" (grey), "low risk" (green) and "increased risk" (red).

With the status display "unknown risk", the risk determination has not been active long enough to perform a risk determination."

The status "Unknown Risk" was removed with version 1.8.

## Suggested change

Remove the reference to "Unknown Risk" in the FAQ article.

## Related issues / Pull Requests

- PR "Refactor riskcard & states; Chapter1 (EXPOSUREAPP-4049, EXPOSUREAPP-3834)" https://github.com/corona-warn-app/cwa-app-android/pull/1751 merged into branch release/1.8.x.

- "Unused Unknown Risk appears in Overview" https://github.com/corona-warn-app/cwa-app-android/issues/2196

**Comment by Ein-Tim** [comment]
As commented in https://github.com/corona-warn-app/cwa-app-android/issues/2196, the behavior under iOS is the same.
I would suggest to wait for confirmation that this is indented and not a bug before changing the FAQ.

**Comment by MikeMcC399** [comment]
It has been clarified that the bug does not exist in CWA iOS (see screen shot in https://github.com/corona-warn-app/cwa-app-android/issues/2198#issuecomment-766704532) 
![image](https://user-images.githubusercontent.com/1409741/105691575-b452e380-5efd-11eb-840b-4cda6d4f720e.png)
and that it will be fixed in CWA Android 1.12 (see https://github.com/corona-warn-app/cwa-app-android/issues/2198#issuecomment-766733450).

@dsarkar 
Thank you for moving forward with the PR #807, which looks good to me!

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks!
