### ISSUE TITLE
[CWA 1.12] Link to updated risk assessment docs

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#803]
## Your Question

* Website URL Path: https://www.coronawarn.app/en/faq/#encounter_criteria
* Line / Paragraph: 2nd paragraph
"If the calculated risk exceeds a certain [threshold](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation) specified by the Robert Koch Institute, users will receive a notification regarding an increased risk."

* Question: Does the link [threshold](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation)  to document [solution_architecture.md Section #risk-score-calculation](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation) cover the v2 risk calculations? It seems like the document [solution_architecture.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md) is out-of-date as far as risk score calculations are concerned.

v2 calculations are described in https://www.coronawarn.app/en/faq/#encounter_19_calc

**Comment by MikeMcC399** [comment]
I can answer my own question:

The link [threshold](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation) to document [solution_architecture.md Section #risk-score-calculation](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation) only describes the v1 risk calculations. The document [solution_architecture.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md) is out-of-date as far as risk score calculations are concerned (see https://github.com/corona-warn-app/cwa-documentation/issues/453).

## Suggested change

In 
https://www.coronawarn.app/en/faq/#encounter_criteria and
https://www.coronawarn.app/de/faq/#encounter_criteria

1. Remove the link in the 2nd paragraph to
`https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation`. The text can remain without the link.
2. Optionally, link this article, `https://www.coronawarn.app/en/faq/#encounter_criteria`, to the detailed v2 risk calculation description in `https://www.coronawarn.app/en/faq/#encounter_19_calc` for both languages respectively.

**Comment by heinezen** [comment]
These documents are still supposed to be updated, but this process is still ongoing. It might be okay to remove them for now and add the links back later. If there are no news on this on Thursday, I'll remove the links temporarily like you suggested.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 
https://github.com/corona-warn-app/cwa-documentation/issues/453 has the label `Fix 1.12`, so I assumed that the documents would not be updated so quickly.

**Comment by heinezen** [comment]
@MikeMcC399 PR is ready. See https://github.com/corona-warn-app/cwa-website/issues/803 for the changes.

**Comment by MikeMcC399** [comment]
@heinezen 
#813 LGTM
Thank you for implementing! 🙂

**Comment by heinezen** [comment]
Merged! I suggest we leave this issue open so that we don't forget to reinegrate the new doc links once they are ready.
