### ISSUE TITLE
English blog post January 25, 2021 - Wording of translation changes intended message

### ISSUE THREAD

**Issue by vaubaehn** [corona-warn-app/cwa-website#810]
@HannaHei & @dsarkar 
cc: @janetback 

## Where to find the issue
https://www.coronawarn.app/en/blog/2021-01-25-corona-warn-app-version-1-11-teaser/

## Describe the issue
Yesterday this blog post was announced by @Ein-Tim on our [slack channel](https://covidapps.slack.com/archives/C0194ML0MLN/p1611591970037000). 
As a spontaneous reaction, I left a silly comment:

> "The app's more than 25 million users will then be able to see [several statistics]. The goal is to encourage even more users who have tested positive to share their test result and warn others."
> Have I been the only one, reading this, felt it sounds like statistics are un-locked for every shared positive test result? Doesn't sound too impossible in times where federal prime ministers play Candy Crush during lockdown conferences... :wink: 
> But luckily we can trust our devs that they never supported such a cynical gamification.
> I see nice progress with the app. For my taste a very good job is/was done.

My comment urged @d4rken to clarify, that

> Statistics will be visible for everyone, there is no condition except having internet access.

While writing my response to him, that I am sorry to steal his time by provoking a clarification, I had a second, more serious look on the text of the blog post, and concluded, that it may be worth to improve it.

So, let's look together now.

The German blog post reads:
> Die mehr als 25 Millionen Nutzer*innen der Corona-Warn-App können dann in der App stets auf die aktuellen Zahlen zu den Neuinfektionen, der 7-Tage-Inzidenz und dem 7-Tage-R-Wert zugreifen. Außerdem können sie direkt in der App einsehen, wie viele Nutzer*innen ihr Testergebnis geteilt haben. Ziel ist es, noch mehr positiv getestete Nutzer*innen dazu anzuregen, ihr Testergebnis zu teilen und Kontaktpersonen zu warnen.

The intention of the content inherent in the German version seems to be more clear here: First some statistics are announced in one sentence. Then the statistic of users sharing their test results is emphasized in the next sentence. The last sentence connects to the preceding sentence: the goal of that user statistic is to encourage more users to share their test results.

The English translation is slightly different:
> The app’s more than 25 million users will then be able to see the number of new infections, the 7-day incidence rates and the 7-day R-value, as well as the number of people who have warned their fellow citizens via the app. The goal is to encourage even more users who have tested positive to share their test result and warn others.

Here we have only two sentences, one counting all statistics, and the second stating what is the goal (of _all_ the statistics): to encourage users to share their test results - which is a different message compared to the German version. The English version might be misunderstood by a small amount of biased readers.

## Suggested change
For the English version:
`The Corona-Warn-App’s more than 25 million users will then be able to see the number of new infections, the 7-day incidence rates and the 7-day R-value directly from inside the application. Additionally, in-app statistics are presented on the number of users who have already warned their fellow citizens via the app, to encourage even more users who have tested positive to share their test result and to warn others. `

There could also be a small change to the German version for smoothing the connection of the third sentence:
`Die mehr als 25 Millionen Nutzer*innen der Corona-Warn-App können dann in der App stets auf die aktuellen Zahlen zu den Neuinfektionen, der 7-Tage-Inzidenz und dem 7-Tage-R-Wert zugreifen. Außerdem können sie direkt in der App einsehen, wie viele Nutzer*innen ihr Testergebnis geteilt haben. So sollen noch mehr positiv getestete Nutzer*innen dazu angeregt werden, ihr Testergebnis zu teilen und Kontaktpersonen zu warnen.`

Excuse me for being overly precise here... I just finished the review of a scientific paper, and probably I'm still in referee mode. But maybe you find the suggestions useful.

Cheers,
V.

**Comment by MikeMcC399** [comment]
@vaubaehn 

Even though the German and English texts are not necessarily exactly equivalent, they are both valid. I would not want to make any assumptions about which of the values might or might not motivate a user to share the result of a positive test, or even the fact that there is some sharing of the bigger picture in general might change a person's level of involvement.

I would suggest leaving the English text unchanged.

Here are screen shots from Android branch release/1.11.x (which is not yet released)

![Confirmed New](https://user-images.githubusercontent.com/66998419/105878839-c027ce00-6001-11eb-8b26-e538c28f6182.png)
![Warnings by users](https://user-images.githubusercontent.com/66998419/105878856-c5851880-6001-11eb-8986-80114bf64565.png)
![7-day incidence](https://user-images.githubusercontent.com/66998419/105878874-ca49cc80-6001-11eb-8f4a-32627bcd93c7.png)
![7day R value](https://user-images.githubusercontent.com/66998419/105878882-cddd5380-6001-11eb-9fce-b9f4acb4834c.png)

**Comment by vaubaehn** [comment]
@MikeMcC399 

Is my proposal less correct or less precise?
Could you please elaborate your suggestion to leave it unchanged?

**Comment by MikeMcC399** [comment]
@vaubaehn 
We would need help from the original author to clarify the intended statement and whether they consider a change is necessary. So whether your suggestions are more correct depends on the author's intention.

I expect there will be another more detailed blog post when Version 1.11 is released, so I would not put too much weight on the exact wording of the pre-release blog post.

**Comment by MikeMcC399** [comment]
@vaubaehn 
Now that CWA Version 1.11 has been announced and released (see [Blog Post](https://www.coronawarn.app/de/blog/2021-01-28-corona-warn-app-version-1-11/)) you should consider if you want to pursue your request for text changes in the pre-release announcement.

**Comment by vaubaehn** [comment]
@MikeMcC399 

Thanks for all your suggestions.
