### ISSUE TITLE
BReg FAQ: Glossary: Bad links to Risk Assessment documents

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#828]
## Where to find the issue

Glossary / Glossar documents on Federal FAQ website
https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636 (English) and
https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392 (German)

## Describe the issue

The Glossary documents on the Federal FAQ site contain URLs pointing to the Risk Assessment documents on github.

1. The URLs are not embedded hyperlinks and cannot be clicked on to open the document.
a. On Android nothing happens if an attempt is made to open the documents by tapping the URL text.
b. On Microsoft Windows if reading the documents with Adobe Acrobat Reader DC and Preferences > General > Create links from URLs is selected then various errors occur:
i. English Page 2, error 404 due to hyphenation mas-ter across line change
ii. English Page 4, error 404 due to hyphenation cwa-risk-as-sessment across line change
iii. German Page 1, no error 
iv. German Page 4, error 404 due to hyphenation transla-tions across line change

2. The English language Glossary lists the URL of the German language Risk Assessment document.

3. There is no version number or date in the Glossary documents, although there is a date hard-coded into the filename of the documents.

## Suggested change

1. Use clickable hyperlinks to https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md to the English language Risk Assessment document in the English language Glossary.

2. Make the existing links a hyperlink for https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/cwa-risk-assessment.de.md to the German language Risk Assessment document in the German language Glossary.

3. Add a version number or a revision date footer to each Glossary document which is visible when printing or reading the document.

## Documents

[2020-06-16-glossar-en-data.pdf](https://github.com/corona-warn-app/cwa-website/files/5904244/2020-06-16-glossar-en-data.pdf)
[2020-06-16-glossar-data.pdf](https://github.com/corona-warn-app/cwa-website/files/5904245/2020-06-16-glossar-data.pdf)

---
Internal Tracking ID: [EXPOSUREAPP-4481](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4481) FAQ
Internal Tracking ID: [EXPOSUREAPP-4971](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4971) Glossary

**Comment by heinezen** [comment]
@MikeMcC399 I have added your finding to the general BReg issue ticket. We'll try to get these fixed by talking to the responsible entities again.

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-4481](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4481) FAQ
Internal Tracking ID: [EXPOSUREAPP-4971](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4971) Glossary

**Comment by MikeMcC399** [comment]
Many months have gone by and this issue has not been fixed. I suggest to close the issue if there is no possibility to remedy the glossary documents served on the website of the Bundesregierung.

**Comment by MikeMcC399** [comment]
Closing due to non-response.
