### ISSUE TITLE
FAQ: English page links to German terms of use (EXPOSUREAPP-4985)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#837]
## Where to find the issue

https://www.coronawarn.app/en/ Section Transparency

![image](https://user-images.githubusercontent.com/66998419/106758963-73ac4600-6632-11eb-9b79-c2b454e548d3.png)

## Describe the issue
https://www.coronawarn.app/en/ (English) links to German terms of use https://www.coronawarn.app/assets/documents/cwa-eula-de.pdf

## Suggested change

Change the link on https://www.coronawarn.app/en/ (English) to the **English** terms of use https://www.coronawarn.app/assets/documents/cwa-eula-en.pdf

---
EXPOSUREAPP-4985

**Comment by MikeMcC399** [comment]
The link seems to have been this way for months. I just wanted to get feedback from the Open Source Team before submitting a PR, since this is a legal document. I can't see any reason though *not* to link to the English Terms of Use on the English page.

The app itself is displaying English Terms of Use when the UI is set to English.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Sorry, I definitely did not want to steal you a PR (if you like to I can close mine and you can open a new one) 🙂

It was a quick fix so I just thought let's do it. If they, for what reason so ever, don't want to change the link, that's not a big problem, was a quick one 😄

**Comment by MikeMcC399** [comment]
@Ein-Tim 
No, don't close your PR. It's fine!

Just in future check with me before opening a PR on one of my issues please, as I will sometimes open an issue first if I think it needs a discussion before submitting a PR. Before I set up a PR I like to have the feeling that the Open Source Team is likely to approve it! When I started here (now months ago!) I did not have the experience with GitHub to know how to do things right. In the meantime I've learned a bit, so I can now do most things myself. 😀

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> Just in future check with me before opening a PR on one of my issues please

For sure, will do so! 👍

**Comment by dsarkar** [comment]
EXPOSUREAPP-4985

**Comment by dsarkar** [comment]
@Ein-Tim  @MikeMcC399 Thanks !
