### ISSUE TITLE
Review of FAQs related to Release 1.12 /-4987/-4988

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#842]
- FAQs prüfen, inwieweit Einträge hinsichtlich der Unterstützung von iOS 12.5 (ältere iPhones) angepasst werden müssen
- FAQs 1x durchscrollen und prüfen, ob für 1.12 noch weitere Anpassungen notwendig sind (Stichwort "exposure history")

[EXPOSUREAPP-4987](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4987)
[EXPOSUREAPP-4988](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4988)

---

DE - Suggestion for updating https://www.coronawarn.app/de/faq/#minimum_requirements

Welche Systemvoraussetzungen muss mein Smartphone erfüllen?
----

**AKTUELL 8. Februar 2021**

Seit dem 5. Februar 2021 werden nur die Corona-Warn-App (CWA) Versionen 1.5 und höher unterstützt. Aus diesem Grund erhalten Nutzer mit älteren Versionen einen Hinweis, Ihre App entsprechend zu aktualisieren. Dies gilt sowohl für iOS als auch Android. Parallel gelten jedoch bestimmte Mindestvoraussetzungen an das Betriebssystem: Android mindestens 6.0 und iOS mindestens 13.7.

iOS Nutzer, die bisher bspw. 13.5 genutzt haben, müssen Ihre App nun zwingend auf mindestens 13.7 aktualisieren, um die CWA weiterhin zu nutzen. Nur in diesem Fall kann eine technisch korrekte Funktion der App sichergestellt werden. 

	
- Bitte führen Sie zunächst ein Update Ihrer iOS-Version durch. Auch ältere Smartphones, wie bspw. das iPhone SE, 6S oder 6S Plus unterstützen das neueste iOS Betriebssystem. Sie können Ihr iPhone somit mindestens auf iOS 13.7 aktualisieren. Aus Sicherheitsgründen sollten Sie ihr iPhone jedoch grundsätzlich aktuell halten, da Apple auch regelmäßig kleinere Sicherheitslücken mit den Updates behebt. Sie können dies auf Ihrem iPhone unter Einstellungen – Allgemein – Softwareupdate durchführen.
	
- Im Anschluss aktualisieren Sie bitte die Corona-Warn-App. Die Corona-Warn-App muss zudem mindestens in Version 1.5 installiert sein. Inzwischen ist bereits Version 1.11 verfügbar. 

Ab der CWA Version 1.12 werden zusätzlich auch die ältere iPhone Modelle iPhone 5s, iPhone 6, iPhone 6plus unterstützt. Diese Geräte müssen auf die iOS Version 12.5 bzw. 12.5.1 aktualisiert werden.

Die folgende Tabelle dient zur Übersicht:
Die folgende Tabelle dient zur Übersicht:

Folgende Tabelle dient zur Übersicht:

Gerät  | Betriebssytem Minimum | Betriebssytem Empfohlen | Exposure Notification System  |  CWA Minimum | CWA Empfohlen
--- | --- | --- | --- | ---  | ---  
iPhone 5s, 6, und 6 Plus | iOS 12.5 | iOS 12.5.1 | v2 ENF (inbegriffen in iOS)  |  1.5 | 1.11
iPhone SE, 6s, 6s Plus und [neuere Modelle](https://support.apple.com/en-gb/guide/iphone/iphe3fa5df43/ios) | iOS 13.7 | iOS 14.4 | v2 ENF (inbegriffen in iOS) | 1.5  | 1.11
Android  | Android 6 | neuste Version vom Gerätehersteller | aktuelle Google Play services  | 1.5  | 1.11

 

---

**AKTUELL**
Telekom und SAP werden die Corona Warn App für iOS 12.5 verfügbar machen.

---

[Apple/iOS]: Die App läuft auf iOS-Smartphones ab dem iPhone 6s. Obwohl die Exposure Notification API mit iOS 13.5 eingeführt wurde, muss Ihr Betriebssystem iOS 13.7 oder höher sein, da die Corona-Warn-App Version 2 des Exposure Notification Frameworks benutzt, welche mit iOS 13.7 eingeführt wurde.

[Google/Android]: Die App läuft auf Smartphones ab Android 6. Die Exposure Notification API wurde hier bereits über die Google-Play-Dienste eingespielt.

Weitere Fragen zu den Betriebssystemen können nur die Hersteller selbst beantworten.

**Comment by dsarkar** [comment]
https://www.coronawarn.app/en/faq/#minimum_requirements

**Comment by Ein-Tim** [comment]
@dsarkar 

Could you please clarify internally what we should do with the ios-minimum-required-os-version?

Because we can't just state that iOS 12.5 is the minimum required since the app will not work on iOS 13.0 - 13.7.

I hope you understand what I mean 😅👍

**Comment by MikeMcC399** [comment]
Also the requirements will need to be updated on related websites in the FAQ hierarchy:

- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392#toggledown-content-7
- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636#toggledown-content-7
- https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Will forward info.
@Ein-Tim 

I suggest:
"
Keep operating systems up-to-date (iOS 12.5.x for iPhone 6, and iOS 14.4 resp. at least iOS 13.7 for iPhone 6s and newer models or at least Android 6 with current Google Play Services)
"

**Comment by Ein-Tim** [comment]
@dsarkar 

Yeah this sounds good, but maybe we should consider to add a small new FAQ entry to the FAQs explaining this a bit more detailed to avoid confusion?

**Comment by MikeMcC399** [comment]
@dsarkar 
The statement is a bit difficult to read. Maybe it would be better as a list?

Also it doesn't seem to cover the same list of iOS phones are the latest blog https://www.coronawarn.app/en/blog/2021-02-04-cwa-1-12-announcement/
"With version 1.12, the Corona-Warn-App will be compatible with iOS 12.5 so that owners of older iPhones, such as the iPhone 5s, 6, and 6plus, can use the app."

I'm not sure if the following is correct for iOS, but @Ein-Tim can say:

Device | Operating System | Minimum | Preferred | Additional
--- | --- | --- | --- | ---
iPhone 5s, 6, and 6plus | iOS | 12.5 | 12.5.1 |
all other Apple | iOS | 13.7 | 14.4 |
any Android | Android | 6 | latest for device | current Google Play services

If you stay with the one-line explanation "resp." as an abbreviation in English is not common. Better to write it in full as "respectively".

In "Google Play services", Google does not capitalise the word "services" 
See https://play.google.com/store/apps/details?id=com.google.android.gms

![image](https://user-images.githubusercontent.com/66998419/106941920-d3cee500-6723-11eb-87e5-5f471284c51e.png)

**Comment by Ein-Tim** [comment]
@MikeMcC399 

What you wrote is correct and I definitely think that we should do it in this list, although it's a bit more complicated to update from our side (new OS version), but I think this should work! 

We could use https://www.coronawarn.app/en/faq/#minimum_requirements for this, or?

**Comment by MikeMcC399** [comment]
@dsarkar / @Ein-Tim 
In https://www.coronawarn.app/en/faq/#minimum_requirements it discusses about v2 ENF. How does iOS 12.5 work with CWA 1.12? Will it use v2 or is it going to use the old v1? That information probably needs to be discussed and it could go in the table I proposed.

**Comment by Ein-Tim** [comment]
@MikeMcC399 iOS 12.5 will use v2 of the ENF.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
>  iOS 12.5 will use v2 of the ENF. We should definetly update it and do it in an table to make it clearer.

Maybe it's good that I know nothing about this, because then I'm like a user who knows nothing! So is 12.5 an new update which Apple will load onto iPhone 5s, 6, and 6plus phones, and it contains v2? Or how does this work?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

>Maybe it's good that I know nothing about this, because then I'm like a user who knows nothing!

You're right, seems like this is perfect for this case.

>So is 12.5 an new update which Apple will load onto iPhone 5s, 6, and 6plus phones, and it contains v2? Or how does this work?

Yes, iOS 12.5 has been rolled out to devices which don't support iOS 13 (so they stopped updating with iOS 12.4.x) to give the users of the iPhone 6, iPhone 6 Plus and iPhone 5s an opportunity to use the ENF.

There was a problem with iOS 12.5 so they rolled out a bug fix (iOS 12.5.1).

---

IMHO what is the most confusing about all of this is that we can't state that you need iOS 12.5 or higher to use CWA since iOS 13.0 - 13.6.1 are not supported (iOS 13.0 - 13.4.1 didn't support the ENF and iOS 13.5 - 13.6.1 are not supported anymore by CWA (because v2 of the ENF came with iOS 13.7))

**Comment by dsarkar** [comment]
@EIn-Tim @MikeMcC399 Thanks. Table looks good indeed.

Question is: Nice short statement on min. requirements on the homepage. Maybe link to FAQ with table for details?

So:


I suggest:
"
Keep operating systems up-to-date (iOS 14.4 or iOS 12.5.1 depending on your iPhone model or at least Android 6 with current Google Play Services, respectively) [More details here](https://github.com/corona-warn-app/cwa-website/issues/842#issuecomment-773543700)
"

"
Betriebssysteme aktuell halten (iOS 14.4 oder mindestens iOS 13.7, iOS 12.5.1 oder mindestens 12.5 für iPhone 5s, 6, 6Plus bzw. mindestens Android 6 mit aktuellen Google Play Services)
"

**Comment by MikeMcC399** [comment]
@dsarkar / @Ein-Tim 

You should probably explain what options a user with iOS 13.5 and 13.6 has. And I don't know the answer.

If a user already has an older version of CWA installed which was compatible with the versions of iOS 13.5 & 13.6 will the older version of CWA continue to work? If it doesn't work any more is it always possible to update iOS to at least 13.7, or are there some models which can't be updated? (I understand a bit more about the compatibilities, now that I read https://developer.apple.com/documentation/exposurenotification/supporting_exposure_notifications_in_ios_12_5).

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> You should probably explain what options a user with iOS 13.5 and 13.6 has. And I don't know the answer.

They only have the option to either continue to use CWA 1.7 or lower or to update their OS. 

> If a user already has an older version of CWA installed which was compatible with the versions of iOS 13.5 & 13.6 will the older version of CWA continue to work?

I assume that users on iOS versions lower than 13.7 can't update to CWA 1.9 or higher (the App Store will stop them from doing so). 

Starting with version 1.12 there will be a screen which is shown to all users on iOS versions between 13.0 and 13.6.1 informing them to update iOS (https://github.com/corona-warn-app/cwa-app-ios/pull/1818)

> If it doesn't work any more is it always possible to update iOS to at least 13.7, or are there some models which can't be updated? 

All devices which can run iOS 13 can also run iOS 14, so everybody on any iOS 13 version is able to update to the newest iOS 14 version.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for explaining to me. In that case the table I did doesn't need more explanation. It's good to read that the 1.12 iOS app will also take responsibility for advising the user about updating iOS.

@dsarkar 
> Keep operating systems up-to-date (iOS 14.4 or iOS 12.5.1 depending on your iPhone model or at least Android 6 with current Google Play Services, respectively)

Knowing the background information from @Ein-Tim your statement sounds good!

**Comment by dsarkar** [comment]
@Ein-Tim  @MikeMcC399 FYI

Since last Friday minimum supported CWA is release 1.5.
In the AppStores, some users run into popup notifications to update CWA (apparently still using < 1.5 (!)) but could not do so, since they had not updated to iOS 13.7 or higher. Decision to update 

https://www.coronawarn.app/de/faq/#minimum_requirements

before release 12.5.

**Comment by dsarkar** [comment]
![image](https://user-images.githubusercontent.com/1409741/107214096-afb42200-6a09-11eb-8de6-db8f6e18546a.png)

**Comment by MikeMcC399** [comment]
@dsarkar 
> 
> Since last Friday minimum supported CWA is release 1.5.
> In the AppStores, some users run into popup notifications to update CWA (apparently still using < 1.5 (!)) but could not do so, since they had not updated to iOS 13.7 or higher. 

That is a significant change and although https://www.coronawarn.app/en/ and https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636 already say the minimum iOS version is 13.7, the change from 13.5 hasn't been explicitly announced.

Probably there should be a blog post announcing the change (maybe together with the announcement for CWA version 1.12.0 since this is also very close). It would be good not only to announce the change, but also to explain the reason for enforcing the minimum version. Iirc correctly on Android it was only previously enforced that 1.0.5 was the minimum installed version.

**Comment by dsarkar** [comment]
DE - Suggestion:
----

**AKTUELL 8. Februar 2021**


Seit dem 5. Februar 2021 werden nur die Corona-Warn-App (CWA) Versionen 1.5 und höher unterstützt. Dadurch kann es vorkommen, dass Benutzer eine Nachricht erhalten, die CWA upzudaten. Dabei muss beachtet werden, dass möglicherweise zuvor auch das iOS Betriebssytem auf aktuellen Stand gebracht werden muss:


- Bitte führen Sie zunächst ein Update Ihrer iOS-Version durch. Auch ältere Smartphones, wie bspw. das iPhone SE, 6S oder 6S Plus unterstützen das neueste iOS Betriebssystem. Sie können Ihr iPhone somit mindestens auf iOS 13.7 aktualisieren. Aus Sicherheitsgründen sollten Sie ihr iPhone immer aktuell halten, da Apple auch regelmäßig kleinere Sicherheitslücken mit den Updates behebt. Sie können dies auf Ihrem iPhone unter Einstellungen – Allgemein – Softwareupdate durchführen.


- Im Anschluss aktualisieren Sie bitte die Corona-Warn-App. Die Corona-Warn-App muss zudem mindestens in Version 1.5 installiert sein. Inzwischen ist bereits Version 1.11 verfügbar. Wir bitte Sie daher, Ihre Corona-Warn-App zu aktualisieren. 


- In der CWA Version 1.12 werden auch die ältere iPhone Modelle iPhone 5s, iPhone 6, iPhone 6plus unterstützt. Diese Geräte müssen auf die iOS Version 12.5 oder besser 12.5.1 aktualisiert werden. 

Tabelle 


 


---


**AKTUELL**
Telekom und SAP werden die Corona Warn App für iOS 12.5 verfügbar machen.

---

[Apple/iOS]: Die App läuft auf iOS-Smartphones ab dem iPhone 6s. Obwohl die Exposure Notification API mit iOS 13.5 eingeführt wurde, muss Ihr Betriebssystem iOS 13.7 oder höher sein, da die Corona-Warn-App Version 2 des Exposure Notification Frameworks benutzt, welche mit iOS 13.7 eingeführt wurde.

[Google/Android]: Die App läuft auf Smartphones ab Android 6. Die Exposure Notification API wurde hier bereits über die Google-Play-Dienste eingespielt.

Weitere Fragen zu den Betriebssystemen können nur die Hersteller selbst beantworten.

**Comment by MikeMcC399** [comment]
@dsarkar 
I checked on Android and after installing CWA 1.0.0 I got a popup to say I have to update. I didn't get that message after installing then trying to run CWA 1.3.1 for instance. So I wonder what is being enforced for Android. I will take a look again later at this.

![image](https://user-images.githubusercontent.com/66998419/107217768-f22c2d80-6a0e-11eb-899e-05a9d5e0d44a.png)

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/852

**Comment by MikeMcC399** [comment]
@dsarkar 
On Android I see in the debug logs 
**minVersionFromServer:31**

https://www.apkmirror.com/apk/robert-koch-institut/corona-warn-app/corona-warn-app-1-0-4-release/corona-warn-app-1-0-4-android-apk-download/ shows
Version: 1.0.4 (**31**)

So CWA Android is enforcing a minimum version of 1.0.4, not 5.1.0.

**Comment by MikeMcC399** [comment]
@dsarkar 
Could you please check about the statement that only Version 1.5 is supported and that users will be prompted to update?

For Android versionName 1.5.0 the versionCode was 47 and I am seeing only versionCode 31 being forced by the server configuration parameters.

Is the forced update already supposed to be implemented for Android? Am I interpreting the information correctly? You wrote that the support changed starting on Feb 5, 2021.

See the following for versionName / versionCode
https://github.com/corona-warn-app/cwa-app-android/blob/0f12f4ddbd814ac368901858363f7835bb30b9a8/Corona-Warn-App/build.gradle#L43-L44

**Comment by dsarkar** [comment]
@MikeMcC399 My understanding is they rolled it back on the server for Android, but kept min version 1.5 for iOS.

**Comment by dsarkar** [comment]
@MikeMcC399 FYI https://github.com/corona-warn-app/cwa-server/pull/1138/files

**Comment by MikeMcC399** [comment]
@dsarkar 

Now I'm confused because according to https://github.com/corona-warn-app/cwa-server/pull/1138/files 
min-android-version-code:
was changed on Jan 25, 2021 
from 31 to 48
min-android-version-code: ${ANDROID_MIN_VERSION_CODE:48}
and I can't see any record of it being reverted to 31!?

Are there server parameter changes being made which are not recorded in GitHub?

**Comment by dsarkar** [comment]
@Ein-Tim 

> 
Could you please clarify internally what we should do with the ios-minimum-required-os-version?



- for the moment let use that one for iPhone 6s and above, i.e. currently 13.7
- we update 12.5.1 for older models manually where necessary. We Will discuss internally if it is appropriate to create a new variable
