### ISSUE TITLE
Special case "Limit already reached" after app reset

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#848]
## Where to find the issue

[Google/Android]: Error when communicating with Google API (39508)
https://www.coronawarn.app/en/faq/#API39508

Also work-in-progress PR #789.

## Describe the issue

As described in "Reset App late in day causes "Limit already reached" error message" https://github.com/corona-warn-app/cwa-app-android/issues/2248 the error message "Limit already reached" can be caused by resetting the app late in the day after approximately 20:00 UTC (21:00 CET or 22:00 CEST) when the app has been operating correctly and is permanently connected to WiFi, so that it will have performed a risk evaluation every 4 hours. 

According to https://developers.google.com/android/exposure-notifications/exposure-notifications-api#modes provideDiagnosisKeys quota is Six per day (counter resets at 00:00 UTC) in ExposureWindow mode (aka v2). So if the first submission is done at 00:01 UTC, followed by 04:01, 08:01, 12:01, 16:01 at 20:01 the quota of six submissions for the day has already been used up. This should not normally matter, because the next submission will not be due until after 24:00 UTC. However, Reset App, could provoke an additional submission and thus exceed the quota.

This Reset App issue will not be fixed (see https://github.com/corona-warn-app/cwa-app-android/issues/2248#issuecomment-773900831) since it is considered an edge case and would be complex to work around.

The situation is not described in the FAQ https://www.coronawarn.app/en/faq/#API39508.

## Suggested change

In the draft PR #789, after the sentence:

"However, should you experience an issue related to this error notification, please submit your report here: [associated GitHub issue 1459](https://github.com/corona-warn-app/cwa-app-android/issues/1459)"

add

EN
If you have just carried out "Reset App" in the app Settings and you then receive the error message "Limit already reached", please follow the instructions in the message and wait until the next day for the limit to be automatically reset.

DE
Wenn Sie gerade "Anwendung zurücksetzen" in den Einstellungen der App durchgeführt haben, und danach die Fehlermeldung "Limit bereits erreicht" bekommen, dann warten Sie bitte bis zum nächsten Tag, dass das Limit automatisch zurückgesetzt wird, wie in der Meldung empfohlen.

**Comment by heinezen** [comment]
Also relevant: https://github.com/corona-warn-app/cwa-website/pull/895

**Comment by MikeMcC399** [comment]
This issue was resolved by PR #895, which was merged on May 3, 2021.
