### ISSUE TITLE
Text is going out of the box in #de

### ISSUE THREAD

**Issue by Max-Trueby** [corona-warn-app/cwa-website#849]
## Where to find the issue
![grafik](https://user-images.githubusercontent.com/63929717/107158626-bb610380-698b-11eb-98ae-acee8127a4ba.png)
https://www.coronawarn.app/de/
This issue only in **#de** not in **#en** and it is in the Questions section

## Describe the issue
The text is going out of the box if the browser size is ca. 766-576 x 0-1000 (and more) pixel.

## Suggested change
I would take a `<br>` between "Mehr Fragen?" `<h3>` and "Häufig gestellte Fragen zur Corona-Warn-App" `<a>`

**Comment by Ein-Tim** [comment]
German file:

https://github.com/corona-warn-app/cwa-website/blob/b2ea009a6a4557f89a7bfe18aae1a81b1c626df6/src/data/index_de.json#L330-L337

English file:

https://github.com/corona-warn-app/cwa-website/blob/b2ea009a6a4557f89a7bfe18aae1a81b1c626df6/src/data/index.json#L330-L337

I don't really know what's going on here, it seems like both, German & English have the same structure, so maybe it's about the longer German text ("Häufig gestellte Fragen zur Corona-Warn-App")...

**Comment by dsarkar** [comment]
@Max-Trueby  @Ein-Tim Thanks for contributing. We will look for a simple solution.

**Comment by dsarkar** [comment]
@heinezen Any idea for a simple solution?

**Comment by MikeMcC399** [comment]
@dsarkar 
The simplest workaround is to replace the text "Häufig gestellte Fragen zur Corona-Warn-App" with a shorter text. If you make the browser window even narrower then the text is moved down and it is no longer overflowing from the box.

The box however does overlap the one below in that case.

![image](https://user-images.githubusercontent.com/66998419/107225613-4dfbb400-6a19-11eb-84ec-a5edb5e81da4.png)

Otherwise somebody would need to start debugging and fixing the code generation from the json input to html code.

**Comment by dsarkar** [comment]
> Otherwise somebody would need to start debugging and fixing the code generation from the json input to html code.

Yes, that what I want to avoid if possible.

**Comment by Ein-Tim** [comment]
We could just write:

" **Mehr Fragen?**

Antworten in den FAQ" 

We could also change the English text to be consistent: 

" **More questions?**

Answers in the FAQ"

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Did you try your proposed changes out on a local server and then watch what happens as you change the width of the browser window dynamically?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Just tested it via Chrome DevTools, it works 👍

<img src="https://user-images.githubusercontent.com/67682506/107254292-75617980-6a37-11eb-8aa5-ca9323d0f198.png" width="300">

But if the browser is wider, it looks a bit strange IMHO:

<img src="https://user-images.githubusercontent.com/67682506/107254432-9a55ec80-6a37-11eb-879c-781e852fdbdb.png" width="300">

**Comment by MikeMcC399** [comment]
@Ein-Tim 
If you think it is good will you now submit a PR?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I'm quite bussy at the moment (and in the next few days) so feel free to submit one.

What do you think, should we change the English text too or leave it like it is?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
OK. I'll take a look at it and submit a PR. Thanks for trying things out!

**Comment by MikeMcC399** [comment]
I have submitted PR #853 and I only changed the German text since the English text was not causing a problem.
