### ISSUE TITLE
[CWA v1.12] Add small FAQ entry explaining the contact journal

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#850]
## Suggested Enhancement 

As discussed in https://github.com/corona-warn-app/cwa-app-ios/issues/1936, it would make sense to have a small FAQ entry (based on the [Blog](https://www.coronawarn.app/en/blog/2020-12-28-corona-warn-app-version-1-10/)) which explains how to delete/edit entries.

**Comment by dsarkar** [comment]
@Ein-Tim 

Suggestion: Extend this FAQ: https://www.coronawarn.app/en/faq/#contact_diary

- One possibility is simply to put there a link to the blog, saying there is more info on how to use it.
- Or small explanation and for more info see blog (with link)

**Comment by Ein-Tim** [comment]
@dsarkar 

I would say just put the link to the blog there.

DE: 

"Weitere Informationen zur Bedienung des Kontakttagebuchs finden Sie in diesem Blog Post"

EN:

"More information on how to use the contact journal can be found in this blog post"

**Comment by heinezen** [comment]
We are waiting for CWA release 1.12 on this one.

**Comment by Ein-Tim** [comment]
@heinezen 

Am I wrong or was version 1.12 released yesterday?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Android users have to exercise patience: I only just received CWA Android 1.12 a few minutes ago, even though the release was already announced through https://github.com/corona-warn-app/cwa-website/pull/863 more than 48 hours ago. 🙂

**Comment by Ein-Tim** [comment]
If nobody is working on this, I can integrate a [link to the blog](https://www.coronawarn.app/en/blog/2020-12-28-corona-warn-app-version-1-10/) in the [FAQ entry](https://www.coronawarn.app/en/faq/#contact_diary).
Just let me quickly know if somebody else is already on it.

Thanks!

**Comment by dsarkar** [comment]
@Ein-Tim sure, go ahead! Thanks.
