### ISSUE TITLE
Update https://www.coronawarn.app/en/faq/#ios135

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#855]
## Where to find the issue
https://www.coronawarn.app/en/faq/#ios135

## Describe the issue
min req. now 12.5 for iPhone 5s, 6, 6 Plus

## Suggested change

indroduce link to FAQ https://www.coronawarn.app/en/faq/#minimum_requirements
and mention 12.5

remove [ios.minimum-required-os-version] from title, since 12.5 and 13.7 are both min req, depending on model

**Comment by dsarkar** [comment]
Currently 

EN

![image](https://user-images.githubusercontent.com/1409741/107339334-df703200-6abc-11eb-9d19-6fb813fb0d05.png)

DE

![image](https://user-images.githubusercontent.com/1409741/107339378-ec8d2100-6abc-11eb-8225-893a071e3b04.png)

**Comment by dsarkar** [comment]
Suggested update
---


**AKTUELL 10 Februar 2021**

Mit der Corona-Warn-App Version 1.12 werden zusätzlich auch die ältere iPhone Modelle iPhone 5s, iPhone 6 und iPhone 6 Plus unterstützt. Vorraussetzung ist auf diesen Geräten das iOS Betriebssystem mindestens auf die Version iOS 12.5 zu aktualisieren. 

Siehe auch den Blog [Telekom und SAP werden die Corona Warn App für iOS 12.5 verfügbar machen.](https://www.coronawarn.app/de/blog/2020-12-15-ios-12-5/)

---

Apple hat die erforderliche Schnittstelle für Verfolgung von Begegnungen (Exposure Notification API) mit iOS 13.5 eingeführt, siehe Informationen zu iOS 13-Updates. Mit dem Release 1.9 (und dem Update auf Version 2 des Exposure Notification Frameworks) der Corona-Warn-App wird nun iOS 13.7 vorausgesetzt, da die Version 2 des Exposure Notification Frameworks mit dieser Version eingeführt wurde. Die unterstützten Gerätemodelle finden Sie unter anderem hier: Unterstützte iPhone-Modelle. Leider bietet Apple keine Unterstützung mehr für Geräte an, die älter als 4-5 Jahre sind. An diesen Gegebenheiten können wir als App-Entwickler leider nichts ändern.

**Comment by Ein-Tim** [comment]
@dsarkar 

We could also rearrange the FAQ so that the https://www.coronawarn.app/en/faq/#ios135 entry is directly under https://www.coronawarn.app/en/faq/#minimum_requirements.

**Comment by dsarkar** [comment]
@Ein-Tim Yes, indeed, good idea!

**Comment by dsarkar** [comment]
EN


The Corona-Warn-App release 1.12 also supports the older iPhone models iPhone 5s, iPhone 6, and iPhone 6 Plus. On these devices, the iOS operating system must be upgraded to at least iOS 12.5.  
Apple is providing the operating system  iOS 13.7 and higher versions for the iPhone SE (1st generation), iPhone 6s, and newer models. 
 
More details about the system requirement can be found [in this FAQ entry](https://www.coronawarn.app/en/faq/#minimum_requirements). 
See also the blog [Telecom and SAP will make the Corona Warn app available for iOS 12.5.] ( https://www.coronawarn.app/en/blog/2020-12-15-ios-12-5/) 

---

**Comment by MikeMcC399** [comment]
@dsarkar 

I would change
"Apple is providing"
to
"Apple provides"
because it is a permanent state, not just something happening right now.

Also
"system requirement"
I suggest should be plural
"system requirements"
since there are multiple different requirements.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks!

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/857
