### ISSUE TITLE
Update website - Section: This is how the app works best

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#856]
## Where to find the issue

EN
![image](https://user-images.githubusercontent.com/1409741/107343112-53acd480-6ac1-11eb-9985-f8cd46a4c468.png)

DE
![image](https://user-images.githubusercontent.com/1409741/107344188-7986a900-6ac2-11eb-9c93-15c128c89e24.png)

## Describe the issue

12.5 min req for iPhone 5s, 6, 6 Plus, ... 13.7 for higher models

## Suggested change

EN
---
"Keep operating systems up-to-date (iOS 14.4 or iOS 12.5.1 depending on your iPhone model or at least Android 6 with current Google Play services, respectively) [More details](https://www.coronawarn.app/en/faq/#minimum_requirements)"

DE
---

Betriebssysteme aktuell halten (iOS 14.4 oder iOS 12.5.1 abhängig von Ihrem iPhone Modell oder mindestens Android 6 mit aktuellen Google Play-Dienste) [Mehr Details](https://www.coronawarn.app/de/faq/#minimum_requirements)"

**Comment by MikeMcC399** [comment]
@dsarkar 
The changes look good.
Should be "Google Play services" without capitalization of services though. 🙂

**Comment by dsarkar** [comment]
@MikeMcC399 OK! Thanks!

**Comment by dsarkar** [comment]
@MikeMcC399 

I think in DE itshould be
"Google Play-Dienste"

**Comment by MikeMcC399** [comment]
@dsarkar 
"Google Play-Dienste" is what I see in German too. 👍
