### ISSUE TITLE
FAQ: Link in EN version of Minimum OS requirements

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#874]
## Where to find the issue

**What are the minimum operating system requirements for my phone?**
https://www.coronawarn.app/en/faq/#minimum_requirements

## Describe the issue

https://www.coronawarn.app/en/faq/#minimum_requirements
**[Apple/iOS]: Why is iOS 13.7 a minimum requirement?**
links to https://www.coronawarn.app/en/faq/#no_risk_update however the title of this entry is **[Google/Android]: My risk status hasn't been updated for over a day. An internet connection was available, what's wrong?**

## Suggested change

In https://www.coronawarn.app/en/faq/#minimum_requirements
change `#no_risk_update` to `#ios135`

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. PR #876

**Comment by Ein-Tim** [comment]
#876 is merged, please close this issue.
