### ISSUE TITLE
FAQ: Typos in "iOS 13.7 bzw iOS 12.5 Mindestvoraussetzung"

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#875]
## Where to find the issue

**[Apple/iOS]: Warum ist iOS 13.7 bzw iOS 12.5 Mindestvoraussetzung?**
https://www.coronawarn.app/de/faq/#ios135

## Describe the issue

These are typos:
- die ältere iPhone Modelle
- Vorraussetzung 
- Apple stellt für die Modelle iPhone SE (1. Generation), iPhone 6s, und neuere Modelle die Betriebssystem Version iOS 13.7 und höher bereit.

## Suggested changes

- ältere => älteren
- Vorraussetzung => Voraussetzung 
- Apple stellt für die Modelle iPhone SE (1. Generation), iPhone 6s, und neuere Modelle die Betriebssystem-Version iOS 13.7 und höher bereit.

Edited thanks to feedback from @ndegendogo .

**Comment by ndegendogo** [comment]
@MikeMcC399 
> die Betriebssystem

Which sentence exactly are you referring to? This one?
> Apple stellt für die Modelle iPhone SE (1. Generation), iPhone 6s, und neuere Modelle die Betriebssystem Version iOS 13.7 und höher bereit

I think they meant something like "die Betriebssystem-Version iOS 13.7" or "die Betriebssystemversion iOS 13.7"
and maybe another suggestion:
"Apple stellt für die Modelle iPhone SE (1. Generation), iPhone 6s sowie für neuere Modelle die Version iOS 13.7 und höhere Versionen ihres Betriebssystems bereit"

**Comment by MikeMcC399** [comment]
@ndegendogo 

Thanks for your comments! I misread it and I think it can be corrected by just adding a hyphen. I'll leave it to @dsarkar to judge how he wants to correct it, since the text is based on PR https://github.com/corona-warn-app/cwa-website/pull/857.

I have adjusted the suggestion above.

**Comment by dsarkar** [comment]
@ndegendogo @MikeMcC399 

As usual by now... great proofreading, great suggestions! Many thanks!

PR https://github.com/corona-warn-app/cwa-website/pull/877
