### ISSUE TITLE
FAQ: Menu cut off on smaller mobile device

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#882]
## Where to find the issue

https://www.coronawarn.app/en/faq/

## Describe the issue

On a small mobile device the menu listing the categories of items in the FAQ list is cut off at the bottom and cannot be scrolled.

![FAQ menu on Nexus 5](https://user-images.githubusercontent.com/66998419/107761846-4fd0ba80-6d2c-11eb-956f-7408ba978360.png)

---

Compare to display with larger window

![FAQ menu on windows](https://user-images.githubusercontent.com/66998419/107761882-64ad4e00-6d2c-11eb-912d-a72eb0d1d300.png)

## Steps to reproduce

Device: Google Nexus 5 emulator API 30 (Android 11) or
Samsung Galaxy A5 (2017) SM-A520F
Browser: Google Chrome

1. Open https://www.coronawarn.app/en/faq/
2. Scroll down until horizontal arrow appears
3. Tap arrow
4. Try to scroll category list to see last item in list which is currently "Resolved". On a smaller mobile device this is not possible.

**Comment by dsarkar** [comment]
@MikeMcC399 ok. @heinezen Any simple solution in your mind?

**Comment by Ein-Tim** [comment]
I noticed another problem with the FAQ menu, i.e. the arrow to open it (@MikeMcC399 let me know if I should rather open a new issue for this).

If you open https://www.coronawarn.app/en/faq/ on an iPhone without a home button, it is not possible to open the menu, using Apple's standard browser, Safari.

Screen recording from an iPhone XR:

https://user-images.githubusercontent.com/67682506/107765890-e607df00-6d32-11eb-83d5-f771797933b7.mp4


As you can see, the arrow can't be clicked, since safari will open its "menu" and the arrow disappears behind it.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
The iPhone / Safari problem should be a separate issue.

**Comment by MikeMcC399** [comment]
Now that the category list has grown in length, more categories are lost off the bottom of a smaller device. With

- Samsung Galaxy A5 (2017) SM-A520F
- Browser: Google Chrome

the last category to be shown is Use. The following, from the bottom of the list after the "Use" entry, are not displayed:
- Risk Assessment
- General
- Open Source
- Privacy and Security
- Resolved

**Comment by MikeMcC399** [comment]
There is nobody assigned to this issue. Considering that the FAQs can be expected to be viewed on a mobile device, there ought to be at least some evaluation of whether this issue can be solved (for instance by making the menu sidebar scrollable).

**Comment by MikeMcC399** [comment]
This issue is no longer reproducible on
- Samsung Galaxy A5 (2017) SM-A520F
- Browser: Google Chrome

It is now possible to scroll down to the last item "Resolved" on https://www.coronawarn.app/en/faq/.

Scrolling also works on
https://www.coronawarn.app/en/screenshots.
