### ISSUE TITLE
FAQ: Link about "How often has the Corona warning app been downloaded so far" is not working, pdf file not on rki page

### ISSUE THREAD

**Issue by BFallert** [corona-warn-app/cwa-website#886]
## Where to find the issue
in the file src/data/faq_de.json
in the section 
`                    {
                        "title": "Wie oft wurde die Corona-Warn-App bisher heruntergeladen? Wie viele TeleTANs wurden ausgegeben?",
                        "anchor": "numbers_RKI",
                        "active": true,
                        "textblock": [
                            "Diese und weitere aktuelle Zahlen stellt das Robert Koch-Institut <a href='https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Kennzahlen.pdf?__blob=publicationFile' target='_blank' rel='noopener noreferrer'> auf seiner Webseite</a> zur Verfügung."
                        ]
                    },
`
## Describe the issue
The link `<a href='https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Kennzahlen.pdf?__blob=publicationFile' target='_blank' rel='noopener noreferrer'>` didn't work. The pdf file is not on the rki page.

## Suggested change

Talk with the RKI, i didn't find the information on there webpage.

**Comment by Ein-Tim** [comment]
I'll fix this, the link is now: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html;jsessionid=041B1E316F2E11A2FB9036CD0E457343.internet082?nn=13490888

**Comment by dsarkar** [comment]
@BFallert Thanks for reporting, @Ein-Tim Many thanks for fixing! Best wishes, DS 

---
Corona-Warn-App Open Source Team
