### ISSUE TITLE
Implement easy end-to-end testing

### ISSUE THREAD

**Issue by dannylinden** [corona-warn-app/cwa-website#89]
To make sure features / hotfixes are didn't break anything I would recommend to implement a simple end-to-end testing system.

For this I would recommend [Cypress](https://www.cypress.io/), which is very straight forward ans easy manageable with npm.

This will also improve the ability to detect bugs faster.

The default test command will run End-To-End tests in a headless electron browser.

As an alternativ tests can also run with chrome or firefox.

I will submit a Pull-Request with the framework and a first test in the next minutes

**Comment by dannylinden** [comment]
PR is ready for review, here an example:

<img width="631" alt="Bildschirmfoto 2020-06-17 um 14 17 14" src="https://user-images.githubusercontent.com/5121876/84867394-49a71300-b0a5-11ea-9130-e3a7cb36f462.png">

**Comment by corneliusroemer** [comment]
Maintainers, your feedback is requested :) @SebastianWolf-SAP @tkowark @jakobmoellersap

**Comment by dannylinden** [comment]
Cause no feedback for 10 day, can I friendly remind? @SebastianWolf-SAP @tkowark @jakobmoellersap @corneliusroemer
