### ISSUE TITLE
FAQ: Missing step to access exposure checks for Google

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#891]
## Where to find the issue

https://www.coronawarn.app/en/faq/#exposure_check and
**My exposure log shows checks for less than 14 days**

Your phone settings display the exposure checks for the last 14 days:
...
Android: 'Settings' -> 'Google' -> 'COVID-19 exposure notifications' -> 'Exposure Checks'

https://www.coronawarn.app/de/faq/#exposure_check
**In den Begegnungsüberprüfungen sind die Aufzeichnungen von weniger als 14 Tagen gespeichert**

Die Einstellungen Ihres Smartphones zeigen die Begegnungsüberprüfungen der letzten 14 Tage an:
...
Android: 'Einstellungen' -> 'Google' -> 'COVID-19-Benachrichtigungen' -> 'Überprüfung auf mögliche Begegnungen'

## Describe the issue

The instructions to access the exposure check log are out of date because Google changed the UI. An extra step, using the three-dot icon, is needed to access the level of the UI where "Exposure checks" can be selected.

Google Exposure Notifications Version: 18210214000
Android Version: 10

## Suggested change

Add the step "three-dot icon" to the instructions. I will submit a PR for these changes.

### EN

Android: 'Settings' -> 'Google' -> 'COVID-19 Exposure Notifications' -> **three-dot icon** -> 'Exposure checks'

### DE

Android: 'Einstellungen' -> 'Google' -> 'COVID-19-Benachrichtigungen' -> **drei-Punkte-Icon** -> 'Überprüfung auf mögliche Begegnungen'

**Comment by dsarkar** [comment]
@MikeMcC399 Many thanks.
