### ISSUE TITLE
FAQ: Contact Journal number of days

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#893]
## Where to find the issue

CWA Android app 1.11.0 upgrade to 1.12.0 Contact Journal
Suggestion for new FAQ article. Related to question https://github.com/corona-warn-app/cwa-app-android/issues/2079#issuecomment-779290518 from @dsarkar about lost entries.

## Describe the issue

The Contact Journal in CWA 1.12.0 keeps track of 15 days. In CWA 1.11.0 the journal lists 14 days.
After updating from 1.11.0 to 1.12.0 then viewing the journal it may look like the data from the first day has been lost. In reality this data was never populated.

So for instance, today Monday, Feb 15, 2021, the Contact Journal shows the earliest day Tuesday, Feb 2, 2021 using CWA Android 1.11.0. Export Entries says: "Kontakte der letzten 14 Tage"

After updating to 1.12.0 the earliest day listed is now Monday, Feb 1, 2021, which is empty of people and places. Export Entries now says: "Kontakte der letzten 15 Tage"

## Suggested change

Explain the change between versions.

**Comment by MikeMcC399** [comment]
@dsarkar 
Do you have any more details about Android users who said they lost Contact Journal data when updating from 1.11.0 to 1.12.0 as you mentioned in https://github.com/corona-warn-app/cwa-app-android/issues/2079#issuecomment-779290518?

Do you think this topic should be an FAQ article or is it too short-lived?

**Comment by dsarkar** [comment]
@MikeMcC399 

1. I will check if there are more occurrences in the PlayStore
2. In the FAQ we don't mention 14 or 15 days, so I think there is no need to adjust something
3. Here 14 days are mentioned https://www.coronawarn.app/en/blog/2020-12-28-corona-warn-app-version-1-10/

**Comment by MikeMcC399** [comment]
@dsarkar 
> Solution: Add sentence in parenthesis (Update: 15 days in version 1.12 and later.) or something similar.

Possibly that should go into the blog announcement for 1.12 as a modification to the existing text? At the moment though I would tend not to change anything unless it turns out to be a big issue.

https://www.coronawarn.app/en/blog/2021-02-10-corona-warn-app-version-1-12/

If they've had encounters with a high or low risk in the past 15 days, users can find the exposure history in the overview of their contact journal after they've selected "Open Journal".

https://www.coronawarn.app/de/blog/2021-02-10-corona-warn-app-version-1-12/

Sofern sie in den vergangenen 15 Tagen Risikobegegnungen hatten, können Nutzer*innen die Begegnungshistorie in der Übersicht ihres Kontakt-Tagebuchs sehen, nachdem sie in der App „Tagebuch öffnen“ gewählt haben.

**Comment by dsarkar** [comment]
@MikeMcC399 Yes, good!

**Comment by dsarkar** [comment]
@MikeMcC399 Feedback is the following: Behaviour is as intended. The log includes past 14 days + current day = 15 entries.

**Comment by MikeMcC399** [comment]
@dsarkar 
I will close this issue, because it was only about creating a new FAQ entry, and it seems this is not necessary.
