### ISSUE TITLE
Hard to understand wording in `#qr_test`

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#899]
## Where to find the issue
https://www.coronawarn.app/de/faq/#qr_test
https://www.coronawarn.app/en/faq/#qr_test

## Describe the issue
The FAQ Entry says that you should report an infection via the hotline if you are tested positive, then it gives advice how to do this.

## Suggested change
We should also explain to the user how to remove the still pending test result, since the user can only enter a TAN after deleting the pending result

## Additional information
PR #900

**Comment by dsarkar** [comment]
@Ein-Tim Good morning, looking forward to your PR!

**Comment by Ein-Tim** [comment]
@dsarkar 

Good morning, PR #900.
