### ISSUE TITLE
FAQ: Trend differences between 7-Day Average and 7-Day Incidence

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#904]
## Where to find the issue
https://www.coronawarn.app/en/faq/#further_details
In-App statistics starting with release 1.11

## Describe the issue
The FAQ article does not explain about the differences between the data and calculation methods between the 7-Day Average and 7-Day Incidence of new infections. A recent issue "Difference in trends for 7-day incidence and 7-day average" https://github.com/corona-warn-app/cwa-documentation/issues/528 could not be answered easily and satisfactorily.

## Suggested change

Consider publishing an explanation.

Here is some raw material that may assist:

### Why are the trends 7-Day Average (Confirmed New Infections) and 7-Day Incidence different?

Three factors may cause differences in the trends displayed:
- data transmission delays from the local health authorities to the Robert Koch Institute (RKI)
- different time-frames for comparison with previous values
- different limits for definition of steady trend

The contributing data is slightly different for the 7-Day Average of new infections compared to the 7-Day Incidence. In addition the 7-Day Average is compared to the same value one week previously, whereas the 7-Day Incidence is compared to the value for the previous day when calculating the trend.

The count of new infections used to calculate the 7-Day Average is based on each day's new data as it is received by RKI. This is different to the calculation of the 7-Day Incidence which bundles the data together according to the date a new infection was reported to the local health authority. Due to reporting chain delays, the date of reporting to the local health authority can be different to the date when the data is received at the RKI.

The data for the 7-Day Average is the sum of the new infections shown each day in the app, for yesterday and the six days previous to that, divided by 7. The count of daily infections is the same number shown on [COVID-19: Fallzahlen in Deutschland und weltweit](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html) in the column "Dif­fe­renz zum Vor­tag" and row "Gesamt". The history of previous days can be extracted from the [Excel file - Gesamtübersicht der pro Tag ans RKI übermittelten Fälle, Todesfälle und 7-Tage-Inzidenzen nach Bundesland und Landkreis (xlsx)](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.xlsx), which is normally updated each working weekday, tab "Fälle-Todesfälle-gesamt" column "Differenz Vortag Fälle".

The 7-Day Incidence is equivalent to the number shown on [COVID-19: Fallzahlen in Deutschland und weltweit](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html) in the column "7-Tage-Inzi­denz" and row "Gesamt" rounded to a whole number. The app value for the 7-Day Incidence can be calculated from the number in the column "Fälle in den letzten 7 Tagen" divided by the nominal population of Germany 83,166,711 multiplied by 100,000.

The trend for the 7-Day Average of Confirmed New Infections compares the equivalent value 7 days earlier and declares it to be upwards-, steady- or downwards-trending depending whether the change oversteps the ±5% mark. It is effectively using 14 days of data for this comparison.

The trend for the 7-Day Incidence, compares the equivalent value one day earlier and declares it to be upwards-, steady- or downwards-trending depending whether the change oversteps the ±1% mark. It is effectively using 8 days of data for this comparison.

## References

[COVID-19: Fallzahlen in Deutschland und weltweit](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html)

"Die Anzahl der Fälle - und deren Differenz zum Vortag - und die Anzahl der Todesfälle beziehen sich auf Fälle, die dem RKI täglich übermittelt werden. Dies beinhaltet Fälle, die am gleichen Tag oder bereits an früheren Tagen an das Gesundheitsamt gemeldet worden sind. Bei den Fällen in den letzten 7 Tagen und der 7-Tage-Inzidenz liegt das Meldedatum beim Gesundheitsamt zugrunde, also das Datum, an dem das lokale Gesundheitsamt Kenntnis über den Fall erlangt und ihn elektronisch erfasst hat."

From Android app [strings.xml#L1367](https://github.com/corona-warn-app/cwa-app-android/blob/a204c6ada1d05ba26ca54c341e69f4ff416f2ca8/Corona-Warn-App/src/main/res/values/strings.xml#L1367) `statistics_explanation_trend_text`

"Trend"

"The arrow direction indicates whether the trend is increasing, decreasing, or remaining steady – that is, demonstrates a deviation of less than 1% compared to the previous day or 5% compared to the previous week. The color indicates this trend as positive (green), negative (red), or neutral (gray). The trend compares the value from the previous day with the value from two days ago or, for the 7-day trends, the average value from the last 7 days with the average value from the 7 days prior to that."

[StatisticsJsonStringObject.java#L30-L31](https://github.com/corona-warn-app/cwa-server/blob/7102a0eb07a334cddc96ce2aaa18590796a1248d/services/distribution/src/main/java/app/coronawarn/server/services/distribution/statistics/StatisticsJsonStringObject.java#L30-L31)
@JsonProperty("infections_effective_7days_avg_trend_5percent")
private Integer infectionsReported7daysTrend5percent;

[StatisticsJsonStringObject.java#L60-L61](https://github.com/corona-warn-app/cwa-server/blob/7102a0eb07a334cddc96ce2aaa18590796a1248d/services/distribution/src/main/java/app/coronawarn/server/services/distribution/statistics/StatisticsJsonStringObject.java#L60-L61)
@JsonProperty("seven_day_incidence_1st_reported_trend_1percent")
private Integer sevenDayIncidenceTrend1percent;

[Aktueller Lage-/Situationsbericht des RKI zu COVID-19](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Gesamt.html) in German version only.
Hinweise zur Datenerfassung und -bewertung

Für die Berechnung der Inzidenzen werden die Daten der Bevölkerungsstatistik des Statistischen Bundesamtes mit Datenstand 31.12.2019 verwendet. Die Berechnung der 7-Tage-Inzidenz erfolgt auf Basis des Meldedatums, also dem Datum, an dem das lokale Gesundheitsamt Kenntnis über den Fall erlangt und ihn elektronisch erfasst hat. Für die heutige 7-Tage-Inzidenz werden die Fälle mit Meldedatum der letzten 7 Tage gezählt.

[Statistisches Bundesamt - Bevölkerungsstand](https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bevoelkerung/Bevoelkerungsstand/Tabellen/zensus-geschlecht-staatsangehoerigkeit-2019.html)
Population 83166711 (estimated)
on 31.12.2019

[COVID-19: Fallzahlen in Deutschland und weltweit](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html) 

[Gesamtübersicht der pro Tag ans RKI übermittelten Fälle, Todesfälle und 7-Tage-Inzidenzen nach Bundesland und Landkreis](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Daten.html)
Die arbeitstäglich aktualisierte Tabelle gibt eine Gesamtübersicht der pro Tag ans RKI übermittelten Fälle und Todesfälle (seit Februar 2020) und 7-Tage-Inzidenzen nach Bundesland (seit Mai 2020) und Landkreis (seit 19.10.2020). Die innerhalb eines Tages ans RKI übermittelten Fallzahlen sind nicht zu verwechseln mit den Fallzahlen nach Meldedatum beim Gesundheitsamt, siehe hierzu FAQ [www.rki.de/covid-19-faq](https://www.rki.de/SharedDocs/FAQ/NCOV2019/gesamt.html) > Fallzahlen und Meldungen > Wie funktioniert der Meldeweg und welche Informationen zu den Erkrankten werden ans RKI übermittelt?

[Gesamtübersicht der pro Tag ans RKI übermittelten Fälle, Todesfälle und 7-Tage-Inzidenzen nach Bundesland und Landkreis (xlsx)](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.xlsx)

**Comment by GisoSchroederSAP** [comment]
Thank you for bringing this all together, @MikeMcC399 .
Great pool of information for those that are interested to dive in.
For the FAQ we may get a bit more abstract, to reach a broader audience and those users that just want to understand the meaning and the implications to their behavior. It's all about balancing both sides. 

I like the summary of references. Maybe we follow this approach and add another note where to find even more "raw" information. Thank you starting this!

**Comment by MikeMcC399** [comment]
The blog posts
- https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/ (EN) "Explanation of the statistic tiles in the Corona-Warn-App"
- https://www.coronawarn.app/de/blog/2021-08-05-statistictiles/ (DE) "Erläuterung der Statistikkacheln in der Corona-Warn-App"
published on Aug 5, 2021, provide detailed explanations about the statistics data.

Closing this issue now. Any comments on the blog post should go into a separate new issue.
