### ISSUE TITLE
FAQ: Publish own entry informing why the `update os` screen is shown (iOS)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#905]
## Where to find the issue
n/a

## Describe the issue
Since version 1.12 it is possible that some users of CWA run into the problem that CWA shows a screen which tells them to update the iOS version. When reading the feedback on the App Store, you can see that the most people don't update the iOS version, but uninstall the app. This should definitely be changed

## Suggested change
Add a FAQ entry explaining why this screen is necessary.

## Related Issues

- https://github.com/corona-warn-app/cwa-app-ios/issues/2032
- https://github.com/corona-warn-app/cwa-app-ios/issues/2045

**Comment by Ein-Tim** [comment]
@dsarkar Could you let me know if you agree that such an FAQ entry should be published, if yes, I've already started to prepare a PR which would introduce this.

<details>
<summary>Suggested text</summary>

DE:

>Dieser Bildschirm wird auf iPhones mit einer iOS-Version zwischen iOS 13.5 und (einschließlich) iOS 13.6.1 angezeigt.  Auf diesen iOS-Versionen ist die verwendete Version 2 des Exposure Notification Frameworks nicht verfügbar, deshalb muss erst auf iOS 13.7 oder neuer aktualisiert werden, um die Corona-Warn-App weiterhin verwenden zu können. Weitere Informationen finden Sie in <a href='../faq/#ios135' target='_blank' rel='noopener noreferrer'>diesem</a> FAQ Eintrag.

EN: 

>This screen is shown on iPhones running an iOS version between iOS 13.5 and (including) iOS 13.6.1. On these iOS Versions, the used version 2 of the Exposure Notification Framework is not availibale, therefore it's necessary to update to iOS 13.7 or newer, to continue on using the Corona-Warn-App. More information can be found in <a href='../faq/#ios135' target='_blank' rel='noopener noreferrer'>this</a> FAQ entry.


</details>

It's just a real short one but I think it's good for users which are asking why they see this screen.

**Comment by heinezen** [comment]
@Ein-Tim I would say this change is okay and you can go ahead and make a PR. This FAQ entry is important, especially if there's no easy fix.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Thanks for the feedback @heinezen 

PR #938
