### ISSUE TITLE
BReg FAQ English articles link to German CWA FAQ

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#913]
## Where to find the issue
https://www.bundesregierung.de/corona-warn-app-faq-englisch referred to by the FAQ link `main_about_link` in the CWA app.

Open issues reviewed for page status date:
~~Wednesday, 10. February 2021~~ 
~~Monday, 1. March 2021~~
~~Wednesday, 24. March 2021~~
~~Wednesday, 21. April 2021~~
~~Monday, 3. May 2021~~
Thursday, 10. June 2021

This issue is carried over from https://github.com/corona-warn-app/cwa-website/issues/711.

## Describe the issue

The English language version of the FAQs https://www.bundesregierung.de/corona-warn-app-faq-englisch links to the German language version of the CWA FAQ https://www.coronawarn.app/de/faq/ in the body of two FAQ articles.

## Steps to reproduce

1. Open https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636
2. Scroll down to "What are the minimum device requirements?" and expand the article by clicking on the ➕ sign.
3. Note the link to https://www.coronawarn.app/de/faq/
4. Scroll down to "How are data security and data protection ensured for the Corona-Warn-App?" and expand the article by clicking on the ➕ sign.
5. Note the link to https://www.coronawarn.app/de/faq/

## Suggested change

The FAQ articles on https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636
- "What are the minimum device requirements?"
- "How are data security and data protection ensured for the Corona-Warn-App?"

should be linked to the English language FAQ https://www.coronawarn.app/en/faq/

---
Internal Tracking ID: [EXPOSUREAPP-4481](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4481)

**Comment by MikeMcC399** [comment]
Unfortunately this issue has not been addressed.

In fact, the update Wednesday, 24. March 2021 to the website of the Bundesregierung introduced additional links from the English-language page https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636 to the German-language section of https://www.coronawarn.app/.

https://www.coronawarn.app/de/faq/
should be https://www.coronawarn.app/en/faq/

https://www.coronawarn.app/de/faq/#interoperability_countries
should be https://www.coronawarn.app/en/faq/#interoperability_countries

**Comment by MikeMcC399** [comment]
Although the site https://www.bundesregierung.de/corona-warn-app-faq-englisch  has been modified multiple times since this issue was submitted, the problem of linking to the wrong language version of the FAQs has not been addressed.

There is also a new typo on this page linking to https://github.com/corona-warn-app/ where the text says `ttps://github.com/corona-warn-app/` (missing the h in https) in the section which describes the CWA 2.0 update.

**Comment by MikeMcC399** [comment]
Checking today on the status of the English-language page https://www.bundesregierung.de/corona-warn-app-faq-englisch 

- The page has been updated to include information about 2.1, however strangely the status date at the bottom of the page still says "Wednesday, 21. April 2021"), although 2.1 was released yesterday, May 2, 2021.
- The FAQ link is still to the wrong language https://www.coronawarn.app/de/faq/ instead of https://www.coronawarn.app/en/faq/ in more than one place.
- The phone number still needs updating (see https://github.com/corona-warn-app/cwa-website/issues/1003).
- The typo mentioned in the previous post `ttps://github.com/corona-warn-app/` has been fixed.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks, I updated the internal ticket!

**Comment by MikeMcC399** [comment]
Despite multiple updates to the website of the Bundesregierung https://www.bundesregierung.de/corona-warn-app-faq-englisch over a period of 5 months, the original problem described in this issue report #913 has not been fixed:

"The English language version of the FAQs https://www.bundesregierung.de/corona-warn-app-faq-englisch links to the German language version of the CWA FAQ https://www.coronawarn.app/de/faq/ in the body of two FAQ articles."

Closing this issue due to lack of effective response over a long period of time.
