### ISSUE TITLE
FAQ: Change from 10 minute contact duration to 5 minutes

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#914]
## Where to find the issue

**EN**
https://www.coronawarn.app/en/faq/#encounter_but_green
https://www.coronawarn.app/en/faq/#encounter_count_19
https://www.coronawarn.app/en/faq/#encounter_19_calc

**DE**
https://www.coronawarn.app/de/faq/#encounter_but_green
https://www.coronawarn.app/de/faq/#encounter_count_19
https://www.coronawarn.app/de/faq/#encounter_19_calc

## Describe the issue

According to https://www.coronawarn.app/en/blog/2021-02-23-corona-warn-app-risk-calculation-optimization/ the filter for considering contacts in the risk calculation was reduced from 10 minutes to 5 minutes starting Feb 23, 2021.

Several FAQ articles refer to the old 10 minute limit.

## Suggested change

- Either replace the 10 minute value with the 5 minute value or
- add a note such as "(reduced to 5 minutes on Feb 23, 2021)" next to the original 10 minute text.

**Comment by dsarkar** [comment]
(reduced to 5 minutes on Feb 23, 2021, see <a href='../blog/2021-02-23-corona-warn-app-risk-calculation-optimization/' target='_blank' rel='noopener noreferrer'>blog post</a>)

**Comment by dsarkar** [comment]
(reduziert auf 5 Minutes am 23 Feb. 2021, siehe <a href='../blog/2021-02-23-corona-warn-app-risk-calculation-optimization/' target='_blank' rel='noopener noreferrer'>Blogartikel</a>)

**Comment by dsarkar** [comment]
@MikeMcC399 FYI - PR ready for review.
