### ISSUE TITLE
FAQ - update times 10 -> 5 min

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#915]
## Where to find the issue

https://www.coronawarn.app/de/faq/?search=Benachrichtigungen#encounter_but_green
https://www.coronawarn.app/en/faq/?search=Benachrichtigungen#encounter_but_green

## Describe the issue

says 10 min

## Suggested change

should be 5 min

see
https://www.coronawarn.app/de/blog/2021-02-23-corona-warn-app-risk-calculation-optimization/

**Comment by MikeMcC399** [comment]
@dsarkar 
You've just duplicated my issue https://github.com/corona-warn-app/cwa-website/issues/914 😄 that I posted earlier today!

**Comment by dsarkar** [comment]
@MikeMcC399 Sorry !
