### ISSUE TITLE
Release 1.13 - Update FAQ

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#921]
## Where to find the issue

https://www.coronawarn.app/en/faq/
## Describe the issue

**Release 1.13**
Update FAQ articles, if necessary:

1. alignment of red and green card, date also shown on green card
https://www.coronawarn.app/en/faq/#encounter_criteria
2. Negative test result -> Terminate quarantine, resume exposure checks and delete test
https://www.coronawarn.app/en/faq/#test_negative
3. contact diary in a separate tab bar, and enhancements
https://www.coronawarn.app/en/faq/#contact_diary
4. Data Donation 
no article yet
5. High-risk encounter - there is now in the app a link to FAQ https://www.coronawarn.app/en/faq/#red_card_how_to_test and RKI survey

**Comment by Ein-Tim** [comment]
@dsarkar 

It seems like that there should be screenshots published on 
https://www.coronawarn.app starting with 1.13. (See for example the screenshot in [this](https://github.com/corona-warn-app/cwa-app-ios/pull/2083) PR). 

Do you know where these screenshot should be published? In a blog post?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
The PR https://github.com/corona-warn-app/cwa-app-ios/pull/2083, which you quoted, is merging into release/1.14.x not into the 1.13 release.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks, I have mixed this up, although the milestone and the branch is 1.14, the title talks about version 1.13. 
[This](https://github.com/corona-warn-app/cwa-app-ios/pull/1878/files) is the PR which added the texts for the 1.13 release.

Sorry, next time I'll double check 🤪

**Comment by MikeMcC399** [comment]
@Ein-Tim 
The details were confusing, as the title version did not match the merge version, and the PR did not change anything about screen shots. It was more about a misnomer.

**Comment by MikeMcC399** [comment]
@dsarkar 

The announcement of the release 1.13 in https://www.coronawarn.app/en/blog/2021-02-26-corona-warn-app-1-13-announcement/ has been removed.

What is the plan now?

**Comment by Ein-Tim** [comment]
[This](https://www.coronawarn.app/en/faq/#recovered) FAQ entry has to be updated too, since version 1.13 will introduce a new "End of life"-behavior. 
(See f.e. this PR: https://github.com/corona-warn-app/cwa-app-ios/pull/1960)

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim 

> What is the plan now?

Standby please, there should be an official announcement soon. Good night!

**Comment by MikeMcC399** [comment]
Here is the official announcement
https://www.coronawarn.app/en/blog/2021-03-04-corona-warn-app-version-1-13/

**Comment by Ein-Tim** [comment]
I think we can close this now, or?

**Comment by dsarkar** [comment]
@Ein-Tim Indeed, Thanks.
