### ISSUE TITLE
FAQ 2001

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#925]
## Where to find the issue

FAQ 2001

https://www.coronawarn.app/en/faq/#cause2001
https://www.coronawarn.app/de/faq/#cause2001

## Describe the issue

![image](https://user-images.githubusercontent.com/1409741/110118966-6dd58c00-7dbb-11eb-8fe3-7639cad1cc75.png)

## Suggested change

see https://github.com/corona-warn-app/cwa-app-android/issues/968#issuecomment-787214377

restart might be necessary..

---
Internal Tracking ID: [EXPOSUREAPP-14426](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14426)

**Comment by dsarkar** [comment]
Suggestion based on user comment corona-warn-app/cwa-app-android#968 (comment):
Add fourth bullet point:

"
- In some cases, it is necessary to restart the device
"

**Comment by amouzayanni** [comment]
Hello! I see that the FAQ posts have already been updated to inform users of the firewall settings fix, but not of the restart and mobile data fixes. If you'd like me add them then I'd be glad to help.

**Comment by Ein-Tim** [comment]
@amouzayanni I think you can go ahead and add this information to the FAQ, I (as a community contributor) don't see any points speaking against this. 

An "official" statement from @dsarkar or another member of the @Open-Soruce-Team would still be good.

**Comment by amouzayanni** [comment]
Sorry for the late response on my end! Just want to clarify that I'm no longer going to work on this issue.

**Comment by larswmh** [comment]
> An "official" statement from @dsarkar or another member of the @Open-Soruce-Team would still be good.

We think that the missing information can be added to the FAQ. I will prepare a PR soon.
