### ISSUE TITLE
FAQ - update - How do I tell the app that I recovered from COVID-19?

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#932]
## Where to find the issue

https://www.coronawarn.app/en/faq/#recovered

## Describe the issue

Process changes with version 1.13

**Comment by Ein-Tim** [comment]
We should consider to move this entry to the solved section when 1.13 is released, I think that the app now better explains itself how to reactivate the risk calculation. 
(iOS PR with Screen shots: https://github.com/corona-warn-app/cwa-app-ios/pull/1960) 
But maybe we should also add a comment to the entry which informs that 1.13 has changed the behavior.

**Comment by Ein-Tim** [comment]
@dsarkar 

Will you create a PR for this?

**Comment by Ein-Tim** [comment]
@dsarkar 

Pls close, didn't close automatically.
