### ISSUE TITLE
Opening FAQ page shows "Support", "News" & "Event Check-In" as active in the menu

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#951]
## Where to find the issue
https://www.coronawarn.app/de/faq/
https://www.coronawarn.app/en/faq/

## Describe the issue
When opening the FAQ page, the menu on the left-hand side shows that "Support", "News" & "Event Check-In" are the active (blue line on the left-hand side of the text) categories.
<img width="1407" alt="Ohne Titel" src="https://user-images.githubusercontent.com/67682506/115893958-0a7de700-a459-11eb-9bff-335f15ec843b.png">

## Suggested change
Only show "Support" as active category.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
The marker to the left of the category seems to be intended to show which category the browser is currently displaying.
Try scrolling down and you see that the marker moves down too. Now scroll back up to the top and the marker doesn't scroll up to the Support issue. Instead it gets stuck on "Common Issues" (viewing on a larger Google Chrome desktop screen). On a smaller mobile device, also viewing using Google Chrome it gets stuck on "News".

The issue https://github.com/corona-warn-app/cwa-website/issues/882 is also about this category handling too.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I understand what the marker is doing, but IMHO there should (in my case) only one marker next to "Support" and not also to "News". On larger screens this can be different since it's possible that two categories are shown.

**Comment by Ein-Tim** [comment]
This has been fixed by [`a2f649d` (#1340)](https://github.com/corona-warn-app/cwa-website/pull/1340/commits/a2f649db4371d1a99aa3e24fb9f633debfdecb13).

Closing as solved.
