### ISSUE TITLE
FAQ: Firewall setting for Event-driven User Surveys (EDUS)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#952]
## Where to find the issue

**[Google/Android]: Firewall/Router configuration: CAUSE: 4000, error during web request, HTTP status 901**
https://www.coronawarn.app/en/faq/#access-list

**[Google/Android]: Firewall/Router Konfiguration: URSACHE: 4000, error during web request, HTTP status 901**
https://www.coronawarn.app/de/faq/#access-list

## Describe the issue

The domains listed in the Firewall advice (see links above) are:

- *.coronawarn.app
- *.t-online.de

The domain *.rki.de is not listed and it seems this is necessary for the Event-driven User Surveys (EDUS) according to the verbose logging I'm seeing in CWA Android 1.13.2 Logcat, which shows a configuration parameter
`surveyOnHighRiskUrl=https://befragungen.rki.de/CWABasisbefragung` 

The parameter is also to be seen in the server configuration file [application.yaml](https://github.com/corona-warn-app/cwa-server/blob/main/services/distribution/src/main/resources/application.yaml).

## Suggested change

Please check that access to `https://befragungen.rki.de` is necessary.

Add 
`*.rki.de`
to the list of domains in
- https://www.coronawarn.app/en/faq/#access-list
- https://www.coronawarn.app/de/faq/#access-list

Also, test what happens if a firewall blocks access to this URL. If the error 
`CAUSE: 4000, error during web request, HTTP status 901`
is not the outcome, then it might be necessary to reword the document including the title.

---
Internal Tracking ID: [EXPOSUREAPP-1906](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-1906)

**Comment by Ein-Tim** [comment]
@MikeMcC399 

The site https://befragungen.rki.de/CWABasisbefragung checks your browser with https://www.howsmyssl.com/ (see https://befragungen.rki.de/browsercheck), so probably this site would also have to be whitelisted, or is this process completely independent from the app?

Just btw, is the survey only in German?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Good point about https://www.howsmyssl.com/ ! I didn't notice this. I can see this URL also being used when I look at the network traffic. Perhaps the prerequisites for using the survey need to be a new separate FAQ?

> Just btw, is the survey only in German?
I don't know about this. There is a link at the top right to change between English and German though. You have to be authorized by the app to take part in the survey which only happens if you reach a red risk status, so I can't try it out.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks! We will bring this to the developers for clarification. So, in short:

For the RKI survey routers should include in their domains access-list (apparently we shall not use the word whitelist):
- *.rki.de
- *howsmyssl.com

?

**Comment by MikeMcC399** [comment]
@dsarkar 
Thank you! The term these days is now "allowlisted", but in fact the current FAQ words it differently anyway:
"... make sure to include the following domains in the access-list ..." / "... die folgenden Domains in der Access-Liste ..."
which is fine.

**Comment by Ein-Tim** [comment]
Sorry for the wrong term, changed it in my comment (and learned something new, did not know this yet 😅😀).

Let's wait what the devs say?

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim ;-) Yes, I wasn´t aware neither. When we created the error 2001 FAQ entry, we were told to change the word.

**Comment by dsarkar** [comment]
actually, I mean the error 4000 FAQ (not 2001)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-1906](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-1906)

**Comment by MikeMcC399** [comment]
> Internal Tracking ID: [EXPOSUREAPP-1906](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-1906)
