### ISSUE TITLE
FAQ: Add instructions to find ENS version through app

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#954]
## Where to find the issue

**[Google/Android]: Which version of the COVID-19 Exposure Notifications System is currently installed?**
https://www.coronawarn.app/en/faq/#ENF_version

**[Google/Android]: Welche Version der COVID-19-Benachrichtigungen habe ich?**
https://www.coronawarn.app/de/faq/#ENF_version

## Describe the issue

The instructions for determining the installed version of the Google Exposure Notifications System on Android do not include how to find this out directly in the Corona-Warn-App itself. 

There was a bug in 1.12.0 which prevented scrolling down to the ENS version number on small screens - see https://github.com/corona-warn-app/cwa-app-android/issues/2302. This has been fixed in the CWA 1.13.2 release, which means it would now be good to update the FAQ instructions accordingly.

Here is an example of where the version number is displayed:

![App Information 1 13 2 Nexus 5](https://user-images.githubusercontent.com/66998419/110235631-8bc4fd00-7f31-11eb-8652-5fc53364ebbd.png)

## Suggested change

- Describe how to access the ENS version number through CWA.
- Move the description about how to use the Google UI to a secondary position in the description.

I will submit a PR for this change.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> There was a bug in 1.12.0 which prevented scrolling down to the ENS version number on small screens - see https://www.coronawarn.app/de/faq/#ENF_version. This has been fixed in the CWA 1.13.2 release, which means it would now be good to update the FAQ instructions accordingly.

I think the link there should be https://github.com/corona-warn-app/cwa-app-android/issues/2302. 

However, very good catch! Why complicated if it goes easy? 😀

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for spotting my paste mistake, which I corrected now.

**Comment by heinezen** [comment]
@MikeMcC399 See https://github.com/corona-warn-app/cwa-website/pull/955

(Sry I didn't see that you want to make a PR until just now.)

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 
I would prefer if you let me suggest the changes, which I have already done in draft form. I haven't pushed them yet though.

Your PR #955 deletes a lot of information that I found quite useful in the past, so I would be sorry to see that go for the sake of other people who might also find it useful.

The Google Android environment is quite different to the iOS environment, because the Google ENS is updated independently of the Android operating system. Not only that, the behavior of the Google ENS is controlled by dynamic parameters set by Google, for instance to change the UI appearance.

In iOS the ENF software is just part of the OS update, so if you know what iOS version is installed then you know what ENF version you have installed.

**Comment by dsarkar** [comment]
@MikeMcC399 OK, we will wait for your PR! Thanks!

**Comment by MikeMcC399** [comment]
PR #958 submitted.
