### ISSUE TITLE
Specify screenshot versions

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#965]
## Where to find the issue

Screenshots
https://www.coronawarn.app/en/screenshots/
https://www.coronawarn.app/de/screenshots/

## Describe the issue
The screenshots pages refer only to the "current release" without a specific version number.

## Suggested change

Add the version number for Android and iOS to the text:

"Browse through the screenshots to get an overview of the features that Corona-Warn-App offers in the current release."

"Verschaffen Sie sich mithilfe von Screenshots einen Überblick über die Funktionen, die die Corona-Warn-App im aktuellen Release bietet."

**Comment by dsarkar** [comment]
@MikeMcC399 see https://github.com/corona-warn-app/cwa-website/pull/1208

**Comment by MikeMcC399** [comment]
@dsarkar 
Thank you for adding the version number! Since the issue has been addressed, I will now close.
