### ISSUE TITLE
New Android version number 1.14.0 or 1.14.3?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#966]
@svengabr 
See closed PR https://github.com/corona-warn-app/cwa-website/pull/964

## Your Question
https://www.coronawarn.app/en/ says
"Download the current version of the app (iOS: 1.14.0 or Android: 1.14.0)"

and on https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.14.3

the release is 1.14.3 for Android.

Could you check if the website needs updating to 1.14.3, instead of 1.14.0?

**Comment by Ein-Tim** [comment]
Same for iOS.

**Comment by Ein-Tim** [comment]
Hope this PR is ok and you didn't want to provide it (: @MikeMcC399

**Comment by MikeMcC399** [comment]
@Ein-Tim 

No problem. I just want @svengabr to take care, because I never know exactly what is going on in the background with the releases. Also I don't really look at iOS.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Okay, understandable. Have a nice evening and sorry again 😅😀
