### ISSUE TITLE
Typo(s) in 1.14 announcement (EN)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#969]
## Where to find the issue

https://www.coronawarn.app/en/blog/2021-03-09-corona-warn-app-version-1-14/

## Describe the issue

The sentence:

"They can also specify whether they’ve met another person for more than 15 minutes or less, whether they wore a mask during the meeting, and whether they were outside our indoors."

is not right.

"our" is wrong
"outside" does not correspond to screenshot

Also in

"Under both, locations and people, users can also add their own notes."

It is confusing to place a comma after "both" in the above.

## Suggested change

Change to "outdoors or indoors".

Remove the comma after "both".

PS Let me know if you want me to submit a PR to correct these two issues.

---
Internal Tracking ID: [EXPOSUREAPP-5070](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5070)

**Comment by dsarkar** [comment]
@MikeMcC399 I will check if they will accept you offer.

**Comment by dsarkar** [comment]
[EXPOSUREAPP-5070](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5070)

**Comment by MikeMcC399** [comment]
@HannaHei 

Are you planning to correct the typos in the 1.14 announcement (English version) soon?

The nonsensical sentence:

"They can also specify whether they’ve met another person for more than 15 minutes or less, whether they wore a mask during the meeting, and whether they were **outside our indoors**."

still appears on https://www.coronawarn.app/en/blog/2021-03-09-corona-warn-app-version-1-14/.

**Comment by dsarkar** [comment]
@MikeMcC399 I forward it to the ticket.

**Comment by Ein-Tim** [comment]
The "our" has been fixed in #982

**Comment by MikeMcC399** [comment]
@dsarkar / @HannaHei 

Both issues I described are fixed. 

Thank you!
