### ISSUE TITLE
Add app installation counter to website

### ISSUE THREAD

**Issue by pozoo** [corona-warn-app/cwa-website#97]
## Feature description
Add an actual counter for the number of installed apps to the website.

## Problem and motivation

A lot of people are probably interested in this number, because it also gives an indication of how much of a difference the app can possibly make. 
I know this can be roughly seen in the play store but the granularity decreases with increasing installs (next value above 10M is 50M). I think this info is not public in the AppStore at all. 

It would probably motivate people to install the app if they see how many others have already  installed it as well and could be shared on social media to motivate others.

## Is this something you're interested in working on
This can only be done by people with access to the publisher accounts in the AppStores

**Comment by tens0rfl0w** [comment]
Please see this [link](https://www.rki.de/SharedDocs/Bilder/InfAZ/neuartiges_Coronavirus/WarnApp/WarnAppDownloadzahl.jpg) for the daily installation numbers.
Numbers from yesterday:
<img src="https://www.rki.de/SharedDocs/Bilder/InfAZ/neuartiges_Coronavirus/WarnApp/WarnAppDownloadzahl.jpg?__blob=normal&v=9"/>

**Comment by tkowark** [comment]
We leave the sharing of this information to the app publisher (RKI) and focus on the open source project on this page.
