### ISSUE TITLE
FAQ ENError 13 - remove version number

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#980]
## Where to find the issue

https://www.coronawarn.app/en/faq/#ENError13
https://www.coronawarn.app/de/faq/#ENError13

## Suggested change

UPDATE 12.03.2021: 

If you updated the Corona-Warn-App to the newest version, some users may receive the following error message: "Error 13: Your exposure logging for today has already been carried out. Please try again in 24 hours."

The Corona-Warn-App is functioning correctly despite this message. If you have any further problems in this context, you can describe your problem in detail here: corona-warn-app/cwa-app-ios-1715

[EXPOSUREAPP-5744](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5744)

**Comment by Ein-Tim** [comment]
@dsarkar 

I suggest to remove everything but 

> The ENErrorDomain 13 error is thrown by Apple's Exposure Notification System, which is used by the Corona-Warn-App. It is the information that on this day, an exposure check already took place. Please restart your phone and do not open the app for 24 hours. Then, the next exposure identification takes place and this information should no longer be displayed. Please do not remove and reinstall the Corona-Warn-App, as it still works as intended.

since this includes the most important information.

**Comment by dsarkar** [comment]
@Ein-Tim I think a restart is not required. I will test.

**Comment by Ein-Tim** [comment]
Thanks @dsarkar 

And btw I could provide a PR for this today afternoon, if you aren't already on it.

**Comment by dsarkar** [comment]
@Ein-Tim ok, thank you, go ahead with the PR. Lets, clean that up. Remove all unnecessary, please. And copy and paste the actual json entry to the end of FAQ using the anchor #ENError13**_old** or similar. We will move that away later.

**Comment by Ein-Tim** [comment]
@dsarkar 

So that it's in the "Resolved" category? 
Don't forget that the iOS app links to this entry so we shouldn't change the link.

**Comment by Ein-Tim** [comment]
@dsarkar I would also change the title of the FAQ entry so that it reflects the message which is shown in app:

**Comment by Ein-Tim** [comment]
Suggestion English:
<img width="822" alt="Suggestion Error 13 EN" src="https://user-images.githubusercontent.com/67682506/110956232-b60c2580-834a-11eb-8cdf-4fc06654cbb2.png">

Suggestion German:
<img width="828" alt="Suggestion Error 13 DE" src="https://user-images.githubusercontent.com/67682506/110957913-67f82180-834c-11eb-8452-d1c7e4b78512.png">
