### ISSUE TITLE
Link to QR error codes in blog now incorrect

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#986]
## Where to find the issue

**QR Code scanned but no test result in the Corona-Warn-App**
https://www.coronawarn.app/en/blog/2020-08-25-notes-qr-codes/

and 
**QR-Code gescannt aber kein Testergebnis in der Corona-Warn-App**
https://www.coronawarn.app/de/blog/2020-08-25-notes-qr-codes/

used by 
https://www.coronawarn.app/en/faq/#who_can_help and 
https://www.coronawarn.app/de/faq/#who_can_help. 

## Describe the issue

In the sentence from the [blog](https://www.coronawarn.app/en/blog/2020-08-25-notes-qr-codes/) the first link is no longer correct:

"In some cases, **[error messages](https://www.coronawarn.app/en/faq/#qr_test)** appear, in others the [test result cannot be retrieved](https://www.coronawarn.app/en/faq/#qr_test)."

### Detailed description

Since the blog entry [QR Code scanned but no test result in the Corona-Warn-App](https://www.coronawarn.app/en/blog/2020-08-25-notes-qr-codes/) was published on Aug 25, 2020 the QR entry in the FAQ [#qr_test](https://www.coronawarn.app/en/faq/#qr_test) has been split into two separate articles:

**I get an error while scanning the QR code. What can I do?**
[#qr_scan](https://www.coronawarn.app/en/faq/#qr_scan)

and 

**I have scanned a QR code, but the test result could not be retrieved for days.**
[#qr_test](https://www.coronawarn.app/en/faq/#qr_test)

## Suggested change

**EN**
In https://www.coronawarn.app/en/blog/2020-08-25-notes-qr-codes/ change
"In some cases, [error messages](https://www.coronawarn.app/en/faq/#qr_test) ..."
to link to [#qr_scan](https://www.coronawarn.app/en/faq/#qr_scan).

**DE**
In https://www.coronawarn.app/de/blog/2020-08-25-notes-qr-codes/ change
"In some cases, [error messages](https://www.coronawarn.app/de/faq/#qr_test) ..."
to link to [#qr_scan](https://www.coronawarn.app/de/faq/#qr_scan).

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/987 submitted to correct this issue.

**Comment by dsarkar** [comment]
@MikeMcC399 ok! Thanks!
