### ISSUE TITLE
General feedback on handling PRs and issues

### ISSUE THREAD

**Issue by eyecatchup** [corona-warn-app/cwa-website#99]
I was a bit disappointed, when I saw that @SebastianWolf-SAP [commited a change](https://github.com/corona-warn-app/cwa-website/commit/e3b7ce442db50e457cd09d945510922162c777e9) to add [a new feature that was requested as an issue](https://github.com/corona-warn-app/cwa-website/issues/71). However, I already created [a PR to address this issue](https://github.com/corona-warn-app/cwa-website/pull/92) (with a more generic and scalable solution) a few hours before his change. Ultimately, the change created a merge conflict for my PR.

So, please comment on issues / feature requests, when you put it in your backlog for you to implement / fix by yourself. That way, contributors will not work on stuff you already work on. On the other hand, please review PRs first, before you start implementing stuff, which may have been already implemented by contributors. 

Thanks for helping us helping you.

**Comment by corneliusroemer** [comment]
Very good point. I think in general, the community side of the project needs better support by maintainers. Can you maybe add extra personnel for this, maintainers?

**Comment by SebastianWolf-SAP** [comment]
I'm terribly sorry for that - I was simply updating the FAQ while remembering that deep-linking was requested in another thread. It seems that I simply started the fix without checking all issues and PRs and therefore I also didn't report on the issue.

However, we need to have stable links, even if the header changes, so sorry that I can't accept #92.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by corneliusroemer** [comment]
@SebastianWolf-SAP All good, no need to apologise. But don't you think it would help if you had one or two extra people working full-time on community support? This is nothing personal at all. This is getting a lot of attention right now, especially after launch and it's of course impossible to do it with the same number of people as before launch.
